<?php

/**
 * Implementation of hook_badges()
 *
 * @return array
 */
function badges_statistics_badges()
{
  $badges = array();

  $badges['statistics_bronze'] = array(
    'function' => 'badges_statistics_check',
    'name' => t('Notable Issue'),
    'info' => t('Posted issue with 1,000 views'),
    'type' => 'bronze',
    'arguments' => array('views' => 1000),
  );
  $badges['statistics_silver'] = array(
    'function' => 'badges_statistics_check',
    'name' => t('Popular Issue'),
    'info' => t('Posted issue with 2,500 views'),
    'type' => 'silver',
    'arguments' => array('views' => 2500),
  );
  $badges['statistics_gold'] = array(
    'function' => 'badges_statistics_check',
    'name' => t('Provocative Issue'),
    'info' => t('Posted issue with 10,000 views'),
    'type' => 'gold',
    'arguments' => array('views' => 10000),
  );

  $badges['statistics_tumbleweed'] = array(
    'function' => 'badges_statistics_tumbleweed_check',
    'name' => t('Tumbleweed'),
    'info' => t('Asked a question with no answers, no comments, and low views for a week'),
    'arguments' => array('views' => 10, 'days' => 7),
  );

  return $badges;
}

/**
 * @param $uid
 * @return bool
 */
function badges_statistics_check($uid, $arguments = array())
{
  static $cache;

  if (is_null($cache)) {
    $cache = array();

    $result = db_query("SELECT n.uid, MAX(nc.totalcount) count FROM {node} n LEFT JOIN {node_counter} nc ON n.nid = nc.nid GROUP BY n.uid");
    while ($row = db_fetch_array($result)) {
      $cache[$row['uid']] = $row['count'];
    }
  }

  return isset($cache[$uid]) ? $cache[$uid] >= $arguments['views'] : false;
}

/**
 * @param $uid
 * @return bool
 */
function badges_statistics_tumbleweed_check($uid, $arguments = array())
{
  static $cache;

  if (is_null($cache)) {
    $cache = array();

    $result = db_query("SELECT n.uid, DATEDIFF(CURDATE(), FROM_UNIXTIME(n.created, '%Y-%m-%d')) days, IFNULL(nc.totalcount, 0) views FROM {node} n LEFT JOIN {node_counter} nc ON n.nid = nc.nid WHERE n.type = '%s'", 'poll');
    while ($row = db_fetch_array($result)) {
      $cache[$row['uid']][] = array('days' => $row['days'], 'views' => $row['views']);
    }
  }

  if (isset($cache[$uid])) {
    foreach (isset($cache[$uid]) as $data) {
      if (($data['views'] <= $arguments['views']) && ($data['days'] >= $arguments['days'])) {
        return true;
      }
    }
  }

  return false;
}