<?php
/**
 * Implementation of hook_perm().
 */
function mashup_perm() {
  return array('Create Mash Up');
}


/**
 * Implementation of hook_menu().
 */
 
function mashup_menu() {	

$items['mashup'] = array(
    'title' => ' Mashup',
    'page callback' => 'createMashup',
	'page arguments' => array(1),
    'access arguments' => array('Create Mash Up'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'mashup.pages.inc',
  );
 $items['mashup/save'] = array(
    'title' => ' Mashup Save',
    'page callback' => 'mashupSave',
    'access arguments' => array('Create Mash Up'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'mashup.pages.inc',
  );
 $items['mashup/confrim'] = array(
    'title' => ' Mashup',
    'page callback' => 'mashupConfrim',
    'access arguments' => array('Create Mash Up'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'mashup.pages.inc',
  );
$items['mashup/xml'] = array(
    'title' => ' Mash Up Xml',
    'page callback' => 'mashupXML',
	'page arguments' => array(2),
    'access arguments' => array('Create Mash Up'),
    'type' => MENU_CALLBACK,
    'file' => 'mashup.pages.inc',
  );
 
 
  return $items;
}

	
	