<?php

function location_province_list_yt() {
  return array(
    "97601" => "Acoua",
    "97602" => "Bandraboua",
    "97603" => "Bandrele",
    "97604" => "Bouéni",
    "97605" => "Chiconi",
    "97606" => "Chirongui",
    "97607" => "Dembeni",
    "97608" => "Dzaoudzi",
    "97609" => "Kani-Kéli",
    "97610" => "Koungou",
    "97613" => "M'Tsangamouji",
    "97611" => "Mamoudzou",
    "97612" => "Mtsamboro",
    "97614" => "Ouangani",
    "97615" => "Pamandzi",
    "97616" => "Sada",
    "97617" => "Tsingoni",
  );
}
