<?php

function location_province_list_uz () {
	return array (
		"AN" => t("Andijan"),
		"BU" => t("Bukhara"),
		"FA" => t("Fergana"),
		"JI" => t("Jizzakh Province"),
		"QR" => t("Karakalpakstan"),
		"QA" => t("Kashkadarya Province"),
		"NG" => t("Namangan Province"),
		"NW" => t("Navoiy Province"),
		"SA" => t("Samarqand Viloyati"),
		"SI" => t("Sirdaryo"),
		"SU" => t("Surxondaryo Viloyati"),
		"TK" => t("Toshkent Shahri"),
		"TO" => t("Toshkent Viloyati"),
		"XO" => t("Xorazm Viloyati"),
	);
}
