<?php

function location_province_list_bi() {
  return array(
    "BB" => t("Bubanza Province"),
    "BM" => t("Bujumbura Mairie Province"),
    "BL" => t("Bujumbura Rural Province"),
    "BR" => t("Bururi Province"),
    "CA" => t("Cankuzo Province"),
    "CI" => t("Cibitoke Province"),
    "GI" => t("Gitega Province"),
    "KR" => t("Karuzi Province"),
    "KY" => t("Kayanza Province"),
    "KI" => t("Kirundo Province"),
    "MA" => t("Makamba Province"),
    "MU" => t("Muramvya Province"),
    "MY" => t("Muyinga Province"),
    "NG" => t("Ngozi Province"),
    "MW" => t("Province de Mwaro"),
    "RT" => t("Rutana Province"),
    "RY" => t("Ruyigi Province"),
  );
}
