<?php

function location_province_list_ve() {
  return array(
    "Y" => "Delta Amacuro",
    "W" => "Dependencias Federales",
    "A" => "Distrito Federal",
    "Z" => "Estado Amazonas",
    "B" => "Estado Anzoátegui",
    "C" => "Estado Apure",
    "D" => "Estado Aragua",
    "E" => "Estado Barinas",
    "F" => "Estado Bolívar",
    "G" => "Estado Carabobo",
    "H" => "Estado Cojedes",
    "I" => "Estado Falcón",
    "J" => "Estado Guárico",
    "K" => "Estado Lara",
    "M" => "Estado Miranda",
    "N" => "Estado Monagas",
    "L" => "Estado Mérida",
    "O" => "Estado Nueva Esparta",
    "P" => "Estado Portuguesa",
    "S" => "Estado Táchira",
    "U" => "Estado Yaracuy",
    "V" => "Estado Zulia",
    "R" => "Sucre",
    "T" => "Trujillo",
    "X" => "Vargas",
  );
}
