<?php

function location_province_list_lt() {
  return array(
    "AL" => t("Alytaus Apskritis"),
    "KU" => t("Kauno Apskritis"),
    "KL" => t("Klaipėdos Apskritis"),
    "MR" => t("Marijampolės Apskritis"),
    "PN" => t("Panevėžio Apskritis"),
    "TA" => t("Tauragės Apskritis"),
    "TE" => t("Telšių Apskritis"),
    "UT" => t("Utenos Apskritis"),
    "VL" => t("Vilniaus Apskritis"),
    "SA" => t("Šiaulių Apskritis"),
  );
}
