<?php

function location_province_list_mn () {
	return array (
		"073" => t("Arhangay Aymag"),
		"071" => t("Bayan-Ölgiy Aymag"),
		"069" => t("Bayanhongor Aymag"),
		"067" => t("Bulgan Aymag"),
		"047" => t("Central"),
		"037" => t("Darhan-Uul Aymag"),
		"057" => t("Dzavhan Aymag"),
		"061" => t("East Aimak"),
		"063" => t("East Gobi Aymag"),
		"065" => t("Govĭ-Altay Aymag"),
		"064" => t("Govĭ-Sumber"),
		"039" => t("Hentiy Aymag"),
		"043" => t("Hovd Aymag"),
		"041" => t("Hövsgöl Aymag"),
		"059" => t("Middle Govĭ"),
		"035" => t("Orhon Aymag"),
		"049" => t("Selenge Aymag"),
		"051" => t("Sühbaatar Aymag"),
		"1" => t("Ulaanbaatar Hot"),
		"046" => t("Uvs Aymag"),
		"053" => t("Ömnögovi Province"),
		"055" => t("Övörhangay"),
	);
}
