<?php

function location_province_list_cu() {
  return array(
    "10" => "Las Tunas",
    "99" => "Municipio Especial Isla de la Juventud",
    "AR" => "Provincia Artemisa",
    "12" => "Provincia Granma",
    "MA" => "Provincia Mayabeque",
    "09" => "Provincia de Camagüey",
    "08" => "Provincia de Ciego de Ávila",
    "06" => "Provincia de Cienfuegos",
    "14" => "Provincia de Guantánamo",
    "11" => "Provincia de Holguín",
    "03" => "Provincia de La Habana",
    "04" => "Provincia de Matanzas",
    "01" => "Provincia de Pinar del Río",
    "07" => "Provincia de Sancti Spíritus",
    "13" => "Provincia de Santiago de Cuba",
    "05" => "Provincia de Villa Clara",
  );
}
