<?php

function location_province_list_sa () {
	return array (
		"12" => t("Al Jawf"),
		"05" => t("Al-Qassim Province"),
		"04" => t("Eastern Province"),
		"02" => t("Makkah"),
		"09" => t("Minţaqat Jīzān"),
		"10" => t("Minţaqat Najrān"),
		"07" => t("Minţaqat Tabūk"),
		"11" => t("Minţaqat al Bāḩah"),
		"03" => t("Minţaqat al Madīnah"),
		"01" => t("Minţaqat ar Riyāḑ"),
		"06" => t("Minţaqat Ḩā’il"),
		"14" => t("Minţaqat ‘Asīr"),
		"08" => t("Northern Borders Region"),
	);
}
