<?php

function location_province_list_it() {
  return array(
    "65" => t("Abruzzo"),
    "23" => t("Aosta Valley"),
    "75" => t("Apulia"),
    "77" => t("Basilicate"),
    "78" => t("Calabria"),
    "72" => t("Campania"),
    "45" => t("Emilia-Romagna"),
    "36" => t("Friuli Venezia Giulia"),
    "62" => t("Latium"),
    "42" => t("Liguria"),
    "25" => t("Lombardy"),
    "67" => t("Molise"),
    "21" => t("Piedmont"),
    "88" => t("Sardinia"),
    "82" => t("Sicily"),
    "57" => t("The Marches"),
    "32" => t("Trentino-Alto Adige"),
    "52" => t("Tuscany"),
    "55" => t("Umbria"),
    "34" => t("Veneto"),
  );
}
