<?php

function location_province_list_uz() {
  return array(
    "AN" => "Andijan",
    "BU" => "Bukhara",
    "FA" => "Fergana",
    "JI" => "Jizzakh Province",
    "QR" => "Karakalpakstan",
    "QA" => "Kashkadarya Province",
    "NG" => "Namangan Province",
    "NW" => "Navoiy Province",
    "SA" => "Samarqand Viloyati",
    "SI" => "Sirdaryo",
    "SU" => "Surxondaryo Viloyati",
    "TK" => "Toshkent Shahri",
    "TO" => "Toshkent Viloyati",
    "XO" => "Xorazm Viloyati",
  );
}
