<?php

function location_province_list_pa() {
  return array(
    "EM" => t("Emberá-Wounaan"),
    "KY" => t("Kuna Yala"),
    "NB" => t("Ngöbe-Buglé"),
    "1"  => t("Provincia de Bocas del Toro"),
    "4"  => t("Provincia de Chiriquí"),
    "2"  => t("Provincia de Coclé"),
    "3"  => t("Provincia de Colón"),
    "6"  => t("Provincia de Herrera"),
    "7"  => t("Provincia de Los Santos"),
    "8"  => t("Provincia de Panamá"),
    "9"  => t("Provincia de Veraguas"),
    "5"  => t("Provincia del Darién"),
  );
}
