<?php

function location_province_list_ma() {
  return array(
    "09" => "Chaouia-Ouardigha",
    "10" => "Doukkala-Abda",
    "02" => "Gharb-Chrarda-Beni Hssen",
    "14" => "Guelmim-Es Semara",
    "15" => "Laâyoune-Boujdour-Sakia El Hamra",
    "11" => "Marrakech-Tensift-Al Haouz",
    "04" => "Oriental Region",
    "EH" => "Oued ed Dahab-Lagouira",
    "05" => "Région de Fès-Boulemane",
    "06" => "Région de Meknès-Tafilalet",
    "07" => "Région de Rabat-Salé-Zemmour-Zaër",
    "13" => "Région de Souss-Massa-Drâa",
    "01" => "Région de Tanger-Tétouan",
    "08" => "Région du Grand Casablanca",
    "12" => "Tadla-Azilal",
    "03" => "Taza-Al Hoceima-Taounate",
  );
}
