<?php

function location_province_list_bg() {
  return array(
    "01" => "Blagoevgrad",
    "02" => "Burgas",
    "07" => "Gabrovo Province",
    "11" => "Lovech",
    "08" => "Oblast Dobrich",
    "26" => "Oblast Khaskovo",
    "10" => "Oblast Kyustendil",
    "09" => "Oblast Kŭrdzhali",
    "12" => "Oblast Montana",
    "15" => "Oblast Pleven",
    "17" => "Oblast Razgrad",
    "18" => "Oblast Ruse",
    "27" => "Oblast Shumen",
    "19" => "Oblast Silistra",
    "20" => "Oblast Sliven",
    "21" => "Oblast Smolyan",
    "24" => "Oblast Stara Zagora",
    "25" => "Oblast Tŭrgovishte",
    "04" => "Oblast Veliko Tŭrnovo",
    "05" => "Oblast Vidin",
    "06" => "Oblast Vratsa",
    "28" => "Oblast Yambol",
    "13" => "Pazardzhik",
    "14" => "Pernik",
    "16" => "Plovdiv",
    "22" => "Sofia-Capital",
    "23" => "Sofiya",
    "03" => "Varna",
  );
}
