<?php

function location_province_list_lt() {
  return array(
    "AL" => "Alytaus Apskritis",
    "KU" => "Kauno Apskritis",
    "KL" => "Klaipėdos Apskritis",
    "MR" => "Marijampolės Apskritis",
    "PN" => "Panevėžio Apskritis",
    "TA" => "Tauragės Apskritis",
    "TE" => "Telšių Apskritis",
    "UT" => "Utenos Apskritis",
    "VL" => "Vilniaus Apskritis",
    "SA" => "Šiaulių Apskritis",
  );
}
