<?php

function location_province_list_mm() {
  return array(
    "07" => "Ayeyawady Region",
    "02" => "Bago Region",
    "14" => "Chin State",
    "11" => "Kachin State",
    "12" => "Kayah State",
    "13" => "Kayin State",
    "03" => "Magway Region",
    "04" => "Mandalay Region",
    "15" => "Mon State",
    "16" => "Rakhine State",
    "01" => "Sagaing Region",
    "17" => "Shan State",
    "05" => "Taninthayi Region",
    "06" => "Yangon Region",
  );
}
