<?php

function location_province_list_ci() {
  return array(
    "16" => "Agnéby",
    "17" => "Bafing",
    "09" => "Bas-Sassandra",
    "10" => "Denguélé",
    "06" => "Dix-Huit Montagnes",
    "18" => "Fromager",
    "02" => "Haut-Sassandra",
    "07" => "Lacs",
    "01" => "Lagunes",
    "12" => "Marahoué",
    "19" => "Moyen-Cavally",
    "05" => "Moyen-Comoé",
    "11" => "N’zi-Comoé",
    "13" => "Région du Sud-Comoé",
    "03" => "Savanes",
    "15" => "Sud-Bandama",
    "04" => "Vallée du Bandama",
    "14" => "Worodougou",
    "08" => "Zanzan",
  );
}
