<?php

function location_province_list_fi() {
  return array(
    "035" => "Brändö",
    "IS"  => "Eastern Finland Province",
    "043" => "Eckerö",
    "060" => "Finström",
    "062" => "Föglö",
    "065" => "Geta",
    "076" => "Hammarland",
    "170" => "Jomala",
    "295" => "Kumlinge",
    "318" => "Kökar",
    "LL"  => "Lapponia",
    "417" => "Lemland",
    "438" => "Lumparland",
    "478" => "Mariehamn",
    "OL"  => "Oulu",
    "12"  => "Province of Western Finland",
    "736" => "Saltvik",
    "766" => "Sottunga",
    "ES"  => "Southern Finland Province",
    "771" => "Sund",
    "941" => "Vårdö",
  );
}
