<?php

function location_province_list_mm() {
  return array(
    "07" => t("Ayeyawady Region"),
    "02" => t("Bago Region"),
    "14" => t("Chin State"),
    "11" => t("Kachin State"),
    "12" => t("Kayah State"),
    "13" => t("Kayin State"),
    "03" => t("Magway Region"),
    "04" => t("Mandalay Region"),
    "15" => t("Mon State"),
    "16" => t("Rakhine State"),
    "01" => t("Sagaing Region"),
    "17" => t("Shan State"),
    "05" => t("Taninthayi Region"),
    "06" => t("Yangon Region"),
  );
}
