<?php

function location_province_list_ar() {
  return array(
    "C" => "Buenos Aires F.D.",
    "B" => "Provincia de Buenos Aires",
    "K" => "Provincia de Catamarca",
    "W" => "Provincia de Corrientes",
    "X" => "Provincia de Córdoba",
    "E" => "Provincia de Entre Ríos",
    "P" => "Provincia de Formosa",
    "Y" => "Provincia de Jujuy",
    "L" => "Provincia de La Pampa",
    "F" => "Provincia de La Rioja",
    "M" => "Provincia de Mendoza",
    "N" => "Provincia de Misiones",
    "R" => "Provincia de Río Negro",
    "J" => "Provincia de San Juan",
    "D" => "Provincia de San Luis",
    "Z" => "Provincia de Santa Cruz",
    "S" => "Provincia de Santa Fe",
    "G" => "Provincia de Santiago del Estero",
    "V" => "Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur",
    "T" => "Provincia de Tucumán",
    "H" => "Provincia del Chaco",
    "U" => "Provincia del Chubut",
    "Q" => "Provincia del Neuquén",
    "A" => "Salta",
  );
}
