<?php

function location_province_list_et() {
  return array(
    "AF" => "Afar Region",
    "AM" => "Amhara Region",
    "BE" => "Benishangul-Gumuz Region",
    "DD" => "Dire Dawa Region",
    "GA" => "Gambela",
    "HA" => "Harari Region",
    "OR" => "Oromiya Region",
    "SO" => "Somali Region",
    "SN" => "Southern Nations, Nationalities, and People's Region",
    "TI" => "Tigray Region",
    "AA" => "Ādīs Ābeba Āstedader",
  );
}
