<?php

function location_province_list_cf() {
  return array(
    "BB"  => t("Bamingui-Bangoran"),
    "BK"  => t("Basse-Kotto"),
    "BGF" => t("Commune de Bangui"),
    "HM"  => t("Haut-Mbomou"),
    "HK"  => t("Haute-Kotto"),
    "LB"  => t("Lobaye"),
    "HS"  => t("Mambéré-Kadéï"),
    "MB"  => t("Mbomou"),
    "MP"  => t("Ombella-Mpoko"),
    "UK"  => t("Ouaka"),
    "AC"  => t("Ouham"),
    "KG"  => t("Préfecture de la Kémo"),
    "KB"  => t("Préfecture de la Nana-Grébizi"),
    "NM"  => t("Préfecture de la Nana-Mambéré"),
    "SE"  => t("Préfecture de la Sangha-Mbaéré"),
    "OP"  => t("Préfecture de l’ Ouham-Pendé"),
    "VK"  => t("Vakaga"),
  );
}
