<?php

function location_province_list_td() {
  return array(
    "BG" => t("Barh el Gazel"),
    "BA" => t("Batha Region"),
    "BO" => t("Borkou Region"),
    "CB" => t("Chari-Baguirmi Region"),
    "EN" => t("Ennedi Region"),
    "GR" => t("Guera Region"),
    "HL" => t("Hadjer-Lamis"),
    "KA" => t("Kanem Region"),
    "LC" => t("Lac Region"),
    "LO" => t("Logone Occidental Region"),
    "LR" => t("Logone Oriental Region"),
    "MA" => t("Mandoul"),
    "ME" => t("Mayo-Kebbi East Region"),
    "MO" => t("Mayo-Kebbi West Region"),
    "MC" => t("Moyen-Chari Region"),
    "OD" => t("Ouaddai Region"),
    "SA" => t("Salamat Region"),
    "SI" => t("Sila"),
    "TA" => t("Tandjile Region"),
    "TI" => t("Tibesti Region"),
    "ND" => t("Ville de N'Djaména"),
    "WF" => t("Wadi Fira Region"),
  );
}
