<?php

function location_province_list_jm() {
  return array(
    "09" => "Hanover Parish",
    "01" => "Kingston",
    "13" => "Parish of Clarendon",
    "12" => "Parish of Manchester",
    "04" => "Parish of Portland",
    "02" => "Parish of Saint Andrew",
    "06" => "Parish of Saint Ann",
    "14" => "Parish of Saint Catherine",
    "08" => "Parish of Saint James",
    "05" => "Parish of Saint Mary",
    "03" => "Parish of Saint Thomas",
    "07" => "Parish of Trelawny",
    "10" => "Parish of Westmoreland",
    "11" => "St. Elizabeth",
  );
}
