<?php

function location_province_list_uy() {
  return array(
    "AR" => "Artigas",
    "CA" => "Canelones",
    "CL" => "Cerro Largo",
    "CO" => "Colonia",
    "DU" => "Departamento de Durazno",
    "FS" => "Departamento de Flores",
    "MO" => "Departamento de Montevideo",
    "PA" => "Departamento de Paysandú",
    "RV" => "Departamento de Rivera",
    "RO" => "Departamento de Rocha",
    "RN" => "Departamento de Río Negro",
    "SA" => "Departamento de Salto",
    "SJ" => "Departamento de San José",
    "TA" => "Departamento de Tacuarembó",
    "TT" => "Departamento de Treinta y Tres",
    "FD" => "Florida",
    "LA" => "Lavalleja",
    "MA" => "Maldonado",
    "SO" => "Soriano",
  );
}
