<?php

function location_province_list_ao() {
  return array(
    "BGO" => "Bengo Province",
    "BGU" => "Benguela",
    "CAB" => "Cabinda",
    "CNO" => "Cuanza Norte Province",
    "CNN" => "Cunene Province",
    "HUA" => "Huambo",
    "HUI" => "Huila Province",
    "CCU" => "Kuando Kubango",
    "CUS" => "Kwanza Sul",
    "LUA" => "Luanda Province",
    "LNO" => "Lunda Norte Province",
    "LSU" => "Lunda Sul",
    "MAL" => "Malanje Province",
    "MOX" => "Moxico",
    "NAM" => "Namibe Province",
    "BIE" => "Província do Bié",
    "UIG" => "Província do Uíge",
    "ZAI" => "Zaire",
  );
}
