<?php

function location_province_list_mv () {
	return array (
		"31" => t("Baa Atholhu"),
		"CE" => t("Central Province"),
		"32" => t("Dhaalu Atholhu"),
		"33" => t("Faafu Atholhu"),
		"34" => t("Gaafu Alifu Atholhu"),
		"35" => t("Gaafu Dhaalu Atholhu"),
		"42" => t("Gnyaviyani Atoll"),
		"36" => t("Haa Alifu Atholhu"),
		"37" => t("Haa Dhaalu Atholhu"),
		"38" => t("Kaafu Atoll"),
		"05" => t("Laamu Atholhu"),
		"39" => t("Lhaviyani Atholhu"),
		"MLE" => t("Maale"),
		"41" => t("Meemu Atholhu"),
		"43" => t("Noonu Atoll"),
		"NC" => t("North Central Province"),
		"NO" => t("North Province"),
		"30" => t("Northern Ari Atoll"),
		"44" => t("Raa Atholhu"),
		"01" => t("Seenu Atholhu"),
		"45" => t("Shaviyani Atholhu"),
		"SC" => t("South Central Province"),
		"SU" => t("South Province"),
		"46" => t("Thaa Atholhu"),
		"UN" => t("Upper North Province"),
		"US" => t("Upper South Province"),
		"47" => t("Vaavu Atholhu"),
	);
}
