<?php

function location_province_list_ss () {
	return array (
		"EC" => t("Central Equatoria State"),
		"EE" => t("Eastern Equatoria State"),
		"JG" => t("Jonglei State"),
		"LK" => t("Lakes"),
		"BN" => t("Northern Bahr el Ghazal State"),
		"UY" => t("Unity"),
		"NU" => t("Upper Nile State"),
		"WR" => t("Warrap"),
		"BW" => t("Western Bahr el Ghazal State"),
		"EW" => t("Western Equatoria"),
	);
}
