<?php

function location_province_list_zw() {
  return array(
    "BU" => "Bulawayo",
    "HA" => "Harare",
    "MA" => "Manicaland",
    "MC" => "Mashonaland Central Province",
    "ME" => "Mashonaland East Province",
    "MW" => "Mashonaland West",
    "MV" => "Masvingo Province",
    "MN" => "Matabeleland North",
    "MS" => "Matabeleland South Province",
    "MI" => "Midlands Province",
  );
}
