<?php

function location_province_list_se() {
  return array(
    "K"  => "Blekinge",
    "W"  => "Dalarna",
    "I"  => "Gotland",
    "X"  => "Gävleborg",
    "N"  => "Halland",
    "Z"  => "Jämtland",
    "F"  => "Jönköping",
    "H"  => "Kalmar",
    "G"  => "Kronoberg",
    "BD" => "Norrbotten",
    "M"  => "Skåne",
    "AB" => "Stockholm",
    "D"  => "Södermanland",
    "C"  => "Uppsala",
    "S"  => "Värmland",
    "AC" => "Västerbotten",
    "Y"  => "Västernorrland",
    "U"  => "Västmanland",
    "O"  => "Västra Götaland",
    "T"  => "Örebro",
    "E"  => "Östergötland",
  );
}
