<?php

function location_province_list_fr() {
  return array(
    "A"  => t("Alsace"),
    "B"  => t("Aquitaine"),
    "C"  => t("Auvergne"),
    "D"  => t("Bourgogne"),
    "E"  => t("Brittany"),
    "F"  => t("Centre"),
    "G"  => t("Champagne-Ardenne"),
    "H"  => t("Corsica"),
    "I"  => t("Franche-Comté"),
    "GP" => t("Guadeloupe"),
    "GF" => t("Guyane"),
    "K"  => t("Languedoc-Roussillon"),
    "L"  => t("Limousin"),
    "M"  => t("Lorraine"),
    "P"  => t("Lower Normandy"),
    "MQ" => t("Martinique"),
    "N"  => t("Midi-Pyrénées"),
    "O"  => t("Nord-Pas-de-Calais"),
    "R"  => t("Pays de la Loire"),
    "S"  => t("Picardie"),
    "T"  => t("Poitou-Charentes"),
    "U"  => t("Provence-Alpes-Côte d'Azur"),
    "V"  => t("Rhône-Alpes"),
    "RE" => t("Réunion"),
    "Q"  => t("Upper Normandy"),
    "J"  => t("Île-de-France"),
  );
}
