<?php

function location_province_list_es() {
  return array(
    "AN" => "Andalusia",
    "AR" => "Aragon",
    "AS" => "Asturias",
    "IB" => "Balearic Islands",
    "PV" => "Basque Country",
    "CN" => "Canary Islands",
    "CB" => "Cantabria",
    "CL" => "Castille and León",
    "CM" => "Castille-La Mancha",
    "CT" => "Catalonia",
    "CE" => "Ceuta",
    "EX" => "Extremadura",
    "GA" => "Galicia",
    "RI" => "La Rioja",
    "MD" => "Madrid",
    "ML" => "Melilla",
    "MC" => "Murcia",
    "NC" => "Navarre",
    "VC" => "Valencia",
  );
}
