<?php

function location_province_list_gu() {
  return array(
    "AH" => "Agana Heights Municipality",
    "AT" => "Agat Municipality",
    "AS" => "Asan-Maina Municipality",
    "BA" => "Barrigada Municipality",
    "CP" => "Chalan Pago-Ordot Municipality",
    "DD" => "Dededo Municipality",
    "AN" => "Hagåtña Municipality",
    "IN" => "Inarajan Municipality",
    "MA" => "Mangilao Municipality",
    "ME" => "Merizo Municipality",
    "MT" => "Mongmong-Toto-Maite Municipality",
    "PI" => "Piti Municipality",
    "SR" => "Santa Rita Municipality",
    "SJ" => "Sinajana Municipality",
    "TF" => "Talofofo Municipality",
    "TM" => "Tamuning-Tumon-Harmon Municipality",
    "UM" => "Umatac Municipality",
    "YG" => "Yigo Municipality",
    "YN" => "Yona Municipality",
  );
}
