<?php

function location_province_list_ye() {
  return array(
    "AD" => "Aden",
    "MR" => "Al Mahrah",
    "MW" => "Al Maḩwīt",
    "SA" => "Amanat Al Asimah",
    "IB" => "Ibb",
    "AB" => "Muḩāfaz̧at Abyan",
    "DH" => "Muḩāfaz̧at Dhamār",
    "LA" => "Muḩāfaz̧at Laḩij",
    "MA" => "Muḩāfaz̧at Ma’rib",
    "RA" => "Muḩāfaz̧at Raymah",
    "TA" => "Muḩāfaz̧at Ta‘izz",
    "BA" => "Muḩāfaz̧at al Bayḑā’",
    "JA" => "Muḩāfaz̧at al Jawf",
    "HU" => "Muḩāfaz̧at al Ḩudaydah",
    "DA" => "Muḩāfaz̧at aḑ Ḑāli‘",
    "SD" => "Muḩāfaz̧at Şa‘dah",
    "HJ" => "Muḩāfaz̧at Ḩajjah",
    "HD" => "Muḩāfaz̧at Ḩaḑramawt",
    "AM" => "Omran",
    "SN" => "Sanaa",
    "SH" => "Shabwah",
  );
}
