<?php

function location_province_list_de () {
	return array (
		"BW" => t("Baden-Württemberg Region"),
		"BY" => t("Bavaria"),
		"BB" => t("Brandenburg"),
		"HB" => t("Bremen"),
		"HH" => t("Free and Hanseatic City of Hamburg"),
		"HE" => t("Hesse"),
		"BE" => t("Land Berlin"),
		"NI" => t("Lower Saxony"),
		"MV" => t("Mecklenburg-Vorpommern"),
		"NW" => t("North Rhine-Westphalia"),
		"RP" => t("Rheinland-Pfalz"),
		"SL" => t("Saarland"),
		"SN" => t("Saxony"),
		"ST" => t("Saxony-Anhalt"),
		"SH" => t("Schleswig-Holstein"),
		"TH" => t("Thuringia"),
	);
}
