<?php

function location_province_list_ph() {
  return array(
    "14"  => "Autonomous Region in Muslim Mindanao",
    "ALB" => "Bicol",
    "02"  => "Cagayan Valley",
    "MDC" => "Calabarzon",
    "BUL" => "Caraga",
    "AGS" => "Central Luzon",
    "07"  => "Central Visayas",
    "CAN" => "Cordillera Administrative Region",
    "BOH" => "Davao",
    "08"  => "Eastern Visayas",
    "01"  => "Ilocos Region",
    "41"  => "Mimaropa",
    "00"  => "National Capital Region",
    "10"  => "Northern Mindanao",
    "12"  => "Soccsksargen",
    "06"  => "Western Visayas",
    "BTG" => "Zamboanga Peninsula",
  );
}
