<?php

function location_province_list_gt() {
  return array(
    "AV" => "Departamento de Alta Verapaz",
    "BV" => "Departamento de Baja Verapaz",
    "CM" => "Departamento de Chimaltenango",
    "CQ" => "Departamento de Chiquimula",
    "PR" => "Departamento de El Progreso",
    "ES" => "Departamento de Escuintla",
    "GU" => "Departamento de Guatemala",
    "HU" => "Departamento de Huehuetenango",
    "IZ" => "Departamento de Izabal",
    "JA" => "Departamento de Jalapa",
    "JU" => "Departamento de Jutiapa",
    "QZ" => "Departamento de Quetzaltenango",
    "RE" => "Departamento de Retalhuleu",
    "SA" => "Departamento de Sacatepéquez",
    "SM" => "Departamento de San Marcos",
    "SR" => "Departamento de Santa Rosa",
    "SO" => "Departamento de Sololá",
    "SU" => "Departamento de Suchitepéquez",
    "TO" => "Departamento de Totonicapán",
    "ZA" => "Departamento de Zacapa",
    "PE" => "Departamento del Petén",
    "QC" => "Departamento del Quiché",
  );
}
