<?php

function location_province_list_om() {
  return array(
    "SH" => "Ash Sharqiyah South",
    "ZA" => "Az̧ Z̧āhirah",
    "MU" => "Musandam",
    "BA" => "Muḩāfaz̧at Janūb al Bāţinah",
    "MA" => "Muḩāfaz̧at Masqaţ",
    "11" => "Muḩāfaz̧at Shamāl al Bāţinah",
    "12" => "Muḩāfaz̧at Shamāl ash Sharqīyah",
    "ZU" => "Muḩāfaz̧at Z̧ufār",
    "DA" => "Muḩāfaz̧at ad Dākhilīyah",
    "BU" => "Muḩāfaz̧at al Buraymī",
    "WU" => "Muḩāfaz̧at al Wusţá",
  );
}
