<?php

function location_province_list_de() {
  return array(
    "BW" => "Baden-Württemberg Region",
    "BY" => "Bavaria",
    "BB" => "Brandenburg",
    "HB" => "Bremen",
    "HH" => "Free and Hanseatic City of Hamburg",
    "HE" => "Hesse",
    "BE" => "Land Berlin",
    "NI" => "Lower Saxony",
    "MV" => "Mecklenburg-Vorpommern",
    "NW" => "North Rhine-Westphalia",
    "RP" => "Rheinland-Pfalz",
    "SL" => "Saarland",
    "SN" => "Saxony",
    "ST" => "Saxony-Anhalt",
    "SH" => "Schleswig-Holstein",
    "TH" => "Thuringia",
  );
}
