<?php

function location_province_list_hu() {
  return array(
    "BA" => "Baranya county",
    "BE" => "Bekes County",
    "BZ" => "Borsod-Abaúj-Zemplén",
    "BU" => "Budapest főváros",
    "BK" => "Bács-Kiskun",
    "CS" => "Csongrád megye",
    "FE" => "Fejér",
    "GS" => "Győr-Moson-Sopron",
    "HB" => "Hajdú-Bihar",
    "HE" => "Heves megye",
    "JN" => "Jász-Nagykun-Szolnok",
    "KE" => "Komárom-Esztergom",
    "NO" => "Nógrád megye",
    "PE" => "Pest megye",
    "SO" => "Somogy megye",
    "SZ" => "Szabolcs-Szatmár-Bereg",
    "TO" => "Tolna megye",
    "VA" => "Vas",
    "VE" => "Veszprém megye",
    "ZA" => "Zala",
  );
}
