<?php

function location_province_list_mv() {
  return array(
    "31"  => "Baa Atholhu",
    "CE"  => "Central Province",
    "32"  => "Dhaalu Atholhu",
    "33"  => "Faafu Atholhu",
    "34"  => "Gaafu Alifu Atholhu",
    "35"  => "Gaafu Dhaalu Atholhu",
    "42"  => "Gnyaviyani Atoll",
    "36"  => "Haa Alifu Atholhu",
    "37"  => "Haa Dhaalu Atholhu",
    "38"  => "Kaafu Atoll",
    "05"  => "Laamu Atholhu",
    "39"  => "Lhaviyani Atholhu",
    "MLE" => "Maale",
    "41"  => "Meemu Atholhu",
    "43"  => "Noonu Atoll",
    "NC"  => "North Central Province",
    "NO"  => "North Province",
    "30"  => "Northern Ari Atoll",
    "44"  => "Raa Atholhu",
    "01"  => "Seenu Atholhu",
    "45"  => "Shaviyani Atholhu",
    "SC"  => "South Central Province",
    "SU"  => "South Province",
    "46"  => "Thaa Atholhu",
    "UN"  => "Upper North Province",
    "US"  => "Upper South Province",
    "47"  => "Vaavu Atholhu",
  );
}
