<?php

function location_province_list_ly() {
  return array(
    "JU" => "Al Jufrah",
    "KF" => "Al Kufrah",
    "MJ" => "Al Marj",
    "MB" => "Al Marqab",
    "DR" => "Darnah",
    "MQ" => "Murzuq",
    "BA" => "Sha‘bīyat Banghāzī",
    "GT" => "Sha‘bīyat Ghāt",
    "MI" => "Sha‘bīyat Mişrātah",
    "NL" => "Sha‘bīyat Nālūt",
    "SB" => "Sha‘bīyat Sabhā",
    "WD" => "Sha‘bīyat Wādī al Ḩayāt",
    "WS" => "Sha‘bīyat Wādī ash Shāţi’",
    "BU" => "Sha‘bīyat al Buţnān",
    "JA" => "Sha‘bīyat al Jabal al Akhḑar",
    "JG" => "Sha‘bīyat al Jabal al Gharbī",
    "JI" => "Sha‘bīyat al Jafārah",
    "WA" => "Sha‘bīyat al Wāḩāt",
    "NQ" => "Sha‘bīyat an Nuqāţ al Khams",
    "ZA" => "Sha‘bīyat az Zāwiyah",
    "TB" => "Sha‘bīyat Ţarābulus",
    "SR" => "Surt",
  );
}
