<?php

function location_province_list_ci() {
  return array(
    "16" => t("Agnéby"),
    "17" => t("Bafing"),
    "09" => t("Bas-Sassandra"),
    "10" => t("Denguélé"),
    "06" => t("Dix-Huit Montagnes"),
    "18" => t("Fromager"),
    "02" => t("Haut-Sassandra"),
    "07" => t("Lacs"),
    "01" => t("Lagunes"),
    "12" => t("Marahoué"),
    "19" => t("Moyen-Cavally"),
    "05" => t("Moyen-Comoé"),
    "11" => t("N’zi-Comoé"),
    "13" => t("Région du Sud-Comoé"),
    "03" => t("Savanes"),
    "15" => t("Sud-Bandama"),
    "04" => t("Vallée du Bandama"),
    "14" => t("Worodougou"),
    "08" => t("Zanzan"),
  );
}
