<?php

function location_province_list_mr() {
  return array(
    "07"  => "Adrar",
    "03"  => "Assaba",
    "05"  => "Brakna",
    "08"  => "Dakhlet Nouadhibou",
    "NKC" => "District de Nouakchott",
    "04"  => "Gorgol",
    "10"  => "Guidimaka",
    "01"  => "Hodh ech Chargui",
    "02"  => "Hodh el Gharbi",
    "12"  => "Inchiri",
    "09"  => "Tagant",
    "11"  => "Tiris Zemmour",
    "06"  => "Wilaya du Trarza",
  );
}
