<?php

function location_province_list_cg() {
  return array(
    "BZV"     => "Commune de Brazzaville",
    "8"       => "Cuvette",
    "15"      => "Cuvette-Ouest",
    "7"       => "Likouala",
    "14"      => "Plateaux",
    "7280295" => "Pointe-Noire",
    "12"      => "Pool",
    "11"      => "Région de la Bouenza",
    "2"       => "Région de la Lékoumou",
    "5"       => "Région du Kouilou",
    "9"       => "Région du Niari",
    "13"      => "Sangha",
  );
}
