<?php

function location_province_list_ga() {
  return array(
    "1" => "Estuaire",
    "4" => "Province de la Ngounié",
    "5" => "Province de la Nyanga",
    "6" => "Province de l’ Ogooué-Ivindo",
    "7" => "Province de l’ Ogooué-Lolo",
    "8" => "Province de l’ Ogooué-Maritime",
    "2" => "Province du Haut-Ogooué",
    "3" => "Province du Moyen-Ogooué",
    "9" => "Province du Woleu-Ntem",
  );
}
