<?php

function location_province_list_ni() {
  return array(
    "BO" => "Departamento de Boaco",
    "CA" => "Departamento de Carazo",
    "CI" => "Departamento de Chinandega",
    "CO" => "Departamento de Chontales",
    "ES" => "Departamento de Estelí",
    "GR" => "Departamento de Granada",
    "JI" => "Departamento de Jinotega",
    "LE" => "Departamento de León",
    "MD" => "Departamento de Madriz",
    "MN" => "Departamento de Managua",
    "MS" => "Departamento de Masaya",
    "MT" => "Departamento de Matagalpa",
    "NS" => "Departamento de Nueva Segovia",
    "RI" => "Departamento de Rivas",
    "SJ" => "Departamento de Río San Juan",
    "AN" => "Región Autónoma Atlántico Norte",
    "AS" => "Región Autónoma Atlántico Sur",
  );
}
