<?php

function location_province_list_mn() {
  return array(
    "073" => "Arhangay Aymag",
    "071" => "Bayan-Ölgiy Aymag",
    "069" => "Bayanhongor Aymag",
    "067" => "Bulgan Aymag",
    "047" => "Central",
    "037" => "Darhan-Uul Aymag",
    "057" => "Dzavhan Aymag",
    "061" => "East Aimak",
    "063" => "East Gobi Aymag",
    "065" => "Govĭ-Altay Aymag",
    "064" => "Govĭ-Sumber",
    "039" => "Hentiy Aymag",
    "043" => "Hovd Aymag",
    "041" => "Hövsgöl Aymag",
    "059" => "Middle Govĭ",
    "035" => "Orhon Aymag",
    "049" => "Selenge Aymag",
    "051" => "Sühbaatar Aymag",
    "1"   => "Ulaanbaatar Hot",
    "046" => "Uvs Aymag",
    "053" => "Ömnögovi Province",
    "055" => "Övörhangay",
  );
}
