<?php

function location_province_list_la() {
  return array(
    "AT" => t("Attapu"),
    "BL" => t("Bolikhamxai"),
    "CH" => t("Champasak"),
    "HO" => t("Houaphan"),
    "KH" => t("Khammouan"),
    "BK" => t("Khouèng Bokèo"),
    "OU" => t("Khouèng Oudômxai"),
    "PH" => t("Khouèng Phôngsali"),
    "SV" => t("Khouèng Savannakhét"),
    "XE" => t("Khouèng Xékong"),
    "LM" => t("Louangnamtha"),
    "LP" => t("Luang Prabang Province"),
    "SL" => t("Salavan"),
    "VT" => t("Vientiane Prefecture"),
    "VI" => t("Vientiane Province"),
    "XA" => t("Xaignabouli"),
    "XI" => t("Xiangkhouang"),
  );
}
