<?php

function location_province_list_hk () {
	return array (
		"HCW" => t("Central and Western District"),
		"HEA" => t("Eastern"),
		"NIS" => t("Islands District"),
		"KKC" => t("Kowloon City"),
		"NKT" => t("Kwai Tsing"),
		"KKT" => t("Kwon Tong"),
		"NNO" => t("North"),
		"NSK" => t("Sai Kung District"),
		"NST" => t("Sha Tin"),
		"KSS" => t("Sham Shui Po"),
		"HSO" => t("Southern"),
		"NTP" => t("Tai Po District"),
		"NTW" => t("Tsuen Wan District"),
		"NTM" => t("Tuen Mun"),
		"HWC" => t("Wanchai"),
		"KWT" => t("Wong Tai Sin"),
		"KYT" => t("Yau Tsim Mong"),
		"NYL" => t("Yuen Long District"),
		"00" => t("Hong Kong"),
	);
}
