<?php

function location_province_list_la() {
  return array(
    "AT" => "Attapu",
    "BL" => "Bolikhamxai",
    "CH" => "Champasak",
    "HO" => "Houaphan",
    "KH" => "Khammouan",
    "BK" => "Khouèng Bokèo",
    "OU" => "Khouèng Oudômxai",
    "PH" => "Khouèng Phôngsali",
    "SV" => "Khouèng Savannakhét",
    "XE" => "Khouèng Xékong",
    "LM" => "Louangnamtha",
    "LP" => "Luang Prabang Province",
    "SL" => "Salavan",
    "VT" => "Vientiane Prefecture",
    "VI" => "Vientiane Province",
    "XA" => "Xaignabouli",
    "XI" => "Xiangkhouang",
  );
}
