<?php

function location_province_list_zw() {
  return array(
    "BU" => t("Bulawayo"),
    "HA" => t("Harare"),
    "MA" => t("Manicaland"),
    "MC" => t("Mashonaland Central Province"),
    "ME" => t("Mashonaland East Province"),
    "MW" => t("Mashonaland West"),
    "MV" => t("Masvingo Province"),
    "MN" => t("Matabeleland North"),
    "MS" => t("Matabeleland South Province"),
    "MI" => t("Midlands Province"),
  );
}
