<?php

function location_province_list_mg() {
  return array(
    "7670851" => "Alaotra Mangoro Region",
    "7670904" => "Amoron'i Mania Region",
    "7670856" => "Analamanga Region",
    "7670848" => "Analanjirofo Region",
    "7670911" => "Androy Region",
    "7670910" => "Anosy Region",
    "7670913" => "Atsimo-Andrefana Region",
    "7670908" => "Atsimo-Atsinanana Region",
    "7670857" => "Atsinanana Region",
    "7670850" => "Betsiboka Region",
    "7670849" => "Boeny Region",
    "7670853" => "Bongolava Region",
    "7670842" => "Diana Region",
    "7670907" => "Ihorombe Region",
    "7670855" => "Itasy Region",
    "7670852" => "Melaky Region",
    "7670902" => "Menabe Region",
    "7670846" => "Sava Region",
    "7670847" => "Sofia Region",
    "7670905" => "Upper Matsiatra",
    "7670854" => "Vakinankaratra Region",
    "7670906" => "Vatovavy Fitovinany Region",
  );
}
