<?php

function location_province_list_nz() {
  return array(
    "AUK" => "Auckland",
    "BOP" => "Bay of Plenty",
    "CAN" => "Canterbury Region",
    "CIT" => "Chatham Islands",
    "GIS" => "Gisborne Region",
    "HKB" => "Hawke's Bay",
    "MWT" => "Manawatu-Wanganui",
    "MBH" => "Marlborough",
    "NSN" => "Nelson",
    "NTL" => "Northland",
    "OTA" => "Otago Region",
    "STL" => "Southland Region",
    "TKI" => "Taranaki",
    "TAS" => "Tasman",
    "WKO" => "Waikato",
    "WGN" => "Wellington",
    "WTC" => "West Coast",
  );
}
