<?php

function location_province_list_kr() {
  return array(
    "26" => "Busan",
    "27" => "Daegu",
    "30" => "Daejeon",
    "42" => "Gangwon",
    "29" => "Gwangju",
    "41" => "Gyeonggi Province",
    "28" => "Incheon",
    "49" => "Jeju",
    "43" => "North Chungcheong",
    "47" => "North Gyeongsang",
    "45" => "North Jeolla",
    "22" => "Sejong",
    "11" => "Seoul",
    "44" => "South Chungcheong",
    "48" => "South Gyeongsang",
    "46" => "South Jeolla Province",
    "31" => "Ulsan",
  );
}
