<?php

function location_province_list_cf() {
  return array(
    "BB"  => "Bamingui-Bangoran",
    "BK"  => "Basse-Kotto",
    "BGF" => "Commune de Bangui",
    "HM"  => "Haut-Mbomou",
    "HK"  => "Haute-Kotto",
    "LB"  => "Lobaye",
    "HS"  => "Mambéré-Kadéï",
    "MB"  => "Mbomou",
    "MP"  => "Ombella-Mpoko",
    "UK"  => "Ouaka",
    "AC"  => "Ouham",
    "KG"  => "Préfecture de la Kémo",
    "KB"  => "Préfecture de la Nana-Grébizi",
    "NM"  => "Préfecture de la Nana-Mambéré",
    "SE"  => "Préfecture de la Sangha-Mbaéré",
    "OP"  => "Préfecture de l’ Ouham-Pendé",
    "VK"  => "Vakaga",
  );
}
