<?php

function location_province_list_sy() {
  return array(
    "HA" => "Al-Hasakah",
    "HL" => "Aleppo",
    "RA" => "Ar-Raqqah",
    "SU" => "As-Suwayda",
    "DI" => "Damascus City",
    "DR" => "Daraa",
    "DY" => "Deir ez-Zor",
    "HM" => "Hama",
    "HI" => "Homs",
    "ID" => "Idlib",
    "LA" => "Latakia",
    "QU" => "Quneitra",
    "RD" => "Rif-dimashq",
    "TA" => "Tartus",
  );
}
