<?php

function location_province_list_lr() {
  return array(
    "BM" => "Bomi County",
    "BG" => "Bong County",
    "21" => "Gbarpolu County",
    "GB" => "Grand Bassa County",
    "CM" => "Grand Cape Mount County",
    "GG" => "Grand Gedeh County",
    "GK" => "Grand Kru County",
    "LO" => "Lofa County",
    "MG" => "Margibi County",
    "MY" => "Maryland County",
    "MO" => "Montserrado County",
    "NI" => "Nimba County",
    "RI" => "River Cess County",
    "22" => "River Gee County",
    "SI" => "Sinoe County",
  );
}
