<?php

function location_province_list_cz() {
  return array(
    "ST" => "Central Bohemian Region",
    "PR" => "Hlavní město Praha",
    "JC" => "Jihočeský kraj",
    "KA" => "Karlovarský kraj",
    "VY" => "Kraj Vysočina",
    "KR" => "Královéhradecký kraj",
    "LI" => "Liberecký kraj",
    "MO" => "Moravskoslezský kraj",
    "OL" => "Olomoucký kraj",
    "PA" => "Pardubický kraj",
    "PL" => "Plzeňský kraj",
    "JM" => "South Moravian Region",
    "ZL" => "Zlínský kraj",
    "US" => "Ústecký kraj",
  );
}
