<?php

function location_province_list_bm() {
  return array(
    "DS" => t("Devonshire Parish"),
    "HA" => t("Hamilton Parish"),
    "HC" => t("Hamilton city"),
    "PG" => t("Paget"),
    "PB" => t("Pembroke Parish"),
    "GC" => t("Saint George"),
    "SG" => t("Saint George’s Parish"),
    "SA" => t("Sandys Parish"),
    "SM" => t("Smith’s Parish"),
    "SH" => t("Southampton Parish"),
    "WA" => t("Warwick Parish"),
  );
}
