<?php

function location_province_list_mu() {
  return array(
    "AG" => "Agalega Islands",
    "BL" => "Black River District",
    "CC" => "Cargados Carajos",
    "FL" => "Flacq District",
    "GP" => "Grand Port District",
    "MO" => "Moka District",
    "PA" => "Pamplemousses District",
    "PW" => "Plaines Wilhems District",
    "PL" => "Port Louis District",
    "RR" => "Rivière du Rempart District",
    "RO" => "Rodrigues",
    "SA" => "Savanne District",
  );
}
