<?php

function location_province_list_cl() {
  return array(
    "AN" => "Antofagasta",
    "AT" => "Atacama",
    "CO" => "Coquimbo",
    "LL" => "Los Lagos",
    "ML" => "Maule",
    "AI" => "Región Aisén del General Carlos Ibáñez del Campo",
    "AP" => "Región de Arica y Parinacota",
    "LR" => "Región de Los Ríos",
    "MA" => "Región de Magallanes y de la Antártica Chilena",
    "VS" => "Región de Valparaíso",
    "AR" => "Región de la Araucanía",
    "BI" => "Región del Biobío",
    "LI" => "Región del Libertador General Bernardo O’Higgins",
    "RM" => "Santiago",
    "TA" => "Tarapacá Region",
  );
}
