<?php

function location_province_list_it() {
  return array(
    "65" => "Abruzzo",
    "23" => "Aosta Valley",
    "75" => "Apulia",
    "77" => "Basilicate",
    "78" => "Calabria",
    "72" => "Campania",
    "45" => "Emilia-Romagna",
    "36" => "Friuli Venezia Giulia",
    "62" => "Latium",
    "42" => "Liguria",
    "25" => "Lombardy",
    "67" => "Molise",
    "21" => "Piedmont",
    "88" => "Sardinia",
    "82" => "Sicily",
    "57" => "The Marches",
    "32" => "Trentino-Alto Adige",
    "52" => "Tuscany",
    "55" => "Umbria",
    "34" => "Veneto",
  );
}
