<?php

function location_province_list_nl () {
	return array (
		"FR" => t("Friesland"),
		"GR" => t("Groningen"),
		"NB" => t("North Brabant"),
		"NH" => t("North Holland"),
		"DR" => t("Provincie Drenthe"),
		"FL" => t("Provincie Flevoland"),
		"GE" => t("Provincie Gelderland"),
		"LI" => t("Provincie Limburg"),
		"OV" => t("Provincie Overijssel"),
		"UT" => t("Provincie Utrecht"),
		"ZE" => t("Provincie Zeeland"),
		"ZH" => t("South Holland"),
	);
}
