<?php

function location_province_list_lr () {
	return array (
		"BM" => t("Bomi County"),
		"BG" => t("Bong County"),
		"21" => t("Gbarpolu County"),
		"GB" => t("Grand Bassa County"),
		"CM" => t("Grand Cape Mount County"),
		"GG" => t("Grand Gedeh County"),
		"GK" => t("Grand Kru County"),
		"LO" => t("Lofa County"),
		"MG" => t("Margibi County"),
		"MY" => t("Maryland County"),
		"MO" => t("Montserrado County"),
		"NI" => t("Nimba County"),
		"RI" => t("River Cess County"),
		"22" => t("River Gee County"),
		"SI" => t("Sinoe County"),
	);
}
