<?php

function location_province_list_pl() {
  return array(
    "WP" => t("Greater Poland Voivodeship"),
    "KP" => t("Kujawsko-Pomorskie"),
    "MA" => t("Lesser Poland Voivodeship"),
    "DS" => t("Lower Silesian Voivodeship"),
    "LU" => t("Lublin Voivodeship"),
    "LB" => t("Lubusz"),
    "MZ" => t("Masovian Voivodeship"),
    "OP" => t("Opole Voivodeship"),
    "PD" => t("Podlasie"),
    "PM" => t("Pomeranian Voivodeship"),
    "SL" => t("Silesian Voivodeship"),
    "PK" => t("Subcarpathian Voivodeship"),
    "WN" => t("Warmian-Masurian Voivodeship"),
    "ZP" => t("West Pomeranian Voivodeship"),
    "LD" => t("Łódź Voivodeship"),
    "SK" => t("Świętokrzyskie"),
  );
}
