<?php

function location_province_list_bj() {
  return array(
    "AL" => "Alibori",
    "AK" => "Atakora Department",
    "AQ" => "Atlantique Department",
    "BO" => "Borgou Department",
    "CO" => "Collines Department",
    "DO" => "Donga",
    "OU" => "Département de l’ Ouémé",
    "KO" => "Kouffo Department",
    "LI" => "Littoral",
    "MO" => "Mono",
    "PL" => "Plateau Department",
    "ZO" => "Zou Department",
  );
}
