<?php

function location_province_list_py() {
  return array(
    "ASU" => "Asunción",
    "11"  => "Departamento Central",
    "16"  => "Departamento de Alto Paraguay",
    "19"  => "Departamento de Boquerón",
    "5"   => "Departamento de Caaguazú",
    "6"   => "Departamento de Caazapá",
    "14"  => "Departamento de Canindeyú",
    "1"   => "Departamento de Concepción",
    "7"   => "Departamento de Itapúa",
    "8"   => "Departamento de Misiones",
    "9"   => "Departamento de Paraguarí",
    "15"  => "Departamento de Presidente Hayes",
    "2"   => "Departamento de San Pedro",
    "3"   => "Departamento de la Cordillera",
    "12"  => "Departamento de Ñeembucú",
    "10"  => "Departamento del Alto Paraná",
    "13"  => "Departamento del Amambay",
    "4"   => "Departamento del Guairá",
  );
}
