<?php

function location_province_list_sm() {
  return array(
    "01" => t("Castello di Acquaviva"),
    "06" => t("Castello di Borgo Maggiore"),
    "03" => t("Castello di Domagnano"),
    "04" => t("Castello di Faetano"),
    "05" => t("Castello di Fiorentino"),
    "08" => t("Castello di Montegiardino"),
    "07" => t("Castello di San Marino Città"),
    "02" => t("Chiesanuova"),
    "09" => t("Serravalle"),
  );
}
