<?php

function location_province_list_cd () {
	return array (
		"BN" => t("Bandundu Province"),
		"OR" => t("Eastern Province"),
		"KA" => t("Katanga Province"),
		"KN" => t("Kinshasa City"),
		"NK" => t("Nord Kivu"),
		"EQ" => t("Province de l’ Équateur"),
		"BC" => t("Province du Bas-Congo"),
		"KW" => t("Province du Kasaï-Occidental"),
		"KE" => t("Province du Kasaï-Oriental"),
		"MA" => t("Province du Maniema"),
		"SK" => t("South Kivu"),
	);
}
