<?php

function location_province_list_lc() {
  return array(
    "AR" => t("Quarter of Anse-la-Raye"),
    "CA" => t("Quarter of Castries"),
    "CH" => t("Quarter of Choiseul"),
    "DA" => t("Quarter of Dauphin"),
    "DE" => t("Quarter of Dennery"),
    "GI" => t("Quarter of Gros-Islet"),
    "LA" => t("Quarter of Laborie"),
    "MI" => t("Quarter of Micoud"),
    "PR" => t("Quarter of Praslin"),
    "SO" => t("Quarter of Soufrière"),
    "VF" => t("Quarter of Vieux-Fort"),
  );
}
