<?php

function location_province_list_gy () {
	return array (
		"BA" => t("Barima-Waini Region"),
		"CU" => t("Cuyuni-Mazaruni Region"),
		"DE" => t("Demerara-Mahaica Region"),
		"EB" => t("East Berbice-Corentyne Region"),
		"ES" => t("Essequibo Islands-West Demerara Region"),
		"MA" => t("Mahaica-Berbice Region"),
		"PM" => t("Pomeroon-Supenaam Region"),
		"PT" => t("Potaro-Siparuni Region"),
		"UD" => t("Upper Demerara-Berbice Region"),
		"UT" => t("Upper Takutu-Upper Essequibo Region"),
	);
}
