<?php

function location_province_list_eg() {
  return array(
    "ALX" => "Alexandria",
    "SUZ" => "As Suways",
    "BH"  => "Beheira Governorate",
    "SHR" => "Eastern Province",
    "IS"  => "Ismailia Governorate",
    "KFS" => "Kafr ash Shaykh",
    "ASN" => "Muḩāfaz̧at Aswān",
    "AST" => "Muḩāfaz̧at Asyūţ",
    "BNS" => "Muḩāfaz̧at Banī Suwayf",
    "PTS" => "Muḩāfaz̧at Būr Sa‘īd",
    "DT"  => "Muḩāfaz̧at Dumyāţ",
    "JS"  => "Muḩāfaz̧at Janūb Sīnā’",
    "MT"  => "Muḩāfaz̧at Maţrūḩ",
    "KN"  => "Muḩāfaz̧at Qinā",
    "SIN" => "Muḩāfaz̧at Shamāl Sīnā’",
    "SHG" => "Muḩāfaz̧at Sūhāj",
    "DK"  => "Muḩāfaz̧at ad Daqahlīyah",
    "BA"  => "Muḩāfaz̧at al Baḩr al Aḩmar",
    "FYM" => "Muḩāfaz̧at al Fayyūm",
    "GH"  => "Muḩāfaz̧at al Gharbīyah",
    "GZ"  => "Muḩāfaz̧at al Jīzah",
    "MN"  => "Muḩāfaz̧at al Minyā",
    "MNF" => "Muḩāfaz̧at al Minūfīyah",
    "KB"  => "Muḩāfaz̧at al Qalyūbīyah",
    "C"   => "Muḩāfaz̧at al Qāhirah",
    "LX"  => "Muḩāfaz̧at al Uqşur",
    "WAD" => "Muḩāfaz̧at al Wādī al Jadīd",
  );
}
