<?php

function location_province_list_ee() {
  return array(
    "37" => "Harju County",
    "39" => "Hiiumaa",
    "44" => "Ida-Virumaa",
    "51" => "Järvamaa",
    "49" => "Jõgevamaa",
    "57" => "Lääne County",
    "59" => "Lääne-Virumaa",
    "67" => "Pärnumaa",
    "65" => "Põlva",
    "70" => "Raplamaa",
    "74" => "Saare County",
    "78" => "Tartu County",
    "82" => "Valgamaa",
    "84" => "Viljandimaa",
    "86" => "Võrumaa",
  );
}
