<?php

function location_province_list_kh () {
	return array (
		"1" => t("Banteay Meanchey Province"),
		"2" => t("Battambang Province"),
		"3" => t("Kampong Cham"),
		"4" => t("Kampong Chhnang"),
		"5" => t("Kampong Speu"),
		"6" => t("Kampong Thom"),
		"7" => t("Kampot"),
		"8" => t("Kandal"),
		"23" => t("Kep"),
		"9" => t("Koh Kong"),
		"10" => t("Kratie"),
		"11" => t("Mondolkiri"),
		"24" => t("Pailin"),
		"12" => t("Phnom Penh"),
		"18" => t("Preah Sihanouk"),
		"13" => t("Preah Vihear"),
		"14" => t("Prey Veng"),
		"15" => t("Pursat"),
		"16" => t("Ratanakiri"),
		"17" => t("Siem Reap"),
		"19" => t("Stung Treng"),
		"20" => t("Svay Rieng"),
		"21" => t("Takeo"),
		"22" => t("Ŏtâr Méanchey"),
	);
}
