<?php

function location_province_list_ua () {
	return array (
		"43" => t("Avtonomna Respublika Krym"),
		"71" => t("Cherkas’ka Oblast’"),
		"74" => t("Chernihivs’ka Oblast’"),
		"77" => t("Chernivets'ka Oblast'"),
		"12" => t("Dnipropetrovska Oblast'"),
		"14" => t("Donets’ka Oblast’"),
		"26" => t("Ivano-Frankivs’ka Oblast’"),
		"63" => t("Kharkivs’ka Oblast’"),
		"65" => t("Khersons’ka Oblast’"),
		"68" => t("Khmel’nyts’ka Oblast’"),
		"35" => t("Kirovohrads’ka Oblast’"),
		"30" => t("Kyiv City"),
		"32" => t("Kyyivs’ka Oblast’"),
		"09" => t("Luhans’ka Oblast’"),
		"46" => t("L’vivs’ka Oblast’"),
		"40" => t("Misto Sevastopol’"),
		"48" => t("Mykolayivs’ka Oblast’"),
		"51" => t("Odes’ka Oblast’"),
		"53" => t("Poltavs’ka Oblast’"),
		"56" => t("Rivnens’ka Oblast’"),
		"59" => t("Sums’ka Oblast’"),
		"61" => t("Ternopil’s’ka Oblast’"),
		"05" => t("Vinnyts’ka Oblast’"),
		"07" => t("Volyns’ka Oblast’"),
		"21" => t("Zakarpattia Oblast"),
		"23" => t("Zaporiz’ka Oblast’"),
		"18" => t("Zhytomyrs’ka Oblast’"),
	);
}
