<?php

function location_province_list_ec() {
  return array(
    "B"  => "Provincia de Bolívar",
    "X"  => "Provincia de Cotopaxi",
    "O"  => "Provincia de El Oro",
    "E"  => "Provincia de Esmeraldas",
    "D"  => "Provincia de Francisco de Orellana",
    "W"  => "Provincia de Galápagos",
    "I"  => "Provincia de Imbabura",
    "L"  => "Provincia de Loja",
    "R"  => "Provincia de Los Ríos",
    "M"  => "Provincia de Manabí",
    "S"  => "Provincia de Morona Santiago",
    "N"  => "Provincia de Napo",
    "P"  => "Provincia de Pichincha",
    "SE" => "Provincia de Santa Elena",
    "SD" => "Provincia de Santo Domingo de los Tsáchilas",
    "U"  => "Provincia de Sucumbíos",
    "Z"  => "Provincia de Zamora Chinchipe",
    "A"  => "Provincia del Azuay",
    "C"  => "Provincia del Carchi",
    "F"  => "Provincia del Cañar",
    "H"  => "Provincia del Chimborazo",
    "G"  => "Provincia del Guayas",
    "Y"  => "Provincia del Pastaza",
    "T"  => "Provincia del Tungurahua",
  );
}
