<?php

function location_province_list_ua() {
  return array(
    "43" => "Avtonomna Respublika Krym",
    "71" => "Cherkas’ka Oblast’",
    "74" => "Chernihivs’ka Oblast’",
    "77" => "Chernivets'ka Oblast'",
    "12" => "Dnipropetrovska Oblast'",
    "14" => "Donets’ka Oblast’",
    "26" => "Ivano-Frankivs’ka Oblast’",
    "63" => "Kharkivs’ka Oblast’",
    "65" => "Khersons’ka Oblast’",
    "68" => "Khmel’nyts’ka Oblast’",
    "35" => "Kirovohrads’ka Oblast’",
    "30" => "Kyiv City",
    "32" => "Kyyivs’ka Oblast’",
    "09" => "Luhans’ka Oblast’",
    "46" => "L’vivs’ka Oblast’",
    "40" => "Misto Sevastopol’",
    "48" => "Mykolayivs’ka Oblast’",
    "51" => "Odes’ka Oblast’",
    "53" => "Poltavs’ka Oblast’",
    "56" => "Rivnens’ka Oblast’",
    "59" => "Sums’ka Oblast’",
    "61" => "Ternopil’s’ka Oblast’",
    "05" => "Vinnyts’ka Oblast’",
    "07" => "Volyns’ka Oblast’",
    "21" => "Zakarpattia Oblast",
    "23" => "Zaporiz’ka Oblast’",
    "18" => "Zhytomyrs’ka Oblast’",
  );
}
