<?php

function location_province_list_cd() {
  return array(
    "BN" => "Bandundu Province",
    "OR" => "Eastern Province",
    "KA" => "Katanga Province",
    "KN" => "Kinshasa City",
    "NK" => "Nord Kivu",
    "EQ" => "Province de l’ Équateur",
    "BC" => "Province du Bas-Congo",
    "KW" => "Province du Kasaï-Occidental",
    "KE" => "Province du Kasaï-Oriental",
    "MA" => "Province du Maniema",
    "SK" => "South Kivu",
  );
}
