<?php

function location_province_list_me() {
  return array(
    "01" => "Andrijevica",
    "02" => "Bar",
    "03" => "Berane",
    "04" => "Bijelo Polje",
    "05" => "Budva",
    "06" => "Cetinje",
    "07" => "Danilovgrad",
    "08" => "Herceg Novi",
    "10" => "Kotor",
    "11" => "Mojkovac",
    "09" => "Opština Kolašin",
    "12" => "Opština Nikšić",
    "13" => "Opština Plav",
    "15" => "Opština Plužine",
    "17" => "Opština Rožaje",
    "18" => "Opština Šavnik",
    "21" => "Opština Žabljak",
    "14" => "Pljevlja",
    "16" => "Podgorica",
    "19" => "Tivat",
    "20" => "Ulcinj",
  );
}
