<?php

function location_province_list_gr () {
	return array (
		"I" => t("Attica"),
		"H" => t("Central Greece"),
		"B" => t("Central Macedonia"),
		"M" => t("Crete"),
		"A" => t("East Macedonia and Thrace"),
		"D" => t("Epirus"),
		"F" => t("Ionian Islands"),
		"69" => t("Mount Athos"),
		"K" => t("North Aegean"),
		"J" => t("Peloponnese"),
		"L" => t("South Aegean"),
		"E" => t("Thessaly"),
		"G" => t("West Greece"),
		"C" => t("West Macedonia"),
	);
}
