<?php

function location_province_list_br() {
  return array(
    "AM" => "Amazonas",
    "PB" => "Estado da Paraíba",
    "AL" => "Estado de Alagoas",
    "BA" => "Estado de Bahía",
    "GO" => "Estado de Goiás",
    "MT" => "Estado de Mato Grosso",
    "MS" => "Estado de Mato Grosso do Sul",
    "MG" => "Estado de Minas Gerais",
    "PE" => "Estado de Pernambuco",
    "RO" => "Estado de Rondônia",
    "RR" => "Estado de Roraima",
    "SC" => "Estado de Santa Catarina",
    "SE" => "Estado de Sergipe",
    "SP" => "Estado de São Paulo",
    "TO" => "Estado de Tocantins",
    "AC" => "Estado do Acre",
    "AP" => "Estado do Amapá",
    "CE" => "Estado do Ceará",
    "ES" => "Estado do Espírito Santo",
    "MA" => "Estado do Maranhão",
    "PR" => "Estado do Paraná",
    "PA" => "Estado do Pará",
    "PI" => "Estado do Piauí",
    "RN" => "Estado do Rio Grande do Norte",
    "RS" => "Estado do Rio Grande do Sul",
    "DF" => "Federal District",
    "RJ" => "Rio de Janeiro",
  );
}
