<?php

function location_province_list_ph () {
	return array (
		"14" => t("Autonomous Region in Muslim Mindanao"),
		"ALB" => t("Bicol"),
		"02" => t("Cagayan Valley"),
		"MDC" => t("Calabarzon"),
		"BUL" => t("Caraga"),
		"AGS" => t("Central Luzon"),
		"07" => t("Central Visayas"),
		"CAN" => t("Cordillera Administrative Region"),
		"BOH" => t("Davao"),
		"08" => t("Eastern Visayas"),
		"01" => t("Ilocos Region"),
		"41" => t("Mimaropa"),
		"00" => t("National Capital Region"),
		"10" => t("Northern Mindanao"),
		"12" => t("Soccsksargen"),
		"06" => t("Western Visayas"),
		"BTG" => t("Zamboanga Peninsula"),
	);
}
