<?php

function location_province_list_tn() {
  return array(
    "13" => "Gouvernorat de Ben Arous",
    "23" => "Gouvernorat de Bizerte",
    "31" => "Gouvernorat de Béja",
    "81" => "Gouvernorat de Gabès",
    "71" => "Gouvernorat de Gafsa",
    "32" => "Gouvernorat de Jendouba",
    "41" => "Gouvernorat de Kairouan",
    "42" => "Gouvernorat de Kasserine",
    "33" => "Gouvernorat de Kef",
    "73" => "Gouvernorat de Kébili",
    "53" => "Gouvernorat de Mahdia",
    "52" => "Gouvernorat de Monastir",
    "82" => "Gouvernorat de Médenine",
    "21" => "Gouvernorat de Nabeul",
    "61" => "Gouvernorat de Sfax",
    "43" => "Gouvernorat de Sidi Bouzid",
    "34" => "Gouvernorat de Siliana",
    "51" => "Gouvernorat de Sousse",
    "72" => "Gouvernorat de Tozeur",
    "11" => "Gouvernorat de Tunis",
    "22" => "Gouvernorat de Zaghouan",
    "12" => "Gouvernorat de l’ Ariana",
    "14" => "Manouba",
    "83" => "Tataouine",
  );
}
