<?php

function location_province_list_hn() {
  return array(
    "IB" => "Bay Islands",
    "AT" => "Departamento de Atlántida",
    "CH" => "Departamento de Choluteca",
    "CL" => "Departamento de Colón",
    "CM" => "Departamento de Comayagua",
    "CP" => "Departamento de Copán",
    "CR" => "Departamento de Cortés",
    "EP" => "Departamento de El Paraíso",
    "FM" => "Departamento de Francisco Morazán",
    "GD" => "Departamento de Gracias a Dios",
    "IN" => "Departamento de Intibucá",
    "LP" => "Departamento de La Paz",
    "LE" => "Departamento de Lempira",
    "OC" => "Departamento de Ocotepeque",
    "OL" => "Departamento de Olancho",
    "SB" => "Departamento de Santa Bárbara",
    "VA" => "Departamento de Valle",
    "YO" => "Departamento de Yoro",
  );
}
