<?php

function location_province_list_mz() {
  return array(
    "P"   => "Cabo Delgado Province",
    "MPM" => "Cidade de Maputo",
    "G"   => "Gaza Province",
    "I"   => "Inhambane Province",
    "B"   => "Manica Province",
    "L"   => "Maputo",
    "N"   => "Nampula",
    "A"   => "Niassa Province",
    "T"   => "Province of Tete",
    "Q"   => "Província de Zambézia",
    "S"   => "Sofala Province",
  );
}
