<?php

function location_province_list_so() {
  return array(
    "AW" => "Awadal Region",
    "BK" => "Bakool Region",
    "BN" => "Banadir Region",
    "BR" => "Bari Region",
    "BY" => "Bay Region",
    "GA" => "Galgadud Region",
    "GE" => "Gedo Region",
    "HI" => "Hiiran Region",
    "JH" => "Jubbada Hoose Region",
    "SH" => "Lower Shabeelle",
    "JD" => "Middle Jubba",
    "MU" => "Mudug Region",
    "NU" => "Nugaal Region",
    "SA" => "Sanaag Region",
    "SD" => "Shabeele Dhexe Region",
    "SO" => "Sool Region",
    "TO" => "Togdheer Region",
    "WO" => "Waqooyi Galbeed Region",
  );
}
