<?php

function location_province_list_pl() {
  return array(
    "WP" => "Greater Poland Voivodeship",
    "KP" => "Kujawsko-Pomorskie",
    "MA" => "Lesser Poland Voivodeship",
    "DS" => "Lower Silesian Voivodeship",
    "LU" => "Lublin Voivodeship",
    "LB" => "Lubusz",
    "MZ" => "Masovian Voivodeship",
    "OP" => "Opole Voivodeship",
    "PD" => "Podlasie",
    "PM" => "Pomeranian Voivodeship",
    "SL" => "Silesian Voivodeship",
    "PK" => "Subcarpathian Voivodeship",
    "WN" => "Warmian-Masurian Voivodeship",
    "ZP" => "West Pomeranian Voivodeship",
    "LD" => "Łódź Voivodeship",
    "SK" => "Świętokrzyskie",
  );
}
