<?php

function location_province_list_sr() {
  return array(
    "BR" => "Distrikt Brokopondo",
    "CM" => "Distrikt Commewijne",
    "CR" => "Distrikt Coronie",
    "MA" => "Distrikt Marowijne",
    "NI" => "Distrikt Nickerie",
    "PR" => "Distrikt Para",
    "PM" => "Distrikt Paramaribo",
    "SA" => "Distrikt Saramacca",
    "SI" => "Distrikt Sipaliwini",
    "WA" => "Distrikt Wanica",
  );
}
