<?php

function location_province_list_al() {
  return array(
    "01" => "Qarku i Beratit",
    "09" => "Qarku i Dibrës",
    "02" => "Qarku i Durrësit",
    "03" => "Qarku i Elbasanit",
    "04" => "Qarku i Fierit",
    "05" => "Qarku i Gjirokastrës",
    "06" => "Qarku i Korçës",
    "07" => "Qarku i Kukësit",
    "08" => "Qarku i Lezhës",
    "10" => "Qarku i Shkodrës",
    "11" => "Qarku i Tiranës",
    "12" => "Qarku i Vlorës",
  );
}
