<?php

function location_province_list_qa() {
  return array(
    "WA" => "Al Wakrah",
    "11" => "Baladīyat Jarayān al Bāţinah",
    "12" => "Baladīyat Umm Sa‘īd",
    "US" => "Baladīyat Umm Şalāl",
    "DA" => "Baladīyat ad Dawḩah",
    "02" => "Baladīyat al Ghuwayrīyah",
    "03" => "Baladīyat al Jumaylīyah",
    "KH" => "Baladīyat al Khawr wa adh Dhakhīrah",
    "RA" => "Baladīyat ar Rayyān",
    "MS" => "Baladīyat ash Shamāl",
    "13" => "Baladīyat az̧ Z̧a‘āyin",
  );
}
