<?php

function location_province_list_my() {
  return array(
    "01" => "Johor",
    "02" => "Kedah",
    "03" => "Kelantan",
    "14" => "Kuala Lumpur",
    "15" => "Labuan",
    "04" => "Melaka",
    "05" => "Negeri Sembilan",
    "06" => "Pahang",
    "08" => "Perak",
    "09" => "Perlis",
    "07" => "Pulau Pinang",
    "16" => "Putrajaya",
    "12" => "Sabah",
    "13" => "Sarawak",
    "10" => "Selangor",
    "11" => "Terengganu",
  );
}
