<?php

function location_province_list_ge() {
  return array(
    "AB" => "Abkhazia",
    "AJ" => "Ajaria",
    "GU" => "Guria",
    "IM" => "Imereti",
    "TB" => "K'alak'i T'bilisi",
    "KA" => "Kakheti",
    "KK" => "Kvemo Kartli",
    "MM" => "Mtskheta-Mtianeti",
    "RL" => "Racha-Lechkhumi and Kvemo Svaneti",
    "SZ" => "Samegrelo and Zemo Svaneti",
    "SJ" => "Samtskhe-Javakheti",
    "SK" => "Shida Kartli",
  );
}
