<?php

function location_province_list_tt() {
  return array(
    "ARI" => "Borough of Arima",
    "CHA" => "Chaguanas",
    "POS" => "City of Port of Spain",
    "SFO" => "City of San Fernando",
    "CTT" => "Couva-Tabaquite-Talparo",
    "DMN" => "Diego Martin",
    "ETO" => "Eastern Tobago",
    "RCM" => "Mayaro",
    "PED" => "Penal/Debe",
    "PTF" => "Point Fortin",
    "PRT" => "Princes Town",
    "SJL" => "San Juan/Laventille",
    "SGE" => "Sangre Grande",
    "SIP" => "Siparia",
    "WTO" => "Tobago",
    "TUP" => "Tunapuna/Piarco",
  );
}
