<?php

function location_province_list_bi() {
  return array(
    "BB" => "Bubanza Province",
    "BM" => "Bujumbura Mairie Province",
    "BL" => "Bujumbura Rural Province",
    "BR" => "Bururi Province",
    "CA" => "Cankuzo Province",
    "CI" => "Cibitoke Province",
    "GI" => "Gitega Province",
    "KR" => "Karuzi Province",
    "KY" => "Kayanza Province",
    "KI" => "Kirundo Province",
    "MA" => "Makamba Province",
    "MU" => "Muramvya Province",
    "MY" => "Muyinga Province",
    "NG" => "Ngozi Province",
    "MW" => "Province de Mwaro",
    "RT" => "Rutana Province",
    "RY" => "Ruyigi Province",
  );
}
