<?php

function location_province_list_pe() {
  return array(
    "AMA" => "Amazonas Region",
    "ANC" => "Ancash Region",
    "APU" => "Apurimac",
    "ARE" => "Arequipa Region",
    "AYA" => "Ayacucho Region",
    "CAJ" => "Cajamarca",
    "CAL" => "Callao",
    "CUS" => "Cusco",
    "MOQ" => "Departamento de Moquegua",
    "HUV" => "Huancavelica Region",
    "ICA" => "Ica Region",
    "JUN" => "Junín",
    "LAL" => "La Libertad Region",
    "LAM" => "Lambayeque Region",
    "LIM" => "Lima Region",
    "LOR" => "Loreto Region",
    "MDD" => "Madre de Dios",
    "PAS" => "Pasco",
    "PIU" => "Piura Region",
    "LMA" => "Provincia de Lima",
    "PUN" => "Puno Region",
    "HUC" => "Región de Huánuco",
    "SAM" => "Región de San Martín",
    "TAC" => "Tacna Region",
    "TUM" => "Tumbes",
    "UCA" => "Ucayali Region",
  );
}
