<?php

function location_province_list_bm() {
  return array(
    "DS" => "Devonshire Parish",
    "HA" => "Hamilton Parish",
    "HC" => "Hamilton city",
    "PG" => "Paget",
    "PB" => "Pembroke Parish",
    "GC" => "Saint George",
    "SG" => "Saint George’s Parish",
    "SA" => "Sandys Parish",
    "SM" => "Smith’s Parish",
    "SH" => "Southampton Parish",
    "WA" => "Warwick Parish",
  );
}
