<?php
/**
 * Implementation of hook_perm().
 */
function forum_perm() {
  return array('Question Forum');
}


/**
 * Implementation of hook_menu().
 */
 
function forum_menu() {	
  $items['question/forum'] = array(
    'title' => ' Forum',
    'page callback' => 'forum_list',
    'access arguments' => array('Question Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );

  return $items;
}



function converttimestamp($indate){

	list($year, $month, $day) = explode('-', $indate);

	$timestamp = mktime(0, 0, 0, $month, $day, $year);

	return $timestamp;

}
