<?php
/**
 * Implementation of hook_perm().
 */
function forum_perm() {
  return array('Question Forum');
}


/**
 * Implementation of hook_menu().
 */
 
function forum_menu() {	
  $items['question/forum'] = array(
    'title' => ' Forum',
    'page callback' => 'forum_list',
    'access arguments' => array('Question Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );

  return $items;
}



function converttimestamp($indate){

	list($year, $month, $day) = explode('-', $indate);

	$timestamp = mktime(0, 0, 0, $month, $day, $year);

	return $timestamp;

}

function cdatetime($timestamp)
{
	if(!$timestamp){
		return 'N/A';
	}
 
	$timestamp = (int)strtotime($timestamp);
	$difference = time() - $timestamp;
	$periods = array("sec", "min", "hour", "day", "week","month", "year", "decade");
	$lengths = array("60","60","24","7","4.35","12","10");
	$total_lengths = count($lengths);
 
	if ($difference > 0) { // this was in the past
		$ending = "ago";
	} else { // this was in the future
		$difference = -$difference;
		$ending = " from now";
	}
	//return;
 
	for($j = 0; $difference > $lengths[$j] && $total_lengths > $j; $j++) {
		$difference /= $lengths[$j];
	}
 
	$difference = round($difference);
	if($difference != 1) {
		$periods[$j].= "s";
	}
 
	$text = "$difference $periods[$j] $ending";
 
	return $text;
}