<?php
/**
 * Implementation of hook_perm().
 */
function forum_perm() {
  return array('Question Forum','Question Forum Submit','Admin Forum','Admin Edit Forum','Admin Forum Wavelets','Resource Forum');
}


/**
 * Implementation of hook_menu().
 */
 
function forum_menu() {	
  $items['question/forum'] = array(
    'title' => ' Forum',
    'page callback' => 'forum_list',
    'access arguments' => array('Question Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
    $items['resource/forum'] = array(
    'title' => 'Resource Forum',
    'page callback' => 'resforum_list',
    'access arguments' => array('Resource Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
	  $items['question/forum/savecmt'] = array(
    'title' => ' Forum',
    'page callback' => 'cmt_submit',
    'access arguments' => array('Question Forum Submit'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
 $items['admin/forum'] = array(
    'title' => 'Admin Forum',
    'page callback' => 'admin_forum',
    'access arguments' => array('Admin Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
  
  $items['admin/forum/edit'] = array(
    'title' => 'Admin Edit Forum',
    'page callback' => 'admin_forum_edit',
    'access arguments' => array('Admin Edit Forum'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
  $items['admin/wavelets'] = array(
    'title' => 'Admin Forum Wavelets',
    'page callback' => 'admin_forum_wlets',
    'access arguments' => array('Admin Forum Wavelets'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  );
  
  $items['admin/wavelets/edit'] = array(
    'title' => 'Admin Forum Wavelets',
    'page callback' => 'admin_wlets_edit',
    'access arguments' => array('Admin Forum Wavelets'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'forum.pages.inc',
  ); 
  return $items;
}


