<?php


function location_cities_list_ba_brc() {
  return array(
    "3203521" => "Brcko",
  );
}


function location_cities_list_ba_bih() {
  return array(
    "3186573" => "Zenica",
    "3187609" => "Visoko",
    "3188225" => "Velika Kladusa",
    "3188582" => "Tuzla",
    "3188924" => "Travnik",
    "3191281" => "Sarajevo",
    "3194828" => "Mostar",
    "3199744" => "Gradacac",
    "3199779" => "Gracanica",
    "3200396" => "Gorazde",
    "3202822" => "Cazin",
    "3203099" => "Bugojno",
    "3203653" => "Bosanska Krupa",
    "3204222" => "Bihac",
    "3337476" => "Konjic",
  );
}


function location_cities_list_ba_srp() {
  return array(
    "3188893" => "Trebinje",
    "3192409" => "Prijedor",
    "3201984" => "Doboj",
    "3204186" => "Bijeljina",
    "3204541" => "Banja Luka",
  );
}
