<?php


function location_cities_list_cf_bb() {
  return array();
}


function location_cities_list_cf_bk() {
  return array(
    "237478" => "Mobaye",
  );
}


function location_cities_list_cf_bgf() {
  return array(
    "2389853" => "Bangui",
  );
}


function location_cities_list_cf_hm() {
  return array();
}


function location_cities_list_cf_hk() {
  return array(
    "239899" => "Bria",
  );
}


function location_cities_list_cf_lb() {
  return array(
    "2384770" => "Mbaiki",
    "2388614" => "Boda",
  );
}


function location_cities_list_cf_hs() {
  return array(
    "2387495" => "Carnot",
    "2389086" => "Berberati",
  );
}


function location_cities_list_cf_mb() {
  return array(
    "240498" => "Bangassou",
  );
}


function location_cities_list_cf_mp() {
  return array(
    "2387435" => "Damara",
    "2388873" => "Bimbo",
  );
}


function location_cities_list_cf_uk() {
  return array(
    "238566" => "Ippy",
    "240604" => "Bambari",
  );
}


function location_cities_list_cf_ac() {
  return array(
    "2388036" => "Bossangoa",
    "2389691" => "Batangafo",
  );
}


function location_cities_list_cf_kg() {
  return array(
    "2383119" => "Sibut",
  );
}


function location_cities_list_cf_kb() {
  return array(
    "2386012" => "Kaga Bandoro",
  );
}


function location_cities_list_cf_nm() {
  return array(
    "2387926" => "Bouar",
  );
}


function location_cities_list_cf_se() {
  return array(
    "2383827" => "Nola",
  );
}


function location_cities_list_cf_op() {
  return array(
    "2383523" => "Paoua",
    "2387546" => "Bozoum",
  );
}


function location_cities_list_cf_vk() {
  return array();
}
