<?php


function location_cities_list_sm_01() {
  return array();
}


function location_cities_list_sm_06() {
  return array();
}


function location_cities_list_sm_03() {
  return array();
}


function location_cities_list_sm_04() {
  return array();
}


function location_cities_list_sm_05() {
  return array();
}


function location_cities_list_sm_08() {
  return array();
}


function location_cities_list_sm_07() {
  return array(
    "3168070" => t("San Marino"),
  );
}


function location_cities_list_sm_02() {
  return array();
}


function location_cities_list_sm_09() {
  return array();
}
