<?php

function location_cities_list_sk_pv () {
	return array (
		"725168" => t("Bardejov"),
		"724627" => t("Humenne"),
		"724503" => t("Kezmarok"),
		"723846" => t("Poprad"),
		"723819" => t("Presov"),
		"723559" => t("Snina"),
		"723505" => t("Stara L'ubovna"),
		"723195" => t("Vranov nad Topl'ou"),
	);
}


function location_cities_list_sk_ki () {
	return array (
		"724443" => t("Kosice"),
		"724144" => t("Michalovce"),
		"723713" => t("Roznava"),
		"723526" => t("Spisska Nova Ves"),
		"723358" => t("Trebisov"),
	);
}


function location_cities_list_sk_bc () {
	return array (
		"3061186" => t("Banska Bystrica"),
		"3060950" => t("Brezno"),
		"3060589" => t("Detva"),
		"3058986" => t("Lucenec"),
		"723736" => t("Rimavska Sobota"),
		"3056523" => t("Ziar nad Hronom"),
		"3056459" => t("Zvolen"),
	);
}


function location_cities_list_sk_ni () {
	return array (
		"3061188" => t("Banovce nad Bebravou"),
		"3060346" => t("Dubnica nad Vahom"),
		"3060139" => t("Handlova"),
		"3059101" => t("Levice"),
		"3058531" => t("Nitra"),
		"3058268" => t("Partizanske"),
		"3058000" => t("Prievidza"),
		"3057963" => t("Puchov"),
		"3057769" => t("Sellye"),
		"3056495" => t("Zlate Moravce"),
	);
}


function location_cities_list_sk_zi () {
	return array (
		"3060835" => t("Cadca"),
		"3060405" => t("Dolny Kubin"),
		"3059179" => t("Kysucke Nove Mesto"),
		"3059050" => t("Liptovsky Mikulas"),
		"3058780" => t("Martin"),
		"3057789" => t("Ruzomberok"),
		"3056508" => t("Zilina"),
	);
}


function location_cities_list_sk_ta () {
	return array (
		"3060308" => t("Dunajska Streda"),
		"3060095" => t("Hlohovec"),
		"3058202" => t("Piestany"),
		"3057691" => t("Senica"),
		"3057630" => t("Skalica"),
		"3057124" => t("Trnava"),
	);
}


function location_cities_list_sk_tc () {
	return array (
		"3058060" => t("Povazska Bystrica"),
		"3057140" => t("Trencin"),
	);
}


function location_cities_list_sk_bl () {
	return array (
		"3060972" => t("Bratislava"),
		"3058897" => t("Malacky"),
		"3058210" => t("Pezinok"),
	);
}


