<?php

function location_cities_list_dz_35 () {
	return array (
		"2506623" => t("Arbatache"),
		"2504739" => t("Beni Amrane"),
		"2503229" => t("Boudouaou"),
		"2474141" => t("Boumerdas"),
		"2501873" => t("Chabet el Ameur"),
		"2500583" => t("Dellys"),
		"2499116" => t("Draa Ben Khedda"),
		"2492991" => t("Isser"),
		"2491913" => t("Khemis el Khechna"),
		"2490297" => t("Makouda"),
		"2486505" => t("Naciria"),
		"2483757" => t("Reghaia"),
		"2478831" => t("Tadmait"),
		"2476917" => t("Thenia"),
		"2475764" => t("Tizi Gheniff"),
	);
}


function location_cities_list_dz_07 () {
	return array (
		"2503826" => t("Biskra"),
		"2480368" => t("Sidi Khaled"),
		"2479916" => t("Sidi Okba"),
		"2475612" => t("Tolga"),
		"2474506" => t("Zeribet el Oued"),
	);
}


function location_cities_list_dz_42 () {
	return array (
		"2508275" => t("'Ain Benian"),
		"2505653" => t("Baraki"),
		"2502939" => t("Bou Ismail"),
		"2501465" => t("Cheraga"),
		"2499193" => t("Douera"),
		"2498752" => t("El Affroun"),
		"2494962" => t("Hadjout"),
		"2491578" => t("Kolea"),
		"2486825" => t("Mouzaia"),
		"2485633" => t("Oued el Alleug"),
		"2482390" => t("Saoula"),
		"2476028" => t("Tipasa"),
		"2474583" => t("Zeralda"),
	);
}


function location_cities_list_dz_48 () {
	return array (
		"2508010" => t("'Ain Merane"),
		"2507155" => t("Ammi Moussa"),
		"2492920" => t("Djidiouia"),
		"2489987" => t("Mazouna"),
		"2485582" => t("Oued Rhiou"),
		"2483668" => t("Relizane"),
		"2474638" => t("Zemoura"),
	);
}


function location_cities_list_dz_30 () {
	return array (
		"2500282" => t("Djamaa"),
		"2498172" => t("El Hadjira"),
		"2494029" => t("Hassi Messaoud"),
		"2488716" => t("Megarine"),
		"2485801" => t("Ouargla"),
		"2482886" => t("Rouissat"),
		"2481058" => t("Sidi Amrane"),
		"2477462" => t("Tebesbest"),
		"2475475" => t("Touggourt"),
	);
}


function location_cities_list_dz_13 () {
	return array (
		"2504616" => t("Beni Mester"),
		"2504385" => t("Bensekrane"),
		"2501362" => t("Chetouane"),
		"2493918" => t("Hennaya"),
		"2490183" => t("Mansoura"),
		"2486284" => t("Nedroma"),
		"2484846" => t("Ouled Mimoun"),
		"2483649" => t("Remchi"),
		"2482211" => t("Sebdou"),
		"2481389" => t("Sidi Abdelli"),
		"2475687" => t("Tlemcen"),
	);
}


function location_cities_list_dz_15 () {
	return array (
		"2508152" => t("'Ain el Hammam"),
		"2506519" => t("Arhribs"),
		"2506043" => t("Azazga"),
		"2504703" => t("Beni Douala"),
		"2503755" => t("Boghni"),
		"2503237" => t("Boudjima"),
		"2501508" => t("Chemini"),
		"2496241" => t("Freha"),
		"2493605" => t("Ighram"),
		"2491042" => t("L'Arbaa Nait Irathen"),
		"2488500" => t("Mekla"),
		"2476396" => t("Timizart"),
		"2475921" => t("Tirmitine"),
		"2475744" => t("Tizi Ouzou"),
		"2475740" => t("Tizi Rached"),
		"2475752" => t("Tizi-n-Tleta"),
	);
}


function location_cities_list_dz_38 () {
	return array (
		"2475860" => t("Tissemsilt"),
	);
}


function location_cities_list_dz_37 () {
	return array (
		"2476301" => t("Tindouf"),
	);
}


function location_cities_list_dz_01 () {
	return array (
		"2508813" => t("Adrar"),
		"2506795" => t("Aoulef"),
		"2483761" => t("Reggane"),
		"2476403" => t("Timimoun"),
	);
}


function location_cities_list_dz_06 () {
	return array (
		"2507646" => t("Akbou"),
		"2507169" => t("Amizour"),
		"2505651" => t("Barbacha"),
		"2505329" => t("Bejaia"),
		"2497796" => t("El Kseur"),
		"2496573" => t("Feraoun"),
		"2482159" => t("Seddouk"),
		"2476412" => t("el hed"),
	);
}


function location_cities_list_dz_14 () {
	return array (
		"2508225" => t("'Ain Deheb"),
		"2496232" => t("Frenda"),
		"2491335" => t("Ksar Chellala"),
		"2488616" => t("Mehdia"),
		"2479247" => t("Sougueur"),
		"2476897" => t("Tiaret"),
	);
}


function location_cities_list_dz_44 () {
	return array (
		"2508228" => t("Ain Defla"),
		"2498782" => t("El Abadia"),
		"2498590" => t("El Attaf"),
		"2491911" => t("Khemis Miliana"),
		"2476915" => t("Theniet el Had"),
	);
}


function location_cities_list_dz_43 () {
	return array (
		"2501541" => t("Chelghoum el Aid"),
		"2487452" => t("Mila"),
		"2482939" => t("Rouached"),
		"2480198" => t("Sidi Merouane"),
		"2477255" => t("Telerghma"),
	);
}


function location_cities_list_dz_12 () {
	return array (
		"2503878" => t("Bir el Ater"),
		"2501404" => t("Cheria"),
		"2494548" => t("Hammamet"),
		"2477461" => t("Tebessa"),
	);
}


function location_cities_list_dz_05 () {
	return array (
		"2507877" => t("Ain Touta"),
		"2506404" => t("Arris"),
		"2505629" => t("Barika"),
		"2505572" => t("Batna"),
		"2487882" => t("Merouana"),
		"2483968" => t("Ras el Aioun"),
		"2477528" => t("Tazoult-Lambese"),
	);
}


function location_cities_list_dz_11 () {
	return array (
		"2493222" => t("I-n-Salah"),
		"2478216" => t("Tamanrasset"),
	);
}


function location_cities_list_dz_21 () {
	return array (
		"2505915" => t("Azzaba"),
		"2492345" => t("Kerkera"),
		"2479536" => t("Skikda"),
		"2478226" => t("Tamalous"),
	);
}


function location_cities_list_dz_10 () {
	return array (
		"2508268" => t("Ain Bessem"),
		"2502958" => t("Bouira"),
		"2501289" => t("Chorfa"),
		"2499104" => t("Draa el Mizan"),
		"2491134" => t("Lakhdaria"),
		"2479161" => t("Sour el Ghozlane"),
	);
}


function location_cities_list_dz_09 () {
	return array (
		"2504622" => t("Beni Mered"),
		"2503769" => t("Blida"),
		"2503468" => t("Bou Arfa"),
		"2503181" => t("Boufarik"),
		"2503147" => t("Bougara"),
		"2502962" => t("Bouinan"),
		"2501680" => t("Chebli"),
		"2501323" => t("Chiffa"),
		"2491050" => t("L'Arba"),
		"2488722" => t("Meftah"),
		"2479966" => t("Sidi Moussa"),
		"2479183" => t("Souma"),
	);
}


function location_cities_list_dz_41 () {
	return array (
		"2482090" => t("Sedrata"),
		"2479215" => t("Souk Ahras"),
	);
}


function location_cities_list_dz_29 () {
	return array (
		"2503033" => t("Bou Hanifia el Hamamat"),
		"2490098" => t("Mascara"),
		"2485636" => t("Oued el Abtal"),
		"2479609" => t("Sig"),
	);
}


function location_cities_list_dz_31 () {
	return array (
		"2508119" => t("'Ain el Turk"),
		"2508174" => t("Ain el Bya"),
		"2503874" => t("Bir el Djir"),
		"2502239" => t("Bou Tlelis"),
		"2497060" => t("Es Senia"),
		"2487852" => t("Mers el Kebir"),
		"2485926" => t("Oran"),
		"2480618" => t("Sidi ech Chahmi"),
	);
}


function location_cities_list_dz_22 () {
	return array (
		"2508180" => t("'Ain el Berd"),
		"2481639" => t("Sfizef"),
		"2481007" => t("Sidi Bel Abbes"),
	);
}


function location_cities_list_dz_02 () {
	return array (
		"2509031" => t("Abou el Hassan"),
		"2502924" => t("Boukadir"),
		"2498611" => t("Chlef"),
		"2498954" => t("Ech Chettia"),
		"2485618" => t("Oued Fodda"),
		"2485572" => t("Oued Sly"),
		"2481207" => t("Sidi Akkacha"),
	);
}


function location_cities_list_dz_28 () {
	return array (
		"2508130" => t("'Ain el Melh"),
		"2486690" => t("M'Sila"),
		"2481246" => t("Sidi Aissa"),
		"2508157" => t("`Ain el Hadjel"),
	);
}


function location_cities_list_dz_19 () {
	return array (
		"2508297" => t("Ain Arnat"),
		"6698360" => t("BABOR - VILLE"),
		"2503156" => t("Bougaa"),
		"2498392" => t("El Eulma"),
		"2482447" => t("Salah Bey"),
		"2481700" => t("Setif"),
	);
}


function location_cities_list_dz_20 () {
	return array (
		"2482572" => t("Saida"),
	);
}


function location_cities_list_dz_16 () {
	return array (
		"2507912" => t("Ain Taya"),
		"2507480" => t("Algiers"),
		"2505854" => t("Bab Ezzouar"),
		"2503847" => t("Birkhadem"),
		"2503661" => t("Bordj el Kiffan"),
		"2500889" => t("Dar el Beida"),
		"2482908" => t("Rouiba"),
	);
}


function location_cities_list_dz_39 () {
	return array (
		"2500737" => t("Debila"),
		"2497411" => t("El Oued"),
		"2483746" => t("Reguiba"),
		"2483000" => t("Robbah"),
	);
}


function location_cities_list_dz_34 () {
	return array (
		"2503701" => t("Bordj Bou Arreridj"),
		"2503654" => t("Bordj Ghdir"),
		"2503620" => t("Bordj Zemoura"),
		"2498766" => t("El Achir"),
		"2490180" => t("Mansourah"),
		"2488202" => t("Melouza"),
		"2483936" => t("Ras el Oued"),
	);
}


function location_cities_list_dz_04 () {
	return array (
		"2508287" => t("Ain Beida"),
		"2508102" => t("Ain Fakroun"),
		"2508059" => t("Ain Kercha"),
		"2498667" => t("El Aouinet"),
		"2487805" => t("Meskiana"),
		"2484620" => t("Oum el Bouaghi"),
	);
}


function location_cities_list_dz_27 () {
	return array (
		"2487134" => t("Mostaganem"),
	);
}


function location_cities_list_dz_47 () {
	return array (
		"2504110" => t("Berriane"),
		"2496049" => t("Ghardaia"),
		"2487620" => t("Metlili Chaamba"),
	);
}


function location_cities_list_dz_17 () {
	return array (
		"2508184" => t("'Ain el Bell"),
		"2507972" => t("Ain Oussera"),
		"2503852" => t("Birine"),
		"2501767" => t("Charef"),
		"2500904" => t("Dar Chioukh"),
		"2500017" => t("Djelfa"),
		"2498000" => t("El Idrissia"),
		"2487772" => t("Messaad"),
	);
}


function location_cities_list_dz_26 () {
	return array (
		"2504099" => t("Berrouaghia"),
		"2491323" => t("Ksar el Boukhari"),
		"2488835" => t("Medea"),
	);
}


function location_cities_list_dz_03 () {
	return array (
		"2508737" => t("Aflou"),
		"2491191" => t("Laghouat"),
	);
}


function location_cities_list_dz_40 () {
	return array (
		"2491889" => t("Khenchela"),
	);
}


function location_cities_list_dz_18 () {
	return array (
		"2492913" => t("Jijel"),
	);
}


function location_cities_list_dz_24 () {
	return array (
		"2502686" => t("Boumahra Ahmed"),
		"2495662" => t("Guelma"),
		"2493956" => t("Heliopolis"),
	);
}


function location_cities_list_dz_46 () {
	return array (
		"2507901" => t("'Ain Temouchent"),
		"2504581" => t("Beni Saf"),
		"2498704" => t("El Amria"),
		"2497714" => t("El Malah"),
		"2494554" => t("Hammam Bou Hadjar"),
	);
}


function location_cities_list_dz_25 () {
	return array (
		"2508309" => t("'Ain Abid"),
		"2507926" => t("Ain Smara"),
		"2501152" => t("Constantine"),
		"2500401" => t("Didouche Mourad"),
		"2497849" => t("El Khroub"),
		"2494610" => t("Hamma Bouziane"),
	);
}


function location_cities_list_dz_36 () {
	return array (
		"2504486" => t("Ben Mehidi"),
		"2504072" => t("Besbes"),
		"2497988" => t("El Kala"),
		"2497323" => t("El Tarf"),
	);
}


function location_cities_list_dz_23 () {
	return array (
		"2506999" => t("Annaba"),
		"2504136" => t("Berrahal"),
		"2499055" => t("Drean"),
		"2498183" => t("El Hadjar"),
	);
}


function location_cities_list_dz_32 () {
	return array (
		"2502034" => t("Brezina"),
		"2498775" => t("El Abiodh Sidi Cheikh"),
		"2498543" => t("El Bayadh"),
	);
}


function location_cities_list_dz_08 () {
	return array (
		"2505530" => t("Bechar"),
	);
}


function location_cities_list_dz_45 () {
	return array (
		"2507943" => t("Ain Sefra"),
	);
}


