<?php

function location_cities_list_kn_ccn()
{
	return array(
		'3575533' => t('Bourryau'),
		'3575316' => t('Lodge'),
		'3575300' => t('Mansion'),
		'3575288' => t('Molineaux'),
		'3575251' => t('Nicola Town'),
		'3575216' => t('Phillips'),
	);
}
function location_cities_list_kn_sas()
{
	return array(
		'3575508' => t('Burts'),
		'3575452' => t('Craddocks'),
		'3575422' => t('Fig Tree'),
		'3575156' => t('Sandy Point Town'),
	);
}
function location_cities_list_kn_sgb()
{
	return array(
		'3575551' => t('Basseterre'),
		'3575334' => t('Kit Stoddart’s'),
		'3575322' => t('Limekiln'),
	);
}
function location_cities_list_kn_sgg()
{
	return array(
		'3575558' => t('Bachelors Hall'),
		'3575512' => t('Buck’s Hill'),
		'3575478' => t('Chicken Stone'),
		'3575448' => t('Crook’s Ground'),
		'3575424' => t('Fenton Hill'),
		'3575419' => t('Fothergill'),
		'3575403' => t('Gingerland'),
		'3575380' => t('Hardtimes'),
		'3575377' => t('Harris'),
		'3575363' => t('Hichmans'),
		'3575356' => t('Holmes Hill'),
		'3575350' => t('Hull Ground'),
		'3575296' => t('Market Shop'),
		'3575294' => t('Maynards Ground'),
		'3575257' => t('New River'),
		'3575198' => t('Rawlins'),
		'3575195' => t('Rices'),
		'3575155' => t('Scarborough'),
		'3575149' => t('Sherriffs'),
		'3575130' => t('Stonyhill'),
		'3575124' => t('Taylors Pasture'),
		'3575099' => t('Webb’s Ground'),
		'3575078' => t('Zetlands'),
		'3575076' => t('Zion'),
	);
}
function location_cities_list_kn_sjw()
{
	return array(
		'3575553' => t('Barnabys Village'),
		'3575527' => t('Brick Kiln'),
		'3575510' => t('Burnaby'),
		'3575504' => t('Butlers'),
		'3575493' => t('Camps'),
		'3575417' => t('Fountain'),
		'3575361' => t('Hick’s'),
		'3575306' => t('Maddens'),
		'3575301' => t('Mannings'),
		'3575274' => t('Mount Lily'),
		'3575261' => t('Newcastle'),
		'3575197' => t('Rawlins'),
		'3575090' => t('Whitehall'),
	);
}
function location_cities_list_kn_sjc()
{
	return array(
		'3575542' => t('Belle Vue'),
		'3575529' => t('Brambles'),
		'3575441' => t('Dieppe Bay Town'),
		'3575405' => t('Geagans'),
		'3575378' => t('Harris'),
		'3575353' => t('Houstons'),
		'3575309' => t('Lucas'),
		'3575222' => t('Parson’s Ground'),
		'3575186' => t('Sadlers'),
		'3575126' => t('Tabernacle'),
	);
}
function location_cities_list_kn_sjf()
{
	return array(
		'3575549' => t('Bath'),
		'3575544' => t('Beaumont'),
		'3575516' => t('Brown Hill'),
		'3575515' => t('Brown Pasture'),
		'3575475' => t('Church Ground'),
		'3575465' => t('Cole Hill'),
		'3575456' => t('Cox'),
		'3575423' => t('Fig Tree'),
		'3575283' => t('Montpelier'),
		'3575219' => t('Pembroke'),
		'3575207' => t('Pond Hill'),
	);
}
function location_cities_list_kn_smc()
{
	return array(
		'3575487' => t('Cayon'),
		'3575446' => t('Dalzells'),
		'3575367' => t('Hermitage'),
		'3575336' => t('Key'),
		'3575233' => t('Ottley’s'),
	);
}
function location_cities_list_kn_cap()
{
	return array(
		'3575468' => t('Cliftons'),
		'3575371' => t('Heldens'),
		'3575254' => t('Newton Ground'),
		'3575170' => t('Saint Paul’s'),
		'3575091' => t('Whitegate'),
	);
}
function location_cities_list_kn_cha()
{
	return array(
		'3575479' => t('Charlestown'),
	);
}
function location_cities_list_kn_spb()
{
	return array(
		'3575546' => t('Bayford’s'),
		'3575492' => t('Canada'),
		'3575438' => t('Douglas'),
		'3575400' => t('Golden Rock'),
		'3575394' => t('Greatheeds'),
		'3575341' => t('John England Village'),
		'3575284' => t('Monkey Hill'),
		'3575244' => t('Ogee’s'),
		'3575224' => t('Parry’s'),
		'3575136' => t('Stapleton'),
		'3575109' => t('Upper Conaree'),
	);
}
function location_cities_list_kn_stl()
{
	return array(
		'3575552' => t('Barnes Ghaut'),
		'3575469' => t('Cliftons'),
		'3575458' => t('Cotton Ground'),
		'3575344' => t('Jessup'),
		'3575106' => t('Vaughans'),
		'3575097' => t('Westbury'),
	);
}
function location_cities_list_kn_stm()
{
	return array(
		'3575384' => t('Half Way Tree'),
		'3575292' => t('Middle Island'),
		'3575240' => t('Old Road Town'),
		'3575191' => t('Romneys'),
		'3575081' => t('Wingfield Manor'),
	);
}
function location_cities_list_kn_tpp()
{
	return array(
		'3575531' => t('Boyd’s'),
		'3575483' => t('Challengers'),
		'3575234' => t('Ottley’s'),
		'3575115' => t('Trinity'),
	);
}
