<?php

function location_cities_list_ni_mn () {
	return array (
		"3828262" => t("Ciudad Sandino"),
		"3619853" => t("El Crucero"),
		"3617763" => t("Managua"),
		"3616594" => t("San Rafael del Sur"),
		"3616035" => t("Tipitapa"),
	);
}


function location_cities_list_ni_md () {
	return array (
		"3616232" => t("Somoto"),
	);
}


function location_cities_list_ni_ci () {
	return array (
		"3620390" => t("Chichigalpa"),
		"3620381" => t("Chinandega"),
		"3620269" => t("Corinto"),
		"3619267" => t("El Viejo"),
		"3616234" => t("Somotillo"),
	);
}


function location_cities_list_ni_an () {
	return array (
		"3617154" => t("Bilwi"),
		"3616253" => t("Siuna"),
	);
}


function location_cities_list_ni_ca () {
	return array (
		"3620170" => t("Diriamba"),
		"3618926" => t("Jinotepe"),
		"3616682" => t("San Marcos"),
	);
}


function location_cities_list_ni_ri () {
	return array (
		"3617052" => t("Rivas"),
	);
}


function location_cities_list_ni_mt () {
	return array (
		"3617708" => t("Matagalpa"),
		"3617069" => t("Rio Blanco"),
	);
}


function location_cities_list_ni_as () {
	return array (
		"3620680" => t("Bluefields"),
		"3617459" => t("Nueva Guinea"),
		"3617095" => t("Rama"),
	);
}


function location_cities_list_ni_ns () {
	return array (
		"3618954" => t("Jalapa"),
		"3617448" => t("Ocotal"),
	);
}


function location_cities_list_ni_gr () {
	return array (
		"3619136" => t("Granada"),
		"3617513" => t("Nandaime"),
	);
}


function location_cities_list_ni_le () {
	return array (
		"3618411" => t("La Paz Centro"),
		"3618030" => t("Leon"),
		"3617522" => t("Nagarote"),
	);
}


function location_cities_list_ni_ms () {
	return array (
		"3617725" => t("Masatepe"),
		"3617723" => t("Masaya"),
	);
}


function location_cities_list_ni_co () {
	return array (
		"3618908" => t("Juigalpa"),
	);
}


function location_cities_list_ni_ji () {
	return array (
		"3618929" => t("Jinotega"),
	);
}


function location_cities_list_ni_es () {
	return array (
		"3619194" => t("Esteli"),
	);
}


function location_cities_list_ni_bo () {
	return array (
		"3620674" => t("Boaco"),
		"3620544" => t("Camoapa"),
	);
}


