<?php


function location_cities_list_mg_7670851() {
  return array(
    "1058532" => "Moramanga",
    "1076194" => "Andilamena",
    "1078446" => "Amparafaravola",
    "1082639" => "Ambatondrazaka",
  );
}


function location_cities_list_mg_7670904() {
  return array(
    "1065222" => "Fandriana",
    "1079088" => "Ambositra",
    "1083239" => "Ambatofinandrahana",
  );
}


function location_cities_list_mg_7670856() {
  return array(
    "1057688" => "Sadabe",
    "1060673" => "Manjakandriana",
    "1070940" => "Antananarivo",
    "1072711" => "Ankazondandy",
    "1072849" => "Ankazobe",
    "1073482" => "Anjozorobe",
    "1079777" => "Ambohitrolomahitsy",
    "1084740" => "Alarobia",
  );
}


function location_cities_list_mg_7670848() {
  return array(
    "1054192" => "Vavatenina",
    "1056386" => "Soanierana Ivongo",
    "1060283" => "Maroantsetra",
    "1061412" => "Mananara",
    "1064980" => "Fenoarivo Atsinanana",
  );
}


function location_cities_list_mg_7670911() {
  return array(
    "1054500" => "Tsiombe",
    "1067565" => "Beloha",
    "1079048" => "Ambovombe",
  );
}


function location_cities_list_mg_7670910() {
  return array(
    "1055433" => "Fort Dauphin",
    "1081790" => "Amboasary",
  );
}


function location_cities_list_mg_7670913() {
  return array(
    "1055429" => "Toliara",
    "1057095" => "Sakaraha",
    "1066310" => "Betioky",
    "1066831" => "Beroroha",
    "1072879" => "Ankazoabo",
    "1078553" => "Ampanihy",
  );
}


function location_cities_list_mg_7670908() {
  return array(
    "1053507" => "Vondrozo",
    "1053778" => "Vohipaho",
    "1054329" => "Vangaindrano",
    "1065158" => "Farafangana",
  );
}


function location_cities_list_mg_7670857() {
  return array(
    "1053384" => "Toamasina",
    "1054035" => "Vohibinany",
    "1060007" => "Marolambo",
    "1062553" => "Mahanoro",
  );
}


function location_cities_list_mg_7670850() {
  return array(
    "1055059" => "Tsaratanana",
    "1062842" => "Maevatanana",
  );
}


function location_cities_list_mg_7670849() {
  return array(
    "1056531" => "Sitampiky",
    "1059507" => "Marovoay",
    "1062663" => "Mahajanga",
    "1083257" => "Ambato Boeny",
  );
}


function location_cities_list_mg_7670853() {
  return array(
    "1054463" => "Tsiroanomandidy",
    "1064978" => "Fenoarivo Be",
  );
}


function location_cities_list_mg_7670842() {
  return array(
    "1068955" => "Antsohimbondrona",
    "1069129" => "Antsiranana",
    "1076105" => "Andoany",
    "1082243" => "Ambilobe",
    "1083676" => "Ambarakaraka",
    "1083724" => "Ambanja",
  );
}


function location_cities_list_mg_7670907() {
  return array(
    "1064275" => "Ihosy",
  );
}


function location_cities_list_mg_7670855() {
  return array(
    "1056151" => "Soavinandriana",
    "1068865" => "Arivonimamo",
  );
}


function location_cities_list_mg_7670852() {
  return array(
    "1061912" => "Maintirano",
  );
}


function location_cities_list_mg_7670902() {
  return array(
    "1058381" => "Morondava",
    "1059051" => "Miandrivazo",
    "1067531" => "Belo sur Tsiribihina",
  );
}


function location_cities_list_mg_7670846() {
  return array(
    "1056899" => "Sambava",
    "1071296" => "Antalaha",
    "1076454" => "Andapa",
    "1078966" => "Ampahana",
  );
}


function location_cities_list_mg_7670847() {
  return array(
    "1068670" => "Bealanana",
    "1068971" => "Antsohihy",
  );
}


function location_cities_list_mg_7670905() {
  return array(
    "1064258" => "Ikalamavony",
    "1064890" => "Fianarantsoa",
    "1083968" => "Ambalavao",
  );
}


function location_cities_list_mg_7670854() {
  return array(
    "1056381" => "Soanindrariny",
    "1059059" => "Miandrarivo",
    "1065140" => "Faratsiho",
    "1066514" => "Betafo",
    "1069166" => "Antsirabe",
    "1070661" => "Antanifotsy",
    "1082992" => "Ambatolampy",
  );
}


function location_cities_list_mg_7670906() {
  return array(
    "1057277" => "Sahavato",
    "1058080" => "Nosy Varika",
    "1061335" => "Mananjary",
    "1061605" => "Manakara",
    "1064234" => "Ikongo",
    "1064366" => "Ifanadiana",
    "1081863" => "Amboanjo",
  );
}
