<?php

function location_cities_list_pl_mz () {
	return array (
		"776251" => t("Bemowo"),
		"776103" => t("Bialoleka"),
		"776029" => t("Bielany"),
		"774208" => t("Ciechanow"),
		"772339" => t("Garwolin"),
		"3098619" => t("Gostynin"),
		"771401" => t("Grodzisk Mazowiecki"),
		"769981" => t("Jozefow"),
		"769893" => t("Kabaty"),
		"768905" => t("Kobylka"),
		"768216" => t("Konstancin-Jeziorna"),
		"767814" => t("Kozienice"),
		"766555" => t("Legionowo"),
		"766042" => t("Lomianki"),
		"765191" => t("Marki"),
		"764749" => t("Milanowek"),
		"764679" => t("Minsk Mazowiecki"),
		"764634" => t("Mlawa"),
		"764484" => t("Mokotow"),
		"763556" => t("Nowy Dwor Mazowiecki"),
		"763442" => t("Ochota"),
		"762909" => t("Ostroleka"),
		"762850" => t("Ostrow Mazowiecka"),
		"762788" => t("Otwock"),
		"762423" => t("Piaseczno"),
		"762381" => t("Piastow"),
		"762199" => t("Pionki"),
		"3088825" => t("Plock"),
		"762021" => t("Plonsk"),
		"6545347" => t("Praga Polnoc"),
		"6545348" => t("Praga Poludnie"),
		"761228" => t("Pruszkow"),
		"761218" => t("Przasnysz"),
		"760917" => t("Pultusk"),
		"760778" => t("Radom"),
		"760503" => t("Rembertow"),
		"759412" => t("Siedlce"),
		"3085941" => t("Sierpc"),
		"758682" => t("Sochaczew"),
		"758626" => t("Sokolow Podlaski"),
		"758470" => t("Srodmiescie"),
		"757809" => t("Sulejowek"),
		"757065" => t("Targowek"),
		"756320" => t("Ursus"),
		"6545326" => t("Ursynow"),
		"756135" => t("Warsaw"),
		"756092" => t("Wawer"),
		"756004" => t("Wesola"),
		"755475" => t("Wlochy"),
		"755330" => t("Wola"),
		"754800" => t("Wolomin"),
		"754454" => t("Wyszkow"),
		"754351" => t("Zabki"),
		"753276" => t("Zielonka"),
		"753142" => t("Zoliborz"),
		"752967" => t("Zyrardow"),
	);
}


function location_cities_list_pl_lu () {
	return array (
		"776175" => t("Biala Podlaska"),
		"775922" => t("Bilgoraj"),
		"774558" => t("Chelm"),
		"773357" => t("Deblin"),
		"770966" => t("Hrubieszow"),
		"767623" => t("Krasnik"),
		"767605" => t("Krasnystaw"),
		"766583" => t("Leczna"),
		"765927" => t("Lubartow"),
		"765876" => t("Lublin"),
		"765749" => t("Lukow"),
		"764862" => t("Miedzyrzec Podlaski"),
		"760924" => t("Pulawy"),
		"760680" => t("Radzyn Podlaski"),
		"757692" => t("Swidnik"),
		"756868" => t("Tomaszow Lubelski"),
		"753866" => t("Zamosc"),
	);
}


function location_cities_list_pl_pd () {
	return array (
		"776597" => t("Augustow"),
		"776069" => t("Bialystok"),
		"775986" => t("Bielsk Podlaski"),
		"771506" => t("Grajewo"),
		"771158" => t("Hajnowka"),
		"766783" => t("Lapy"),
		"766027" => t("Lomza"),
		"759320" => t("Siemiatycze"),
		"758651" => t("Sokolka"),
		"757718" => t("Suwalki"),
		"753895" => t("Zambrow"),
	);
}


function location_cities_list_pl_ma () {
	return array (
		"3104115" => t("Andrychow"),
		"775758" => t("Bochnia"),
		"775183" => t("Brzesko"),
		"3101547" => t("Chrzanow"),
		"771804" => t("Gorlice"),
		"3096328" => t("Kety"),
		"3094802" => t("Krakow"),
		"3093457" => t("Libiaz"),
		"3091256" => t("Myslenice"),
		"763534" => t("Nowy Sacz"),
		"763523" => t("Nowy Targ"),
		"3090146" => t("Olkusz"),
		"3089658" => t("Oswiecim"),
		"3085807" => t("Skawina"),
		"757026" => t("Tarnow"),
		"3083111" => t("Trzebinia"),
		"3082722" => t("Wadowice"),
		"755889" => t("Wieliczka"),
		"3080866" => t("Zakopane"),
	);
}


function location_cities_list_pl_ld () {
	return array (
		"3104132" => t("Aleksandrow Lodzki"),
		"3103709" => t("Belchatow"),
		"3099180" => t("Glowno"),
		"3095277" => t("Konstantynow Lodzki"),
		"3094170" => t("Kutno"),
		"3093902" => t("Lask"),
		"3093726" => t("Leczyca"),
		"3093133" => t("Lodz"),
		"3093066" => t("Lowicz"),
		"763111" => t("Opoczno"),
		"3089582" => t("Ozorkow"),
		"3089578" => t("Pabianice"),
		"3088972" => t("Piotrkow Trybunalski"),
		"3087497" => t("Radomsko"),
		"760584" => t("Rawa Mazowiecka"),
		"3085978" => t("Sieradz"),
		"759123" => t("Skierniewice"),
		"756867" => t("Tomaszow Mazowiecki"),
		"3082197" => t("Wielun"),
		"3080414" => t("Zdunska Wola"),
		"3080251" => t("Zgierz"),
	);
}


function location_cities_list_pl_pk () {
	return array (
		"773380" => t("Debica"),
		"770380" => t("Jaroslaw"),
		"770293" => t("Jaslo"),
		"767470" => t("Krosno"),
		"766810" => t("Lancut"),
		"764849" => t("Mielec"),
		"763829" => t("Nisko"),
		"761168" => t("Przemysl"),
		"761131" => t("Przeworsk"),
		"760343" => t("Ropczyce"),
		"759734" => t("Rzeszow"),
		"759591" => t("Sanok"),
		"758445" => t("Stalowa Wola"),
		"757033" => t("Tarnobrzeg"),
	);
}


function location_cities_list_pl_wn () {
	return array (
		"776337" => t("Bartoszyce"),
		"3102677" => t("Braniewo"),
		"772748" => t("Dzialdowo"),
		"3099759" => t("Elblag"),
		"772621" => t("Elk"),
		"772227" => t("Gierloz"),
		"772195" => t("Gizycko"),
		"3097902" => t("Ilawa"),
		"769274" => t("Ketrzyn"),
		"766307" => t("Lidzbark Warminski"),
		"764312" => t("Mragowo"),
		"763291" => t("Olecko"),
		"763166" => t("Olsztyn"),
		"3089779" => t("Ostroda"),
		"762120" => t("Pisz"),
		"757357" => t("Szczytno"),
	);
}


function location_cities_list_pl_sk () {
	return array (
		"774747" => t("Busko-Zdroj"),
		"770157" => t("Jedrzejow"),
		"769250" => t("Kielce"),
		"768218" => t("Konskie"),
		"762863" => t("Ostrowiec Swietokrzyski"),
		"759603" => t("Sandomierz"),
		"759141" => t("Skarzysko-Kamienna"),
		"758390" => t("Starachowice"),
		"758252" => t("Staszow"),
	);
}


function location_cities_list_pl_sl () {
	return array (
		"3103719" => t("Bedzin"),
		"3103402" => t("Bielsko-Biala"),
		"3103365" => t("Bierun"),
		"3101950" => t("Bytom"),
		"3101619" => t("Chorzow"),
		"3101321" => t("Cieszyn"),
		"3101076" => t("Czechowice-Dziedzice"),
		"3101057" => t("Czeladz"),
		"3100974" => t("Czerwionka-Leszczyny"),
		"3100946" => t("Czestochowa"),
		"3100796" => t("Dabrowa Gornicza"),
		"3099230" => t("Gliwice"),
		"3097391" => t("Jastrzebie Zdroj"),
		"3097333" => t("Jaworzno"),
		"3096472" => t("Katowice"),
		"3095971" => t("Knurow"),
		"3093785" => t("Laziska Gorne"),
		"3093708" => t("Ledziny"),
		"3092906" => t("Lubliniec"),
		"3091831" => t("Mikolow"),
		"3091232" => t("Myslowice"),
		"3091217" => t("Myszkow"),
		"3089965" => t("Orzesze"),
		"3089125" => t("Piekary Slaskie"),
		"3087705" => t("Pszczyna"),
		"3087628" => t("Pyskowice"),
		"3087584" => t("Raciborz"),
		"3087529" => t("Radlin"),
		"3087418" => t("Radzionkow"),
		"3086800" => t("Ruda Slaska"),
		"3086586" => t("Rybnik"),
		"3086531" => t("Rydultowy"),
		"3086024" => t("Siemianowice Slaskie"),
		"3085128" => t("Sosnowiec"),
		"3083988" => t("Swietochlowice"),
		"3083440" => t("Tarnowskie Gory"),
		"3082914" => t("Tychy"),
		"3082751" => t("Ustron"),
		"3081677" => t("Wodzislaw Slaski"),
		"3080985" => t("Zabrze"),
		"3080526" => t("Zawiercie"),
		"3080004" => t("Zory"),
		"3079855" => t("Zywiec"),
	);
}


function location_cities_list_pl_wp () {
	return array (
		"3101680" => t("Chodziez"),
		"3099112" => t("Gniezno"),
		"3098625" => t("Gostyn"),
		"3097528" => t("Jarocin"),
		"3096880" => t("Kalisz"),
		"3095797" => t("Kolo"),
		"3095321" => t("Konin"),
		"3095151" => t("Koscian"),
		"3094625" => t("Krotoszyn"),
		"3093524" => t("Leszno"),
		"3092856" => t("Lubon"),
		"3090452" => t("Nowy Tomysl"),
		"3090403" => t("Oborniki"),
		"3089684" => t("Ostrow Wielkopolski"),
		"3089033" => t("Pila"),
		"3088848" => t("Pleszew"),
		"3088171" => t("Poznan"),
		"3087307" => t("Rawicz"),
		"3085056" => t("Srem"),
		"3085045" => t("Sroda Wielkopolska"),
		"3084130" => t("Swarzedz"),
		"3083878" => t("Szamotuly"),
		"3083185" => t("Trzcianka"),
		"3082998" => t("Turek"),
		"3082712" => t("Wagrowiec"),
		"3081324" => t("Wrzesnia"),
		"3080071" => t("Zlotow"),
	);
}


function location_cities_list_pl_ds () {
	return array (
		"3103476" => t("Bielawa"),
		"3103096" => t("Bogatynia"),
		"3103034" => t("Boguszow-Gorce"),
		"3102987" => t("Boleslawiec"),
		"3099828" => t("Dzierzoniow"),
		"3099213" => t("Glogow"),
		"3097367" => t("Jawor"),
		"3097271" => t("Jelcz"),
		"7303641" => t("Jelcz Laskowice"),
		"3097257" => t("Jelenia Gora"),
		"3096779" => t("Kamienna Gora"),
		"3096053" => t("Klodzko"),
		"3093692" => t("Legnica"),
		"3093040" => t("Luban"),
		"3092931" => t("Lubin"),
		"3090768" => t("Nowa Ruda"),
		"3090205" => t("Olawa"),
		"3090170" => t("Olesnica"),
		"3088435" => t("Polkowice"),
		"3084440" => t("Strzegom"),
		"3084093" => t("Swidnica"),
		"3084084" => t("Swiebodzice"),
		"3082707" => t("Walbrzych"),
		"3081368" => t("Wroclaw"),
		"3081046" => t("Zabkowice Slaskie"),
		"3080231" => t("Zgorzelec"),
		"3080074" => t("Zlotoryja"),
	);
}


function location_cities_list_pl_lb () {
	return array (
		"3098722" => t("Gorzow Wielkopolski"),
		"3098130" => t("Gubin"),
		"3095057" => t("Kostrzyn nad Odra"),
		"3091969" => t("Miedzyrzecz"),
		"3090764" => t("Nowa Sol"),
		"3085495" => t("Slubice"),
		"3084241" => t("Sulechow"),
		"3084062" => t("Swiebodzin"),
		"3080944" => t("Zagan"),
		"3080644" => t("Zary"),
		"3080165" => t("Zielona Gora"),
	);
}


function location_cities_list_pl_kp () {
	return array (
		"3102627" => t("Brodnica"),
		"3102014" => t("Bydgoszcz"),
		"3101795" => t("Chelmno"),
		"3101787" => t("Chelmza"),
		"3099654" => t("Fordon"),
		"3098218" => t("Grudziadz"),
		"3097872" => t("Inowroclaw"),
		"3091150" => t("Naklo nad Notecia"),
		"3086511" => t("Rypin"),
		"3085172" => t("Solec Kujawski"),
		"3084074" => t("Swiecie"),
		"3083271" => t("Torun"),
		"3081741" => t("Wloclawek"),
	);
}


function location_cities_list_pl_pm () {
	return array (
		"3101943" => t("Bytow"),
		"3101672" => t("Chojnice"),
		"3099434" => t("Gdansk"),
		"3099424" => t("Gdynia"),
		"3096525" => t("Kartuzy"),
		"3095126" => t("Koscierzyna"),
		"3094086" => t("Kwidzyn"),
		"3093739" => t("Lebork"),
		"3092472" => t("Malbork"),
		"3088034" => t("Pruszcz Gdanski"),
		"3087281" => t("Reda"),
		"3086706" => t("Rumia"),
		"3085450" => t("Slupsk"),
		"3085151" => t("Sopot"),
		"3084826" => t("Starogard Gdanski"),
		"3083426" => t("Tczew"),
		"3082756" => t("Ustka"),
		"3082473" => t("Wejherowo"),
	);
}


function location_cities_list_pl_zp () {
	return array (
		"3103556" => t("Bialogard"),
		"3101613" => t("Choszczno"),
		"3098966" => t("Goleniow"),
		"3098201" => t("Gryfice"),
		"3098200" => t("Gryfino"),
		"3095795" => t("Kolobrzeg"),
		"3095049" => t("Koszalin"),
		"3090558" => t("Nowogard"),
		"3088461" => t("Police"),
		"3084840" => t("Stargard Szczecinski"),
		"3084085" => t("Swidwin"),
		"3083955" => t("Swinoujscie"),
		"3083829" => t("Szczecin"),
		"3083826" => t("Szczecinek"),
		"3082704" => t("Walcz"),
	);
}


function location_cities_list_pl_op () {
	return array (
		"3102459" => t("Brzeg"),
		"3099169" => t("Glucholazy"),
		"3096372" => t("Kedzierzyn-Kozle"),
		"3096003" => t("Kluczbork"),
		"3094788" => t("Krapkowice"),
		"3091141" => t("Namyslow"),
		"3090436" => t("Nysa"),
		"3090433" => t("Nysa Zamlynie"),
		"3090048" => t("Opole"),
		"3088065" => t("Prudnik"),
		"3084415" => t("Strzelce Opolskie"),
	);
}


