<?php

function location_cities_list_au_sa () {
	return array (
		"2078025" => t("Adelaide"),
		"7302628" => t("Adelaide Hills"),
		"2071059" => t("Gawler"),
		"2065740" => t("Morphett Vale"),
		"2156643" => t("Mount Gambier"),
		"2065176" => t("Murray Bridge"),
		"2062944" => t("Prospect"),
		"2058430" => t("Whyalla"),
	);
}


function location_cities_list_au_wa () {
	return array (
		"2077963" => t("Albany"),
		"2077579" => t("Armadale"),
		"2075432" => t("Bunbury"),
		"2075265" => t("Busselton"),
		"7302631" => t("Canning Vale"),
		"2071223" => t("Fremantle"),
		"2070998" => t("Geraldton"),
		"2070571" => t("Gosnells"),
		"2068823" => t("Kalgoorlie"),
		"2068079" => t("Kwinana"),
		"2067119" => t("Mandurah"),
		"2063523" => t("Perth"),
		"2063042" => t("Port Hedland"),
		"2062338" => t("Rockingham"),
	);
}


function location_cities_list_au_qld () {
	return array (
		"7932654" => t("Booval"),
		"6943558" => t("Bracken Ridge"),
		"2174003" => t("Brisbane"),
		"2173605" => t("Buderim"),
		"2173323" => t("Bundaberg"),
		"2172832" => t("Caboolture"),
		"2172797" => t("Cairns"),
		"2172710" => t("Caloundra"),
		"7281839" => t("Carindale"),
		"2169220" => t("Deception Bay"),
		"2165478" => t("Gladstone"),
		"2165087" => t("Gold Coast"),
		"7281838" => t("Logan City"),
		"2159220" => t("Mackay"),
		"2158562" => t("Maryborough"),
		"2156934" => t("Morayfield"),
		"2065594" => t("Mount Isa"),
		"2155542" => t("Nerang"),
		"8354541" => t("Robina"),
		"2151437" => t("Rockhampton"),
		"2207259" => t("South Brisbane"),
		"2148928" => t("Southport"),
		"2147892" => t("Sunnybank"),
		"2147849" => t("Surfers Paradise"),
		"2146268" => t("Toowoomba"),
		"2146142" => t("Townsville"),
		"2143069" => t("Woodridge"),
	);
}


function location_cities_list_au_nt () {
	return array (
		"2077895" => t("Alice Springs"),
		"2073124" => t("Darwin"),
		"6301965" => t("Palmerston"),
	);
}


function location_cities_list_au_vic () {
	return array (
		"2177091" => t("Ballarat"),
		"7932629" => t("Balwyn North"),
		"2176187" => t("Bendigo"),
		"7932651" => t("Bentleigh East"),
		"7932646" => t("Brighton East"),
		"2173741" => t("Brunswick"),
		"2172686" => t("Camberwell"),
		"7932636" => t("Carnegie"),
		"8347717" => t("Clayton"),
		"2170089" => t("Craigieburn"),
		"2170078" => t("Cranbourne"),
		"2167817" => t("Echuca"),
		"8347325" => t("Endeavour Hills"),
		"7281850" => t("Ferntree Gully"),
		"2166143" => t("Frankston East"),
		"2165798" => t("Geelong"),
		"7932612" => t("Glen Iris"),
		"2164515" => t("Greensborough"),
		"7281807" => t("Hoppers Crossing"),
		"7932638" => t("Malvern East"),
		"2158177" => t("Melbourne"),
		"2158151" => t("Melton"),
		"2157698" => t("Mildura"),
		"2157343" => t("Moe"),
		"2156878" => t("Mornington"),
		"2156340" => t("Mulgrave"),
		"2151649" => t("Richmond"),
		"2150660" => t("Saint Kilda"),
		"2149645" => t("Shepparton"),
		"8015209" => t("St Albans"),
		"2147914" => t("Sunbury"),
		"2146108" => t("Traralgon"),
		"2144764" => t("Wangaratta"),
		"2144528" => t("Warrnambool"),
		"2143285" => t("Wodonga"),
	);
}


function location_cities_list_au_nsw () {
	return array (
		"2178174" => t("Albury"),
		"2177671" => t("Armidale"),
		"2176934" => t("Banora Point"),
		"2176632" => t("Bathurst"),
		"2175411" => t("Blacktown"),
		"2173911" => t("Broken Hill"),
		"2172311" => t("Caringbah"),
		"2172303" => t("Carlingford"),
		"2172111" => t("Castle Hill"),
		"2171845" => t("Cessnock"),
		"7302259" => t("City of Parramatta"),
		"2171085" => t("Coffs Harbour"),
		"2169956" => t("Cronulla"),
		"2208305" => t("Dee Why"),
		"2168305" => t("Dubbo"),
		"2167949" => t("Earlwood"),
		"2167312" => t("Engadine"),
		"2167280" => t("Epping"),
		"2166309" => t("Forster"),
		"7302642" => t("Glenmore Park"),
		"2164837" => t("Goulburn"),
		"2164691" => t("Granville"),
		"2164422" => t("Griffith"),
		"2163137" => t("Hornsby"),
		"2161776" => t("Katoomba"),
		"2160063" => t("Lismore"),
		"2159851" => t("Liverpool"),
		"2159045" => t("Maitland"),
		"2158651" => t("Maroubra"),
		"2158626" => t("Marrickville"),
		"2156813" => t("Mosman"),
		"2155472" => t("Newcastle"),
		"7281782" => t("North Ryde"),
		"2154787" => t("Nowra"),
		"2154219" => t("Orange"),
		"7281840" => t("Paramatta"),
		"2152659" => t("Port Macquarie"),
		"2148398" => t("Port Stephens"),
		"2152329" => t("Quakers Hill"),
		"2152286" => t("Queanbeyan"),
		"2208285" => t("Randwick"),
		"2148997" => t("South Grafton"),
		"2147714" => t("Sydney"),
		"2147497" => t("Tamworth"),
		"2147381" => t("Taree"),
		"2145110" => t("Wagga Wagga"),
		"2171507" => t("Wollongong"),
	);
}


function location_cities_list_au_tas () {
	return array (
		"2173125" => t("Burnie"),
		"2168943" => t("Devonport"),
		"2163355" => t("Hobart"),
		"2160517" => t("Launceston"),
	);
}


function location_cities_list_au_act () {
	return array (
		"2172517" => t("Canberra"),
	);
}


