<?php

function location_cities_list_gw_ba () {
	return array (
		"2375254" => t("Bafata"),
	);
}


function location_cities_list_gw_bm () {
	return array (
	);
}


function location_cities_list_gw_bs () {
	return array (
		"2374775" => t("Bissau"),
	);
}


function location_cities_list_gw_bl () {
	return array (
	);
}


function location_cities_list_gw_ca () {
	return array (
	);
}


function location_cities_list_gw_ga () {
	return array (
	);
}


function location_cities_list_gw_oi () {
	return array (
	);
}


function location_cities_list_gw_qu () {
	return array (
	);
}


function location_cities_list_gw_to () {
	return array (
	);
}
