<?php


function location_cities_list_hu_ba() {
  return array(
    "3046526" => "Pecs",
    "3047967" => "Mohacs",
    "3049512" => "Komlo",
  );
}


function location_cities_list_hu_be() {
  return array(
    "715466" => "Szarvas",
    "716736" => "Oroshaza",
    "720334" => "Gyula",
    "720364" => "Gyomaendrod",
    "722437" => "Bekescsaba",
    "722439" => "Bekes",
  );
}


function location_cities_list_hu_bz() {
  return array(
    "714697" => "Tiszaujvaros",
    "715839" => "Satoraljaujhely",
    "716671" => "Ozd",
    "717582" => "Miskolc",
    "717652" => "Mezokovesd",
    "719311" => "Kazincbarcika",
  );
}


function location_cities_list_hu_bu() {
  return array(
    "3054643" => "Budapest",
    "7284823" => "Budapest XII. keruelet",
    "7284824" => "Budapest XI. keruelet",
    "7284825" => "Budapest IX. keruelet",
    "7284826" => "Budapest VIII. keruelet",
    "7284827" => "Budapest VII. keruelet",
    "7284828" => "Budapest VI. keruelet",
    "7284829" => "Budapest XIV. keruelet",
    "7284830" => "Budapest XIII. keruelet",
    "7284831" => "Budapest IV. keruelet",
    "7284832" => "Budapest XV. keruelet",
    "7284833" => "Budapest XVI. keruelet",
    "7284834" => "Budapest X. keruelet",
    "7284835" => "Budapest XIX. keruelet",
    "7284836" => "Budapest XVIII. keruelet",
    "7284837" => "Budapest XXIII. keruelet",
    "7284838" => "Budapest XXII. keruelet",
    "7284839" => "Budapest XXI. keruelet",
    "7284840" => "Budapest XX. keruelet",
    "7284841" => "Budapest XVII. keruelet",
    "7284842" => "Budapest III. keruelet",
    "7284843" => "Budapest II. keruelet",
    "7284844" => "Budapest I. keruelet",
  );
}


function location_cities_list_hu_bk() {
  return array(
    "3049880" => "Kiskunhalas",
    "3049885" => "Kiskunfelegyhaza",
    "3049896" => "Kiskoros",
    "3050434" => "Kecskemet",
    "3050719" => "Kalocsa",
    "3055685" => "Baja",
  );
}


function location_cities_list_hu_cs() {
  return array(
    "715338" => "Szentes",
    "715429" => "Szeged",
    "717902" => "Mako",
    "719965" => "Hodmezovasarhely",
    "721592" => "Csongrad",
  );
}


function location_cities_list_hu_fe() {
  return array(
    "3044774" => "Szekesfehervar",
    "3053438" => "Dunaujvaros",
  );
}


function location_cities_list_hu_gs() {
  return array(
    "3045190" => "Sopron",
    "3047896" => "Mosonmagyarovar",
    "3052009" => "Gyor",
  );
}


function location_cities_list_hu_hb() {
  return array(
    "716301" => "Puspokladany",
    "720276" => "Hajduszoboszlo",
    "720284" => "Hajdunanas",
    "720292" => "Hajduboszormeny",
    "721472" => "Debrecen",
    "722324" => "Berettyoujfalu",
    "722636" => "Balmazujvaros",
  );
}


function location_cities_list_hu_he() {
  return array(
    "721239"  => "Eger",
    "3046619" => "Paradsasvar",
    "3051621" => "Hatvan",
    "3052040" => "Gyongyos",
  );
}


function location_cities_list_hu_jn() {
  return array(
    "714581"  => "Torokszentmiklos",
    "715126"  => "Szolnok",
    "717635"  => "Mezotur",
    "719404"  => "Karcag",
    "3050907" => "Jaszbereny",
  );
}


function location_cities_list_hu_ke() {
  return array(
    "3044082" => "Tatabanya",
    "3044083" => "Tata",
    "3046888" => "Oroszlany",
    "3049519" => "Komarom",
    "3053163" => "Esztergom",
  );
}


function location_cities_list_hu_no() {
  return array(
    "3045643" => "Salgotarjan",
    "3055601" => "Balassagyarmat",
  );
}


function location_cities_list_hu_pe() {
  return array(
    "723030"  => "Abony",
    "3043019" => "Vecses",
    "3043293" => "Vac",
    "3044475" => "Szigetszentmiklos",
    "3044681" => "Szentendre",
    "3044821" => "Szazhalombatta",
    "3047651" => "Nagykoros",
    "3047942" => "Monor",
    "3052101" => "Gyal",
    "3052236" => "Godollo",
    "3052241" => "God",
    "3052542" => "Fot",
    "3053281" => "Erd",
    "3053476" => "Dunakeszi",
    "3053485" => "Dunaharaszti",
    "3053836" => "Dabas",
    "3054543" => "Cegled",
    "3054646" => "Budaors",
  );
}


function location_cities_list_hu_so() {
  return array(
    "3045332" => "Siofok",
    "3050616" => "Kaposvar",
  );
}


function location_cities_list_hu_sz() {
  return array(
    "716935" => "Nyiregyhaza",
    "717771" => "Mateszalka",
    "718739" => "Kisvarda",
  );
}


function location_cities_list_hu_to() {
  return array(
    "3044760" => "Szekszard",
    "3046768" => "Paks",
    "3053590" => "Dombovar",
  );
}


function location_cities_list_hu_va() {
  return array(
    "3044310" => "Szombathely",
    "3045487" => "Sarvar",
  );
}


function location_cities_list_hu_ve() {
  return array(
    "3042929" => "Veszprem",
    "3043095" => "Varpalota",
    "3044141" => "Tapolca",
    "3046686" => "Papa",
    "3056357" => "Ajka",
  );
}


function location_cities_list_hu_za() {
  return array(
    "3042638" => "Zalaegerszeg",
    "3047679" => "Nagykanizsa",
    "3050212" => "Keszthely",
  );
}
