<?php


function location_cities_list_bw_ce () {
	return array (
		"933000" => t("Tonota"),
		"933088" => t("Serowe"),
		"933099" => t("Selebi-Phikwe"),
		"933182" => t("Palapye"),
		"933471" => t("Mahalapye"),
		"933535" => t("Letlhakane"),
	);
}


function location_cities_list_bw_gh () {
	return array (
	);
}


function location_cities_list_bw_kg () {
	return array (
	);
}


function location_cities_list_bw_kl () {
	return array (
		"933340" => t("Mochudi"),
	);
}


function location_cities_list_bw_kw () {
	return array (
		"933018" => t("Thamaga"),
		"933305" => t("Molepolole"),
		"933331" => t("Mogoditshane"),
	);
}


function location_cities_list_bw_ne () {
	return array (
		"933778" => t("Francistown"),
	);
}


function location_cities_list_bw_nw () {
	return array (
		"933366" => t("Maun"),
	);
}


function location_cities_list_bw_se () {
	return array (
		"933141" => t("Ramotswa"),
		"933521" => t("Lobatse"),
		"933719" => t("Janeng"),
		"933773" => t("Gaborone"),
	);
}


function location_cities_list_bw_so () {
	return array (
		"933271" => t("Mosopa"),
		"933685" => t("Kanye"),
	);
}
