<?php


function location_cities_list_gq_an () {
	return array (
	);
}


function location_cities_list_gq_bn () {
	return array (
		"2309527" => t("Malabo"),
	);
}


function location_cities_list_gq_bs () {
	return array (
	);
}


function location_cities_list_gq_cs () {
	return array (
	);
}


function location_cities_list_gq_kn () {
	return array (
		"2309332" => t("Ebebiyin"),
	);
}


function location_cities_list_gq_li () {
	return array (
		"2310046" => t("Bata"),
	);
}


function location_cities_list_gq_wn () {
	return array (
	);
}
