<?php

function location_cities_list_pt_11 () {
	return array (
		"2272215" => t("Alcabideche"),
		"2271985" => t("Alges"),
		"2271772" => t("Amadora"),
		"2270981" => t("Belas"),
		"2270503" => t("Cacem"),
		"2270377" => t("Camarate"),
		"2270184" => t("Carcavelos"),
		"2270157" => t("Carnaxide"),
		"2269594" => t("Cascais"),
		"2268436" => t("Estoril"),
		"2267067" => t("Linda-a-Velha"),
		"2267057" => t("Lisbon"),
		"2266977" => t("Loures"),
		"2265927" => t("Monte Estoril"),
		"2265467" => t("Odivelas"),
		"2265326" => t("Paco de Arcos"),
		"2265169" => t("Parede"),
		"2264526" => t("Pontinha"),
		"2264359" => t("Povoa de Santa Iria"),
		"2264268" => t("Queluz"),
		"2264087" => t("Ramada"),
		"2263827" => t("Rio de Mouro"),
		"2263667" => t("Sacavem"),
		"2263523" => t("Santa Iria da Azoia"),
		"2263352" => t("Sao Domingos de Rana"),
		"2263326" => t("Sao Joao da Talha"),
		"2262912" => t("Sintra"),
		"2262581" => t("Torres Vedras"),
		"2261697" => t("Vialonga"),
		"2261639" => t("Vila Franca de Xira"),
	);
}


function location_cities_list_pt_14 () {
	return array (
		"2268575" => t("Entroncamento"),
		"2266249" => t("Monsanto"),
		"2263480" => t("Santarem"),
		"2262644" => t("Tomar"),
	);
}


function location_cities_list_pt_15 () {
	return array (
		"2271961" => t("Almada"),
		"2271680" => t("Amora"),
		"2271473" => t("Arrentela"),
		"2271071" => t("Barreiro"),
		"2270229" => t("Caparica"),
		"2269282" => t("Charneca"),
		"2269041" => t("Corroios"),
		"2266319" => t("Moita"),
		"2265788" => t("Montijo"),
		"2265223" => t("Palmela"),
		"2264736" => t("Piedade"),
		"2264718" => t("Pinhal Novo"),
		"2262957" => t("Sesimbra"),
		"2262963" => t("Setubal"),
	);
}


function location_cities_list_pt_08 () {
	return array (
		"2272222" => t("Albufeira"),
		"2268339" => t("Faro"),
		"2267226" => t("Lagos"),
		"2267131" => t("Laranjeiro"),
		"2266988" => t("Loule"),
		"2265447" => t("Olhao"),
		"2264456" => t("Portimao"),
		"2264299" => t("Quarteira"),
	);
}


function location_cities_list_pt_12 () {
	return array (
		"2264508" => t("Portalegre"),
	);
}


function location_cities_list_pt_10 () {
	return array (
		"2270437" => t("Caldas da Rainha"),
		"2267095" => t("Leiria"),
		"2266703" => t("Marinha Grande"),
		"2264923" => t("Peniche"),
		"2264575" => t("Pombal"),
	);
}


function location_cities_list_pt_30 () {
	return array (
		"2270380" => t("Camara de Lobos"),
		"2267827" => t("Funchal"),
	);
}


function location_cities_list_pt_07 () {
	return array (
		"2268406" => t("Evora"),
	);
}


function location_cities_list_pt_05 () {
	return array (
		"2269514" => t("Castelo Branco"),
		"2740313" => t("Covilha"),
	);
}


function location_cities_list_pt_02 () {
	return array (
		"2270985" => t("Beja"),
	);
}


function location_cities_list_pt_18 () {
	return array (
		"2732265" => t("Viseu"),
	);
}


function location_cities_list_pt_17 () {
	return array (
		"2732438" => t("Vila Real"),
	);
}


function location_cities_list_pt_13 () {
	return array (
		"2743304" => t("Aguas Santas"),
		"2742506" => t("Baguim do Monte"),
		"2742051" => t("Bougado"),
		"2741551" => t("Canidelo"),
		"2739997" => t("Ermezinde"),
		"2739756" => t("Fanzeres"),
		"2738925" => t("Gondomar"),
		"2738348" => t("Leca da Palmeira"),
		"2738347" => t("Leca do Bailio"),
		"2738014" => t("Maia"),
		"2737824" => t("Matosinhos"),
		"2737039" => t("Oliveira do Douro"),
		"2736521" => t("Pedroso"),
		"2735943" => t("Porto"),
		"2735787" => t("Povoa de Varzim"),
		"2735083" => t("Rio Tinto"),
		"2734434" => t("Sao Mamede de Infesta"),
		"2734363" => t("Sao Pedro da Cova"),
		"2734140" => t("Senhora da Hora"),
		"2732978" => t("Valongo"),
		"2732544" => t("Vila Nova de Gaia"),
		"2732649" => t("Vila do Conde"),
		"2732475" => t("Vilar de Andorinho"),
	);
}


function location_cities_list_pt_16 () {
	return array (
		"2737523" => t("Moncao"),
		"2736041" => t("Ponte do Lima"),
		"2732773" => t("Viana do Castelo"),
	);
}


function location_cities_list_pt_09 () {
	return array (
		"2740174" => t("Custoias"),
		"2738785" => t("Guarda"),
		"2734106" => t("Sequeira"),
	);
}


function location_cities_list_pt_01 () {
	return array (
		"2742611" => t("Aveiro"),
		"2739723" => t("Feira"),
		"2738707" => t("Ilhavo"),
		"2736930" => t("Ovar"),
		"2734484" => t("Sao Joao da Madeira"),
	);
}


function location_cities_list_pt_03 () {
	return array (
		"2742416" => t("Barcelos"),
		"2742032" => t("Braga"),
		"2739849" => t("Esposende"),
		"2739848" => t("Esposende"),
		"2739788" => t("Fafe"),
		"2738752" => t("Guimaraes"),
	);
}


function location_cities_list_pt_06 () {
	return array (
		"2740637" => t("Coimbra"),
	);
}


function location_cities_list_pt_04 () {
	return array (
		"2742027" => t("Braganca"),
	);
}


function location_cities_list_pt_20 () {
	return array (
		"3372783" => t("Ponta Delgada"),
	);
}


