<?php

function location_cities_list_gn_l () {
	return array (
		"2418362" => t("Labe"),
		"2414545" => t("Tougue"),
	);
}


function location_cities_list_gn_d () {
	return array (
		"2422457" => t("Coyah"),
		"2419533" => t("Kindia"),
		"2414926" => t("Telimele"),
	);
}


function location_cities_list_gn_k () {
	return array (
		"2419992" => t("Kankan"),
		"2415703" => t("Siguiri"),
	);
}


function location_cities_list_gn_m () {
	return array (
		"2417833" => t("Mamou"),
		"2416443" => t("Pita"),
	);
}


function location_cities_list_gn_n () {
	return array (
		"2420562" => t("Gueckedou"),
		"2417988" => t("Macenta"),
		"2416969" => t("Nzerekore"),
	);
}


function location_cities_list_gn_f () {
	return array (
		"2419472" => t("Kissidougou"),
	);
}


function location_cities_list_gn_b () {
	return array (
		"2422924" => t("Boke"),
		"2420884" => t("Fria"),
		"2420056" => t("Kamsar"),
	);
}


function location_cities_list_gn_c () {
	return array (
		"2422488" => t("Camayenne"),
		"2422465" => t("Conakry"),
	);
}


