<?php


function location_cities_list_ly_ju() {
  return array(
    "2209055" => "Waddan",
    "2216645" => "Hun",
  );
}


function location_cities_list_ly_kf() {
  return array(
    "88562" => "At Taj",
    "88930" => "Al Kufrah",
    "88962" => "Al Jawf",
  );
}


function location_cities_list_ly_mj() {
  return array(
    "88834" => "Tukrah",
    "88903" => "Al Marj",
  );
}


function location_cities_list_ly_mb() {
  return array(
    "2210221" => "Tarhuna",
    "2219905" => "Al Khums",
  );
}


function location_cities_list_ly_dr() {
  return array(
    "87205" => "Darnah",
  );
}


function location_cities_list_ly_mq() {
  return array(
    "2214603" => "Murzuq",
  );
}


function location_cities_list_ly_ba() {
  return array(
    "81604" => "Suluq",
    "88319" => "Benghazi",
  );
}


function location_cities_list_ly_gt() {
  return array(
    "2217351" => "Ghat",
  );
}


function location_cities_list_ly_mi() {
  return array(
    "2208485" => "Zliten",
    "2214846" => "Misratah",
  );
}


function location_cities_list_ly_nl() {
  return array(
    "2214433" => "Nalut",
  );
}


function location_cities_list_ly_sb() {
  return array(
    "2212775" => "Sabha",
    "2219960" => "Al Jadid",
  );
}


function location_cities_list_ly_wd() {
  return array(
    "2219235" => "Awbari",
  );
}


function location_cities_list_ly_ws() {
  return array(
    "2218478" => "Birak",
  );
}


function location_cities_list_ly_bu() {
  return array(
    "81302" => "Tobruk",
  );
}


function location_cities_list_ly_ja() {
  return array(
    "89055" => "Al Bayda'",
  );
}


function location_cities_list_ly_jg() {
  return array(
    "2208791" => "Yafran",
    "2217362" => "Gharyan",
    "2218963" => "Az Zintan",
  );
}


function location_cities_list_ly_ji() {
  return array();
}


function location_cities_list_ly_wa() {
  return array(
    "88380" => "Az Zuwaytinah",
    "89113" => "Ajdabiya",
  );
}


function location_cities_list_ly_nq() {
  return array(
    "2208425" => "Zuwarah",
  );
}


function location_cities_list_ly_za() {
  return array(
    "2210560" => "Surman",
    "2212771" => "Sabratah",
    "2216885" => "Zawiya",
    "2218970" => "Az Zawiyah",
  );
}


function location_cities_list_ly_tb() {
  return array(
    "2210247" => "Tripoli",
    "2210394" => "Tagiura",
  );
}


function location_cities_list_ly_sr() {
  return array(
    "2210554" => "Sirte",
  );
}
