<?php


function location_cities_list_fj_c() {
  return array(
    "2198148" => "Suva",
  );
}


function location_cities_list_fj_e() {
  return array();
}


function location_cities_list_fj_n() {
  return array(
    "2204582" => "Lambasa",
  );
}


function location_cities_list_fj_r() {
  return array();
}


function location_cities_list_fj_w() {
  return array(
    "2202064" => "Nadi",
    "2204506" => "Lautoka",
  );
}
