<?php


function location_cities_list_om_sh() {
  return array(
    "286245" => "Sur",
  );
}


function location_cities_list_om_za() {
  return array(
    "287830" => "`Ibri",
    "411849" => "Yanqul",
  );
}


function location_cities_list_om_mu() {
  return array(
    "287614" => "Khasab",
  );
}


function location_cities_list_om_ba() {
  return array(
    "288789" => "Barka'",
    "289011" => "Rustaq",
  );
}


function location_cities_list_om_ma() {
  return array(
    "287286" => "Muscat",
    "288764" => "Bawshar",
    "288967" => "As Sib al Jadidah",
  );
}


function location_cities_list_om_11() {
  return array(
    "286282" => "Al Sohar",
    "286402" => "Shinas",
    "286647" => "Saham",
    "288955" => "As Suwayq",
    "289174" => "Al Liwa'",
    "289199" => "Al Khaburah",
  );
}


function location_cities_list_om_12() {
  return array(
    "287832" => "Ibra'",
    "288902" => "Badiyah",
  );
}


function location_cities_list_om_zu() {
  return array(
    "286621" => "Salalah",
  );
}


function location_cities_list_om_da() {
  return array(
    "286293" => "Sufalat Sama'il",
    "286987" => "Nizwa",
    "287814" => "Izki",
    "288721" => "Bidbid",
    "288899" => "Bahla'",
    "289433" => "Adam",
  );
}


function location_cities_list_om_bu() {
  return array(
    "289317" => "Al Buraymi",
  );
}


function location_cities_list_om_wu() {
  return array();
}
