<?php

function location_cities_list_mm_03 () {
	return array (
		"1327659" => t("Chauk"),
		"1312609" => t("Magway"),
		"1309289" => t("Minbu"),
		"1329239" => t("Myaydo"),
		"1302439" => t("Pakokku"),
		"1294041" => t("Taungdwingyi"),
		"1292037" => t("Thayetmyo"),
		"1285173" => t("Yenangyaung"),
	);
}


function location_cities_list_mm_07 () {
	return array (
		"1328121" => t("Bogale"),
		"1325211" => t("Hinthada"),
		"1317397" => t("Kyaiklat"),
		"1310362" => t("Maubin"),
		"1308464" => t("Mawlamyinegyunn"),
		"1308204" => t("Myanaung"),
		"1285871" => t("Nyaungdon"),
		"1328421" => t("Pathein"),
		"1299237" => t("Pyapon"),
		"1289828" => t("Wakema"),
	);
}


function location_cities_list_mm_04 () {
	return array (
		"1316703" => t("Kyaukse"),
		"1311874" => t("Mandalay"),
		"1309937" => t("Maymyo"),
		"1309793" => t("Meiktila"),
		"1308937" => t("Mogok"),
		"1307835" => t("Myingyan"),
		"6611854" => t("Nay Pyi Taw"),
		"1298987" => t("Pyinmana"),
		"1285899" => t("Yamethin"),
	);
}


function location_cities_list_mm_06 () {
	return array (
		"1320944" => t("Kanbe"),
		"1319533" => t("Kayan"),
		"1298824" => t("Rangoon"),
		"1295395" => t("Syriam"),
		"1291193" => t("Thongwa"),
		"1290374" => t("Twante"),
	);
}


function location_cities_list_mm_02 () {
	return array (
		"1300466" => t("Bago"),
		"1314042" => t("Letpandan"),
		"1303406" => t("Nyaunglebin"),
		"1300969" => t("Paungde"),
		"1299154" => t("Pyay"),
		"1298911" => t("Pyu"),
		"1290596" => t("Taungoo"),
		"1292579" => t("Thanatpin"),
		"1292580" => t("Thanatpin"),
		"1292313" => t("Tharyarwady"),
	);
}


function location_cities_list_mm_15 () {
	return array (
		"1317402" => t("Kyaikkami"),
		"1317375" => t("Kyaikto"),
		"1310460" => t("Martaban"),
		"1308465" => t("Mawlamyine"),
		"1308415" => t("Mudon"),
		"1292288" => t("Thaton"),
	);
}


function location_cities_list_mm_05 () {
	return array (
		"1293625" => t("Dawei"),
		"1309611" => t("Myeik"),
	);
}


function location_cities_list_mm_17 () {
	return array (
		"1314759" => t("Lashio"),
		"1293960" => t("Taunggyi"),
	);
}


function location_cities_list_mm_16 () {
	return array (
		"1295765" => t("Sittwe"),
	);
}


function location_cities_list_mm_01 () {
	return array (
		"1310120" => t("Mawlaik"),
		"1308522" => t("Monywa"),
		"1298482" => t("Sagaing"),
		"1296736" => t("Shwebo"),
	);
}


function location_cities_list_mm_13 () {
	return array (
		"1302849" => t("Hpa-an"),
	);
}


function location_cities_list_mm_11 () {
	return array (
		"1328218" => t("Bhamo"),
		"1307741" => t("Myitkyina"),
	);
}


function location_cities_list_mm_12 () {
	return array (
		"1313479" => t("Loikaw"),
	);
}


function location_cities_list_mm_14 () {
	return array (
		"1325443" => t("Hakha"),
	);
}


