<?php


function location_cities_list_sa_12() {
  return array(
    "101631" => "Tubarjal",
    "102527" => "Sakaka",
    "108648" => "Al Qurayyat",
  );
}


function location_cities_list_sa_05() {
  return array(
    "107304"  => "Buraydah",
    "108435"  => "Ar Rass",
    "109131"  => "Al Mithnab",
    "109878"  => "Al Bukayriyah",
    "8394316" => "Unaizah",
  );
}


function location_cities_list_sa_04() {
  return array(
    "101554" => "Tarut",
    "102318" => "Sayhat",
    "102585" => "Safwa",
    "102985" => "Rahimah",
    "107312" => "Abqaiq",
    "107797" => "Dhahran",
    "107959" => "At Taraf",
    "108918" => "Al Qaysumah",
    "108927" => "Al Qatif",
    "109059" => "Al Munayzilah",
    "109101" => "Al Mubarraz",
    "109323" => "Al Khubar",
    "109380" => "Al Khafji",
    "109435" => "Al Jubayl",
    "109571" => "Al Hufuf",
    "109915" => "Al Battaliyah",
    "110336" => "Dammam",
  );
}


function location_cities_list_sa_02() {
  return array(
    "101322" => "Turabah",
    "103035" => "Rabigh",
    "104515" => "Mecca",
    "105343" => "Jeddah",
    "107968" => "Ta'if",
    "109417" => "Al Jumum",
  );
}


function location_cities_list_sa_09() {
  return array(
    "102451" => "Samitah",
    "102651" => "Sabya",
    "105299" => "Jizan",
    "110619" => "Abu `Arish",
  );
}


function location_cities_list_sa_10() {
  return array(
    "103630" => "Najran",
  );
}


function location_cities_list_sa_07() {
  return array(
    "100926" => "Umm Lajj",
    "101628" => "Tabuk",
    "106909" => "Duba",
    "108773" => "Al Wajh",
  );
}


function location_cities_list_sa_11() {
  return array(
    "109953" => "Al Bahah",
  );
}


function location_cities_list_sa_03() {
  return array(
    "100425" => "Yanbu` al Bahr",
    "101760" => "Sultanah",
    "107744" => "Badr Hunayn",
    "109223" => "Medina",
  );
}


function location_cities_list_sa_01() {
  return array(
    "107781" => "Az Zulfi",
    "108048" => "As Sulayyil",
    "108410" => "Riyadh",
    "110250" => "`Afif",
    "110314" => "Ad Dilam",
    "110325" => "Ad Dawadimi",
  );
}


function location_cities_list_sa_06() {
  return array(
    "106281" => "Hayil",
  );
}


function location_cities_list_sa_14() {
  return array(
    "103369" => "Qal`at Bishah",
    "105072" => "Khamis Mushayt",
    "108617" => "An Nimas",
    "110690" => "Abha",
  );
}


function location_cities_list_sa_08() {
  return array(
    "101312" => "Turayf",
    "108512" => "'Ar'ar",
  );
}
