<?php


function location_cities_list_ar_c() {
  return array(
    "3427408" => "Villa Lugano",
    "3429576" => "Retiro",
    "3435356" => "Colegiales",
    "3435910" => "Buenos Aires",
    "6693230" => "Villa Santa Rita",
  );
}


function location_cities_list_ar_b() {
  return array(
    "3427213" => "Zarate",
    "3427431" => "Villa Gesell",
    "3427761" => "Tigre",
    "3427833" => "Tandil",
    "3429652" => "Quilmes",
    "3429902" => "Pontevedra",
    "3430443" => "Necochea",
    "3430545" => "Moron",
    "3430708" => "Mercedes",
    "3430863" => "Mar del Plata",
    "3430988" => "Lujan",
    "3432043" => "La Plata",
    "3435038" => "Dolores",
    "3435810" => "Campana",
    "3436199" => "Azul",
    "3833112" => "Veinticinco de Mayo",
    "3833859" => "Tres Arroyos",
    "3836846" => "San Nicolas de los Arroyos",
    "3839982" => "Punta Alta",
    "3841490" => "Pergamino",
    "3842670" => "Olavarria",
    "3842881" => "Nueve de Julio",
    "3846864" => "Lincoln",
    "3853354" => "Junin",
    "3860164" => "Coronel Suarez",
    "3861344" => "Chivilcoy",
    "3861953" => "Chacabuco",
    "3865086" => "Bahia Blanca",
  );
}


function location_cities_list_ar_k() {
  return array(
    "3837702" => "San Fernando del Valle de Catamarca",
  );
}


function location_cities_list_ar_w() {
  return array(
    "3428071" => "Santo Tome",
    "3428708" => "San Luis del Palmar",
    "3428759" => "San Lorenzo",
    "3429403" => "Saladas",
    "3430104" => "Paso de los Libres",
    "3430598" => "Monte Caseros",
    "3430709" => "Mercedes",
    "3433715" => "Goya",
    "3433753" => "Gobernador Ingeniero Valentin Virasoro",
    "3434095" => "Esquina",
    "3435103" => "Curuzu Cuatia",
    "3435217" => "Corrientes",
  );
}


function location_cities_list_ar_x() {
  return array(
    "3832662" => "Villa Nueva",
    "3832694" => "Villa Maria",
    "3832756" => "Villa Dolores",
    "3832791" => "Villa Carlos Paz",
    "3832815" => "Villa Allende",
    "3833412" => "Unquillo",
    "3837675" => "San Francisco",
    "3838793" => "Rio Tercero",
    "3838797" => "Rio Segundo",
    "3838874" => "Rio Cuarto",
    "3838902" => "Rio Ceballos",
    "3843619" => "Morteros",
    "3844899" => "Marcos Juarez",
    "3851331" => "La Falda",
    "3852374" => "La Calera",
    "3852468" => "Laboulaye",
    "3853510" => "Jesus Maria",
    "3856235" => "Embalse",
    "3859512" => "Dean Funes",
    "3859828" => "Cruz del Eje",
    "3859965" => "Cosquin",
    "3860259" => "Cordoba",
    "3864331" => "Bell Ville",
    "3865424" => "Arroyito",
    "3866163" => "Alta Gracia",
  );
}


function location_cities_list_ar_e() {
  return array(
    "3427428" => "Villaguay",
    "3428359" => "Santa Elena",
    "3432079" => "La Paz",
    "3433658" => "Gualeguaychu",
    "3433663" => "Gualeguay",
    "3433956" => "Federal",
    "3435261" => "Concordia",
    "3435264" => "Concepcion del Uruguay",
    "3435486" => "Chajari",
    "3832934" => "Victoria",
    "3841956" => "Parana",
    "3859384" => "Diamante",
    "3859904" => "Crespo",
  );
}


function location_cities_list_ar_p() {
  return array(
    "3429949" => "Pirane",
    "3433899" => "Formosa",
  );
}


function location_cities_list_ar_y() {
  return array(
    "3836564" => "San Salvador de Jujuy",
    "3836772" => "San Pedro",
    "3842190" => "Palpala",
    "3846915" => "Libertador General San Martin",
  );
}


function location_cities_list_ar_l() {
  return array(
    "3835994" => "Santa Rosa",
    "3855075" => "General Pico",
  );
}


function location_cities_list_ar_f() {
  return array(
    "3848950" => "La Rioja",
    "3861445" => "Chilecito",
  );
}


function location_cities_list_ar_m() {
  return array(
    "3836669" => "San Rafael",
    "3836992" => "San Martin",
    "3844421" => "Mendoza",
  );
}


function location_cities_list_ar_n() {
  return array(
    "3428068" => "San Vicente",
    "3428577" => "San Pedro",
    "3429732" => "Puerto Rico",
    "3429777" => "Puerto Iguazu",
    "3429786" => "Puerto Esperanza",
    "3429790" => "Puerto Eldorado",
    "3429886" => "Posadas",
    "3430340" => "Obera",
    "3430601" => "Montecarlo",
    "3433349" => "Jardin America",
    "3433836" => "Garupa",
    "3434291" => "El Soberbio",
    "3436287" => "Aristobulo del Valle",
  );
}


function location_cities_list_ar_r() {
  return array(
    "3832647" => "Villa Regina",
    "3832899" => "Viedma",
    "3837980" => "San Antonio Oeste",
    "3855065" => "General Roca",
    "3858765" => "El Bolson",
    "3861056" => "Cipolletti",
    "3861061" => "Cinco Saltos",
    "3862254" => "Catriel",
    "3866242" => "Allen",
    "7647007" => "San Carlos de Bariloche",
  );
}


function location_cities_list_ar_j() {
  return array(
    "3832653" => "Villa Paula de Sarmiento",
    "3836194" => "Santa Lucia",
    "3837213" => "San Juan",
    "3837240" => "San Jose de Jachal",
    "3840860" => "Pocito",
    "3861416" => "Chimbas",
    "3862240" => "Caucete",
    "3866425" => "Albardon",
  );
}


function location_cities_list_ar_d() {
  return array(
    "3837056" => "San Luis",
    "7116866" => "Villa Mercedes",
  );
}


function location_cities_list_ar_z() {
  return array(
    "3838859" => "Rio Gallegos",
    "3863379" => "Caleta Olivia",
  );
}


function location_cities_list_ar_s() {
  return array(
    "3427388" => "Villa Ocampo",
    "3428975" => "San Javier",
    "3429594" => "Reconquista",
    "3436230" => "Avellaneda",
    "3832778" => "Villa Constitucion",
    "3833027" => "Vera",
    "3833062" => "Venado Tuerto",
    "3834971" => "Sunchales",
    "3835793" => "Santo Tome",
    "3836277" => "Santa Fe de la Vera Cruz",
    "3837124" => "San Justo",
    "3837441" => "San Jorge",
    "3838506" => "Rufino",
    "3838583" => "Rosario",
    "3839479" => "Rafaela",
    "3841500" => "Perez",
    "3854895" => "Granadero Baigorria",
    "3854985" => "Gobernador Galvez",
    "3855244" => "Galvez",
    "3855554" => "Firmat",
    "3856022" => "Esperanza",
    "3860217" => "Coronda",
    "3862351" => "Casilda",
    "3862655" => "Carcarana",
    "3862738" => "Capitan Bermudez",
    "3862981" => "Canada de Gomez",
    "3865385" => "Arroyo Seco",
  );
}


function location_cities_list_ar_g() {
  return array(
    "3834502" => "Termas de Rio Hondo",
    "3835869" => "Santiago del Estero",
    "3865840" => "Anatuya",
  );
}


function location_cities_list_ar_v() {
  return array(
    "3833367" => "Ushuaia",
  );
}


function location_cities_list_ar_t() {
  return array(
    "3832260" => "Yerba Buena",
    "3834813" => "Tafi Viejo",
    "3836873" => "San Miguel de Tucuman",
    "3843803" => "Monteros",
    "3855666" => "Famailla",
    "3864375" => "Bella Vista",
    "3866367" => "Alderetes",
    "3866496" => "Aguilares",
  );
}


function location_cities_list_ar_h() {
  return array(
    "3429577" => "Resistencia",
    "3433803" => "General Jose de San Martin",
    "3433901" => "Fontana",
    "3436124" => "Barranqueras",
    "3832811" => "Villa Angela",
    "3833794" => "Tres Isletas",
    "3839490" => "Quitilipi",
    "3840300" => "Presidencia Roque Saenz Pena",
    "3845330" => "Machagai",
    "3848687" => "Las Brenas",
    "3855074" => "General Pinedo",
    "3861678" => "Charata",
    "3862320" => "Castelli",
  );
}


function location_cities_list_ar_u() {
  return array(
    "3833883" => "Trelew",
    "3839307" => "Rawson",
    "3840092" => "Puerto Madryn",
    "3855974" => "Esquel",
    "3860443" => "Comodoro Rivadavia",
  );
}


function location_cities_list_ar_q() {
  return array(
    "3832132" => "Zapala",
    "3836951" => "San Martin de los Andes",
    "3840885" => "Plottier",
    "3843123" => "Neuquen",
    "3859552" => "Cutral-Co",
    "3862144" => "Centenario",
  );
}


function location_cities_list_ar_a() {
  return array(
    "3834601" => "Tartagal",
    "3836620" => "San Ramon de la Nueva Oran",
    "3838233" => "Salta",
    "3853491" => "Joaquin V. Gonzalez",
    "3855116" => "General Enrique Mosconi",
    "3856231" => "Embarcacion",
  );
}
