<?php

function location_cities_list_ie_l () {
	return array (
		"2962361" => t("An Muileann gCearr"),
		"2966839" => t("Athlone"),
		"2966131" => t("Blackrock"),
		"2966022" => t("Bray"),
		"2965768" => t("Carlow"),
		"2965529" => t("Celbridge"),
		"2964661" => t("Drogheda"),
		"2962290" => t("Droichead Nua"),
		"2964574" => t("Dublin"),
		"2964506" => t("Dun Laoghaire"),
		"2964540" => t("Dundalk"),
		"2963398" => t("Kilkenny"),
		"2962974" => t("Leixlip"),
		"2960964" => t("Loch Garman"),
		"2962334" => t("Naas"),
		"2962308" => t("Navan"),
		"2961297" => t("Swords"),
		"2961284" => t("Tallaght"),
	);
}


function location_cities_list_ie_m () {
	return array (
		"2965353" => t("Cluain Meala"),
		"2965140" => t("Cork"),
		"2964405" => t("Ennis"),
		"2962943" => t("Luimneach"),
		"2961123" => t("Tralee"),
		"2960992" => t("Waterford"),
	);
}


function location_cities_list_ie_c () {
	return array (
		"2964180" => t("Gaillimh"),
		"2961423" => t("Sligo"),
	);
}


function location_cities_list_ie_u () {
	return array (
		"2962961" => t("Letterkenny"),
	);
}


