<?php


function location_cities_list_is_1 () {
	return array (
		"3413829" => t("Reykjavik"),
		"3415212" => t("Kopavogur"),
		"3416706" => t("Hafnarfjordur"),
	);
}


function location_cities_list_is_7 () {
	return array (
	);
}


function location_cities_list_is_6 () {
	return array (
		"2633274" => t("Akureyri"),
	);
}


function location_cities_list_is_5 () {
	return array (
	);
}


function location_cities_list_is_8 () {
	return array (
	);
}


function location_cities_list_is_2 () {
	return array (
	);
}


function location_cities_list_is_3 () {
	return array (
	);
}


function location_cities_list_is_4 () {
	return array (
	);
}
