<?php


function location_cities_list_ps_gz() {
  return array(
    "281102" => "Rafah",
    "281109" => "An Nusayrat",
    "281124" => "Khan Yunis",
    "281129" => "Jabalya",
    "281133" => "Gaza",
    "281141" => "Dayr al Balah",
    "281145" => "Bayt Lahya",
    "281146" => "Bayt Hanun",
    "281148" => "Bani Suhayla",
    "281161" => "Al Burayj",
    "281165" => "`Abasan al Kabirah",
  );
}


function location_cities_list_ps_we() {
  return array(
    "281292"  => "Yuta",
    "281577"  => "Tulkarm",
    "281581"  => "Tubas",
    "281793"  => "Sa`ir",
    "282239"  => "Ramallah",
    "282457"  => "Qalqilyah",
    "282476"  => "Qabatiyah",
    "282615"  => "Nablus",
    "283506"  => "Janin",
    "283621"  => "Idhna",
    "283806"  => "Halhul",
    "284011"  => "Dura",
    "284315"  => "Bethlehem",
    "284324"  => "Bayt Jala",
    "284431"  => "Bani Na`im",
    "284446"  => "Balatah",
    "284486"  => "Az Zahiriyah",
    "284583"  => "As Samu`",
    "284890"  => "Ar Ram wa Dahiyat al Barid",
    "284899"  => "Jericho",
    "284999"  => "Al Yamun",
    "285066"  => "Hebron",
    "285108"  => "Al Birah",
    "285111"  => "Al `Ayzariyah",
    "7303419" => "East Jerusalem",
  );
}
