<?php

function location_cities_list_bw_ce () {
	return array (
		"933535" => t("Letlhakane"),
		"933471" => t("Mahalapye"),
		"933182" => t("Palapye"),
		"933099" => t("Selebi-Phikwe"),
		"933088" => t("Serowe"),
		"933000" => t("Tonota"),
	);
}


function location_cities_list_bw_kw () {
	return array (
		"933331" => t("Mogoditshane"),
		"933305" => t("Molepolole"),
		"933018" => t("Thamaga"),
	);
}


function location_cities_list_bw_se () {
	return array (
		"933773" => t("Gaborone"),
		"933719" => t("Janeng"),
		"933521" => t("Lobatse"),
		"933141" => t("Ramotswa"),
	);
}


function location_cities_list_bw_so () {
	return array (
		"933685" => t("Kanye"),
		"933271" => t("Mosopa"),
	);
}


function location_cities_list_bw_kl () {
	return array (
		"933340" => t("Mochudi"),
	);
}


function location_cities_list_bw_nw () {
	return array (
		"933366" => t("Maun"),
	);
}


function location_cities_list_bw_ne () {
	return array (
		"933778" => t("Francistown"),
	);
}


