<?php


function location_cities_list_th_10() {
  return array(
    "1609350" => "Bangkok",
  );
}


function location_cities_list_th_37() {
  return array(
    "1621060" => "Amnat Charoen",
  );
}


function location_cities_list_th_15() {
  return array(
    "1605018" => "Wiset Chaichan",
  );
}


function location_cities_list_th_81() {
  return array(
    "1152633" => "Krabi",
  );
}


function location_cities_list_th_31() {
  return array(
    "1607257" => "Prakhon Chai",
    "1608424" => "Nang Rong",
    "1611453" => "Buriram",
  );
}


function location_cities_list_th_24() {
  return array(
    "1607801" => "Phanom Sarakham",
    "1611439" => "Chachoengsao",
    "1619363" => "Bang Pakong",
  );
}


function location_cities_list_th_18() {
  return array(
    "1611416" => "Chai Nat",
  );
}


function location_cities_list_th_36() {
  return array(
    "1607439" => "Phu Khiao",
    "1610187" => "Kaset Sombun",
    "1610505" => "Kaeng Khro",
    "1611407" => "Chaiyaphum",
  );
}


function location_cities_list_th_22() {
  return array(
    "1605601" => "Tha Mai",
    "1609278" => "Laem Sing",
    "1611269" => "Chanthaburi",
  );
}


function location_cities_list_th_57() {
  return array(
    "1152194" => "Mae Sai",
    "1152227" => "Mae Chan",
    "1153669" => "Chiang Rai",
  );
}


function location_cities_list_th_20() {
  return array(
    "1606250" => "Si Racha",
    "1606386" => "Sattahip",
    "1607793" => "Phan Thong",
    "1607838" => "Phanat Nikhom",
    "1611110" => "Chon Buri",
    "1614295" => "Phatthaya",
    "1619423" => "Bang Lamung",
    "1620442" => "Ban Talat Bueng",
  );
}


function location_cities_list_th_86() {
  return array(
    "1152432" => "Lang Suan",
    "1153557" => "Chumphon",
  );
}


function location_cities_list_th_46() {
  return array(
    "1595679" => "Nong Kung Si",
    "1609345" => "Kuchinarai",
    "1609990" => "Khao Wong",
    "1610459" => "Kamalasai",
    "1610469" => "Kalasin",
  );
}


function location_cities_list_th_62() {
  return array(
    "1152953" => "Khanu Woralaksaburi",
    "1153090" => "Kamphaeng Phet",
  );
}


function location_cities_list_th_71() {
  return array(
    "1150246" => "Tha Muang",
    "1150275" => "Tha Maka",
    "1153081" => "Kanchanaburi",
    "1153850" => "Bo Phloi",
  );
}


function location_cities_list_th_40() {
  return array(
    "1609776" => "Khon Kaen",
    "1611026" => "Chum Phae",
    "1614455" => "Ban Phai",
  );
}


function location_cities_list_th_52() {
  return array(
    "1150154" => "Thoen",
    "1152473" => "Lampang",
  );
}


function location_cities_list_th_51() {
  return array(
    "1151528" => "Pa Sang",
    "1152468" => "Lamphun",
  );
}


function location_cities_list_th_42() {
  return array(
    "1605102" => "Wang Saphung",
    "1607435" => "Phu Kradueng",
    "1609071" => "Loei",
  );
}


function location_cities_list_th_16() {
  return array(
    "1609032" => "Lop Buri",
    "1611424" => "Chai Badan",
  );
}


function location_cities_list_th_58() {
  return array();
}


function location_cities_list_th_44() {
  return array(
    "1608900" => "Maha Sarakham",
  );
}


function location_cities_list_th_49() {
  return array(
    "1608597" => "Mukdahan",
  );
}


function location_cities_list_th_26() {
  return array(
    "1608539" => "Nakhon Nayok",
  );
}


function location_cities_list_th_73() {
  return array(
    "1606638" => "Sam Phran",
    "1608534" => "Nakhon Pathom",
    "1619415" => "Bang Len",
  );
}


function location_cities_list_th_48() {
  return array(
    "1608531" => "Nakhon Phanom",
  );
}


function location_cities_list_th_30() {
  return array(
    "1603235" => "Ban Huai Thalaeng",
    "1608057" => "Pak Chong",
    "1608136" => "Non Sung",
    "1608529" => "Nakhon Ratchasima",
    "1609795" => "Khon Buri",
    "1610963" => "Dan Khun Thot",
    "1611135" => "Chok Chai",
    "1611492" => "Bua Yai",
    "1948015" => "Amphoe Sikhiu",
  );
}


function location_cities_list_th_60() {
  return array(
    "1152377" => "Lat Yao",
    "1608527" => "Nakhon Sawan",
  );
}


function location_cities_list_th_80() {
  return array(
    "1150085" => "Thung Song",
    "1150921" => "Ron Phibun",
    "1151933" => "Nakhon Si Thammarat",
    "1608033" => "Pak Phanang",
  );
}


function location_cities_list_th_55() {
  return array(
    "1608452" => "Nan",
  );
}


function location_cities_list_th_96() {
  return array(
    "1605957" => "Tak Bai",
    "1606050" => "Su-ngai Kolok",
    "1607083" => "Ra-ngae",
    "1608409" => "Narathiwat",
  );
}


function location_cities_list_th_39() {
  return array(
    "1604654" => "Na Klang",
    "1608269" => "Nong Bua Lamphu",
  );
}


function location_cities_list_th_43() {
  return array(
    "1605677" => "Tha Bo",
    "1607615" => "Phon Charoen",
    "1608232" => "Nong Khai",
  );
}


function location_cities_list_th_12() {
  return array(
    "1608048" => "Pak Kret",
    "1608133" => "Mueang Nonthaburi",
    "1619434" => "Bang Kruai",
    "1619602" => "Bang Bua Thong",
  );
}


function location_cities_list_th_13() {
  return array(
    "1607983" => "Pathum Thani",
    "1609899" => "Khlong Luang",
    "1613769" => "Ban Rangsit",
    "1617111" => "Ban Lam Luk Ka",
  );
}


function location_cities_list_th_94() {
  return array(
    "1604771" => "Yaring",
    "1607978" => "Pattani",
  );
}


function location_cities_list_th_82() {
  return array();
}


function location_cities_list_th_93() {
  return array(
    "1607779" => "Phatthalung",
  );
}


function location_cities_list_th_56() {
  return array(
    "1151426" => "Phayao",
    "1153464" => "Dok Kham Tai",
  );
}


function location_cities_list_th_67() {
  return array(
    "1605024" => "Wichian Buri",
    "1607737" => "Phetchabun",
    "1608191" => "Nong Phai",
    "1609043" => "Lom Sak",
    "1611106" => "Chon Daen",
  );
}


function location_cities_list_th_76() {
  return array(
    "1149698" => "Phetchaburi",
    "1152919" => "Khao Yoi",
    "1153807" => "Cha-am",
    "1605467" => "Tha Yang",
  );
}


function location_cities_list_th_66() {
  return array(
    "1605538" => "Thap Khlo",
    "1605754" => "Taphan Hin",
    "1607725" => "Phichit",
    "1619400" => "Bang Mun Nak",
  );
}


function location_cities_list_th_65() {
  return array(
    "1607708" => "Phitsanulok",
    "1619276" => "Bang Rakam",
    "1619437" => "Bang Krathum",
  );
}


function location_cities_list_th_14() {
  return array(
    "1605118" => "Wang Noi",
    "1605509" => "Tha Ruea",
    "1607532" => "Phra Nakhon Si Ayutthaya",
    "1607865" => "Phak Hai",
    "1608541" => "Nakhon Luang",
    "1619369" => "Bang Pa-in",
    "1619616" => "Bang Ban",
    "1620875" => "Ban Bang Kadi Pathum Thani",
  );
}


function location_cities_list_th_54() {
  return array(
    "1607552" => "Phrae",
    "1610943" => "Den Chai",
  );
}


function location_cities_list_th_25() {
  return array(
    "1607280" => "Prachin Buri",
    "1610538" => "Kabin Buri",
  );
}


function location_cities_list_th_77() {
  return array(
    "1117823" => "Sam Roi Yot",
    "1151063" => "Pran Buri",
    "1151074" => "Prachuap Khiri Khan",
    "1152562" => "Kui Buri",
    "1153269" => "Hua Hin",
    "1157662" => "Bang Saphan",
  );
}


function location_cities_list_th_85() {
  return array(
    "1150965" => "Ranong",
  );
}


function location_cities_list_th_70() {
  return array(
    "1150954" => "Ratchaburi",
    "1151340" => "Photharam",
    "1153513" => "Damnoen Saduak",
    "1153646" => "Chom Bueng",
    "1155139" => "Ban Pong",
    "1157683" => "Bang Phae",
  );
}


function location_cities_list_th_21() {
  return array(
    "1607017" => "Rayong",
    "1609610" => "Klaeng",
    "1620254" => "Ban Chang",
  );
}


function location_cities_list_th_45() {
  return array(
    "1607001" => "Roi Et",
    "1610185" => "Kaset Wisai",
    "1613284" => "Ban Selaphum",
  );
}


function location_cities_list_th_27() {
  return array(
    "1605119" => "Wang Nam Yen",
    "1606807" => "Sa Kaeo",
    "1621020" => "Aranyaprathet",
  );
}


function location_cities_list_th_47() {
  return array(
    "1606350" => "Sawang Daen Din",
    "1606790" => "Sakon Nakhon",
  );
}


function location_cities_list_th_11() {
  return array(
    "1604452" => "Ban Khlong Bang Sao Thong",
    "1606590" => "Samut Prakan",
    "1607508" => "Phra Pradaeng",
    "1620919" => "Ban Bang Bo (1)",
  );
}


function location_cities_list_th_74() {
  return array(
    "1606588" => "Samut Sakhon",
    "1609395" => "Krathum Baen",
    "1614465" => "Ban Phaeo",
  );
}


function location_cities_list_th_75() {
  return array(
    "1606586" => "Samut Songkhram",
  );
}


function location_cities_list_th_19() {
  return array(
    "1606418" => "Saraburi",
    "1607512" => "Phra Phutthabat",
    "1608239" => "Nong Khae",
    "1610503" => "Kaeng Khoi",
    "1616658" => "Ban Mo",
  );
}


function location_cities_list_th_91() {
  return array(
    "1606376" => "Satun",
  );
}


function location_cities_list_th_17() {
  return array(
    "1606270" => "Sing Buri",
    "1619281" => "Bang Racham",
  );
}


function location_cities_list_th_33() {
  return array(
    "1606239" => "Si Sa Ket",
    "1610227" => "Kantharalak",
  );
}


function location_cities_list_th_90() {
  return array(
    "1601579" => "Ban Mai",
    "1606147" => "Songkhla",
    "1606939" => "Sadao",
    "1607068" => "Ranot",
    "1610780" => "Hat Yai",
  );
}


function location_cities_list_th_64() {
  return array(
    "1150533" => "Sukhothai",
    "1150624" => "Si Satchanalai",
    "1150681" => "Sawankhalok",
    "1156257" => "Ban Na",
  );
}


function location_cities_list_th_72() {
  return array(
    "1606033" => "Suphan Buri",
  );
}


function location_cities_list_th_84() {
  return array(
    "1150515" => "Surat Thani",
    "1151211" => "Phunphin",
    "1154689" => "Ko Samui",
    "1156046" => "Ban Na San",
  );
}


function location_cities_list_th_32() {
  return array(
    "1606030" => "Surin",
  );
}


function location_cities_list_th_63() {
  return array(
    "1150490" => "Tak",
    "1152188" => "Mae Sot",
    "1152202" => "Mae Ramat",
    "1154677" => "Ban Tak",
  );
}


function location_cities_list_th_92() {
  return array(
    "1150007" => "Trang",
    "1153241" => "Huai Yot",
  );
}


function location_cities_list_th_23() {
  return array(
    "1605279" => "Trat",
  );
}


function location_cities_list_th_34() {
  return array(
    "1605069" => "Warin Chamrap",
    "1605245" => "Ubon Ratchathani",
    "1607730" => "Phibun Mangsahan",
    "1610940" => "Det Udom",
  );
}


function location_cities_list_th_41() {
  return array(
    "1599640" => "Ban Nong Wua So",
    "1605239" => "Udon Thani",
    "1608462" => "Nam Som",
    "1609324" => "Kut Chap",
    "1614336" => "Ban Phan Don",
    "1619650" => "Ban Dung",
  );
}


function location_cities_list_th_61() {
  return array(
    "1150210" => "Thap Than",
    "1605221" => "Uthai Thani",
  );
}


function location_cities_list_th_53() {
  return array(
    "1605215" => "Uttaradit",
  );
}


function location_cities_list_th_95() {
  return array(
    "1604870" => "Yala",
    "1611635" => "Betong",
  );
}


function location_cities_list_th_35() {
  return array(
    "1604769" => "Yasothon",
  );
}


function location_cities_list_th_50() {
  return array(
    "1150728" => "San Pa Tong",
    "1150732" => "San Kamphaeng",
    "1153386" => "Hang Dong",
    "1153671" => "Chiang Mai",
  );
}


function location_cities_list_th_83() {
  return array(
    "1117652" => "Ban Talat Yai",
    "1117656" => "Ban Talat Nua",
    "1151254" => "Phuket",
    "1153035" => "Kathu",
    "6696291" => "Wichit",
    "7091861" => "Ban Chalong",
    "7091912" => "Ban Ratsada",
  );
}
