<?php


function location_cities_list_bf_01() {
  return array(
    "2354176" => "Tougan",
    "2357163" => "Nouna",
    "2361477" => "Dedougou",
  );
}


function location_cities_list_bf_02() {
  return array(
    "2362909" => "Banfora",
  );
}


function location_cities_list_bf_03() {
  return array(
    "2357048" => "Ouagadougou",
  );
}


function location_cities_list_bf_04() {
  return array(
    "2354675" => "Tenkodogo",
    "2358738" => "Koupela",
    "2360615" => "Garango",
  );
}


function location_cities_list_bf_05() {
  return array(
    "2359142" => "Kongoussi",
    "2359608" => "Kaya",
    "2361946" => "Boulsa",
  );
}


function location_cities_list_bf_06() {
  return array(
    "2356228" => "Reo",
    "2358382" => "Leo",
    "2358946" => "Koudougou",
    "2359317" => "Kokologo",
  );
}


function location_cities_list_bf_07() {
  return array(
    "2356454" => "Po",
    "2358100" => "Manga",
    "2359227" => "Kombissiri",
  );
}


function location_cities_list_bf_08() {
  return array(
    "2360886" => "Fada N'gourma",
    "2361373" => "Diapaga",
  );
}


function location_cities_list_bf_09() {
  return array(
    "2360073" => "Hounde",
    "2362344" => "Bobo-Dioulasso",
    "2577164" => "Orodara",
  );
}


function location_cities_list_bf_10() {
  return array(
    "2353688" => "Yako",
    "2354349" => "Titao",
    "2357043" => "Ouahigouya",
    "2360238" => "Gourcy",
  );
}


function location_cities_list_bf_11() {
  return array(
    "2353197" => "Zorgo",
    "2361845" => "Bousse",
  );
}


function location_cities_list_bf_12() {
  return array(
    "2361082" => "Dori",
    "2361177" => "Djibo",
  );
}


function location_cities_list_bf_13() {
  return array(
    "2577162" => "Gaoua",
  );
}
