<?php


function location_cities_list_ga_1() {
  return array(
    "2399697" => t("Libreville"),
  );
}


function location_cities_list_ga_4() {
  return array(
    "2398073" => t("Mouila"),
  );
}


function location_cities_list_ga_5() {
  return array(
    "2396253" => t("Tchibanga"),
  );
}


function location_cities_list_ga_6() {
  return array();
}


function location_cities_list_ga_7() {
  return array(
    "2399959" => t("Koulamoutou"),
  );
}


function location_cities_list_ga_8() {
  return array(
    "2396518" => t("Port-Gentil"),
  );
}


function location_cities_list_ga_2() {
  return array(
    "2398269" => t("Moanda"),
    "2400555" => t("Franceville"),
  );
}


function location_cities_list_ga_3() {
  return array(
    "2399888" => t("Lambarene"),
  );
}


function location_cities_list_ga_9() {
  return array(
    "2396646" => t("Oyem"),
  );
}
