<?php

function location_cities_list_al_br()
{
  return array(
    '783626' => t('Rrethi i Beratit'),
    '3315069' => t('Rrethi i Kuçovës'),
    '781574' => t('Rrethi i Skraparit'),
  );
}

function location_cities_list_al_di()
{
  return array(
    '831275' => t('Rrethi i Bulqizës'),
    '783346' => t('Rrethi i Dibrës'),
    '782345' => t('Rrethi i Matit'),
  );
}

function location_cities_list_al_dr()
{
  return array(
    '3185730' => t('Rrethi i Durrësit'),
    '3185084' => t('Rrethi i Krujës'),
  );
}

function location_cities_list_al_el()
{
  return array(
    '783265' => t('Rrethi i Elbasanit'),
    '783060' => t('Rrethi i Gramshit'),
    '782521' => t('Rrethi i Librazhdit'),
    '3342179' => t('Rrethi i Peqinit'),
  );
}

function location_cities_list_al_fr()
{
  return array(
    '3185674' => t('Rrethi i Fierit'),
    '3184864' => t('Rrethi i Lushnjës'),
    '3316444' => t('Rrethi i Mallakastrës'),
  );
}

function location_cities_list_al_gj()
{
  return array(
    '783151' => t('Rrethi i Gjirokastrës'),
    '782072' => t('Rrethi i Përmetit'),
    '3183911' => t('Rrethi i Tepelenës'),
  );
}

function location_cities_list_al_ko()
{
  return array(
    '831276' => t('Rrethi i Devollit'),
    '782775' => t('Rrethi i Kolonjës'),
    '782758' => t('Rrethi i Korçës'),
    '781990' => t('Rrethi i Pogradecit'),
  );
}

function location_cities_list_al_ku()
{
  return array(
    '831098' => t('Rrethi i Hasit'),
    '782662' => t('Rrethi i Kukësit'),
    '781360' => t('Rrethi i Tropojës'),
  );
}

function location_cities_list_al_le()
{
  return array(
    '3315070' => t('Rrethi i Kurbinit'),
    '3184937' => t('Rrethi i Lezhës'),
    '782268' => t('Rrethi i Mirditës'),
  );
}

function location_cities_list_al_sh()
{
  return array(
    '3338383' => t('Rrethi i Malësia e Madhe'),
    '781913' => t('Rrethi i Pukës'),
    '3184083' => t('Rrethi i Shkodrës'),
  );
}

function location_cities_list_al_tr()
{
  return array(
    '3315068' => t('Rrethi i Kavajës'),
    '3183879' => t('Rrethi i Tiranës'),
  );
}

function location_cities_list_al_vl()
{
  return array(
    '414383' => t('Rrethi i Delvinës'),
    '363245' => t('Rrethi i Sarandës'),
    '3183721' => t('Rrethi i Vlorës'),
  );
}
