<?php

function location_cities_list_ps_gz () {
	return array (
		"281102" => t("Rafah"),
		"281109" => t("An Nusayrat"),
		"281124" => t("Khan Yunis"),
		"281129" => t("Jabalya"),
		"281133" => t("Gaza"),
		"281141" => t("Dayr al Balah"),
		"281145" => t("Bayt Lahya"),
		"281146" => t("Bayt Hanun"),
		"281148" => t("Bani Suhayla"),
		"281161" => t("Al Burayj"),
		"281165" => t("`Abasan al Kabirah"),
	);
}


function location_cities_list_ps_we () {
	return array (
		"281292" => t("Yuta"),
		"281577" => t("Tulkarm"),
		"281581" => t("Tubas"),
		"281793" => t("Sa`ir"),
		"282239" => t("Ramallah"),
		"282457" => t("Qalqilyah"),
		"282476" => t("Qabatiyah"),
		"282615" => t("Nablus"),
		"283506" => t("Janin"),
		"283621" => t("Idhna"),
		"283806" => t("Halhul"),
		"284011" => t("Dura"),
		"284315" => t("Bethlehem"),
		"284324" => t("Bayt Jala"),
		"284431" => t("Bani Na`im"),
		"284446" => t("Balatah"),
		"284486" => t("Az Zahiriyah"),
		"284583" => t("As Samu`"),
		"284890" => t("Ar Ram wa Dahiyat al Barid"),
		"284899" => t("Jericho"),
		"284999" => t("Al Yamun"),
		"285066" => t("Hebron"),
		"285108" => t("Al Birah"),
		"285111" => t("Al `Ayzariyah"),
		"7303419" => t("East Jerusalem"),
	);
}
