<?php


function location_cities_list_ec_b() {
  return array(
    "3657571" => "Guaranda",
  );
}


function location_cities_list_ec_x() {
  return array(
    "3652684" => "Pujili",
    "3654870" => "Latacunga",
    "3655117" => "La Mana",
  );
}


function location_cities_list_ec_o() {
  return array(
    "3651356" => "Santa Rosa",
    "3653130" => "Pinas",
    "3653403" => "Pasaje",
    "3654533" => "Machala",
    "3655720" => "Huaquillas",
  );
}


function location_cities_list_ec_e() {
  return array(
    "3651694" => "San Lorenzo de Esmeraldas",
    "3652257" => "Rosa Zarate",
    "3657990" => "Esmeraldas",
  );
}


function location_cities_list_ec_d() {
  return array(
    "3652743" => "Puerto Francisco de Orellana",
    "3660152" => "Boca Suno",
  );
}


function location_cities_list_ec_w() {
  return array();
}


function location_cities_list_ec_i() {
  return array(
    "3653693" => "Otavalo",
    "3655673" => "Ibarra",
    "3660478" => "Atuntaqui",
  );
}


function location_cities_list_ec_l() {
  return array(
    "3654667" => "Loja",
    "3659599" => "Catamayo",
    "3659711" => "Cariamanga",
  );
}


function location_cities_list_ec_r() {
  return array(
    "3650186" => "Vinces",
    "3650267" => "Ventanas",
    "3652567" => "Quevedo",
    "3654064" => "Montalvo",
    "3660418" => "Babahoyo",
  );
}


function location_cities_list_ec_m() {
  return array(
    "3650960" => "Sucre",
    "3652941" => "Portoviejo",
    "3654055" => "Montecristi",
    "3654410" => "Manta",
    "3655446" => "Jipijapa",
    "3659139" => "Chone",
    "3659926" => "Calceta",
    "3660401" => "Bahia de Caraquez",
  );
}


function location_cities_list_ec_s() {
  return array(
    "3654541" => "Macas",
  );
}


function location_cities_list_ec_n() {
  return array(
    "3650721" => "Tena",
  );
}


function location_cities_list_ec_p() {
  return array(
    "3652462" => "Quito",
    "3654536" => "Machachi",
    "3659578" => "Cayambe",
  );
}


function location_cities_list_ec_se() {
  return array(
    "3651438" => "Santa Elena",
  );
}


function location_cities_list_ec_sd() {
  return array(
    "3651297" => "Santo Domingo de los Colorados",
  );
}


function location_cities_list_ec_u() {
  return array(
    "3655185" => "Nueva Loja",
  );
}


function location_cities_list_ec_z() {
  return array(
    "3649959" => "Zamora",
  );
}


function location_cities_list_ec_a() {
  return array(
    "3657670" => "Gualaceo",
    "3658666" => "Cuenca",
  );
}


function location_cities_list_ec_c() {
  return array(
    "3650472" => "Tulcan",
    "3651868" => "San Gabriel",
  );
}


function location_cities_list_ec_f() {
  return array(
    "3654853" => "La Troncal",
    "3660434" => "Azogues",
  );
}


function location_cities_list_ec_h() {
  return array(
    "3652350" => "Riobamba",
  );
}


function location_cities_list_ec_g() {
  return array(
    "3650121" => "Yaguachi Nuevo",
    "3650273" => "Velasco Ibarra",
    "3652065" => "Samborondon",
    "3652100" => "Salinas",
    "3653015" => "Playas",
    "3653295" => "Pedro Carbo",
    "3653873" => "Naranjito",
    "3653882" => "Naranjal",
    "3655131" => "La Libertad",
    "3657509" => "Guayaquil",
    "3658053" => "El Triunfo",
    "3658192" => "Eloy Alfaro",
    "3660361" => "Balzar",
  );
}


function location_cities_list_ec_y() {
  return array(
    "3652584" => "Puyo",
  );
}


function location_cities_list_ec_t() {
  return array(
    "3653287" => "Pelileo",
    "3660689" => "Ambato",
  );
}
