<?php

function location_cities_list_tg_c () {
	return array (
		"2363908" => t("Tchamba"),
		"2364079" => t("Sotouboua"),
		"2364104" => t("Sokode"),
	);
}


function location_cities_list_tg_k () {
	return array (
		"2364812" => t("Niamtougou"),
		"2366152" => t("Kara"),
		"2367568" => t("Bassar"),
		"2367656" => t("Bafilo"),
	);
}


function location_cities_list_tg_m () {
	return array (
		"2363490" => t("Vogan"),
		"2363534" => t("Tsevie"),
		"2365267" => t("Lome"),
		"2367990" => t("Aneho"),
	);
}


function location_cities_list_tg_p () {
	return array (
		"2364752" => t("Notse"),
		"2365560" => t("Kpalime"),
		"2367886" => t("Atakpame"),
	);
}


function location_cities_list_tg_s () {
	return array (
		"2365190" => t("Sansanne-Mango"),
		"2367164" => t("Dapaong"),
	);
}
