<?php


function location_cities_list_lk_2() {
  return array(
    "1232783" => t("Nuwara Eliya"),
    "1241622" => t("Kandy"),
    "1244596" => t("Hatton"),
    "1246000" => t("Gampola"),
    "1248749" => t("Dambulla"),
  );
}


function location_cities_list_lk_5() {
  return array(
    "1226260" => t("Trincomalee"),
    "1242110" => t("Kalmunai"),
    "1246924" => t("Eravur Town"),
    "1250161" => t("Batticaloa"),
    "1251459" => t("Ampara"),
  );
}


function location_cities_list_lk_7() {
  return array(
    "1251081" => t("Anuradhapura"),
  );
}


function location_cities_list_lk_6() {
  return array(
    "1229293" => t("Puttalam"),
    "1237980" => t("Kurunegala"),
    "1249145" => t("Chilaw"),
  );
}


function location_cities_list_lk_4() {
  return array(
    "1225018" => t("Vavuniya"),
    "1225142" => t("Valvedditturai"),
    "1229989" => t("Point Pedro"),
    "1242833" => t("Jaffna"),
  );
}


function location_cities_list_lk_9() {
  return array(
    "1228730" => t("Ratnapura"),
  );
}


function location_cities_list_lk_8() {
  return array(
    "1250615" => t("Badulla"),
  );
}


function location_cities_list_lk_3() {
  return array(
    "1223738" => t("Weligama"),
    "1235846" => t("Matara"),
    "1246294" => t("Galle"),
    "1249978" => t("Bentota"),
    "1251574" => t("Ambalangoda"),
  );
}


function location_cities_list_lk_1() {
  return array(
    "1223648" => t("Welisara"),
    "1224085" => t("Wattala"),
    "1230089" => t("Pita Kotte"),
    "1230613" => t("Peliyagoda"),
    "1231410" => t("Panadura"),
    "1233369" => t("Negombo"),
    "1234378" => t("Mulleriyawa"),
    "1234633" => t("Moratuwa"),
    "1236854" => t("Maharagama"),
    "1238992" => t("Sri Jayewardenepura Kotte"),
    "1239047" => t("Kotikawatta"),
    "1239593" => t("Kolonnawa"),
    "1240622" => t("Kelaniya"),
    "1240935" => t("Katunayaka North"),
    "1241750" => t("Kandana"),
    "1241964" => t("Kalutara"),
    "1242835" => t("Ja Ela"),
    "1243936" => t("Homagama"),
    "1244397" => t("Hendala"),
    "1244773" => t("Hanwella Ihala"),
    "1246321" => t("Galkissa"),
    "1248991" => t("Colombo"),
    "1249931" => t("Beruwala"),
    "1250164" => t("Battaramulla South"),
  );
}
