<?php

function location_cities_list_tl_co () {
	return array (
		"1626459" => t("Suai"),
	);
}


function location_cities_list_tl_bo () {
	return array (
		"1636670" => t("Maliana"),
	);
}


function location_cities_list_tl_li () {
	return array (
		"1637730" => t("Liquica"),
	);
}


function location_cities_list_tl_di () {
	return array (
		"1645457" => t("Dili"),
	);
}


function location_cities_list_tl_ba () {
	return array (
		"1649539" => t("Baucau"),
	);
}


function location_cities_list_tl_al () {
	return array (
		"1651816" => t("Aileu"),
	);
}


function location_cities_list_tl_mf () {
	return array (
		"1937031" => t("Same"),
	);
}


function location_cities_list_tl_la () {
	return array (
		"1937274" => t("Lospalos"),
	);
}


