<?php


function location_cities_list_ma_09() {
  return array(
    "2537406" => "Settat",
    "2540689" => "Oued Zem",
    "2544248" => "Khouribga",
    "2553751" => "Bouznika",
    "2556272" => "Berrechid",
    "6546693" => "Boujniba",
  );
}


function location_cities_list_ma_10() {
  return array(
    "2526488" => "Youssoufia",
    "2536074" => "Sidi Bennour",
    "2537881" => "Safi",
    "2550078" => "El Jadida",
    "2556657" => "Azemmour",
  );
}


function location_cities_list_ma_02() {
  return array(
    "2532394" => "Souq Larb'a al Gharb",
    "2532822" => "Sidi Yahia el Gharb",
    "2532945" => "Sidi Slimane",
    "2533191" => "Sidi Qacem",
    "2540810" => "Ouazzane",
    "2542866" => "Mechra Belqsiri",
    "2544571" => "Kenitra",
  );
}


function location_cities_list_ma_14() {
  return array(
    "2530241" => "Tan-Tan",
    "2548526" => "Guelmim",
  );
}


function location_cities_list_ma_15() {
  return array();
}


function location_cities_list_ma_11() {
  return array(
    "2542997" => "Marrakesh",
    "2549263" => "Essaouira",
  );
}


function location_cities_list_ma_04() {
  return array(
    "2526435" => "Zaio",
    "2530048" => "Taourirt",
    "2540483" => "Oujda",
    "2541479" => "Nador",
    "2545017" => "Jerada",
    "2550806" => "El Aioun",
    "2555467" => "Berkane",
    "2561124" => "Ahfir",
  );
}


function location_cities_list_ma_eh() {
  return array(
    "8542188" => "Dakhla",
  );
}


function location_cities_list_ma_05() {
  return array(
    "2537545" => "Sefrou",
    "2548885" => "Fes",
  );
}


function location_cities_list_ma_06() {
  return array(
    "2542227" => "Midelt",
    "2542715" => "Meknes",
    "2544333" => "Khenifra",
    "2550252" => "El Hajeb",
    "2556464" => "Azrou",
  );
}


function location_cities_list_ma_07() {
  return array(
    "2528659" => "Tiflet",
    "2537763" => "Sale",
    "2538475" => "Rabat",
    "2558470" => "Khemisset",
    "2562055" => "Skhirat",
  );
}


function location_cities_list_ma_13() {
  return array(
    "2526452" => "Zagora",
    "2527089" => "Tiznit",
    "2527915" => "Tineghir",
    "2529649" => "Taroudant",
    "2534515" => "Sidi Ifni",
    "2539134" => "Oulad Teima",
    "2540850" => "Ouarzazat",
    "2561668" => "Agadir",
  );
}


function location_cities_list_ma_01() {
  return array(
    "2528910" => "Tetouan",
    "2530335" => "Tangier",
    "2542987" => "Martil",
    "2543549" => "Larache",
    "2544001" => "Ksar el Kebir",
    "2553455" => "Chefchaouene",
    "2557055" => "Asilah",
  );
}


function location_cities_list_ma_08() {
  return array(
    "2542051" => "Mohammedia",
    "2553604" => "Casablanca",
  );
}


function location_cities_list_ma_12() {
  return array(
    "2544720" => "Kasba Tadla",
    "2548830" => "Fkih Ben Salah",
    "2555745" => "Beni Mellal",
  );
}


function location_cities_list_ma_03() {
  return array(
    "2527645" => "Tirhanimine",
    "2529317" => "Taza",
    "2530155" => "Taounate",
    "2531480" => "Tahala",
    "2545985" => "Imzourene",
    "2548489" => "Guercif",
    "2558545" => "Al Hoceima",
  );
}
