<?php

function location_cities_list_vn_44 () {
	return array (
		"1575627" => t("Long Xuyen"),
		"1585660" => t("Cho Dok"),
	);
}


function location_cities_list_vn_30 () {
	return array (
		"1569684" => t("Pleiku"),
	);
}


function location_cities_list_vn_73 () {
	return array (
		"1562538" => t("Vi Thanh"),
	);
}


function location_cities_list_vn_65 () {
	return array (
		"1566083" => t("Ho Chi Minh City"),
		"1584661" => t("Cu Chi"),
		"1586288" => t("Can Gio"),
	);
}


function location_cities_list_vn_71 () {
	return array (
		"1583477" => t("Dien Bien Phu"),
	);
}


function location_cities_list_vn_28 () {
	return array (
		"1578500" => t("Kon Tum"),
	);
}


function location_cities_list_vn_41 () {
	return array (
		"1567069" => t("Tan An"),
		"1586296" => t("Can Duoc"),
	);
}


function location_cities_list_vn_48 () {
	return array (
		"1586203" => t("Can Tho"),
	);
}


function location_cities_list_vn_64 () {
	return array (
		"1567621" => t("Son Tay"),
		"1581130" => t("Hanoi"),
		"1581364" => t("Ha Dong"),
	);
}


function location_cities_list_vn_62 () {
	return array (
		"1581298" => t("Haiphong"),
	);
}


function location_cities_list_vn_60 () {
	return array (
		"1583992" => t("Da Nang"),
	);
}


function location_cities_list_vn_43 () {
	return array (
		"1562414" => t("Vung Tau"),
	);
}


function location_cities_list_vn_57 () {
	return array (
		"1565022" => t("Thu Dau Mot"),
	);
}


function location_cities_list_vn_58 () {
	return array (
		"1582436" => t("Dong Xoai"),
	);
}


function location_cities_list_vn_40 () {
	return array (
		"1571058" => t("Phan Thiet"),
		"1577995" => t("Lagi"),
	);
}


function location_cities_list_vn_31 () {
	return array (
		"1568574" => t("Qui Nhon"),
	);
}


function location_cities_list_vn_55 () {
	return array (
		"1591474" => t("Thanh pho Bac Lieu"),
	);
}


function location_cities_list_vn_54 () {
	return array (
		"1591527" => t("Bac Giang"),
	);
}


function location_cities_list_vn_53 () {
	return array (
		"1591538" => t("Bac Kan"),
	);
}


function location_cities_list_vn_56 () {
	return array (
		"1591449" => t("Bac Ninh"),
	);
}


function location_cities_list_vn_50 () {
	return array (
		"1587976" => t("Ben Tre"),
	);
}


function location_cities_list_vn_04 () {
	return array (
		"1586185" => t("Thanh Pho Cao Bang"),
	);
}


function location_cities_list_vn_59 () {
	return array (
		"1586443" => t("Ca Mau"),
	);
}


function location_cities_list_vn_03 () {
	return array (
		"1581349" => t("Thanh Pho Ha Giang"),
	);
}


function location_cities_list_vn_63 () {
	return array (
		"1570449" => t("Thanh Pho Phu Ly"),
	);
}


function location_cities_list_vn_23 () {
	return array (
		"1581047" => t("Ha Tinh"),
	);
}


function location_cities_list_vn_14 () {
	return array (
		"1580830" => t("Thanh Pho Hoa Binh"),
	);
}


function location_cities_list_vn_66 () {
	return array (
		"1580142" => t("Hung Yen"),
	);
}


function location_cities_list_vn_61 () {
	return array (
		"1581326" => t("Hai Duong"),
	);
}


function location_cities_list_vn_34 () {
	return array (
		"1572151" => t("Nha Trang"),
		"1586350" => t("Cam Ranh"),
	);
}


function location_cities_list_vn_47 () {
	return array (
		"1568510" => t("Rach Gia"),
		"1581052" => t("Ha Tien"),
	);
}


function location_cities_list_vn_01 () {
	return array (
	);
}


function location_cities_list_vn_02 () {
	return array (
		"1568043" => t("Sa Pa"),
		"1576303" => t("Lao Cai"),
	);
}


function location_cities_list_vn_35 () {
	return array (
		"1584071" => t("Da Lat"),
	);
}


function location_cities_list_vn_09 () {
	return array (
		"1576633" => t("Thanh Pho Lang Son"),
	);
}


function location_cities_list_vn_67 () {
	return array (
		"1573517" => t("Thanh Pho Nam Dinh"),
	);
}


function location_cities_list_vn_22 () {
	return array (
		"1560037" => t("Yen Vinh"),
		"1562798" => t("Vinh"),
	);
}


function location_cities_list_vn_18 () {
	return array (
		"1571968" => t("Thanh Pho Ninh Binh"),
	);
}


function location_cities_list_vn_36 () {
	return array (
		"1571067" => t("Phan Rang-Thap Cham"),
	);
}


function location_cities_list_vn_68 () {
	return array (
		"1562820" => t("Viet Tri"),
	);
}


function location_cities_list_vn_32 () {
	return array (
		"1563281" => t("Tuy Hoa"),
		"1567723" => t("Song Cau"),
	);
}


function location_cities_list_vn_24 () {
	return array (
		"1582886" => t("Kwang Binh"),
	);
}


function location_cities_list_vn_27 () {
	return array (
		"1567148" => t("Tam Ky"),
		"1580541" => t("Hoi An"),
	);
}


function location_cities_list_vn_29 () {
	return array (
		"1568770" => t("Quang Ngai"),
	);
}


function location_cities_list_vn_13 () {
	return array (
		"1563241" => t("Thanh Pho Uong Bi"),
		"1574507" => t("Mong Cai"),
		"1580410" => t("Thanh Pho Ha Long"),
		"1586357" => t("Cam Pha Mines"),
	);
}


function location_cities_list_vn_25 () {
	return array (
		"1582926" => t("Dong Ha"),
	);
}


function location_cities_list_vn_52 () {
	return array (
		"1567788" => t("Soc Trang"),
	);
}


function location_cities_list_vn_05 () {
	return array (
		"1567681" => t("Son La"),
	);
}


function location_cities_list_vn_21 () {
	return array (
		"1566166" => t("Thanh Hoa"),
		"1587919" => t("Bim Son"),
	);
}


function location_cities_list_vn_20 () {
	return array (
		"1566346" => t("Thanh Pho Thai Binh"),
	);
}


function location_cities_list_vn_69 () {
	return array (
		"1566319" => t("Thai Nguyen"),
	);
}


function location_cities_list_vn_26 () {
	return array (
		"1580240" => t("Hue"),
	);
}


function location_cities_list_vn_46 () {
	return array (
		"1574023" => t("My Tho"),
	);
}


function location_cities_list_vn_51 () {
	return array (
		"1563926" => t("Tra Vinh"),
	);
}


function location_cities_list_vn_07 () {
	return array (
		"1563287" => t("Thanh Pho Tuyen Quang"),
	);
}


function location_cities_list_vn_37 () {
	return array (
		"1566559" => t("Tay Ninh"),
		"1570549" => t("Phu Khuong"),
	);
}


function location_cities_list_vn_49 () {
	return array (
		"1562693" => t("Vinh Long"),
	);
}


function location_cities_list_vn_70 () {
	return array (
		"1562548" => t("Vinh Yen"),
	);
}


function location_cities_list_vn_06 () {
	return array (
		"1560349" => t("Yen Bai"),
	);
}


function location_cities_list_vn_33 () {
	return array (
		"1586896" => t("Buon Ma Thuot"),
	);
}


function location_cities_list_vn_39 () {
	return array (
		"1587923" => t("Bien Hoa"),
	);
}


function location_cities_list_vn_45 () {
	return array (
		"1568212" => t("Sadek"),
		"1586151" => t("Cao Lanh"),
	);
}


function location_cities_list_vn_72 () {
	return array (
	);
}
