<?php

function location_cities_list_se_ac () {
	return array (
		"602913" => t("Skelleftea"),
		"602150" => t("Umea"),
	);
}


function location_cities_list_se_bd () {
	return array (
		"606531" => t("Boden"),
		"605155" => t("Kiruna"),
		"604490" => t("Lulea"),
		"603570" => t("Pitea"),
	);
}


function location_cities_list_se_m () {
	return array (
		"2725901" => t("AEngelholm"),
		"2715946" => t("Eslov"),
		"2707399" => t("Hassleholm"),
		"2706767" => t("Helsingborg"),
		"2699310" => t("Kristianstad"),
		"2697720" => t("Landskrona"),
		"2693678" => t("Lund"),
		"2692969" => t("Malmoe"),
		"2667402" => t("Trelleborg"),
		"2662149" => t("Ystad"),
	);
}


function location_cities_list_se_i () {
	return array (
		"2662689" => t("Visby"),
	);
}


function location_cities_list_se_g () {
	return array (
		"2663536" => t("Vaexjoe"),
	);
}


function location_cities_list_se_h () {
	return array (
		"2702261" => t("Kalmar"),
		"2686162" => t("Oskarshamn"),
		"2664203" => t("Vaestervik"),
	);
}


function location_cities_list_se_u () {
	return array (
		"2699791" => t("Koping"),
		"2664454" => t("Vasteras"),
	);
}


function location_cities_list_se_f () {
	return array (
		"2704136" => t("Huskvarna"),
		"2702979" => t("Jonkoping"),
		"2690170" => t("Nassjo"),
		"2664855" => t("Varnamo"),
	);
}


function location_cities_list_se_n () {
	return array (
		"2715573" => t("Falkenberg"),
		"2708365" => t("Halmstad"),
		"2698729" => t("Kungsbacka"),
		"2664996" => t("Varberg"),
	);
}


function location_cities_list_se_o () {
	return array (
		"2726756" => t("Alingsas"),
		"2720501" => t("Boras"),
		"2715568" => t("Falkoeping"),
		"2711537" => t("Goeteborg"),
		"2698739" => t("Kungalv"),
		"2696503" => t("Lerum"),
		"2696329" => t("Lidkoping"),
		"6619708" => t("Majorna"),
		"2691459" => t("Moelndal"),
		"2684395" => t("Partille"),
		"2677234" => t("Skoevde"),
		"2667303" => t("Trollhattan"),
		"2666670" => t("Uddevalla"),
		"2665171" => t("Vanersborg"),
	);
}


function location_cities_list_se_ab () {
	return array (
		"2727234" => t("Akersberga"),
		"2725201" => t("Arsta"),
		"2721259" => t("Boo"),
		"2719111" => t("Bromma"),
		"2707953" => t("Haninge"),
		"2704620" => t("Huddinge"),
		"2703396" => t("Jakobsberg"),
		"2700791" => t("Kista"),
		"2696334" => t("Lidingoe"),
		"2692475" => t("Marsta"),
		"2690580" => t("Nacka"),
		"2688250" => t("Norrtalje"),
		"2685828" => t("OEstermalm"),
		"2683034" => t("Rasunda"),
		"2676176" => t("Soedertaelje"),
		"2675408" => t("Sollentuna"),
		"2675397" => t("Solna"),
		"2673730" => t("Stockholm"),
		"2670879" => t("Sundbyberg"),
		"2669772" => t("Taby"),
		"2667109" => t("Tullinge"),
		"2667094" => t("Tumba"),
		"2666238" => t("Upplands Vaesby"),
		"2665452" => t("Vallentuna"),
	);
}


function location_cities_list_se_c () {
	return array (
		"2716166" => t("Enkoping"),
		"2666199" => t("Uppsala"),
	);
}


function location_cities_list_se_y () {
	return array (
		"2707684" => t("Haernoesand"),
		"2686469" => t("Ornskoldsvik"),
		"2670781" => t("Sundsvall"),
	);
}


function location_cities_list_se_x () {
	return array (
		"2712414" => t("Gavle"),
		"2680075" => t("Sandviken"),
	);
}


function location_cities_list_se_z () {
	return array (
		"2685750" => t("Ostersund"),
	);
}


function location_cities_list_se_t () {
	return array (
		"2701715" => t("Karlskoga"),
		"2686657" => t("Orebro"),
	);
}


function location_cities_list_se_d () {
	return array (
		"2715953" => t("Eskilstuna"),
		"2701223" => t("Katrineholm"),
		"2687700" => t("Nykoping"),
	);
}


function location_cities_list_se_e () {
	return array (
		"2694762" => t("Linkoping"),
		"2690960" => t("Motala"),
		"2688368" => t("Norrkoping"),
	);
}


function location_cities_list_se_s () {
	return array (
		"2701680" => t("Karlstad"),
		"2699282" => t("Kristinehamn"),
	);
}


function location_cities_list_se_k () {
	return array (
		"2701727" => t("Karlshamn"),
		"2701713" => t("Karlskrona"),
	);
}


function location_cities_list_se_w () {
	return array (
		"2720383" => t("Borlaenge"),
		"2715459" => t("Falun"),
	);
}


