<?php


function location_cities_list_my_01() {
  return array(
    "1732687" => "Batu Pahat",
    "1732698" => "Parit Raja",
    "1732706" => "Pekan Nenas",
    "1732711" => "Pontian Kechil",
    "1732721" => "Kampung Pasir Gudang Baru",
    "1732738" => "Kota Tinggi",
    "1732741" => "Taman Senai",
    "1732742" => "Kulai",
    "1732745" => "Sekudai",
    "1732752" => "Johor Bahru",
    "1732811" => "Kluang",
    "1732814" => "Yong Peng",
    "1732826" => "Mersing",
    "1732846" => "Segamat",
    "1732857" => "Tangkak",
    "1732869" => "Muar",
    "1732871" => "Bakeri",
    "1732877" => "Labis",
    "1738294" => "Ulu Tiram",
    "1764318" => "Kampung Simpang Renggam",
  );
}


function location_cities_list_my_02() {
  return array(
    "1222396" => "Kuah",
    "1734393" => "Kulim",
    "1734439" => "Bedong",
    "1735485" => "Gurun",
    "1735498" => "Sungai Petani",
    "1736302" => "Jitra",
    "1736305" => "Kuala Kedah",
    "1736309" => "Alor Setar",
  );
}


function location_cities_list_my_03() {
  return array(
    "1734651" => "Gua Musang",
    "1735553" => "Tanah Merah",
    "1736372" => "Pasir Mas",
    "1736376" => "Kota Bharu",
    "1750582" => "Peringat",
    "1766249" => "Kampong Pangkal Kalong",
    "1768664" => "Kampong Kadok",
  );
}


function location_cities_list_my_14() {
  return array(
    "1735161" => "Kuala Lumpur",
  );
}


function location_cities_list_my_15() {
  return array(
    "1733782" => "Victoria",
  );
}


function location_cities_list_my_04() {
  return array(
    "1734745" => "Alor Gajah",
    "1734753" => "Kampung Ayer Keroh",
    "1734757" => "Sungai Udang",
    "1734759" => "Melaka",
    "1761242" => "Klebang Besar",
    "1767021" => "Kampong Masjid Tanah",
    "1770351" => "Kampung Bukit Baharu",
    "1771485" => "Kampung Ayer Molek",
    "1778290" => "Bukit Rambai",
    "1780890" => "Berendam",
  );
}


function location_cities_list_my_05() {
  return array(
    "1734738" => "Tampin",
    "1734810" => "Seremban",
    "1734815" => "Port Dickson",
    "1734839" => "Bahau",
    "1734841" => "Kuala Pilah",
    "1771287" => "Kampung Baharu Nilai",
  );
}


function location_cities_list_my_06() {
  return array(
    "1732602" => "Jerantut",
    "1732663" => "Raub",
    "1733023" => "Kuala Lipis",
    "1734971" => "Pekan",
    "1735018" => "Mentekab",
    "1735022" => "Temerluh",
    "1735227" => "Kuantan",
    "1779790" => "Bentong Town",
  );
}


function location_cities_list_my_08() {
  return array(
    "1734409" => "Bagan Serai",
    "1734576" => "Simpang Empat",
    "1734586" => "Taiping",
    "1734599" => "Kuala Kangsar",
    "1734634" => "Ipoh",
    "1735089" => "Parit Buntar",
    "1735268" => "Batu Gajah",
    "1735274" => "Kampar",
    "1735282" => "Tapah Road",
    "1735287" => "Bidur",
    "1735450" => "Lumut",
    "1735459" => "Teluk Intan",
    "1752256" => "Pantai Remis",
  );
}


function location_cities_list_my_09() {
  return array(
    "1736278" => "Kangar",
  );
}


function location_cities_list_my_07() {
  return array(
    "1735076" => "Butterworth",
    "1735077" => "Perai",
    "1735079" => "Bukit Mertajam",
    "1735086" => "Nibong Tebal",
    "1735093" => "Tasek Glugor",
    "1735106" => "George Town",
    "1735506" => "Kepala Batas",
    "1741550" => "Tanjung Tokong",
    "1750500" => "Permatang Kuching",
    "1764160" => "Kampung Sungai Ara",
  );
}


function location_cities_list_my_16() {
  return array(
    "6697380" => "Putrajaya",
  );
}


function location_cities_list_my_12() {
  return array(
    "1733353" => "Papar",
    "1733432" => "Kota Kinabalu",
    "1733438" => "Donggongon",
    "1733440" => "Putatan",
    "1733449" => "Kinarut",
    "1733502" => "Ranau",
    "1733697" => "Semporna",
    "1733874" => "Beaufort",
    "1733953" => "Lahad Datu",
    "1734052" => "Sandakan",
    "1734098" => "Keningau",
    "1734199" => "Tawau",
    "1736458" => "Kudat",
    "7302815" => "Bandar Labuan",
  );
}


function location_cities_list_my_13() {
  return array(
    "1735634" => "Kuching",
    "1735799" => "Simanggang",
    "1735837" => "Sarikei",
    "1735902" => "Sibu",
    "1737185" => "Kapit",
    "1737486" => "Bintulu",
    "1737714" => "Limbang",
    "1738050" => "Miri",
  );
}


function location_cities_list_my_10() {
  return array(
    "1732891" => "Kuala Selangor",
    "1732903" => "Shah Alam",
    "1732905" => "Klang",
    "1734793" => "Jenjarum",
    "1734798" => "Semenyih",
    "1735148" => "Serendah",
    "1735150" => "Rawang",
    "1735158" => "Petaling Jaya",
    "1735195" => "Sabak Bernam",
    "1735199" => "Sungai Besar",
    "1741562" => "Tanjung Sepat",
    "1750974" => "Ladang Seri Kundang",
    "1759486" => "Kuang",
    "1763412" => "Kampung Tanjung Karang",
    "1771023" => "Kampung Baru Subang",
    "1771304" => "Kampong Baharu Balakong",
    "8504423" => "Subang Jaya",
  );
}


function location_cities_list_my_11() {
  return array(
    "1732945" => "Cukai",
    "1734313" => "Paka",
    "1734316" => "Kertih",
    "1734705" => "Kuala Terengganu",
    "1734715" => "Marang",
  );
}
