<?php


function location_cities_list_eg_alx() {
  return array(
    "361058" => "Alexandria",
  );
}


function location_cities_list_eg_suz() {
  return array(
    "359796"  => "Suez",
    "7521348" => "Ain Sukhna",
  );
}


function location_cities_list_eg_bh() {
  return array(
    "350203" => "Rosetta",
    "353828" => "Kawm Hamadah",
    "354775" => "Kafr ad Dawwar",
    "355628" => "Idku",
    "356000" => "Hawsh `Isa",
    "358448" => "Damanhur",
    "361827" => "Ad Dilinjat",
    "362882" => "Abu al Matamir",
  );
}


function location_cities_list_eg_shr() {
  return array(
    "352679" => "Mashtul as Suq",
    "354105" => "Kafr Saqr",
    "355939" => "Hihya",
    "356989" => "Faqus",
    "358095" => "Diyarb Najm",
    "358840" => "Bilbays",
    "359493" => "Zagazig",
    "360542" => "Al Qurayn",
    "360612" => "Al Qanayat",
    "361103" => "Al Ibrahimiyah",
    "362485" => "Abu Kabir",
  );
}


function location_cities_list_eg_is() {
  return array(
    "359710" => "At Tall al Kabir",
    "361055" => "Ismailia",
  );
}


function location_cities_list_eg_kfs() {
  return array(
    "348112" => "Sidi Salim",
    "354502" => "Kafr ash Shaykh",
    "356806" => "Fuwah",
    "358108" => "Disuq",
    "361213" => "Al Hamul",
  );
}


function location_cities_list_eg_asn() {
  return array(
    "353802" => "Kawm Umbu",
    "359792" => "Aswan",
    "411165" => "Idfu",
  );
}


function location_cities_list_eg_ast() {
  return array(
    "352913" => "Manfalut",
    "358269" => "Dayrut",
    "359783" => "Asyut",
    "360526" => "Al Qusiyah",
    "361478" => "Al Badari",
    "362004" => "Abu Tij",
    "362973" => "Abnub",
  );
}


function location_cities_list_eg_bns() {
  return array(
    "347749" => "Sumusta as Sultani",
    "358600" => "Bush",
    "359173" => "Bani Suwayf",
    "361329" => "Al Fashn",
  );
}


function location_cities_list_eg_pts() {
  return array(
    "358619" => "Port Said",
  );
}


function location_cities_list_eg_dt() {
  return array(
    "356945" => "Faraskur",
    "358048" => "Damietta",
    "419435" => "Az Zarqa",
  );
}


function location_cities_list_eg_js() {
  return array();
}


function location_cities_list_eg_mt() {
  return array(
    "352733" => "Marsa Matruh",
  );
}


function location_cities_list_eg_kn() {
  return array(
    "350422" => "Kousa",
    "350550" => "Qina",
    "351434" => "Naj` Hammadi",
    "355449" => "Isna",
    "356933" => "Farshut",
    "358115" => "Dishna",
  );
}


function location_cities_list_eg_sin() {
  return array(
    "361546" => "Arish",
  );
}


function location_cities_list_eg_shg() {
  return array(
    "347634" => "Tahta",
    "347796" => "Suhaj",
    "354981" => "Juhaynah",
    "355026" => "Jirja",
    "360773" => "Al Manshah",
    "361435" => "Al Balyana",
    "361661" => "Akhmim",
  );
}


function location_cities_list_eg_dk() {
  return array(
    "347591" => "Talkha",
    "349114" => "Shirbin",
    "352344" => "Minyat an Nasr",
    "355392" => "`Izbat al Burj",
    "358172" => "Dikirnis",
    "358821" => "Bilqas",
    "360716" => "Al Matariyah",
    "360754" => "Al Manzilah",
    "360761" => "Al Mansurah",
    "361029" => "Al Jamaliyah",
    "361702" => "Aja",
  );
}


function location_cities_list_eg_ba() {
  return array(
    "358620" => "Bur Safajah",
    "360531" => "Al Qusayr",
    "361291" => "Al Ghardaqah",
  );
}


function location_cities_list_eg_fym() {
  return array(
    "347542" => "Tamiyah",
    "355420" => "Itsa",
    "355648" => "Ibshaway",
    "360464" => "Al Wasitah",
    "361320" => "Al Fayyum",
  );
}


function location_cities_list_eg_gh() {
  return array(
    "346030" => "Zifta",
    "347497" => "Tanda",
    "349715" => "Samannud",
    "350376" => "Qutur",
    "354365" => "Kafr az Zayyat",
    "358970" => "Basyun",
    "360829" => "Al Mahallah al Kubra",
  );
}


function location_cities_list_eg_gz() {
  return array(
    "353219" => "Madinat Sittah Uktubar",
    "359576" => "Awsim",
    "359900" => "As Saff",
    "360995" => "Al Jizah",
    "361179" => "Al Hawamidiyah",
    "361394" => "Al Bawiti",
    "361495" => "Al `Ayyat",
  );
}


function location_cities_list_eg_mn() {
  return array(
    "349717" => "Samalut",
    "352628" => "Matay",
    "352951" => "Mallawi",
    "358274" => "Dayr Mawas",
    "359212" => "Bani Mazar",
    "360686" => "Al Minya",
    "362277" => "Abu Qurqas",
  );
}


function location_cities_list_eg_mnf() {
  return array(
    "347612" => "Tala",
    "349158" => "Shibin al Kawm",
    "350370" => "Quwaysina",
    "352354" => "Minuf",
    "359953" => "Ash Shuhada'",
    "360048" => "Ashmun",
    "361457" => "Al Bajur",
  );
}


function location_cities_list_eg_kb() {
  return array(
    "347236" => "Toukh",
    "349156" => "Shibin al Qanatir",
    "350789" => "Qalyub",
    "359280" => "Banha",
    "360615" => "Al Qanatir al Khayriyah",
    "360928" => "Al Khankah",
  );
}


function location_cities_list_eg_c() {
  return array(
    "355795" => "Halwan",
    "360630" => "Cairo",
  );
}


function location_cities_list_eg_lx() {
  return array(
    "360502" => "Luxor",
  );
}


function location_cities_list_eg_wad() {
  return array(
    "360923" => "Al Kharijah",
  );
}
