<?php

function location_cities_list_tv_fun () {
	return array (
		"2110394" => t("Funafuti"),
	);
}


function location_cities_list_tv_nmg () {
	return array (
	);
}


function location_cities_list_tv_nma () {
	return array (
	);
}


function location_cities_list_tv_nit () {
	return array (
	);
}


function location_cities_list_tv_nui () {
	return array (
	);
}


function location_cities_list_tv_nkf () {
	return array (
	);
}


function location_cities_list_tv_nkl () {
	return array (
	);
}


function location_cities_list_tv_vai () {
	return array (
	);
}
