<?php


function location_cities_list_ma_09() {
  return array(
    "2537406" => t("Settat"),
    "2540689" => t("Oued Zem"),
    "2544248" => t("Khouribga"),
    "2553751" => t("Bouznika"),
    "2556272" => t("Berrechid"),
    "6546693" => t("Boujniba"),
  );
}


function location_cities_list_ma_10() {
  return array(
    "2526488" => t("Youssoufia"),
    "2536074" => t("Sidi Bennour"),
    "2537881" => t("Safi"),
    "2550078" => t("El Jadida"),
    "2556657" => t("Azemmour"),
  );
}


function location_cities_list_ma_02() {
  return array(
    "2532394" => t("Souq Larb'a al Gharb"),
    "2532822" => t("Sidi Yahia el Gharb"),
    "2532945" => t("Sidi Slimane"),
    "2533191" => t("Sidi Qacem"),
    "2540810" => t("Ouazzane"),
    "2542866" => t("Mechra Belqsiri"),
    "2544571" => t("Kenitra"),
  );
}


function location_cities_list_ma_14() {
  return array(
    "2530241" => t("Tan-Tan"),
    "2548526" => t("Guelmim"),
  );
}


function location_cities_list_ma_15() {
  return array();
}


function location_cities_list_ma_11() {
  return array(
    "2542997" => t("Marrakesh"),
    "2549263" => t("Essaouira"),
  );
}


function location_cities_list_ma_04() {
  return array(
    "2526435" => t("Zaio"),
    "2530048" => t("Taourirt"),
    "2540483" => t("Oujda"),
    "2541479" => t("Nador"),
    "2545017" => t("Jerada"),
    "2550806" => t("El Aioun"),
    "2555467" => t("Berkane"),
    "2561124" => t("Ahfir"),
  );
}


function location_cities_list_ma_eh() {
  return array(
    "8542188" => t("Dakhla"),
  );
}


function location_cities_list_ma_05() {
  return array(
    "2537545" => t("Sefrou"),
    "2548885" => t("Fes"),
  );
}


function location_cities_list_ma_06() {
  return array(
    "2542227" => t("Midelt"),
    "2542715" => t("Meknes"),
    "2544333" => t("Khenifra"),
    "2550252" => t("El Hajeb"),
    "2556464" => t("Azrou"),
  );
}


function location_cities_list_ma_07() {
  return array(
    "2528659" => t("Tiflet"),
    "2537763" => t("Sale"),
    "2538475" => t("Rabat"),
    "2558470" => t("Khemisset"),
    "2562055" => t("Skhirat"),
  );
}


function location_cities_list_ma_13() {
  return array(
    "2526452" => t("Zagora"),
    "2527089" => t("Tiznit"),
    "2527915" => t("Tineghir"),
    "2529649" => t("Taroudant"),
    "2534515" => t("Sidi Ifni"),
    "2539134" => t("Oulad Teima"),
    "2540850" => t("Ouarzazat"),
    "2561668" => t("Agadir"),
  );
}


function location_cities_list_ma_01() {
  return array(
    "2528910" => t("Tetouan"),
    "2530335" => t("Tangier"),
    "2542987" => t("Martil"),
    "2543549" => t("Larache"),
    "2544001" => t("Ksar el Kebir"),
    "2553455" => t("Chefchaouene"),
    "2557055" => t("Asilah"),
  );
}


function location_cities_list_ma_08() {
  return array(
    "2542051" => t("Mohammedia"),
    "2553604" => t("Casablanca"),
  );
}


function location_cities_list_ma_12() {
  return array(
    "2544720" => t("Kasba Tadla"),
    "2548830" => t("Fkih Ben Salah"),
    "2555745" => t("Beni Mellal"),
  );
}


function location_cities_list_ma_03() {
  return array(
    "2527645" => t("Tirhanimine"),
    "2529317" => t("Taza"),
    "2530155" => t("Taounate"),
    "2531480" => t("Tahala"),
    "2545985" => t("Imzourene"),
    "2548489" => t("Guercif"),
    "2558545" => t("Al Hoceima"),
  );
}
