<?php

function location_cities_list_cm_ce () {
	return array (
		"2235776" => t("Akonolinga"),
		"2235194" => t("Bafia"),
		"2231881" => t("Eseka"),
		"2228079" => t("Mbalmayo"),
		"2228028" => t("Mbandjok"),
		"2225457" => t("Nanga Eboko"),
		"2223734" => t("Nkoteng"),
		"2223293" => t("Obala"),
		"2220957" => t("Yaounde"),
	);
}


function location_cities_list_cm_en () {
	return array (
		"2233805" => t("Bogo"),
		"2230599" => t("Kaele"),
		"2229798" => t("Kousseri"),
		"2228373" => t("Maroua"),
		"2226275" => t("Mokolo"),
		"2225991" => t("Mora"),
		"2221030" => t("Yagoua"),
	);
}


function location_cities_list_cm_nw () {
	return array (
		"2235029" => t("Bali"),
		"2234974" => t("Bamenda"),
		"2231482" => t("Fundong"),
		"2229748" => t("Kumbo"),
		"2221053" => t("Wum"),
	);
}


function location_cities_list_cm_ou () {
	return array (
		"2235196" => t("Bafang"),
		"2235189" => t("Bafoussam"),
		"2234865" => t("Bangangte"),
		"2232444" => t("Dschang"),
		"2231506" => t("Foumban"),
		"2231504" => t("Foumbot"),
		"2227613" => t("Mbouda"),
		"2221394" => t("Tonga"),
	);
}


function location_cities_list_cm_sw () {
	return array (
		"2234941" => t("Bamusso"),
		"2233410" => t("Buea"),
		"2231564" => t("Fontem"),
		"2594800" => t("Idenao"),
		"2229752" => t("Kumba"),
		"2229411" => t("Limbe"),
		"2228675" => t("Mamfe"),
		"2225728" => t("Mutengene"),
		"2225726" => t("Muyuka"),
		"2221504" => t("Tiko"),
	);
}


function location_cities_list_cm_ad () {
	return array (
		"2234794" => t("Banyo"),
		"2227402" => t("Meiganga"),
		"2224827" => t("Ngaoundere"),
		"2221530" => t("Tibati"),
	);
}


function location_cities_list_cm_no () {
	return array (
		"2231320" => t("Garoua"),
		"2230876" => t("Guider"),
		"2229681" => t("Lagdo"),
		"2221607" => t("Tchollire"),
	);
}


function location_cities_list_cm_su () {
	return array (
		"2232283" => t("Ebolowa"),
		"2229761" => t("Kribi"),
		"2229267" => t("Lolodorf"),
		"2222230" => t("Sangmelima"),
	);
}


function location_cities_list_cm_lt () {
	return array (
		"2232997" => t("Dizangue"),
		"2232593" => t("Douala"),
		"2232239" => t("Edea"),
		"2229152" => t("Loum"),
		"2228499" => t("Manjo"),
		"2228005" => t("Mbanga"),
		"2227230" => t("Melong"),
		"2223763" => t("Nkongsamba"),
		"2222623" => t("Penja"),
	);
}


function location_cities_list_cm_es () {
	return array (
		"2234663" => t("Batouri"),
		"2234536" => t("Belabo"),
		"2234359" => t("Bertoua"),
		"2231319" => t("Garoua Boulai"),
	);
}


