<?php

function location_cities_list_ve_y () {
	return array (
		"3625929" => t("Tucupita"),
	);
}


function location_cities_list_ve_w () {
	return array (
	);
}


function location_cities_list_ve_a () {
	return array (
		"3646738" => t("Caracas"),
	);
}


function location_cities_list_ve_z () {
	return array (
		"3629710" => t("Puerto Ayacucho"),
	);
}


function location_cities_list_ve_b () {
	return array (
		"3486270" => t("Anaco"),
		"3628142" => t("San Jose de Guanipa"),
		"3629672" => t("Puerto La Cruz"),
		"3641351" => t("El Tigre"),
		"3646869" => t("Cantaura"),
		"3648559" => t("Barcelona"),
	);
}


function location_cities_list_ve_c () {
	return array (
		"3804949" => t("Guasdualito"),
		"3805673" => t("San Fernando Apure"),
	);
}


function location_cities_list_ve_d () {
	return array (
		"3625341" => t("Villa de Cura"),
		"3625829" => t("Turmero"),
		"3627968" => t("San Mateo"),
		"3630932" => t("Palo Negro"),
		"3632998" => t("Maracay"),
		"3634922" => t("La Victoria"),
		"3635325" => t("Las Tejerias"),
		"3642833" => t("El Limon"),
		"3647549" => t("Cagua"),
	);
}


function location_cities_list_ve_e () {
	return array (
		"3487903" => t("Alto Barinas"),
		"3648540" => t("Barinitas"),
		"3648546" => t("Barinas"),
	);
}


function location_cities_list_ve_f () {
	return array (
		"3625710" => t("Upata"),
		"3627382" => t("Santa Elena de Uairen"),
		"3645528" => t("Ciudad Guayana"),
		"3645532" => t("Ciudad Bolivar"),
	);
}


function location_cities_list_ve_g () {
	return array (
		"3625549" => t("Valencia"),
		"3628267" => t("San Joaquin"),
		"3629706" => t("Puerto Cabello"),
		"3631878" => t("Moron"),
		"3632929" => t("Mariara"),
		"3639747" => t("Guigue"),
		"3640465" => t("Guacara"),
		"3646062" => t("Tacarigua"),
	);
}


function location_cities_list_ve_h () {
	return array (
		"3626219" => t("Tinaquillo"),
		"3628503" => t("San Carlos"),
	);
}


function location_cities_list_ve_i () {
	return array (
		"3629576" => t("Punto Fijo"),
		"3629614" => t("Punta Cardon"),
		"3645213" => t("Coro"),
	);
}


function location_cities_list_ve_j () {
	return array (
		"3625066" => t("Zaraza"),
		"3625515" => t("Valle de La Pascua"),
		"3628053" => t("San Juan de los Morros"),
		"3647444" => t("Calabozo"),
		"3649408" => t("Altagracia de Orituco"),
	);
}


function location_cities_list_ve_k () {
	return array (
		"3629419" => t("Quibor"),
		"3633677" => t("Los Rastrojos"),
		"3641275" => t("El Tocuyo"),
		"3646487" => t("Carora"),
		"3648522" => t("Barquisimeto"),
	);
}


function location_cities_list_ve_m () {
	return array (
		"3627047" => t("Santa Teresa"),
		"3628550" => t("San Antonio de Los Altos"),
		"3630297" => t("Petare"),
		"3631412" => t("Ocumare del Tuy"),
		"3633622" => t("Los Teques"),
		"3634184" => t("Los Dos Caminos"),
		"3639898" => t("Guatire"),
		"3640049" => t("Guarenas"),
		"3643031" => t("El Hatillo"),
		"3644918" => t("Cua"),
		"3645854" => t("Charallave"),
		"3645981" => t("Chacao"),
		"3646169" => t("Caucaguito"),
		"3646451" => t("Carrizal"),
		"3648439" => t("Baruta"),
		"3803449" => t("El Cafetal"),
		"3803515" => t("Caucaguita"),
		"3803651" => t("La Dolorita"),
	);
}


function location_cities_list_ve_n () {
	return array (
		"3778045" => t("Maturin"),
	);
}


function location_cities_list_ve_l () {
	return array (
		"3631741" => t("Mucumpiz"),
		"3632308" => t("Merida"),
		"3641099" => t("El Vigia"),
		"3644417" => t("Ejido"),
	);
}


function location_cities_list_ve_o () {
	return array (
		"3480908" => t("La Asuncion"),
		"3629965" => t("Porlamar"),
		"3639107" => t("Juan Griego"),
	);
}


function location_cities_list_ve_p () {
	return array (
		"3625346" => t("Villa Bruzual"),
		"3640226" => t("Guanare"),
		"3649017" => t("Araure"),
		"3649833" => t("Acarigua"),
	);
}


function location_cities_list_ve_s () {
	return array (
		"3626402" => t("Tariba"),
		"3628060" => t("San Juan de Colon"),
		"3628473" => t("San Cristobal"),
		"3628549" => t("San Antonio del Tachira"),
		"3628952" => t("Rubio"),
		"3795152" => t("La Fria"),
	);
}


function location_cities_list_ve_u () {
	return array (
		"3625207" => t("Yaritagua"),
		"3628423" => t("San Felipe"),
		"3631507" => t("Nirgua"),
		"3645671" => t("Chivacoa"),
	);
}


function location_cities_list_ve_v () {
	return array (
		"3627186" => t("Santa Rita"),
		"3628489" => t("San Carlos del Zulia"),
		"3628966" => t("La Villa del Rosario"),
		"3633009" => t("Maracaibo"),
		"3633444" => t("Machiques"),
		"3637623" => t("Lagunillas"),
		"3647651" => t("Cabimas"),
	);
}


function location_cities_list_ve_r () {
	return array (
		"3639725" => t("Gueiria"),
		"3644768" => t("Cumana"),
		"3646382" => t("Carupano"),
	);
}


function location_cities_list_ve_t () {
	return array (
		"3625542" => t("Valera"),
		"3625979" => t("Trujillo"),
	);
}


function location_cities_list_ve_x () {
	return array (
		"3633341" => t("Maiquetia"),
		"3637721" => t("La Guaira"),
		"3646190" => t("Catia La Mar"),
		"3646767" => t("Caraballeda"),
	);
}
