<?php

function location_cities_list_za_fs () {
	return array (
		"940424" => t("Wesselsbron"),
		"940909" => t("Welkom"),
		"943882" => t("Virginia"),
		"943960" => t("Viljoenskroon"),
		"949282" => t("Theunissen"),
		"949703" => t("Thaba Nchu"),
		"956507" => t("Senekal"),
		"957487" => t("Sasolburg"),
		"962847" => t("Reitz"),
		"965401" => t("Phuthaditjhaba"),
		"966166" => t("Parys"),
		"985015" => t("Ladybrand"),
		"986083" => t("Kutloanong"),
		"986846" => t("Kroonstad"),
		"996918" => t("Hennenman"),
		"997140" => t("Heilbron"),
		"997751" => t("Harrismith"),
		"1016670" => t("Botshabelo"),
		"1016698" => t("Bothaville"),
		"1018725" => t("Bloemfontein"),
		"1019704" => t("Bethlehem"),
		"1023287" => t("Allanridge"),
	);
}


function location_cities_list_za_gp () {
	return array (
		"936374" => t("Roodepoort"),
		"940316" => t("Westonaria"),
		"944385" => t("Vereeniging"),
		"944986" => t("Vanderbijlpark"),
		"949880" => t("Tembisa"),
		"952865" => t("Springs"),
		"953781" => t("Soweto"),
		"963230" => t("Randfontein"),
		"964137" => t("Pretoria"),
		"970566" => t("Nigel"),
		"980921" => t("Mabopane"),
		"986822" => t("Krugersdorp"),
		"993800" => t("Johannesburg"),
		"997151" => t("Heidelberg"),
		"1012413" => t("Cullinan"),
		"1014073" => t("Carletonville"),
		"1015504" => t("Bronkhorstspruit"),
		"1016181" => t("Brakpan"),
		"1017780" => t("Boksburg"),
		"1020098" => t("Benoni"),
		"1105726" => t("Ekangala"),
		"1105776" => t("Midrand"),
		"1105777" => t("Centurion"),
	);
}


function location_cities_list_za_zn () {
	return array (
		"942470" => t("Vryheid"),
		"946128" => t("Umkomaas"),
		"946257" => t("Ulundi"),
		"952734" => t("Stanger"),
		"956878" => t("Scottburgh"),
		"962330" => t("Richmond"),
		"962367" => t("Richards Bay"),
		"964406" => t("Port Shepstone"),
		"965301" => t("Pietermaritzburg"),
		"971421" => t("Newcastle"),
		"973111" => t("Mpumalanga"),
		"973139" => t("Mpophomeni"),
		"974670" => t("Mondlo"),
		"978895" => t("Margate"),
		"988356" => t("Kokstad"),
		"995202" => t("Howick"),
		"1005029" => t("eSikhawini"),
		"1005544" => t("Empangeni"),
		"1007311" => t("Durban"),
		"1007400" => t("Dundee"),
		"1021360" => t("Ballitoville"),
	);
}


function location_cities_list_za_lp () {
	return array (
		"941966" => t("Warmbaths"),
		"946973" => t("Tzaneen"),
		"949224" => t("Thohoyandou"),
		"964315" => t("Mokopane"),
		"965289" => t("Polokwane"),
		"965528" => t("Phalaborwa"),
		"968665" => t("Modimolle"),
		"970341" => t("Nkowakowa"),
		"976885" => t("Messina"),
		"981827" => t("Louis Trichardt"),
		"984087" => t("Lebowakgomo"),
		"1001860" => t("Giyani"),
		"1005768" => t("Ellisras"),
		"1007514" => t("Duiwelskloof"),
	);
}


function location_cities_list_za_mp () {
	return array (
		"938694" => t("White River"),
		"939270" => t("Witbank"),
		"943032" => t("Volksrust"),
		"952747" => t("Standerton"),
		"955313" => t("Siyabuswa"),
		"956767" => t("Secunda"),
		"965241" => t("Piet Retief"),
		"971534" => t("Nelspruit"),
		"976361" => t("Middelburg"),
		"981158" => t("Lydenburg"),
		"987202" => t("Kriel"),
		"988290" => t("Komatipoort"),
		"996930" => t("Hendrina"),
		"1005125" => t("Ermelo"),
		"1005646" => t("eMbalenhle"),
		"1008261" => t("Driefontein"),
		"1011031" => t("Delmas"),
		"1019760" => t("Bethal"),
		"1021086" => t("Barberton"),
		"1021396" => t("Balfour"),
	);
}


function location_cities_list_za_nc () {
	return array (
		"941931" => t("Warrenton"),
		"945945" => t("Upington"),
		"990930" => t("Kimberley"),
		"1011632" => t("De Aar"),
	);
}


function location_cities_list_za_ec () {
	return array (
		"946058" => t("Mthatha"),
		"946877" => t("Uitenhage"),
		"951650" => t("Stutterheim"),
		"954161" => t("Somerset East"),
		"963516" => t("Queenstown"),
		"963525" => t("Queensdale"),
		"964420" => t("Port Elizabeth"),
		"964432" => t("Port Alfred"),
		"976358" => t("Middelburg"),
		"985011" => t("Lady Frere"),
		"986717" => t("Kruisfontein"),
		"1000501" => t("Grahamstown"),
		"1000543" => t("Graaff-Reinet"),
		"1003953" => t("Fort Beaufort"),
		"1006984" => t("East London"),
		"1012600" => t("Cradock"),
		"1014489" => t("Butterworth"),
		"1019330" => t("Bhisho"),
		"1023309" => t("Aliwal North"),
	);
}


function location_cities_list_za_nw () {
	return array (
		"937136" => t("Zeerust"),
		"938457" => t("Wolmaransstad"),
		"942511" => t("Vryburg"),
		"952192" => t("Stilfontein"),
		"956907" => t("Schweizer-Reneke"),
		"958724" => t("Rustenburg"),
		"964349" => t("Potchefstroom"),
		"966380" => t("Pampierstad"),
		"967476" => t("Orkney"),
		"975436" => t("Mmabatho"),
		"982899" => t("Lichtenburg"),
		"989921" => t("Klerksdorp"),
		"1002851" => t("Ga-Rankuwa"),
		"1004109" => t("Fochville"),
		"1013550" => t("Christiana"),
		"1015621" => t("Brits"),
		"1018673" => t("Bloemhof"),
	);
}


function location_cities_list_za_wc () {
	return array (
		"964712" => t("Plettenberg Bay"),
		"967106" => t("Oudtshoorn"),
		"973709" => t("Mossel Bay"),
		"988698" => t("Knysna"),
		"1002145" => t("George"),
		"1020641" => t("Beaufort West"),
		"3359041" => t("Worcester"),
		"3361025" => t("Stellenbosch"),
		"3361934" => t("Saldanha"),
		"3363613" => t("Noorder-Paarl"),
		"3364346" => t("Malmesbury"),
		"3366880" => t("Hermanus"),
		"3367513" => t("Grabouw"),
		"3369129" => t("Ceres"),
		"3369157" => t("Cape Town"),
		"3370352" => t("Atlantis"),
	);
}
