<?php

function location_cities_list_ss_ec () {
	return array (
		"373303" => t("Juba"),
		"363619" => t("Yei"),
	);
}


function location_cities_list_ss_ew () {
	return array (
		"363656" => t("Yambio"),
	);
}


function location_cities_list_ss_bw () {
	return array (
		"363885" => t("Wau"),
	);
}


function location_cities_list_ss_bn () {
	return array (
		"364367" => t("Aweil"),
	);
}


function location_cities_list_ss_ee () {
	return array (
		"375495" => t("Pajok"),
		"365742" => t("Torit"),
	);
}


function location_cities_list_ss_wr () {
	return array (
		"374739" => t("Gogrial"),
		"365763" => t("Tonj"),
	);
}


function location_cities_list_ss_lk () {
	return array (
		"367927" => t("Rumbek"),
	);
}


function location_cities_list_ss_nu () {
	return array (
		"370737" => t("Malakal"),
	);
}


function location_cities_list_ss_jg () {
	return array (
		"377241" => t("Bor"),
	);
}


