<?php


function location_cities_list_ec_b() {
  return array(
    "3657571" => t("Guaranda"),
  );
}


function location_cities_list_ec_x() {
  return array(
    "3652684" => t("Pujili"),
    "3654870" => t("Latacunga"),
    "3655117" => t("La Mana"),
  );
}


function location_cities_list_ec_o() {
  return array(
    "3651356" => t("Santa Rosa"),
    "3653130" => t("Pinas"),
    "3653403" => t("Pasaje"),
    "3654533" => t("Machala"),
    "3655720" => t("Huaquillas"),
  );
}


function location_cities_list_ec_e() {
  return array(
    "3651694" => t("San Lorenzo de Esmeraldas"),
    "3652257" => t("Rosa Zarate"),
    "3657990" => t("Esmeraldas"),
  );
}


function location_cities_list_ec_d() {
  return array(
    "3652743" => t("Puerto Francisco de Orellana"),
    "3660152" => t("Boca Suno"),
  );
}


function location_cities_list_ec_w() {
  return array();
}


function location_cities_list_ec_i() {
  return array(
    "3653693" => t("Otavalo"),
    "3655673" => t("Ibarra"),
    "3660478" => t("Atuntaqui"),
  );
}


function location_cities_list_ec_l() {
  return array(
    "3654667" => t("Loja"),
    "3659599" => t("Catamayo"),
    "3659711" => t("Cariamanga"),
  );
}


function location_cities_list_ec_r() {
  return array(
    "3650186" => t("Vinces"),
    "3650267" => t("Ventanas"),
    "3652567" => t("Quevedo"),
    "3654064" => t("Montalvo"),
    "3660418" => t("Babahoyo"),
  );
}


function location_cities_list_ec_m() {
  return array(
    "3650960" => t("Sucre"),
    "3652941" => t("Portoviejo"),
    "3654055" => t("Montecristi"),
    "3654410" => t("Manta"),
    "3655446" => t("Jipijapa"),
    "3659139" => t("Chone"),
    "3659926" => t("Calceta"),
    "3660401" => t("Bahia de Caraquez"),
  );
}


function location_cities_list_ec_s() {
  return array(
    "3654541" => t("Macas"),
  );
}


function location_cities_list_ec_n() {
  return array(
    "3650721" => t("Tena"),
  );
}


function location_cities_list_ec_p() {
  return array(
    "3652462" => t("Quito"),
    "3654536" => t("Machachi"),
    "3659578" => t("Cayambe"),
  );
}


function location_cities_list_ec_se() {
  return array(
    "3651438" => t("Santa Elena"),
  );
}


function location_cities_list_ec_sd() {
  return array(
    "3651297" => t("Santo Domingo de los Colorados"),
  );
}


function location_cities_list_ec_u() {
  return array(
    "3655185" => t("Nueva Loja"),
  );
}


function location_cities_list_ec_z() {
  return array(
    "3649959" => t("Zamora"),
  );
}


function location_cities_list_ec_a() {
  return array(
    "3657670" => t("Gualaceo"),
    "3658666" => t("Cuenca"),
  );
}


function location_cities_list_ec_c() {
  return array(
    "3650472" => t("Tulcan"),
    "3651868" => t("San Gabriel"),
  );
}


function location_cities_list_ec_f() {
  return array(
    "3654853" => t("La Troncal"),
    "3660434" => t("Azogues"),
  );
}


function location_cities_list_ec_h() {
  return array(
    "3652350" => t("Riobamba"),
  );
}


function location_cities_list_ec_g() {
  return array(
    "3650121" => t("Yaguachi Nuevo"),
    "3650273" => t("Velasco Ibarra"),
    "3652065" => t("Samborondon"),
    "3652100" => t("Salinas"),
    "3653015" => t("Playas"),
    "3653295" => t("Pedro Carbo"),
    "3653873" => t("Naranjito"),
    "3653882" => t("Naranjal"),
    "3655131" => t("La Libertad"),
    "3657509" => t("Guayaquil"),
    "3658053" => t("El Triunfo"),
    "3658192" => t("Eloy Alfaro"),
    "3660361" => t("Balzar"),
  );
}


function location_cities_list_ec_y() {
  return array(
    "3652584" => t("Puyo"),
  );
}


function location_cities_list_ec_t() {
  return array(
    "3653287" => t("Pelileo"),
    "3660689" => t("Ambato"),
  );
}
