<?php


function location_cities_list_do_01() {
  return array(
    "3491941" => "Villa Francisca",
    "3491946" => "Villa Consuelo",
    "3492908" => "Santo Domingo",
    "3509578" => "Ciudad Nueva",
    "3511550" => "Bella Vista",
  );
}


function location_cities_list_do_06() {
  return array(
    "3493146" => "San Francisco de Macoris",
  );
}


function location_cities_list_do_09() {
  return array(
    "3496331" => "Moca",
  );
}


function location_cities_list_do_14() {
  return array(
    "3496021" => "Nagua",
  );
}


function location_cities_list_do_24() {
  return array(
    "3509207" => "Cotui",
  );
}


function location_cities_list_do_02() {
  return array(
    "3512208" => "Azua de Compostela",
  );
}


function location_cities_list_do_03() {
  return array(
    "3495857" => "Neiba",
  );
}


function location_cities_list_do_04() {
  return array(
    "3492985" => "Santa Cruz de Barahona",
  );
}


function location_cities_list_do_05() {
  return array(
    "3508952" => "Dajabon",
  );
}


function location_cities_list_do_08() {
  return array(
    "3492984" => "Santa Cruz de El Seibo",
  );
}


function location_cities_list_do_07() {
  return array();
}


function location_cities_list_do_30() {
  return array(
    "3504765" => "Hato Mayor del Rey",
  );
}


function location_cities_list_do_19() {
  return array(
    "3493283" => "Salcedo",
  );
}


function location_cities_list_do_10() {
  return array();
}


function location_cities_list_do_11() {
  return array(
    "3493240" => "Salvaleon de Higuey",
  );
}


function location_cities_list_do_12() {
  return array(
    "3500957" => "La Romana",
  );
}


function location_cities_list_do_13() {
  return array(
    "3504158" => "Jarabacoa",
    "3509363" => "Constanza",
    "3509382" => "Concepcion de La Vega",
  );
}


function location_cities_list_do_28() {
  return array(
    "3511233" => "Bonao",
  );
}


function location_cities_list_do_15() {
  return array(
    "3493174" => "San Fernando de Monte Cristi",
  );
}


function location_cities_list_do_29() {
  return array(
    "3493482" => "Sabana Grande de Boya",
    "3496134" => "Monte Plata",
    "3511626" => "Bayaguana",
  );
}


function location_cities_list_do_16() {
  return array();
}


function location_cities_list_do_17() {
  return array(
    "3512067" => "Bani",
  );
}


function location_cities_list_do_20() {
  return array();
}


function location_cities_list_do_21() {
  return array(
    "3491952" => "Villa Altagracia",
    "3511540" => "San Cristobal",
    "3512128" => "Bajos de Haina",
  );
}


function location_cities_list_do_36() {
  return array(
    "3493100" => "San Jose de Ocoa",
  );
}


function location_cities_list_do_22() {
  return array(
    "3493081" => "San Juan de la Maguana",
    "3494242" => "Punta Cana",
    "3500370" => "Las Matas de Farfan",
  );
}


function location_cities_list_do_23() {
  return array(
    "3493032" => "San Pedro de Macoris",
    "3494121" => "Quisqueya",
  );
}


function location_cities_list_do_25() {
  return array(
    "3491948" => "Villa Bisono",
    "3492517" => "Tamboril",
    "3492914" => "Santiago de los Caballeros",
  );
}


function location_cities_list_do_26() {
  return array(
    "3493383" => "Sabaneta",
  );
}


function location_cities_list_do_37() {
  return array(
    "3511336" => "Boca Chica",
    "7874116" => "Santo Domingo Oeste",
  );
}


function location_cities_list_do_27() {
  return array(
    "3496831" => "Mao",
    "3505855" => "Esperanza",
  );
}


function location_cities_list_do_18() {
  return array(
    "3493175" => "Puerto Plata",
    "3493769" => "Rio Grande",
  );
}
