<?php


function location_cities_list_co_atl () {
	return array (
		"3667849" => t("Soledad"),
		"3668332" => t("Santo Tomas"),
		"3668655" => t("Santa Lucia"),
		"3670502" => t("Sabanalarga"),
		"3670513" => t("Sabanagrande"),
		"3670874" => t("Repelon"),
		"3671497" => t("Puerto Colombia"),
		"3673220" => t("Palmar de Varela"),
		"3675595" => t("Malambo"),
		"3682238" => t("Galapa"),
		"3687758" => t("Campo de la Cruz"),
		"3689147" => t("Barranquilla"),
		"3689235" => t("Baranoa"),
	);
}


function location_cities_list_co_dc () {
	return array (
		"3688689" => t("Bogota"),
	);
}


function location_cities_list_co_cun () {
	return array (
		"3665542" => t("Zipaquira"),
		"3665895" => t("Villeta"),
		"3666519" => t("Ubate"),
		"3667905" => t("Soacha"),
		"3668087" => t("Sibate"),
		"3673424" => t("Pacho"),
		"3674292" => t("Mosquera"),
		"3675707" => t("Madrid"),
		"3678405" => t("La Mesa"),
		"3682028" => t("Girardot"),
		"3682274" => t("Fusagasuga"),
		"3682281" => t("Funza"),
		"3682516" => t("Facatativa"),
		"3686675" => t("Chia"),
		"3688006" => t("Cajica"),
	);
}


function location_cities_list_co_ant () {
	return array (
		"3665566" => t("Zaragoza"),
		"3665741" => t("Yarumal"),
		"3666395" => t("Urrao"),
		"3666570" => t("Turbo"),
		"3667820" => t("Sonson"),
		"3668175" => t("Segovia"),
		"3668323" => t("Santuario"),
		"3669998" => t("San Carlos"),
		"3670475" => t("Sabaneta"),
		"3670730" => t("Rionegro"),
		"3671540" => t("Puerto Berrio"),
		"3674962" => t("Medellin"),
		"3675263" => t("Marinilla"),
		"3679065" => t("La Estrella"),
		"3679554" => t("La Ceja"),
		"3680450" => t("Itagui"),
		"3682631" => t("Envigado"),
		"3684945" => t("El Bagre"),
		"3685949" => t("Municipio de Copacabana"),
		"3686636" => t("Chigorodo"),
		"3687025" => t("Caucasia"),
		"3687318" => t("Carmen de Viboral"),
		"3687952" => t("Caldas"),
		"3688928" => t("Bello"),
		"3689205" => t("Barbosa"),
		"3689798" => t("Apartado"),
		"3689899" => t("Los Andes"),
		"3792375" => t("Carepa"),
		"3792376" => t("Ciudad Bolivar"),
	);
}


function location_cities_list_co_ara () {
	return array (
		"3667478" => t("Tame"),
		"3689718" => t("Arauca"),
	);
}


function location_cities_list_co_bol () {
	return array (
		"3666577" => t("Turbaco"),
		"3669454" => t("San Juan Nepomuceno"),
		"3669736" => t("San Jacinto"),
		"3674412" => t("Morales"),
		"3674597" => t("Mompos"),
		"3675287" => t("Maria la Baja"),
		"3675692" => t("Magangue"),
		"3684666" => t("El Carmen de Bolivar"),
		"3687238" => t("Cartagena"),
		"3689570" => t("Arjona"),
	);
}


function location_cities_list_co_boy () {
	return array (
		"3666608" => t("Tunja"),
		"3667873" => t("Sogamoso"),
		"3671531" => t("Puerto Boyaca"),
		"3685084" => t("Duitama"),
		"3686513" => t("Chiquinquira"),
	);
}


function location_cities_list_co_cal () {
	return array (
		"3665851" => t("Viterbo"),
		"3665973" => t("Villamaria"),
		"3670370" => t("Salamina"),
		"3670719" => t("Riosucio"),
		"3675409" => t("Manzanares"),
		"3675443" => t("Manizales"),
		"3679277" => t("La Dorada"),
		"3686561" => t("Chinchina"),
		"3690431" => t("Aguadas"),
	);
}


function location_cities_list_co_cas () {
	return array (
		"3665688" => t("Yopal"),
		"3665951" => t("Villanueva"),
		"3690316" => t("Aguazul"),
	);
}


function location_cities_list_co_cor () {
	return array (
		"3667158" => t("Tierralta"),
		"3669997" => t("San Carlos"),
		"3670419" => t("Sahagun"),
		"3672068" => t("Planeta Rica"),
		"3674453" => t("Monteria"),
		"3674470" => t("Montelibano"),
		"3676397" => t("Lorica"),
		"3686272" => t("Cienaga de Oro"),
		"3686540" => t("Chinu"),
		"3686922" => t("Cerete"),
		"3689381" => t("Ayapel"),
	);
}


function location_cities_list_co_lag () {
	return array (
		"3665934" => t("Villanueva"),
		"3669469" => t("San Juan del Cesar"),
		"3670745" => t("Riohacha"),
		"3675657" => t("Maicao"),
		"3682374" => t("Fonseca"),
		"3689162" => t("Barrancas"),
	);
}


function location_cities_list_co_nar () {
	return array (
		"3666582" => t("Tuquerres"),
		"3666640" => t("Tumaco"),
		"3672778" => t("Pasto"),
		"3676934" => t("La Union"),
		"3680539" => t("Ipiales"),
		"3684579" => t("El Charco"),
	);
}


function location_cities_list_co_nsa () {
	return array (
		"3665913" => t("Villa del Rosario"),
		"3671325" => t("Puerto Santander"),
		"3673045" => t("Pamplona"),
		"3673662" => t("Ocana"),
		"3675975" => t("Los Patios"),
		"3685533" => t("Cucuta"),
	);
}


function location_cities_list_co_ris () {
	return array (
		"3668454" => t("Santa Rosa de Cabal"),
		"3672486" => t("Pereira"),
		"3676720" => t("La Virginia"),
		"3685095" => t("Dos Quebradas"),
		"3688989" => t("Belen de Umbria"),
		"3689833" => t("Anserma"),
	);
}


function location_cities_list_co_san () {
	return array (
		"3667887" => t("Socorro"),
		"3669808" => t("San Gil"),
		"3672328" => t("Piedecuesta"),
		"3675605" => t("Malaga"),
		"3682018" => t("Giron"),
		"3682385" => t("Floridablanca"),
		"3688465" => t("Bucaramanga"),
		"3689169" => t("Barrancabermeja"),
		"3689206" => t("Barbosa"),
	);
}


function location_cities_list_co_suc () {
	return array (
		"3666939" => t("Tolu"),
		"3667728" => t("Sucre"),
		"3667983" => t("Sincelejo"),
		"3667991" => t("Since"),
		"3669218" => t("San Onofre"),
		"3669346" => t("San Marcos"),
		"3670038" => t("San Benito Abad"),
		"3670280" => t("Sampues"),
		"3685823" => t("Corozal"),
	);
}


function location_cities_list_co_tol () {
	return array (
		"3674885" => t("Melgar"),
		"3675252" => t("Mariquita"),
		"3676604" => t("Libano"),
		"3676626" => t("Lerida"),
		"3680656" => t("Ibague"),
		"3680840" => t("Honda"),
		"3682330" => t("Fresno"),
		"3682458" => t("Flandes"),
		"3682573" => t("Espinal"),
		"3686793" => t("Chaparral"),
	);
}


function location_cities_list_co_ama () {
	return array (
		"3676623" => t("Leticia"),
	);
}


function location_cities_list_co_caq () {
	return array (
		"3682426" => t("Florencia"),
	);
}


function location_cities_list_co_cau () {
	return array (
		"3668572" => t("Santander de Quilichao"),
		"3671315" => t("Puerto Tejada"),
		"3671916" => t("Popayan"),
		"3672761" => t("Patia"),
		"3673398" => t("Belalcazar"),
		"3685871" => t("Corinto"),
		"3770718" => t("Morales"),
	);
}


function location_cities_list_co_ces () {
	return array (
		"3666304" => t("Valledupar"),
		"3678674" => t("La Jagua de Ibirico"),
		"3684452" => t("El Copey"),
		"3685335" => t("Curumani"),
		"3686479" => t("Chiriguana"),
		"3686585" => t("Chimichagua"),
		"3689589" => t("Ariguani"),
		"3690465" => t("Aguachica"),
		"3792383" => t("Agustin Codazzi"),
	);
}


function location_cities_list_co_cho () {
	return array (
		"3671116" => t("Quibdo"),
	);
}


function location_cities_list_co_gua () {
	return array (
	);
}


function location_cities_list_co_guv () {
	return array (
		"3828545" => t("San Jose del Guaviare"),
	);
}


function location_cities_list_co_hui () {
	return array (
		"3672110" => t("Pitalito"),
		"3673899" => t("Neiva"),
		"3678097" => t("La Plata"),
		"3682108" => t("Garzon"),
		"3687806" => t("Campoalegre"),
	);
}


function location_cities_list_co_mag () {
	return array (
		"3668605" => t("Santa Marta"),
		"3672093" => t("Pivijay"),
		"3682292" => t("Fundacion"),
		"3683233" => t("El Reten"),
		"3684917" => t("El Banco"),
		"3686279" => t("Cienaga"),
		"3689759" => t("Aracataca"),
		"3792392" => t("Plato"),
	);
}


function location_cities_list_co_met () {
	return array (
		"3665900" => t("Villavicencio"),
		"3669332" => t("San Martin"),
		"3671418" => t("Puerto Lopez"),
		"3681957" => t("Granada"),
		"3690577" => t("Acacias"),
	);
}


function location_cities_list_co_put () {
	return array (
		"3671549" => t("Puerto Asis"),
		"3674654" => t("Mocoa"),
	);
}


function location_cities_list_co_vac () {
	return array (
		"3665559" => t("Zarzal"),
		"3665657" => t("Yumbo"),
		"3666645" => t("Tulua"),
		"3668132" => t("Sevilla"),
		"3670644" => t("Roldanillo"),
		"3671772" => t("Pradera"),
		"3673164" => t("Palmira"),
		"3676928" => t("La Union"),
		"3680387" => t("Jamundi"),
		"3681797" => t("Guacari"),
		"3682393" => t("Florida"),
		"3684615" => t("El Cerrito"),
		"3687230" => t("Cartago"),
		"3687644" => t("Candelaria"),
		"3687925" => t("Cali"),
		"3688071" => t("Caicedonia"),
		"3688256" => t("Buga"),
		"3688451" => t("Buenaventura"),
		"3688452" => t("Buenaventura"),
		"3689905" => t("Andalucia"),
	);
}


function location_cities_list_co_vau () {
	return array (
	);
}


function location_cities_list_co_vid () {
	return array (
	);
}


function location_cities_list_co_sap () {
	return array (
		"3670218" => t("San Andres"),
	);
}


function location_cities_list_co_qui () {
	return array (
		"3671098" => t("Quimbaya"),
		"3674463" => t("Montenegro"),
		"3677010" => t("La Tebaida"),
		"3686233" => t("Circasia"),
		"3687964" => t("Calarca"),
		"3689560" => t("Armenia"),
	);
}
