<?php

function location_cities_list_do_01 () {
	return array (
		"3511550" => t("Bella Vista"),
		"3509578" => t("Ciudad Nueva"),
		"3492908" => t("Santo Domingo"),
		"3491946" => t("Villa Consuelo"),
		"3491941" => t("Villa Francisca"),
	);
}


function location_cities_list_do_25 () {
	return array (
		"3492914" => t("Santiago de los Caballeros"),
		"3492517" => t("Tamboril"),
		"3491948" => t("Villa Bisono"),
	);
}


function location_cities_list_do_21 () {
	return array (
		"3512128" => t("Bajos de Haina"),
		"3511540" => t("San Cristobal"),
		"3491952" => t("Villa Altagracia"),
	);
}


function location_cities_list_do_08 () {
	return array (
		"3492984" => t("Santa Cruz de El Seibo"),
	);
}


function location_cities_list_do_04 () {
	return array (
		"3492985" => t("Santa Cruz de Barahona"),
	);
}


function location_cities_list_do_23 () {
	return array (
		"3494121" => t("Quisqueya"),
		"3493032" => t("San Pedro de Macoris"),
	);
}


function location_cities_list_do_22 () {
	return array (
		"3500370" => t("Las Matas de Farfan"),
		"3494242" => t("Punta Cana"),
		"3493081" => t("San Juan de la Maguana"),
	);
}


function location_cities_list_do_06 () {
	return array (
		"3493146" => t("San Francisco de Macoris"),
	);
}


function location_cities_list_do_15 () {
	return array (
		"3493174" => t("San Fernando de Monte Cristi"),
	);
}


function location_cities_list_do_18 () {
	return array (
		"3493175" => t("Puerto Plata"),
		"3493769" => t("Rio Grande"),
	);
}


function location_cities_list_do_11 () {
	return array (
		"3493240" => t("Salvaleon de Higuey"),
	);
}


function location_cities_list_do_19 () {
	return array (
		"3493283" => t("Salcedo"),
	);
}


function location_cities_list_do_26 () {
	return array (
		"3493383" => t("Sabaneta"),
	);
}


function location_cities_list_do_29 () {
	return array (
		"3511626" => t("Bayaguana"),
		"3496134" => t("Monte Plata"),
		"3493482" => t("Sabana Grande de Boya"),
	);
}


function location_cities_list_do_03 () {
	return array (
		"3495857" => t("Neiba"),
	);
}


function location_cities_list_do_14 () {
	return array (
		"3496021" => t("Nagua"),
	);
}


function location_cities_list_do_09 () {
	return array (
		"3496331" => t("Moca"),
	);
}


function location_cities_list_do_27 () {
	return array (
		"3505855" => t("Esperanza"),
		"3496831" => t("Mao"),
	);
}


function location_cities_list_do_12 () {
	return array (
		"3500957" => t("La Romana"),
	);
}


function location_cities_list_do_13 () {
	return array (
		"3509382" => t("Concepcion de La Vega"),
		"3509363" => t("Constanza"),
		"3504158" => t("Jarabacoa"),
	);
}


function location_cities_list_do_30 () {
	return array (
		"3504765" => t("Hato Mayor del Rey"),
	);
}


function location_cities_list_do_05 () {
	return array (
		"3508952" => t("Dajabon"),
	);
}


function location_cities_list_do_24 () {
	return array (
		"3509207" => t("Cotui"),
	);
}


function location_cities_list_do_28 () {
	return array (
		"3511233" => t("Bonao"),
	);
}


function location_cities_list_do_17 () {
	return array (
		"3512067" => t("Bani"),
	);
}


function location_cities_list_do_02 () {
	return array (
		"3512208" => t("Azua de Compostela"),
	);
}


