<?php


function location_cities_list_na_ca() {
  return array(
    "877178" => "Katima Mulilo",
  );
}


function location_cities_list_na_er() {
  return array(
    "3352844" => "Swakopmund",
    "3359638" => "Walvis Bay",
  );
}


function location_cities_list_na_ha() {
  return array(
    "3353540" => "Rehoboth",
  );
}


function location_cities_list_na_ka() {
  return array(
    "3355672" => "Luderitz",
    "3356264" => "Keetmanshoop",
  );
}


function location_cities_list_na_kh() {
  return array(
    "3352136" => "Windhoek",
  );
}


function location_cities_list_na_ku() {
  return array();
}


function location_cities_list_na_ow() {
  return array();
}


function location_cities_list_na_ok() {
  return array(
    "3353383" => "Rundu",
  );
}


function location_cities_list_na_oh() {
  return array(
    "3357247" => "Gobabis",
  );
}


function location_cities_list_na_os() {
  return array();
}


function location_cities_list_na_on() {
  return array(
    "3354021" => "Oshakati",
  );
}


function location_cities_list_na_ot() {
  return array();
}


function location_cities_list_na_od() {
  return array(
    "3353811" => "Otjiwarongo",
    "3354898" => "Okahandja",
    "3357114" => "Grootfontein",
  );
}
