<?php

function location_cities_list_ye_ad () {
	return array (
		"415189" => t("Aden"),
	);
}


function location_cities_list_ye_mr () {
	return array (
	);
}


function location_cities_list_ye_mw () {
	return array (
	);
}


function location_cities_list_ye_sa () {
	return array (
		"71137" => t("Sanaa"),
	);
}


function location_cities_list_ye_ib () {
	return array (
		"69559" => t("Yarim"),
		"74477" => t("Ibb"),
		"76154" => t("Dhi as Sufal"),
	);
}


function location_cities_list_ye_ab () {
	return array (
		"69426" => t("Zinjibar"),
	);
}


function location_cities_list_ye_dh () {
	return array (
		"76184" => t("Dhamar"),
	);
}


function location_cities_list_ye_la () {
	return array (
		"73560" => t("Lahij"),
	);
}


function location_cities_list_ye_ma () {
	return array (
		"72968" => t("Ma'rib"),
	);
}


function location_cities_list_ye_ra () {
	return array (
	);
}


function location_cities_list_ye_ta () {
	return array (
		"70225" => t("Ta`izz"),
	);
}


function location_cities_list_ye_ba () {
	return array (
		"79836" => t("Al Bayda'"),
	);
}


function location_cities_list_ye_ja () {
	return array (
		"79455" => t("Al Hazm"),
	);
}


function location_cities_list_ye_hu () {
	return array (
		"69500" => t("Zabid"),
		"76991" => t("Bayt al Faqih"),
		"77408" => t("Bajil"),
		"79415" => t("Al Hudaydah"),
	);
}


function location_cities_list_ye_da () {
	return array (
	);
}


function location_cities_list_ye_sd () {
	return array (
		"71334" => t("Sa'dah"),
	);
}


function location_cities_list_ye_hj () {
	return array (
		"75337" => t("Hajjah"),
	);
}


function location_cities_list_ye_hd () {
	return array (
		"78754" => t("Al Mukalla"),
	);
}


function location_cities_list_ye_am () {
	return array (
		"78428" => t("'Amran"),
	);
}


function location_cities_list_ye_sn () {
	return array (
		"70979" => t("Sayyan"),
		"71273" => t("Sahar"),
	);
}


function location_cities_list_ye_sh () {
	return array (
		"77726" => t("Ataq"),
	);
}
