<?php


function location_cities_list_ls_d() {
  return array();
}


function location_cities_list_ls_b() {
  return array(
    "932886" => "Butha-Buthe",
  );
}


function location_cities_list_ls_c() {
  return array(
    "932521" => "Maputsoe",
    "932698" => "Leribe",
  );
}


function location_cities_list_ls_e() {
  return array(
    "932614" => "Mafeteng",
  );
}


function location_cities_list_ls_a() {
  return array(
    "932505" => "Maseru",
  );
}


function location_cities_list_ls_f() {
  return array(
    "932438" => "Mohale's Hoek",
  );
}


function location_cities_list_ls_j() {
  return array();
}


function location_cities_list_ls_h() {
  return array(
    "932218" => "Qacha's Nek",
  );
}


function location_cities_list_ls_g() {
  return array(
    "932183" => "Quthing",
  );
}


function location_cities_list_ls_k() {
  return array();
}
