<?php

function location_cities_list_cy_04 () {
	return array (
		"18918" => t("Protaras"),
		"146617" => t("Famagusta"),
	);
}


function location_cities_list_cy_06 () {
	return array (
		"146412" => t("Kyrenia"),
	);
}


function location_cities_list_cy_03 () {
	return array (
		"146400" => t("Larnaca"),
	);
}


function location_cities_list_cy_01 () {
	return array (
		"146268" => t("Nicosia"),
	);
}


function location_cities_list_cy_02 () {
	return array (
		"146384" => t("Limassol"),
	);
}


function location_cities_list_cy_05 () {
	return array (
		"146214" => t("Paphos"),
	);
}
