<?php


function location_cities_list_no_02() {
  return array();
}


function location_cities_list_no_09() {
  return array(
    "3162955" => "Arendal",
  );
}


function location_cities_list_no_06() {
  return array(
    "3149563" => "Kongsberg",
    "3159016" => "Drammen",
  );
}


function location_cities_list_no_20() {
  return array();
}


function location_cities_list_no_04() {
  return array(
    "3154084" => "Hamar",
  );
}


function location_cities_list_no_12() {
  return array(
    "3161732" => "Bergen",
    "3336587" => "Askoy",
    "6697344" => "Ytrebygda",
  );
}


function location_cities_list_no_15() {
  return array(
    "3145580" => "Molde",
    "3149312" => "Kristiansund",
    "3163392" => "Alesund",
  );
}


function location_cities_list_no_17() {
  return array(
    "3136947" => "Steinkjer",
  );
}


function location_cities_list_no_18() {
  return array(
    "3145614" => "Mo i Rana",
    "3160881" => "Bodo",
  );
}


function location_cities_list_no_05() {
  return array(
    "3147474" => "Lillehammer",
    "3155573" => "Gjovik",
  );
}


function location_cities_list_no_03() {
  return array(
    "3143244" => "Oslo",
  );
}


function location_cities_list_no_11() {
  return array(
    "3137115" => "Stavanger",
    "3140321" => "Sandnes",
    "3153623" => "Haugesund",
  );
}


function location_cities_list_no_14() {
  return array();
}


function location_cities_list_no_16() {
  return array(
    "3133880" => "Trondheim",
  );
}


function location_cities_list_no_08() {
  return array(
    "3139075" => "Skien",
    "3142657" => "Porsgrunn",
  );
}


function location_cities_list_no_19() {
  return array(
    "3133895" => "Tromso",
    "3153823" => "Harstad",
  );
}


function location_cities_list_no_10() {
  return array(
    "3149318" => "Kristiansand",
  );
}


function location_cities_list_no_07() {
  return array(
    "3134331" => "Tonsberg",
    "3140390" => "Sandefjord",
    "3148129" => "Larvik",
    "3151770" => "Horten",
  );
}


function location_cities_list_no_01() {
  return array(
    "3140084" => "Sarpsborg",
    "3145375" => "Moss",
    "3154209" => "Halden",
    "3156529" => "Fredrikstad",
  );
}
