<?php

function location_cities_list_sn_zg () {
	return array (
		"2253901" => t("Bignona"),
		"2243940" => t("Ziguinchor"),
	);
}


function location_cities_list_sn_kd () {
	return array (
		"2249782" => t("Kolda"),
		"2244177" => t("Velingara"),
	);
}


function location_cities_list_sn_db () {
	return array (
		"2248698" => t("Mbake"),
		"2244616" => t("Tiebo"),
		"2244322" => t("Touba"),
	);
}


function location_cities_list_sn_th () {
	return array (
		"2251084" => t("Joal-Fadiout"),
		"2250677" => t("Kayar"),
		"2248409" => t("Mekhe"),
		"2247381" => t("Nguekhokh"),
		"2246606" => t("Pout"),
		"2244799" => t("Thies Nones"),
	);
}


function location_cities_list_sn_tc () {
	return array (
		"2244991" => t("Tambacounda"),
	);
}


function location_cities_list_sn_se () {
	return array (
		"2245704" => t("Sedhiou"),
	);
}


function location_cities_list_sn_sl () {
	return array (
		"2246544" => t("Richard-Toll"),
		"2246452" => t("Saint-Louis"),
	);
}


function location_cities_list_sn_fk () {
	return array (
		"2251230" => t("Guinguineo"),
		"2246608" => t("Pourham"),
	);
}


function location_cities_list_sn_dk () {
	return array (
		"2253354" => t("Dakar"),
		"2251339" => t("Grand Dakar"),
		"2246678" => t("Pikine"),
	);
}


function location_cities_list_sn_kl () {
	return array (
		"2250805" => t("Kaolack"),
		"2247157" => t("Nioro du Rip"),
	);
}


function location_cities_list_sn_lg () {
	return array (
		"2253277" => t("Dara"),
		"2249222" => t("Louga"),
		"2247813" => t("Ndibene Dahra"),
	);
}


function location_cities_list_sn_mt () {
	return array (
		"2248752" => t("Matam"),
	);
}


function location_cities_list_sn_ke () {
	return array (
		"2250645" => t("Kedougou"),
	);
}


function location_cities_list_sn_ka () {
	return array (
		"2251007" => t("Kaffrine"),
	);
}


