<?php


function location_cities_list_kw_ku() {
  return array(
    "285787" => "Kuwait City",
    "285856" => "Ad Dasmah",
    "388065" => "Ar Rabiyah",
  );
}


function location_cities_list_kw_fa() {
  return array(
    "285603" => "Janub as Surrah",
    "285815" => "Al Farwaniyah",
  );
}


function location_cities_list_kw_mu() {
  return array(
    "412800" => "Sabah as Salim",
  );
}


function location_cities_list_kw_ah() {
  return array(
    "285728" => "Ar Riqqah",
    "285778" => "Al Manqaf",
    "285782" => "Al Mahbulah",
    "285811" => "Al Fahahil",
    "285812" => "Al Fintas",
    "285839" => "Al Ahmadi",
  );
}


function location_cities_list_kw_ja() {
  return array(
    "285799" => "Al Jahra'",
  );
}


function location_cities_list_kw_ha() {
  return array(
    "285629" => "Hawalli",
    "285704" => "As Salimiyah",
    "285726" => "Ar Rumaythiyah",
    "387958" => "Salwa",
  );
}
