<?php


function location_cities_list_za_fs() {
  return array(
    "940424"  => "Wesselsbron",
    "940909"  => "Welkom",
    "943882"  => "Virginia",
    "943960"  => "Viljoenskroon",
    "949282"  => "Theunissen",
    "949703"  => "Thaba Nchu",
    "956507"  => "Senekal",
    "957487"  => "Sasolburg",
    "962847"  => "Reitz",
    "965401"  => "Phuthaditjhaba",
    "966166"  => "Parys",
    "985015"  => "Ladybrand",
    "986083"  => "Kutloanong",
    "986846"  => "Kroonstad",
    "996918"  => "Hennenman",
    "997140"  => "Heilbron",
    "997751"  => "Harrismith",
    "1016670" => "Botshabelo",
    "1016698" => "Bothaville",
    "1018725" => "Bloemfontein",
    "1019704" => "Bethlehem",
    "1023287" => "Allanridge",
  );
}


function location_cities_list_za_gp() {
  return array(
    "936374"  => "Roodepoort",
    "940316"  => "Westonaria",
    "944385"  => "Vereeniging",
    "944986"  => "Vanderbijlpark",
    "949880"  => "Tembisa",
    "952865"  => "Springs",
    "953781"  => "Soweto",
    "963230"  => "Randfontein",
    "964137"  => "Pretoria",
    "970566"  => "Nigel",
    "980921"  => "Mabopane",
    "986822"  => "Krugersdorp",
    "993800"  => "Johannesburg",
    "997151"  => "Heidelberg",
    "1012413" => "Cullinan",
    "1014073" => "Carletonville",
    "1015504" => "Bronkhorstspruit",
    "1016181" => "Brakpan",
    "1017780" => "Boksburg",
    "1020098" => "Benoni",
    "1105726" => "Ekangala",
    "1105776" => "Midrand",
    "1105777" => "Centurion",
  );
}


function location_cities_list_za_zn() {
  return array(
    "942470"  => "Vryheid",
    "946128"  => "Umkomaas",
    "946257"  => "Ulundi",
    "952734"  => "Stanger",
    "956878"  => "Scottburgh",
    "962330"  => "Richmond",
    "962367"  => "Richards Bay",
    "964406"  => "Port Shepstone",
    "965301"  => "Pietermaritzburg",
    "971421"  => "Newcastle",
    "973111"  => "Mpumalanga",
    "973139"  => "Mpophomeni",
    "974670"  => "Mondlo",
    "978895"  => "Margate",
    "988356"  => "Kokstad",
    "995202"  => "Howick",
    "1005029" => "eSikhawini",
    "1005544" => "Empangeni",
    "1007311" => "Durban",
    "1007400" => "Dundee",
    "1021360" => "Ballitoville",
  );
}


function location_cities_list_za_lp() {
  return array(
    "941966"  => "Warmbaths",
    "946973"  => "Tzaneen",
    "949224"  => "Thohoyandou",
    "964315"  => "Mokopane",
    "965289"  => "Polokwane",
    "965528"  => "Phalaborwa",
    "968665"  => "Modimolle",
    "970341"  => "Nkowakowa",
    "976885"  => "Messina",
    "981827"  => "Louis Trichardt",
    "984087"  => "Lebowakgomo",
    "1001860" => "Giyani",
    "1005768" => "Ellisras",
    "1007514" => "Duiwelskloof",
  );
}


function location_cities_list_za_mp() {
  return array(
    "938694"  => "White River",
    "939270"  => "Witbank",
    "943032"  => "Volksrust",
    "952747"  => "Standerton",
    "955313"  => "Siyabuswa",
    "956767"  => "Secunda",
    "965241"  => "Piet Retief",
    "971534"  => "Nelspruit",
    "976361"  => "Middelburg",
    "981158"  => "Lydenburg",
    "987202"  => "Kriel",
    "988290"  => "Komatipoort",
    "996930"  => "Hendrina",
    "1005125" => "Ermelo",
    "1005646" => "eMbalenhle",
    "1008261" => "Driefontein",
    "1011031" => "Delmas",
    "1019760" => "Bethal",
    "1021086" => "Barberton",
    "1021396" => "Balfour",
  );
}


function location_cities_list_za_nc() {
  return array(
    "941931"  => "Warrenton",
    "945945"  => "Upington",
    "990930"  => "Kimberley",
    "1011632" => "De Aar",
  );
}


function location_cities_list_za_ec() {
  return array(
    "946058"  => "Mthatha",
    "946877"  => "Uitenhage",
    "951650"  => "Stutterheim",
    "954161"  => "Somerset East",
    "963516"  => "Queenstown",
    "963525"  => "Queensdale",
    "964420"  => "Port Elizabeth",
    "964432"  => "Port Alfred",
    "976358"  => "Middelburg",
    "985011"  => "Lady Frere",
    "986717"  => "Kruisfontein",
    "1000501" => "Grahamstown",
    "1000543" => "Graaff-Reinet",
    "1003953" => "Fort Beaufort",
    "1006984" => "East London",
    "1012600" => "Cradock",
    "1014489" => "Butterworth",
    "1019330" => "Bhisho",
    "1023309" => "Aliwal North",
  );
}


function location_cities_list_za_nw() {
  return array(
    "937136"  => "Zeerust",
    "938457"  => "Wolmaransstad",
    "942511"  => "Vryburg",
    "952192"  => "Stilfontein",
    "956907"  => "Schweizer-Reneke",
    "958724"  => "Rustenburg",
    "964349"  => "Potchefstroom",
    "966380"  => "Pampierstad",
    "967476"  => "Orkney",
    "975436"  => "Mmabatho",
    "982899"  => "Lichtenburg",
    "989921"  => "Klerksdorp",
    "1002851" => "Ga-Rankuwa",
    "1004109" => "Fochville",
    "1013550" => "Christiana",
    "1015621" => "Brits",
    "1018673" => "Bloemhof",
  );
}


function location_cities_list_za_wc() {
  return array(
    "964712"  => "Plettenberg Bay",
    "967106"  => "Oudtshoorn",
    "973709"  => "Mossel Bay",
    "988698"  => "Knysna",
    "1002145" => "George",
    "1020641" => "Beaufort West",
    "3359041" => "Worcester",
    "3361025" => "Stellenbosch",
    "3361934" => "Saldanha",
    "3363613" => "Noorder-Paarl",
    "3364346" => "Malmesbury",
    "3366880" => "Hermanus",
    "3367513" => "Grabouw",
    "3369129" => "Ceres",
    "3369157" => "Cape Town",
    "3370352" => "Atlantis",
  );
}
