<?php

function location_cities_list_uz_an()
{
	return array(
		'1538282' => t('Andijon Shahri'),
		'1514584' => t('Andijon Tumani'),
		'1538283' => t('Asaka Shahri'),
		'1513270' => t('Asaka Tumani'),
		'1514451' => t('Baliqchi Tumani'),
		'1538281' => t('Buloqboshi Tumani'),
		'1514336' => t('Bŭz Tumani'),
		'1513888' => t('Izboskan Tumani'),
		'1514108' => t('Jalolkuduk Tumani'),
		'1538285' => t('Khonobod Shahri'),
		'1513598' => t('Khŭjaobod Tumani'),
		'1513240' => t('Marhamat Tumani'),
		'1514606' => t('Oltinkŭl Tumani'),
		'1513039' => t('Pakhtaobod Tumani'),
		'1538284' => t('Qorasuw Shahri'),
		'1513363' => t('Qŭrghontepa Tumani'),
		'1538286' => t('Shahrikhon Shahri'),
		'1513193' => t('Shahrikhon Tumani'),
		'7668830' => t('Ulugnar'),
	);
}
function location_cities_list_uz_bu()
{
	return array(
		'7668831' => t('Alat'),
		'1346436' => t('Bukhoro Shahri'),
		'1217663' => t('Bukhoro Tumani'),
		'1538236' => t('Ghijduwon Shahri'),
		'1513982' => t('Ghijduwon Tumani'),
		'1216048' => t('Jondor Tumani'),
		'1346437' => t('Kogon Shahri'),
		'1217179' => t('Kogon Tumani'),
		'1217905' => t('Olot Tumani'),
		'1513006' => t('Peshku Tumani'),
		'1217081' => t('Qorakŭl Tumani'),
		'1346433' => t('Qorovulbozor Tumani'),
		'1216289' => t('Romiton Tumani'),
		'1512837' => t('Shofirkon Tumani'),
		'1215788' => t('Wobkent Tumani'),
	);
}
function location_cities_list_uz_fa()
{
	return array(
		'7668818' => t('Altyarik'),
		'7668819' => t('Bagdad'),
		'1514482' => t('Baghdod Tumani'),
		'1513547' => t('Beshariq Tumani'),
		'1514299' => t('Buwayda Tumani'),
		'1514016' => t('Danghara Tumani'),
		'1514017' => t('Farghona Tumani'),
		'1538296' => t('Farg‘ona Shahri'),
		'1538294' => t('Furqat Tumani'),
		'1538300' => t('Marg‘ilon Shahri'),
		'1514681' => t('Okhunboboyew Tumani'),
		'1514616' => t('Oltiariq Tumani'),
		'1538297' => t('Qo‘qon Shahri'),
		'1538298' => t('Quva Shahri'),
		'1538299' => t('Quvasoy Shahri'),
		'1513329' => t('Quwa Tumani'),
		'7668820' => t('Rishtan'),
		'1512956' => t('Rishton Tumani'),
		'1538295' => t('So’x Tumani'),
		'1512646' => t('Toshloq Tumani'),
		'1513272' => t('Uchkŭprik Tumani'),
		'1513493' => t('Ulughnor Tumani'),
		'7668842' => t('Yazyavan'),
		'1512318' => t('Yozyowon Tumani'),
		'1512439' => t('Ŭzbekiston Tumani'),
	);
}
function location_cities_list_uz_ji()
{
	return array(
		'1514555' => t('Arnasoy Tumani'),
		'1217778' => t('Baxmal Tumani'),
		'1514124' => t('Dŭstlik Tumani'),
		'1514024' => t('Forish Tumani'),
		'1217334' => t('G‘allaorol Tumani'),
		'1538240' => t('Jizzax Shahri'),
		'1514068' => t('Jizzax Tumani'),
		'1513202' => t('Mirzachŭl Tumani'),
		'1513035' => t('Paxtakor Tumani'),
		'1513067' => t('Zafarobod Tumani'),
		'1512277' => t('Zarbdor Tumani'),
		'1215692' => t('Zomin Tumani'),
	);
}
function location_cities_list_uz_ng()
{
	return array(
		'1538272' => t('Chortoq Tumani'),
		'1514190' => t('Chust Tumani'),
		'1538277' => t('Chust Tumani'),
		'1513713' => t('Kosonsoy Tumani'),
		'1512289' => t('Mingbuloq Tumani'),
		'1513156' => t('Namangan Tumani'),
		'1513144' => t('Norin Tumani'),
		'1513021' => t('Pop Tumani'),
		'1512548' => t('Tŭraqŭrghon Tumani'),
		'1512500' => t('Uchqŭrghon Tumani'),
		'1512448' => t('Uychi Tumani'),
		'1512349' => t('Yangiqo‘rg‘on Tumani'),
	);
}
function location_cities_list_uz_nw()
{
	return array(
		'1513830' => t('Konimex Tumani'),
		'1513135' => t('Navbahor Tumani'),
		'1513133' => t('Navoiy Tumani'),
		'1513082' => t('Nurota Tumani'),
		'1216582' => t('Qiziltepa Tumani'),
		'1512673' => t('Tomdi Tumani'),
		'1512504' => t('Uchquduq Tumani'),
		'1513622' => t('Xatirchi Tumani'),
	);
}
function location_cities_list_uz_qa()
{
	return array(
		'1514593' => t('Amudaryo Tumani'),
		'1514386' => t('Beruniy Tumani'),
		'601398' => t('Bo’zatov Tumani'),
		'601394' => t('Chimboy Tumani'),
		'1514037' => t('Ellikqala Tumani'),
		'601347' => t('Kegeyli Tumani'),
		'601301' => t('Mo’ynoq Tumani'),
		'601292' => t('Nukus Tumani'),
		'601309' => t('Qanliko’l Tumani'),
		'1513732' => t('Qorao’zak Tumani'),
		'601322' => t('Qo’ng’irot Tumani'),
		'601276' => t('Shumanay Tumani'),
		'1512698' => t('Taxtako’pir Tumani'),
		'1512534' => t('To’rtko’l Tumani'),
		'601340' => t('Xo’jayli Tumani'),
	);
}
function location_cities_list_uz_qr()
{
	return array(
		'1217538' => t('Chiroqchi Tumani'),
		'1217479' => t('Dehqonobod Tumani'),
		'1217259' => t('G‘uzor Tumani'),
		'1215855' => t('Kasbi Tumani'),
		'1216786' => t('Kitob Tumani'),
		'1217005' => t('Koson Tumani'),
		'7668833' => t('Mirishkar'),
		'1346479' => t('Mirishkor Tumani'),
		'1216474' => t('Muborak Tumani'),
		'1216399' => t('Nishon Tumani'),
		'1217142' => t('Qamashi Tumani'),
		'1346481' => t('Qarshi Shahri'),
		'1217013' => t('Qarshi Tumani'),
		'1216186' => t('Shahrisabz Tumani'),
		'1215811' => t('Usmon Yusupov Tumani'),
		'1215766' => t('Yakkabog’ Tumani'),
	);
}
function location_cities_list_uz_sa()
{
	return array(
		'1217655' => t('Bulung‘ur Tumani'),
		'1346451' => t('Chelak Tumani'),
		'1346455' => t('Go`zalkent Tumani'),
		'1217214' => t('Ishtixon Tumani'),
		'1217412' => t('Jomboy Tumani'),
		'1346466' => t('Kattaqo‘rg‘on Shahri'),
		'1216987' => t('Kattaqo‘rg‘on Tumani'),
		'1216429' => t('Narpay Tumani'),
		'1216079' => t('Nurobod Tumani'),
		'1217960' => t('Oqdaryo Tumani'),
		'1346465' => t('Oqtosh Shahri'),
		'7668834' => t('Pastdargom'),
		'1216341' => t('Pastdarg‘om Tumani'),
		'1216354' => t('Paxtachi Tumani'),
		'1216337' => t('Payariq Tumani'),
		'1513472' => t('Qo‘shrabot Tumani'),
		'1346463' => t('Samarqand Shahri'),
		'1216266' => t('Samarqand Tumani'),
		'1346462' => t('Toyloq Tumani'),
		'1346467' => t('Urgut Shahri'),
		'1215838' => t('Urgut Tumani'),
	);
}
function location_cities_list_uz_si()
{
	return array(
		'1538253' => t('Bakht Shahri'),
		'7668840' => t('Bayaut'),
		'1514430' => t('Boyowut Tumani'),
		'1538249' => t('Guliston Shahri'),
		'1513967' => t('Guliston Tumani'),
		'1513618' => t('Khovos Tumani'),
		'1538246' => t('Mehnatobod Tumani'),
		'1513490' => t('Mirzaobod Tumani'),
		'1514705' => t('Oqoltin Tumani'),
		'1512404' => t('Sayhunobod Tumani'),
		'1513952' => t('Sharof-Rashidow Tumani'),
		'1538251' => t('Shirin Shahri'),
		'1538250' => t('Sirdaryo Shahri'),
		'1512717' => t('Sirdaryo Tumani'),
		'1538252' => t('Yangiyer Shahri'),
	);
}
function location_cities_list_uz_su()
{
	return array(
		'1217872' => t('Angor Tumani'),
		'1346534' => t('Bandikhon Tumani'),
		'1217733' => t('Boysun Tumani'),
		'1346537' => t('Denov Shahri'),
		'1217476' => t('Denov Tumani'),
		'1217391' => t('Jarqo’rg’on Tumani'),
		'1217341' => t('Muzrabod Tumani'),
		'1217894' => t('Oltinsoy Tumani'),
		'1216571' => t('Qiziriq Tumani'),
		'1216685' => t('Qumqŭrghon Tumani'),
		'1216243' => t('Sariosiyo Tumani'),
		'1216154' => t('Sherobod Tumani'),
		'1216113' => t('Sho’rchi Tumani'),
		'1346536' => t('Termiz Shahri'),
		'1215958' => t('Termiz Tumani'),
		'1346497' => t('Uzun Tumani'),
		'1538254' => t('Yangiyŭl Tumani'),
	);
}
function location_cities_list_uz_tk()
{
	return array(
		'1514665' => t('Akmal Ikromow Tumani'),
		'1536760' => t('Bektemir Tumani'),
		'1514229' => t('Chilonzor Tumani'),
		'1513648' => t('Hamza Tumani'),
		'1513269' => t('Mirobod Tumani'),
		'1513328' => t('Mirzo Ulug‘bek Tumani'),
		'1513066' => t('Shaykhontohur Tumani'),
		'1512848' => t('Sirgali Tumani'),
		'1512949' => t('Sobir Rahimov Tumani'),
		'1536761' => t('Yakkasaroy Tumani'),
		'1513546' => t('Yunusobod Tumani'),
	);
}
function location_cities_list_uz_to()
{
	return array(
		'1538257' => t('Angren Shahri'),
		'1538259' => t('Bekobod Shahri'),
		'1514399' => t('Bekobod Tumani'),
		'1514327' => t('Bŭka Tumani'),
		'1514338' => t('Bŭstonliq Tumani'),
		'1514214' => t('Chinoz Tumani'),
		'1538260' => t('Chirchiq Shahri'),
		'1538258' => t('Ohangaron Shahri'),
		'1514687' => t('Ohangaron Tumani'),
		'1538256' => t('Olmaliq Shahri'),
		'1514667' => t('Oqqŭrghon Tumani'),
		'1513016' => t('Parkent Tumani'),
		'1512985' => t('Piskent Tumani'),
		'1513057' => t('Qibray Tumani'),
		'1514010' => t('Quyi Chirchiq Tumani'),
		'1512652' => t('Toshkent Tumani'),
		'1538261' => t('Yangiobod Shahri'),
		'1513498' => t('Yuqori Chirchiq Tumani'),
		'1513860' => t('Zangiota Tumani'),
		'1512751' => t('Ŭrta Chirchiq Tumani'),
	);
}
function location_cities_list_uz_xo()
{
	return array(
		'1514485' => t('Boghot Tumani'),
		'1513961' => t('Gurlan Tumani'),
		'1513610' => t('Hazorasp Tumani'),
		'1538228' => t('Khiwa Shahri'),
		'1513603' => t('Khiwa Tumani'),
		'1513635' => t('Khonqa Tumani'),
		'1538227' => t('Pitnak Shahri'),
		'1513477' => t('Qŭshkŭpir Tumani'),
		'1512818' => t('Showot Tumani'),
		'1538226' => t('Urganch Shahri'),
		'1512467' => t('Urganch Tumani'),
		'1512367' => t('Yangiariq Tumani'),
		'1512360' => t('Yangibozor Tumani'),
	);
}
