<?php


function location_cities_list_kw_ku() {
  return array(
    "285787" => t("Kuwait City"),
    "285856" => t("Ad Dasmah"),
    "388065" => t("Ar Rabiyah"),
  );
}


function location_cities_list_kw_fa() {
  return array(
    "285603" => t("Janub as Surrah"),
    "285815" => t("Al Farwaniyah"),
  );
}


function location_cities_list_kw_mu() {
  return array(
    "412800" => t("Sabah as Salim"),
  );
}


function location_cities_list_kw_ah() {
  return array(
    "285728" => t("Ar Riqqah"),
    "285778" => t("Al Manqaf"),
    "285782" => t("Al Mahbulah"),
    "285811" => t("Al Fahahil"),
    "285812" => t("Al Fintas"),
    "285839" => t("Al Ahmadi"),
  );
}


function location_cities_list_kw_ja() {
  return array(
    "285799" => t("Al Jahra'"),
  );
}


function location_cities_list_kw_ha() {
  return array(
    "285629" => t("Hawalli"),
    "285704" => t("As Salimiyah"),
    "285726" => t("Ar Rumaythiyah"),
    "387958" => t("Salwa"),
  );
}
