<?php


function location_cities_list_ir_44() {
  return array(
    "122438" => "Nazarabad",
    "128747" => "Karaj",
  );
}


function location_cities_list_ir_06() {
  return array(
    "134217" => "Bandar-e Ganaveh",
    "139817" => "Bandar-e Bushehr",
    "140097" => "Borazjan",
  );
}


function location_cities_list_ir_01() {
  return array(
    "113646" => "Tabriz",
    "124862" => "Marand",
    "140889" => "Bonab",
    "142554" => "Hashtrud",
    "144443" => "`Ajab Shir",
    "144616" => "Ahar",
  );
}


function location_cities_list_ir_14() {
  return array(
    "115019" => "Shiraz",
    "121925" => "Nurabad",
    "122289" => "Neyriz",
    "128321" => "Kazerun",
    "133595" => "Gerash",
    "134518" => "Firuzabad",
    "134721" => "Fasa",
    "137956" => "Darab",
    "144410" => "Akbarabad",
    "145449" => "Abadeh",
  );
}


function location_cities_list_ir_23() {
  return array(
    "119374" => "Qeshm",
    "123941" => "Minab",
    "126914" => "Kish",
    "141665" => "Bandar-e Lengeh",
    "141681" => "Bandar 'Abbas",
  );
}


function location_cities_list_ir_22() {
  return array(
    "116667" => "Saveh",
    "127403" => "Khomeyn",
    "136399" => "Delijan",
    "143127" => "Arak",
    "144794" => "Abyek",
  );
}


function location_cities_list_ir_21() {
  return array(
    "112656" => "Tonekabon",
    "116996" => "Sari",
    "121959" => "Now Shahr",
    "122397" => "Neka'",
    "129933" => "Juybar",
    "134602" => "Fereydun Kenar",
    "139223" => "Chalus",
    "140918" => "Behshahr",
    "142358" => "Babolsar",
    "142363" => "Babol",
    "143534" => "Amol",
  );
}


function location_cities_list_ir_03() {
  return array(
    "121380" => "Parsabad",
    "128008" => "Herowabad",
    "143083" => "Ardabil",
  );
}


function location_cities_list_ir_08() {
  return array(
    "115770" => "Shahr-e Kord",
    "120678" => "Farrokh Shahr",
    "134762" => "Farsan",
    "140046" => "Borujen",
  );
}


function location_cities_list_ir_04() {
  return array(
    "116406" => "Semirom",
    "127033" => "Khvansar",
    "128477" => "Kashan",
    "133037" => "Golpayegan",
    "143052" => "Ardestan",
    "417594" => "Shahreza",
    "418521" => "Rehnan",
    "418571" => "Qahderijan",
    "418606" => "Najafabad",
    "418710" => "Khomeyni Shahr",
    "418723" => "Kelishad va Sudarjan",
    "418851" => "Felavarjan",
    "418863" => "Esfahan",
    "418868" => "Dowlatabad",
    "418896" => "Dorcheh Piaz",
  );
}


function location_cities_list_ir_27() {
  return array(
    "110831" => "Shah Pasand",
    "129512" => "Kalaleh",
    "132892" => "Gorgan",
    "132938" => "Gonbad-e Qabus",
  );
}


function location_cities_list_ir_19() {
  return array(
    "113343" => "Hashtpar",
    "118191" => "Rudsar",
    "118743" => "Rasht",
    "125897" => "Langerud",
    "141679" => "Bandar-e Anzali",
    "142676" => "Astara",
    "142679" => "Astaneh-ye Ashrafiyeh",
  );
}


function location_cities_list_ir_24() {
  return array(
    "14256"  => "Azadshahr",
    "122915" => "Nahavand",
    "125185" => "Malayer",
    "132144" => "Hamadan",
    "142000" => "Bahar",
    "142872" => "Asadabad",
  );
}


function location_cities_list_ir_15() {
  return array(
    "111421" => "Zarand",
    "114259" => "Sirjan",
    "115781" => "Shahr-e Babak",
    "118704" => "Ravar",
    "118994" => "Rafsanjan",
    "124647" => "Bardsir",
    "128234" => "Kerman",
    "141736" => "Bam",
  );
}


function location_cities_list_ir_17() {
  return array(
    "23814"  => "Kahriz",
    "114049" => "Sonqor",
    "120931" => "Sarpol-e Zahab",
    "121240" => "Paveh",
    "128226" => "Kermanshah",
    "128831" => "Kangavar",
    "130245" => "Javanrud",
    "131962" => "Harsin",
  );
}


function location_cities_list_ir_29() {
  return array(
    "140463" => "Birjand",
  );
}


function location_cities_list_ir_31() {
  return array(
    "135298" => "Esfarayen",
    "140380" => "Bojnurd",
  );
}


function location_cities_list_ir_10() {
  return array(
    "114584" => "Shushtar",
    "114593" => "Shush",
    "116102" => "Shadegan",
    "118805" => "Ramshir",
    "118826" => "Ramhormoz",
    "121861" => "Omidiyeh",
    "124620" => "Masjed Soleyman",
    "127319" => "Khorramshahr",
    "137268" => "Susangerd",
    "140951" => "Behbahan",
    "144448" => "Ahvaz",
    "144696" => "Aghajari",
    "145459" => "Abadan",
  );
}


function location_cities_list_ir_18() {
  return array(
    "66093"  => "Yasuj",
    "136014" => "Do Gonbadan",
    "136987" => "Dehdasht",
  );
}


function location_cities_list_ir_16() {
  return array(
    "117392" => "Saqqez",
    "117574" => "Sanandaj",
    "119161" => "Qorveh",
    "128905" => "Kamyaran",
    "140521" => "Bijar",
    "141584" => "Baneh",
  );
}


function location_cities_list_ir_20() {
  return array(
    "24851"  => "Nurabad",
    "126409" => "Kuhdasht",
    "127349" => "Khorramabad",
    "140044" => "Borujerd",
    "142496" => "Azna",
    "143921" => "Aligudarz",
    "144269" => "Aleshtar",
  );
}


function location_cities_list_ir_28() {
  return array(
    "113491" => "Takestan",
    "119505" => "Qazvin",
  );
}


function location_cities_list_ir_13() {
  return array(
    "1113217" => "Zabol",
    "1159301" => "Zahedan",
    "1160571" => "Khash",
    "1160939" => "Iranshahr",
    "1161724" => "Chah Bahar",
  );
}


function location_cities_list_ir_07() {
  return array(
    "32767"  => "Qarchak",
    "32909"  => "Shahre Jadide Andisheh",
    "112214" => "Varamin",
    "112931" => "Tehran",
    "118367" => "Robat Karim",
    "120972" => "Pishva",
    "125188" => "Malard",
    "138042" => "Damavand",
    "143860" => "Shahriar",
    "406993" => "Eqbaliyeh",
  );
}


function location_cities_list_ir_02() {
  return array(
    "113508" => "Takab",
    "117656" => "Salmas",
    "117793" => "Shahin Dezh",
    "119730" => "Qarah Zia' od Din",
    "121110" => "Piranshahr",
    "121795" => "Oshnaviyeh",
    "121801" => "Orumiyeh",
    "122698" => "Naqadeh",
    "124085" => "Miandowab",
    "125446" => "Mahabad",
    "126972" => "Khvoy",
    "139889" => "Bukan",
  );
}


function location_cities_list_ir_05() {
  return array(
    "130802" => "Ilam",
    "136702" => "Dehloran",
    "145233" => "Abdanan",
  );
}


function location_cities_list_ir_26() {
  return array(
    "119208" => "Qom",
  );
}


function location_cities_list_ir_30() {
  return array(
    "112646"  => "Torbat-e Heydariyeh",
    "118063"  => "Sabzevar",
    "119115"  => "Quchan",
    "120694"  => "Qayen",
    "122285"  => "Neyshabur",
    "124665"  => "Mashhad",
    "128447"  => "Kashmar",
    "132961"  => "Gonabad",
    "138742"  => "Chenaran",
    "1159362" => "Torbat-e Jam",
    "1159384" => "Taybad",
    "1159716" => "Sarakhs",
  );
}


function location_cities_list_ir_12() {
  return array(
    "32723"  => "Istgah-e Rah Ahan-e Garmsar",
    "116402" => "Semnan",
    "135423" => "Shahrud",
    "138025" => "Damghan",
  );
}


function location_cities_list_ir_25() {
  return array(
    "111822" => "Yazd",
    "113632" => "Taft",
    "113659" => "Tabas",
    "124193" => "Meybod",
    "124274" => "Mehriz",
    "142255" => "Bafq",
    "143073" => "Ardakan",
  );
}


function location_cities_list_ir_11() {
  return array(
    "41210"  => "Khorram Darreh",
    "111453" => "Zanjan",
    "143748" => "Alvand",
    "145034" => "Abhar",
  );
}
