<?php

function location_cities_list_zw_bu () {
	return array (
		"894701" => t("Bulawayo"),
	);
}


function location_cities_list_zw_ha () {
	return array (
		"890299" => t("Harare"),
		"1085510" => t("Epworth"),
		"1106542" => t("Chitungwiza"),
	);
}


function location_cities_list_zw_ma () {
	return array (
		"882100" => t("Rusape"),
		"884979" => t("Mutare"),
		"893549" => t("Chipinge"),
	);
}


function location_cities_list_zw_mc () {
	return array (
		"895061" => t("Bindura"),
	);
}


function location_cities_list_zw_me () {
	return array (
		"886990" => t("Marondera"),
	);
}


function location_cities_list_zw_mw () {
	return array (
		"884141" => t("Norton"),
		"889191" => t("Karoi"),
		"889215" => t("Kariba"),
		"889453" => t("Kadoma"),
		"893697" => t("Chinhoyi"),
		"894239" => t("Chegutu"),
	);
}


function location_cities_list_zw_mv () {
	return array (
		"878549" => t("Zvishavane"),
		"886763" => t("Masvingo"),
		"893485" => t("Chiredzi"),
	);
}


function location_cities_list_zw_mn () {
	return array (
		"879431" => t("Victoria Falls"),
		"889942" => t("Hwange"),
	);
}


function location_cities_list_zw_ms () {
	return array (
		"895269" => t("Beitbridge"),
	);
}


function location_cities_list_zw_mi () {
	return array (
		"881164" => t("Shurugwi"),
		"882599" => t("Redcliff"),
		"888710" => t("Kwekwe"),
		"890422" => t("Gweru"),
		"890983" => t("Gokwe"),
	);
}
