<?php


function location_cities_list_ng_ab() {
  return array(
    "2320576" => "Umuahia",
    "2327494" => "Ohafia-Ifigh",
    "2347303" => "Bende",
    "2350249" => "Amaigbo",
    "2353151" => "Aba",
  );
}


function location_cities_list_ng_ad() {
  return array(
    "2318044" => "Yola",
    "2328617" => "Numan",
    "2329821" => "Mubi",
    "2336056" => "Jimeta",
    "2340446" => "Little Gombi",
    "2341955" => "Ganye",
  );
}


function location_cities_list_ng_ak() {
  return array(
    "2319480" => "Uyo",
    "2336985" => "Itu",
    "2338106" => "Ikot-Ekpene",
    "2343093" => "Esuk Oron",
    "2343720" => "Eket",
  );
}


function location_cities_list_ng_ba() {
  return array(
    "2335015" => "Kari",
    "2345152" => "Darazo",
    "2347470" => "Bauchi",
    "2348595" => "Azare",
  );
}


function location_cities_list_ng_by() {
  return array(
    "2318123" => "Yenagoa",
  );
}


function location_cities_list_ng_be() {
  return array(
    "2322552" => "Takum",
    "2325437" => "Otukpa",
    "2331140" => "Makurdi",
    "2334801" => "Katsina Ala",
    "2338660" => "Igbor",
  );
}


function location_cities_list_ng_bo() {
  return array(
    "2329946" => "Mongonu",
    "2330719" => "Marte",
    "2331447" => "Maiduguri",
    "2331528" => "Magumeri",
    "2333563" => "Kukawa",
    "2339665" => "Gwoza",
    "2342192" => "Gambaru",
    "2344854" => "Dikwa",
    "2345498" => "Damboa",
    "2346995" => "Biu",
    "2347954" => "Bama",
  );
}


function location_cities_list_ng_cr() {
  return array(
    "2320831" => "Ugep",
    "2327650" => "Ogoja",
    "2328151" => "Obudu",
    "2338242" => "Ikom",
    "2346229" => "Calabar",
  );
}


function location_cities_list_ng_de() {
  return array(
    "2319133" => "Warri",
    "2320829" => "Ughelli",
    "2323675" => "Sapele",
    "2327513" => "Ogwashi-Uku",
    "2332871" => "Kwale",
    "2346317" => "Burutu",
    "2349276" => "Asaba",
    "2351979" => "Agbor",
  );
}


function location_cities_list_ng_eb() {
  return array(
    "2337148" => "Isieke",
    "2342883" => "Ezza Ohu",
    "2343985" => "Effium",
    "2352250" => "Afikpo",
    "2353099" => "Abakaliki",
  );
}


function location_cities_list_ng_ed() {
  return array(
    "2319668" => "Uromi",
    "2321031" => "Ubiaja",
    "2343641" => "Ekpoma",
    "2347283" => "Benin City",
    "2348892" => "Auchi",
  );
}


function location_cities_list_ng_ek() {
  return array(
    "2327233" => "Oke Ila",
    "2337207" => "Ise-Ekiti",
    "2337352" => "Ipoti",
    "2338287" => "Ikerre",
    "2338385" => "Ijero-Ekiti",
    "2338630" => "Igede-Ekiti",
    "2338810" => "Igbara-Odo",
    "2343299" => "Emure-Ekiti",
    "2349529" => "Araomoko Ekiti",
    "2352379" => "Ado-Ekiti",
  );
}


function location_cities_list_ng_en() {
  return array(
    "2328684" => "Nsukka",
    "2343273" => "Enugu-Ezike",
    "2343279" => "Enugu",
    "2343822" => "Eha Amufu",
    "2348783" => "Awgu",
    "2350886" => "Aku",
  );
}


function location_cities_list_ng_fc() {
  return array(
    "2333604" => "Kuje",
    "2352778" => "Abuja",
  );
}


function location_cities_list_ng_go() {
  return array(
    "2324857" => "Pindiga",
    "2329562" => "Nafada",
    "2333451" => "Kumo",
    "2340451" => "Gombe",
    "2341758" => "Garko",
    "2344418" => "Dukku",
    "2345029" => "Deba Habe",
    "2347155" => "Biliri",
  );
}


function location_cities_list_ng_im() {
  return array(
    "2325330" => "Owerri",
    "2327143" => "Okigwi",
    "2327521" => "Oguta",
    "2328790" => "Nkwerre",
  );
}


function location_cities_list_ng_ji() {
  return array(
    "2334306" => "Kiyawa",
    "2339631" => "Hadejia",
    "2339786" => "Gwaram",
    "2340091" => "Gumel",
    "2344245" => "Dutse",
    "2347057" => "Birnin Kudu",
  );
}


function location_cities_list_ng_kd() {
  return array(
    "2317765" => "Zaria",
    "2322957" => "Soba",
    "2332079" => "Lere",
    "2335614" => "Kagoro",
    "2335713" => "Kafachan",
    "2335727" => "Kaduna",
    "2335798" => "Kachia",
    "2344229" => "Dutsen Wai",
    "2347061" => "Sofo-Birnin-Gwari",
    "2349951" => "Anchau",
  );
}


function location_cities_list_ng_kn() {
  return array(
    "2318933" => "Wudil",
    "2324575" => "Rano",
    "2335204" => "Kano",
    "2339756" => "Gwarzo",
    "2341580" => "Gaya",
  );
}


function location_cities_list_ng_kt() {
  return array(
    "2331005" => "Malumfashi",
    "2334802" => "Katsina",
    "2342490" => "Funtua",
    "2345094" => "Daura",
  );
}


function location_cities_list_ng_ke() {
  return array(
    "2317548" => "Zuru",
    "2335333" => "Kamba",
    "2336237" => "Jega",
    "2347059" => "Birnin Kebbi",
    "2349431" => "Argungu",
  );
}


function location_cities_list_ng_ko() {
  return array(
    "2327827" => "Ogaminan",
    "2331939" => "Lokoja",
    "2335843" => "Kabba",
    "2337235" => "Isanlu Itedoijowa",
    "2339156" => "Idah",
    "2343943" => "Egbe",
    "2351470" => "Ajaokuta",
  );
}


function location_cities_list_ng_kw() {
  return array(
    "2324960" => "Pategi",
    "2326811" => "Okuta",
    "2327879" => "Offa",
    "2332504" => "Lafiagi",
    "2335596" => "Kaiama",
    "2336251" => "Jebba",
    "2337639" => "Ilorin",
    "2346951" => "Bode Sadu",
  );
}


function location_cities_list_ng_la() {
  return array(
    "2331158" => "Makoko",
    "2332459" => "Lagos",
    "2338313" => "Ikeja",
    "2343252" => "Epe",
    "2344082" => "Ebute Ikorodu",
    "2348395" => "Badagry",
  );
}


function location_cities_list_ng_na() {
  return array(
    "2319257" => "Wamba",
    "2329451" => "Nassarawa",
    "2332515" => "Lafia",
    "2334652" => "Keffi",
    "2344600" => "Doma",
    "2350806" => "Akwanga",
  );
}


function location_cities_list_ng_ni() {
  return array(
    "2317569" => "Zungeru",
    "2322263" => "Tegina",
    "2322794" => "Suleja",
    "2324504" => "Rijau",
    "2329981" => "Mokwa",
    "2330100" => "Minna",
    "2332249" => "Lapai",
    "2334008" => "Kontagora",
    "2339293" => "Ibeto",
    "2347209" => "Bida",
    "2347592" => "Baro",
    "2348507" => "Babana",
  );
}


function location_cities_list_ng_og() {
  return array(
    "2323411" => "Shagamu",
    "2337379" => "Iperu",
    "2337759" => "Ilaro",
    "2338400" => "Ijebu-Ode",
    "2338403" => "Ijebu-Igbo",
    "2338876" => "Ifo",
    "2352356" => "Ado Odo",
    "2352947" => "Abeokuta",
  );
}


function location_cities_list_ng_on() {
  return array(
    "2325314" => "Owo",
    "2326171" => "Ondo",
    "2328090" => "Ode",
    "2339150" => "Idanre",
    "2350841" => "Akure",
  );
}


function location_cities_list_ng_os() {
  return array(
    "2325249" => "Oyan",
    "2325506" => "Otan Aiyegbaju",
    "2325590" => "Osogbo",
    "2326302" => "Olupona",
    "2327223" => "Oke Mesi",
    "2330028" => "Modakeke",
    "2336905" => "Iwo",
    "2337490" => "Inisa",
    "2337659" => "Ilobu",
    "2337704" => "Ilesa",
    "2337765" => "Ila Orangun",
    "2338269" => "Ikirun",
    "2338273" => "Ikire",
    "2338401" => "Ijebu Ijesha",
    "2341355" => "Gbongan",
    "2343784" => "Ejigbo",
    "2343983" => "Effon Alaiye",
    "2349558" => "Apomu",
  );
}


function location_cities_list_ng_oy() {
  return array(
    "2323390" => "Saki",
    "2325200" => "Oyo",
    "2325733" => "Orita Eruwa",
    "2332357" => "Lalupon",
    "2334327" => "Kishi",
    "2338669" => "Igbo Ora",
    "2338711" => "Igboho",
    "2338772" => "Igbeti",
    "2339354" => "Ibadan",
    "2342628" => "Fiditi",
  );
}


function location_cities_list_ng_pl() {
  return array(
    "2325060" => "Pankshin",
    "2335953" => "Jos",
    "2346561" => "Bukuru",
  );
}


function location_cities_list_ng_ri() {
  return array(
    "2324774" => "Port Harcourt",
    "2326899" => "Okrika",
    "2328185" => "Obonoma",
    "2343512" => "Elele",
    "2346615" => "Buguma",
    "2346812" => "Bonny",
    "2591159" => "Degema Hulk",
  );
}


function location_cities_list_ng_so() {
  return array(
    "2322495" => "Tambawel",
    "2322911" => "Sokoto",
    "2337680" => "Illela",
    "2339892" => "Gwadabawa",
  );
}


function location_cities_list_ng_ta() {
  return array(
    "2318921" => "Wukari",
    "2336589" => "Jalingo",
    "2339287" => "Ibi",
    "2341275" => "Gembu",
    "2347330" => "Beli",
  );
}


function location_cities_list_ng_an() {
  return array(
    "2320920" => "Uga",
    "2325161" => "Ozubulu",
    "2326016" => "Onitsha",
    "2328765" => "Nnewi",
    "2328811" => "Nkpor",
    "2338497" => "Ihiala",
    "2338640" => "Igbo-Ukwu",
    "2343270" => "Enugu-Ukwu",
    "2348773" => "Awka",
    "2351740" => "Agulu",
  );
}


function location_cities_list_ng_yo() {
  return array(
    "2324767" => "Potiskum",
    "2328952" => "Nguru",
    "2333490" => "Kumagunnam",
    "2341294" => "Geidam",
    "2341656" => "Gashua",
    "2345096" => "Daura",
    "2345521" => "Damaturu",
  );
}


function location_cities_list_ng_za() {
  return array(
    "2322529" => "Talata Mafara",
    "2329920" => "Moriki",
    "2334756" => "Kaura Namoda",
    "2339937" => "Gusau",
    "2340086" => "Gummi",
  );
}
