<?php


function location_cities_list_al_01() {
  return array(
    "3185060" => "Kucove",
    "3186084" => "Berat",
  );
}


function location_cities_list_al_09() {
  return array(
    "783493" => "Burrel",
  );
}


function location_cities_list_al_02() {
  return array(
    "3185082" => "Kruje",
    "3185728" => "Durres",
  );
}


function location_cities_list_al_03() {
  return array(
    "783263" => "Elbasan",
  );
}


function location_cities_list_al_04() {
  return array(
    "3184517" => "Patos Fshat",
    "3184862" => "Lushnje",
    "3185670" => "Fier-Cifci",
    "3185672" => "Fier",
  );
}


function location_cities_list_al_05() {
  return array(
    "783148" => "Gjirokaster",
  );
}


function location_cities_list_al_06() {
  return array(
    "782756" => "Korce",
  );
}


function location_cities_list_al_07() {
  return array(
    "782661" => "Kukes",
  );
}


function location_cities_list_al_08() {
  return array(
    "3184935" => "Lezhe",
    "3185012" => "Lac",
  );
}


function location_cities_list_al_10() {
  return array(
    "3184081" => "Shkoder",
  );
}


function location_cities_list_al_11() {
  return array(
    "3183875" => "Tirana",
    "3185211" => "Kavaje",
  );
}


function location_cities_list_al_12() {
  return array(
    "363243"  => "Sarande",
    "3183719" => "Vlore",
  );
}
