<?php


function location_cities_list_gr_i() {
  return array(
    "251780"  => t("Voula"),
    "251948"  => t("Vyronas"),
    "254144"  => t("Salamis"),
    "255274"  => t("Piraeus"),
    "255377"  => t("Petroupolis"),
    "255524"  => t("Peristeri"),
    "255588"  => t("Perama"),
    "256075"  => t("Palaio Faliro"),
    "256429"  => t("Nikaia"),
    "256575"  => t("Nea Smyrni"),
    "256601"  => t("Ilion"),
    "256614"  => t("Nea Ionia"),
    "256621"  => t("Nea Filadelfeia"),
    "256622"  => t("Nea Erythraia"),
    "256750"  => t("Moskhaton"),
    "257302"  => t("Melissia"),
    "257365"  => t("Megara"),
    "259251"  => t("Koropi"),
    "259824"  => t("Kifisia"),
    "259949"  => t("Cholargos"),
    "260172"  => t("Khalandrion"),
    "260204"  => t("Keratsini"),
    "261414"  => t("Kallithea"),
    "261614"  => t("Alimos"),
    "261678"  => t("Kaisariani"),
    "261743"  => t("Irakleio"),
    "262135"  => t("Galatsi"),
    "262719"  => t("Elliniko"),
    "262752"  => t("Elefsina"),
    "264111"  => t("Agia Varvara"),
    "264194"  => t("Agia Paraskevi"),
    "264371"  => t("Athens"),
    "264445"  => t("Aspropyrgos"),
    "264888"  => t("Ano Liosia"),
    "265243"  => t("Marousi"),
    "265488"  => t("Acharnes"),
    "265533"  => t("Aigaleo"),
    "6324534" => t("Vrilissia"),
    "7522530" => t("Marousi"),
  );
}


function location_cities_list_gr_h() {
  return array(
    "252910" => t("Thivai"),
    "258463" => t("Livadeia"),
    "258620" => t("Lamia"),
    "260133" => t("Chalkida"),
  );
}


function location_cities_list_gr_b() {
  return array(
    "733776" => t("Giannitsa"),
    "733905" => t("Veroia"),
    "734077" => t("Thessaloniki"),
    "734301" => t("Sykies"),
    "734330" => t("Serres"),
    "734538" => t("Polichni"),
    "734643" => t("Pylaia"),
    "734712" => t("Peraia"),
    "734771" => t("Panorama"),
    "734883" => t("Oraiokastro"),
    "735030" => t("Naousa"),
    "735215" => t("Menemeni"),
    "735736" => t("Kilkis"),
    "735914" => t("Katerini"),
    "736083" => t("Kalamaria"),
    "736357" => t("Edessa"),
  );
}


function location_cities_list_gr_m() {
  return array(
    "254352" => t("Rethymno"),
    "260114" => t("Chania"),
    "261745" => t("Irakleion"),
  );
}


function location_cities_list_gr_a() {
  return array(
    "733840" => t("Xanthi"),
    "734880" => t("Orestiada"),
    "735640" => t("Komotini"),
    "735861" => t("Kavala"),
    "736364" => t("Drama"),
    "736928" => t("Alexandroupoli"),
  );
}


function location_cities_list_gr_d() {
  return array(
    "254698" => t("Preveza"),
    "261779" => t("Ioannina"),
    "264559" => t("Arta"),
  );
}


function location_cities_list_gr_f() {
  return array(
    "2463679" => t("Kerkyra"),
  );
}


function location_cities_list_gr_69() {
  return array();
}


function location_cities_list_gr_k() {
  return array(
    "256866" => t("Mytilini"),
    "259973" => t("Chios"),
  );
}


function location_cities_list_gr_j() {
  return array(
    "252601" => t("Tripoli"),
    "253394" => t("Sparti"),
    "259289" => t("Korinthos"),
    "261604" => t("Kalamata"),
    "264670" => t("Argos"),
  );
}


function location_cities_list_gr_l() {
  return array(
    "259245" => t("Kos"),
    "400666" => t("Rodos"),
  );
}


function location_cities_list_gr_e() {
  return array(
    "251833" => t("Volos"),
    "252664" => t("Trikala"),
    "258576" => t("Larisa"),
    "260989" => t("Karditsa"),
  );
}


function location_cities_list_gr_g() {
  return array(
    "255229" => t("Pyrgos"),
    "255683" => t("Patra"),
    "256639" => t("Nafpaktos"),
    "265252" => t("Amaliada"),
    "265500" => t("Aigio"),
    "265560" => t("Agrinio"),
  );
}


function location_cities_list_gr_c() {
  return array(
    "734426" => t("Ptolemaida"),
    "735563" => t("Kozani"),
    "736229" => t("Florina"),
  );
}
