<?php

function location_cities_list_af_bds () {
	return array (
		"1142170" => t("Fayzabad"),
	);
}


function location_cities_list_af_bdg () {
	return array (
		"1141089" => t("Ghormach"),
	);
}


function location_cities_list_af_bal () {
	return array (
		"1133616" => t("Mazar-e Sharif"),
		"1136575" => t("Khulm"),
		"1147290" => t("Balkh"),
	);
}


function location_cities_list_af_fra () {
	return array (
		"1142264" => t("Farah"),
	);
}


function location_cities_list_af_fyb () {
	return array (
		"1133453" => t("Maymana"),
		"1148658" => t("Andkhoy"),
	);
}


function location_cities_list_af_gho () {
	return array (
		"1125896" => t("Shahrak"),
	);
}


function location_cities_list_af_hel () {
	return array (
		"1134720" => t("Lashkar Gah"),
		"1141540" => t("Gereshk"),
	);
}


function location_cities_list_af_her () {
	return array (
		"1125155" => t("Shindand"),
		"1135158" => t("Kushk"),
		"1137807" => t("Karukh"),
		"1140026" => t("Herat"),
		"1142404" => t("Kafir Qala"),
	);
}


function location_cities_list_af_kab () {
	return array (
		"1131316" => t("Paghman"),
		"1138958" => t("Kabul"),
	);
}


function location_cities_list_af_kan () {
	return array (
		"1138336" => t("Kandahar"),
	);
}


function location_cities_list_af_kdz () {
	return array (
		"1129648" => t("Qarawul"),
		"1135689" => t("Kunduz"),
		"1137168" => t("Khanabad"),
	);
}


function location_cities_list_af_nan () {
	return array (
		"1139715" => t("Jalalabad"),
		"1469706" => t("Markaz-e Woluswali-ye Achin"),
	);
}


function location_cities_list_af_oru () {
	return array (
	);
}


function location_cities_list_af_pia () {
	return array (
		"1141857" => t("Gardez"),
	);
}


function location_cities_list_af_pan () {
	return array (
		"1429434" => t("Bazarak"),
	);
}


function location_cities_list_af_par () {
	return array (
		"1139807" => t("Jabal os Saraj"),
		"1145352" => t("Charikar"),
	);
}


function location_cities_list_af_sam () {
	return array (
		"1127768" => t("Aibak"),
	);
}


function location_cities_list_af_sar () {
	return array (
		"1127110" => t("Sar-e Pul"),
		"1127628" => t("Sang-e Charak"),
	);
}


function location_cities_list_af_kho () {
	return array (
		"1136469" => t("Khost"),
	);
}


function location_cities_list_af_nur () {
	return array (
	);
}


function location_cities_list_af_war () {
	return array (
	);
}


function location_cities_list_af_bgl () {
	return array (
		"1130490" => t("Pul-e Khumri"),
		"1132495" => t("Nahrin"),
		"1147540" => t("Baghlan"),
	);
}


function location_cities_list_af_bam () {
	return array (
		"1147242" => t("Bamyan"),
		"6692413" => t("Cool urhajo"),
	);
}


function location_cities_list_af_day () {
	return array (
		"1131833" => t("Nili"),
	);
}


function location_cities_list_af_gha () {
	return array (
		"1141269" => t("Ghazni"),
	);
}


function location_cities_list_af_jow () {
	return array (
		"1125444" => t("Shibirghan"),
		"1129516" => t("Qarqin"),
	);
}


function location_cities_list_af_knr () {
	return array (
		"1148205" => t("Asmar"),
		"1148311" => t("Asadabad"),
	);
}


function location_cities_list_af_kap () {
	return array (
	);
}


function location_cities_list_af_lag () {
	return array (
		"1133574" => t("Mehtar Lam"),
	);
}


function location_cities_list_af_low () {
	return array (
		"1147066" => t("Baraki Barak"),
	);
}


function location_cities_list_af_nim () {
	return array (
		"1120985" => t("Zaranj"),
		"1136863" => t("Khash"),
	);
}


function location_cities_list_af_pka () {
	return array (
	);
}


function location_cities_list_af_tak () {
	return array (
		"1123004" => t("Taloqan"),
		"1128265" => t("Rustaq"),
		"1148106" => t("Art Khwajah"),
	);
}


function location_cities_list_af_zab () {
	return array (
	);
}
