<?php

function location_cities_list_er_an () {
	return array (
		"333287" => t("Keren"),
	);
}


function location_cities_list_er_du () {
	return array (
		"344901" => t("Mendefera"),
	);
}


function location_cities_list_er_gb () {
	return array (
		"342711" => t("Barentu"),
	);
}


function location_cities_list_er_ma () {
	return array (
		"343300" => t("Asmara"),
	);
}


function location_cities_list_er_sk () {
	return array (
		"330546" => t("Massawa"),
	);
}


function location_cities_list_er_dk () {
	return array (
		"343386" => t("Assab"),
	);
}
