<?php


function location_cities_list_mh_007 () {
	return array (
	);
}


function location_cities_list_mh_all () {
	return array (
	);
}


function location_cities_list_mh_alk () {
	return array (
	);
}


function location_cities_list_mh_arn () {
	return array (
	);
}


function location_cities_list_mh_aur () {
	return array (
	);
}


function location_cities_list_mh_060 () {
	return array (
	);
}


function location_cities_list_mh_070 () {
	return array (
	);
}


function location_cities_list_mh_073 () {
	return array (
	);
}


function location_cities_list_mh_ebo () {
	return array (
	);
}


function location_cities_list_mh_eni () {
	return array (
	);
}


function location_cities_list_mh_100 () {
	return array (
	);
}


function location_cities_list_mh_jab () {
	return array (
	);
}


function location_cities_list_mh_jal () {
	return array (
	);
}


function location_cities_list_mh_130 () {
	return array (
	);
}


function location_cities_list_mh_kil () {
	return array (
	);
}


function location_cities_list_mh_kwa () {
	return array (
	);
}


function location_cities_list_mh_lae () {
	return array (
	);
}


function location_cities_list_mh_lib () {
	return array (
	);
}


function location_cities_list_mh_lik () {
	return array (
	);
}


function location_cities_list_mh_maj () {
	return array (
		"2113779" => t("Majuro"),
		"7874852" => t("RMI Capitol"),
	);
}


function location_cities_list_mh_mal () {
	return array (
	);
}


function location_cities_list_mh_mej () {
	return array (
	);
}


function location_cities_list_mh_mil () {
	return array (
	);
}


function location_cities_list_mh_nmk () {
	return array (
	);
}


function location_cities_list_mh_nmu () {
	return array (
	);
}


function location_cities_list_mh_ron () {
	return array (
	);
}


function location_cities_list_mh_360 () {
	return array (
	);
}


function location_cities_list_mh_385 () {
	return array (
	);
}


function location_cities_list_mh_uja () {
	return array (
	);
}


function location_cities_list_mh_400 () {
	return array (
	);
}


function location_cities_list_mh_uti () {
	return array (
	);
}


function location_cities_list_mh_wth () {
	return array (
	);
}


function location_cities_list_mh_wtj () {
	return array (
	);
}
