<?php


function location_cities_list_vu_map () {
	return array (
	);
}


function location_cities_list_vu_pam () {
	return array (
	);
}


function location_cities_list_vu_sam () {
	return array (
	);
}


function location_cities_list_vu_see () {
	return array (
		"2135171" => t("Port-Vila"),
	);
}


function location_cities_list_vu_tae () {
	return array (
	);
}


function location_cities_list_vu_tob () {
	return array (
	);
}
