<?php

function location_cities_list_tm_b () {
	return array (
		"161616" => t("Balkanabat"),
		"161974" => t("Gazanjyk"),
		"161943" => t("Gumdag"),
		"601594" => t("Turkmenbasy"),
	);
}


function location_cities_list_tm_a () {
	return array (
		"162183" => t("Ashgabat"),
		"162158" => t("Baherden"),
		"162099" => t("Buzmeyin"),
		"1218239" => t("Tejen"),
	);
}


function location_cities_list_tm_d () {
	return array (
		"601734" => t("Dasoguz"),
	);
}


function location_cities_list_tm_l () {
	return array (
		"1219002" => t("Atamyrat"),
		"1219392" => t("Gowurdak"),
		"1218436" => t("Sayat"),
		"1219649" => t("Turkmenabat"),
	);
}


function location_cities_list_tm_m () {
	return array (
		"1219762" => t("Bayramaly"),
		"1218667" => t("Mary"),
	);
}


