<?php

function location_cities_list_rw_02 () {
	return array (
		"201463" => t("Rwamagana"),
		"202068" => t("Kibungo"),
	);
}


function location_cities_list_rw_01 () {
	return array (
		"202061" => t("Kigali"),
	);
}


function location_cities_list_rw_03 () {
	return array (
		"201521" => t("Musanze"),
		"203104" => t("Byumba"),
	);
}


function location_cities_list_rw_05 () {
	return array (
		"201865" => t("Nzega"),
		"202217" => t("Gitarama"),
		"203112" => t("Butare"),
	);
}


function location_cities_list_rw_04 () {
	return array (
		"202065" => t("Kibuye"),
		"202326" => t("Cyangugu"),
		"202905" => t("Gisenyi"),
	);
}
