<?php


function location_cities_list_mx_agu() {
  return array(
    "3988651" => "Rincon de Romos",
    "4016086" => "Calvillo",
    "4019233" => "Aguascalientes",
  );
}


function location_cities_list_mx_bcs() {
  return array(
    "3985710" => "Cabo San Lucas",
    "3986172" => "San Jose del Cabo",
    "4000900" => "La Paz",
    "4013723" => "Ciudad Constitucion",
  );
}


function location_cities_list_mx_cam() {
  return array(
    "3527795" => "Escarcega",
    "3530599" => "Ciudad del Carmen",
    "3531177" => "Champoton",
    "3531732" => "Campeche",
  );
}


function location_cities_list_mx_chp() {
  return array(
    "3514785" => "Venustiano Carranza",
    "3515001" => "Tuxtla Gutierrez",
    "3516266" => "Tapachula",
    "3519537" => "San Cristobal de Las Casas",
    "3521476" => "Pijijiapan",
    "3522164" => "Palenque",
    "3522444" => "Ocozocuautla",
    "3522484" => "Ocosingo",
    "3522926" => "Motozintla de Mendoza",
    "3523590" => "Mapastepec",
    "3524744" => "Las Margaritas",
    "3526855" => "Huixtla",
    "3527542" => "Frontera Comalapa",
    "3530367" => "Comitan de Dominguez",
    "3530617" => "Cintalapa de Figueroa",
    "3531013" => "Chiapa de Corzo",
    "3532254" => "Berriozabal",
    "3816721" => "Tonala",
    "3816739" => "Arriaga",
  );
}


function location_cities_list_mx_chh() {
  return array(
    "3994469" => "Ojinaga",
    "3994616" => "Nuevo Casas Grandes",
    "3996234" => "Pedro Meoqui",
    "3996956" => "Madera",
    "4003938" => "Jimenez",
    "4004867" => "Hidalgo del Parral",
    "4012406" => "Cuauhtemoc",
    "4013708" => "Ciudad Juarez",
    "4013720" => "Ciudad Delicias",
    "4013724" => "Ciudad Camargo",
    "4014338" => "Chihuahua",
  );
}


function location_cities_list_mx_coa() {
  return array(
    "3980180" => "Ciudad Frontera",
    "3981254" => "Torreon",
    "3985129" => "San Pedro",
    "3987500" => "San Buenaventura",
    "3988086" => "Saltillo",
    "3988333" => "Ciudad Sabinas",
    "3991043" => "Ramos Arizpe",
    "3992619" => "Piedras Negras",
    "3993335" => "Parras de la Fuente",
    "3993893" => "Palau",
    "3994667" => "Nueva Rosita",
    "3995050" => "Nava",
    "3995523" => "Monclova",
    "3996271" => "Melchor Muzquiz",
    "3996426" => "Matamoros",
    "4013728" => "Ciudad Acuna",
    "4015022" => "Castanos",
    "4018761" => "Allende",
  );
}


function location_cities_list_mx_col() {
  return array(
    "3980194" => "Ciudad de Villa de Alvarez",
    "3982213" => "Tecoman",
    "3996663" => "Manzanillo",
    "4013516" => "Colima",
    "4018227" => "Armeria",
  );
}


function location_cities_list_mx_dur() {
  return array(
    "3983631" => "Santiago Papasquiaro",
    "3985327" => "San Miguel de Papasquiaro",
    "4005775" => "Gomez Palacio",
    "4007676" => "El Salto",
    "4011743" => "Victoria de Durango",
    "4013706" => "Ciudad Lerdo",
  );
}


function location_cities_list_mx_bcn() {
  return array(
    "3979505" => "Guadalupe Victoria",
    "3981609" => "Tijuana",
    "3982266" => "Tecate",
    "3984237" => "Santa Isabel",
    "3987224" => "San Felipe",
    "3988392" => "Rosarito",
    "3996069" => "Mexicali",
    "3996737" => "Rodolfo Sanchez Taboada",
    "4006702" => "Ensenada",
  );
}


function location_cities_list_mx_mex() {
  return array(
    "3513966" => "Zumpango de Ocampo",
    "3514409" => "Xonacatlan",
    "3514519" => "San Miguel Xico",
    "3514683" => "Villa Cuauhtemoc",
    "3515042" => "Tultitlan",
    "3515044" => "Tultepec",
    "3515302" => "Toluca de Lerdo",
    "3515431" => "Tlalnepantla",
    "3515679" => "Tianguistenco",
    "3515715" => "Texcoco de Mora",
    "3515794" => "Tequixquiac",
    "3515807" => "Cuautitlan Izcalli",
    "3515827" => "Tepotzotlan",
    "3515942" => "Teoloyucan",
    "3515993" => "Tenango de Arista",
    "3517270" => "Santa Maria Chimalhuacan",
    "3517524" => "Santa Cruz Tecamac",
    "3517832" => "San Salvador Atenco",
    "3518135" => "San Pablo de las Salinas",
    "3518138" => "San Pablo Autopan",
    "3518221" => "San Miguel Zinacantepec",
    "3518277" => "San Miguel Coatlinchan",
    "3518387" => "San Mateo Atenco",
    "3518618" => "San Juan Teotihuacan",
    "3519290" => "San Francisco Acuautla",
    "3522232" => "Ozumba de Alzate",
    "3522445" => "Ocoyoacac",
    "3522732" => "Nicolas Romero",
    "3522790" => "Naucalpan de Juarez",
    "3523303" => "Metepec",
    "3523900" => "Los Reyes Acozac",
    "3523908" => "Los Reyes",
    "3524389" => "Lerma de Villada",
    "3526681" => "Ixtapan de la Sal",
    "3526682" => "Ixtapaluca",
    "3529612" => "Ecatepec",
    "3529986" => "Cuautitlan",
    "3530123" => "Coyotepec",
    "3530569" => "Coacalco",
    "3530589" => "Ciudad Nezahualcoyotl",
    "3530932" => "Chiconcuac",
    "3530937" => "San Vicente Chicoloapan",
    "3531007" => "Chiautla",
    "3531200" => "Chalco de Diaz Covarrubias",
    "3531598" => "Capulhuac",
    "3532617" => "Atlacomulco",
    "3532624" => "Ciudad Lopez Mateos",
    "3532899" => "Amecameca de Juarez",
    "3827254" => "San Mateo Otzacatipan",
    "3827256" => "San Maria Totoltepec",
    "3827414" => "Huixquilucan",
    "3827586" => "Melchor Ocampo",
    "3827588" => "Huilango",
    "3827596" => "Santiago Teyahualco",
    "3827598" => "Ojo de Agua",
    "3827606" => "Buenavista",
    "3980621" => "Valle de Bravo",
    "3982121" => "Tejupilco de Hidalgo",
    "7280711" => "Colonia Lindavista",
  );
}


function location_cities_list_mx_ver() {
  return array(
    "3514518" => "Xico",
    "3514783" => "Veracruz",
    "3515011" => "Tuxpan de Rodriguez Cano",
    "3515386" => "Tlapacoyan",
    "3516053" => "Temapache",
    "3516271" => "Tantoyuca",
    "3516912" => "Santiago Tuxtla",
    "3519907" => "San Andres Tuxtla",
    "3520274" => "Rio Blanco",
    "3521168" => "Poza Rica de Hidalgo",
    "3521628" => "Perote",
    "3521922" => "Papantla de Olarte",
    "3521941" => "Panuco",
    "3522307" => "Orizaba",
    "3522696" => "Nogales",
    "3522804" => "Naranjos",
    "3522845" => "Nanchital",
    "3523141" => "Misantla",
    "3523183" => "Minatitlan",
    "3523513" => "Martinez de La Torre",
    "3524391" => "Lerdo de Tejada",
    "3524903" => "Las Choapas",
    "3525596" => "La Isla",
    "3526617" => "Xalapa de Enriquez",
    "3526696" => "Ixtac Zoquitlan",
    "3526993" => "Huatusco de Chicuellar",
    "3527596" => "Fortin de las Flores",
    "3530167" => "Cosoleacaque",
    "3530177" => "Cosamaloapan de Carpio",
    "3530240" => "Cordoba",
    "3530513" => "Coatzintla",
    "3530517" => "Coatzacoalcos",
    "3530531" => "Coatepec",
    "3530592" => "Ciudad Mendoza",
    "3531321" => "Cerro Azul",
    "3531416" => "Catemaco",
    "3531556" => "Carlos A. Carrillo",
    "3532414" => "Banderilla",
    "3532964" => "Alvarado",
    "3532969" => "Altotonga",
    "3533056" => "Allende",
    "3533107" => "Alamo",
    "3533269" => "Agua Dulce",
    "3533426" => "Acayucan",
    "3824536" => "Alto Lucero",
    "3824741" => "Misantla",
  );
}


function location_cities_list_mx_gua() {
  return array(
    "3979855" => "Yuriria",
    "3980174" => "Villagran",
    "3980605" => "Valle de Santiago",
    "3980777" => "Uriangato",
    "3983058" => "Silao",
    "3985344" => "San Miguel de Allende",
    "3985620" => "San Luis de la Paz",
    "3986088" => "San Jose Iturbide",
    "3986984" => "San Francisco del Rincon",
    "3987246" => "San Felipe",
    "3988050" => "Salvatierra",
    "3988214" => "Salamanca",
    "3988462" => "Romita",
    "3992986" => "Penjamo",
    "3995343" => "Moroleon",
    "3996299" => "Medina",
    "3996595" => "Marfil",
    "3998655" => "Leon",
    "4003662" => "Juventino Rosas",
    "4004092" => "Jaral del Progreso",
    "4004330" => "Irapuato",
    "4005270" => "Guanajuato",
    "4012721" => "Cortazar",
    "4013094" => "Comonfort",
    "4014875" => "Celaya",
    "4018403" => "Apaseo el Grande",
    "4018404" => "Apaseo el Alto",
    "4019827" => "Acambaro",
    "4019869" => "Abasolo",
    "4023117" => "Dolores Hidalgo Cuna de la Independencia Nacional",
  );
}


function location_cities_list_mx_gro() {
  return array(
    "3513967" => "Zumpango del Rio",
    "3515384" => "Tlapa de Comonfort",
    "3515510" => "Tixtla de Guerrero",
    "3516060" => "Teloloapan",
    "3516225" => "Taxco de Alarcon",
    "3522343" => "Ometepec",
    "3523683" => "Malinaltepec",
    "3526798" => "Iguala de la Independencia",
    "3526864" => "Huitzuco de los Figueroa",
    "3530870" => "Chilpancingo de los Bravos",
    "3530886" => "Chilapa de Alvarez",
    "3533462" => "Acapulco de Juarez",
    "3979673" => "Zihuatanejo",
    "3985621" => "San Luis de la Paz",
    "3992842" => "Petatlan",
    "4013727" => "Ciudad Altamirano",
    "4017984" => "Atoyac de Alvarez",
    "4018320" => "Arcelia",
    "4025652" => "Ciudad Altamirano",
  );
}


function location_cities_list_mx_hid() {
  return array(
    "3514134" => "Zacualtipan",
    "3515062" => "Tulancingo",
    "3515064" => "Tula de Allende",
    "3515505" => "Tizayuca",
    "3515690" => "Tezontepec de Aldama",
    "3515887" => "Tepeji de Ocampo",
    "3516982" => "Santiago Tulantepec",
    "3521103" => "Progreso de Obregon",
    "3522210" => "Pachuca de Soto",
    "3523127" => "Mixquiahuala",
    "3526708" => "Ixmiquilpan",
    "3526952" => "Huejutla de Reyes",
    "3529989" => "Cuautepec de Hinojosa",
    "3530587" => "Ciudad Sahagun",
    "3532815" => "Apan",
    "3533389" => "Actopan",
  );
}


function location_cities_list_mx_jal() {
  return array(
    "3976999" => "Cihuatlan",
    "3979717" => "Zapotlanejo",
    "3979727" => "Zapotiltic",
    "3979770" => "Zapopan",
    "3979822" => "Zacoalco de Torres",
    "3980844" => "Tuxpan",
    "3981369" => "Tonala",
    "3981461" => "Tlaquepaque",
    "3981467" => "Tlajomulco de Zuniga",
    "3981791" => "Tesistan",
    "3981885" => "Tequila",
    "3981984" => "Tepatitlan de Morelos",
    "3982034" => "Teocaltiche",
    "3982567" => "Tamazula de Gordiano",
    "3982616" => "Tala",
    "3983216" => "Sayula",
    "3983217" => "Sayula",
    "3984680" => "Santa Anita",
    "3984791" => "San Sebastian el Grande",
    "3985323" => "San Miguel el Alto",
    "3985865" => "San Juan de los Lagos",
    "3988025" => "Nicolas R Casillas",
    "3991328" => "Puerto Vallarta",
    "3994489" => "Ocotlan",
    "3994604" => "Nuevo Mexico",
    "3999325" => "Las Pintas de Arriba",
    "4002224" => "Lagos de Moreno",
    "4003526" => "La Barca",
    "4003908" => "Jocotepec",
    "4004126" => "Jamay",
    "4004153" => "Jalostotitlan",
    "4004293" => "Ixtapa",
    "4005539" => "Guadalajara",
    "4006783" => "Encarnacion de Diaz",
    "4007684" => "El Salto",
    "4009697" => "El Grullo",
    "4013714" => "Ciudad Guzman",
    "4014553" => "Chapala",
    "4017957" => "Autlan de Navarro",
    "4017992" => "Atotonilco el Alto",
    "4018348" => "Arandas",
    "4018582" => "Ameca",
  );
}


function location_cities_list_mx_mic() {
  return array(
    "3979802" => "Zamora de Hidalgo",
    "3979846" => "Zacapu",
    "3979856" => "Yurecuaro",
    "3980760" => "Uruapan del Progreso",
    "3982007" => "Tepalcatepec",
    "3982545" => "Tangancicuaro de Arista",
    "3982693" => "Tacambaro de Codallos",
    "3988258" => "Sahuayo de Morelos",
    "3991219" => "Puruandiro",
    "3993179" => "Patzcuaro",
    "3993457" => "Paracho de Verduzco",
    "3994674" => "Nueva Italia de Ruiz",
    "3995402" => "Morelia",
    "3996626" => "Maravatio",
    "4000821" => "La Piedad Cavadas",
    "4001056" => "La Orilla",
    "4003923" => "Jiquilpan de Juarez",
    "4004555" => "Huetamo de Nunez",
    "4004885" => "Heroica Zitacuaro",
    "4013712" => "Ciudad Hidalgo",
    "4018400" => "Apatzingan de la Constitucion",
    "4026075" => "Las Guacamayas",
    "4026082" => "Lazaro Cardenas",
  );
}


function location_cities_list_mx_mor() {
  return array(
    "3514163" => "Zacatepec",
    "3514278" => "Yecapixtla",
    "3514321" => "Yautepec",
    "3514398" => "Xoxocotla",
    "3514437" => "Xochitepec",
    "3515373" => "Tlaquiltenango",
    "3515811" => "Tepoztlan",
    "3516035" => "Temixco",
    "3521051" => "Puente de Ixtla",
    "3526467" => "Jojutla",
    "3526485" => "Jiutepec",
    "3527879" => "Emiliano Zapata",
    "3529947" => "Cuernavaca",
    "3529982" => "Cuautla Morelos",
    "3532545" => "Axochiapan",
  );
}


function location_cities_list_mx_nay() {
  return array(
    "3981941" => "Tepic",
    "3983636" => "Santiago Ixcuintla",
    "4004267" => "Ixtlan del Rio",
    "4013085" => "Compostela",
    "4019819" => "Acaponeta",
  );
}


function location_cities_list_mx_nle() {
  return array(
    "3523011" => "Montemorelos",
    "3524348" => "Linares",
    "3531865" => "Cadereyta",
    "3792044" => "Hidalgo",
    "3980190" => "Villa de Garcia",
    "3983671" => "Santiago",
    "3984583" => "Santa Catarina",
    "3985241" => "San Nicolas de los Garza",
    "3988327" => "Sabinas Hidalgo",
    "3995465" => "Monterrey",
    "4005492" => "Guadalupe",
    "4005867" => "General Escobedo",
    "4005937" => "Garza Garcia",
    "4013726" => "Ciudad Anahuac",
    "4018390" => "Apodaca",
    "4018762" => "Allende",
    "4022908" => "Anahuac",
  );
}


function location_cities_list_mx_oax() {
  return array(
    "3516843" => "Santo Domingo Tehuantepec",
    "3516926" => "Santiago Pinotepa Nacional",
    "3517517" => "Santa Cruz Xoxocotlan",
    "3518723" => "San Juan Bautista Tuxtepec",
    "3520064" => "Salina Cruz",
    "3520994" => "Puerto Escondido",
    "3522507" => "Oaxaca",
    "3523240" => "Miahuatlan de Porfirio Diaz",
    "3523450" => "Matias Romero",
    "3526357" => "Juchitan de Zaragoza",
    "3526674" => "San Jeronimo Ixtepec",
    "3527023" => "Ciudad de Huajuapam de Leon",
    "3762770" => "San Antonio de la Cal",
  );
}


function location_cities_list_mx_pue() {
  return array(
    "3514148" => "Zacatlan",
    "3514510" => "Xicotepec de Juarez",
    "3515358" => "Tlaxcalancingo",
    "3515696" => "Teziutlan",
    "3515904" => "Tepeaca",
    "3515906" => "Tepatlaxco de Hidalgo",
    "3516109" => "Tehuacan",
    "3516188" => "Tecamachalco",
    "3517231" => "Santa Maria Moyotzingo",
    "3517831" => "San Salvador el Seco",
    "3518407" => "San Martin Texmelucan de Labastida",
    "3519531" => "Sanctorum",
    "3521081" => "Puebla de Zaragoza",
    "3522118" => "Palmarito Tochapan",
    "3523061" => "Santiago Momoxpan",
    "3526657" => "Izucar de Matamoros",
    "3526953" => "Huejotzingo",
    "3526992" => "Huauchinango",
    "3529981" => "Cuautlancingo",
    "3530584" => "Ciudad Serdan",
    "3530757" => "Cholula",
    "3530908" => "Chignahuapan",
    "3532592" => "Atlixco",
    "3532881" => "Amozoc de Mota",
    "3532989" => "Altepexi",
    "3533126" => "Ajalpan",
    "3533433" => "Acatzingo de Hidalgo",
    "3533440" => "Acatlan de Osorio",
    "3533486" => "Acajete",
    "3818742" => "San Andres Cholula",
  );
}


function location_cities_list_mx_que() {
  return array(
    "3515796" => "Tequisquiapan",
    "3518692" => "San Juan del Rio",
    "3983820" => "Santa Rosa Jauregui",
    "3991164" => "Santiago de Queretaro",
    "4008303" => "El Pueblito",
  );
}


function location_cities_list_mx_roo() {
  return array(
    "3521342" => "Playa del Carmen",
    "3527639" => "Felipe Carrillo Puerto",
    "3530103" => "San Miguel de Cozumel",
    "3531023" => "Chetumal",
    "3531673" => "Cancun",
  );
}


function location_cities_list_mx_slp() {
  return array(
    "3516385" => "Tamazunchale",
    "3520235" => "Rio Verde",
    "3530582" => "Ciudad Valles",
    "3530596" => "Ciudad Fernandez",
    "3531574" => "Cardenas",
    "3982912" => "Soledad Diez Gutierrez",
    "3985606" => "San Luis Potosi",
    "3996387" => "Matehuala",
  );
}


function location_cities_list_mx_sin() {
  return array(
    "3976775" => "Gabriel Leyva Solano",
    "3995017" => "Navolato",
    "3996322" => "Mazatlan",
    "3997479" => "Los Mochis",
    "4005219" => "Guasave",
    "4005297" => "Guamuchil",
    "4005864" => "General Juan Jose Rios",
    "4006622" => "Escuinapa de Hidalgo",
    "4012176" => "Culiacan",
    "4012693" => "Villa de Costa Rica",
    "4015938" => "Campo Gobierno",
  );
}


function location_cities_list_mx_son() {
  return array(
    "3970972" => "Miguel Aleman (La Doce)",
    "3985604" => "San Luis Rio Colorado",
    "3991347" => "Puerto Penasco",
    "3995019" => "Navojoa",
    "3996893" => "Magdalena de Kino",
    "4004647" => "Huatabampo",
    "4004886" => "Nogales",
    "4004887" => "Heroica Caborca",
    "4004898" => "Hermosillo",
    "4005143" => "Guaymas",
    "4006806" => "Empalme",
    "4013704" => "Ciudad Obregon",
    "4015700" => "Cananea",
    "4019260" => "Agua Prieta",
  );
}


function location_cities_list_mx_tab() {
  return array(
    "3514670" => "Villahermosa",
    "3515956" => "Tenosique de Pino Suarez",
    "3516210" => "Teapa",
    "3521912" => "Paraiso",
    "3523791" => "Macuspana",
    "3526603" => "Jalpa de Mendez",
    "3526908" => "Huimanguillo",
    "3527545" => "Frontera",
    "3527880" => "Emiliano Zapata",
    "3529886" => "Cunduacan",
    "3530385" => "Comalcalco",
    "3531576" => "Cardenas",
    "3802739" => "Rio de Teapa",
  );
}


function location_cities_list_mx_tam() {
  return array(
    "3482969" => "Gustavo A. Madero",
    "3483197" => "San Fernando",
    "3514868" => "Valle Hermoso",
    "3516355" => "Tampico",
    "3520271" => "Rio Bravo",
    "3520339" => "Reynosa",
    "3522551" => "Nuevo Laredo",
    "3523149" => "Miramar",
    "3523466" => "Heroica Matamoros",
    "3528756" => "Ciudad Mante",
    "3530580" => "Ciudad Victoria",
    "3530590" => "Ciudad Miguel Aleman",
    "3530594" => "Ciudad Madero",
    "3533005" => "Altamira",
    "3824166" => "Tampico",
  );
}


function location_cities_list_mx_dif() {
  return array(
    "3514450" => "Xochimilco",
    "3514663" => "Alvaro Obregon",
    "3514674" => "Gustavo A. Madero",
    "3515428" => "Tlalpan",
    "3515463" => "Tlahuac",
    "3521305" => "Polanco",
    "3523202" => "Milpa Alta",
    "3523760" => "Magdalena Contreras",
    "3526683" => "Iztapalapa",
    "3526700" => "Iztacalco",
    "3530049" => "Cuajimalpa",
    "3530139" => "Coyoacan",
    "3530597" => "Mexico City",
    "3532497" => "Azcapotzalco",
    "3827406" => "Benito Juarez",
    "3827407" => "Venustiano Carranza",
    "3827408" => "Miguel Hidalgo",
    "3827409" => "Cuauhtemoc",
    "7280708" => "Colonia del Valle",
    "7280718" => "Colonia Nativitas",
  );
}


function location_cities_list_mx_tla() {
  return array(
    "3517742" => "Chiautempan",
    "3518475" => "Teolocholco",
    "3530276" => "San Bernardino Contla",
    "3531784" => "Calpulalpan",
    "3532792" => "Apizaco",
    "3815324" => "Huamantla",
    "3815392" => "Zacatelco",
    "3815415" => "Tlaxcala",
    "3815447" => "Papalotla",
    "3815453" => "Vicente Guerrero",
  );
}


function location_cities_list_mx_yuc() {
  return array(
    "3514876" => "Valladolid",
    "3514929" => "Uman",
    "3515504" => "Tizimin",
    "3515665" => "Ticul",
    "3516076" => "Tekax de Alvaro Obregon",
    "3521108" => "Progreso",
    "3521596" => "Peto",
    "3522251" => "Oxkutzcab",
    "3522924" => "Motul de Felipe Carrillo Puerto",
    "3523349" => "Merida",
    "3526323" => "Kanasin",
    "3526838" => "Hunucma",
    "3530978" => "Chichen-Itza",
  );
}


function location_cities_list_mx_zac() {
  return array(
    "3979844" => "Zacatecas",
    "3982887" => "Sombrerete",
    "3988594" => "Rio Grande",
    "3994912" => "Nochistlan",
    "3998291" => "Loreto",
    "4004024" => "Jerez de Garcia Salinas",
    "4005509" => "Guadalupe",
    "4006163" => "Fresnillo de Gonzalez Echeverria",
    "4016132" => "Victor Rosales",
  );
}
