<?php

function location_cities_list_lv_vmr () {
	return array (
		"453754" => t("Valmiera"),
	);
}


function location_cities_list_lv_106 () {
	return array (
		"454310" => t("Ventspils"),
	);
}


function location_cities_list_lv_lpx () {
	return array (
		"457954" => t("Liepaja"),
		"454432" => t("Vec-Liepaja"),
	);
}


function location_cities_list_lv_099 () {
	return array (
		"454768" => t("Tukums"),
	);
}


function location_cities_list_lv_087 () {
	return array (
		"455898" => t("Salaspils"),
	);
}


function location_cities_list_lv_rix () {
	return array (
		"456172" => t("Riga"),
	);
}


function location_cities_list_lv_rez () {
	return array (
		"456202" => t("Rezekne"),
	);
}


function location_cities_list_lv_067 () {
	return array (
		"457065" => t("Ogre"),
	);
}


function location_cities_list_lv_jur () {
	return array (
		"459201" => t("Jurmala"),
	);
}


function location_cities_list_lv_jel () {
	return array (
		"459279" => t("Jelgava"),
	);
}


function location_cities_list_lv_042 () {
	return array (
		"459283" => t("Jekabpils"),
	);
}


function location_cities_list_lv_025 () {
	return array (
		"460413" => t("Daugavpils"),
	);
}


function location_cities_list_lv_022 () {
	return array (
		"460570" => t("Cesis"),
	);
}


