<?php

function location_cities_list_om_sh () {
	return array (
		"286245" => t("Sur"),
	);
}


function location_cities_list_om_za () {
	return array (
		"287830" => t("`Ibri"),
		"411849" => t("Yanqul"),
	);
}


function location_cities_list_om_mu () {
	return array (
		"287614" => t("Khasab"),
	);
}


function location_cities_list_om_ba () {
	return array (
		"288789" => t("Barka'"),
		"289011" => t("Rustaq"),
	);
}


function location_cities_list_om_ma () {
	return array (
		"287286" => t("Muscat"),
		"288764" => t("Bawshar"),
		"288967" => t("As Sib al Jadidah"),
	);
}


function location_cities_list_om_11 () {
	return array (
		"286282" => t("Al Sohar"),
		"286402" => t("Shinas"),
		"286647" => t("Saham"),
		"288955" => t("As Suwayq"),
		"289174" => t("Al Liwa'"),
		"289199" => t("Al Khaburah"),
	);
}


function location_cities_list_om_12 () {
	return array (
		"287832" => t("Ibra'"),
		"288902" => t("Badiyah"),
	);
}


function location_cities_list_om_zu () {
	return array (
		"286621" => t("Salalah"),
	);
}


function location_cities_list_om_da () {
	return array (
		"286293" => t("Sufalat Sama'il"),
		"286987" => t("Nizwa"),
		"287814" => t("Izki"),
		"288721" => t("Bidbid"),
		"288899" => t("Bahla'"),
		"289433" => t("Adam"),
	);
}


function location_cities_list_om_bu () {
	return array (
		"289317" => t("Al Buraymi"),
	);
}


function location_cities_list_om_wu () {
	return array (
	);
}
