<?php


function location_cities_list_vn_44() {
  return array(
    "1575627" => "Long Xuyen",
    "1585660" => "Cho Dok",
  );
}


function location_cities_list_vn_30() {
  return array(
    "1569684" => "Pleiku",
  );
}


function location_cities_list_vn_73() {
  return array(
    "1562538" => "Vi Thanh",
  );
}


function location_cities_list_vn_65() {
  return array(
    "1566083" => "Ho Chi Minh City",
    "1584661" => "Cu Chi",
    "1586288" => "Can Gio",
  );
}


function location_cities_list_vn_71() {
  return array(
    "1583477" => "Dien Bien Phu",
  );
}


function location_cities_list_vn_28() {
  return array(
    "1578500" => "Kon Tum",
  );
}


function location_cities_list_vn_41() {
  return array(
    "1567069" => "Tan An",
    "1586296" => "Can Duoc",
  );
}


function location_cities_list_vn_48() {
  return array(
    "1586203" => "Can Tho",
  );
}


function location_cities_list_vn_64() {
  return array(
    "1567621" => "Son Tay",
    "1581130" => "Hanoi",
    "1581364" => "Ha Dong",
  );
}


function location_cities_list_vn_62() {
  return array(
    "1581298" => "Haiphong",
  );
}


function location_cities_list_vn_60() {
  return array(
    "1583992" => "Da Nang",
  );
}


function location_cities_list_vn_43() {
  return array(
    "1562414" => "Vung Tau",
  );
}


function location_cities_list_vn_57() {
  return array(
    "1565022" => "Thu Dau Mot",
  );
}


function location_cities_list_vn_58() {
  return array(
    "1582436" => "Dong Xoai",
  );
}


function location_cities_list_vn_40() {
  return array(
    "1571058" => "Phan Thiet",
    "1577995" => "Lagi",
  );
}


function location_cities_list_vn_31() {
  return array(
    "1568574" => "Qui Nhon",
  );
}


function location_cities_list_vn_55() {
  return array(
    "1591474" => "Thanh pho Bac Lieu",
  );
}


function location_cities_list_vn_54() {
  return array(
    "1591527" => "Bac Giang",
  );
}


function location_cities_list_vn_53() {
  return array(
    "1591538" => "Bac Kan",
  );
}


function location_cities_list_vn_56() {
  return array(
    "1591449" => "Bac Ninh",
  );
}


function location_cities_list_vn_50() {
  return array(
    "1587976" => "Ben Tre",
  );
}


function location_cities_list_vn_04() {
  return array(
    "1586185" => "Thanh Pho Cao Bang",
  );
}


function location_cities_list_vn_59() {
  return array(
    "1586443" => "Ca Mau",
  );
}


function location_cities_list_vn_03() {
  return array(
    "1581349" => "Thanh Pho Ha Giang",
  );
}


function location_cities_list_vn_63() {
  return array(
    "1570449" => "Thanh Pho Phu Ly",
  );
}


function location_cities_list_vn_23() {
  return array(
    "1581047" => "Ha Tinh",
  );
}


function location_cities_list_vn_14() {
  return array(
    "1580830" => "Thanh Pho Hoa Binh",
  );
}


function location_cities_list_vn_66() {
  return array(
    "1580142" => "Hung Yen",
  );
}


function location_cities_list_vn_61() {
  return array(
    "1581326" => "Hai Duong",
  );
}


function location_cities_list_vn_34() {
  return array(
    "1572151" => "Nha Trang",
    "1586350" => "Cam Ranh",
  );
}


function location_cities_list_vn_47() {
  return array(
    "1568510" => "Rach Gia",
    "1581052" => "Ha Tien",
  );
}


function location_cities_list_vn_01() {
  return array();
}


function location_cities_list_vn_02() {
  return array(
    "1568043" => "Sa Pa",
    "1576303" => "Lao Cai",
  );
}


function location_cities_list_vn_35() {
  return array(
    "1584071" => "Da Lat",
  );
}


function location_cities_list_vn_09() {
  return array(
    "1576633" => "Thanh Pho Lang Son",
  );
}


function location_cities_list_vn_67() {
  return array(
    "1573517" => "Thanh Pho Nam Dinh",
  );
}


function location_cities_list_vn_22() {
  return array(
    "1560037" => "Yen Vinh",
    "1562798" => "Vinh",
  );
}


function location_cities_list_vn_18() {
  return array(
    "1571968" => "Thanh Pho Ninh Binh",
  );
}


function location_cities_list_vn_36() {
  return array(
    "1571067" => "Phan Rang-Thap Cham",
  );
}


function location_cities_list_vn_68() {
  return array(
    "1562820" => "Viet Tri",
  );
}


function location_cities_list_vn_32() {
  return array(
    "1563281" => "Tuy Hoa",
    "1567723" => "Song Cau",
  );
}


function location_cities_list_vn_24() {
  return array(
    "1582886" => "Kwang Binh",
  );
}


function location_cities_list_vn_27() {
  return array(
    "1567148" => "Tam Ky",
    "1580541" => "Hoi An",
  );
}


function location_cities_list_vn_29() {
  return array(
    "1568770" => "Quang Ngai",
  );
}


function location_cities_list_vn_13() {
  return array(
    "1563241" => "Thanh Pho Uong Bi",
    "1574507" => "Mong Cai",
    "1580410" => "Thanh Pho Ha Long",
    "1586357" => "Cam Pha Mines",
  );
}


function location_cities_list_vn_25() {
  return array(
    "1582926" => "Dong Ha",
  );
}


function location_cities_list_vn_52() {
  return array(
    "1567788" => "Soc Trang",
  );
}


function location_cities_list_vn_05() {
  return array(
    "1567681" => "Son La",
  );
}


function location_cities_list_vn_21() {
  return array(
    "1566166" => "Thanh Hoa",
    "1587919" => "Bim Son",
  );
}


function location_cities_list_vn_20() {
  return array(
    "1566346" => "Thanh Pho Thai Binh",
  );
}


function location_cities_list_vn_69() {
  return array(
    "1566319" => "Thai Nguyen",
  );
}


function location_cities_list_vn_26() {
  return array(
    "1580240" => "Hue",
  );
}


function location_cities_list_vn_46() {
  return array(
    "1574023" => "My Tho",
  );
}


function location_cities_list_vn_51() {
  return array(
    "1563926" => "Tra Vinh",
  );
}


function location_cities_list_vn_07() {
  return array(
    "1563287" => "Thanh Pho Tuyen Quang",
  );
}


function location_cities_list_vn_37() {
  return array(
    "1566559" => "Tay Ninh",
    "1570549" => "Phu Khuong",
  );
}


function location_cities_list_vn_49() {
  return array(
    "1562693" => "Vinh Long",
  );
}


function location_cities_list_vn_70() {
  return array(
    "1562548" => "Vinh Yen",
  );
}


function location_cities_list_vn_06() {
  return array(
    "1560349" => "Yen Bai",
  );
}


function location_cities_list_vn_33() {
  return array(
    "1586896" => "Buon Ma Thuot",
  );
}


function location_cities_list_vn_39() {
  return array(
    "1587923" => "Bien Hoa",
  );
}


function location_cities_list_vn_45() {
  return array(
    "1568212" => "Sadek",
    "1586151" => "Cao Lanh",
  );
}


function location_cities_list_vn_72() {
  return array();
}
