<?php


function location_cities_list_et_af () {
	return array (
		"338554" => t("Dubti"),
		"343409" => t("Asaita"),
	);
}


function location_cities_list_et_am () {
	return array (
		"326206" => t("Werota"),
		"329586" => t("Robit"),
		"333356" => t("Kemise"),
		"333373" => t("Kombolcha"),
		"336014" => t("Gonder"),
		"337712" => t("Finote Selam"),
		"339219" => t("Dese"),
		"339686" => t("Debre Tabor"),
		"339708" => t("Debre Mark'os"),
		"339734" => t("Debre Birhan"),
		"339823" => t("Debark'"),
		"341397" => t("Bure"),
		"342190" => t("Bichena"),
		"342641" => t("Bati"),
		"342884" => t("Bahir Dar"),
		"344923" => t("Adis Zemen"),
		"345353" => t("Addiet Canna"),
		"345704" => t("Abomsa"),
	);
}


function location_cities_list_et_be () {
	return array (
		"343292" => t("Asosa"),
	);
}


function location_cities_list_et_dd () {
	return array (
		"338832" => t("Dire Dawa"),
	);
}


function location_cities_list_et_ga () {
	return array (
		"337405" => t("Gambela"),
	);
}


function location_cities_list_et_ha () {
	return array (
		"335035" => t("Harar"),
	);
}


function location_cities_list_et_or () {
	return array (
		"325579" => t("Ziway"),
		"326036" => t("Yabelo"),
		"326308" => t("Wenji"),
		"328689" => t("Shashemene"),
		"328709" => t("Shambu"),
		"328716" => t("Shakiso"),
		"329114" => t("Sebeta"),
		"330120" => t("Nejo"),
		"330186" => t("Nazret"),
		"330491" => t("Mojo"),
		"330764" => t("Metu"),
		"330811" => t("Metahara"),
		"331038" => t("Mendi"),
		"333103" => t("Kibre Mengist"),
		"333772" => t("Jima"),
		"335288" => t("Hagere Hiywet"),
		"336350" => t("Goba"),
		"336372" => t("Giyon"),
		"336454" => t("Ginir"),
		"336496" => t("Gimbi"),
		"336931" => t("Genet"),
		"337010" => t("Gelemso"),
		"337152" => t("Gebre Guracha"),
		"337771" => t("Fiche"),
		"338726" => t("Dodola"),
		"339448" => t("Dembi Dolo"),
		"339666" => t("Debre Zeyit"),
		"342559" => t("Bedesa"),
		"342567" => t("Bedele"),
		"343402" => t("Asbe Teferi"),
		"343413" => t("Asasa"),
		"344620" => t("Hagere Maryam"),
		"344661" => t("Agaro"),
	);
}


function location_cities_list_et_so () {
	return array (
		"333795" => t("Jijiga"),
	);
}


function location_cities_list_et_sn () {
	return array (
		"325780" => t("Yirga `Alem"),
		"327694" => t("Tippi"),
		"332880" => t("K'olito"),
		"333750" => t("Jinka"),
		"337853" => t("Felege Neway"),
		"338998" => t("Dila"),
		"341297" => t("Butajira"),
		"341742" => t("Bonga"),
		"341877" => t("Boditi"),
		"342856" => t("Bako"),
		"343137" => t("Hawassa"),
		"343593" => t("Areka"),
		"343663" => t("Arba Minch'"),
	);
}


function location_cities_list_et_ti () {
	return array (
		"331180" => t("Mekele"),
		"331416" => t("Maych'ew"),
		"332746" => t("Korem"),
		"334227" => t("Inda Silase"),
		"344420" => t("Aksum"),
		"345149" => t("Adigrat"),
	);
}


function location_cities_list_et_aa () {
	return array (
		"344979" => t("Addis Ababa"),
	);
}
