<?php


function location_cities_list_lr_bm () {
	return array (
	);
}


function location_cities_list_lr_bg () {
	return array (
		"2277060" => t("Gbarnga"),
	);
}


function location_cities_list_lr_21 () {
	return array (
	);
}


function location_cities_list_lr_gb () {
	return array (
		"2278158" => t("Buchanan"),
	);
}


function location_cities_list_lr_cm () {
	return array (
	);
}


function location_cities_list_lr_gg () {
	return array (
		"2272491" => t("Zwedru"),
	);
}


function location_cities_list_lr_gk () {
	return array (
	);
}


function location_cities_list_lr_lo () {
	return array (
		"2273312" => t("Voinjama"),
	);
}


function location_cities_list_lr_mg () {
	return array (
		"2276086" => t("Kakata"),
	);
}


function location_cities_list_lr_my () {
	return array (
		"2276492" => t("Harper"),
	);
}


function location_cities_list_lr_mo () {
	return array (
		"2274895" => t("Monrovia"),
		"2278682" => t("Bensonville"),
	);
}


function location_cities_list_lr_ni () {
	return array (
		"2272790" => t("New Yekepa"),
	);
}


function location_cities_list_lr_ri () {
	return array (
	);
}


function location_cities_list_lr_22 () {
	return array (
	);
}


function location_cities_list_lr_si () {
	return array (
		"2276600" => t("Greenville"),
	);
}
