<?php


function location_cities_list_ae_az() {
  return array(
    "292688" => t("Ar Ruways"),
    "292913" => t("Al Ain"),
    "292968" => t("Abu Dhabi"),
  );
}


function location_cities_list_ae_aj() {
  return array(
    "292932" => t("Ajman"),
  );
}


function location_cities_list_ae_fu() {
  return array(
    "292239" => t("Diba"),
    "292878" => t("Al Fujayrah"),
  );
}


function location_cities_list_ae_sh() {
  return array(
    "291696" => t("Khawr Fakkan"),
    "292672" => t("Sharjah"),
    "292953" => t("Adh Dhayd"),
  );
}


function location_cities_list_ae_du() {
  return array(
    "292223" => t("Dubai"),
  );
}


function location_cities_list_ae_rk() {
  return array(
    "291074" => t("Ra's al Khaymah"),
  );
}


function location_cities_list_ae_uq() {
  return array(
    "290594" => t("Umm al Qaywayn"),
  );
}
