<?php


function location_cities_list_si_002 () {
	return array (
	);
}


function location_cities_list_si_148 () {
	return array (
	);
}


function location_cities_list_si_149 () {
	return array (
	);
}


function location_cities_list_si_150 () {
	return array (
	);
}


function location_cities_list_si_004 () {
	return array (
	);
}


function location_cities_list_si_005 () {
	return array (
	);
}


function location_cities_list_si_007 () {
	return array (
	);
}


function location_cities_list_si_008 () {
	return array (
	);
}


function location_cities_list_si_152 () {
	return array (
	);
}


function location_cities_list_si_011 () {
	return array (
		"3202781" => t("Celje"),
	);
}


function location_cities_list_si_012 () {
	return array (
	);
}


function location_cities_list_si_013 () {
	return array (
	);
}


function location_cities_list_si_014 () {
	return array (
	);
}


function location_cities_list_si_153 () {
	return array (
	);
}


function location_cities_list_si_196 () {
	return array (
	);
}


function location_cities_list_si_018 () {
	return array (
	);
}


function location_cities_list_si_154 () {
	return array (
	);
}


function location_cities_list_si_020 () {
	return array (
	);
}


function location_cities_list_si_155 () {
	return array (
	);
}


function location_cities_list_si_021 () {
	return array (
	);
}


function location_cities_list_si_156 () {
	return array (
	);
}


function location_cities_list_si_022 () {
	return array (
	);
}


function location_cities_list_si_157 () {
	return array (
	);
}


function location_cities_list_si_024 () {
	return array (
	);
}


function location_cities_list_si_025 () {
	return array (
	);
}


function location_cities_list_si_026 () {
	return array (
	);
}


function location_cities_list_si_027 () {
	return array (
	);
}


function location_cities_list_si_029 () {
	return array (
	);
}


function location_cities_list_si_030 () {
	return array (
	);
}


function location_cities_list_si_031 () {
	return array (
	);
}


function location_cities_list_si_158 () {
	return array (
	);
}


function location_cities_list_si_032 () {
	return array (
	);
}


function location_cities_list_si_159 () {
	return array (
	);
}


function location_cities_list_si_161 () {
	return array (
	);
}


function location_cities_list_si_162 () {
	return array (
	);
}


function location_cities_list_si_034 () {
	return array (
	);
}


function location_cities_list_si_035 () {
	return array (
	);
}


function location_cities_list_si_036 () {
	return array (
	);
}


function location_cities_list_si_037 () {
	return array (
	);
}


function location_cities_list_si_038 () {
	return array (
	);
}


function location_cities_list_si_040 () {
	return array (
	);
}


function location_cities_list_si_041 () {
	return array (
	);
}


function location_cities_list_si_163 () {
	return array (
	);
}


function location_cities_list_si_043 () {
	return array (
	);
}


function location_cities_list_si_044 () {
	return array (
	);
}


function location_cities_list_si_047 () {
	return array (
	);
}


function location_cities_list_si_049 () {
	return array (
	);
}


function location_cities_list_si_164 () {
	return array (
	);
}


function location_cities_list_si_050 () {
	return array (
		"3197753" => t("Koper"),
	);
}


function location_cities_list_si_197 () {
	return array (
	);
}


function location_cities_list_si_165 () {
	return array (
	);
}


function location_cities_list_si_051 () {
	return array (
	);
}


function location_cities_list_si_052 () {
	return array (
		"3197378" => t("Kranj"),
	);
}


function location_cities_list_si_053 () {
	return array (
	);
}


function location_cities_list_si_055 () {
	return array (
	);
}


function location_cities_list_si_056 () {
	return array (
	);
}


function location_cities_list_si_058 () {
	return array (
	);
}


function location_cities_list_si_059 () {
	return array (
	);
}


function location_cities_list_si_060 () {
	return array (
	);
}


function location_cities_list_si_062 () {
	return array (
	);
}


function location_cities_list_si_063 () {
	return array (
	);
}


function location_cities_list_si_208 () {
	return array (
	);
}


function location_cities_list_si_064 () {
	return array (
	);
}


function location_cities_list_si_167 () {
	return array (
	);
}


function location_cities_list_si_068 () {
	return array (
	);
}


function location_cities_list_si_198 () {
	return array (
	);
}


function location_cities_list_si_070 () {
	return array (
		"3195506" => t("Maribor"),
	);
}


function location_cities_list_si_168 () {
	return array (
	);
}


function location_cities_list_si_071 () {
	return array (
	);
}


function location_cities_list_si_085 () {
	return array (
		"3194351" => t("Novo Mesto"),
	);
}


function location_cities_list_si_073 () {
	return array (
	);
}


function location_cities_list_si_075 () {
	return array (
	);
}


function location_cities_list_si_076 () {
	return array (
	);
}


function location_cities_list_si_199 () {
	return array (
	);
}


function location_cities_list_si_078 () {
	return array (
	);
}


function location_cities_list_si_079 () {
	return array (
	);
}


function location_cities_list_si_080 () {
	return array (
	);
}


function location_cities_list_si_081 () {
	return array (
	);
}


function location_cities_list_si_082 () {
	return array (
	);
}


function location_cities_list_si_083 () {
	return array (
	);
}


function location_cities_list_si_084 () {
	return array (
	);
}


function location_cities_list_si_001 () {
	return array (
	);
}


function location_cities_list_si_195 () {
	return array (
	);
}


function location_cities_list_si_003 () {
	return array (
	);
}


function location_cities_list_si_006 () {
	return array (
	);
}


function location_cities_list_si_151 () {
	return array (
	);
}


function location_cities_list_si_009 () {
	return array (
	);
}


function location_cities_list_si_019 () {
	return array (
	);
}


function location_cities_list_si_023 () {
	return array (
	);
}


function location_cities_list_si_028 () {
	return array (
	);
}


function location_cities_list_si_160 () {
	return array (
	);
}


function location_cities_list_si_039 () {
	return array (
	);
}


function location_cities_list_si_045 () {
	return array (
	);
}


function location_cities_list_si_046 () {
	return array (
	);
}


function location_cities_list_si_048 () {
	return array (
	);
}


function location_cities_list_si_166 () {
	return array (
	);
}


function location_cities_list_si_054 () {
	return array (
	);
}


function location_cities_list_si_057 () {
	return array (
	);
}


function location_cities_list_si_065 () {
	return array (
	);
}


function location_cities_list_si_066 () {
	return array (
	);
}


function location_cities_list_si_067 () {
	return array (
	);
}


function location_cities_list_si_069 () {
	return array (
	);
}


function location_cities_list_si_072 () {
	return array (
	);
}


function location_cities_list_si_074 () {
	return array (
	);
}


function location_cities_list_si_169 () {
	return array (
	);
}


function location_cities_list_si_170 () {
	return array (
	);
}


function location_cities_list_si_077 () {
	return array (
	);
}


function location_cities_list_si_087 () {
	return array (
	);
}


function location_cities_list_si_092 () {
	return array (
	);
}


function location_cities_list_si_200 () {
	return array (
	);
}


function location_cities_list_si_099 () {
	return array (
	);
}


function location_cities_list_si_103 () {
	return array (
	);
}


function location_cities_list_si_176 () {
	return array (
	);
}


function location_cities_list_si_098 () {
	return array (
	);
}


function location_cities_list_si_201 () {
	return array (
	);
}


function location_cities_list_si_209 () {
	return array (
	);
}


function location_cities_list_si_106 () {
	return array (
	);
}


function location_cities_list_si_108 () {
	return array (
	);
}


function location_cities_list_si_109 () {
	return array (
	);
}


function location_cities_list_si_111 () {
	return array (
	);
}


function location_cities_list_si_179 () {
	return array (
	);
}


function location_cities_list_si_180 () {
	return array (
	);
}


function location_cities_list_si_202 () {
	return array (
	);
}


function location_cities_list_si_215 () {
	return array (
	);
}


function location_cities_list_si_203 () {
	return array (
	);
}


function location_cities_list_si_182 () {
	return array (
	);
}


function location_cities_list_si_116 () {
	return array (
	);
}


function location_cities_list_si_205 () {
	return array (
	);
}


function location_cities_list_si_010 () {
	return array (
	);
}


function location_cities_list_si_128 () {
	return array (
	);
}


function location_cities_list_si_131 () {
	return array (
	);
}


function location_cities_list_si_134 () {
	return array (
	);
}


function location_cities_list_si_188 () {
	return array (
	);
}


function location_cities_list_si_144 () {
	return array (
	);
}


function location_cities_list_si_016 () {
	return array (
	);
}


function location_cities_list_si_017 () {
	return array (
	);
}


function location_cities_list_si_033 () {
	return array (
	);
}


function location_cities_list_si_118 () {
	return array (
	);
}


function location_cities_list_si_119 () {
	return array (
	);
}


function location_cities_list_si_120 () {
	return array (
	);
}


function location_cities_list_si_211 () {
	return array (
	);
}


function location_cities_list_si_117 () {
	return array (
	);
}


function location_cities_list_si_121 () {
	return array (
	);
}


function location_cities_list_si_122 () {
	return array (
	);
}


function location_cities_list_si_123 () {
	return array (
	);
}


function location_cities_list_si_124 () {
	return array (
	);
}


function location_cities_list_si_206 () {
	return array (
	);
}


function location_cities_list_si_125 () {
	return array (
	);
}


function location_cities_list_si_194 () {
	return array (
		"3190495" => t("Smartno pri Litiji"),
	);
}


function location_cities_list_si_126 () {
	return array (
	);
}


function location_cities_list_si_127 () {
	return array (
	);
}


function location_cities_list_si_190 () {
	return array (
	);
}


function location_cities_list_si_146 () {
	return array (
	);
}


function location_cities_list_si_191 () {
	return array (
	);
}


function location_cities_list_si_147 () {
	return array (
	);
}


function location_cities_list_si_192 () {
	return array (
	);
}


function location_cities_list_si_086 () {
	return array (
	);
}


function location_cities_list_si_171 () {
	return array (
	);
}


function location_cities_list_si_088 () {
	return array (
	);
}


function location_cities_list_si_089 () {
	return array (
	);
}


function location_cities_list_si_090 () {
	return array (
	);
}


function location_cities_list_si_091 () {
	return array (
	);
}


function location_cities_list_si_172 () {
	return array (
	);
}


function location_cities_list_si_093 () {
	return array (
	);
}


function location_cities_list_si_173 () {
	return array (
	);
}


function location_cities_list_si_094 () {
	return array (
	);
}


function location_cities_list_si_174 () {
	return array (
	);
}


function location_cities_list_si_095 () {
	return array (
	);
}


function location_cities_list_si_175 () {
	return array (
	);
}


function location_cities_list_si_096 () {
	return array (
		"3192241" => t("Ptuj"),
	);
}


function location_cities_list_si_097 () {
	return array (
	);
}


function location_cities_list_si_100 () {
	return array (
	);
}


function location_cities_list_si_101 () {
	return array (
	);
}


function location_cities_list_si_102 () {
	return array (
	);
}


function location_cities_list_si_104 () {
	return array (
	);
}


function location_cities_list_si_177 () {
	return array (
	);
}


function location_cities_list_si_107 () {
	return array (
	);
}


function location_cities_list_si_178 () {
	return array (
	);
}


function location_cities_list_si_110 () {
	return array (
	);
}


function location_cities_list_si_112 () {
	return array (
	);
}


function location_cities_list_si_113 () {
	return array (
	);
}


function location_cities_list_si_114 () {
	return array (
	);
}


function location_cities_list_si_181 () {
	return array (
	);
}


function location_cities_list_si_204 () {
	return array (
	);
}


function location_cities_list_si_210 () {
	return array (
	);
}


function location_cities_list_si_184 () {
	return array (
	);
}


function location_cities_list_si_129 () {
	return array (
		"3188915" => t("Trbovlje"),
	);
}


function location_cities_list_si_130 () {
	return array (
	);
}


function location_cities_list_si_186 () {
	return array (
	);
}


function location_cities_list_si_133 () {
	return array (
		"3189075" => t("Velenje"),
	);
}


function location_cities_list_si_187 () {
	return array (
	);
}


function location_cities_list_si_135 () {
	return array (
	);
}


function location_cities_list_si_136 () {
	return array (
	);
}


function location_cities_list_si_137 () {
	return array (
	);
}


function location_cities_list_si_138 () {
	return array (
	);
}


function location_cities_list_si_139 () {
	return array (
	);
}


function location_cities_list_si_189 () {
	return array (
	);
}


function location_cities_list_si_140 () {
	return array (
	);
}


function location_cities_list_si_141 () {
	return array (
	);
}


function location_cities_list_si_142 () {
	return array (
	);
}
