<?php

function location_cities_list_ir_24 () {
	return array (
		"142872" => t("Asadabad"),
		"14256" => t("Azadshahr"),
		"142000" => t("Bahar"),
		"132144" => t("Hamadan"),
		"125185" => t("Malayer"),
		"122915" => t("Nahavand"),
	);
}


function location_cities_list_ir_17 () {
	return array (
		"131962" => t("Harsin"),
		"130245" => t("Javanrud"),
		"23814" => t("Kahriz"),
		"128831" => t("Kangavar"),
		"128226" => t("Kermanshah"),
		"121240" => t("Paveh"),
		"120931" => t("Sarpol-e Zahab"),
		"114049" => t("Sonqor"),
	);
}


function location_cities_list_ir_20 () {
	return array (
		"144269" => t("Aleshtar"),
		"143921" => t("Aligudarz"),
		"142496" => t("Azna"),
		"140044" => t("Borujerd"),
		"127349" => t("Khorramabad"),
		"126409" => t("Kuhdasht"),
		"24851" => t("Nurabad"),
	);
}


function location_cities_list_ir_12 () {
	return array (
		"138025" => t("Damghan"),
		"32723" => t("Istgah-e Rah Ahan-e Garmsar"),
		"116402" => t("Semnan"),
		"135423" => t("Shahrud"),
	);
}


function location_cities_list_ir_07 () {
	return array (
		"138042" => t("Damavand"),
		"406993" => t("Eqbaliyeh"),
		"125188" => t("Malard"),
		"120972" => t("Pishva"),
		"32767" => t("Qarchak"),
		"118367" => t("Robat Karim"),
		"32909" => t("Shahre Jadide Andisheh"),
		"143860" => t("Shahriar"),
		"112931" => t("Tehran"),
		"112214" => t("Varamin"),
	);
}


function location_cities_list_ir_11 () {
	return array (
		"145034" => t("Abhar"),
		"143748" => t("Alvand"),
		"41210" => t("Khorram Darreh"),
		"111453" => t("Zanjan"),
	);
}


function location_cities_list_ir_18 () {
	return array (
		"136987" => t("Dehdasht"),
		"136014" => t("Do Gonbadan"),
		"66093" => t("Yasuj"),
	);
}


function location_cities_list_ir_27 () {
	return array (
		"132938" => t("Gonbad-e Qabus"),
		"132892" => t("Gorgan"),
		"129512" => t("Kalaleh"),
		"110831" => t("Shah Pasand"),
	);
}


function location_cities_list_ir_15 () {
	return array (
		"141736" => t("Bam"),
		"124647" => t("Bardsir"),
		"128234" => t("Kerman"),
		"118994" => t("Rafsanjan"),
		"118704" => t("Ravar"),
		"115781" => t("Shahr-e Babak"),
		"114259" => t("Sirjan"),
		"111421" => t("Zarand"),
	);
}


function location_cities_list_ir_25 () {
	return array (
		"143073" => t("Ardakan"),
		"142255" => t("Bafq"),
		"124274" => t("Mehriz"),
		"124193" => t("Meybod"),
		"113659" => t("Tabas"),
		"113632" => t("Taft"),
		"111822" => t("Yazd"),
	);
}


function location_cities_list_ir_30 () {
	return array (
		"138742" => t("Chenaran"),
		"132961" => t("Gonabad"),
		"128447" => t("Kashmar"),
		"124665" => t("Mashhad"),
		"122285" => t("Neyshabur"),
		"120694" => t("Qayen"),
		"119115" => t("Quchan"),
		"118063" => t("Sabzevar"),
		"1159716" => t("Sarakhs"),
		"1159384" => t("Taybad"),
		"112646" => t("Torbat-e Heydariyeh"),
		"1159362" => t("Torbat-e Jam"),
	);
}


function location_cities_list_ir_21 () {
	return array (
		"143534" => t("Amol"),
		"142363" => t("Babol"),
		"142358" => t("Babolsar"),
		"140918" => t("Behshahr"),
		"139223" => t("Chalus"),
		"134602" => t("Fereydun Kenar"),
		"129933" => t("Juybar"),
		"122397" => t("Neka'"),
		"121959" => t("Now Shahr"),
		"116996" => t("Sari"),
		"112656" => t("Tonekabon"),
	);
}


function location_cities_list_ir_19 () {
	return array (
		"142679" => t("Astaneh-ye Ashrafiyeh"),
		"142676" => t("Astara"),
		"141679" => t("Bandar-e Anzali"),
		"113343" => t("Hashtpar"),
		"125897" => t("Langerud"),
		"118743" => t("Rasht"),
		"118191" => t("Rudsar"),
	);
}


function location_cities_list_ir_28 () {
	return array (
		"119505" => t("Qazvin"),
		"113491" => t("Takestan"),
	);
}


function location_cities_list_ir_02 () {
	return array (
		"139889" => t("Bukan"),
		"126972" => t("Khvoy"),
		"125446" => t("Mahabad"),
		"124085" => t("Miandowab"),
		"122698" => t("Naqadeh"),
		"121801" => t("Orumiyeh"),
		"121795" => t("Oshnaviyeh"),
		"121110" => t("Piranshahr"),
		"119730" => t("Qarah Zia' od Din"),
		"117656" => t("Salmas"),
		"117793" => t("Shahin Dezh"),
		"113508" => t("Takab"),
	);
}


function location_cities_list_ir_01 () {
	return array (
		"144616" => t("Ahar"),
		"140889" => t("Bonab"),
		"142554" => t("Hashtrud"),
		"124862" => t("Marand"),
		"113646" => t("Tabriz"),
		"144443" => t("`Ajab Shir"),
	);
}


function location_cities_list_ir_10 () {
	return array (
		"145459" => t("Abadan"),
		"144696" => t("Aghajari"),
		"144448" => t("Ahvaz"),
		"140951" => t("Behbahan"),
		"127319" => t("Khorramshahr"),
		"124620" => t("Masjed Soleyman"),
		"121861" => t("Omidiyeh"),
		"118826" => t("Ramhormoz"),
		"118805" => t("Ramshir"),
		"116102" => t("Shadegan"),
		"114593" => t("Shush"),
		"114584" => t("Shushtar"),
		"137268" => t("Susangerd"),
	);
}


function location_cities_list_ir_14 () {
	return array (
		"145449" => t("Abadeh"),
		"144410" => t("Akbarabad"),
		"137956" => t("Darab"),
		"134721" => t("Fasa"),
		"134518" => t("Firuzabad"),
		"133595" => t("Gerash"),
		"128321" => t("Kazerun"),
		"122289" => t("Neyriz"),
		"121925" => t("Nurabad"),
		"115019" => t("Shiraz"),
	);
}


function location_cities_list_ir_08 () {
	return array (
		"140046" => t("Borujen"),
		"120678" => t("Farrokh Shahr"),
		"134762" => t("Farsan"),
		"115770" => t("Shahr-e Kord"),
	);
}


function location_cities_list_ir_04 () {
	return array (
		"143052" => t("Ardestan"),
		"418896" => t("Dorcheh Piaz"),
		"418868" => t("Dowlatabad"),
		"418863" => t("Esfahan"),
		"418851" => t("Felavarjan"),
		"133037" => t("Golpayegan"),
		"128477" => t("Kashan"),
		"418723" => t("Kelishad va Sudarjan"),
		"418710" => t("Khomeyni Shahr"),
		"127033" => t("Khvansar"),
		"418606" => t("Najafabad"),
		"418571" => t("Qahderijan"),
		"418521" => t("Rehnan"),
		"116406" => t("Semirom"),
		"417594" => t("Shahreza"),
	);
}


function location_cities_list_ir_22 () {
	return array (
		"144794" => t("Abyek"),
		"143127" => t("Arak"),
		"136399" => t("Delijan"),
		"127403" => t("Khomeyn"),
		"116667" => t("Saveh"),
	);
}


function location_cities_list_ir_16 () {
	return array (
		"141584" => t("Baneh"),
		"140521" => t("Bijar"),
		"128905" => t("Kamyaran"),
		"119161" => t("Qorveh"),
		"117574" => t("Sanandaj"),
		"117392" => t("Saqqez"),
	);
}


function location_cities_list_ir_26 () {
	return array (
		"119208" => t("Qom"),
	);
}


function location_cities_list_ir_23 () {
	return array (
		"141681" => t("Bandar 'Abbas"),
		"141665" => t("Bandar-e Lengeh"),
		"126914" => t("Kish"),
		"123941" => t("Minab"),
		"119374" => t("Qeshm"),
	);
}


function location_cities_list_ir_03 () {
	return array (
		"143083" => t("Ardabil"),
		"128008" => t("Herowabad"),
		"121380" => t("Parsabad"),
	);
}


function location_cities_list_ir_05 () {
	return array (
		"145233" => t("Abdanan"),
		"136702" => t("Dehloran"),
		"130802" => t("Ilam"),
	);
}


function location_cities_list_ir_06 () {
	return array (
		"139817" => t("Bandar-e Bushehr"),
		"134217" => t("Bandar-e Ganaveh"),
		"140097" => t("Borazjan"),
	);
}


function location_cities_list_ir_31 () {
	return array (
		"140380" => t("Bojnurd"),
		"135298" => t("Esfarayen"),
	);
}


function location_cities_list_ir_29 () {
	return array (
		"140463" => t("Birjand"),
	);
}


function location_cities_list_ir_13 () {
	return array (
		"1161724" => t("Chah Bahar"),
		"1160939" => t("Iranshahr"),
		"1160571" => t("Khash"),
		"1113217" => t("Zabol"),
		"1159301" => t("Zahedan"),
	);
}


