<?php


function location_cities_list_ae_az() {
  return array(
    "292688" => "Ar Ruways",
    "292913" => "Al Ain",
    "292968" => "Abu Dhabi",
  );
}


function location_cities_list_ae_aj() {
  return array(
    "292932" => "Ajman",
  );
}


function location_cities_list_ae_fu() {
  return array(
    "292239" => "Diba",
    "292878" => "Al Fujayrah",
  );
}


function location_cities_list_ae_sh() {
  return array(
    "291696" => "Khawr Fakkan",
    "292672" => "Sharjah",
    "292953" => "Adh Dhayd",
  );
}


function location_cities_list_ae_du() {
  return array(
    "292223" => "Dubai",
  );
}


function location_cities_list_ae_rk() {
  return array(
    "291074" => "Ra's al Khaymah",
  );
}


function location_cities_list_ae_uq() {
  return array(
    "290594" => "Umm al Qaywayn",
  );
}
