<?php


function location_cities_list_ir_44() {
  return array(
    "122438" => t("Nazarabad"),
    "128747" => t("Karaj"),
  );
}


function location_cities_list_ir_06() {
  return array(
    "134217" => t("Bandar-e Ganaveh"),
    "139817" => t("Bandar-e Bushehr"),
    "140097" => t("Borazjan"),
  );
}


function location_cities_list_ir_01() {
  return array(
    "113646" => t("Tabriz"),
    "124862" => t("Marand"),
    "140889" => t("Bonab"),
    "142554" => t("Hashtrud"),
    "144443" => t("`Ajab Shir"),
    "144616" => t("Ahar"),
  );
}


function location_cities_list_ir_14() {
  return array(
    "115019" => t("Shiraz"),
    "121925" => t("Nurabad"),
    "122289" => t("Neyriz"),
    "128321" => t("Kazerun"),
    "133595" => t("Gerash"),
    "134518" => t("Firuzabad"),
    "134721" => t("Fasa"),
    "137956" => t("Darab"),
    "144410" => t("Akbarabad"),
    "145449" => t("Abadeh"),
  );
}


function location_cities_list_ir_23() {
  return array(
    "119374" => t("Qeshm"),
    "123941" => t("Minab"),
    "126914" => t("Kish"),
    "141665" => t("Bandar-e Lengeh"),
    "141681" => t("Bandar 'Abbas"),
  );
}


function location_cities_list_ir_22() {
  return array(
    "116667" => t("Saveh"),
    "127403" => t("Khomeyn"),
    "136399" => t("Delijan"),
    "143127" => t("Arak"),
    "144794" => t("Abyek"),
  );
}


function location_cities_list_ir_21() {
  return array(
    "112656" => t("Tonekabon"),
    "116996" => t("Sari"),
    "121959" => t("Now Shahr"),
    "122397" => t("Neka'"),
    "129933" => t("Juybar"),
    "134602" => t("Fereydun Kenar"),
    "139223" => t("Chalus"),
    "140918" => t("Behshahr"),
    "142358" => t("Babolsar"),
    "142363" => t("Babol"),
    "143534" => t("Amol"),
  );
}


function location_cities_list_ir_03() {
  return array(
    "121380" => t("Parsabad"),
    "128008" => t("Herowabad"),
    "143083" => t("Ardabil"),
  );
}


function location_cities_list_ir_08() {
  return array(
    "115770" => t("Shahr-e Kord"),
    "120678" => t("Farrokh Shahr"),
    "134762" => t("Farsan"),
    "140046" => t("Borujen"),
  );
}


function location_cities_list_ir_04() {
  return array(
    "116406" => t("Semirom"),
    "127033" => t("Khvansar"),
    "128477" => t("Kashan"),
    "133037" => t("Golpayegan"),
    "143052" => t("Ardestan"),
    "417594" => t("Shahreza"),
    "418521" => t("Rehnan"),
    "418571" => t("Qahderijan"),
    "418606" => t("Najafabad"),
    "418710" => t("Khomeyni Shahr"),
    "418723" => t("Kelishad va Sudarjan"),
    "418851" => t("Felavarjan"),
    "418863" => t("Esfahan"),
    "418868" => t("Dowlatabad"),
    "418896" => t("Dorcheh Piaz"),
  );
}


function location_cities_list_ir_27() {
  return array(
    "110831" => t("Shah Pasand"),
    "129512" => t("Kalaleh"),
    "132892" => t("Gorgan"),
    "132938" => t("Gonbad-e Qabus"),
  );
}


function location_cities_list_ir_19() {
  return array(
    "113343" => t("Hashtpar"),
    "118191" => t("Rudsar"),
    "118743" => t("Rasht"),
    "125897" => t("Langerud"),
    "141679" => t("Bandar-e Anzali"),
    "142676" => t("Astara"),
    "142679" => t("Astaneh-ye Ashrafiyeh"),
  );
}


function location_cities_list_ir_24() {
  return array(
    "14256"  => t("Azadshahr"),
    "122915" => t("Nahavand"),
    "125185" => t("Malayer"),
    "132144" => t("Hamadan"),
    "142000" => t("Bahar"),
    "142872" => t("Asadabad"),
  );
}


function location_cities_list_ir_15() {
  return array(
    "111421" => t("Zarand"),
    "114259" => t("Sirjan"),
    "115781" => t("Shahr-e Babak"),
    "118704" => t("Ravar"),
    "118994" => t("Rafsanjan"),
    "124647" => t("Bardsir"),
    "128234" => t("Kerman"),
    "141736" => t("Bam"),
  );
}


function location_cities_list_ir_17() {
  return array(
    "23814"  => t("Kahriz"),
    "114049" => t("Sonqor"),
    "120931" => t("Sarpol-e Zahab"),
    "121240" => t("Paveh"),
    "128226" => t("Kermanshah"),
    "128831" => t("Kangavar"),
    "130245" => t("Javanrud"),
    "131962" => t("Harsin"),
  );
}


function location_cities_list_ir_29() {
  return array(
    "140463" => t("Birjand"),
  );
}


function location_cities_list_ir_31() {
  return array(
    "135298" => t("Esfarayen"),
    "140380" => t("Bojnurd"),
  );
}


function location_cities_list_ir_10() {
  return array(
    "114584" => t("Shushtar"),
    "114593" => t("Shush"),
    "116102" => t("Shadegan"),
    "118805" => t("Ramshir"),
    "118826" => t("Ramhormoz"),
    "121861" => t("Omidiyeh"),
    "124620" => t("Masjed Soleyman"),
    "127319" => t("Khorramshahr"),
    "137268" => t("Susangerd"),
    "140951" => t("Behbahan"),
    "144448" => t("Ahvaz"),
    "144696" => t("Aghajari"),
    "145459" => t("Abadan"),
  );
}


function location_cities_list_ir_18() {
  return array(
    "66093"  => t("Yasuj"),
    "136014" => t("Do Gonbadan"),
    "136987" => t("Dehdasht"),
  );
}


function location_cities_list_ir_16() {
  return array(
    "117392" => t("Saqqez"),
    "117574" => t("Sanandaj"),
    "119161" => t("Qorveh"),
    "128905" => t("Kamyaran"),
    "140521" => t("Bijar"),
    "141584" => t("Baneh"),
  );
}


function location_cities_list_ir_20() {
  return array(
    "24851"  => t("Nurabad"),
    "126409" => t("Kuhdasht"),
    "127349" => t("Khorramabad"),
    "140044" => t("Borujerd"),
    "142496" => t("Azna"),
    "143921" => t("Aligudarz"),
    "144269" => t("Aleshtar"),
  );
}


function location_cities_list_ir_28() {
  return array(
    "113491" => t("Takestan"),
    "119505" => t("Qazvin"),
  );
}


function location_cities_list_ir_13() {
  return array(
    "1113217" => t("Zabol"),
    "1159301" => t("Zahedan"),
    "1160571" => t("Khash"),
    "1160939" => t("Iranshahr"),
    "1161724" => t("Chah Bahar"),
  );
}


function location_cities_list_ir_07() {
  return array(
    "32767"  => t("Qarchak"),
    "32909"  => t("Shahre Jadide Andisheh"),
    "112214" => t("Varamin"),
    "112931" => t("Tehran"),
    "118367" => t("Robat Karim"),
    "120972" => t("Pishva"),
    "125188" => t("Malard"),
    "138042" => t("Damavand"),
    "143860" => t("Shahriar"),
    "406993" => t("Eqbaliyeh"),
  );
}


function location_cities_list_ir_02() {
  return array(
    "113508" => t("Takab"),
    "117656" => t("Salmas"),
    "117793" => t("Shahin Dezh"),
    "119730" => t("Qarah Zia' od Din"),
    "121110" => t("Piranshahr"),
    "121795" => t("Oshnaviyeh"),
    "121801" => t("Orumiyeh"),
    "122698" => t("Naqadeh"),
    "124085" => t("Miandowab"),
    "125446" => t("Mahabad"),
    "126972" => t("Khvoy"),
    "139889" => t("Bukan"),
  );
}


function location_cities_list_ir_05() {
  return array(
    "130802" => t("Ilam"),
    "136702" => t("Dehloran"),
    "145233" => t("Abdanan"),
  );
}


function location_cities_list_ir_26() {
  return array(
    "119208" => t("Qom"),
  );
}


function location_cities_list_ir_30() {
  return array(
    "112646"  => t("Torbat-e Heydariyeh"),
    "118063"  => t("Sabzevar"),
    "119115"  => t("Quchan"),
    "120694"  => t("Qayen"),
    "122285"  => t("Neyshabur"),
    "124665"  => t("Mashhad"),
    "128447"  => t("Kashmar"),
    "132961"  => t("Gonabad"),
    "138742"  => t("Chenaran"),
    "1159362" => t("Torbat-e Jam"),
    "1159384" => t("Taybad"),
    "1159716" => t("Sarakhs"),
  );
}


function location_cities_list_ir_12() {
  return array(
    "32723"  => t("Istgah-e Rah Ahan-e Garmsar"),
    "116402" => t("Semnan"),
    "135423" => t("Shahrud"),
    "138025" => t("Damghan"),
  );
}


function location_cities_list_ir_25() {
  return array(
    "111822" => t("Yazd"),
    "113632" => t("Taft"),
    "113659" => t("Tabas"),
    "124193" => t("Meybod"),
    "124274" => t("Mehriz"),
    "142255" => t("Bafq"),
    "143073" => t("Ardakan"),
  );
}


function location_cities_list_ir_11() {
  return array(
    "41210"  => t("Khorram Darreh"),
    "111453" => t("Zanjan"),
    "143748" => t("Alvand"),
    "145034" => t("Abhar"),
  );
}
