<?php


function location_cities_list_kr_26() {
  return array(
    "1838524" => "Busan",
    "1842966" => "Kijang",
  );
}


function location_cities_list_kr_27() {
  return array(
    "1835329" => "Daegu",
    "1925943" => "Hwawon",
  );
}


function location_cities_list_kr_30() {
  return array(
    "1835235" => "Daejeon",
  );
}


function location_cities_list_kr_42() {
  return array(
    "1832257" => "Neietsu",
    "1832909" => "Yanggu",
    "1833105" => "Wonju",
    "1835515" => "T'aebaek",
    "1836553" => "Sogcho",
    "1838069" => "Santyoku",
    "1840179" => "Kosong",
    "1843137" => "Kang-neung",
    "1844045" => "Hwacheon",
    "1844191" => "Hongch'on",
    "1845136" => "Chuncheon",
    "1892823" => "Tonghae",
  );
}


function location_cities_list_kr_29() {
  return array(
    "1841811" => "Gwangju",
  );
}


function location_cities_list_kr_41() {
  return array(
    "1832743" => "Yeoju",
    "1832830" => "Yangp'yong",
    "1832847" => "Yangju",
    "1833788" => "Vijongbu",
    "1835553" => "Suigen",
    "1838716" => "Bucheon",
    "1839652" => "Osan",
    "1840862" => "Munsan",
    "1841810" => "Kwangju",
    "1841988" => "Kuri",
    "1842485" => "Goyang",
    "1843082" => "Gapyeong",
    "1843702" => "Ich'on",
    "1843847" => "Hwaseong",
    "1846898" => "Anyang",
    "1846912" => "Anseong",
    "1846918" => "Ansan",
    "1896953" => "Pubal",
    "1897000" => "Seongnam",
    "1897007" => "Hanam",
    "1897118" => "Hwado",
    "1897122" => "Yanggok",
    "1912209" => "Wabu",
    "1948005" => "Kwangmyong",
  );
}


function location_cities_list_kr_28() {
  return array(
    "1843163" => "Ganghwa",
    "1843564" => "Incheon",
  );
}


function location_cities_list_kr_49() {
  return array(
    "1846266" => "Jeju",
    "1847050" => "Gaigeturi",
  );
}


function location_cities_list_kr_43() {
  return array(
    "1832566" => "Yong-dong",
    "1839873" => "Okcheon",
    "1842800" => "Koesan",
    "1845604" => "Cheongju",
    "1846095" => "Chinch'on",
  );
}


function location_cities_list_kr_47() {
  return array(
    "1832015" => "Heung-hai",
    "1832215" => "Enjitsu",
    "1832384" => "Eisen",
    "1832617" => "Eisen",
    "1833514" => "Waegwan",
    "1835967" => "Jenzan",
    "1837706" => "Sangju",
    "1839071" => "Pohang",
    "1840886" => "Mungyeong",
    "1841598" => "Keizan",
    "1841603" => "Kyonju",
    "1842016" => "Kunwi",
    "1842225" => "Gumi",
    "1842944" => "Gimcheon",
    "1844308" => "Hayang",
    "1845519" => "Cheongsong gun",
    "1846986" => "Andong",
  );
}


function location_cities_list_kr_45() {
  return array(
    "1833466" => "Wanju",
    "1838722" => "Puan",
    "1840379" => "Nangen",
    "1842025" => "Kunsan",
    "1842859" => "Koch'ang",
    "1842939" => "Kimje",
    "1843491" => "Iksan",
    "1843585" => "Imsil",
    "1845457" => "Jeonju",
    "1846114" => "jin-angun",
    "1846355" => "Changsu",
  );
}


function location_cities_list_kr_22() {
  return array();
}


function location_cities_list_kr_11() {
  return array(
    "1835848" => "Seoul",
  );
}


function location_cities_list_kr_44() {
  return array(
    "1832771" => "Yesan",
    "1834885" => "Tangjin",
    "1835096" => "Taesal-li",
    "1835447" => "Taisen-ri",
    "1835895" => "Suisan",
    "1836208" => "Songwon",
    "1838508" => "Fuyo",
    "1839726" => "Asan",
    "1840211" => "Nonsan",
    "1842153" => "Kinzan",
    "1842616" => "Kongju",
    "1844174" => "Hongsung",
    "1845759" => "Tenan",
    "1886598" => "Yonmu",
  );
}


function location_cities_list_kr_48() {
  return array(
    "1832828" => "Yangsan",
    "1841149" => "Miryang",
    "1841245" => "Masan",
    "1842518" => "Goseong",
    "1842754" => "Kyosai",
    "1842943" => "Kimhae",
    "1846052" => "Chinju",
    "1846069" => "Chinhae",
    "1846326" => "Changwon",
    "1882056" => "Sinhyeon",
    "1912205" => "Ungsang",
    "1925936" => "Naeso",
    "6903078" => "Changnyeong",
  );
}


function location_cities_list_kr_46() {
  return array(
    "1832501" => "Reiko",
    "1835648" => "Suncheon",
    "1839011" => "Beolgyo",
    "1840536" => "Naju",
    "1840982" => "Muan",
    "1841066" => "Moppo",
    "1841775" => "Kwangyang",
    "1841976" => "Kurye",
    "1843841" => "Hwasun",
    "1844751" => "Haenam",
    "1884138" => "Yeosu",
    "6395804" => "Sinan",
  );
}


function location_cities_list_kr_31() {
  return array(
    "1833747" => "Ulsan",
  );
}
