<?php


function location_cities_list_dz_01() {
  return array(
    "2476403" => "Timimoun",
    "2483761" => "Reggane",
    "2506795" => "Aoulef",
    "2508813" => "Adrar",
  );
}


function location_cities_list_dz_23() {
  return array(
    "2498183" => "El Hadjar",
    "2499055" => "Drean",
    "2504136" => "Berrahal",
    "2506999" => "Annaba",
  );
}


function location_cities_list_dz_32() {
  return array(
    "2498543" => "El Bayadh",
    "2498775" => "El Abiodh Sidi Cheikh",
    "2502034" => "Brezina",
  );
}


function location_cities_list_dz_39() {
  return array(
    "2483000" => "Robbah",
    "2483746" => "Reguiba",
    "2497411" => "El Oued",
    "2500737" => "Debila",
  );
}


function location_cities_list_dz_36() {
  return array(
    "2497323" => "El Tarf",
    "2497988" => "El Kala",
    "2504072" => "Besbes",
    "2504486" => "Ben Mehidi",
  );
}


function location_cities_list_dz_33() {
  return array();
}


function location_cities_list_dz_31() {
  return array(
    "2480618" => "Sidi ech Chahmi",
    "2485926" => "Oran",
    "2487852" => "Mers el Kebir",
    "2497060" => "Es Senia",
    "2502239" => "Bou Tlelis",
    "2503874" => "Bir el Djir",
    "2508119" => "'Ain el Turk",
    "2508174" => "Ain el Bya",
  );
}


function location_cities_list_dz_04() {
  return array(
    "2484620" => "Oum el Bouaghi",
    "2487805" => "Meskiana",
    "2498667" => "El Aouinet",
    "2508059" => "Ain Kercha",
    "2508102" => "Ain Fakroun",
    "2508287" => "Ain Beida",
  );
}


function location_cities_list_dz_44() {
  return array(
    "2476915" => "Theniet el Had",
    "2491911" => "Khemis Miliana",
    "2498590" => "El Attaf",
    "2498782" => "El Abadia",
    "2508228" => "Ain Defla",
  );
}


function location_cities_list_dz_46() {
  return array(
    "2494554" => "Hammam Bou Hadjar",
    "2497714" => "El Malah",
    "2498704" => "El Amria",
    "2504581" => "Beni Saf",
    "2507901" => "'Ain Temouchent",
  );
}


function location_cities_list_dz_05() {
  return array(
    "2477528" => "Tazoult-Lambese",
    "2483968" => "Ras el Aioun",
    "2487882" => "Merouana",
    "2505572" => "Batna",
    "2505629" => "Barika",
    "2506404" => "Arris",
    "2507877" => "Ain Touta",
  );
}


function location_cities_list_dz_06() {
  return array(
    "2476412" => "el hed",
    "2482159" => "Seddouk",
    "2496573" => "Feraoun",
    "2497796" => "El Kseur",
    "2505329" => "Bejaia",
    "2505651" => "Barbacha",
    "2507169" => "Amizour",
    "2507646" => "Akbou",
  );
}


function location_cities_list_dz_07() {
  return array(
    "2474506" => "Zeribet el Oued",
    "2475612" => "Tolga",
    "2479916" => "Sidi Okba",
    "2480368" => "Sidi Khaled",
    "2503826" => "Biskra",
  );
}


function location_cities_list_dz_09() {
  return array(
    "2479183" => "Souma",
    "2479966" => "Sidi Moussa",
    "2488722" => "Meftah",
    "2491050" => "L'Arba",
    "2501323" => "Chiffa",
    "2501680" => "Chebli",
    "2502962" => "Bouinan",
    "2503147" => "Bougara",
    "2503181" => "Boufarik",
    "2503468" => "Bou Arfa",
    "2503769" => "Blida",
    "2504622" => "Beni Mered",
  );
}


function location_cities_list_dz_34() {
  return array(
    "2483936" => "Ras el Oued",
    "2488202" => "Melouza",
    "2490180" => "Mansourah",
    "2498766" => "El Achir",
    "2503620" => "Bordj Zemoura",
    "2503654" => "Bordj Ghdir",
    "2503701" => "Bordj Bou Arreridj",
  );
}


function location_cities_list_dz_10() {
  return array(
    "2479161" => "Sour el Ghozlane",
    "2491134" => "Lakhdaria",
    "2499104" => "Draa el Mizan",
    "2501289" => "Chorfa",
    "2502958" => "Bouira",
    "2508268" => "Ain Bessem",
  );
}


function location_cities_list_dz_35() {
  return array(
    "2474141" => "Boumerdas",
    "2475764" => "Tizi Gheniff",
    "2476917" => "Thenia",
    "2478831" => "Tadmait",
    "2483757" => "Reghaia",
    "2486505" => "Naciria",
    "2490297" => "Makouda",
    "2491913" => "Khemis el Khechna",
    "2492991" => "Isser",
    "2499116" => "Draa Ben Khedda",
    "2500583" => "Dellys",
    "2501873" => "Chabet el Ameur",
    "2503229" => "Boudouaou",
    "2504739" => "Beni Amrane",
    "2506623" => "Arbatache",
  );
}


function location_cities_list_dz_08() {
  return array(
    "2505530" => "Bechar",
  );
}


function location_cities_list_dz_02() {
  return array(
    "2481207" => "Sidi Akkacha",
    "2485572" => "Oued Sly",
    "2485618" => "Oued Fodda",
    "2498611" => "Chlef",
    "2498954" => "Ech Chettia",
    "2502924" => "Boukadir",
    "2509031" => "Abou el Hassan",
  );
}


function location_cities_list_dz_25() {
  return array(
    "2494610" => "Hamma Bouziane",
    "2497849" => "El Khroub",
    "2500401" => "Didouche Mourad",
    "2501152" => "Constantine",
    "2507926" => "Ain Smara",
    "2508309" => "'Ain Abid",
  );
}


function location_cities_list_dz_17() {
  return array(
    "2487772" => "Messaad",
    "2498000" => "El Idrissia",
    "2500017" => "Djelfa",
    "2500904" => "Dar Chioukh",
    "2501767" => "Charef",
    "2503852" => "Birine",
    "2507972" => "Ain Oussera",
    "2508184" => "'Ain el Bell",
  );
}


function location_cities_list_dz_47() {
  return array(
    "2487620" => "Metlili Chaamba",
    "2496049" => "Ghardaia",
    "2504110" => "Berriane",
  );
}


function location_cities_list_dz_24() {
  return array(
    "2493956" => "Heliopolis",
    "2495662" => "Guelma",
    "2502686" => "Boumahra Ahmed",
  );
}


function location_cities_list_dz_18() {
  return array(
    "2492913" => "Jijel",
  );
}


function location_cities_list_dz_40() {
  return array(
    "2491889" => "Khenchela",
  );
}


function location_cities_list_dz_03() {
  return array(
    "2491191" => "Laghouat",
    "2508737" => "Aflou",
  );
}


function location_cities_list_dz_29() {
  return array(
    "2479609" => "Sig",
    "2485636" => "Oued el Abtal",
    "2490098" => "Mascara",
    "2503033" => "Bou Hanifia el Hamamat",
  );
}


function location_cities_list_dz_43() {
  return array(
    "2477255" => "Telerghma",
    "2480198" => "Sidi Merouane",
    "2482939" => "Rouached",
    "2487452" => "Mila",
    "2501541" => "Chelghoum el Aid",
  );
}


function location_cities_list_dz_27() {
  return array(
    "2487134" => "Mostaganem",
  );
}


function location_cities_list_dz_26() {
  return array(
    "2488835" => "Medea",
    "2491323" => "Ksar el Boukhari",
    "2504099" => "Berrouaghia",
  );
}


function location_cities_list_dz_28() {
  return array(
    "2481246" => "Sidi Aissa",
    "2486690" => "M'Sila",
    "2508130" => "'Ain el Melh",
    "2508157" => "`Ain el Hadjel",
  );
}


function location_cities_list_dz_45() {
  return array(
    "2507943" => "Ain Sefra",
  );
}


function location_cities_list_dz_30() {
  return array(
    "2475475" => "Touggourt",
    "2477462" => "Tebesbest",
    "2481058" => "Sidi Amrane",
    "2482886" => "Rouissat",
    "2485801" => "Ouargla",
    "2488716" => "Megarine",
    "2494029" => "Hassi Messaoud",
    "2498172" => "El Hadjira",
    "2500282" => "Djamaa",
  );
}


function location_cities_list_dz_48() {
  return array(
    "2474638" => "Zemoura",
    "2483668" => "Relizane",
    "2485582" => "Oued Rhiou",
    "2489987" => "Mazouna",
    "2492920" => "Djidiouia",
    "2507155" => "Ammi Moussa",
    "2508010" => "'Ain Merane",
  );
}


function location_cities_list_dz_20() {
  return array(
    "2482572" => "Saida",
  );
}


function location_cities_list_dz_22() {
  return array(
    "2481007" => "Sidi Bel Abbes",
    "2481639" => "Sfizef",
    "2508180" => "'Ain el Berd",
  );
}


function location_cities_list_dz_21() {
  return array(
    "2478226" => "Tamalous",
    "2479536" => "Skikda",
    "2492345" => "Kerkera",
    "2505915" => "Azzaba",
  );
}


function location_cities_list_dz_41() {
  return array(
    "2479215" => "Souk Ahras",
    "2482090" => "Sedrata",
  );
}


function location_cities_list_dz_19() {
  return array(
    "2481700" => "Setif",
    "2482447" => "Salah Bey",
    "2498392" => "El Eulma",
    "2503156" => "Bougaa",
    "2508297" => "Ain Arnat",
    "6698360" => "BABOR - VILLE",
  );
}


function location_cities_list_dz_11() {
  return array(
    "2478216" => "Tamanrasset",
    "2493222" => "I-n-Salah",
  );
}


function location_cities_list_dz_14() {
  return array(
    "2476897" => "Tiaret",
    "2479247" => "Sougueur",
    "2488616" => "Mehdia",
    "2491335" => "Ksar Chellala",
    "2496232" => "Frenda",
    "2508225" => "'Ain Deheb",
  );
}


function location_cities_list_dz_37() {
  return array(
    "2476301" => "Tindouf",
  );
}


function location_cities_list_dz_42() {
  return array(
    "2474583" => "Zeralda",
    "2476028" => "Tipasa",
    "2482390" => "Saoula",
    "2485633" => "Oued el Alleug",
    "2486825" => "Mouzaia",
    "2491578" => "Kolea",
    "2494962" => "Hadjout",
    "2498752" => "El Affroun",
    "2499193" => "Douera",
    "2501465" => "Cheraga",
    "2502939" => "Bou Ismail",
    "2505653" => "Baraki",
    "2508275" => "'Ain Benian",
  );
}


function location_cities_list_dz_38() {
  return array(
    "2475860" => "Tissemsilt",
  );
}


function location_cities_list_dz_15() {
  return array(
    "2475740" => "Tizi Rached",
    "2475744" => "Tizi Ouzou",
    "2475752" => "Tizi-n-Tleta",
    "2475921" => "Tirmitine",
    "2476396" => "Timizart",
    "2488500" => "Mekla",
    "2491042" => "L'Arbaa Nait Irathen",
    "2493605" => "Ighram",
    "2496241" => "Freha",
    "2501508" => "Chemini",
    "2503237" => "Boudjima",
    "2503755" => "Boghni",
    "2504703" => "Beni Douala",
    "2506043" => "Azazga",
    "2506519" => "Arhribs",
    "2508152" => "'Ain el Hammam",
  );
}


function location_cities_list_dz_13() {
  return array(
    "2475687" => "Tlemcen",
    "2481389" => "Sidi Abdelli",
    "2482211" => "Sebdou",
    "2483649" => "Remchi",
    "2484846" => "Ouled Mimoun",
    "2486284" => "Nedroma",
    "2490183" => "Mansoura",
    "2493918" => "Hennaya",
    "2501362" => "Chetouane",
    "2504385" => "Bensekrane",
    "2504616" => "Beni Mester",
  );
}


function location_cities_list_dz_12() {
  return array(
    "2477461" => "Tebessa",
    "2494548" => "Hammamet",
    "2501404" => "Cheria",
    "2503878" => "Bir el Ater",
  );
}


function location_cities_list_dz_16() {
  return array(
    "2482908" => "Rouiba",
    "2500889" => "Dar el Beida",
    "2503661" => "Bordj el Kiffan",
    "2503847" => "Birkhadem",
    "2505854" => "Bab Ezzouar",
    "2507480" => "Algiers",
    "2507912" => "Ain Taya",
  );
}
