<?php


function location_cities_list_ml_bko() {
  return array(
    "2460596" => "Bamako",
  );
}


function location_cities_list_ml_7() {
  return array(
    "2457163" => "Gao",
  );
}


function location_cities_list_ml_1() {
  return array(
    "2455516" => "Kayes Ndi",
    "2455518" => "Kayes",
    "2460755" => "Bafoulabe",
  );
}


function location_cities_list_ml_8() {
  return array();
}


function location_cities_list_ml_2() {
  return array(
    "2454530" => "Koulikoro",
    "2454955" => "Kolokani",
    "2455558" => "Kati",
    "2460546" => "Banamba",
  );
}


function location_cities_list_ml_5() {
  return array(
    "2453348" => "Mopti",
    "2458589" => "Djenne",
  );
}


function location_cities_list_ml_3() {
  return array(
    "2448442" => "Yorosso",
    "2451185" => "Sikasso",
    "2454268" => "Koutiala",
    "2459775" => "Bougouni",
  );
}


function location_cities_list_ml_4() {
  return array(
    "2451478" => "Segou",
    "2451778" => "San",
    "2453662" => "Markala",
  );
}


function location_cities_list_ml_6() {
  return array(
    "2449067" => "Timbuktu",
  );
}
