<?php


function location_cities_list_au_act() {
  return array(
    "2172517" => "Canberra",
  );
}


function location_cities_list_au_nsw() {
  return array(
    "2145110" => "Wagga Wagga",
    "2147381" => "Taree",
    "2147497" => "Tamworth",
    "2147714" => "Sydney",
    "2148398" => "Port Stephens",
    "2148997" => "South Grafton",
    "2152286" => "Queanbeyan",
    "2152329" => "Quakers Hill",
    "2152659" => "Port Macquarie",
    "2154219" => "Orange",
    "2154787" => "Nowra",
    "2155472" => "Newcastle",
    "2156813" => "Mosman",
    "2158626" => "Marrickville",
    "2158651" => "Maroubra",
    "2159045" => "Maitland",
    "2159851" => "Liverpool",
    "2160063" => "Lismore",
    "2161776" => "Katoomba",
    "2163137" => "Hornsby",
    "2164422" => "Griffith",
    "2164691" => "Granville",
    "2164837" => "Goulburn",
    "2166309" => "Forster",
    "2167280" => "Epping",
    "2167312" => "Engadine",
    "2167949" => "Earlwood",
    "2168305" => "Dubbo",
    "2169956" => "Cronulla",
    "2171085" => "Coffs Harbour",
    "2171507" => "Wollongong",
    "2171845" => "Cessnock",
    "2172111" => "Castle Hill",
    "2172303" => "Carlingford",
    "2172311" => "Caringbah",
    "2173911" => "Broken Hill",
    "2175411" => "Blacktown",
    "2176632" => "Bathurst",
    "2176934" => "Banora Point",
    "2177671" => "Armidale",
    "2178174" => "Albury",
    "2208285" => "Randwick",
    "2208305" => "Dee Why",
    "7281782" => "North Ryde",
    "7281840" => "Paramatta",
    "7302259" => "City of Parramatta",
    "7302642" => "Glenmore Park",
  );
}


function location_cities_list_au_nt() {
  return array(
    "2073124" => "Darwin",
    "2077895" => "Alice Springs",
    "6301965" => "Palmerston",
  );
}


function location_cities_list_au_qld() {
  return array(
    "2065594" => "Mount Isa",
    "2143069" => "Woodridge",
    "2146142" => "Townsville",
    "2146268" => "Toowoomba",
    "2147849" => "Surfers Paradise",
    "2147892" => "Sunnybank",
    "2148928" => "Southport",
    "2151437" => "Rockhampton",
    "2155542" => "Nerang",
    "2156934" => "Morayfield",
    "2158562" => "Maryborough",
    "2159220" => "Mackay",
    "2165087" => "Gold Coast",
    "2165478" => "Gladstone",
    "2169220" => "Deception Bay",
    "2172710" => "Caloundra",
    "2172797" => "Cairns",
    "2172832" => "Caboolture",
    "2173323" => "Bundaberg",
    "2173605" => "Buderim",
    "2174003" => "Brisbane",
    "2207259" => "South Brisbane",
    "6943558" => "Bracken Ridge",
    "7281838" => "Logan City",
    "7281839" => "Carindale",
    "7932654" => "Booval",
    "8354541" => "Robina",
  );
}


function location_cities_list_au_sa() {
  return array(
    "2058430" => "Whyalla",
    "2062944" => "Prospect",
    "2065176" => "Murray Bridge",
    "2065740" => "Morphett Vale",
    "2071059" => "Gawler",
    "2078025" => "Adelaide",
    "2156643" => "Mount Gambier",
    "7302628" => "Adelaide Hills",
  );
}


function location_cities_list_au_tas() {
  return array(
    "2160517" => "Launceston",
    "2163355" => "Hobart",
    "2168943" => "Devonport",
    "2173125" => "Burnie",
  );
}


function location_cities_list_au_vic() {
  return array(
    "2143285" => "Wodonga",
    "2144528" => "Warrnambool",
    "2144764" => "Wangaratta",
    "2146108" => "Traralgon",
    "2147914" => "Sunbury",
    "2149645" => "Shepparton",
    "2150660" => "Saint Kilda",
    "2151649" => "Richmond",
    "2156340" => "Mulgrave",
    "2156878" => "Mornington",
    "2157343" => "Moe",
    "2157698" => "Mildura",
    "2158151" => "Melton",
    "2158177" => "Melbourne",
    "2164515" => "Greensborough",
    "2165798" => "Geelong",
    "2166143" => "Frankston East",
    "2167817" => "Echuca",
    "2170078" => "Cranbourne",
    "2170089" => "Craigieburn",
    "2172686" => "Camberwell",
    "2173741" => "Brunswick",
    "2176187" => "Bendigo",
    "2177091" => "Ballarat",
    "7281807" => "Hoppers Crossing",
    "7281850" => "Ferntree Gully",
    "7932612" => "Glen Iris",
    "7932629" => "Balwyn North",
    "7932636" => "Carnegie",
    "7932638" => "Malvern East",
    "7932646" => "Brighton East",
    "7932651" => "Bentleigh East",
    "8015209" => "St Albans",
    "8347325" => "Endeavour Hills",
    "8347717" => "Clayton",
  );
}


function location_cities_list_au_wa() {
  return array(
    "2062338" => "Rockingham",
    "2063042" => "Port Hedland",
    "2063523" => "Perth",
    "2067119" => "Mandurah",
    "2068079" => "Kwinana",
    "2068823" => "Kalgoorlie",
    "2070571" => "Gosnells",
    "2070998" => "Geraldton",
    "2071223" => "Fremantle",
    "2075265" => "Busselton",
    "2075432" => "Bunbury",
    "2077579" => "Armadale",
    "2077963" => "Albany",
    "7302631" => "Canning Vale",
  );
}
