<?php


function location_cities_list_se_k() {
  return array(
    "2701713" => "Karlskrona",
    "2701727" => "Karlshamn",
  );
}


function location_cities_list_se_w() {
  return array(
    "2715459" => "Falun",
    "2720383" => "Borlaenge",
  );
}


function location_cities_list_se_i() {
  return array(
    "2662689" => "Visby",
  );
}


function location_cities_list_se_x() {
  return array(
    "2680075" => "Sandviken",
    "2712414" => "Gavle",
  );
}


function location_cities_list_se_n() {
  return array(
    "2664996" => "Varberg",
    "2698729" => "Kungsbacka",
    "2708365" => "Halmstad",
    "2715573" => "Falkenberg",
  );
}


function location_cities_list_se_z() {
  return array(
    "2685750" => "Ostersund",
  );
}


function location_cities_list_se_f() {
  return array(
    "2664855" => "Varnamo",
    "2690170" => "Nassjo",
    "2702979" => "Jonkoping",
    "2704136" => "Huskvarna",
  );
}


function location_cities_list_se_h() {
  return array(
    "2664203" => "Vaestervik",
    "2686162" => "Oskarshamn",
    "2702261" => "Kalmar",
  );
}


function location_cities_list_se_g() {
  return array(
    "2663536" => "Vaexjoe",
  );
}


function location_cities_list_se_bd() {
  return array(
    "603570" => "Pitea",
    "604490" => "Lulea",
    "605155" => "Kiruna",
    "606531" => "Boden",
  );
}


function location_cities_list_se_m() {
  return array(
    "2662149" => "Ystad",
    "2667402" => "Trelleborg",
    "2692969" => "Malmoe",
    "2693678" => "Lund",
    "2697720" => "Landskrona",
    "2699310" => "Kristianstad",
    "2706767" => "Helsingborg",
    "2707399" => "Hassleholm",
    "2715946" => "Eslov",
    "2725901" => "AEngelholm",
  );
}


function location_cities_list_se_ab() {
  return array(
    "2665452" => "Vallentuna",
    "2666238" => "Upplands Vaesby",
    "2667094" => "Tumba",
    "2667109" => "Tullinge",
    "2669772" => "Taby",
    "2670879" => "Sundbyberg",
    "2673730" => "Stockholm",
    "2675397" => "Solna",
    "2675408" => "Sollentuna",
    "2676176" => "Soedertaelje",
    "2683034" => "Rasunda",
    "2685828" => "OEstermalm",
    "2688250" => "Norrtalje",
    "2690580" => "Nacka",
    "2692475" => "Marsta",
    "2696334" => "Lidingoe",
    "2700791" => "Kista",
    "2703396" => "Jakobsberg",
    "2704620" => "Huddinge",
    "2707953" => "Haninge",
    "2719111" => "Bromma",
    "2721259" => "Boo",
    "2725201" => "Arsta",
    "2727234" => "Akersberga",
  );
}


function location_cities_list_se_d() {
  return array(
    "2687700" => "Nykoping",
    "2701223" => "Katrineholm",
    "2715953" => "Eskilstuna",
  );
}


function location_cities_list_se_c() {
  return array(
    "2666199" => "Uppsala",
    "2716166" => "Enkoping",
  );
}


function location_cities_list_se_s() {
  return array(
    "2699282" => "Kristinehamn",
    "2701680" => "Karlstad",
  );
}


function location_cities_list_se_ac() {
  return array(
    "602150" => "Umea",
    "602913" => "Skelleftea",
  );
}


function location_cities_list_se_y() {
  return array(
    "2670781" => "Sundsvall",
    "2686469" => "Ornskoldsvik",
    "2707684" => "Haernoesand",
  );
}


function location_cities_list_se_u() {
  return array(
    "2664454" => "Vasteras",
    "2699791" => "Koping",
  );
}


function location_cities_list_se_o() {
  return array(
    "2665171" => "Vanersborg",
    "2666670" => "Uddevalla",
    "2667303" => "Trollhattan",
    "2677234" => "Skoevde",
    "2684395" => "Partille",
    "2691459" => "Moelndal",
    "2696329" => "Lidkoping",
    "2696503" => "Lerum",
    "2698739" => "Kungalv",
    "2711537" => "Goeteborg",
    "2715568" => "Falkoeping",
    "2720501" => "Boras",
    "2726756" => "Alingsas",
    "6619708" => "Majorna",
  );
}


function location_cities_list_se_t() {
  return array(
    "2686657" => "Orebro",
    "2701715" => "Karlskoga",
  );
}


function location_cities_list_se_e() {
  return array(
    "2688368" => "Norrkoping",
    "2690960" => "Motala",
    "2694762" => "Linkoping",
  );
}
