<?php

function location_cities_list_sd_dc () {
	return array (
		"363533" => t("Zalingei"),
	);
}


function location_cities_list_sd_gz () {
	return array (
		"379427" => t("Al Hasaheisa"),
		"379406" => t("Al Hilaliyya"),
		"379149" => t("Al Manaqil"),
		"364103" => t("Wad Medani"),
	);
}


function location_cities_list_sd_kn () {
	return array (
		"380348" => t("Abu Zabad"),
		"378699" => t("An Nuhud"),
		"378493" => t("Ar Rahad"),
		"377724" => t("Barah"),
		"379003" => t("El Obeid"),
		"364706" => t("Umm Ruwaba"),
	);
}


function location_cities_list_sd_kh () {
	return array (
		"379252" => t("Khartoum"),
		"365137" => t("Omdurman"),
	);
}


function location_cities_list_sd_rs () {
	return array (
		"377039" => t("Port Sudan"),
		"367544" => t("Sawakin"),
		"366323" => t("Tokar"),
	);
}


function location_cities_list_sd_nw () {
	return array (
		"380129" => t("Ad Douiem"),
		"379014" => t("Al Qitena"),
		"371760" => t("Kosti"),
		"368277" => t("Rabak"),
		"366426" => t("Tandalti"),
	);
}


function location_cities_list_sd_si () {
	return array (
		"380151" => t("Ad Dindar"),
		"378271" => t("As Suki"),
		"372386" => t("Kinana"),
		"370838" => t("Maiurno"),
		"366847" => t("Sinja"),
		"367644" => t("Sinnar"),
	);
}


function location_cities_list_sd_nr () {
	return array (
		"378231" => t("Atbara"),
		"377690" => t("Berber"),
		"380173" => t("Ed Damer"),
		"379630" => t("El Bauga"),
		"367308" => t("Shendi"),
	);
}


function location_cities_list_sd_no () {
	return array (
		"371870" => t("Kuraymah"),
	);
}


function location_cities_list_sd_ka () {
	return array (
		"372753" => t("Kassala"),
	);
}


function location_cities_list_sd_ks () {
	return array (
		"380757" => t("Abu Jibeha"),
		"379102" => t("Al Mijlad"),
		"376450" => t("Dilling"),
		"373141" => t("Kadugli"),
	);
}


function location_cities_list_sd_gd () {
	return array (
		"379416" => t("Al Hawatah"),
		"379062" => t("Al Qadarif"),
		"376332" => t("Doka"),
	);
}


function location_cities_list_sd_nb () {
	return array (
		"380174" => t("Ad-Damazin"),
		"378459" => t("Ar Ruseris"),
	);
}


function location_cities_list_sd_dw () {
	return array (
		"379303" => t("El Geneina"),
	);
}


function location_cities_list_sd_dn () {
	return array (
		"379555" => t("El Fasher"),
	);
}


function location_cities_list_sd_de () {
	return array (
		"380148" => t("El Daein"),
	);
}


