<?php


function location_cities_list_gd_10() {
  return array();
}


function location_cities_list_gd_01() {
  return array();
}


function location_cities_list_gd_02() {
  return array();
}


function location_cities_list_gd_03() {
  return array(
    "3579925" => t("Saint George's"),
  );
}


function location_cities_list_gd_04() {
  return array();
}


function location_cities_list_gd_05() {
  return array();
}


function location_cities_list_gd_06() {
  return array();
}
