<?php

function location_cities_list_cr_c () {
	return array (
		"3624370" => t("Cartago"),
		"3622547" => t("Paraiso"),
		"3621926" => t("San Diego"),
		"3621184" => t("Turrialba"),
	);
}


function location_cities_list_cr_sj () {
	return array (
		"3624848" => t("Aserri"),
		"3624509" => t("Calle Blancos"),
		"3624174" => t("Colima"),
		"3623977" => t("Curridabat"),
		"3623593" => t("Guadalupe"),
		"3623394" => t("Ipis"),
		"3622507" => t("Patarra"),
		"3622217" => t("Purral"),
		"3621922" => t("San Felipe"),
		"3621889" => t("San Isidro"),
		"3621849" => t("San Jose"),
		"3621819" => t("San Juan"),
		"3621804" => t("San Juan de Dios"),
		"3621753" => t("San Miguel"),
		"3621717" => t("San Pedro"),
		"3621689" => t("San Rafael"),
		"3621659" => t("San Rafael Abajo"),
		"3621655" => t("San Rafael Arriba"),
		"3621505" => t("San Vicente"),
		"6612154" => t("San Vicente de Moravia"),
		"3621335" => t("Tejar"),
	);
}


function location_cities_list_cr_l () {
	return array (
		"3623580" => t("Guapiles"),
		"3622247" => t("Puerto Limon"),
		"3621440" => t("Siquirres"),
	);
}


function location_cities_list_cr_a () {
	return array (
		"3624955" => t("Alajuela"),
		"3622190" => t("Quesada"),
		"3621841" => t("San Jose"),
		"3621687" => t("San Rafael"),
	);
}


function location_cities_list_cr_h () {
	return array (
		"3623486" => t("Heredia"),
		"3622881" => t("Mercedes"),
		"3621911" => t("San Francisco"),
		"3621729" => t("San Pablo"),
	);
}


function location_cities_list_cr_p () {
	return array (
		"3624288" => t("Chacarita"),
		"3623781" => t("Esparza"),
		"3622228" => t("Puntarenas"),
	);
}


function location_cities_list_cr_g () {
	return array (
		"3624468" => t("Canas"),
		"3623076" => t("Liberia"),
		"3622716" => t("Nicoya"),
	);
}


