<?php


function location_cities_list_ni_bo() {
  return array(
    "3620544" => "Camoapa",
    "3620674" => "Boaco",
  );
}


function location_cities_list_ni_ca() {
  return array(
    "3616682" => "San Marcos",
    "3618926" => "Jinotepe",
    "3620170" => "Diriamba",
  );
}


function location_cities_list_ni_ci() {
  return array(
    "3616234" => "Somotillo",
    "3619267" => "El Viejo",
    "3620269" => "Corinto",
    "3620381" => "Chinandega",
    "3620390" => "Chichigalpa",
  );
}


function location_cities_list_ni_co() {
  return array(
    "3618908" => "Juigalpa",
  );
}


function location_cities_list_ni_es() {
  return array(
    "3619194" => "Esteli",
  );
}


function location_cities_list_ni_gr() {
  return array(
    "3617513" => "Nandaime",
    "3619136" => "Granada",
  );
}


function location_cities_list_ni_ji() {
  return array(
    "3618929" => "Jinotega",
  );
}


function location_cities_list_ni_le() {
  return array(
    "3617522" => "Nagarote",
    "3618030" => "Leon",
    "3618411" => "La Paz Centro",
  );
}


function location_cities_list_ni_md() {
  return array(
    "3616232" => "Somoto",
  );
}


function location_cities_list_ni_mn() {
  return array(
    "3616035" => "Tipitapa",
    "3616594" => "San Rafael del Sur",
    "3617763" => "Managua",
    "3619853" => "El Crucero",
    "3828262" => "Ciudad Sandino",
  );
}


function location_cities_list_ni_ms() {
  return array(
    "3617723" => "Masaya",
    "3617725" => "Masatepe",
  );
}


function location_cities_list_ni_mt() {
  return array(
    "3617069" => "Rio Blanco",
    "3617708" => "Matagalpa",
  );
}


function location_cities_list_ni_ns() {
  return array(
    "3617448" => "Ocotal",
    "3618954" => "Jalapa",
  );
}


function location_cities_list_ni_ri() {
  return array(
    "3617052" => "Rivas",
  );
}


function location_cities_list_ni_sj() {
  return array();
}


function location_cities_list_ni_an() {
  return array(
    "3616253" => "Siuna",
    "3617154" => "Bilwi",
  );
}


function location_cities_list_ni_as() {
  return array(
    "3617095" => "Rama",
    "3617459" => "Nueva Guinea",
    "3620680" => "Bluefields",
  );
}
