<?php

function location_cities_list_dj_as () {
	return array (
		"224152" => t("Danan"),
		"225284" => t("'Ali Sabieh"),
	);
}


function location_cities_list_dj_ar () {
	return array (
	);
}


function location_cities_list_dj_di () {
	return array (
	);
}


function location_cities_list_dj_dj () {
	return array (
		"223817" => t("Djibouti"),
	);
}


function location_cities_list_dj_ob () {
	return array (
		"221527" => t("Obock"),
	);
}


function location_cities_list_dj_ta () {
	return array (
		"220782" => t("Tadjoura"),
	);
}
