<?php

function location_cities_list_fi_ls () {
	return array (
		"656130" => t("Jakobstad"),
		"656083" => t("Jamsa"),
		"655194" => t("Jyvaeskylae"),
		"655130" => t("Kaarina"),
		"654440" => t("Kangasala"),
		"651943" => t("Karleby"),
		"651299" => t("Korsholm"),
		"7911309" => t("Laensi-Turunmaa"),
		"648738" => t("Laukaa"),
		"648366" => t("Lempaala"),
		"648056" => t("Lieto"),
		"644450" => t("Nokia"),
		"641489" => t("Pirkkala"),
		"640999" => t("Pori"),
		"640124" => t("Raisio"),
		"639734" => t("Rauma"),
		"637948" => t("Salo"),
		"637219" => t("Seinaejoki"),
		"634963" => t("Tampere"),
		"633679" => t("Turku"),
		"633221" => t("Uusikaupunki"),
		"632978" => t("Vaasa"),
		"632672" => t("Valkeakoski"),
		"630752" => t("Ylojarvi"),
	);
}


function location_cities_list_fi_es () {
	return array (
		"661164" => t("Anjala"),
		"660158" => t("Espoo"),
		"659935" => t("Forssa"),
		"659180" => t("Hameenlinna"),
		"659169" => t("Hamina"),
		"658288" => t("Heinola"),
		"658225" => t("Helsinki"),
		"657530" => t("Hollola"),
		"656913" => t("Hyvinkaa"),
		"656688" => t("Imatra"),
		"656073" => t("Janakkala"),
		"655958" => t("Jarvenpaa"),
		"654137" => t("Karhula"),
		"653185" => t("Kerava"),
		"649630" => t("Kirkkonummi"),
		"650946" => t("Kotka"),
		"650859" => t("Kouvola"),
		"649919" => t("Kuusankoski"),
		"649360" => t("Lahti"),
		"648900" => t("Lappeenranta"),
		"647751" => t("Lohja"),
		"646723" => t("Mantsala"),
		"644171" => t("Nurmijarvi"),
		"660561" => t("Porvoo"),
		"639406" => t("Riihimaki"),
		"637067" => t("Sibbo"),
		"633591" => t("Tuusula"),
		"632453" => t("Vantaa"),
		"631707" => t("Vihti"),
	);
}


function location_cities_list_fi_is () {
	return array (
		"656820" => t("Iisalmi"),
		"655808" => t("Joensuu"),
		"650224" => t("Kuopio"),
		"646005" => t("Mikkeli"),
		"637292" => t("Savonlinna"),
		"636947" => t("Siilinjarvi"),
		"632370" => t("Varkaus"),
	);
}


function location_cities_list_fi_ll () {
	return array (
		"653281" => t("Kemi"),
		"638936" => t("Rovaniemi"),
		"634093" => t("Tornio"),
	);
}


function location_cities_list_fi_ol () {
	return array (
		"658629" => t("Haukipudas"),
		"654899" => t("Kajaani"),
		"649924" => t("Kuusamo"),
		"643492" => t("Oulu"),
		"640276" => t("Raahe"),
	);
}


