<?php

function location_cities_list_ar_b () {
	return array (
		"3436199" => t("Azul"),
		"3865086" => t("Bahia Blanca"),
		"3435810" => t("Campana"),
		"3861953" => t("Chacabuco"),
		"3861344" => t("Chivilcoy"),
		"3860164" => t("Coronel Suarez"),
		"3435038" => t("Dolores"),
		"3853354" => t("Junin"),
		"3432043" => t("La Plata"),
		"3846864" => t("Lincoln"),
		"3430988" => t("Lujan"),
		"3430863" => t("Mar del Plata"),
		"3430708" => t("Mercedes"),
		"3430545" => t("Moron"),
		"3430443" => t("Necochea"),
		"3842881" => t("Nueve de Julio"),
		"3842670" => t("Olavarria"),
		"3841490" => t("Pergamino"),
		"3429902" => t("Pontevedra"),
		"3839982" => t("Punta Alta"),
		"3429652" => t("Quilmes"),
		"3836846" => t("San Nicolas de los Arroyos"),
		"3427833" => t("Tandil"),
		"3427761" => t("Tigre"),
		"3833859" => t("Tres Arroyos"),
		"3833112" => t("Veinticinco de Mayo"),
		"3427431" => t("Villa Gesell"),
		"3427213" => t("Zarate"),
	);
}


function location_cities_list_ar_s () {
	return array (
		"3865385" => t("Arroyo Seco"),
		"3436230" => t("Avellaneda"),
		"3862981" => t("Canada de Gomez"),
		"3862738" => t("Capitan Bermudez"),
		"3862655" => t("Carcarana"),
		"3862351" => t("Casilda"),
		"3860217" => t("Coronda"),
		"3856022" => t("Esperanza"),
		"3855554" => t("Firmat"),
		"3855244" => t("Galvez"),
		"3854985" => t("Gobernador Galvez"),
		"3854895" => t("Granadero Baigorria"),
		"3841500" => t("Perez"),
		"3839479" => t("Rafaela"),
		"3429594" => t("Reconquista"),
		"3838583" => t("Rosario"),
		"3838506" => t("Rufino"),
		"3428975" => t("San Javier"),
		"3837441" => t("San Jorge"),
		"3837124" => t("San Justo"),
		"3836277" => t("Santa Fe de la Vera Cruz"),
		"3835793" => t("Santo Tome"),
		"3834971" => t("Sunchales"),
		"3833062" => t("Venado Tuerto"),
		"3833027" => t("Vera"),
		"3832778" => t("Villa Constitucion"),
		"3427388" => t("Villa Ocampo"),
	);
}


function location_cities_list_ar_c () {
	return array (
		"3435910" => t("Buenos Aires"),
		"3435356" => t("Colegiales"),
		"3429576" => t("Retiro"),
		"3427408" => t("Villa Lugano"),
		"6693230" => t("Villa Santa Rita"),
	);
}


function location_cities_list_ar_e () {
	return array (
		"3435486" => t("Chajari"),
		"3435264" => t("Concepcion del Uruguay"),
		"3435261" => t("Concordia"),
		"3859904" => t("Crespo"),
		"3859384" => t("Diamante"),
		"3433956" => t("Federal"),
		"3433663" => t("Gualeguay"),
		"3433658" => t("Gualeguaychu"),
		"3432079" => t("La Paz"),
		"3841956" => t("Parana"),
		"3428359" => t("Santa Elena"),
		"3832934" => t("Victoria"),
		"3427428" => t("Villaguay"),
	);
}


function location_cities_list_ar_n () {
	return array (
		"3436287" => t("Aristobulo del Valle"),
		"3434291" => t("El Soberbio"),
		"3433836" => t("Garupa"),
		"3433349" => t("Jardin America"),
		"3430601" => t("Montecarlo"),
		"3430340" => t("Obera"),
		"3429886" => t("Posadas"),
		"3429790" => t("Puerto Eldorado"),
		"3429786" => t("Puerto Esperanza"),
		"3429777" => t("Puerto Iguazu"),
		"3429732" => t("Puerto Rico"),
		"3428577" => t("San Pedro"),
		"3428068" => t("San Vicente"),
	);
}


function location_cities_list_ar_w () {
	return array (
		"3435217" => t("Corrientes"),
		"3435103" => t("Curuzu Cuatia"),
		"3434095" => t("Esquina"),
		"3433753" => t("Gobernador Ingeniero Valentin Virasoro"),
		"3433715" => t("Goya"),
		"3430709" => t("Mercedes"),
		"3430598" => t("Monte Caseros"),
		"3430104" => t("Paso de los Libres"),
		"3429403" => t("Saladas"),
		"3428759" => t("San Lorenzo"),
		"3428708" => t("San Luis del Palmar"),
		"3428071" => t("Santo Tome"),
	);
}


function location_cities_list_ar_h () {
	return array (
		"3436124" => t("Barranqueras"),
		"3862320" => t("Castelli"),
		"3861678" => t("Charata"),
		"3433901" => t("Fontana"),
		"3433803" => t("General Jose de San Martin"),
		"3855074" => t("General Pinedo"),
		"3848687" => t("Las Brenas"),
		"3845330" => t("Machagai"),
		"3840300" => t("Presidencia Roque Saenz Pena"),
		"3839490" => t("Quitilipi"),
		"3429577" => t("Resistencia"),
		"3833794" => t("Tres Isletas"),
		"3832811" => t("Villa Angela"),
	);
}


function location_cities_list_ar_p () {
	return array (
		"3433899" => t("Formosa"),
		"3429949" => t("Pirane"),
	);
}


function location_cities_list_ar_q () {
	return array (
		"3862144" => t("Centenario"),
		"3859552" => t("Cutral-Co"),
		"3843123" => t("Neuquen"),
		"3840885" => t("Plottier"),
		"3836951" => t("San Martin de los Andes"),
		"3832132" => t("Zapala"),
	);
}


function location_cities_list_ar_t () {
	return array (
		"3866496" => t("Aguilares"),
		"3866367" => t("Alderetes"),
		"3864375" => t("Bella Vista"),
		"3855666" => t("Famailla"),
		"3843803" => t("Monteros"),
		"3836873" => t("San Miguel de Tucuman"),
		"3834813" => t("Tafi Viejo"),
		"3832260" => t("Yerba Buena"),
	);
}


function location_cities_list_ar_r () {
	return array (
		"3866242" => t("Allen"),
		"3862254" => t("Catriel"),
		"3861061" => t("Cinco Saltos"),
		"3861056" => t("Cipolletti"),
		"3858765" => t("El Bolson"),
		"3855065" => t("General Roca"),
		"3837980" => t("San Antonio Oeste"),
		"7647007" => t("San Carlos de Bariloche"),
		"3832899" => t("Viedma"),
		"3832647" => t("Villa Regina"),
	);
}


function location_cities_list_ar_j () {
	return array (
		"3866425" => t("Albardon"),
		"3862240" => t("Caucete"),
		"3861416" => t("Chimbas"),
		"3840860" => t("Pocito"),
		"3837240" => t("San Jose de Jachal"),
		"3837213" => t("San Juan"),
		"3836194" => t("Santa Lucia"),
		"3832653" => t("Villa Paula de Sarmiento"),
	);
}


function location_cities_list_ar_x () {
	return array (
		"3866163" => t("Alta Gracia"),
		"3865424" => t("Arroyito"),
		"3864331" => t("Bell Ville"),
		"3860259" => t("Cordoba"),
		"3859965" => t("Cosquin"),
		"3859828" => t("Cruz del Eje"),
		"3859512" => t("Dean Funes"),
		"3856235" => t("Embalse"),
		"3853510" => t("Jesus Maria"),
		"3852374" => t("La Calera"),
		"3851331" => t("La Falda"),
		"3852468" => t("Laboulaye"),
		"3844899" => t("Marcos Juarez"),
		"3843619" => t("Morteros"),
		"3838902" => t("Rio Ceballos"),
		"3838874" => t("Rio Cuarto"),
		"3838797" => t("Rio Segundo"),
		"3838793" => t("Rio Tercero"),
		"3837675" => t("San Francisco"),
		"3833412" => t("Unquillo"),
		"3832815" => t("Villa Allende"),
		"3832791" => t("Villa Carlos Paz"),
		"3832756" => t("Villa Dolores"),
		"3832694" => t("Villa Maria"),
		"3832662" => t("Villa Nueva"),
	);
}


function location_cities_list_ar_v () {
	return array (
		"3833367" => t("Ushuaia"),
	);
}


function location_cities_list_ar_u () {
	return array (
		"3860443" => t("Comodoro Rivadavia"),
		"3855974" => t("Esquel"),
		"3840092" => t("Puerto Madryn"),
		"3839307" => t("Rawson"),
		"3833883" => t("Trelew"),
	);
}


function location_cities_list_ar_g () {
	return array (
		"3865840" => t("Anatuya"),
		"3835869" => t("Santiago del Estero"),
		"3834502" => t("Termas de Rio Hondo"),
	);
}


function location_cities_list_ar_a () {
	return array (
		"3856231" => t("Embarcacion"),
		"3855116" => t("General Enrique Mosconi"),
		"3853491" => t("Joaquin V. Gonzalez"),
		"3838233" => t("Salta"),
		"3836620" => t("San Ramon de la Nueva Oran"),
		"3834601" => t("Tartagal"),
	);
}


function location_cities_list_ar_l () {
	return array (
		"3855075" => t("General Pico"),
		"3835994" => t("Santa Rosa"),
	);
}


function location_cities_list_ar_y () {
	return array (
		"3846915" => t("Libertador General San Martin"),
		"3842190" => t("Palpala"),
		"3836772" => t("San Pedro"),
		"3836564" => t("San Salvador de Jujuy"),
	);
}


function location_cities_list_ar_m () {
	return array (
		"3844421" => t("Mendoza"),
		"3836992" => t("San Martin"),
		"3836669" => t("San Rafael"),
	);
}


function location_cities_list_ar_d () {
	return array (
		"3837056" => t("San Luis"),
		"7116866" => t("Villa Mercedes"),
	);
}


function location_cities_list_ar_k () {
	return array (
		"3837702" => t("San Fernando del Valle de Catamarca"),
	);
}


function location_cities_list_ar_z () {
	return array (
		"3863379" => t("Caleta Olivia"),
		"3838859" => t("Rio Gallegos"),
	);
}


function location_cities_list_ar_f () {
	return array (
		"3861445" => t("Chilecito"),
		"3848950" => t("La Rioja"),
	);
}


