<?php

function location_cities_list_kg_b () {
	return array (
		"1222562" => t("Sulyukta"),
		"1222662" => t("Isfana"),
	);
}


function location_cities_list_kg_c () {
	return array (
		"1527199" => t("Tokmok"),
		"1528182" => t("Kara-Balta"),
		"1528193" => t("Kant"),
		"1528675" => t("Bishkek"),
	);
}


function location_cities_list_kg_gb () {
	return array (
	);
}


function location_cities_list_kg_y () {
	return array (
		"1527004" => t("Balykchy"),
		"1527497" => t("Pokrovka"),
		"1528121" => t("Karakol"),
		"1528512" => t("Cholpon-Ata"),
	);
}


function location_cities_list_kg_j () {
	return array (
		"1527260" => t("Tash-Kumyr"),
		"1528249" => t("Jalal-Abad"),
		"1528717" => t("Bazar-Korgon"),
		"1538648" => t("Toktogul"),
	);
}


function location_cities_list_kg_n () {
	return array (
		"1527592" => t("Naryn"),
		"1528796" => t("At-Bashi"),
	);
}


function location_cities_list_kg_o () {
	return array (
		"1527513" => t("Uzgen"),
		"1527534" => t("Osh"),
		"1527719" => t("Kyzyl-Kyya"),
		"1528091" => t("Kara Suu"),
	);
}


function location_cities_list_kg_t () {
	return array (
		"1527299" => t("Talas"),
	);
}
