<?php


function location_cities_list_jm_09 () {
	return array (
	);
}


function location_cities_list_jm_01 () {
	return array (
		"3489854" => t("Kingston"),
	);
}


function location_cities_list_jm_13 () {
	return array (
		"3489523" => t("May Pen"),
	);
}


function location_cities_list_jm_12 () {
	return array (
		"3489577" => t("Mandeville"),
	);
}


function location_cities_list_jm_04 () {
	return array (
	);
}


function location_cities_list_jm_02 () {
	return array (
		"3489297" => t("New Kingston"),
		"3490165" => t("Half Way Tree"),
	);
}


function location_cities_list_jm_06 () {
	return array (
	);
}


function location_cities_list_jm_14 () {
	return array (
		"3488465" => t("Spanish Town"),
		"3488981" => t("Portmore"),
		"3489227" => t("Old Harbour"),
		"3489760" => t("Linstead"),
	);
}


function location_cities_list_jm_08 () {
	return array (
		"3489460" => t("Montego Bay"),
	);
}


function location_cities_list_jm_05 () {
	return array (
	);
}


function location_cities_list_jm_03 () {
	return array (
	);
}


function location_cities_list_jm_07 () {
	return array (
	);
}


function location_cities_list_jm_10 () {
	return array (
		"3488613" => t("Savanna-la-Mar"),
	);
}


function location_cities_list_jm_11 () {
	return array (
	);
}
