<?php

function location_cities_list_cg_bzv () {
	return array (
		"2260535" => t("Brazzaville"),
	);
}


function location_cities_list_cg_8 () {
	return array (
		"2255542" => t("Owando"),
	);
}


function location_cities_list_cg_15 () {
	return array (
	);
}


function location_cities_list_cg_7 () {
	return array (
		"2259655" => t("Impfondo"),
	);
}


function location_cities_list_cg_14 () {
	return array (
		"2259947" => t("Gamboma"),
	);
}


function location_cities_list_cg_7280295 () {
	return array (
	);
}


function location_cities_list_cg_12 () {
	return array (
	);
}


function location_cities_list_cg_11 () {
	return array (
		"2257990" => t("Madingou"),
		"2259383" => t("Kayes"),
	);
}


function location_cities_list_cg_2 () {
	return array (
		"2255285" => t("Sibiti"),
	);
}


function location_cities_list_cg_5 () {
	return array (
		"2255414" => t("Pointe-Noire"),
		"2258378" => t("Loandjili"),
	);
}


function location_cities_list_cg_9 () {
	return array (
		"2256895" => t("Mossendjo"),
		"2258261" => t("Dolisie"),
	);
}


function location_cities_list_cg_13 () {
	return array (
		"2255564" => t("Ouesso"),
	);
}
