<?php


function location_cities_list_pg_nsa() {
  return array(
    "2100633" => "Arawa",
  );
}


function location_cities_list_pg_cpm() {
  return array();
}


function location_cities_list_pg_cpk() {
  return array();
}


function location_cities_list_pg_ebr() {
  return array(
    "2093685" => "Kokopo",
  );
}


function location_cities_list_pg_esw() {
  return array(
    "2083537" => "Wewak",
  );
}


function location_cities_list_pg_ehg() {
  return array(
    "2096742" => "Goroka",
  );
}


function location_cities_list_pg_epw() {
  return array();
}


function location_cities_list_pg_gpk() {
  return array();
}


function location_cities_list_pg_21() {
  return array();
}


function location_cities_list_pg_22() {
  return array();
}


function location_cities_list_pg_mpm() {
  return array(
    "2091996" => "Madang",
  );
}


function location_cities_list_pg_mrl() {
  return array();
}


function location_cities_list_pg_mba() {
  return array();
}


function location_cities_list_pg_mpl() {
  return array(
    "2092740" => "Lae",
    "2098869" => "Bulolo",
  );
}


function location_cities_list_pg_ncd() {
  return array(
    "2088122" => "Port Moresby",
  );
}


function location_cities_list_pg_nik() {
  return array();
}


function location_cities_list_pg_npp() {
  return array(
    "2088163" => "Popondetta",
  );
}


function location_cities_list_pg_shm() {
  return array(
    "2090990" => "Mendi",
  );
}


function location_cities_list_pg_wbk() {
  return array(
    "2093967" => "Kimbe",
  );
}


function location_cities_list_pg_san() {
  return array();
}


function location_cities_list_pg_whm() {
  return array(
    "2090409" => "Mount Hagen",
  );
}


function location_cities_list_pg_wpd() {
  return array(
    "2098329" => "Daru",
  );
}
