<?php


function location_cities_list_ca_ab () {
	return array (
		"5882799" => t("Airdrie"),
		"5913490" => t("Calgary"),
		"5914653" => t("Camrose"),
		"5924618" => t("Cochrane"),
		"5946768" => t("Edmonton"),
		"5955895" => t("Fort McMurray"),
		"5964347" => t("Grande Prairie"),
		"6051562" => t("Leduc"),
		"6053154" => t("Lethbridge"),
		"6071618" => t("Medicine Hat"),
		"6118158" => t("Red Deer"),
		"6146279" => t("Sherwood Park"),
		"6154383" => t("Spruce Grove"),
		"6155033" => t("St. Albert"),
	);
}


function location_cities_list_ca_bc () {
	return array (
		"5881791" => t("Abbotsford"),
		"5911606" => t("Burnaby"),
		"5914132" => t("Campbell River"),
		"5921356" => t("Chilliwack"),
		"5927689" => t("Coquitlam"),
		"5930890" => t("Courtenay"),
		"5931800" => t("Cranbrook"),
		"5937615" => t("Delta"),
		"5943865" => t("Duncan"),
		"5955960" => t("Fort St. John"),
		"5989045" => t("Kamloops"),
		"5990579" => t("Kelowna"),
		"6049388" => t("Langford"),
		"6049429" => t("Langley"),
		"6049430" => t("Langley"),
		"6065686" => t("Maple Ridge"),
		"6075293" => t("Mission"),
		"6085772" => t("Nanaimo"),
		"6087844" => t("New Westminster"),
		"6089661" => t("North Cowichan"),
		"6090785" => t("North Vancouver"),
		"6091919" => t("Oak Bay"),
		"6098642" => t("Parksville"),
		"6101141" => t("Penticton"),
		"6105815" => t("Pitt Meadows"),
		"6111632" => t("Port Alberni"),
		"6111962" => t("Port Moody"),
		"6113365" => t("Prince George"),
		"6122085" => t("Richmond"),
		"6139416" => t("Salmon Arm"),
		"6159905" => t("Surrey"),
		"6162949" => t("Terrace"),
		"6173331" => t("Vancouver"),
		"6173864" => t("Vernon"),
		"6174041" => t("Victoria"),
		"6180961" => t("White Rock"),
		"7281931" => t("Okanagan"),
		"7281936" => t("West Kelowna"),
		"7602078" => t("Ladner"),
		"7669012" => t("Walnut Grove"),
		"8533869" => t("West Vancouver"),
	);
}


function location_cities_list_ca_mb () {
	return array (
		"5907896" => t("Brandon"),
		"6183235" => t("Winnipeg"),
	);
}


function location_cities_list_ca_nb () {
	return array (
		"5939219" => t("Dieppe"),
		"5957776" => t("Fredericton"),
		"6075081" => t("Miramichi"),
		"6076211" => t("Moncton"),
		"6138517" => t("Saint John"),
		"6545023" => t("Edmundston"),
	);
}


function location_cities_list_ca_nl () {
	return array (
		"5926511" => t("Conception Bay South"),
		"5927969" => t("Corner Brook"),
		"6082231" => t("Mount Pearl"),
		"6324733" => t("St. John's"),
	);
}


function location_cities_list_ca_nt () {
	return array (
		"6185377" => t("Yellowknife"),
	);
}


function location_cities_list_ca_ns () {
	return array (
		"5935277" => t("Dartmouth"),
		"5961564" => t("Glace Bay"),
		"6087579" => t("New Glasgow"),
		"6169587" => t("Truro"),
		"6324729" => t("Halifax"),
		"6354908" => t("Sydney"),
		"7280414" => t("Cole Harbour"),
	);
}


function location_cities_list_ca_nu () {
	return array (
	);
}


function location_cities_list_ca_on () {
	return array (
		"5882873" => t("Ajax"),
		"5894171" => t("Barrie"),
		"5897884" => t("Belleville"),
		"5907180" => t("Bradford West Gwillimbury"),
		"5907364" => t("Brampton"),
		"5907983" => t("Brant"),
		"5907990" => t("Brantford"),
		"5909294" => t("Brockville"),
		"5911592" => t("Burlington"),
		"5913695" => t("Cambridge"),
		"5923101" => t("Clarence-Rockland"),
		"5924579" => t("Cobourg"),
		"5925975" => t("Collingwood"),
		"5928065" => t("Cornwall"),
		"5950267" => t("Etobicoke"),
		"5955815" => t("Fort Erie"),
		"5964700" => t("Greater Sudbury"),
		"5965812" => t("Greater Napanee"),
		"5967629" => t("Guelph"),
		"5969782" => t("Hamilton"),
		"5978765" => t("Huntsville"),
		"5991056" => t("Kenora"),
		"5991370" => t("Keswick"),
		"5992500" => t("Kingston"),
		"5992996" => t("Kitchener"),
		"6051123" => t("Leamington"),
		"6058560" => t("London"),
		"6066513" => t("Markham"),
		"6073363" => t("Midland"),
		"6074377" => t("Milton"),
		"6075357" => t("Mississauga"),
		"6087701" => t("Newmarket"),
		"6087892" => t("Niagara Falls"),
		"6089125" => t("Norfolk County"),
		"6089426" => t("North Bay"),
		"6091104" => t("North York"),
		"6092122" => t("Oakville"),
		"6094201" => t("Orangeville"),
		"6094325" => t("Orillia"),
		"6094578" => t("Oshawa"),
		"6094817" => t("Ottawa"),
		"6095645" => t("Owen Sound"),
		"6100832" => t("Pembroke"),
		"6101645" => t("Peterborough"),
		"6104111" => t("Pickering"),
		"6111704" => t("Port Colborne"),
		"6113355" => t("Prince Edward"),
		"6115355" => t("Quinte West"),
		"6117731" => t("Rayside-Balfour"),
		"6122091" => t("Richmond Hill"),
		"6141190" => t("Sarnia"),
		"6141439" => t("Sault Ste. Marie"),
		"6155721" => t("St. Catharines"),
		"6157977" => t("Stratford"),
		"6158357" => t("St. Thomas"),
		"6165719" => t("Thorold"),
		"6166142" => t("Thunder Bay"),
		"6166739" => t("Timmins"),
		"6167865" => t("Toronto"),
		"6173577" => t("Vaughan"),
		"6176823" => t("Waterloo"),
		"6177869" => t("Welland"),
		"6182962" => t("Windsor"),
		"6184365" => t("Woodstock"),
		"8285452" => t("Ancaster"),
		"8558534" => t("Willowdale"),
	);
}


function location_cities_list_ca_pe () {
	return array (
		"5920288" => t("Charlottetown"),
	);
}


function location_cities_list_ca_qc () {
	return array (
		"5884083" => t("Alma"),
		"5884588" => t("Amos"),
		"5889745" => t("Baie-Comeau"),
		"5895650" => t("Beaconsfield"),
		"5898138" => t("Beloeil"),
		"5903510" => t("Blainville"),
		"5905132" => t("Boisbriand"),
		"5906267" => t("Boucherville"),
		"5909629" => t("Brossard"),
		"5914826" => t("Candiac"),
		"5919566" => t("Chambly"),
		"5920433" => t("Chateauguay"),
		"5928488" => t("Cote-Saint-Luc"),
		"5938513" => t("Deux-Montagnes"),
		"5940956" => t("Dollard-Des Ormeaux"),
		"5941925" => t("Dorval"),
		"5942845" => t("Drummondville"),
		"5959974" => t("Gatineau"),
		"5964215" => t("Granby"),
		"5987650" => t("Joliette"),
		"5992830" => t("Kirkland"),
		"6049863" => t("La Prairie"),
		"6050263" => t("L'Assomption"),
		"6050610" => t("Laval"),
		"6059891" => t("Longueuil"),
		"6064180" => t("Magog"),
		"6067494" => t("Mascouche"),
		"6075061" => t("Mirabel"),
		"6077243" => t("Montreal"),
		"6077315" => t("Mont-Royal"),
		"6077340" => t("Mont-Saint-Hilaire"),
		"6107325" => t("Pointe-Claire"),
		"6119518" => t("Repentigny"),
		"6128577" => t("Rouyn-Noranda"),
		"6137270" => t("Saguenay"),
		"6137489" => t("Saint-Basile-le-Grand"),
		"6137540" => t("Saint-Bruno-de-Montarville"),
		"6137633" => t("Saint-Constant"),
		"6137781" => t("Sainte-Catherine"),
		"6137941" => t("Sainte-Julie"),
		"6138121" => t("Sainte-Therese"),
		"6138175" => t("Saint-Eustache"),
		"6138374" => t("Saint-Hyacinthe"),
		"6138495" => t("Saint-Jean-sur-Richelieu"),
		"6138501" => t("Saint-Jerome"),
		"6138599" => t("Saint-Lambert"),
		"6138610" => t("Saint-Laurent"),
		"6138617" => t("Saint-Lazare"),
		"6138625" => t("Saint-Leonard"),
		"6139289" => t("Salaberry-de-Valleyfield"),
		"6144312" => t("Sept-Iles"),
		"6145489" => t("Shawinigan"),
		"6146143" => t("Sherbrooke"),
		"6151352" => t("Sorel-Tracy"),
		"6163012" => t("Terrebonne"),
		"6169141" => t("Trois-Rivieres"),
		"6173017" => t("Val-d'Or"),
		"6173508" => t("Varennes"),
		"6173570" => t("Vaudreuil-Dorion"),
		"6174151" => t("Victoriaville"),
		"6179226" => t("Westmount"),
		"6325494" => t("Quebec"),
		"6325521" => t("Levis"),
		"6354895" => t("Rimouski"),
		"6354897" => t("Riviere-du-Loup"),
		"6534203" => t("L'Ancienne-Lorette"),
		"6943827" => t("Thetford-Mines"),
		"7302647" => t("Bellechasse Regional County Municipality"),
		"7303786" => t("Jonquiere"),
		"7535681" => t("Saint-Augustin-de-Desmaures"),
	);
}


function location_cities_list_ca_sk () {
	return array (
		"6058024" => t("Lloydminster"),
		"6078112" => t("Moose Jaw"),
		"6089404" => t("North Battleford"),
		"6113335" => t("Prince Albert"),
		"6119109" => t("Regina"),
		"6141256" => t("Saskatoon"),
		"6185607" => t("Yorkton"),
	);
}


function location_cities_list_ca_yt () {
	return array (
		"6180550" => t("Whitehorse"),
	);
}
