<?php


function location_cities_list_sg_01() {
  return array();
}


function location_cities_list_sg_02() {
  return array();
}


function location_cities_list_sg_03() {
  return array();
}


function location_cities_list_sg_04() {
  return array();
}


function location_cities_list_sg_05() {
  return array();
}


function location_cities_list_sg_00() {
  return array(
    "1880252" => "Singapore",
  );
}
