<?php


function location_cities_list_cz_st() {
  return array(
    "3065903" => "Slany",
    "3067051" => "Rakovnik",
    "3067542" => "Pribram",
    "3069844" => "Neratovice",
    "3070544" => "Mlada Boleslav",
    "3070862" => "Melnik",
    "3072463" => "Kutna Hora",
    "3072929" => "Kralupy nad Vltavou",
    "3073371" => "Kolin",
    "3073699" => "Kladno",
    "3078837" => "Brandys nad Labem-Stara Boleslav",
    "3079467" => "Beroun",
    "3079508" => "Benesov",
  );
}


function location_cities_list_cz_pr() {
  return array(
    "3067433" => "Prosek",
    "3067696" => "Prague",
    "3070420" => "Modrany",
    "3071966" => "Liben",
    "3072137" => "Letnany",
    "3078833" => "Branik",
    "6269470" => "Cerny Most",
  );
}


function location_cities_list_cz_jc() {
  return array(
    "3064379" => "Tabor",
    "3065067" => "Strakonice",
    "3068293" => "Pisek",
    "3074149" => "Jindrichuv Hradec",
    "3077916" => "Ceske Budejovice",
  );
}


function location_cities_list_cz_ka() {
  return array(
    "3065617" => "Sokolov",
    "3068766" => "Ostrov",
    "3073803" => "Karlovy Vary",
    "3077835" => "Cheb",
  );
}


function location_cities_list_cz_vy() {
  return array(
    "3061692" => "Zd'ar nad Sazavou Druhy",
    "3061695" => "Zd'ar nad Sazavou",
    "3064104" => "Trebic",
    "3068445" => "Pelhrimov",
    "3074199" => "Jihlava",
    "3075919" => "Havlickuv Brod",
  );
}


function location_cities_list_cz_kr() {
  return array(
    "3061284" => "Dvur Kralove nad Labem",
    "3063907" => "Trutnov",
    "3070122" => "Nachod",
    "3074204" => "Jicin",
    "3074967" => "Hradec Kralove",
  );
}


function location_cities_list_cz_li() {
  return array(
    "3071961" => "Liberec",
    "3074603" => "Jablonec nad Nisou",
    "3077929" => "Ceska Lipa",
  );
}


function location_cities_list_cz_mo() {
  return array(
    "3064000" => "Trinec",
    "3065281" => "Stary Bohumin",
    "3068799" => "Ostrava",
    "3068927" => "Opava",
    "3069305" => "Novy Jicin",
    "3073789" => "Karvina",
    "3076127" => "Frydek-Mistek",
    "3078545" => "Bruntal",
  );
}


function location_cities_list_cz_ol() {
  return array(
    "3064673" => "Sumperk",
    "3067421" => "Prostejov",
    "3067580" => "Prerov",
    "3069011" => "Olomouc",
    "3074893" => "Hranice",
  );
}


function location_cities_list_cz_pa() {
  return array(
    "3063546" => "Usti nad Orlici",
    "3064454" => "Svitavy",
    "3068582" => "Pardubice",
    "3077539" => "Chrudim",
    "3077920" => "Ceska Trebova",
  );
}


function location_cities_list_cz_pl() {
  return array(
    "3068160" => "Plzen",
    "3073660" => "Klatovy",
  );
}


function location_cities_list_cz_jm() {
  return array(
    "3061344" => "Znojmo",
    "3062283" => "Vyskov",
    "3075654" => "Hodonin",
    "3078610" => "Brno",
    "3078773" => "Breclav",
    "3079273" => "Blansko",
  );
}


function location_cities_list_cz_zl() {
  return array(
    "3061370" => "Zlin",
    "3062339" => "Vsetin",
    "3063447" => "Valasske Mezirici",
    "3063736" => "Uhersky Brod",
    "3063739" => "Uherske Hradiste",
    "3066651" => "Roznov pod Radhostem",
    "3068689" => "Otrokovice",
    "3068690" => "Otrokovice",
    "3072649" => "Kromeriz",
  );
}


function location_cities_list_cz_us() {
  return array(
    "3061822" => "Zatec",
    "3063375" => "Varnsdorf",
    "3063548" => "Usti nad Labem",
    "3064288" => "Teplice",
    "3070291" => "Most",
    "3071507" => "Louny",
    "3071665" => "Litvinov",
    "3071677" => "Litomerice",
    "3073668" => "Klasterec nad Ohri",
    "3074039" => "Kadan",
    "3074110" => "Jirkov",
    "3077244" => "Decin",
    "3077685" => "Chomutov",
    "3079348" => "Bilina",
  );
}
