<?php


function location_cities_list_cr_a() {
  return array(
    "3621687" => "San Rafael",
    "3621841" => "San Jose",
    "3622190" => "Quesada",
    "3624955" => "Alajuela",
  );
}


function location_cities_list_cr_c() {
  return array(
    "3621184" => "Turrialba",
    "3621926" => "San Diego",
    "3622547" => "Paraiso",
    "3624370" => "Cartago",
  );
}


function location_cities_list_cr_g() {
  return array(
    "3622716" => "Nicoya",
    "3623076" => "Liberia",
    "3624468" => "Canas",
  );
}


function location_cities_list_cr_h() {
  return array(
    "3621729" => "San Pablo",
    "3621911" => "San Francisco",
    "3622881" => "Mercedes",
    "3623486" => "Heredia",
  );
}


function location_cities_list_cr_l() {
  return array(
    "3621440" => "Siquirres",
    "3622247" => "Puerto Limon",
    "3623580" => "Guapiles",
  );
}


function location_cities_list_cr_p() {
  return array(
    "3622228" => "Puntarenas",
    "3623781" => "Esparza",
    "3624288" => "Chacarita",
  );
}


function location_cities_list_cr_sj() {
  return array(
    "3621335" => "Tejar",
    "3621505" => "San Vicente",
    "3621655" => "San Rafael Arriba",
    "3621659" => "San Rafael Abajo",
    "3621689" => "San Rafael",
    "3621717" => "San Pedro",
    "3621753" => "San Miguel",
    "3621804" => "San Juan de Dios",
    "3621819" => "San Juan",
    "3621849" => "San Jose",
    "3621889" => "San Isidro",
    "3621922" => "San Felipe",
    "3622217" => "Purral",
    "3622507" => "Patarra",
    "3623394" => "Ipis",
    "3623593" => "Guadalupe",
    "3623977" => "Curridabat",
    "3624174" => "Colima",
    "3624509" => "Calle Blancos",
    "3624848" => "Aserri",
    "6612154" => "San Vicente de Moravia",
  );
}
