<?php

function location_cities_list_ao_bgu()
{
  return array(
    '3351758' => t('Município Balombo'),
    '3351760' => t('Município Balombo'),
    '3351785' => t('Município Baía Farta'),
    '3351661' => t('Município Benguela'),
    '3351597' => t('Município Bocoio'),
    '3351267' => t('Município Caimbambo'),
    '3349404' => t('Município Chongoroi'),
    '3349225' => t('Município Cubal'),
    '3348578' => t('Município Ganda'),
    '3347937' => t('Município Lobito'),
  );
}

function location_cities_list_ao_cab()
{
  return array(
    '2243645' => t('Município Belize'),
    '2243457' => t('Município Buco Zau'),
    '2243267' => t('Município Cabinda'),
    '2240660' => t('Município Lândana'),
  );
}

function location_cities_list_ao_hua()
{
  return array(
    '3351782' => t('Município Bailundo'),
    '3351497' => t('Município Caála'),
    '3348773' => t('Município Ekunha'),
    '3348311' => t('Município Huambo'),
    '3348093' => t('Município Katchiungo'),
    '3347879' => t('Município Londuimbali'),
    '3347852' => t('Município Longonjo'),
    '3347110' => t('Município Mungo'),
    '3345923' => t('Município Tchikala-Tcholohanga'),
    '3345909' => t('Município Tchindjenje'),
    '3345667' => t('Município Ukuma'),
  );
}

function location_cities_list_ao_lsu()
{
  return array(
    '3351386' => t('Município Cacolo'),
    '876307' => t('Município Dala'),
    '875968' => t('Município Muconda'),
    '145530' => t('Município Saurimo'),
  );
}

function location_cities_list_ao_mox()
{
  return array(
    '876723' => t('Município Alto Zambeze'),
    '876631' => t('Município Camanongue'),
    '876198' => t('Município Luacano'),
    '876176' => t('Município Luau'),
    '3347741' => t('Município Luchazes'),
    '876129' => t('Município Lumbala N’guimbo'),
    '876125' => t('Município Lumege'),
    '876232' => t('Município Léua'),
    '875997' => t('Município Moxico'),
    '875819' => t('Município Rivungo'),
  );
}

function location_cities_list_ao_zai()
{
  return array(
    '2241620' => t('Município Cuimba'),
    '2239519' => t('Município M’banza Congo'),
    '2239019' => t('Município Nóqui'),
    '2239000' => t('Município N’zeto'),
    '2236966' => t('Município Soyo'),
    '2236714' => t('Município Tomboco'),
  );
}

function location_cities_list_ao_bgo()
{
  return array(
    '2241484' => t('Dande Municipality'),
    '2243911' => t('Município Ambriz'),
    '2243420' => t('Município Bula Atumba'),
    '2241454' => t('Município Dembos'),
    '2240756' => t('Município Icoloe Bengo'),
    '2238950' => t('Município Pango Aluquém'),
    '2238564' => t('Município Quicama'),
    '2239093' => t('Nambuangongo Municipality'),
  );
}

function location_cities_list_ao_bie()
{
  return array(
    '3351013' => t('Concelho de Camacupa'),
    '3351882' => t('Município Andulo'),
    '3351012' => t('Município Camacupa'),
    '3350370' => t('Município Catabola'),
    '3349722' => t('Município Chinguar'),
    '3349514' => t('Município Chitembo'),
    '3349179' => t('Município Cuemba'),
    '3349078' => t('Município Cunhinga'),
    '3348077' => t('Município Kuito'),
    '3346941' => t('Município N’harea'),
  );
}

function location_cities_list_ao_ccu()
{
  return array(
    '3351214' => t('Mnuicípio Calai'),
    '3349243' => t('Município Cuangar'),
    '3349195' => t('Município Cuchi'),
    '3349148' => t('Município Cuito Cuanavale'),
    '876291' => t('Município Dirico'),
    '876017' => t('Município Mavinga'),
    '3347352' => t('Município Menongue'),
    '3347005' => t('Município Nankova'),
  );
}

function location_cities_list_ao_cno()
{
  return array(
    '2241967' => t('Cazengo Municipality'),
    '2243916' => t('Município Ambaca'),
    '2243811' => t('Município Banga'),
    '2243535' => t('Município Bolongongo'),
    '2242801' => t('Município Cambambe'),
    '2240974' => t('Município Golungo Alto'),
    '2240905' => t('Município Gonguembo'),
    '2240384' => t('Município Lucala'),
    '2238485' => t('Município Quiculungo'),
  );
}

function location_cities_list_ao_cus()
{
  return array(
    '3351905' => t('Município Amboim'),
    '3350385' => t('Município Cassongue'),
    '3349321' => t('Município Conda'),
    '3348792' => t('Município Ebo'),
    '3347989' => t('Município Libolo'),
    '3347070' => t('Município Mussende'),
    '3346659' => t('Município Porto Amboim'),
    '3346597' => t('Município Quibala'),
    '3346558' => t('Município Quilenda'),
    '3346113' => t('Município Seles'),
    '3346014' => t('Município Sumbe'),
    '3345496' => t('Município Waku Kungo'),
  );
}

function location_cities_list_ao_cnn()
{
  return array(
    '3351306' => t('Município Cahama'),
    '3349237' => t('Município Cuanhama'),
    '3349045' => t('Município Curoca'),
    '3348986' => t('Município Cuvelai'),
    '3347028' => t('Município Namacunde'),
    '3346850' => t('Município Ombadja'),
  );
}

function location_cities_list_ao_hui()
{
  return array(
    '3351379' => t('Município Caconda'),
    '3351021' => t('Município Caluquembe'),
    '3350009' => t('Município Chiange'),
    '3349996' => t('Município Chibia'),
    '3349949' => t('Município Chicomba'),
    '3349647' => t('Município Chipindo'),
    '3348286' => t('Município Humpata'),
    '3348165' => t('Município Jamba'),
    '3348075' => t('Município Kuvango'),
    '3347760' => t('Município Lubango'),
    '3347423' => t('Município Matala'),
    '3346556' => t('Município Quilengues'),
    '3346496' => t('Município Quipungo'),
  );
}

function location_cities_list_ao_lua()
{
  return array(
    '2243171' => t('Cacuaco Municipality'),
    '2240445' => t('Luanda Municipality'),
    '2236499' => t('Viana'),
  );
}

function location_cities_list_ao_lno()
{
  return array(
    '145897' => t('Município Cambulo'),
    '2242427' => t('Município Capenda-Camulemba'),
    '2242051' => t('Município Caungula'),
    '145775' => t('Município Chitato'),
    '2241665' => t('Município Cuango'),
    '2241628' => t('Município Cuilo'),
    '2240415' => t('Município Lubalo'),
    '145723' => t('Município Lucapa'),
    '2236396' => t('Município Xá-Muteba'),
  );
}

function location_cities_list_ao_mal()
{
  return array(
    '2239859' => t('Malanje Municipality'),
    '2243120' => t('Município Cacuso'),
    '2242997' => t('Município Calandula'),
    '3350916' => t('Município Cambundi-Catembo'),
    '3350771' => t('Município Cangandala'),
    '2242475' => t('Município Caombo'),
    '2240688' => t('Município Kiwaba N’zogi'),
    '2240685' => t('Município Kunda-dia-Baze'),
    '3347614' => t('Município Luquembo'),
    '2239711' => t('Município Marimba'),
    '2239696' => t('Município Massango'),
    '2239335' => t('Município Mucari'),
    '2238814' => t('Município Quela'),
    '3346489' => t('Município Quirima'),
  );
}

function location_cities_list_ao_nam()
{
  return array(
    '3351646' => t('Município Bibala'),
    '3351015' => t('Município Camacuio'),
    '3347017' => t('Município Namibe'),
    '3345788' => t('Município Tombua'),
    '3345516' => t('Município Virei'),
  );
}

function location_cities_list_ao_uig()
{
  return array(
    '2243908' => t('Ambuila Municipality'),
    '2243632' => t('Concelho do Bembe'),
    '2243921' => t('Município Alto Cauale'),
    '2243631' => t('Município Bembe'),
    '2243441' => t('Município Buengas'),
    '2243355' => t('Município Bungo'),
    '2241498' => t('Município Damba'),
    '2239352' => t('Município Mucaba'),
    '2238826' => t('Município Puri'),
    '2238174' => t('Município Quimbele'),
    '2237144' => t('Município Santa Cruz'),
    '2237127' => t('Município Sanza Pombo'),
    '2236985' => t('Município Songo'),
    '2239731' => t('Muniípio Maquela do Zombo'),
    '2239067' => t('Negage Municipality'),
    '2237499' => t('Quitexe Municipality'),
    '2236567' => t('Uige Municipality'),
  );
}
