<?php

function location_cities_list_at_1 () {
	return array (
	);
}


function location_cities_list_at_2 () {
	return array (
		"2760910" => t("Wolfsberg"),
		"2762372" => t("Villach"),
		"2764786" => t("Spittal an der Drau"),
		"2774326" => t("Klagenfurt am Woerthersee"),
	);
}


function location_cities_list_at_3 () {
	return array (
		"2761353" => t("Wiener Neustadt"),
		"2761669" => t("Weinzierl bei Krems"),
		"2763460" => t("Traiskirchen"),
		"2763795" => t("Ternitz"),
		"2765388" => t("Schwechat"),
		"2766429" => t("Sankt Polten"),
		"2771335" => t("Modling"),
		"2773549" => t("Krems an der Donau"),
		"2773913" => t("Klosterneuburg"),
		"2782067" => t("Baden"),
		"2782555" => t("Amstetten"),
	);
}


function location_cities_list_at_5 () {
	return array (
		"2766824" => t("Salzburg"),
		"2766922" => t("Saalfelden am Steinernen Meer"),
		"2776951" => t("Hallein"),
		"3323063" => t("Ansfelden"),
	);
}


function location_cities_list_at_6 () {
	return array (
		"2772649" => t("Leoben"),
		"2774773" => t("Kapfenberg"),
		"2778067" => t("Graz"),
	);
}


function location_cities_list_at_7 () {
	return array (
		"2773300" => t("Kufstein"),
		"2775220" => t("Innsbruck"),
	);
}


function location_cities_list_at_4 () {
	return array (
		"2761524" => t("Wels"),
		"2763423" => t("Traun"),
		"2764359" => t("Steyr"),
		"2772400" => t("Linz"),
		"2772635" => t("Leonding"),
		"2781520" => t("Braunau am Inn"),
	);
}


function location_cities_list_at_9 () {
	return array (
		"2761369" => t("Vienna"),
	);
}


function location_cities_list_at_8 () {
	return array (
		"2772173" => t("Lustenau"),
		"2779674" => t("Feldkirch"),
		"2780741" => t("Dornbirn"),
		"2781503" => t("Bregenz"),
	);
}
