<?php

function location_cities_list_ch_zh () {
	return array (
		"2661861" => t("Adliswil"),
		"2661666" => t("Aussersihl"),
		"2661015" => t("Dietikon"),
		"2660971" => t("Dubendorf"),
		"2660305" => t("Horgen"),
		"2660127" => t("Kloten"),
		"6295536" => t("Oberwinterthur (Kreis 2)"),
		"6295531" => t("Seen (Kreis 3)"),
		"6295520" => t("Stadt Winterthur (Kreis 1)"),
		"2658216" => t("Uster"),
		"2657970" => t("Winterthur"),
		"6295539" => t("Zuerich (Kreis 10)"),
		"2660306" => t("Zuerich (Kreis 10) / Hoengg"),
		"6295475" => t("Zuerich (Kreis 10) / Wipkingen"),
		"6295533" => t("Zuerich (Kreis 11)"),
		"6295484" => t("Zuerich (Kreis 11) / Affoltern"),
		"2659310" => t("Zuerich (Kreis 11) / Oerlikon"),
		"2658656" => t("Zuerich (Kreis 11) / Seebach"),
		"6295523" => t("Zuerich (Kreis 12)"),
		"6295540" => t("Zuerich (Kreis 2)"),
		"6295495" => t("Zuerich (Kreis 2) / Wollishofen"),
		"6295532" => t("Zuerich (Kreis 3)"),
		"6295498" => t("Zuerich (Kreis 3) / Sihlfeld"),
		"6295550" => t("Zuerich (Kreis 6)"),
		"6295504" => t("Zuerich (Kreis 6) / Unterstrass"),
		"6295548" => t("Zuerich (Kreis 7)"),
		"6295542" => t("Zuerich (Kreis 8)"),
		"6295534" => t("Zuerich (Kreis 9)"),
		"6295512" => t("Zuerich (Kreis 9) / Albisrieden"),
		"6295513" => t("Zuerich (Kreis 9) / Altstetten"),
		"2657896" => t("Zurich"),
	);
}


function location_cities_list_ch_zg () {
	return array (
		"2661653" => t("Baar"),
		"2657908" => t("Zug"),
	);
}


function location_cities_list_ch_vd () {
	return array (
		"2659994" => t("Lausanne"),
		"2659977" => t("Le Chatelard"),
		"2659601" => t("Montreux"),
		"2659422" => t("Nyon"),
		"2659127" => t("Pully"),
		"2659070" => t("Renens"),
		"2658145" => t("Vevey"),
		"2657941" => t("Yverdon-les-Bains"),
	);
}


function location_cities_list_ch_sg () {
	return array (
		"2660549" => t("Gossau"),
		"2660221" => t("Jona"),
		"2659099" => t("Rapperswil"),
		"2658822" => t("Sankt Gallen"),
		"2657996" => t("Wil"),
	);
}


function location_cities_list_ch_ag () {
	return array (
		"2661881" => t("Aarau"),
		"2661646" => t("Baden"),
		"2658011" => t("Wettingen"),
	);
}


function location_cities_list_ch_ge () {
	return array (
		"2661265" => t("Carouge"),
		"2660646" => t("Geneve"),
		"6691640" => t("Lancy"),
		"2659667" => t("Meyrin"),
		"2659296" => t("Onex"),
		"2658154" => t("Vernier"),
	);
}


function location_cities_list_ch_be () {
	return array (
		"2661552" => t("Bern"),
		"2661513" => t("Biel/Bienne"),
		"2660119" => t("Koniz"),
		"2658494" => t("Steffisburg"),
		"2658377" => t("Thun"),
	);
}


function location_cities_list_ch_vs () {
	return array (
		"2659613" => t("Monthey"),
		"2658606" => t("Sierre"),
		"2658576" => t("Sion"),
	);
}


function location_cities_list_ch_sh () {
	return array (
		"2658761" => t("Schaffhausen"),
	);
}


function location_cities_list_ch_so () {
	return array (
		"2660512" => t("Grenchen"),
		"2659297" => t("Olten"),
	);
}


function location_cities_list_ch_ne () {
	return array (
		"2660076" => t("La Chaux-de-Fonds"),
		"2659496" => t("Neuchatel"),
	);
}


function location_cities_list_ch_bl () {
	return array (
		"2661810" => t("Allschwil"),
		"2659522" => t("Muttenz"),
	);
}


function location_cities_list_ch_lu () {
	return array (
		"2660911" => t("Emmen"),
		"2660104" => t("Kriens"),
		"2659873" => t("Littau"),
		"2659811" => t("Luzern"),
	);
}


function location_cities_list_ch_ti () {
	return array (
		"2661567" => t("Bellinzona"),
		"2659836" => t("Lugano"),
	);
}


function location_cities_list_ch_tg () {
	return array (
		"2660727" => t("Frauenfeld"),
		"2660108" => t("Kreuzlingen"),
	);
}


function location_cities_list_ch_ar () {
	return array (
		"2660365" => t("Herisau"),
	);
}


function location_cities_list_ch_fr () {
	return array (
		"2660718" => t("Fribourg"),
	);
}


function location_cities_list_ch_gr () {
	return array (
		"2661169" => t("Chur"),
	);
}


function location_cities_list_ch_bs () {
	return array (
		"2661604" => t("Basel"),
		"3206590" => t("Riehen"),
	);
}


