<?php

function location_cities_list_ro_tr () {
	return array (
		"686502" => t("Alexandria"),
		"664437" => t("Turnu Magurele"),
		"662187" => t("Zimnicea"),
	);
}


function location_cities_list_ro_bv () {
	return array (
		"683844" => t("Brasov"),
		"668828" => t("Rasnov"),
		"668314" => t("Sacele"),
		"662284" => t("Zarnesti"),
	);
}


function location_cities_list_ro_sj () {
	return array (
		"667101" => t("Simleu Silvaniei"),
		"662334" => t("Zalau"),
	);
}


function location_cities_list_ro_if () {
	return array (
		"683394" => t("Buftea"),
		"671382" => t("Pantelimon"),
		"669870" => t("Popesti-Leordeni"),
		"662476" => t("Voluntari"),
	);
}


function location_cities_list_ro_sv () {
	return array (
		"681845" => t("Campulung Moldovenesc"),
		"678459" => t("Falticeni"),
		"676527" => t("Gura Humorului"),
		"669289" => t("Radauti"),
		"665850" => t("Suceava"),
		"663100" => t("Vatra Dornei"),
	);
}


function location_cities_list_ro_vs () {
	return array (
		"684802" => t("Barlad"),
		"675892" => t("Husi"),
		"663118" => t("Vaslui"),
	);
}


function location_cities_list_ro_il () {
	return array (
		"678306" => t("Fetesti"),
		"678301" => t("Fetesti-Gara"),
		"8581467" => t("Slobozia"),
		"664074" => t("Urziceni"),
	);
}


function location_cities_list_ro_cj () {
	return array (
		"681865" => t("Campia Turzii"),
		"681290" => t("Cluj-Napoca"),
		"679550" => t("Dej"),
		"677429" => t("Gherla"),
		"664460" => t("Turda"),
	);
}


function location_cities_list_ro_tl () {
	return array (
		"664518" => t("Tulcea"),
	);
}


function location_cities_list_ro_ms () {
	return array (
		"674541" => t("Ludus"),
		"8436351" => t("Sighisoara"),
		"665004" => t("Targu-Mures"),
		"664963" => t("Tarnaveni"),
	);
}


function location_cities_list_ro_cv () {
	return array (
		"667303" => t("Sfantu-Gheorghe"),
		"665000" => t("Targu Secuiesc"),
	);
}


function location_cities_list_ro_nt () {
	return array (
		"670889" => t("Piatra Neamt"),
		"668732" => t("Roman"),
		"665003" => t("Targu Neamt"),
	);
}


function location_cities_list_ro_gj () {
	return array (
		"672757" => t("Motru"),
		"665010" => t("Targu Jiu"),
	);
}


function location_cities_list_ro_db () {
	return array (
		"677742" => t("Gaesti"),
		"672862" => t("Moreni"),
		"665024" => t("Targoviste"),
	);
}


function location_cities_list_ro_tm () {
	return array (
		"674531" => t("Lugoj"),
		"665087" => t("Timisoara"),
	);
}


function location_cities_list_ro_gl () {
	return array (
		"677697" => t("Galati"),
		"665355" => t("Tecuci"),
	);
}


function location_cities_list_ro_ot () {
	return array (
		"685586" => t("Bals"),
		"682747" => t("Caracal"),
		"680897" => t("Corabia"),
		"666767" => t("Slatina"),
	);
}


function location_cities_list_ro_mm () {
	return array (
		"685826" => t("Baia Mare"),
		"685823" => t("Baia Sprie"),
		"684156" => t("Borsa"),
		"667227" => t("Sighetu Marmatiei"),
	);
}


function location_cities_list_ro_sb () {
	return array (
		"681502" => t("Cisnadie"),
		"673634" => t("Medias"),
		"667268" => t("Sibiu"),
	);
}


function location_cities_list_ro_ab () {
	return array (
		"686590" => t("Aiud"),
		"686578" => t("Alba Iulia"),
		"684612" => t("Blaj"),
		"679995" => t("Cugir"),
		"672024" => t("Ocna Mures"),
		"667526" => t("Sebes"),
	);
}


function location_cities_list_ro_sm () {
	return array (
		"6697993" => t("Baia Mare"),
		"682685" => t("Carei"),
		"667873" => t("Satu Mare"),
	);
}


function location_cities_list_ro_bh () {
	return array (
		"671768" => t("Oradea"),
		"668129" => t("Salonta"),
	);
}


function location_cities_list_ro_vl () {
	return array (
		"678978" => t("Dragasani"),
		"668872" => t("Ramnicu Valcea"),
	);
}


function location_cities_list_ro_bz () {
	return array (
		"683123" => t("Buzau"),
		"668873" => t("Ramnicu Sarat"),
	);
}


function location_cities_list_ro_cs () {
	return array (
		"684490" => t("Bocsa"),
		"682729" => t("Caransebes"),
		"668954" => t("Resita"),
	);
}


function location_cities_list_ro_ph () {
	return array (
		"685811" => t("Baicoi"),
		"683760" => t("Breaza"),
		"681862" => t("Campina"),
		"673033" => t("Mizil"),
		"670474" => t("Ploiesti"),
	);
}


function location_cities_list_ro_ag () {
	return array (
		"679907" => t("Curtea de Arges"),
		"7733099" => t("Mioveni"),
		"670609" => t("Pitesti"),
	);
}


function location_cities_list_ro_hd () {
	return array (
		"683974" => t("Brad"),
		"679452" => t("Deva"),
		"675918" => t("Hunedoara"),
		"671757" => t("Orastie"),
		"670969" => t("Petrila"),
		"670938" => t("Petrosani"),
	);
}


function location_cities_list_ro_cl () {
	return array (
		"671832" => t("Oltenita"),
	);
}


function location_cities_list_ro_hr () {
	return array (
		"677458" => t("Gheorgheni"),
		"673441" => t("Miercurea-Ciuc"),
		"671964" => t("Odorheiu Secuiesc"),
	);
}


function location_cities_list_ro_ct () {
	return array (
		"682321" => t("Cernavoda"),
		"680963" => t("Constanta"),
		"673921" => t("Mangalia"),
		"673636" => t("Medgidia"),
		"672486" => t("Navodari"),
	);
}


function location_cities_list_ro_bc () {
	return array (
		"685948" => t("Bacau"),
		"683365" => t("Buhusi"),
		"681017" => t("Comanesti"),
		"672926" => t("Moinesti"),
	);
}


function location_cities_list_ro_is () {
	return array (
		"675810" => t("Iasi"),
		"6945426" => t("Pascani"),
	);
}


function location_cities_list_ro_gr () {
	return array (
		"677106" => t("Giurgiu"),
	);
}


function location_cities_list_ro_vn () {
	return array (
		"678015" => t("Focsani"),
	);
}


function location_cities_list_ro_dj () {
	return array (
		"685785" => t("Bailesti"),
		"683034" => t("Calafat"),
		"680332" => t("Craiova"),
		"678261" => t("Filiasi"),
	);
}


function location_cities_list_ro_mh () {
	return array (
		"678817" => t("Drobeta-Turnu Severin"),
	);
}


function location_cities_list_ro_bt () {
	return array (
		"684039" => t("Botosani"),
		"679065" => t("Dorohoi"),
	);
}


function location_cities_list_ro_b () {
	return array (
		"683506" => t("Bucharest"),
	);
}


function location_cities_list_ro_br () {
	return array (
		"683902" => t("Braila"),
	);
}


function location_cities_list_ro_bn () {
	return array (
		"684657" => t("Bistrita"),
	);
}


function location_cities_list_ro_ar () {
	return array (
		"686254" => t("Arad"),
	);
}


