<?php

function location_cities_list_at_bur()
{
  return array(
    '2780188' => t('Eisenstadt Stadt'),
    '2780189' => t('Politischer Bezirk Eisenstadt'),
    '2777215' => t('Politischer Bezirk Güssing'),
    '2775088' => t('Politischer Bezirk Jennersdorf'),
    '2771816' => t('Politischer Bezirk Mattersburg'),
    '2770682' => t('Politischer Bezirk Neusiedl am See'),
    '2769811' => t('Politischer Bezirk Oberpullendorf'),
    '2769621' => t('Politischer Bezirk Oberwart'),
    '2766935' => t('Rust Stadt'),
  );
}

function location_cities_list_at_sal()
{
  return array(
    '2776950' => t('Politischer Bezirk Hallein'),
    '2766817' => t('Politischer Bezirk Salzburg Umgebung'),
    '2766642' => t('Politischer Bezirk Sankt Johann im Pongau'),
    '2763928' => t('Politischer Bezirk Tamsweg'),
    '2760633' => t('Politischer Bezirk Zell am See'),
    '2766818' => t('Salzburg Stadt'),
  );
}

function location_cities_list_at_vor()
{
  return array(
    '2781679' => t('Politischer Bezirk Bludenz'),
    '2781502' => t('Politischer Bezirk Bregenz'),
    '2780740' => t('Politischer Bezirk Dornbirn'),
    '2779673' => t('Politischer Bezirk Feldkirch'),
  );
}

function location_cities_list_at_kar()
{
  return array(
    '2774321' => t('Klagenfurt am Wörthersee'),
    '6459021' => t('Politischer Bezirk Feldkirchen'),
    '2776496' => t('Politischer Bezirk Hermagor'),
    '2774323' => t('Politischer Bezirk Klagenfurt Land'),
    '2766358' => t('Politischer Bezirk Sankt Veit an der Glan'),
    '2764785' => t('Politischer Bezirk Spittal an der Drau'),
    '2762367' => t('Politischer Bezirk Villach Land'),
    '2762314' => t('Politischer Bezirk Völkermarkt'),
    '2760908' => t('Politischer Bezirk Wolfsberg'),
    '2762366' => t('Villach Stadt'),
  );
}

function location_cities_list_at_nos()
{
  return array(
    '2773547' => t('Krems an der Donau'),
    '2782554' => t('Politischer Bezirk Amstetten'),
    '2782066' => t('Politischer Bezirk Baden'),
    '2781372' => t('Politischer Bezirk Bruck an der Leitha'),
    '2778438' => t('Politischer Bezirk Gmünd'),
    '2778876' => t('Politischer Bezirk Gänserndorf'),
    '2775635' => t('Politischer Bezirk Hollabrunn'),
    '2775515' => t('Politischer Bezirk Horn'),
    '2773697' => t('Politischer Bezirk Korneuburg'),
    '2773548' => t('Politischer Bezirk Krems an der Donau'),
    '2772469' => t('Politischer Bezirk Lilienfeld'),
    '2771680' => t('Politischer Bezirk Melk'),
    '2771556' => t('Politischer Bezirk Mistelbach an der Zaya'),
    '2771333' => t('Politischer Bezirk Mödling'),
    '2770710' => t('Politischer Bezirk Neunkirchen'),
    '2766428' => t('Politischer Bezirk Sankt Pölten'),
    '2766079' => t('Politischer Bezirk Scheibbs'),
    '2763265' => t('Politischer Bezirk Tulln'),
    '2762078' => t('Politischer Bezirk Waidhofen an der Thaya'),
    '2761332' => t('Politischer Bezirk Wien Umgebung'),
    '2761352' => t('Politischer Bezirk Wiener Neustadt'),
    '2760421' => t('Politischer Bezirk Zwettl'),
    '2766426' => t('Sankt Pölten Stadt'),
    '6621168' => t('Waidhofen an der Ybbs'),
    '2761349' => t('Wiener Neustadt Stadt'),
  );
}

function location_cities_list_at_oos()
{
  return array(
    '2772395' => t('Linz Stadt'),
    '2781519' => t('Politischer Bezirk Braunau am Inn'),
    '2780393' => t('Politischer Bezirk Eferding'),
    '2779274' => t('Politischer Bezirk Freistadt'),
    '2778435' => t('Politischer Bezirk Gmunden'),
    '2777971' => t('Politischer Bezirk Grieskirchen'),
    '2774389' => t('Politischer Bezirk Kirchdorf an der Krems'),
    '2772396' => t('Politischer Bezirk Linz Land'),
    '2769104' => t('Politischer Bezirk Perg'),
    '2767470' => t('Politischer Bezirk Ried im Innkreis'),
    '2767290' => t('Politischer Bezirk Rohrbach'),
    '2766154' => t('Politischer Bezirk Schärding'),
    '2764357' => t('Politischer Bezirk Steyr-Land'),
    '2762517' => t('Politischer Bezirk Urfahr Umgebung'),
    '2762342' => t('Politischer Bezirk Vöcklabruck'),
    '2764347' => t('Steyr Stadt'),
    '7871309' => t('Wels(Stadt)'),
    '2761523' => t('Wels-Land'),
  );
}

function location_cities_list_at_ste()
{
  return array(
    '2778058' => t('Graz Stadt'),
    '2772752' => t('Leibnitz'),
    '2781022' => t('Politischer Berzirk Deutschlandsberg'),
    '2781370' => t('Politischer Bezirk Bruck an der Mur'),
    '2779681' => t('Politischer Bezirk Feldbach'),
    '2779114' => t('Politischer Bezirk Fürstenfeld'),
    '2778057' => t('Politischer Bezirk Graz Umgebung'),
    '2776799' => t('Politischer Bezirk Hartberg'),
    '2775019' => t('Politischer Bezirk Judenburg'),
    '2773886' => t('Politischer Bezirk Knittelfeld'),
    '2772648' => t('Politischer Bezirk Leoben'),
    '2772479' => t('Politischer Bezirk Liezen'),
    '2771016' => t('Politischer Bezirk Murau'),
    '2770992' => t('Politischer Bezirk Mürzzuschlag'),
    '2768118' => t('Politischer Bezirk Radkersburg'),
    '2762326' => t('Politischer Bezirk Voitsberg'),
    '2761530' => t('Politischer Bezirk Weiz'),
  );
}

function location_cities_list_at_tir()
{
  return array(
    '2775216' => t('Innsbruck Stadt'),
    '2774346' => t('Kitzbuehel'),
    '2773069' => t('Landeck'),
    '2775306' => t('Politischer Bezirk Imst'),
    '2775219' => t('Politischer Bezirk Innsbruck'),
    '2773299' => t('Politischer Bezirk Kufstein'),
    '2772504' => t('Politischer Bezirk Lienz'),
    '2767510' => t('Politischer Bezirk Reutte'),
    '2765389' => t('Politischer Bezirk Schwaz'),
  );
}

function location_cities_list_at_wie()
{
  return array(
    '2761333' => t('Politischer Bezirk Wien (Stadt)'),
  );
}
