<?php


function location_cities_list_rs_vo() {
  return array(
    "783814"  => "Zrenjanin",
    "784136"  => "Vrsac",
    "785559"  => "Stara Pazova",
    "785965"  => "Senta",
    "787237"  => "Pancevo",
    "789518"  => "Kikinda",
    "790015"  => "Ingija",
    "792814"  => "Becej",
    "3187297" => "Vrbas",
    "3189595" => "Subotica",
    "3190103" => "Sremska Mitrovica",
    "3190342" => "Sombor",
    "3191429" => "Ruma",
    "3194360" => "Novi Sad",
    "3204672" => "Backa Topola",
    "3204674" => "Backa Palanka",
    "3204793" => "Apatin",
  );
}


function location_cities_list_rs_se() {
  return array(
    "783920"  => "Zemun",
    "784024"  => "Zajecar",
    "784227"  => "Vranje",
    "784873"  => "Trstenik",
    "785753"  => "Smederevska Palanka",
    "785756"  => "Smederevo",
    "786690"  => "Prokuplje",
    "786827"  => "Pozarevac",
    "787050"  => "Pirot",
    "787516"  => "Obrenovac",
    "787595"  => "Novi Pazar",
    "787657"  => "Nis",
    "787718"  => "Negotin",
    "788709"  => "Leskovac",
    "788771"  => "Lazarevac",
    "788975"  => "Krusevac",
    "789107"  => "Kraljevo",
    "789128"  => "Kragujevac",
    "789923"  => "Jagodina",
    "790367"  => "Gornji Milanovac",
    "791678"  => "Cuprija",
    "792078"  => "Cacak",
    "792456"  => "Bor",
    "792680"  => "Belgrade",
    "793111"  => "Arangelovac",
    "3188402" => "Valjevo",
    "3188434" => "Uzice",
    "3191376" => "Sabac",
    "6619277" => "Knjazevac",
  );
}
