<?php


function location_cities_list_am_ag() {
  return array(
    "616877" => "Ashtarak",
  );
}


function location_cities_list_am_ar() {
  return array(
    "174979" => "Artashat",
    "174991" => "Ararat",
    "616435" => "Masis",
  );
}


function location_cities_list_am_av() {
  return array(
    "616062" => "Ejmiatsin",
    "616631" => "Armavir",
  );
}


function location_cities_list_am_gr() {
  return array(
    "616250" => "Sevan",
    "616599" => "Gavarr",
  );
}


function location_cities_list_am_kt() {
  return array(
    "616629" => "Hrazdan",
    "617026" => "Abovyan",
  );
}


function location_cities_list_am_lo() {
  return array(
    "616199" => "Spitak",
    "616530" => "Vanadzor",
  );
}


function location_cities_list_am_sh() {
  return array(
    "616635" => "Gyumri",
  );
}


function location_cities_list_am_su() {
  return array(
    "174875" => "Kapan",
    "174895" => "Goris",
    "174972" => "Hats'avan",
  );
}


function location_cities_list_am_tv() {
  return array();
}


function location_cities_list_am_vd() {
  return array();
}


function location_cities_list_am_er() {
  return array(
    "616052" => "Yerevan",
  );
}
