<?php

function location_cities_list_hk_hcw () {
	return array (
	);
}


function location_cities_list_hk_hea () {
	return array (
	);
}


function location_cities_list_hk_nis () {
	return array (
	);
}


function location_cities_list_hk_kkc () {
	return array (
		"1819609" => t("Kowloon"),
	);
}


function location_cities_list_hk_nkt () {
	return array (
	);
}


function location_cities_list_hk_kkt () {
	return array (
	);
}


function location_cities_list_hk_nno () {
	return array (
	);
}


function location_cities_list_hk_nsk () {
	return array (
	);
}


function location_cities_list_hk_nst () {
	return array (
		"1818920" => t("Sha Tin"),
	);
}


function location_cities_list_hk_kss () {
	return array (
	);
}


function location_cities_list_hk_hso () {
	return array (
	);
}


function location_cities_list_hk_ntp () {
	return array (
		"1818673" => t("Tai Po"),
	);
}


function location_cities_list_hk_ntw () {
	return array (
		"1818209" => t("Tsuen Wan"),
	);
}


function location_cities_list_hk_ntm () {
	return array (
		"1818446" => t("Tuen Mun"),
	);
}


function location_cities_list_hk_hwc () {
	return array (
	);
}


function location_cities_list_hk_kwt () {
	return array (
	);
}


function location_cities_list_hk_kyt () {
	return array (
	);
}


function location_cities_list_hk_nyl () {
	return array (
		"1818223" => t("Yuen Long Kau Hui"),
	);
}


function location_cities_list_hk_00 () {
	return array (
		"1819729" => t("Hong Kong"),
	);
}
