<?php


function location_cities_list_li_01() {
  return array();
}


function location_cities_list_li_02() {
  return array();
}


function location_cities_list_li_03() {
  return array();
}


function location_cities_list_li_04() {
  return array();
}


function location_cities_list_li_05() {
  return array();
}


function location_cities_list_li_06() {
  return array();
}


function location_cities_list_li_07() {
  return array();
}


function location_cities_list_li_08() {
  return array();
}


function location_cities_list_li_09() {
  return array();
}


function location_cities_list_li_10() {
  return array();
}


function location_cities_list_li_11() {
  return array(
    "3042030" => t("Vaduz"),
  );
}
