<?php


function location_cities_list_me_01() {
  return array();
}


function location_cities_list_me_02() {
  return array(
    "3204509" => "Bar",
  );
}


function location_cities_list_me_03() {
  return array();
}


function location_cities_list_me_04() {
  return array(
    "3204176" => "Bijelo Polje",
  );
}


function location_cities_list_me_05() {
  return array(
    "3203106" => "Budva",
  );
}


function location_cities_list_me_06() {
  return array(
    "3202641" => "Cetinje",
  );
}


function location_cities_list_me_07() {
  return array();
}


function location_cities_list_me_08() {
  return array(
    "3199394" => "Herceg-Novi",
  );
}


function location_cities_list_me_10() {
  return array();
}


function location_cities_list_me_11() {
  return array();
}


function location_cities_list_me_09() {
  return array();
}


function location_cities_list_me_12() {
  return array(
    "3194494" => "Niksic",
  );
}


function location_cities_list_me_13() {
  return array();
}


function location_cities_list_me_15() {
  return array();
}


function location_cities_list_me_17() {
  return array();
}


function location_cities_list_me_18() {
  return array();
}


function location_cities_list_me_21() {
  return array();
}


function location_cities_list_me_14() {
  return array(
    "3193161" => "Pljevlja",
  );
}


function location_cities_list_me_16() {
  return array(
    "3193044" => "Podgorica",
  );
}


function location_cities_list_me_19() {
  return array();
}


function location_cities_list_me_20() {
  return array();
}
