<?php


function location_cities_list_ch_ag() {
  return array(
    "2658011" => "Wettingen",
    "2661646" => "Baden",
    "2661881" => "Aarau",
  );
}


function location_cities_list_ch_ar() {
  return array(
    "2660365" => "Herisau",
  );
}


function location_cities_list_ch_bs() {
  return array(
    "2661604" => "Basel",
    "3206590" => "Riehen",
  );
}


function location_cities_list_ch_bl() {
  return array(
    "2659522" => "Muttenz",
    "2661810" => "Allschwil",
  );
}


function location_cities_list_ch_be() {
  return array(
    "2658377" => "Thun",
    "2658494" => "Steffisburg",
    "2660119" => "Koniz",
    "2661513" => "Biel/Bienne",
    "2661552" => "Bern",
  );
}


function location_cities_list_ch_fr() {
  return array(
    "2660718" => "Fribourg",
  );
}


function location_cities_list_ch_ge() {
  return array(
    "2658154" => "Vernier",
    "2659296" => "Onex",
    "2659667" => "Meyrin",
    "2660646" => "Geneve",
    "2661265" => "Carouge",
    "6691640" => "Lancy",
  );
}


function location_cities_list_ch_gl() {
  return array();
}


function location_cities_list_ch_gr() {
  return array(
    "2661169" => "Chur",
  );
}


function location_cities_list_ch_ju() {
  return array();
}


function location_cities_list_ch_ai() {
  return array();
}


function location_cities_list_ch_lu() {
  return array(
    "2659811" => "Luzern",
    "2659873" => "Littau",
    "2660104" => "Kriens",
    "2660911" => "Emmen",
  );
}


function location_cities_list_ch_ne() {
  return array(
    "2659496" => "Neuchatel",
    "2660076" => "La Chaux-de-Fonds",
  );
}


function location_cities_list_ch_nw() {
  return array();
}


function location_cities_list_ch_ow() {
  return array();
}


function location_cities_list_ch_sg() {
  return array(
    "2657996" => "Wil",
    "2658822" => "Sankt Gallen",
    "2659099" => "Rapperswil",
    "2660221" => "Jona",
    "2660549" => "Gossau",
  );
}


function location_cities_list_ch_sh() {
  return array(
    "2658761" => "Schaffhausen",
  );
}


function location_cities_list_ch_sz() {
  return array();
}


function location_cities_list_ch_so() {
  return array(
    "2659297" => "Olten",
    "2660512" => "Grenchen",
  );
}


function location_cities_list_ch_tg() {
  return array(
    "2660108" => "Kreuzlingen",
    "2660727" => "Frauenfeld",
  );
}


function location_cities_list_ch_ti() {
  return array(
    "2659836" => "Lugano",
    "2661567" => "Bellinzona",
  );
}


function location_cities_list_ch_ur() {
  return array();
}


function location_cities_list_ch_vs() {
  return array(
    "2658576" => "Sion",
    "2658606" => "Sierre",
    "2659613" => "Monthey",
  );
}


function location_cities_list_ch_vd() {
  return array(
    "2657941" => "Yverdon-les-Bains",
    "2658145" => "Vevey",
    "2659070" => "Renens",
    "2659127" => "Pully",
    "2659422" => "Nyon",
    "2659601" => "Montreux",
    "2659977" => "Le Chatelard",
    "2659994" => "Lausanne",
  );
}


function location_cities_list_ch_zg() {
  return array(
    "2657908" => "Zug",
    "2661653" => "Baar",
  );
}


function location_cities_list_ch_zh() {
  return array(
    "2657896" => "Zurich",
    "2657970" => "Winterthur",
    "2658216" => "Uster",
    "2658656" => "Zuerich (Kreis 11) / Seebach",
    "2659310" => "Zuerich (Kreis 11) / Oerlikon",
    "2660127" => "Kloten",
    "2660305" => "Horgen",
    "2660306" => "Zuerich (Kreis 10) / Hoengg",
    "2660971" => "Dubendorf",
    "2661015" => "Dietikon",
    "2661666" => "Aussersihl",
    "2661861" => "Adliswil",
    "6295475" => "Zuerich (Kreis 10) / Wipkingen",
    "6295484" => "Zuerich (Kreis 11) / Affoltern",
    "6295495" => "Zuerich (Kreis 2) / Wollishofen",
    "6295498" => "Zuerich (Kreis 3) / Sihlfeld",
    "6295504" => "Zuerich (Kreis 6) / Unterstrass",
    "6295512" => "Zuerich (Kreis 9) / Albisrieden",
    "6295513" => "Zuerich (Kreis 9) / Altstetten",
    "6295520" => "Stadt Winterthur (Kreis 1)",
    "6295523" => "Zuerich (Kreis 12)",
    "6295531" => "Seen (Kreis 3)",
    "6295532" => "Zuerich (Kreis 3)",
    "6295533" => "Zuerich (Kreis 11)",
    "6295534" => "Zuerich (Kreis 9)",
    "6295536" => "Oberwinterthur (Kreis 2)",
    "6295539" => "Zuerich (Kreis 10)",
    "6295540" => "Zuerich (Kreis 2)",
    "6295542" => "Zuerich (Kreis 8)",
    "6295548" => "Zuerich (Kreis 7)",
    "6295550" => "Zuerich (Kreis 6)",
  );
}
