<?php

function location_cities_list_bg_28 () {
	return array (
		"725578" => t("Yambol"),
	);
}


function location_cities_list_bg_06 () {
	return array (
		"725712" => t("Vratsa"),
	);
}


function location_cities_list_bg_05 () {
	return array (
		"725905" => t("Vidin"),
	);
}


function location_cities_list_bg_13 () {
	return array (
		"728448" => t("Panagyurishte"),
		"728378" => t("Pazardzhik"),
		"728317" => t("Peshtera"),
		"725988" => t("Velingrad"),
	);
}


function location_cities_list_bg_04 () {
	return array (
		"731233" => t("Gorna Oryakhovitsa"),
		"726534" => t("Svishtov"),
		"725993" => t("Veliko Turnovo"),
	);
}


function location_cities_list_bg_03 () {
	return array (
		"726050" => t("Varna"),
	);
}


function location_cities_list_bg_25 () {
	return array (
		"728075" => t("Popovo"),
		"726174" => t("Targovishte"),
	);
}


function location_cities_list_bg_11 () {
	return array (
		"729559" => t("Lovech"),
		"726320" => t("Troyan"),
	);
}


function location_cities_list_bg_08 () {
	return array (
		"726418" => t("Dobrich"),
	);
}


function location_cities_list_bg_26 () {
	return array (
		"732263" => t("Dimitrovgrad"),
		"730435" => t("Haskovo"),
		"730442" => t("Kharmanli"),
		"726546" => t("Svilengrad"),
	);
}


function location_cities_list_bg_24 () {
	return array (
		"732452" => t("Chirpan"),
		"730496" => t("Kazanluk"),
		"726848" => t("Stara Zagora"),
	);
}


function location_cities_list_bg_10 () {
	return array (
		"726872" => t("Dupnitsa"),
		"729730" => t("Kyustendil"),
	);
}


function location_cities_list_bg_22 () {
	return array (
		"727011" => t("Sofia"),
	);
}


function location_cities_list_bg_21 () {
	return array (
		"727030" => t("Smolyan"),
	);
}


function location_cities_list_bg_20 () {
	return array (
		"728742" => t("Nova Zagora"),
		"727079" => t("Sliven"),
	);
}


function location_cities_list_bg_19 () {
	return array (
		"727221" => t("Silistra"),
	);
}


function location_cities_list_bg_27 () {
	return array (
		"727233" => t("Shumen"),
	);
}


function location_cities_list_bg_07 () {
	return array (
		"731549" => t("Gabrovo"),
		"727337" => t("Sevlievo"),
	);
}


function location_cities_list_bg_01 () {
	return array (
		"733191" => t("Blagoevgrad"),
		"731108" => t("Gotse Delchev"),
		"728288" => t("Petrich"),
		"727447" => t("Sandanski"),
	);
}


function location_cities_list_bg_23 () {
	return array (
		"733014" => t("Botevgrad"),
		"727462" => t("Samokov"),
	);
}


function location_cities_list_bg_18 () {
	return array (
		"727523" => t("Ruse"),
	);
}


function location_cities_list_bg_17 () {
	return array (
		"727696" => t("Razgrad"),
	);
}


function location_cities_list_bg_16 () {
	return array (
		"733618" => t("Asenovgrad"),
		"730565" => t("Karlovo"),
		"728193" => t("Plovdiv"),
		"727791" => t("Rakovski"),
	);
}


function location_cities_list_bg_15 () {
	return array (
		"732491" => t("Cherven Bryag"),
		"728203" => t("Pleven"),
	);
}


function location_cities_list_bg_14 () {
	return array (
		"728330" => t("Pernik"),
	);
}


function location_cities_list_bg_12 () {
	return array (
		"733264" => t("Berkovitsa"),
		"729581" => t("Lom"),
		"729114" => t("Montana"),
	);
}


function location_cities_list_bg_09 () {
	return array (
		"729794" => t("Kurdzhali"),
	);
}


function location_cities_list_bg_02 () {
	return array (
		"733579" => t("Aytos"),
		"732770" => t("Burgas"),
		"730559" => t("Karnobat"),
	);
}


