<?php


function location_cities_list_ss_ec() {
  return array(
    "363619" => "Yei",
    "373303" => "Juba",
  );
}


function location_cities_list_ss_ee() {
  return array(
    "365742" => "Torit",
    "375495" => "Pajok",
  );
}


function location_cities_list_ss_jg() {
  return array(
    "377241" => "Bor",
  );
}


function location_cities_list_ss_lk() {
  return array(
    "367927" => "Rumbek",
  );
}


function location_cities_list_ss_bn() {
  return array(
    "364367" => "Aweil",
  );
}


function location_cities_list_ss_uy() {
  return array();
}


function location_cities_list_ss_nu() {
  return array(
    "370737" => "Malakal",
  );
}


function location_cities_list_ss_wr() {
  return array(
    "365763" => "Tonj",
    "374739" => "Gogrial",
  );
}


function location_cities_list_ss_bw() {
  return array(
    "363885" => "Wau",
  );
}


function location_cities_list_ss_ew() {
  return array(
    "363656" => "Yambio",
  );
}
