<?php


function location_cities_list_ht_ce() {
  return array(
    "3723841" => "Hinche",
  );
}


function location_cities_list_ht_15() {
  return array(
    "3720824" => "Miragoane",
  );
}


function location_cities_list_ht_ar() {
  return array(
    "3716044" => "Verrettes",
    "3717588" => "Saint-Marc",
    "3724696" => "Gonaives",
    "3726674" => "Desarmes",
  );
}


function location_cities_list_ht_ou() {
  return array(
    "3716667" => "Thomazeau",
    "3718426" => "Port-au-Prince",
    "3718962" => "Petit Goave",
    "3719028" => "Petionville",
    "3722286" => "Leogane",
    "3723440" => "Kenscoff",
    "3724233" => "Gressier",
    "3724337" => "Grand Goave",
    "3725276" => "Fond Parisien",
    "3726786" => "Delmas 73",
    "3727135" => "Croix des Bouquets",
    "3728338" => "Carrefour",
  );
}


function location_cities_list_ht_ga() {
  return array(
    "3723593" => "Jeremie",
  );
}


function location_cities_list_ht_ne() {
  return array();
}


function location_cities_list_ht_nd() {
  return array(
    "3717546" => "Saint-Raphael",
    "3722124" => "Limbe",
    "3728474" => "Cap-Haitien",
  );
}


function location_cities_list_ht_no() {
  return array(
    "3718420" => "Port-de-Paix",
    "3740016" => "Ti Port-de-Paix",
  );
}


function location_cities_list_ht_sd() {
  return array(
    "3728097" => "Les Cayes",
  );
}


function location_cities_list_ht_se() {
  return array(
    "3723779" => "Jacmel",
  );
}
