<?php


function location_cities_list_ee_37() {
  return array(
    "588409" => "Tallinn",
    "590447" => "Maardu",
  );
}


function location_cities_list_ee_39() {
  return array();
}


function location_cities_list_ee_44() {
  return array(
    "588686" => "Sillamae",
    "590031" => "Narva",
    "591260" => "Kohtla-Jarve",
  );
}


function location_cities_list_ee_51() {
  return array();
}


function location_cities_list_ee_49() {
  return array();
}


function location_cities_list_ee_57() {
  return array();
}


function location_cities_list_ee_59() {
  return array(
    "589165" => "Rakvere",
  );
}


function location_cities_list_ee_67() {
  return array(
    "589580" => "Parnu",
  );
}


function location_cities_list_ee_65() {
  return array();
}


function location_cities_list_ee_70() {
  return array();
}


function location_cities_list_ee_74() {
  return array();
}


function location_cities_list_ee_78() {
  return array(
    "588335" => "Tartu",
  );
}


function location_cities_list_ee_82() {
  return array();
}


function location_cities_list_ee_84() {
  return array(
    "587577" => "Viljandi",
  );
}


function location_cities_list_ee_86() {
  return array();
}
