<?php

function location_cities_list_ba_bih () {
	return array (
		"3204222" => t("Bihac"),
		"3203653" => t("Bosanska Krupa"),
		"3203099" => t("Bugojno"),
		"3202822" => t("Cazin"),
		"3200396" => t("Gorazde"),
		"3199779" => t("Gracanica"),
		"3199744" => t("Gradacac"),
		"3337476" => t("Konjic"),
		"3194828" => t("Mostar"),
		"3191281" => t("Sarajevo"),
		"3188924" => t("Travnik"),
		"3188582" => t("Tuzla"),
		"3188225" => t("Velika Kladusa"),
		"3187609" => t("Visoko"),
		"3186573" => t("Zenica"),
	);
}


function location_cities_list_ba_srp () {
	return array (
		"3204541" => t("Banja Luka"),
		"3204186" => t("Bijeljina"),
		"3201984" => t("Doboj"),
		"3192409" => t("Prijedor"),
		"3188893" => t("Trebinje"),
	);
}


function location_cities_list_ba_brc () {
	return array (
		"3203521" => t("Brcko"),
	);
}


