<?php


function location_cities_list_tr_01() {
  return array(
    "306112" => "Kozan",
    "310892" => "Kadirli",
    "311453" => "Imamoglu",
    "318675" => "Ceyhan",
    "322391" => "Bahce",
    "325363" => "Adana",
  );
}


function location_cities_list_tr_02() {
  return array(
    "310855" => "Kahta",
    "314136" => "Golbasi",
    "321337" => "Besni",
    "325330" => "Adiyaman",
  );
}


function location_cities_list_tr_03() {
  return array(
    "301911" => "Sandikli",
    "315621" => "Emirdag",
    "316634" => "Dinar",
    "319104" => "Cay",
    "320879" => "Bolvadin",
    "325303" => "Afyonkarahisar",
  );
}


function location_cities_list_tr_68() {
  return array(
    "303290" => "Ortakoy",
    "324496" => "Aksaray",
  );
}


function location_cities_list_tr_05() {
  return array(
    "739015" => "Tasova",
    "739251" => "Suluova",
    "741609" => "Merzifon",
    "752015" => "Amasya",
  );
}


function location_cities_list_tr_06() {
  return array(
    "301116"  => "Sereflikochisar",
    "302525"  => "Polatli",
    "315720"  => "Elmadag",
    "323786"  => "Ankara",
    "442301"  => "Batikent",
    "741347"  => "Nallihan",
    "743051"  => "Kizilcahamam",
    "743615"  => "Kazan",
    "748870"  => "Cubuk",
    "750637"  => "Beypazari",
    "6955677" => "Cankaya",
  );
}


function location_cities_list_tr_07() {
  return array(
    "299445" => "Tekirova",
    "301101" => "Serik",
    "304854" => "Manavgat",
    "305680" => "Beykonak",
    "306474" => "Korkuteli",
    "308220" => "Kemer",
    "314812" => "Gazipasa",
    "315697" => "Elmali",
    "321580" => "Belek",
    "323777" => "Antalya",
    "324190" => "Alanya",
  );
}


function location_cities_list_tr_75() {
  return array(
    "751952" => "Ardahan",
  );
}


function location_cities_list_tr_08() {
  return array(
    "745530" => "Hopa",
    "751817" => "Artvin",
    "751931" => "Arhavi",
  );
}


function location_cities_list_tr_09() {
  return array(
    "297090" => "Didim",
    "300399" => "Soeke",
    "303873" => "Nazilli",
    "305359" => "Kusadasi",
    "311314" => "Incirliova",
    "318372" => "Cine",
    "322830" => "Aydin",
  );
}


function location_cities_list_tr_04() {
  return array(
    "302819" => "Patnos",
    "309647" => "Agri",
    "315758" => "Eleskirt",
    "316411" => "Dogubayazit",
    "316542" => "Diyadin",
  );
}


function location_cities_list_tr_10() {
  return array(
    "300058" => "Susurluk",
    "315985" => "Edremit",
    "316102" => "Dursunbey",
    "320369" => "Burhaniye",
    "321136" => "Bigadic",
    "322165" => "Balikesir",
    "322673" => "Ayvalik",
    "746574" => "Gonen",
    "747482" => "Erdek",
    "751077" => "Bandirma",
  );
}


function location_cities_list_tr_74() {
  return array(
    "751057" => "Bartin",
  );
}


function location_cities_list_tr_72() {
  return array(
    "306041" => "Kozluk",
    "321836" => "Batman",
  );
}


function location_cities_list_tr_69() {
  return array(
    "750938" => "Bayburt",
  );
}


function location_cities_list_tr_11() {
  return array(
    "320557" => "Bozuyuk",
    "740881" => "Osmaneli",
    "750598" => "Bilecik",
  );
}


function location_cities_list_tr_12() {
  return array(
    "300377" => "Solhan",
    "314648" => "Genc",
    "321082" => "Bingol",
  );
}


function location_cities_list_tr_13() {
  return array(
    "299582" => "Tatvan",
    "312024" => "Hizan",
    "313331" => "Guroymak",
    "321025" => "Bitlis",
    "325103" => "Ahlat",
    "325336" => "Adilcevaz",
  );
}


function location_cities_list_tr_14() {
  return array(
    "746940" => "Gerede",
    "750516" => "Bolu",
  );
}


function location_cities_list_tr_15() {
  return array(
    "320392" => "Burdur",
    "320533" => "Bucak",
  );
}


function location_cities_list_tr_16() {
  return array(
    "737611" => "Yenisehir",
    "741045" => "Orhangazi",
    "741487" => "Mudanya",
    "743404" => "Kestel",
    "744537" => "Karacabey",
    "745026" => "Iznik",
    "745169" => "Inegeul",
    "746232" => "Gursu",
    "746958" => "Gemlik",
    "750269" => "Bursa",
  );
}


function location_cities_list_tr_20() {
  return array(
    "301827" => "Saraykoy",
    "307211" => "Serinhisar",
    "317109" => "Denizli",
  );
}


function location_cities_list_tr_21() {
  return array(
    "300796" => "Silvan",
    "305089" => "Lice",
    "305750" => "Kulp",
    "315468" => "Ergani",
    "316541" => "Diyarbakir",
    "318766" => "Cermik",
    "321031" => "Bismil",
  );
}


function location_cities_list_tr_81() {
  return array(
    "747764" => "Duzce",
    "752584" => "Akcakoca",
  );
}


function location_cities_list_tr_22() {
  return array(
    "738251" => "Uzun Keupru",
    "743439" => "Kesan",
    "747712" => "Edirne",
  );
}


function location_cities_list_tr_23() {
  return array(
    "306207" => "Kovancilar",
    "309663" => "Karakocan",
    "315808" => "Elazig",
    "321929" => "Baskil",
  );
}


function location_cities_list_tr_24() {
  return array(
    "298230" => "Cimin",
    "315373" => "Erzincan",
  );
}


function location_cities_list_tr_25() {
  return array(
    "302824" => "Pasinler",
    "310004" => "Karacoban",
    "312114" => "Hinis",
    "315368" => "Erzurum",
    "323094" => "Askale",
    "741160" => "Oltu",
    "745527" => "Horasan",
  );
}


function location_cities_list_tr_26() {
  return array(
    "315202" => "Eskisehir",
  );
}


function location_cities_list_tr_27() {
  return array(
    "303798" => "Nizip",
    "314830" => "Gaziantep",
  );
}


function location_cities_list_tr_28() {
  return array(
    "738753" => "Tirebolu",
    "739914" => "Sebinkarahisar",
    "746565" => "Gorele",
    "746881" => "Giresun",
    "750317" => "Bulancak",
    "831432" => "Espiye",
  );
}


function location_cities_list_tr_29() {
  return array(
    "743537" => "Kelkit",
    "746425" => "Gumushkhane",
  );
}


function location_cities_list_tr_30() {
  return array(
    "296173" => "Yuksekova",
    "301209" => "Semdinli",
    "318137" => "Hakkari",
  );
}


function location_cities_list_tr_31() {
  return array(
    "296852" => "Erzin",
    "301089" => "Serinyol",
    "302355" => "Reyhanli",
    "307657" => "Kirikhan",
    "311111" => "Iskenderun",
    "316284" => "Dortyol",
    "321572" => "Belen",
    "323779" => "Antioch",
    "438400" => "Denizciler",
  );
}


function location_cities_list_tr_32() {
  return array(
    "297789" => "Yalvac",
    "301172" => "Senirkent",
    "301539" => "Sarkikaraagac",
    "311073" => "Isparta",
    "315905" => "Egirdir",
  );
}


function location_cities_list_tr_34() {
  return array(
    "737071"  => "Zeytinburnu",
    "738064"  => "Yakuplu",
    "738329"  => "UEskuedar",
    "738377"  => "Umraniye",
    "738858"  => "Tepecik",
    "739549"  => "Sisli",
    "739634"  => "Silivri",
    "741529"  => "Mimarsinan",
    "741763"  => "Maltepe",
    "743818"  => "Kavakli",
    "745044"  => "Istanbul",
    "746234"  => "Gurpinar",
    "747323"  => "Esenyurt",
    "747340"  => "Esenler",
    "747538"  => "Eminoenue",
    "749644"  => "Catalca",
    "751324"  => "Bagcilar",
    "6354984" => "merter keresteciler",
    "6354985" => "guengoeren merter",
    "6947637" => "Atasehir",
    "6947639" => "Basaksehir",
    "6947640" => "Beylikduezue",
    "6947641" => "Bueyuekcekmece",
    "7627067" => "Bahcelievler",
    "7628416" => "Sultangazi",
    "7628419" => "Sultanbeyli",
    "7628420" => "Sancaktepe",
  );
}


function location_cities_list_tr_76() {
  return array(
    "311665" => "Igdir",
  );
}


function location_cities_list_tr_46() {
  return array(
    "302800" => "Pazarcik",
    "310859" => "Kahramanmaras",
    "314188" => "Goksun",
    "315795" => "Elbistan",
    "320004" => "Caglayancerit",
    "325304" => "Afsin",
  );
}


function location_cities_list_tr_78() {
  return array(
    "740430" => "Safranbolu",
    "744562" => "Karabuk",
  );
}


function location_cities_list_tr_70() {
  return array(
    "309527" => "Karaman",
    "315401" => "Ermenek",
  );
}


function location_cities_list_tr_36() {
  return array(
    "740088" => "Sarikamis",
    "743952" => "Kars",
    "744873" => "Kagizman",
  );
}


function location_cities_list_tr_37() {
  return array(
    "738662" => "Tosya",
    "739061" => "Taskopru",
    "743882" => "Kastamonu",
  );
}


function location_cities_list_tr_38() {
  return array(
    "297917" => "Yahyali",
    "299900" => "Talas",
    "308464" => "Kayseri",
    "313013" => "Hacilar",
    "316795" => "Develi",
  );
}


function location_cities_list_tr_79() {
  return array(
    "307864" => "Kilis",
  );
}


function location_cities_list_tr_41() {
  return array(
    "737961" => "Korfez",
    "744168" => "Karamursel",
    "745028" => "Izmit",
    "746666" => "Geulzuk",
    "747014" => "Gebze",
  );
}


function location_cities_list_tr_42() {
  return array(
    "301010" => "Seydisehir",
    "305742" => "Kulu",
    "306571" => "Konya",
    "309415" => "Karapinar",
    "310907" => "Kadinhani",
    "311553" => "Ilgin",
    "312899" => "Hadim",
    "315498" => "Eregli",
    "317844" => "Cumra",
    "321191" => "Beysehir",
    "324490" => "Aksehir",
  );
}


function location_cities_list_tr_43() {
  return array(
    "299545" => "Tavsanli",
    "300791" => "Simav",
    "305268" => "Kutahya",
    "314716" => "Gediz",
    "315639" => "Emet",
  );
}


function location_cities_list_tr_39() {
  return array(
    "741855" => "Luleburgaz",
    "743166" => "Kirklareli",
    "751371" => "Babaeski",
  );
}


function location_cities_list_tr_71() {
  return array(
    "307654" => "Kirikkale",
    "308024" => "Keskin",
  );
}


function location_cities_list_tr_40() {
  return array(
    "304196" => "Mucur",
    "307515" => "Kirsehir",
    "310641" => "Kaman",
  );
}


function location_cities_list_tr_44() {
  return array(
    "304922" => "Malatya",
    "317588" => "Darende",
  );
}


function location_cities_list_tr_45() {
  return array(
    "298806" => "Turgutlu",
    "300371" => "Soma",
    "302043" => "Salihli",
    "304827" => "Manisa",
    "305810" => "Kula",
    "307623" => "Kirkagac",
    "317241" => "Demirci",
    "324172" => "Alasehir",
    "324698" => "Akhisar",
  );
}


function location_cities_list_tr_47() {
  return array(
    "296832" => "Yesilli",
    "303750" => "Nusaybin",
    "304382" => "Midyat",
    "304797" => "Mardin",
    "307084" => "Kiziltepe",
    "317587" => "Dargecit",
  );
}


function location_cities_list_tr_33() {
  return array(
    "299817" => "Tarsus",
    "300808" => "Silifke",
    "304013" => "Mut",
    "304531" => "Mercin",
    "315515" => "Erdemli",
    "320552" => "Bozyazi",
    "323828" => "Anamur",
  );
}


function location_cities_list_tr_48() {
  return array(
    "297564"  => "Yatagan",
    "303354"  => "Ortaca",
    "304184"  => "Mugla",
    "304355"  => "Milas",
    "304782"  => "Marmaris",
    "314967"  => "Fethiye",
    "320995"  => "Bodrum",
    "447273"  => "Dalaman",
    "6692524" => "Sarigerme",
  );
}


function location_cities_list_tr_49() {
  return array(
    "298088" => "Varto",
    "304081" => "Mus",
    "304916" => "Malazgirt",
    "320448" => "Bulanik",
  );
}


function location_cities_list_tr_50() {
  return array(
    "298326" => "Urgub",
    "303831" => "Nevsehir",
  );
}


function location_cities_list_tr_51() {
  return array(
    "303827" => "Nigde",
    "320871" => "Bor",
  );
}


function location_cities_list_tr_52() {
  return array(
    "738349" => "Unieh",
    "741100" => "Ordu",
    "742238" => "Kumru",
    "742658" => "Korgan",
    "746252" => "Gurgentepe",
    "747155" => "Fatsa",
  );
}


function location_cities_list_tr_80() {
  return array(
    "303195" => "Osmaniye",
  );
}


function location_cities_list_tr_53() {
  return array(
    "740483" => "Rize",
    "749502" => "Cayeli",
    "751949" => "Ardesen",
  );
}


function location_cities_list_tr_54() {
  return array(
    "740230" => "Sapanca",
    "742902" => "Kocaali",
    "744093" => "Karasu",
    "745664" => "Hendek",
    "746898" => "Geyve",
    "747135" => "Ferizli",
    "752288" => "Akyazi",
    "752850" => "Adapazari",
  );
}


function location_cities_list_tr_55() {
  return array(
    "738167" => "Vezirkopru",
    "738803" => "Terme",
    "738907" => "Tekkekoy",
    "740264" => "Samsun",
    "745714" => "Havza",
    "749704" => "Carsamba",
    "751335" => "Bafra",
  );
}


function location_cities_list_tr_56() {
  return array(
    "300822" => "Siirt",
    "305532" => "Kurtalan",
  );
}


function location_cities_list_tr_57() {
  return array(
    "739600" => "Sinop",
    "750468" => "Boyabat",
  );
}


function location_cities_list_tr_58() {
  return array(
    "300619" => "Sivas",
    "301537" => "Sarkisla",
    "314665" => "Gemerek",
    "739209" => "Susehri",
  );
}


function location_cities_list_tr_59() {
  return array(
    "738927" => "Tekirdag",
    "741771" => "Malkara",
    "745697" => "Hayrabolu",
    "748893" => "Corlu",
    "749274" => "Cerkezkoey",
  );
}


function location_cities_list_tr_60() {
  return array(
    "737054" => "Zile",
    "738618" => "Turhal",
    "738743" => "Tokat",
    "741304" => "Niksar",
    "747489" => "Erbaa",
  );
}


function location_cities_list_tr_61() {
  return array(
    "737421" => "Yomra",
    "738228" => "Vakfikebir",
    "738648" => "Trabzon",
    "739215" => "Surmene",
    "741240" => "Of",
    "750735" => "Besikduzu",
    "751838" => "Arsin",
    "751971" => "Arakli",
    "752627" => "Akcaabat",
  );
}


function location_cities_list_tr_62() {
  return array(
    "298846" => "Tunceli",
  );
}


function location_cities_list_tr_64() {
  return array(
    "298299" => "Usak",
    "322051" => "Banaz",
  );
}


function location_cities_list_tr_65() {
  return array(
    "298117" => "Van",
    "315530" => "Ercis",
  );
}


function location_cities_list_tr_77() {
  return array(
    "738025" => "Yalova",
  );
}


function location_cities_list_tr_66() {
  return array(
    "296562" => "Yozgat",
    "296895" => "Yerkoy",
    "300352" => "Sorgun",
    "324768" => "Akdagmadeni",
  );
}


function location_cities_list_tr_67() {
  return array(
    "737022" => "Zonguldak",
    "747471" => "Eregli",
    "748167" => "Devrek",
    "749508" => "Caycuma",
    "752184" => "Alapli",
  );
}


function location_cities_list_tr_17() {
  return array(
    "315061" => "Ezine",
    "746983" => "Gelibolu",
    "749780" => "Canakkale",
    "749795" => "Can",
    "750605" => "Biga",
  );
}


function location_cities_list_tr_18() {
  return array(
    "749279" => "Cerkes",
    "749748" => "Khanjarah",
  );
}


function location_cities_list_tr_19() {
  return array(
    "739236" => "Sungurlu",
    "740883" => "Osmancik",
    "745076" => "Iskilip",
    "748879" => "Corum",
    "752278" => "Alaca",
  );
}


function location_cities_list_tr_35() {
  return array(
    "298316"  => "Urla",
    "298935"  => "Torbali",
    "299137"  => "Tire",
    "301256"  => "Selcuk",
    "301350"  => "Seferihisar",
    "303700"  => "Hypaepa",
    "304612"  => "Menemen",
    "308224"  => "Kemalpasa",
    "311046"  => "Izmir",
    "314903"  => "Foca",
    "317851"  => "Menderes",
    "318755"  => "Cesme",
    "321426"  => "Bergama",
    "321786"  => "Bayindir",
    "324106"  => "Aliaga",
    "7701384" => "Karabaglar",
  );
}


function location_cities_list_tr_63() {
  return array(
    "298033" => "Viransehir",
    "298333" => "Sanliurfa",
    "300075" => "Suruc",
    "300614" => "Siverek",
    "312134" => "Hilvan",
    "318668" => "Ceylanpinar",
    "320581" => "Bozova",
    "321062" => "Birecik",
    "324944" => "Akcakale",
  );
}


function location_cities_list_tr_73() {
  return array(
    "300640" => "Sirnak",
    "300797" => "Silopi",
    "311704" => "Idil",
    "318253" => "Cizre",
  );
}
