<?php

function location_cities_list_qa_us () {
	return array (
		"289523" => t("Umm Salal Muhammad"),
	);
}


function location_cities_list_qa_ra () {
	return array (
		"289888" => t("Ar Rayyan"),
	);
}


function location_cities_list_qa_wa () {
	return array (
		"289915" => t("Al Wakrah"),
	);
}


function location_cities_list_qa_kh () {
	return array (
		"289962" => t("Al Khawr"),
	);
}


function location_cities_list_qa_da () {
	return array (
		"290030" => t("Doha"),
	);
}


