<?php

function location_cities_list_so_sh () {
	return array (
		"65785" => t("Afgooye"),
		"54225" => t("Marka"),
		"52867" => t("Qoryooley"),
		"50672" => t("Wanlaweyn"),
	);
}


function location_cities_list_so_br () {
	return array (
		"64013" => t("Bosaso"),
		"53157" => t("Qandala"),
	);
}


function location_cities_list_so_bn () {
	return array (
		"53654" => t("Mogadishu"),
	);
}


function location_cities_list_so_ge () {
	return array (
		"65170" => t("Baardheere"),
		"54715" => t("Luuq"),
	);
}


function location_cities_list_so_jh () {
	return array (
		"56399" => t("Jamaame"),
		"55671" => t("Kismayo"),
	);
}


function location_cities_list_so_jd () {
	return array (
		"56166" => t("Jilib"),
	);
}


function location_cities_list_so_sd () {
	return array (
		"56335" => t("Jawhar"),
	);
}


function location_cities_list_so_wo () {
	return array (
		"64435" => t("Berbera"),
		"57289" => t("Hargeysa"),
	);
}


function location_cities_list_so_nu () {
	return array (
		"60019" => t("Eyl"),
		"58933" => t("Garoowe"),
	);
}


function location_cities_list_so_mu () {
	return array (
		"59611" => t("Gaalkacyo"),
	);
}


function location_cities_list_so_sa () {
	return array (
		"62691" => t("Ceerigaabo"),
	);
}


function location_cities_list_so_ga () {
	return array (
		"62788" => t("Ceeldheer"),
	);
}


function location_cities_list_so_by () {
	return array (
		"64536" => t("Baydhabo"),
		"63571" => t("Buurhakaba"),
	);
}


function location_cities_list_so_hi () {
	return array (
		"64460" => t("Beledweyne"),
		"63689" => t("Buulobarde"),
	);
}


function location_cities_list_so_to () {
	return array (
		"63795" => t("Burco"),
	);
}


function location_cities_list_so_so () {
	return array (
		"400769" => t("Laascaanood"),
	);
}


function location_cities_list_so_aw () {
	return array (
		"8045596" => t("Baki"),
	);
}


