<?php


function location_cities_list_ua_43() {
  return array(
    "688105" => t("Yevpatoriya"),
    "688533" => t("Yalta"),
    "693805" => t("Simferopol'"),
    "694910" => t("Saky"),
    "700019" => t("Nyzhn'ohirs'kyy"),
    "700997" => t("Miskhor"),
    "704362" => t("Krasnoperekops'k"),
    "706524" => t("Kerch"),
    "709161" => t("Feodosiya"),
    "709334" => t("Dzhankoy"),
    "712587" => t("Bilohirs'k"),
    "712969" => t("Bakhchysaray"),
    "713203" => t("Armyans'k"),
    "713513" => t("Alushta"),
  );
}


function location_cities_list_ua_71() {
  return array(
    "686803" => t("Zvenyhorodka"),
    "686875" => t("Zolotonosha"),
    "687245" => t("Zhashkiv"),
    "690312" => t("Vatutine"),
    "690688" => t("Uman'"),
    "691936" => t("Tal'ne"),
    "693457" => t("Smila"),
    "693920" => t("Shpola"),
    "704858" => t("Korsun'-Shevchenkivs'kyy"),
    "706900" => t("Kaniv"),
    "708366" => t("Horodyshche"),
    "710791" => t("Cherkasy"),
  );
}


function location_cities_list_ua_74() {
  return array(
    "696108" => t("Pryluky"),
    "699917" => t("Nosivka"),
    "699942" => t("Nizhyn"),
    "710735" => t("Chernihiv"),
    "712967" => t("Bakhmach"),
  );
}


function location_cities_list_ua_77() {
  return array(
    "710719" => t("Chernivtsi"),
  );
}


function location_cities_list_ua_12() {
  return array(
    "687196" => t("Zhovti Vody"),
    "693796" => t("Synel'nykove"),
    "695965" => t("Piatykhatky"),
    "696943" => t("Pidhorodne"),
    "697889" => t("Pavlohrad"),
    "699445" => t("Novomoskovs'k"),
    "700051" => t("Nikopol'"),
    "701855" => t("Marhanets'"),
    "703845" => t("Kryvyy Rih"),
    "709930" => t("Dnipropetrovsk"),
    "709932" => t("Dniprodzerzhyns'k"),
    "713245" => t("Apostolove"),
  );
}


function location_cities_list_ua_14() {
  return array(
    "616743" => t("Druzhkovka"),
    "686818" => t("Zuhres"),
    "688148" => t("Yenakiyeve"),
    "688373" => t("Yasinovataya"),
    "689198" => t("Volnovakha"),
    "691374" => t("Torez"),
    "693381" => t("Snizhne"),
    "693468" => t("Sloviansk"),
    "694382" => t("Shakhtersk"),
    "694677" => t("Selidovo"),
    "701822" => t("Mariupol"),
    "702320" => t("Makiyivka"),
    "703646" => t("Kurakhovo"),
    "704204" => t("Krasnyy Liman"),
    "704422" => t("Krasnoarmiys'k"),
    "704508" => t("Kramators'k"),
    "705104" => t("Kostyantynivka"),
    "706466" => t("Khartsyzsk"),
    "707679" => t("Ilovays'k"),
    "707753" => t("Horlivka"),
    "709354" => t("Dzerzhyns'k"),
    "709717" => t("Donets'k"),
    "709835" => t("Dokuchayevsk"),
    "709900" => t("Dobropol'ye"),
    "710229" => t("Debal'tsevo"),
    "713122" => t("Avdeyevka"),
    "713174" => t("Artemivs'k"),
    "713504" => t("Amvrosiyivka"),
  );
}


function location_cities_list_ua_26() {
  return array(
    "700507" => t("Nadvirna"),
    "705392" => t("Kolomyya"),
    "707099" => t("Kalush"),
    "707471" => t("Ivano-Frankivs'k"),
    "709755" => t("Dolyna"),
  );
}


function location_cities_list_ua_63() {
  return array(
    "686928" => t("Zmiyev"),
    "689304" => t("Vovchans'k"),
    "701347" => t("Merefa"),
    "702417" => t("Lyubotyn"),
    "702760" => t("Lozova"),
    "703656" => t("Kupjansk"),
    "704388" => t("Krasnohrad"),
    "704608" => t("Kivsharivka"),
    "705183" => t("Komsomol's'ke"),
    "706483" => t("Kharkiv"),
    "707292" => t("Izyum"),
    "710098" => t("Derhachy"),
    "710374" => t("Chuhuyiv"),
    "711894" => t("Bohodukhiv"),
    "712926" => t("Balakliya"),
  );
}


function location_cities_list_ua_65() {
  return array(
    "691037" => t("Tsyurupyns'k"),
    "693709" => t("Skadovsk"),
    "699839" => t("Nova Kakhovka"),
    "706448" => t("Kherson"),
    "707244" => t("Kakhovka"),
    "708632" => t("Hola Prystan'"),
    "708878" => t("Heniches'k"),
  );
}


function location_cities_list_ua_68() {
  return array(
    "692818" => t("Starokostyantyniv"),
    "693581" => t("Slavuta"),
    "694216" => t("Shepetivka"),
    "696660" => t("Polonne"),
    "700261" => t("Netishyn"),
    "704492" => t("Krasyliv"),
    "706369" => t("Khmel'nyts'kyy"),
    "706950" => t("Kamieniec Podolski"),
    "707296" => t("Izyaslav"),
    "707752" => t("Horodok"),
    "709429" => t("Dunaivtsi"),
  );
}


function location_cities_list_ua_35() {
  return array(
    "686919" => t("Znomenka"),
    "692087" => t("Svitlovods'k"),
    "698625" => t("Oleksandriya"),
    "699078" => t("Novoukrayinka"),
    "705812" => t("Kirovohrad"),
    "708898" => t("Hayvoron"),
    "709782" => t("Dolyns'ka"),
  );
}


function location_cities_list_ua_30() {
  return array(
    "703448" => t("Kiev"),
  );
}


function location_cities_list_ua_32() {
  return array(
    "688587"  => t("Yahotyn"),
    "688723"  => t("Vyshhorod"),
    "689487"  => t("Vyshneve"),
    "690412"  => t("Vasyl'kiv"),
    "693615"  => t("Skvyra"),
    "697637"  => t("Pereyaslav-Khmel'nyts'kyy"),
    "698782"  => t("Obukhiv"),
    "707565"  => t("Irpin'"),
    "709248"  => t("Fastiv"),
    "711350"  => t("Bucha"),
    "711390"  => t("Brovary"),
    "711515"  => t("Boyarka"),
    "711660"  => t("Boryspil'"),
    "711867"  => t("Bohuslav"),
    "712165"  => t("Bila Tserkva"),
    "6930327" => t("Slavutich"),
  );
}


function location_cities_list_ua_09() {
  return array(
    "691999" => t("Syeverodonets'k"),
    "692105" => t("Sverdlovs'k"),
    "692118" => t("Svatove"),
    "692832" => t("Starobil's'k"),
    "692975" => t("Stakhanov"),
    "695274" => t("Rubizhne"),
    "695379" => t("Roven'ki"),
    "696566" => t("Popasnaya"),
    "697592" => t("Pervomaysk"),
    "697650" => t("Pereval'sk"),
    "700829" => t("Molodogvardeysk"),
    "702563" => t("Lutugino"),
    "702658" => t("Luhans'k"),
    "702972" => t("Lisichansk"),
    "704138" => t("Kreminna"),
    "704202" => t("Krasnyy Luch"),
    "704403" => t("Krasnodon"),
    "705809" => t("Kirovsk"),
    "710548" => t("Chervonopartizansk"),
    "711369" => t("Bryanka"),
    "713259" => t("Antratsit"),
    "713716" => t("Alchevs'k"),
  );
}


function location_cities_list_ua_46() {
  return array(
    "686896"  => t("Zolochiv"),
    "691179"  => t("Truskavets"),
    "692372"  => t("Stryi"),
    "692632"  => t("Stebnyk"),
    "693301"  => t("Sokal'"),
    "694864"  => t("Sambir"),
    "702550"  => t("L'viv"),
    "708313"  => t("Horodok"),
    "709611"  => t("Drohobych"),
    "710554"  => t("Chervonohrad"),
    "711416"  => t("Brody"),
    "711669"  => t("Boryslav"),
    "8468760" => t("Novoyavorivs'k"),
  );
}


function location_cities_list_ua_40() {
  return array(
    "694423" => t("Sevastopol"),
    "712930" => t("Balaklava"),
  );
}


function location_cities_list_ua_48() {
  return array(
    "688860"  => t("Voznesensk"),
    "697593"  => t("Pervomays'k"),
    "698770"  => t("Ochakiv"),
    "698953"  => t("Novyy Buh"),
    "700569"  => t("Mykolayiv"),
    "7525990" => t("Yuzhnoukrains'k"),
  );
}


function location_cities_list_ua_51() {
  return array(
    "687997" => t("Yuzhne"),
    "695344" => t("Rozdil'na"),
    "695670" => t("Reni"),
    "698740" => t("Odessa"),
    "704679" => t("Kotovs'k"),
    "705883" => t("Kiliya"),
    "707308" => t("Izmayil"),
    "707688" => t("Illichivs'k"),
    "711841" => t("Bolhrad"),
    "712160" => t("Bilhorod-Dnistrovs'kyy"),
    "712886" => t("Balta"),
    "713163" => t("Artsyz"),
  );
}


function location_cities_list_ua_53() {
  return array(
    "696643"  => t("Poltava"),
    "697183"  => t("Pyryatyn"),
    "701075"  => t("Myrhorod"),
    "702723"  => t("Lubny"),
    "704147"  => t("Kremenchuk"),
    "706749"  => t("Karlivka"),
    "709054"  => t("Hadyach"),
    "6559559" => t("Komsomolsk"),
  );
}


function location_cities_list_ua_56() {
  return array(
    "687432" => t("Zdolbuniv"),
    "694792" => t("Sarny"),
    "695594" => t("Rivne"),
    "703464" => t("Kuznetsovs'k"),
    "709540" => t("Dubno"),
  );
}


function location_cities_list_ua_59() {
  return array(
    "613273" => t("Lebedyn"),
    "692194" => t("Sumy"),
    "693942" => t("Shostka"),
    "695464" => t("Romny"),
    "696008" => t("Putyvl'"),
    "704000" => t("Krolevets'"),
    "705135" => t("Konotop"),
    "707758" => t("Hlukhiv"),
    "712559" => t("Bilopillya"),
    "713749" => t("Okhtyrka"),
  );
}


function location_cities_list_ua_61() {
  return array(
    "691650" => t("Ternopil'"),
    "704143" => t("Kremenets'"),
    "710400" => t("Chortkiv"),
    "712374" => t("Berezhani"),
  );
}


function location_cities_list_ua_05() {
  return array(
    "687116" => t("Zhmerynka"),
    "689558" => t("Vinnytsya"),
    "691016" => t("Tul'chyn"),
    "700918" => t("Mohyliv-Podil's'kyy"),
    "703428" => t("Ladyzhyn"),
    "706380" => t("Khmil'nyk"),
    "706571" => t("Kozyatyn"),
    "707155" => t("Kalynivka"),
    "708901" => t("Haysyn"),
    "712861" => t("Bar"),
  );
}


function location_cities_list_ua_07() {
  return array(
    "689378" => t("Volodymyr-Volyns'kyy"),
    "699035" => t("Novovolyns'k"),
    "702569" => t("Luts'k"),
    "704617" => t("Kovel'"),
    "705730" => t("Kivertsi"),
  );
}


function location_cities_list_ua_21() {
  return array(
    "688746" => t("Vynohradiv"),
    "690548" => t("Uzhhorod"),
    "692129" => t("Svalyava"),
    "700646" => t("Mukacheve"),
    "706165" => t("Khust"),
    "712423" => t("Berehove"),
  );
}


function location_cities_list_ua_23() {
  return array(
    "686729" => t("Vasylivka"),
    "687700" => t("Zaporizhzhya"),
    "691469" => t("Tokmak"),
    "696677" => t("Polohy"),
    "698428" => t("Orikhiv"),
    "701404" => t("Melitopol'"),
    "707898" => t("Hulyaypole"),
    "709276" => t("Energodar"),
    "709960" => t("Dniprorudne"),
    "712451" => t("Berdyans'k"),
  );
}


function location_cities_list_ua_18() {
  return array(
    "686967" => t("Zhytomyr"),
    "695912" => t("Radomyshl'"),
    "698131" => t("Ovruch"),
    "699553" => t("Novohrad-Volyns'kyy"),
    "702116" => t("Malyn"),
    "704885" => t("Korostyshiv"),
    "704901" => t("Korosten'"),
    "712441" => t("Berdychiv"),
  );
}
