<?php


function location_cities_list_ug_c() {
  return array(
    "225858" => "Wobulenzi",
    "225964" => "Wakiso",
    "227812" => "Njeru",
    "228227" => "Namasuba",
    "228853" => "Mukono",
    "228971" => "Mubende",
    "229139" => "Mityana",
    "229380" => "Masaka",
    "229746" => "Luwero",
    "229911" => "Lugazi",
    "231139" => "Kireka",
    "231696" => "Kayunga",
    "232422" => "Kampala",
    "233508" => "Entebbe",
  );
}


function location_cities_list_ug_e() {
  return array(
    "226110" => "Tororo",
    "226234" => "Soroti",
    "226823" => "Pallisa",
    "229278" => "Mbale",
    "233114" => "Jinja",
    "233275" => "Iganga",
    "233886" => "Buwenge",
    "234077" => "Busia",
    "234092" => "Busembatia",
    "234565" => "Bugiri",
  );
}


function location_cities_list_ug_n() {
  return array(
    "225835" => "Yumbe",
    "226853" => "Paidha",
    "227904" => "Nebbi",
    "229059" => "Moyo",
    "230166" => "Lira",
    "230617" => "Kotido",
    "230893" => "Kitgum",
    "233346" => "Gulu",
    "235039" => "Arua",
    "235489" => "Adjumani",
  );
}


function location_cities_list_ug_w() {
  return array(
    "227528" => "Nyachera",
    "227592" => "Ntungamo",
    "227593" => "Ntungamo",
    "229268" => "Mbarara",
    "229362" => "Masindi",
    "230299" => "Kyenjojo",
    "232066" => "Kasese",
    "232371" => "Kamwenge",
    "233070" => "Kabale",
    "233312" => "Hoima",
    "233476" => "Fort Portal",
    "233730" => "Bwizibwera",
    "234178" => "Bundibugyo",
  );
}
