<?php


function location_cities_list_jp_23 () {
	return array (
		"1849539" => t("Tsushima"),
		"1849814" => t("Toyota"),
		"1849845" => t("Toyokawa"),
		"1849846" => t("Toyohashi"),
		"1849850" => t("Toyohama"),
		"1850185" => t("Tokoname"),
		"1850818" => t("Taketoyo"),
		"1851155" => t("Takahama"),
		"1851259" => t("Tahara"),
		"1851622" => t("Sobue"),
		"1852046" => t("Shinshiro"),
		"1852663" => t("Seto"),
		"1854376" => t("Okazaki"),
		"1854803" => t("Obu"),
		"1855189" => t("Nishio"),
		"1856057" => t("Nagoya-shi"),
		"1856697" => t("Miyoshi"),
		"1858249" => t("Kuroda"),
		"1858591" => t("Kozakai-cho"),
		"1858836" => t("Konan"),
		"1858926" => t("Komaki"),
		"1859891" => t("Kasugai"),
		"1860034" => t("Kariya"),
		"1860191" => t("Kanie"),
		"1861207" => t("Iwakura"),
		"1861383" => t("Ishiki"),
		"1861602" => t("Inazawa"),
		"1861949" => t("Ichinomiya"),
		"1862912" => t("Hekinan"),
		"1863209" => t("Handa"),
		"1863693" => t("Gamagori"),
		"1864549" => t("Chiryu"),
		"1865294" => t("Anjo"),
	);
}


function location_cities_list_jp_05 () {
	return array (
		"1850405" => t("Tenno"),
		"2110460" => t("Yuzawa"),
		"2110506" => t("Yokotemachi"),
		"2111435" => t("Omagari"),
		"2113126" => t("Akita"),
		"2113719" => t("Akita Shi"),
		"2127910" => t("Takanosu"),
		"2128787" => t("Odate"),
		"2128867" => t("Noshiro"),
		"2130146" => t("Kazuno"),
	);
}


function location_cities_list_jp_02 () {
	return array (
		"2127878" => t("Mutsu"),
		"2129005" => t("Namioka"),
		"2129211" => t("Misawa"),
		"2129395" => t("Kuroishi"),
		"2129513" => t("Shimokizukuri"),
		"2130057" => t("Hirosaki"),
		"2130203" => t("Hachinohe"),
		"2130658" => t("Aomori Shi"),
		"2131612" => t("Goshogawara"),
	);
}


function location_cities_list_jp_12 () {
	return array (
		"1850523" => t("Tateyama"),
		"1855078" => t("Noda"),
		"1856184" => t("Nagareyama"),
		"1857553" => t("Matsudo"),
		"1859393" => t("Kisarazu"),
		"1859924" => t("Kashiwa"),
		"1861968" => t("Ichikawa"),
		"1863713" => t("Futtsu"),
		"1863905" => t("Funabashi"),
		"1907307" => t("Kimitsu"),
		"2110480" => t("Yotsukaido"),
		"2110518" => t("Yokaichiba"),
		"2110579" => t("Yachimata"),
		"2110774" => t("Togane"),
		"2111008" => t("Shisui"),
		"2111018" => t("Shiroi"),
		"2111173" => t("Sawara"),
		"2111220" => t("Sakura"),
		"2111429" => t("Omigawa"),
		"2111495" => t("Ohara"),
		"2111568" => t("Oami"),
		"2111677" => t("Naruto"),
		"2111684" => t("Narita"),
		"2111687" => t("Narashino"),
		"2111855" => t("Mobara"),
		"2112297" => t("Kawaguchi"),
		"2112309" => t("Katsuura"),
		"2112319" => t("Katori-shi"),
		"2112664" => t("Ichihara"),
		"2112802" => t("Hasaki"),
		"2113015" => t("Chiba"),
		"2113077" => t("Asahi"),
		"2113164" => t("Abiko"),
		"6822181" => t("Kamagaya-shi"),
	);
}


function location_cities_list_jp_38 () {
	return array (
		"1855425" => t("Niihama"),
		"1926006" => t("Iyo"),
		"1926020" => t("Uwajima"),
		"1926054" => t("Saijo"),
		"1926055" => t("Ozu"),
		"1926099" => t("Matsuyama-shi"),
		"1926101" => t("Masaki-cho"),
		"1926116" => t("Kawanoe"),
		"1926142" => t("Hojo"),
	);
}


function location_cities_list_jp_18 () {
	return array (
		"1849592" => t("Tsuruga"),
		"1850872" => t("Takefu"),
		"1853338" => t("Sabae"),
		"1854022" => t("Ono"),
		"1854849" => t("Obama"),
		"1857260" => t("Mikuni"),
		"1857651" => t("Maruoka"),
		"1859765" => t("Katsuyama"),
		"1863985" => t("Fukui-shi"),
	);
}


function location_cities_list_jp_40 () {
	return array (
		"1848087" => t("Yukuhashi"),
		"1848573" => t("Yanagawa"),
		"1849299" => t("Umi"),
		"1850627" => t("Tanushimaru"),
		"1851273" => t("Tagawa"),
		"1852109" => t("Shingu"),
		"1852673" => t("Setaka"),
		"1852915" => t("Sasaguri"),
		"1854083" => t("Omuta"),
		"1855066" => t("Nogata"),
		"1855757" => t("Nakatsu"),
		"1855907" => t("Nakama"),
		"1856828" => t("Miyada"),
		"1857844" => t("Maebaru"),
		"1858088" => t("Kurume"),
		"1859094" => t("Koga"),
		"1859307" => t("Kitakyushu"),
		"1859647" => t("Kawasaki"),
		"1860234" => t("Kanda"),
		"1861835" => t("Iizuka"),
		"1863967" => t("Fukuoka-shi"),
		"1863978" => t("Fukuma"),
		"1864572" => t("Chikushino-shi"),
		"1865375" => t("Amagi"),
		"6822146" => t("Onojo"),
		"8198709" => t("Buzen"),
	);
}


function location_cities_list_jp_07 () {
	return array (
		"1859319" => t("Kitakata"),
		"2110538" => t("Yanagawa"),
		"2110959" => t("Sukagawa"),
		"2111656" => t("Nihommatsu"),
		"2111704" => t("Namie"),
		"2111824" => t("Motomiya"),
		"2111943" => t("Miharu"),
		"2112141" => t("Koriyama"),
		"2112539" => t("Iwaki"),
		"2112583" => t("Ishikawa"),
		"2112615" => t("Inawashiro"),
		"2112692" => t("Hobara"),
		"2112903" => t("Funehiki"),
		"2112923" => t("Fukushima-shi"),
	);
}


function location_cities_list_jp_21 () {
	return array (
		"1850207" => t("Toki"),
		"1850600" => t("Tarui"),
		"1850892" => t("Takayama"),
		"1851193" => t("Tajimi"),
		"1854703" => t("Ogaki"),
		"1855753" => t("Nakatsugawa"),
		"1856667" => t("Mizunami"),
		"1856938" => t("Mitake"),
		"1857062" => t("Mino"),
		"1859998" => t("Kasamatsucho"),
		"1860735" => t("Kakamigahara"),
		"1861528" => t("Inuyama"),
		"1863611" => t("Godo"),
		"1863641" => t("Gifu-shi"),
		"6822217" => t("Minokamo"),
		"6822219" => t("Gujo"),
	);
}


function location_cities_list_jp_10 () {
	return array (
		"1848194" => t("Yoshii"),
		"1850091" => t("Tomioka"),
		"1850559" => t("Tatebayashi"),
		"1850746" => t("Tamamura"),
		"1851002" => t("Takasaki"),
		"1852595" => t("Shibukawa"),
		"1853192" => t("Sakai"),
		"1853677" => t("Ota"),
		"1854177" => t("Omama"),
		"1854905" => t("Numata"),
		"1855852" => t("Nakanojo"),
		"1857843" => t("Maebashi-shi"),
		"1859405" => t("Kiryu"),
		"1860211" => t("Kaneko"),
		"1861436" => t("Isesaki"),
		"1864099" => t("Fujioka"),
		"1865290" => t("Annaka"),
	);
}


function location_cities_list_jp_34 () {
	return array (
		"1850860" => t("Takehara"),
		"1851713" => t("Shobara"),
		"1852102" => t("Shinichi"),
		"1853992" => t("Onomichi"),
		"1854028" => t("Ono"),
		"1856698" => t("Miyoshi"),
		"1857334" => t("Mihara"),
		"1858296" => t("Kure"),
		"1860176" => t("Kannabe"),
		"1861586" => t("Innoshima"),
		"1862415" => t("Hiroshima-shi"),
		"1863018" => t("Hatsukaichi"),
		"1863917" => t("Fukuyama"),
		"1864155" => t("Fuchu"),
		"1897590" => t("Kaita"),
	);
}


function location_cities_list_jp_01 () {
	return array (
		"2127383" => t("Bihoro"),
		"2127515" => t("Wakkanai"),
		"2127733" => t("Tomakomai"),
		"2127802" => t("Tobetsu"),
		"2127896" => t("Takikawa"),
		"2127955" => t("Sunagawa"),
		"2128025" => t("Shizunai"),
		"2128072" => t("Shiraoi"),
		"2128147" => t("Shimo-furano"),
		"2128206" => t("Shibetsu"),
		"2128295" => t("Sapporo"),
		"2128382" => t("Rumoi"),
		"2128558" => t("Otofuke"),
		"2128574" => t("Otaru"),
		"2128815" => t("Obihiro"),
		"2128975" => t("Nemuro"),
		"2128983" => t("Nayoro"),
		"2129003" => t("Nanae"),
		"2129101" => t("Muroran"),
		"2129163" => t("Mombetsu"),
		"2129218" => t("Yoichi"),
		"2129324" => t("Makubetsu"),
		"2129376" => t("Kushiro"),
		"2129537" => t("Kitami"),
		"2129766" => t("Kamiiso"),
		"2129868" => t("Iwanai"),
		"2129870" => t("Iwamizawa"),
		"2129909" => t("Ishikari"),
		"2130054" => t("Kitahiroshima"),
		"2130188" => t("Hakodate"),
		"2130332" => t("Fukagawa"),
		"2130404" => t("Ebetsu"),
		"2130421" => t("Date"),
		"2130452" => t("Chitose"),
		"2130534" => t("Bibai"),
		"2130612" => t("Ashibetsu"),
		"2130629" => t("Asahikawa"),
		"2130741" => t("Abashiri"),
	);
}


function location_cities_list_jp_28 () {
	return array (
		"1847966" => t("Akashi"),
		"1848498" => t("Yashiro"),
		"1848633" => t("Yamasaki"),
		"1849831" => t("Toyooka"),
		"1850499" => t("Tatsuno"),
		"1851012" => t("Takarazuka"),
		"1851426" => t("Sumoto"),
		"1851935" => t("Shirahama"),
		"1852901" => t("Sasayama"),
		"1853008" => t("Sanda"),
		"1854026" => t("Ono"),
		"1855134" => t("Nishiwaki"),
		"1855207" => t("Nishinomiya"),
		"1857276" => t("Miki"),
		"1859171" => t("Kobe-shi"),
		"1859675" => t("Kawanishi"),
		"1860704" => t("Kakogawa"),
		"1861310" => t("Itami"),
		"1862627" => t("Himeji"),
		"1863953" => t("Fukura"),
		"1864985" => t("Ashiya"),
		"1865387" => t("Amagasaki"),
		"1865412" => t("Ako"),
		"1865661" => t("Aioi-shi"),
	);
}


function location_cities_list_jp_08 () {
	return array (
		"1848096" => t("Yuki"),
		"1852347" => t("Shimodate"),
		"1853193" => t("Sakai"),
		"1856881" => t("Mitsukaido"),
		"1859093" => t("Koga"),
		"1860748" => t("Kashima-shi"),
		"1861223" => t("Iwai"),
		"1861406" => t("Ishige"),
		"2110629" => t("Ushiku"),
		"2110683" => t("Tsukuba"),
		"2110729" => t("Toride"),
		"2110743" => t("Tomobe"),
		"2110893" => t("Takahagi"),
		"2111258" => t("Ryugasaki"),
		"2111425" => t("Omiya"),
		"2111441" => t("Okunoya"),
		"2111567" => t("Oarai"),
		"2111749" => t("Naka"),
		"2111831" => t("Moriya"),
		"2111901" => t("Mito-shi"),
		"2112019" => t("Makabe"),
		"2112232" => t("Kitaibaraki"),
		"2112312" => t("Katsuta"),
		"2112343" => t("Kasama"),
		"2112521" => t("Iwase"),
		"2112555" => t("Itako"),
		"2112571" => t("Ishioka"),
		"2112708" => t("Hitachi"),
		"2112913" => t("Funaishikawa"),
		"2112940" => t("Fujishiro"),
		"2112963" => t("Edosaki"),
		"2112989" => t("Daigo"),
		"2113115" => t("Ami"),
		"6822096" => t("Hitachi-Naka"),
		"6822108" => t("Inashiki"),
	);
}


function location_cities_list_jp_17 () {
	return array (
		"1849584" => t("Tsurugi"),
		"1849782" => t("Tsubata"),
		"1854979" => t("Nonoichi"),
		"1855670" => t("Nanao"),
		"1857470" => t("Matsuto"),
		"1858910" => t("Komatsu"),
		"1860243" => t("Kanazawa-shi"),
		"1863341" => t("Hakui"),
	);
}


function location_cities_list_jp_03 () {
	return array (
		"2110560" => t("Yamada"),
		"2110735" => t("Tono"),
		"2110994" => t("Shizukuishi"),
		"2111310" => t("Otsuchi"),
		"2111530" => t("Ofunato"),
		"2111834" => t("Morioka-shi"),
		"2111859" => t("Mizusawa"),
		"2111884" => t("Miyako"),
		"2112227" => t("Kitakami"),
		"2112444" => t("Kamaishi"),
		"2112656" => t("Ichinoseki"),
		"2112823" => t("Hanamaki"),
		"2129961" => t("Ichinohe"),
	);
}


function location_cities_list_jp_37 () {
	return array (
		"1850004" => t("Tonosho"),
		"1851100" => t("Takamatsu-shi"),
		"1851282" => t("Tadotsu"),
		"1852561" => t("Shido"),
		"1853190" => t("Sakaide"),
		"1857665" => t("Marugame"),
		"1860122" => t("Kanonji"),
	);
}


function location_cities_list_jp_46 () {
	return array (
		"1850589" => t("Tarumizu"),
		"1851542" => t("Sueyoshi"),
		"1852588" => t("Shibushi"),
		"1852736" => t("Satsumasendai"),
		"1854246" => t("Okuchi"),
		"1855203" => t("Nishinoomote"),
		"1855540" => t("Naze"),
		"1857712" => t("Makurazaki"),
		"1858041" => t("Kushikino"),
		"1858972" => t("Kokubu"),
		"1859964" => t("Kaseda"),
		"1860112" => t("Kanoya"),
		"1860750" => t("Kajiki"),
		"1860827" => t("Kagoshima-shi"),
		"1861108" => t("Izumi"),
		"1861825" => t("Ijuin"),
		"1862010" => t("Ibusuki"),
		"1863279" => t("Hamanoichi"),
		"1865401" => t("Akune"),
	);
}


function location_cities_list_jp_14 () {
	return array (
		"1847963" => t("Atsugi"),
		"1847968" => t("Zushi"),
		"1848004" => t("Zama"),
		"1848113" => t("Yugawara"),
		"1848313" => t("Yokosuka"),
		"1848354" => t("Yokohama-shi"),
		"1853295" => t("Sagamihara"),
		"1854492" => t("Oiso"),
		"1854747" => t("Odawara"),
		"1855380" => t("Ninomiya"),
		"1857144" => t("Minami-rinkan"),
		"1859642" => t("Kawasaki"),
		"1860672" => t("Kamakura"),
		"1861449" => t("Isehara"),
		"1862462" => t("Hiratsuka"),
		"1862992" => t("Hayama"),
		"1863431" => t("Hadano"),
		"1864092" => t("Fujisawa"),
		"1864624" => t("Chigasaki"),
		"1907309" => t("Miura"),
	);
}


function location_cities_list_jp_43 () {
	return array (
		"1848445" => t("Yatsushiro"),
		"1848705" => t("Yamaga"),
		"1849069" => t("Uto"),
		"1849154" => t("Ushibuka"),
		"1849424" => t("Ueki"),
		"1850745" => t("Tamana"),
		"1853433" => t("Ozu"),
		"1857208" => t("Minamata"),
		"1857560" => t("Matsubase"),
		"1858421" => t("Kumamoto-shi"),
		"1859492" => t("Kikuchi"),
		"1862230" => t("Hondo"),
		"1862352" => t("Hitoyoshi"),
	);
}


function location_cities_list_jp_26 () {
	return array (
		"1848439" => t("Yawata"),
		"1849372" => t("Uji"),
		"1850707" => t("Tanabe"),
		"1856456" => t("Muko"),
		"1856703" => t("Miyazu"),
		"1857766" => t("Maizuru"),
		"1857910" => t("Kyoto"),
		"1860635" => t("Kameoka"),
		"1864009" => t("Fukuchiyama"),
		"1864873" => t("Ayabe"),
		"8125829" => t("Kamigyo-ku"),
	);
}


function location_cities_list_jp_39 () {
	return array (
		"1851390" => t("Susaki"),
		"1851462" => t("Sukumo"),
		"1855891" => t("Nakamura"),
		"1856392" => t("Muroto"),
		"1859146" => t("Kochi-shi"),
		"1861584" => t("Ino"),
		"1865449" => t("Aki"),
	);
}


function location_cities_list_jp_24 () {
	return array (
		"1848373" => t("Yokkaichi"),
		"1849414" => t("Ueno"),
		"1849796" => t("Tsu-shi"),
		"1850345" => t("Toba"),
		"1851348" => t("Suzuka"),
		"1853514" => t("Owase"),
		"1856293" => t("Nabari"),
		"1857496" => t("Matsuzaka"),
		"1857968" => t("Kuwana"),
		"1858866" => t("Komono"),
		"1860626" => t("Kameyama"),
		"1861450" => t("Ise"),
		"1861901" => t("Iga"),
		"1862389" => t("Hisai"),
		"6696932" => t("Kawage"),
	);
}


function location_cities_list_jp_04 () {
	return array (
		"2110541" => t("Yamoto"),
		"2110586" => t("Watari"),
		"2110596" => t("Wakuya"),
		"2110744" => t("Tomiya"),
		"2111016" => t("Shiroishi"),
		"2111049" => t("Shiogama"),
		"2111149" => t("Sendai-shi"),
		"2111277" => t("Rifu"),
		"2111461" => t("Okawara"),
		"2111964" => t("Matsushima"),
		"2112008" => t("Marumori"),
		"2112182" => t("Kogota"),
		"2112455" => t("Kakuda"),
		"2112527" => t("Iwanuma"),
		"2112576" => t("Ishinomaki"),
		"2112899" => t("Furukawa"),
	);
}


function location_cities_list_jp_45 () {
	return array (
		"1849647" => t("Tsuma"),
		"1851068" => t("Takanabe"),
		"1855095" => t("Nobeoka"),
		"1855476" => t("Nichinan"),
		"1856717" => t("Miyazaki-shi"),
		"1856775" => t("Miyakonojo"),
		"1859175" => t("Kobayashi"),
		"1895695" => t("Kushima"),
	);
}


function location_cities_list_jp_20 () {
	return array (
		"1849429" => t("Ueda"),
		"1849817" => t("Toyoshina"),
		"1850498" => t("Tatsuno"),
		"1851357" => t("Suzaka"),
		"1851368" => t("Suwa"),
		"1852003" => t("Shiojiri"),
		"1853081" => t("Saku"),
		"1854186" => t("Omachi"),
		"1854384" => t("Okaya"),
		"1855863" => t("Nakano"),
		"1856215" => t("Nagano-shi"),
		"1857519" => t("Matsumoto"),
		"1857659" => t("Maruko"),
		"1858858" => t("Komoro"),
		"1861641" => t("Ina"),
		"1861838" => t("Iiyama"),
		"1861864" => t("Iida"),
		"1862098" => t("Hotaka"),
		"1864557" => t("Chino"),
	);
}


function location_cities_list_jp_42 () {
	return array (
		"1850269" => t("Togitsu"),
		"1852479" => t("Shimabara"),
		"1852899" => t("Sasebo"),
		"1854093" => t("Omura"),
		"1854807" => t("Obita"),
		"1856177" => t("Nagasaki-shi"),
		"1861464" => t("Isahaya"),
		"1862555" => t("Hirado"),
		"1863997" => t("Fukuecho"),
	);
}


function location_cities_list_jp_29 () {
	return array (
		"1850396" => t("Tenri"),
		"1850472" => t("Tawaramoto"),
		"1853066" => t("Sakurai"),
		"1855612" => t("Nara-shi"),
		"1859951" => t("Kashihara-shi"),
		"1861749" => t("Ikoma"),
		"1863398" => t("Haibara"),
		"1863541" => t("Gose"),
		"1863592" => t("Gojo"),
	);
}


function location_cities_list_jp_15 () {
	return array (
		"1848210" => t("Yoshida"),
		"1849788" => t("Tsubame"),
		"1850217" => t("Tokamachi"),
		"1850307" => t("Tochio"),
		"1851494" => t("Suibara"),
		"1851813" => t("Shirone"),
		"1851952" => t("Shiozawa"),
		"1852607" => t("Shibata"),
		"1852984" => t("Sanjo"),
		"1853371" => t("Ryotsu"),
		"1854444" => t("Ojiya"),
		"1855410" => t("Niitsu"),
		"1855431" => t("Niigata-shi"),
		"1856199" => t("Nagaoka"),
		"1856426" => t("Muramatsu"),
		"1856434" => t("Murakami"),
		"1856476" => t("Muikamachi"),
		"1856878" => t("Mitsuke"),
		"1857751" => t("Maki"),
		"1859908" => t("Kashiwazaki"),
		"1860341" => t("Kamo"),
		"1860648" => t("Kameda"),
		"1861285" => t("Itoigawa"),
		"1863540" => t("Gosen"),
		"1865207" => t("Arai"),
		"6825489" => t("Joetsu"),
	);
}


function location_cities_list_jp_33 () {
	return array (
		"1849519" => t("Tsuyama"),
		"1850742" => t("Tamano"),
		"1851137" => t("Takahashi"),
		"1851606" => t("Soja"),
		"1854383" => t("Okayama-shi"),
		"1855416" => t("Niimi"),
		"1858311" => t("Kurashiki"),
		"1859990" => t("Kasaoka"),
		"1860335" => t("Kamogata"),
		"1862034" => t("Ibara"),
	);
}


function location_cities_list_jp_47 () {
	return array (
		"1850108" => t("Tomigusuku"),
		"1856035" => t("Naha-shi"),
		"1856068" => t("Nago"),
		"1861280" => t("Itoman"),
		"1861393" => t("Ishikawa"),
		"1861416" => t("Ishigaki"),
		"1862505" => t("Hirara"),
		"1863426" => t("Haebaru"),
		"1863495" => t("Gushikawa"),
		"1863627" => t("Ginowan"),
		"1864652" => t("Chatan"),
		"1894616" => t("Okinawa"),
	);
}


function location_cities_list_jp_41 () {
	return array (
		"1849183" => t("Ureshino"),
		"1849904" => t("Tosu"),
		"1850834" => t("Takeo"),
		"1853303" => t("Saga-shi"),
		"1854405" => t("Okawa"),
		"1859941" => t("Kashima"),
		"1860063" => t("Karatsu"),
		"1860095" => t("Kanzaki"),
		"1861677" => t("Imari"),
	);
}


function location_cities_list_jp_11 () {
	return array (
		"1848188" => t("Yoshikawa"),
		"1848243" => t("Yorii"),
		"1848254" => t("Yono"),
		"1848499" => t("Yashio-shi"),
		"1848903" => t("Warabi"),
		"1850181" => t("Tokorozawa"),
		"1851504" => t("Sugito"),
		"1851604" => t("Soka"),
		"1851711" => t("Shobu"),
		"1851883" => t("Shiraoka"),
		"1852502" => t("Shiki"),
		"1852849" => t("Satte"),
		"1853209" => t("Sakado"),
		"1854371" => t("Okegawa"),
		"1854530" => t("Oi"),
		"1854665" => t("Ogawa"),
		"1856560" => t("Morohongo"),
		"1857403" => t("Menuma"),
		"1858283" => t("Kurihashi"),
		"1858428" => t("Kumagaya"),
		"1858445" => t("Kukichuo"),
		"1858729" => t("Koshigaya"),
		"1858794" => t("Konosu"),
		"1859113" => t("Kodama"),
		"1859400" => t("Kisai"),
		"1859586" => t("Kazo"),
		"1859730" => t("Kawaguchi"),
		"1859740" => t("Kawagoe"),
		"1859884" => t("Kasukabe"),
		"1861164" => t("Iwatsuki"),
		"1862198" => t("Honjo"),
		"1863023" => t("Hatogaya-honcho"),
		"1863173" => t("Hanyu"),
		"1863183" => t("Hanno"),
		"1863482" => t("Gyoda"),
		"1864025" => t("Fukiage"),
		"1864031" => t("Fukaya"),
		"1864637" => t("Chichibu"),
		"1865714" => t("Ageoshimo"),
		"1907123" => t("Hasuda"),
		"1907125" => t("Kamifukuoka"),
		"1907146" => t("Sayama"),
		"1907299" => t("Asaka"),
		"1907300" => t("Wako"),
		"1907301" => t("Shimotoda"),
		"6940394" => t("Saitama"),
	);
}


function location_cities_list_jp_25 () {
	return array (
		"1848382" => t("Youkaichi"),
		"1848489" => t("Yasu"),
		"1853574" => t("Otsu-shi"),
		"1856243" => t("Nagahama"),
		"1856569" => t("Moriyama"),
		"1857209" => t("Minakuchi"),
		"1858067" => t("Kusatsu"),
		"1859335" => t("Kitahama"),
		"1862601" => t("Hino"),
		"1862636" => t("Hikone"),
		"1863451" => t("Omihachiman"),
	);
}


function location_cities_list_jp_32 () {
	return array (
		"1848482" => t("Yasugi"),
		"1854774" => t("Oda"),
		"1857550" => t("Matsue-shi"),
		"1857594" => t("Masuda"),
		"1861084" => t("Izumo"),
		"1862471" => t("Hirata"),
		"1863310" => t("Hamada"),
		"1863521" => t("Gotsu"),
	);
}


function location_cities_list_jp_22 () {
	return array (
		"1848774" => t("Yaizu"),
		"1851717" => t("Shizuoka-shi"),
		"1852357" => t("Shimoda"),
		"1852472" => t("Shimada"),
		"1853280" => t("Sagara"),
		"1853486" => t("Oyama"),
		"1854902" => t("Numazu"),
		"1856586" => t("Mori"),
		"1856977" => t("Mishima"),
		"1858756" => t("Kosai-shi"),
		"1860256" => t("Kanaya"),
		"1860728" => t("Kakegawa"),
		"1861171" => t("Iwata"),
		"1861290" => t("Ito"),
		"1863289" => t("Hamamatsu"),
		"1863293" => t("Hamakita"),
		"1863528" => t("Gotemba"),
		"1863945" => t("Fukuroi"),
		"1864105" => t("Fujinomiya"),
		"1864132" => t("Fujieda"),
		"1864134" => t("Fuji"),
		"1864945" => t("Atami"),
	);
}


function location_cities_list_jp_09 () {
	return array (
		"1848776" => t("Yaita"),
		"1849053" => t("Utsunomiya-shi"),
		"1849367" => t("Ujiie"),
		"1850311" => t("Tochigi"),
		"1850630" => t("Tanuma"),
		"1852964" => t("Sano"),
		"1853483" => t("Oyama"),
		"1855395" => t("Nikko"),
		"1857379" => t("Mibu"),
		"1860098" => t("Kanuma"),
		"1860458" => t("Kaminokawa"),
		"1861699" => t("Imaichi"),
		"1864098" => t("Fujioka"),
		"1865005" => t("Ashikaga"),
		"2111325" => t("Otawara"),
		"2111827" => t("Motegi"),
		"2111836" => t("Mooka"),
		"2111999" => t("Mashiko"),
		"2112077" => t("Kuroiso"),
		"2112354" => t("Karasuyama"),
	);
}


function location_cities_list_jp_36 () {
	return array (
		"1848933" => t("Waki"),
		"1850158" => t("Tokushima-shi"),
		"1855580" => t("Naruto"),
		"1858902" => t("Komatsushima"),
		"1860321" => t("Kamojima"),
		"1861400" => t("Ishii"),
		"1861799" => t("Ikeda"),
		"1865309" => t("Anan"),
	);
}


function location_cities_list_jp_31 () {
	return array (
		"1848277" => t("Yonago"),
		"1849892" => t("Tottori"),
		"1853174" => t("Sakaiminato"),
		"1858301" => t("Kurayoshi"),
	);
}


function location_cities_list_jp_16 () {
	return array (
		"1848447" => t("Yatsuo"),
		"1849237" => t("Uozu"),
		"1849876" => t("Toyama-shi"),
		"1851032" => t("Takaoka"),
		"1852385" => t("Shimminato"),
		"1854868" => t("Nyuzen"),
		"1855694" => t("Namerikawa"),
		"1858695" => t("Kosugi"),
		"1860563" => t("Kamiichi"),
		"1862612" => t("Himi"),
		"1863973" => t("Fukumitsu"),
		"6694821" => t("Nanto-shi"),
	);
}


function location_cities_list_jp_13 () {
	return array (
		"1849186" => t("Urayasu"),
		"1850147" => t("Tokyo"),
		"1850692" => t("Nishi-Tokyo-shi"),
		"1850693" => t("Tanashicho"),
		"1851307" => t("Tachikawa"),
		"1852140" => t("Shinagawa-ku"),
		"1854162" => t("Ome"),
		"1855503" => t("Nerima-ku"),
		"1856367" => t("Musashino"),
		"1856942" => t("Mitaka-shi"),
		"1857871" => t("Machida"),
		"1858964" => t("Kokubunji"),
		"1859088" => t("Koganei"),
		"1859116" => t("Kodaira"),
		"1860437" => t("Kamirenjaku"),
		"1861261" => t("Itsukaichi"),
		"1862599" => t("Hino"),
		"1863440" => t("Hachioji"),
		"1864154" => t("Fuchu"),
		"1864518" => t("Chofugaoka"),
		"1907148" => t("Fussa"),
		"1907165" => t("Kunitachi"),
		"1907306" => t("Komae"),
		"6419279" => t("Edogawa-ku"),
		"6419327" => t("Koto-ku"),
		"6822131" => t("Akiruno-shi"),
		"6930379" => t("Shinjuku"),
		"6930483" => t("Shibuya-ku"),
		"7279570" => t("Higashimurayama-shi"),
		"8469261" => t("Adachi-ku"),
		"8469265" => t("Arakawa-ku"),
		"8469267" => t("Bunkyo-ku"),
		"8469271" => t("Chiyoda-ku"),
		"8469281" => t("Chuo-ku"),
		"8469283" => t("Itabashi-ku"),
		"8469284" => t("Katsushika-ku"),
		"8469285" => t("Kita-ku"),
		"8469286" => t("Meguro-ku"),
		"8469287" => t("Minato-ku"),
		"8469288" => t("Nakano-ku"),
		"8469289" => t("Ota-ku"),
		"8469290" => t("Suginami-ku"),
		"8469291" => t("Sumida-ku"),
		"8469292" => t("Taito-ku"),
		"8469293" => t("Toshima-ku"),
	);
}


function location_cities_list_jp_30 () {
	return array (
		"1847947" => t("Shingu"),
		"1850708" => t("Tanabe"),
		"1852383" => t("Shimminatocho"),
		"1860785" => t("Kainan"),
		"1861244" => t("Iwade"),
		"1863082" => t("Hashimoto"),
		"1863614" => t("Gobo"),
		"1926004" => t("Wakayama-shi"),
	);
}


function location_cities_list_jp_06 () {
	return array (
		"1848016" => t("Yuza"),
		"1849563" => t("Tsuruoka"),
		"1853140" => t("Sakata"),
		"2110498" => t("Yonezawa"),
		"2110556" => t("Yamagata-shi"),
		"2110793" => t("Tendo"),
		"2110891" => t("Takahata"),
		"2111065" => t("Shinjo"),
		"2111248" => t("Sagae"),
		"2111559" => t("Obanazawa"),
		"2111781" => t("Nagai"),
		"2112409" => t("Kaminoyama"),
		"2112758" => t("Higashine"),
	);
}


function location_cities_list_jp_35 () {
	return array (
		"1848550" => t("Yanai"),
		"1848689" => t("Yamaguchi-shi"),
		"1849498" => t("Ube"),
		"1850152" => t("Tokuyama"),
		"1852225" => t("Shimonoseki"),
		"1853662" => t("Otake"),
		"1854018" => t("Onoda"),
		"1854629" => t("Ogori-shimogo"),
		"1858498" => t("Kudamatsu"),
		"1861212" => t("Iwakuni"),
		"1862302" => t("Hofu"),
		"1863418" => t("Hagi"),
		"1896348" => t("Hikari"),
		"1899102" => t("Nagato"),
	);
}


function location_cities_list_jp_19 () {
	return array (
		"1849407" => t("Uenohara"),
		"1853354" => t("Ryuo"),
		"1853564" => t("Otsuki"),
		"1855363" => t("Nirasaki"),
		"1859100" => t("Kofu-shi"),
		"1861454" => t("Isawa"),
		"1864180" => t("Enzan"),
		"7281819" => t("Fujikawaguchiko"),
	);
}


function location_cities_list_jp_44 () {
	return array (
		"1849094" => t("Usuki"),
		"1849561" => t("Tsurusaki"),
		"1849661" => t("Tsukumi"),
		"1849706" => t("Tsukawaki"),
		"1850878" => t("Takedamachi"),
		"1851170" => t("Bungo-Takada-shi"),
		"1853237" => t("Saiki"),
		"1854487" => t("Oita-shi"),
		"1859234" => t("Kitsuki"),
		"1862373" => t("Hita"),
		"1862689" => t("Hiji"),
		"1864750" => t("Beppu"),
		"7279571" => t("Kunisaki-shi"),
	);
}


function location_cities_list_jp_27 () {
	return array (
		"1848522" => t("Yao"),
		"1849837" => t("Toyonaka"),
		"1850034" => t("Tondabayashi"),
		"1850910" => t("Takatsuki"),
		"1851125" => t("Takaishi"),
		"1851483" => t("Suita"),
		"1853195" => t("Sakai"),
		"1853909" => t("Osaka-shi"),
		"1856584" => t("Moriguchi"),
		"1857046" => t("Mino"),
		"1857568" => t("Matsubara"),
		"1859383" => t("Kishiwada"),
		"1859952" => t("Kashihara"),
		"1860765" => t("Kaizuka"),
		"1860871" => t("Kadoma"),
		"1861095" => t("Izumiotsu"),
		"1861107" => t("Izumi"),
		"1861795" => t("Ikeda"),
		"1862033" => t("Ibaraki"),
		"1862540" => t("Hirakata"),
		"1864416" => t("Daito"),
		"6697563" => t("Neyagawa"),
	);
}
