<?php

function location_cities_list_kn_01 () {
	return array (
	);
}


function location_cities_list_kn_02 () {
	return array (
	);
}


function location_cities_list_kn_03 () {
	return array (
		"3575551" => t("Basseterre"),
	);
}


function location_cities_list_kn_04 () {
	return array (
	);
}


function location_cities_list_kn_05 () {
	return array (
	);
}


function location_cities_list_kn_06 () {
	return array (
	);
}


function location_cities_list_kn_07 () {
	return array (
	);
}


function location_cities_list_kn_08 () {
	return array (
	);
}


function location_cities_list_kn_09 () {
	return array (
	);
}


function location_cities_list_kn_10 () {
	return array (
	);
}


function location_cities_list_kn_11 () {
	return array (
	);
}


function location_cities_list_kn_12 () {
	return array (
	);
}


function location_cities_list_kn_13 () {
	return array (
	);
}


function location_cities_list_kn_15 () {
	return array (
	);
}
