<?php

function location_cities_list_jo_aj () {
	return array (
		"250799" => t("'Ajlun"),
	);
}


function location_cities_list_jo_am () {
	return array (
		"246013" => t("Wadi as Sir"),
		"246314" => t("Umm as Summaq"),
		"247105" => t("Sahab"),
		"250441" => t("Amman"),
		"250461" => t("Al Quwaysimah"),
		"250637" => t("Al Jubayhah"),
	);
}


function location_cities_list_jo_aq () {
	return array (
		"250774" => t("Aqaba"),
	);
}


function location_cities_list_jo_ba () {
	return array (
		"250258" => t("As Salt"),
	);
}


function location_cities_list_jo_ir () {
	return array (
		"248414" => t("Kurayyimah"),
		"248946" => t("Irbid"),
		"250152" => t("Aydun"),
		"250336" => t("Ar Ramtha"),
		"250420" => t("`Anjarah"),
	);
}


function location_cities_list_jo_ja () {
	return array (
		"248875" => t("Jarash"),
	);
}


function location_cities_list_jo_ka () {
	return array (
		"248923" => t("`Izra"),
		"6946409" => t("Karak City"),
	);
}


function location_cities_list_jo_md () {
	return array (
		"248370" => t("Madaba"),
	);
}


function location_cities_list_jo_ma () {
	return array (
		"250582" => t("Al Mafraq"),
	);
}


function location_cities_list_jo_mn () {
	return array (
		"248382" => t("Ma'an"),
		"250624" => t("Qir Moav"),
	);
}


function location_cities_list_jo_at () {
	return array (
		"250198" => t("At Tafilah"),
	);
}


function location_cities_list_jo_az () {
	return array (
		"250090" => t("Zarqa"),
		"7838895" => t("Russeifa"),
	);
}
