<?php

function location_cities_list_ch_zh()
{
  return array(
    '6458818' => t('Bezirk Affoltern'),
    '2661751' => t('Bezirk Andelfingen'),
    '6458867' => t('Bezirk Bülach'),
    '6458760' => t('Bezirk Dietikon'),
    '6458797' => t('Bezirk Hinwil'),
    '6458847' => t('Bezirk Horgen'),
    '2659702' => t('Bezirk Meilen'),
    '6458852' => t('Bezirk Pfäffikon'),
    '6458751' => t('Bezirk Uster'),
    '6458808' => t('Bezirk Winterthur'),
    '6458798' => t('Bezirk Zürich'),
    '6458865' => t('Dielsdorf'),
  );
}

function location_cities_list_ch_be()
{
  return array(
    '8260142' => t('Bern-Mittleland'),
    '8260136' => t('Biel/Bienne'),
    '8260133' => t('Emmental'),
    '8260135' => t('Frutigen-Niedersimmental'),
    '8260139' => t('Interlaken-Oberhasli'),
    '8260140' => t('Jura bernois'),
    '8260141' => t('Oberaargau'),
    '8260134' => t('Obersimmental-Saanen'),
    '8260137' => t('Seeland'),
    '8260138' => t('Thun'),
  );
}

function location_cities_list_ch_lu()
{
  return array(
    '6458899' => t('Amt Entlebuch'),
    '6458761' => t('Amt Hochdorf'),
    '6458876' => t('Amt Luzern'),
    '6458877' => t('Amt Sursee'),
    '6458828' => t('Amt Willisau'),
  );
}

function location_cities_list_ch_ur()
{
  return array(
    '6458799' => t('Uri'),
  );
}

function location_cities_list_ch_sz()
{
  return array(
    '6458878' => t('Bezirk Einsiedeln'),
    '6458810' => t('Bezirk Gersau'),
    '6458848' => t('Bezirk Höfe'),
    '6458839' => t('Bezirk Küssnacht'),
    '6458781' => t('Bezirk March'),
    '6458775' => t('Bezirk Schwyz'),
  );
}

function location_cities_list_ch_ow()
{
  return array(
    '6458816' => t('Obwalden'),
  );
}

function location_cities_list_ch_nw()
{
  return array(
    '6458762' => t('Nidwalden'),
  );
}

function location_cities_list_ch_gl()
{
  return array(
    '6458747' => t('Glarus'),
  );
}

function location_cities_list_ch_zg()
{
  return array(
    '6458807' => t('Zug'),
  );
}

function location_cities_list_ch_fr()
{
  return array(
    '6458820' => t('Bezirk See/District du Lac'),
    '6458898' => t('Bezirk Sense'),
    '6458754' => t('District de la Broye'),
    '2660598' => t('District de la Glâne'),
    '6458796' => t('District de la Gruyère'),
    '6458767' => t('District de la Sarine'),
    '6458862' => t('District de la Veveyse'),
  );
}

function location_cities_list_ch_so()
{
  return array(
    '6458841' => t('Bezirk Bucheggberg'),
    '6458904' => t('Bezirk Dorneck'),
    '6458742' => t('Bezirk Gäu'),
    '6458874' => t('Bezirk Gösgen'),
    '6458829' => t('Bezirk Lebern'),
    '6458893' => t('Bezirk Olten'),
    '6458779' => t('Bezirk Solothurn'),
    '6458869' => t('Bezirk Thal'),
    '2658380' => t('Bezirk Thierstein'),
    '6458885' => t('Bezirk Wasseramt'),
  );
}

function location_cities_list_ch_bl()
{
  return array(
    '6458833' => t('Bezirk Laufen'),
    '6458854' => t('Bezirk Liestal'),
    '6458823' => t('Bezirk Sissach'),
    '6458843' => t('District of Arlesheim'),
    '6458748' => t('Waldenburg'),
  );
}

function location_cities_list_ch_sh()
{
  return array(
    '6458815' => t('Bezirk Oberklettgau'),
    '6458883' => t('Bezirk Reiat'),
    '6458881' => t('Bezirk Schaffhausen'),
    '6458769' => t('Bezirk Schleitheim'),
    '6458794' => t('Bezirk Stein'),
    '6458836' => t('Bezirk Unterklettgau'),
  );
}

function location_cities_list_ch_ar()
{
  return array(
    '6458837' => t('Bezirk Hinterland'),
    '6458830' => t('Bezirk Mittelland'),
    '6458863' => t('Bezirk Vorderland'),
  );
}

function location_cities_list_ch_ag()
{
  return array(
    '6458846' => t('Bezirk Aarau'),
    '6458813' => t('Bezirk Baden'),
    '6458774' => t('Bezirk Bremgarten'),
    '6458826' => t('Bezirk Brugg'),
    '6458772' => t('Bezirk Kulm'),
    '6458860' => t('Bezirk Laufenburg'),
    '6458806' => t('Bezirk Lenzburg'),
    '6458902' => t('Bezirk Muri'),
    '6458853' => t('Bezirk Rheinfelden'),
    '6458746' => t('Bezirk Zofingen'),
    '6458788' => t('Bezirk Zurzach'),
  );
}

function location_cities_list_ch_tg()
{
  return array(
    '8260144' => t('Arbon'),
    '8260143' => t('Frauenfeld'),
    '8260146' => t('Kreuzlingen'),
    '8260145' => t('Münchwilen'),
    '8260147' => t('Weinfelden'),
  );
}

function location_cities_list_ch_ti()
{
  return array(
    '6458870' => t('Distretto di Bellinzona'),
    '6458784' => t('Distretto di Blenio'),
    '6458903' => t('Distretto di Leventina'),
    '6458750' => t('Distretto di Locarno'),
    '6458771' => t('Distretto di Lugano'),
    '6458894' => t('Distretto di Mendrisio'),
    '6458756' => t('Distretto di Riviera'),
    '2658196' => t('Vallemaggia'),
  );
}

function location_cities_list_ch_vd()
{
  return array(
    '6458896' => t('District d\'Aigle'),
    '6458866' => t('District de Lausanne'),
    '7285005' => t('District de Lavaux-Oron'),
    '6458855' => t('District de Morges'),
    '7285006' => t('District de Nyon'),
    '7285007' => t('District de l\'Ouest lausannois'),
    '7285002' => t('District de la Broye-Vully'),
    '7285009' => t('District de la Riviera-Pays-d\'Enhaut'),
    '7285003' => t('District du Gros-de-Vaud'),
    '7285004' => t('District du Jura-Nord vaudois'),
  );
}

function location_cities_list_ch_vs()
{
  return array(
    '6458821' => t('Bezirk Brig'),
    '6458766' => t('Bezirk Goms'),
    '6458753' => t('Bezirk Leuk'),
    '2659097' => t('Bezirk Raron'),
    '6458844' => t('Bezirk Visp'),
    '6458768' => t('District d\'Entremont'),
    '6458872' => t('District d\'Hérens'),
    '6458850' => t('District de Conthey'),
    '6458845' => t('District de Monthey'),
    '6458832' => t('District de Saint-Maurice'),
    '6458795' => t('District de Sierre'),
    '6458745' => t('District de Sion'),
    '2659752' => t('Martigny'),
  );
}

function location_cities_list_ch_ge()
{
  return array(
    '6458783' => t('Geneva'),
  );
}

function location_cities_list_ch_ju()
{
  return array(
    '6458744' => t('District de Delémont'),
    '6458776' => t('District de Porrentruy'),
    '6458790' => t('District des Franches-Montagnes'),
  );
}

function location_cities_list_ch_bs()
{
  return array(
    '6458763' => t('Basel-Stadt'),
  );
}

function location_cities_list_ch_ai()
{
  return array(
    '6458743' => t('Appenzell I.Rh.'),
  );
}

function location_cities_list_ch_sg()
{
  return array(
    '7285000' => t('Wahlkreis Rheintal'),
    '6458838' => t('Wahlkreis Rorschach'),
    '2658792' => t('Wahlkreis Sargans'),
    '7285010' => t('Wahlkreis See-Gaster'),
    '6458770' => t('Wahlkreis St. Gallen'),
    '7285001' => t('Wahlkreis Toggenburg'),
    '6458880' => t('Wahlkreis Werdenberg'),
    '6458840' => t('Wahlkreis Wil'),
  );
}

function location_cities_list_ch_gr()
{
  return array(
    '6458827' => t('Bezirk Albula'),
    '6458759' => t('Bezirk Hinterrhein'),
    '6458905' => t('Bezirk Imboden'),
    '6458858' => t('Bezirk Inn'),
    '7284995' => t('Bezirk Landquart'),
    '7284997' => t('Bezirk Maloja / Distretto di Maloggia'),
    '6458884' => t('Bezirk Plessur'),
    '7285011' => t('Bezirk Prättigau-Davos'),
    '7284999' => t('Bezirk Surselva'),
    '6458851' => t('Distretto di Bernina'),
    '7284998' => t('Distretto di Moesa'),
  );
}

function location_cities_list_ch_ne()
{
  return array(
    '6458825' => t('District de Boudry'),
    '6458886' => t('District de Neuchâtel'),
    '6458831' => t('District de la Chaux-de-Fonds'),
    '6458809' => t('District du Locle'),
    '6458812' => t('District du Val-de-Ruz'),
    '6458835' => t('District du Val-de-Travers'),
  );
}
