<?php


function location_cities_list_sv_ah() {
  return array(
    "3587426" => "Ahuachapan",
  );
}


function location_cities_list_sv_ca() {
  return array(
    "3583158" => "Sensuntepeque",
  );
}


function location_cities_list_sv_ch() {
  return array(
    "3587091" => "Chalatenango",
  );
}


function location_cities_list_sv_cu() {
  return array(
    "3583471" => "San Martin",
    "3586977" => "Cojutepeque",
  );
}


function location_cities_list_sv_li() {
  return array(
    "3583981" => "Quezaltepeque",
    "3584257" => "Santa Tecla",
    "3585157" => "La Libertad",
    "3587362" => "Antiguo Cuscatlan",
  );
}


function location_cities_list_sv_pa() {
  return array(
    "3582805" => "Zacatecoluca",
  );
}


function location_cities_list_sv_un() {
  return array(
    "3584772" => "La Union",
  );
}


function location_cities_list_sv_mo() {
  return array(
    "3583747" => "San Francisco",
  );
}


function location_cities_list_sv_sm() {
  return array(
    "3583379" => "San Rafael Oriente",
    "3583446" => "San Miquel",
  );
}


function location_cities_list_sv_ss() {
  return array(
    "3583096" => "Soyapango",
    "3583361" => "San Salvador",
    "3583480" => "San Marcos",
    "3584399" => "Mejicanos",
    "3585484" => "Ilopango",
    "3586814" => "Delgado",
    "3586833" => "Cuscatancingo",
    "3587308" => "Ayutuxtepeque",
    "3587345" => "Apopa",
    "3587428" => "Aguilares",
  );
}


function location_cities_list_sv_sv() {
  return array(
    "3583178" => "San Vicente",
  );
}


function location_cities_list_sv_sa() {
  return array(
    "3583334" => "Santa Ana",
    "3584384" => "Metapan",
    "3587086" => "Chalchuapa",
  );
}


function location_cities_list_sv_so() {
  return array(
    "3583098" => "Sonzacate",
    "3583102" => "Sonsonate",
    "3585473" => "Izalco",
    "3587498" => "Acajutla",
  );
}


function location_cities_list_sv_us() {
  return array(
    "3582883" => "Usulutan",
    "3583199" => "Santiago de Maria",
    "3584003" => "Puerto El Triunfo",
  );
}
