<?php


function location_cities_list_vc_06() {
  return array();
}


function location_cities_list_vc_01() {
  return array();
}


function location_cities_list_vc_02() {
  return array();
}


function location_cities_list_vc_03() {
  return array();
}


function location_cities_list_vc_04() {
  return array(
    "3577887" => t("Kingstown"),
    "3748726" => t("Kingstown Park"),
  );
}


function location_cities_list_vc_05() {
  return array();
}
