<?php


function location_cities_list_mn_073() {
  return array();
}


function location_cities_list_mn_071() {
  return array(
    "1515436" => "OElgiy",
  );
}


function location_cities_list_mn_069() {
  return array(
    "2032532" => "Bayanhongor",
    "2032533" => "Bayanhongor",
  );
}


function location_cities_list_mn_067() {
  return array(
    "2032201" => "Bulgan",
  );
}


function location_cities_list_mn_047() {
  return array(
    "7648817" => "Zuunmod",
  );
}


function location_cities_list_mn_037() {
  return array(
    "2031964" => "Darhan",
  );
}


function location_cities_list_mn_057() {
  return array(
    "1515007" => "Uliastay",
  );
}


function location_cities_list_mn_061() {
  return array();
}


function location_cities_list_mn_063() {
  return array(
    "2032081" => "Saynshand",
  );
}


function location_cities_list_mn_065() {
  return array(
    "1516393" => "Altai",
  );
}


function location_cities_list_mn_064() {
  return array();
}


function location_cities_list_mn_039() {
  return array();
}


function location_cities_list_mn_043() {
  return array(
    "1516048" => "Khovd",
  );
}


function location_cities_list_mn_041() {
  return array(
    "2029945" => "Murun-kuren",
  );
}


function location_cities_list_mn_059() {
  return array(
    "2030065" => "Mandalgovi",
  );
}


function location_cities_list_mn_035() {
  return array(
    "2031405" => "Erdenet",
  );
}


function location_cities_list_mn_049() {
  return array(
    "2029156" => "Suhbaatar",
    "2031533" => "Dzuunharaa",
  );
}


function location_cities_list_mn_051() {
  return array(
    "2032614" => "Baruun-Urt",
  );
}


function location_cities_list_mn_1() {
  return array(
    "2028462" => "Ulaanbaatar",
  );
}


function location_cities_list_mn_046() {
  return array(
    "1515029" => "Ulaangom",
  );
}


function location_cities_list_mn_053() {
  return array(
    "2032007" => "Dalandzadgad",
  );
}


function location_cities_list_mn_055() {
  return array(
    "2030474" => "Hovd",
    "2032814" => "Arvayheer",
  );
}
