<?php

function location_cities_list_hu_jn () {
	return array (
		"3050907" => t("Jaszbereny"),
		"719404" => t("Karcag"),
		"717635" => t("Mezotur"),
		"715126" => t("Szolnok"),
		"714581" => t("Torokszentmiklos"),
	);
}


function location_cities_list_hu_bz () {
	return array (
		"719311" => t("Kazincbarcika"),
		"717652" => t("Mezokovesd"),
		"717582" => t("Miskolc"),
		"716671" => t("Ozd"),
		"715839" => t("Satoraljaujhely"),
		"714697" => t("Tiszaujvaros"),
	);
}


function location_cities_list_hu_cs () {
	return array (
		"721592" => t("Csongrad"),
		"719965" => t("Hodmezovasarhely"),
		"717902" => t("Mako"),
		"715429" => t("Szeged"),
		"715338" => t("Szentes"),
	);
}


function location_cities_list_hu_be () {
	return array (
		"722439" => t("Bekes"),
		"722437" => t("Bekescsaba"),
		"720364" => t("Gyomaendrod"),
		"720334" => t("Gyula"),
		"716736" => t("Oroshaza"),
		"715466" => t("Szarvas"),
	);
}


function location_cities_list_hu_hb () {
	return array (
		"722636" => t("Balmazujvaros"),
		"722324" => t("Berettyoujfalu"),
		"721472" => t("Debrecen"),
		"720292" => t("Hajduboszormeny"),
		"720284" => t("Hajdunanas"),
		"720276" => t("Hajduszoboszlo"),
		"716301" => t("Puspokladany"),
	);
}


function location_cities_list_hu_sz () {
	return array (
		"718739" => t("Kisvarda"),
		"717771" => t("Mateszalka"),
		"716935" => t("Nyiregyhaza"),
	);
}


function location_cities_list_hu_he () {
	return array (
		"721239" => t("Eger"),
		"3052040" => t("Gyongyos"),
		"3051621" => t("Hatvan"),
		"3046619" => t("Paradsasvar"),
	);
}


function location_cities_list_hu_pe () {
	return array (
		"723030" => t("Abony"),
		"3054646" => t("Budaors"),
		"3054543" => t("Cegled"),
		"3053836" => t("Dabas"),
		"3053485" => t("Dunaharaszti"),
		"3053476" => t("Dunakeszi"),
		"3053281" => t("Erd"),
		"3052542" => t("Fot"),
		"3052241" => t("God"),
		"3052236" => t("Godollo"),
		"3052101" => t("Gyal"),
		"3047942" => t("Monor"),
		"3047651" => t("Nagykoros"),
		"3044821" => t("Szazhalombatta"),
		"3044681" => t("Szentendre"),
		"3044475" => t("Szigetszentmiklos"),
		"3043293" => t("Vac"),
		"3043019" => t("Vecses"),
	);
}


function location_cities_list_hu_za () {
	return array (
		"3050212" => t("Keszthely"),
		"3047679" => t("Nagykanizsa"),
		"3042638" => t("Zalaegerszeg"),
	);
}


function location_cities_list_hu_ve () {
	return array (
		"3056357" => t("Ajka"),
		"3046686" => t("Papa"),
		"3044141" => t("Tapolca"),
		"3043095" => t("Varpalota"),
		"3042929" => t("Veszprem"),
	);
}


function location_cities_list_hu_ke () {
	return array (
		"3053163" => t("Esztergom"),
		"3049519" => t("Komarom"),
		"3046888" => t("Oroszlany"),
		"3044083" => t("Tata"),
		"3044082" => t("Tatabanya"),
	);
}


function location_cities_list_hu_va () {
	return array (
		"3045487" => t("Sarvar"),
		"3044310" => t("Szombathely"),
	);
}


function location_cities_list_hu_to () {
	return array (
		"3053590" => t("Dombovar"),
		"3046768" => t("Paks"),
		"3044760" => t("Szekszard"),
	);
}


function location_cities_list_hu_fe () {
	return array (
		"3053438" => t("Dunaujvaros"),
		"3044774" => t("Szekesfehervar"),
	);
}


function location_cities_list_hu_gs () {
	return array (
		"3052009" => t("Gyor"),
		"3047896" => t("Mosonmagyarovar"),
		"3045190" => t("Sopron"),
	);
}


function location_cities_list_hu_so () {
	return array (
		"3050616" => t("Kaposvar"),
		"3045332" => t("Siofok"),
	);
}


function location_cities_list_hu_no () {
	return array (
		"3055601" => t("Balassagyarmat"),
		"3045643" => t("Salgotarjan"),
	);
}


function location_cities_list_hu_ba () {
	return array (
		"3049512" => t("Komlo"),
		"3047967" => t("Mohacs"),
		"3046526" => t("Pecs"),
	);
}


function location_cities_list_hu_bk () {
	return array (
		"3055685" => t("Baja"),
		"3050719" => t("Kalocsa"),
		"3050434" => t("Kecskemet"),
		"3049896" => t("Kiskoros"),
		"3049885" => t("Kiskunfelegyhaza"),
		"3049880" => t("Kiskunhalas"),
	);
}


function location_cities_list_hu_bu () {
	return array (
		"3054643" => t("Budapest"),
		"7284844" => t("Budapest I. keruelet"),
		"7284843" => t("Budapest II. keruelet"),
		"7284842" => t("Budapest III. keruelet"),
		"7284831" => t("Budapest IV. keruelet"),
		"7284825" => t("Budapest IX. keruelet"),
		"7284828" => t("Budapest VI. keruelet"),
		"7284827" => t("Budapest VII. keruelet"),
		"7284826" => t("Budapest VIII. keruelet"),
		"7284834" => t("Budapest X. keruelet"),
		"7284824" => t("Budapest XI. keruelet"),
		"7284823" => t("Budapest XII. keruelet"),
		"7284830" => t("Budapest XIII. keruelet"),
		"7284829" => t("Budapest XIV. keruelet"),
		"7284835" => t("Budapest XIX. keruelet"),
		"7284832" => t("Budapest XV. keruelet"),
		"7284833" => t("Budapest XVI. keruelet"),
		"7284841" => t("Budapest XVII. keruelet"),
		"7284836" => t("Budapest XVIII. keruelet"),
		"7284840" => t("Budapest XX. keruelet"),
		"7284839" => t("Budapest XXI. keruelet"),
		"7284838" => t("Budapest XXII. keruelet"),
		"7284837" => t("Budapest XXIII. keruelet"),
	);
}


