<?php

function location_cities_list_cf_bk () {
	return array (
		"237478" => t("Mobaye"),
	);
}


function location_cities_list_cf_uk () {
	return array (
		"240604" => t("Bambari"),
		"238566" => t("Ippy"),
	);
}


function location_cities_list_cf_hk () {
	return array (
		"239899" => t("Bria"),
	);
}


function location_cities_list_cf_mb () {
	return array (
		"240498" => t("Bangassou"),
	);
}


function location_cities_list_cf_kg () {
	return array (
		"2383119" => t("Sibut"),
	);
}


function location_cities_list_cf_op () {
	return array (
		"2387546" => t("Bozoum"),
		"2383523" => t("Paoua"),
	);
}


function location_cities_list_cf_se () {
	return array (
		"2383827" => t("Nola"),
	);
}


function location_cities_list_cf_lb () {
	return array (
		"2388614" => t("Boda"),
		"2384770" => t("Mbaiki"),
	);
}


function location_cities_list_cf_kb () {
	return array (
		"2386012" => t("Kaga Bandoro"),
	);
}


function location_cities_list_cf_mp () {
	return array (
		"2388873" => t("Bimbo"),
		"2387435" => t("Damara"),
	);
}


function location_cities_list_cf_hs () {
	return array (
		"2389086" => t("Berberati"),
		"2387495" => t("Carnot"),
	);
}


function location_cities_list_cf_nm () {
	return array (
		"2387926" => t("Bouar"),
	);
}


function location_cities_list_cf_ac () {
	return array (
		"2389691" => t("Batangafo"),
		"2388036" => t("Bossangoa"),
	);
}


function location_cities_list_cf_bgf () {
	return array (
		"2389853" => t("Bangui"),
	);
}


