<?php

function location_cities_list_lt_vl () {
	return array (
		"593116" => t("Vilnius"),
	);
}


function location_cities_list_lt_ut () {
	return array (
		"593672" => t("Utena"),
	);
}


function location_cities_list_lt_te () {
	return array (
		"597188" => t("Mazeikiai"),
		"593926" => t("Telsiai"),
	);
}


function location_cities_list_lt_ta () {
	return array (
		"593959" => t("Taurage"),
	);
}


function location_cities_list_lt_sa () {
	return array (
		"594739" => t("Siauliai"),
	);
}


function location_cities_list_lt_pn () {
	return array (
		"596128" => t("Panevezys"),
	);
}


function location_cities_list_lt_kl () {
	return array (
		"598098" => t("Klaipeda"),
		"596238" => t("Palanga"),
	);
}


function location_cities_list_lt_mr () {
	return array (
		"597231" => t("Marijampole"),
	);
}


function location_cities_list_lt_ku () {
	return array (
		"598818" => t("Jonava"),
		"598316" => t("Kaunas"),
		"598272" => t("Kedainiai"),
	);
}


function location_cities_list_lt_al () {
	return array (
		"601084" => t("Alytus"),
	);
}


