<?php


function location_cities_list_cl_an() {
  return array(
    "3869716" => "Tocopilla",
    "3897347" => "Calama",
    "3899539" => "Antofagasta",
  );
}


function location_cities_list_cl_at() {
  return array(
    "3868633" => "Vallenar",
    "3892454" => "Diego de Almagro",
    "3893656" => "Copiapo",
  );
}


function location_cities_list_cl_co() {
  return array(
    "3877918" => "Ovalle",
    "3884373" => "La Serena",
    "3887344" => "Illapel",
    "3893629" => "Coquimbo",
  );
}


function location_cities_list_cl_ll() {
  return array(
    "3874930" => "Puerto Varas",
    "3874943" => "Puerto Quellon",
    "3874960" => "Puerto Montt",
    "3877949" => "Osorno",
    "3883629" => "La Union",
    "3889263" => "Frutillar",
    "3896218" => "Castro",
    "3899695" => "Ancud",
    "6458708" => "Las Animas",
  );
}


function location_cities_list_cl_ml() {
  return array(
    "3870294" => "Talca",
    "3872154" => "San Javier",
    "3877146" => "Parral",
    "3879627" => "Molina",
    "3883167" => "Linares",
    "3892870" => "Curico",
    "3893726" => "Constitucion",
    "3896105" => "Cauquenes",
  );
}


function location_cities_list_cl_ai() {
  return array(
    "3874997" => "Puerto Aisen",
    "3894426" => "Coihaique",
  );
}


function location_cities_list_cl_ap() {
  return array(
    "3899361" => "Arica",
  );
}


function location_cities_list_cl_lr() {
  return array(
    "3868707" => "Valdivia",
    "3873145" => "Rio Bueno",
  );
}


function location_cities_list_cl_ma() {
  return array(
    "3874787" => "Punta Arenas",
    "3874958" => "Puerto Natales",
  );
}


function location_cities_list_cl_vs() {
  return array(
    "3868121" => "Vina del Mar",
    "3868192" => "Villa Alemana",
    "3868626" => "Valparaiso",
    "3872255" => "San Felipe",
    "3872395" => "San Antonio",
    "3874096" => "Quilpue",
    "3874119" => "Quillota",
    "3882434" => "Los Andes",
    "3883035" => "Llaillay",
    "3883214" => "Limache",
    "3885456" => "La Ligua",
    "3888214" => "Hacienda La Calera",
    "3896433" => "Cartagena",
  );
}


function location_cities_list_cl_ar() {
  return array(
    "3868158" => "Villarrica",
    "3868326" => "Victoria",
    "3870011" => "Temuco",
    "3875070" => "Pucon",
    "3877348" => "Panguipulli",
    "3878456" => "Nueva Imperial",
    "3882582" => "Loncoche",
    "3883615" => "Lautaro",
    "3894177" => "Collipulli",
    "3899629" => "Angol",
  );
}


function location_cities_list_cl_bi() {
  return array(
    "3869657" => "Tome",
    "3870282" => "Talcahuano",
    "3872326" => "San Carlos",
    "3876664" => "Penco",
    "3879123" => "Nacimiento",
    "3879200" => "Mulchen",
    "3881276" => "Lota",
    "3882428" => "Los Angeles",
    "3883457" => "Lebu",
    "3885509" => "La Laja",
    "3892892" => "Curanilahue",
    "3893532" => "Coronel",
    "3893894" => "Concepcion",
    "3895088" => "Chillan",
    "3895138" => "Chiguayante",
    "3896924" => "Canete",
    "3897557" => "Cabrero",
    "3899462" => "Arauco",
  );
}


function location_cities_list_cl_li() {
  return array(
    "3871286" => "San Vicente",
    "3871616" => "Santa Cruz",
    "3873441" => "Rengo",
    "3873775" => "Rancagua",
    "3881102" => "Machali",
    "3888749" => "Graneros",
    "3895061" => "Chimbarongo",
  );
}


function location_cities_list_cl_rm() {
  return array(
    "3870306" => "Talagante",
    "3871336" => "Santiago",
    "3872348" => "San Bernardo",
    "3875024" => "Puente Alto",
    "3876685" => "Penaflor",
    "3877739" => "Paine",
    "3880107" => "Melipilla",
    "3885273" => "Lampa",
    "3890949" => "El Monte",
    "3895165" => "Chicureo Abajo",
    "3897774" => "Buin",
    "7281017" => "La Pintana",
    "7281020" => "Lo Prado",
  );
}


function location_cities_list_cl_ta() {
  return array(
    "3887127" => "Iquique",
  );
}
