<?php

function location_cities_list_cl_an () {
	return array (
		"3869716" => t("Tocopilla"),
		"3897347" => t("Calama"),
		"3899539" => t("Antofagasta"),
	);
}


function location_cities_list_cl_at () {
	return array (
		"3868633" => t("Vallenar"),
		"3892454" => t("Diego de Almagro"),
		"3893656" => t("Copiapo"),
	);
}


function location_cities_list_cl_co () {
	return array (
		"3877918" => t("Ovalle"),
		"3884373" => t("La Serena"),
		"3887344" => t("Illapel"),
		"3893629" => t("Coquimbo"),
	);
}


function location_cities_list_cl_ll () {
	return array (
		"3874930" => t("Puerto Varas"),
		"3874943" => t("Puerto Quellon"),
		"3874960" => t("Puerto Montt"),
		"3877949" => t("Osorno"),
		"3883629" => t("La Union"),
		"3889263" => t("Frutillar"),
		"3896218" => t("Castro"),
		"3899695" => t("Ancud"),
		"6458708" => t("Las Animas"),
	);
}


function location_cities_list_cl_ml () {
	return array (
		"3870294" => t("Talca"),
		"3872154" => t("San Javier"),
		"3877146" => t("Parral"),
		"3879627" => t("Molina"),
		"3883167" => t("Linares"),
		"3892870" => t("Curico"),
		"3893726" => t("Constitucion"),
		"3896105" => t("Cauquenes"),
	);
}


function location_cities_list_cl_ai () {
	return array (
		"3874997" => t("Puerto Aisen"),
		"3894426" => t("Coihaique"),
	);
}


function location_cities_list_cl_ap () {
	return array (
		"3899361" => t("Arica"),
	);
}


function location_cities_list_cl_lr () {
	return array (
		"3868707" => t("Valdivia"),
		"3873145" => t("Rio Bueno"),
	);
}


function location_cities_list_cl_ma () {
	return array (
		"3874787" => t("Punta Arenas"),
		"3874958" => t("Puerto Natales"),
	);
}


function location_cities_list_cl_vs () {
	return array (
		"3868121" => t("Vina del Mar"),
		"3868192" => t("Villa Alemana"),
		"3868626" => t("Valparaiso"),
		"3872255" => t("San Felipe"),
		"3872395" => t("San Antonio"),
		"3874096" => t("Quilpue"),
		"3874119" => t("Quillota"),
		"3882434" => t("Los Andes"),
		"3883035" => t("Llaillay"),
		"3883214" => t("Limache"),
		"3885456" => t("La Ligua"),
		"3888214" => t("Hacienda La Calera"),
		"3896433" => t("Cartagena"),
	);
}


function location_cities_list_cl_ar () {
	return array (
		"3868158" => t("Villarrica"),
		"3868326" => t("Victoria"),
		"3870011" => t("Temuco"),
		"3875070" => t("Pucon"),
		"3877348" => t("Panguipulli"),
		"3878456" => t("Nueva Imperial"),
		"3882582" => t("Loncoche"),
		"3883615" => t("Lautaro"),
		"3894177" => t("Collipulli"),
		"3899629" => t("Angol"),
	);
}


function location_cities_list_cl_bi () {
	return array (
		"3869657" => t("Tome"),
		"3870282" => t("Talcahuano"),
		"3872326" => t("San Carlos"),
		"3876664" => t("Penco"),
		"3879123" => t("Nacimiento"),
		"3879200" => t("Mulchen"),
		"3881276" => t("Lota"),
		"3882428" => t("Los Angeles"),
		"3883457" => t("Lebu"),
		"3885509" => t("La Laja"),
		"3892892" => t("Curanilahue"),
		"3893532" => t("Coronel"),
		"3893894" => t("Concepcion"),
		"3895088" => t("Chillan"),
		"3895138" => t("Chiguayante"),
		"3896924" => t("Canete"),
		"3897557" => t("Cabrero"),
		"3899462" => t("Arauco"),
	);
}


function location_cities_list_cl_li () {
	return array (
		"3871286" => t("San Vicente"),
		"3871616" => t("Santa Cruz"),
		"3873441" => t("Rengo"),
		"3873775" => t("Rancagua"),
		"3881102" => t("Machali"),
		"3888749" => t("Graneros"),
		"3895061" => t("Chimbarongo"),
	);
}


function location_cities_list_cl_rm () {
	return array (
		"3870306" => t("Talagante"),
		"3871336" => t("Santiago"),
		"3872348" => t("San Bernardo"),
		"3875024" => t("Puente Alto"),
		"3876685" => t("Penaflor"),
		"3877739" => t("Paine"),
		"3880107" => t("Melipilla"),
		"3885273" => t("Lampa"),
		"3890949" => t("El Monte"),
		"3895165" => t("Chicureo Abajo"),
		"3897774" => t("Buin"),
		"7281017" => t("La Pintana"),
		"7281020" => t("Lo Prado"),
	);
}


function location_cities_list_cl_ta () {
	return array (
		"3887127" => t("Iquique"),
	);
}
