<?php

function location_cities_list_sy_rd () {
	return array (
		"173598" => t("Al Kiswah"),
		"173312" => t("Al Qutayfah"),
		"173193" => t("An Nabk"),
		"172349" => t("At Tall"),
		"172059" => t("Az Zabadani"),
		"170892" => t("Darayya"),
		"170592" => t("Douma"),
		"169897" => t("Harasta"),
		"169113" => t("Jayrud"),
		"166111" => t("Qarah"),
		"165929" => t("Qatana"),
		"162627" => t("Yabrud"),
		"169372" => t("`Irbin"),
	);
}


function location_cities_list_sy_hm () {
	return array (
		"170044" => t("Halfaya"),
		"170017" => t("Hamah"),
		"168620" => t("Kafr Zaytah"),
		"167046" => t("Masyaf"),
		"164947" => t("Salamiyah"),
		"163915" => t("Souran"),
		"163270" => t("Tayyibat al Imam"),
	);
}


function location_cities_list_sy_ta () {
	return array (
		"171830" => t("Baniyas"),
		"165060" => t("Satita"),
		"163345" => t("Tartouss"),
	);
}


function location_cities_list_sy_hl () {
	return array (
		"174018" => t("Al Bab"),
		"170063" => t("Aleppo"),
		"170785" => t("Dayr Hafir"),
		"172082" => t("I`zaz"),
		"169179" => t("Jarabulus"),
		"167357" => t("Manbij"),
		"166331" => t("Nubl"),
		"172503" => t("Safirah"),
		"163811" => t("Tadif"),
		"163476" => t("Tall Rif`at"),
		"174186" => t("`Afrin"),
	);
}


function location_cities_list_sy_hi () {
	return array (
		"173361" => t("Al Qaryatayn"),
		"173322" => t("Al Qusayr"),
		"172946" => t("Ar Rastan"),
		"169577" => t("Homs"),
		"168668" => t("Kafr Laha"),
		"163808" => t("Tadmur"),
		"163533" => t("Tall Kalakh"),
		"163779" => t("Tallbisah"),
	);
}


function location_cities_list_sy_dr () {
	return array (
		"173819" => t("Al Harak"),
		"170905" => t("Dar'a"),
		"169375" => t("Inkhil"),
		"165997" => t("Jasim"),
		"172469" => t("Sanamayn"),
		"164328" => t("Shaykh Miskin"),
		"163806" => t("Tafas"),
	);
}


function location_cities_list_sy_dy () {
	return array (
		"174448" => t("Albu Kamal"),
		"170794" => t("Deir ez-Zor"),
		"174506" => t("Hajin"),
		"173480" => t("Mayadin"),
		"164025" => t("Subaykhan"),
	);
}


function location_cities_list_sy_id () {
	return array (
		"174259" => t("Ad Dana"),
		"171451" => t("Binnish"),
		"169389" => t("Idlib"),
		"169023" => t("Jisr ash Shughur"),
		"168661" => t("Kafr Nabl"),
		"168629" => t("Kafr Takharim"),
		"168325" => t("Khan Shaykhun"),
		"167605" => t("Ma`arrat Misrin"),
		"164898" => t("Salqin"),
		"164816" => t("Saraqib"),
	);
}


function location_cities_list_sy_la () {
	return array (
		"169304" => t("Jablah"),
		"173576" => t("Latakia"),
	);
}


function location_cities_list_sy_di () {
	return array (
		"170654" => t("Damascus"),
	);
}


function location_cities_list_sy_ha () {
	return array (
		"170887" => t("Ad Darbasiyah"),
		"173811" => t("Al Hasakah"),
	);
}


function location_cities_list_sy_ra () {
	return array (
		"172955" => t("Ar Raqqah"),
		"172374" => t("Thawrah"),
	);
}


function location_cities_list_sy_su () {
	return array (
		"172408" => t("As Suwayda'"),
	);
}


function location_cities_list_sy_qu () {
	return array (
		"173334" => t("Al Qunaytirah"),
	);
}


