<?php

function location_cities_list_tt_tup () {
	return array (
		"3573989" => t("Paradise"),
		"3573576" => t("Tunapuna"),
	);
}


function location_cities_list_tt_wto () {
	return array (
		"3573703" => t("Scarborough"),
	);
}


function location_cities_list_tt_sge () {
	return array (
		"3573732" => t("Sangre Grande"),
	);
}


function location_cities_list_tt_sfo () {
	return array (
		"3574194" => t("Marabella"),
		"3574116" => t("Mon Repos"),
		"3573738" => t("San Fernando"),
	);
}


function location_cities_list_tt_rcm () {
	return array (
		"3573840" => t("Rio Claro"),
	);
}


function location_cities_list_tt_pos () {
	return array (
		"3573890" => t("Port-of-Spain"),
	);
}


function location_cities_list_tt_ptf () {
	return array (
		"3573899" => t("Point Fortin"),
	);
}


function location_cities_list_tt_sjl () {
	return array (
		"3574309" => t("Laventille"),
	);
}


function location_cities_list_tt_cha () {
	return array (
		"3574810" => t("Chaguanas"),
	);
}


function location_cities_list_tt_ari () {
	return array (
		"3575051" => t("Arima"),
	);
}


