<?php


function location_cities_list_bd_a () {
	return array (
		"1185138" => t("Pirojpur"),
		"1185156" => t("Nalchiti"),
		"1185171" => t("Mehendiganj"),
		"1185173" => t("Mathba"),
		"1185210" => t("Gaurnadi"),
		"1185251" => t("Lalmohan"),
		"1210565" => t("Burhanuddin"),
		"1336136" => t("Bhola"),
		"1336137" => t("Barisal"),
		"1477498" => t("Bhandaria"),
	);
}


function location_cities_list_bd_b () {
	return array (
		"1185095" => t("Teknaf"),
		"1185120" => t("Sandwip"),
		"1185127" => t("Ramganj"),
		"1185148" => t("Patiya"),
		"1185183" => t("Laksham"),
		"1185186" => t("Comilla"),
		"1185224" => t("Feni"),
		"1185236" => t("Raipur"),
		"1185249" => t("Chhagalnaiya"),
		"1185252" => t("Khagrachhari"),
		"1185270" => t("Bandarban"),
		"1189638" => t("Raojan"),
		"1193823" => t("Nabinagar"),
		"1196292" => t("Lakshmipur"),
		"1201753" => t("Hajiganj"),
		"1205733" => t("Chittagong"),
		"1336133" => t("Satkania"),
		"1336134" => t("Cox's Bazar"),
		"1462681" => t("Manikchari"),
		"6414184" => t("Fatikchari"),
	);
}


function location_cities_list_bd_c () {
	return array (
		"1185098" => t("Tungi"),
		"1185100" => t("Dohar"),
		"1185106" => t("Jamalpur"),
		"1185116" => t("Netrakona"),
		"1185117" => t("Narsingdi"),
		"1185155" => t("Narayanganj"),
		"1185159" => t("Nagarpur"),
		"1185162" => t("Mymensingh"),
		"1185164" => t("Muktagacha"),
		"1185165" => t("Mirzapur"),
		"1185218" => t("Gafargaon"),
		"1185241" => t("Dhaka"),
		"1185263" => t("Bhairab Bazar"),
		"1185276" => t("Bajitpur"),
		"1185920" => t("Tungipara"),
		"1188569" => t("Sarishabari"),
		"1189056" => t("Sakhipur"),
		"1203344" => t("Faridpur"),
		"1207047" => t("Char Bhadrasan"),
		"1336144" => t("Tangail"),
		"1337245" => t("Madaripur"),
		"1337248" => t("Sherpur"),
		"1337249" => t("Kishorganj"),
	);
}


function location_cities_list_bd_d () {
	return array (
		"1185111" => t("Satkhira"),
		"1185167" => t("Morrelgonj"),
		"1185191" => t("Kushtia"),
		"1185199" => t("Kaliganj"),
		"1185204" => t("Jhingergacha"),
		"1185239" => t("Sarankhola"),
		"1185260" => t("Bhatpara Abhaynagar"),
		"1185262" => t("Bheramara"),
		"1185272" => t("Kalia"),
		"1185293" => t("Narail"),
		"1191139" => t("Phultala"),
		"1197895" => t("Kesabpur"),
		"1205481" => t("Uttar Char Fasson"),
		"1336135" => t("Khulna"),
		"1336140" => t("Jessore"),
	);
}


function location_cities_list_bd_f () {
	return array (
		"1185092" => t("Thakurgaon"),
		"1185141" => t("Panchagarh"),
		"1185149" => t("Parbatipur"),
		"1185160" => t("Nageswari"),
		"1185181" => t("Lalmanirhat"),
		"1185188" => t("Rangpur"),
		"1185247" => t("Chilmari"),
		"1185283" => t("Badarganj"),
		"1203891" => t("Dinajpur"),
		"1337239" => t("Pirgaaj"),
	);
}


function location_cities_list_bd_e () {
	return array (
		"1185108" => t("Shibganj"),
		"1185115" => t("Sirajganj"),
		"1185121" => t("Shahzadpur"),
		"1185128" => t("Rajshahi"),
		"1185206" => t("Joypur Hat"),
		"1185207" => t("Ishurdi"),
		"1192366" => t("Par Naogaon"),
		"1209562" => t("Bera"),
		"1337233" => t("Bogra"),
		"1337240" => t("Nawabganj"),
		"6545349" => t("Saidpur"),
	);
}


function location_cities_list_bd_g () {
	return array (
		"1185099" => t("Sylhet"),
		"1185166" => t("Maulavi Bazar"),
		"1185209" => t("Habiganj"),
		"1185254" => t("Chhatak"),
		"1185274" => t("Baniachang"),
	);
}
