<?php


function location_cities_list_tm_a() {
  return array(
    "162099"  => "Buzmeyin",
    "162158"  => "Baherden",
    "162183"  => "Ashgabat",
    "1218239" => "Tejen",
  );
}


function location_cities_list_tm_b() {
  return array(
    "161616" => "Balkanabat",
    "161943" => "Gumdag",
    "161974" => "Gazanjyk",
    "601594" => "Turkmenbasy",
  );
}


function location_cities_list_tm_d() {
  return array(
    "601734" => "Dasoguz",
  );
}


function location_cities_list_tm_l() {
  return array(
    "1218436" => "Sayat",
    "1219002" => "Atamyrat",
    "1219392" => "Gowurdak",
    "1219649" => "Turkmenabat",
  );
}


function location_cities_list_tm_m() {
  return array(
    "1218667" => "Mary",
    "1219762" => "Bayramaly",
  );
}
