<?php

function location_cities_list_ht_ar () {
	return array (
		"3726674" => t("Desarmes"),
		"3724696" => t("Gonaives"),
		"3717588" => t("Saint-Marc"),
		"3716044" => t("Verrettes"),
	);
}


function location_cities_list_ht_ou () {
	return array (
		"3728338" => t("Carrefour"),
		"3727135" => t("Croix des Bouquets"),
		"3726786" => t("Delmas 73"),
		"3725276" => t("Fond Parisien"),
		"3724337" => t("Grand Goave"),
		"3724233" => t("Gressier"),
		"3723440" => t("Kenscoff"),
		"3722286" => t("Leogane"),
		"3719028" => t("Petionville"),
		"3718962" => t("Petit Goave"),
		"3718426" => t("Port-au-Prince"),
		"3716667" => t("Thomazeau"),
	);
}


function location_cities_list_ht_nd () {
	return array (
		"3728474" => t("Cap-Haitien"),
		"3722124" => t("Limbe"),
		"3717546" => t("Saint-Raphael"),
	);
}


function location_cities_list_ht_no () {
	return array (
		"3718420" => t("Port-de-Paix"),
		"3740016" => t("Ti Port-de-Paix"),
	);
}


function location_cities_list_ht_ga () {
	return array (
		"3723593" => t("Jeremie"),
	);
}


function location_cities_list_ht_se () {
	return array (
		"3723779" => t("Jacmel"),
	);
}


function location_cities_list_ht_ce () {
	return array (
		"3723841" => t("Hinche"),
	);
}


function location_cities_list_ht_sd () {
	return array (
		"3728097" => t("Les Cayes"),
	);
}


