<?php

function location_cities_list_ng_ke () {
	return array (
		"2349431" => t("Argungu"),
		"2347059" => t("Birnin Kebbi"),
		"2336237" => t("Jega"),
		"2335333" => t("Kamba"),
		"2317548" => t("Zuru"),
	);
}


function location_cities_list_ng_ni () {
	return array (
		"2348507" => t("Babana"),
		"2347592" => t("Baro"),
		"2347209" => t("Bida"),
		"2339293" => t("Ibeto"),
		"2334008" => t("Kontagora"),
		"2332249" => t("Lapai"),
		"2330100" => t("Minna"),
		"2329981" => t("Mokwa"),
		"2324504" => t("Rijau"),
		"2322794" => t("Suleja"),
		"2322263" => t("Tegina"),
		"2317569" => t("Zungeru"),
	);
}


function location_cities_list_ng_kd () {
	return array (
		"2349951" => t("Anchau"),
		"2344229" => t("Dutsen Wai"),
		"2335798" => t("Kachia"),
		"2335727" => t("Kaduna"),
		"2335713" => t("Kafachan"),
		"2335614" => t("Kagoro"),
		"2332079" => t("Lere"),
		"2322957" => t("Soba"),
		"2347061" => t("Sofo-Birnin-Gwari"),
		"2317765" => t("Zaria"),
	);
}


function location_cities_list_ng_ad () {
	return array (
		"2341955" => t("Ganye"),
		"2336056" => t("Jimeta"),
		"2340446" => t("Little Gombi"),
		"2329821" => t("Mubi"),
		"2328617" => t("Numan"),
		"2318044" => t("Yola"),
	);
}


function location_cities_list_ng_by () {
	return array (
		"2318123" => t("Yenagoa"),
	);
}


function location_cities_list_ng_ta () {
	return array (
		"2347330" => t("Beli"),
		"2341275" => t("Gembu"),
		"2339287" => t("Ibi"),
		"2336589" => t("Jalingo"),
		"2318921" => t("Wukari"),
	);
}


function location_cities_list_ng_kn () {
	return array (
		"2341580" => t("Gaya"),
		"2339756" => t("Gwarzo"),
		"2335204" => t("Kano"),
		"2324575" => t("Rano"),
		"2318933" => t("Wudil"),
	);
}


function location_cities_list_ng_de () {
	return array (
		"2351979" => t("Agbor"),
		"2349276" => t("Asaba"),
		"2346317" => t("Burutu"),
		"2332871" => t("Kwale"),
		"2327513" => t("Ogwashi-Uku"),
		"2323675" => t("Sapele"),
		"2320829" => t("Ughelli"),
		"2319133" => t("Warri"),
	);
}


function location_cities_list_ng_na () {
	return array (
		"2350806" => t("Akwanga"),
		"2344600" => t("Doma"),
		"2334652" => t("Keffi"),
		"2332515" => t("Lafia"),
		"2329451" => t("Nassarawa"),
		"2319257" => t("Wamba"),
	);
}


function location_cities_list_ng_ak () {
	return array (
		"2343720" => t("Eket"),
		"2343093" => t("Esuk Oron"),
		"2338106" => t("Ikot-Ekpene"),
		"2336985" => t("Itu"),
		"2319480" => t("Uyo"),
	);
}


function location_cities_list_ng_ed () {
	return array (
		"2348892" => t("Auchi"),
		"2347283" => t("Benin City"),
		"2343641" => t("Ekpoma"),
		"2321031" => t("Ubiaja"),
		"2319668" => t("Uromi"),
	);
}


function location_cities_list_ng_ab () {
	return array (
		"2353151" => t("Aba"),
		"2350249" => t("Amaigbo"),
		"2347303" => t("Bende"),
		"2327494" => t("Ohafia-Ifigh"),
		"2320576" => t("Umuahia"),
	);
}


function location_cities_list_ng_cr () {
	return array (
		"2346229" => t("Calabar"),
		"2338242" => t("Ikom"),
		"2328151" => t("Obudu"),
		"2327650" => t("Ogoja"),
		"2320831" => t("Ugep"),
	);
}


function location_cities_list_ng_an () {
	return array (
		"2351740" => t("Agulu"),
		"2348773" => t("Awka"),
		"2343270" => t("Enugu-Ukwu"),
		"2338640" => t("Igbo-Ukwu"),
		"2338497" => t("Ihiala"),
		"2328811" => t("Nkpor"),
		"2328765" => t("Nnewi"),
		"2326016" => t("Onitsha"),
		"2325161" => t("Ozubulu"),
		"2320920" => t("Uga"),
	);
}


function location_cities_list_ng_so () {
	return array (
		"2339892" => t("Gwadabawa"),
		"2337680" => t("Illela"),
		"2322911" => t("Sokoto"),
		"2322495" => t("Tambawel"),
	);
}


function location_cities_list_ng_za () {
	return array (
		"2340086" => t("Gummi"),
		"2339937" => t("Gusau"),
		"2334756" => t("Kaura Namoda"),
		"2329920" => t("Moriki"),
		"2322529" => t("Talata Mafara"),
	);
}


function location_cities_list_ng_be () {
	return array (
		"2338660" => t("Igbor"),
		"2334801" => t("Katsina Ala"),
		"2331140" => t("Makurdi"),
		"2325437" => t("Otukpa"),
		"2322552" => t("Takum"),
	);
}


function location_cities_list_ng_oy () {
	return array (
		"2342628" => t("Fiditi"),
		"2339354" => t("Ibadan"),
		"2338772" => t("Igbeti"),
		"2338669" => t("Igbo Ora"),
		"2338711" => t("Igboho"),
		"2334327" => t("Kishi"),
		"2332357" => t("Lalupon"),
		"2325733" => t("Orita Eruwa"),
		"2325200" => t("Oyo"),
		"2323390" => t("Saki"),
	);
}


function location_cities_list_ng_og () {
	return array (
		"2352947" => t("Abeokuta"),
		"2352356" => t("Ado Odo"),
		"2338876" => t("Ifo"),
		"2338403" => t("Ijebu-Igbo"),
		"2338400" => t("Ijebu-Ode"),
		"2337759" => t("Ilaro"),
		"2337379" => t("Iperu"),
		"2323411" => t("Shagamu"),
	);
}


function location_cities_list_ng_yo () {
	return array (
		"2345521" => t("Damaturu"),
		"2345096" => t("Daura"),
		"2341656" => t("Gashua"),
		"2341294" => t("Geidam"),
		"2333490" => t("Kumagunnam"),
		"2328952" => t("Nguru"),
		"2324767" => t("Potiskum"),
	);
}


function location_cities_list_ng_ri () {
	return array (
		"2346812" => t("Bonny"),
		"2346615" => t("Buguma"),
		"2591159" => t("Degema Hulk"),
		"2343512" => t("Elele"),
		"2328185" => t("Obonoma"),
		"2326899" => t("Okrika"),
		"2324774" => t("Port Harcourt"),
	);
}


function location_cities_list_ng_go () {
	return array (
		"2347155" => t("Biliri"),
		"2345029" => t("Deba Habe"),
		"2344418" => t("Dukku"),
		"2341758" => t("Garko"),
		"2340451" => t("Gombe"),
		"2333451" => t("Kumo"),
		"2329562" => t("Nafada"),
		"2324857" => t("Pindiga"),
	);
}


function location_cities_list_ng_kw () {
	return array (
		"2346951" => t("Bode Sadu"),
		"2337639" => t("Ilorin"),
		"2336251" => t("Jebba"),
		"2335596" => t("Kaiama"),
		"2332504" => t("Lafiagi"),
		"2327879" => t("Offa"),
		"2326811" => t("Okuta"),
		"2324960" => t("Pategi"),
	);
}


function location_cities_list_ng_pl () {
	return array (
		"2346561" => t("Bukuru"),
		"2335953" => t("Jos"),
		"2325060" => t("Pankshin"),
	);
}


function location_cities_list_ng_os () {
	return array (
		"2349558" => t("Apomu"),
		"2343983" => t("Effon Alaiye"),
		"2343784" => t("Ejigbo"),
		"2341355" => t("Gbongan"),
		"2338401" => t("Ijebu Ijesha"),
		"2338273" => t("Ikire"),
		"2338269" => t("Ikirun"),
		"2337765" => t("Ila Orangun"),
		"2337704" => t("Ilesa"),
		"2337659" => t("Ilobu"),
		"2337490" => t("Inisa"),
		"2336905" => t("Iwo"),
		"2330028" => t("Modakeke"),
		"2327223" => t("Oke Mesi"),
		"2326302" => t("Olupona"),
		"2325590" => t("Osogbo"),
		"2325506" => t("Otan Aiyegbaju"),
		"2325249" => t("Oyan"),
	);
}


function location_cities_list_ng_on () {
	return array (
		"2350841" => t("Akure"),
		"2339150" => t("Idanre"),
		"2328090" => t("Ode"),
		"2326171" => t("Ondo"),
		"2325314" => t("Owo"),
	);
}


function location_cities_list_ng_im () {
	return array (
		"2328790" => t("Nkwerre"),
		"2327521" => t("Oguta"),
		"2327143" => t("Okigwi"),
		"2325330" => t("Owerri"),
	);
}


function location_cities_list_ng_ek () {
	return array (
		"2352379" => t("Ado-Ekiti"),
		"2349529" => t("Araomoko Ekiti"),
		"2343299" => t("Emure-Ekiti"),
		"2338810" => t("Igbara-Odo"),
		"2338630" => t("Igede-Ekiti"),
		"2338385" => t("Ijero-Ekiti"),
		"2338287" => t("Ikerre"),
		"2337352" => t("Ipoti"),
		"2337207" => t("Ise-Ekiti"),
		"2327233" => t("Oke Ila"),
	);
}


function location_cities_list_ng_ko () {
	return array (
		"2351470" => t("Ajaokuta"),
		"2343943" => t("Egbe"),
		"2339156" => t("Idah"),
		"2337235" => t("Isanlu Itedoijowa"),
		"2335843" => t("Kabba"),
		"2331939" => t("Lokoja"),
		"2327827" => t("Ogaminan"),
	);
}


function location_cities_list_ng_en () {
	return array (
		"2350886" => t("Aku"),
		"2348783" => t("Awgu"),
		"2343822" => t("Eha Amufu"),
		"2343279" => t("Enugu"),
		"2343273" => t("Enugu-Ezike"),
		"2328684" => t("Nsukka"),
	);
}


function location_cities_list_ng_bo () {
	return array (
		"2347954" => t("Bama"),
		"2346995" => t("Biu"),
		"2345498" => t("Damboa"),
		"2344854" => t("Dikwa"),
		"2342192" => t("Gambaru"),
		"2339665" => t("Gwoza"),
		"2333563" => t("Kukawa"),
		"2331528" => t("Magumeri"),
		"2331447" => t("Maiduguri"),
		"2330719" => t("Marte"),
		"2329946" => t("Mongonu"),
	);
}


function location_cities_list_ng_kt () {
	return array (
		"2345094" => t("Daura"),
		"2342490" => t("Funtua"),
		"2334802" => t("Katsina"),
		"2331005" => t("Malumfashi"),
	);
}


function location_cities_list_ng_la () {
	return array (
		"2348395" => t("Badagry"),
		"2344082" => t("Ebute Ikorodu"),
		"2343252" => t("Epe"),
		"2338313" => t("Ikeja"),
		"2332459" => t("Lagos"),
		"2331158" => t("Makoko"),
	);
}


function location_cities_list_ng_fc () {
	return array (
		"2352778" => t("Abuja"),
		"2333604" => t("Kuje"),
	);
}


function location_cities_list_ng_ji () {
	return array (
		"2347057" => t("Birnin Kudu"),
		"2344245" => t("Dutse"),
		"2340091" => t("Gumel"),
		"2339786" => t("Gwaram"),
		"2339631" => t("Hadejia"),
		"2334306" => t("Kiyawa"),
	);
}


function location_cities_list_ng_ba () {
	return array (
		"2348595" => t("Azare"),
		"2347470" => t("Bauchi"),
		"2345152" => t("Darazo"),
		"2335015" => t("Kari"),
	);
}


function location_cities_list_ng_eb () {
	return array (
		"2353099" => t("Abakaliki"),
		"2352250" => t("Afikpo"),
		"2343985" => t("Effium"),
		"2342883" => t("Ezza Ohu"),
		"2337148" => t("Isieke"),
	);
}


