<?php

function location_cities_list_kw_fa () {
	return array (
		"285815" => t("Al Farwaniyah"),
		"285603" => t("Janub as Surrah"),
	);
}


function location_cities_list_kw_ha () {
	return array (
		"285726" => t("Ar Rumaythiyah"),
		"285704" => t("As Salimiyah"),
		"285629" => t("Hawalli"),
		"387958" => t("Salwa"),
	);
}


function location_cities_list_kw_ah () {
	return array (
		"285839" => t("Al Ahmadi"),
		"285811" => t("Al Fahahil"),
		"285812" => t("Al Fintas"),
		"285782" => t("Al Mahbulah"),
		"285778" => t("Al Manqaf"),
		"285728" => t("Ar Riqqah"),
	);
}


function location_cities_list_kw_ku () {
	return array (
		"285856" => t("Ad Dasmah"),
		"388065" => t("Ar Rabiyah"),
		"285787" => t("Kuwait City"),
	);
}


function location_cities_list_kw_ja () {
	return array (
		"285799" => t("Al Jahra'"),
	);
}


function location_cities_list_kw_mu () {
	return array (
		"412800" => t("Sabah as Salim"),
	);
}


