<?php


function location_cities_list_bj_al() {
  return array(
    "2393693" => "Kandi",
    "2395317" => "Banikoara",
  );
}


function location_cities_list_bj_ak() {
  return array(
    "2391455" => "Tanguieta",
    "2392601" => "Natitingou",
    "2392837" => "Malanville",
  );
}


function location_cities_list_bj_aq() {
  return array(
    "2392308" => "Ouidah",
    "2395635" => "Allada",
    "2395914" => "Abomey-Calavi",
  );
}


function location_cities_list_bj_bo() {
  return array(
    "2391377" => "Tchaourou",
    "2392204" => "Parakou",
    "2392505" => "Nikki",
    "2395182" => "Bembereke",
  );
}


function location_cities_list_bj_co() {
  return array(
    "2391893" => "Save",
    "2391895" => "Savalou",
    "2394711" => "Dassa-Zoume",
  );
}


function location_cities_list_bj_do() {
  return array(
    "2394560" => "Djougou",
    "2395261" => "Bassila",
  );
}


function location_cities_list_bj_ou() {
  return array(
    "2392087" => "Porto-Novo",
  );
}


function location_cities_list_bj_ko() {
  return array(
    "2394545" => "Dogbo",
    "2395568" => "Aplahoue",
  );
}


function location_cities_list_bj_li() {
  return array(
    "2394819" => "Cotonou",
  );
}


function location_cities_list_bj_mo() {
  return array(
    "2392897" => "Lokossa",
    "2394824" => "Come",
  );
}


function location_cities_list_bj_pl() {
  return array(
    "2392009" => "Sakete",
    "2392108" => "Pobe",
    "2393551" => "Ketou",
  );
}


function location_cities_list_bj_zo() {
  return array(
    "2394814" => "Cove",
    "2395049" => "Bohicon",
    "2395915" => "Abomey",
  );
}
