<?php

function location_cities_list_rs_vo () {
	return array (
		"3204793" => t("Apatin"),
		"3204674" => t("Backa Palanka"),
		"3204672" => t("Backa Topola"),
		"792814" => t("Becej"),
		"790015" => t("Ingija"),
		"789518" => t("Kikinda"),
		"3194360" => t("Novi Sad"),
		"787237" => t("Pancevo"),
		"3191429" => t("Ruma"),
		"785965" => t("Senta"),
		"3190342" => t("Sombor"),
		"3190103" => t("Sremska Mitrovica"),
		"785559" => t("Stara Pazova"),
		"3189595" => t("Subotica"),
		"3187297" => t("Vrbas"),
		"784136" => t("Vrsac"),
		"783814" => t("Zrenjanin"),
	);
}


