<?php


function location_cities_list_il_m() {
  return array(
    "293207"  => "Yehud",
    "293222"  => "Yavne",
    "293690"  => "Rosh Ha'Ayin",
    "293703"  => "Rishon LeZiyyon",
    "293768"  => "Ramla",
    "293807"  => "Ra'anana",
    "293896"  => "Qalansuwa",
    "294071"  => "Netanya",
    "294074"  => "Ness Ziona",
    "294421"  => "Lod",
    "294514"  => "Kfar Saba",
    "294604"  => "Kafr Qasim",
    "294760"  => "Hod HaSharon",
    "295127"  => "Tirah",
    "295130"  => "Et Taiyiba",
    "6693674" => "Petah Tikva",
    "6693679" => "Modiin",
  );
}


function location_cities_list_il_ha() {
  return array(
    "293286" => "Umm el Fahm",
    "293308" => "Tirat Karmel",
    "293822" => "Qiryat Yam",
    "293831" => "Qiryat Motzkin",
    "293844" => "Qiryat Bialik",
    "293845" => "Qiryat Ata",
    "294078" => "Nesher",
    "294801" => "Haifa",
    "294946" => "Hadera",
    "295365" => "Daliyat el Karmil",
  );
}


function location_cities_list_il_jm() {
  return array(
    "281184"  => "Jerusalem",
    "294244"  => "Mevo Betar",
    "295432"  => "Bet Shemesh",
    "6945291" => "Old City",
    "7498240" => "West Jerusalem",
  );
}


function location_cities_list_il_z() {
  return array(
    "293100" => "Zefat",
    "293322" => "Tiberias",
    "293420" => "maalot Tarshiha",
    "293426" => "Tamra",
    "293655" => "Sakhnin",
    "293825" => "Qiryat Shemona",
    "294098" => "Nazareth",
    "294117" => "Nahariyya",
    "294210" => "Migdal Ha`Emeq",
    "294387" => "Maghar",
    "294577" => "Karmi'el",
    "294608" => "Kafr Manda",
    "294610" => "Kafr Kanna",
    "294622" => "Judieda Makr",
    "295174" => "Er Reina",
    "295435" => "Bet She'an",
    "295721" => "`Akko",
    "295739" => "`Afula `Illit",
  );
}


function location_cities_list_il_d() {
  return array(
    "293619" => "Sederot",
    "293842" => "Qiryat Gat",
    "293992" => "Ofaqim",
    "294068" => "Netivot",
    "295277" => "Eilat",
    "295328" => "Dimona",
    "295530" => "Beersheba",
    "295620" => "Ashqelon",
    "295629" => "Ashdod",
    "295657" => "'Arad",
  );
}


function location_cities_list_il_ta() {
  return array(
    "293253" => "Yafo",
    "293397" => "Tel Aviv",
    "293783" => "Ramat HaSharon",
    "293788" => "Ramat Gan",
    "293962" => "Or Yehuda",
    "294751" => "Holon",
    "294778" => "Herzliyya",
    "294981" => "Giv`at Shemu'el",
    "294999" => "Giv`atayim",
    "295514" => "Bene Beraq",
    "295548" => "Bat Yam",
  );
}
