<?php


function location_cities_list_kr_26 () {
	return array (
		"1838524" => t("Busan"),
		"1842966" => t("Kijang"),
	);
}


function location_cities_list_kr_27 () {
	return array (
		"1835329" => t("Daegu"),
		"1925943" => t("Hwawon"),
	);
}


function location_cities_list_kr_30 () {
	return array (
		"1835235" => t("Daejeon"),
	);
}


function location_cities_list_kr_42 () {
	return array (
		"1832257" => t("Neietsu"),
		"1832909" => t("Yanggu"),
		"1833105" => t("Wonju"),
		"1835515" => t("T'aebaek"),
		"1836553" => t("Sogcho"),
		"1838069" => t("Santyoku"),
		"1840179" => t("Kosong"),
		"1843137" => t("Kang-neung"),
		"1844045" => t("Hwacheon"),
		"1844191" => t("Hongch'on"),
		"1845136" => t("Chuncheon"),
		"1892823" => t("Tonghae"),
	);
}


function location_cities_list_kr_29 () {
	return array (
		"1841811" => t("Gwangju"),
	);
}


function location_cities_list_kr_41 () {
	return array (
		"1832743" => t("Yeoju"),
		"1832830" => t("Yangp'yong"),
		"1832847" => t("Yangju"),
		"1833788" => t("Vijongbu"),
		"1835553" => t("Suigen"),
		"1838716" => t("Bucheon"),
		"1839652" => t("Osan"),
		"1840862" => t("Munsan"),
		"1841810" => t("Kwangju"),
		"1841988" => t("Kuri"),
		"1842485" => t("Goyang"),
		"1843082" => t("Gapyeong"),
		"1843702" => t("Ich'on"),
		"1843847" => t("Hwaseong"),
		"1846898" => t("Anyang"),
		"1846912" => t("Anseong"),
		"1846918" => t("Ansan"),
		"1896953" => t("Pubal"),
		"1897000" => t("Seongnam"),
		"1897007" => t("Hanam"),
		"1897118" => t("Hwado"),
		"1897122" => t("Yanggok"),
		"1912209" => t("Wabu"),
		"1948005" => t("Kwangmyong"),
	);
}


function location_cities_list_kr_28 () {
	return array (
		"1843163" => t("Ganghwa"),
		"1843564" => t("Incheon"),
	);
}


function location_cities_list_kr_49 () {
	return array (
		"1846266" => t("Jeju"),
		"1847050" => t("Gaigeturi"),
	);
}


function location_cities_list_kr_43 () {
	return array (
		"1832566" => t("Yong-dong"),
		"1839873" => t("Okcheon"),
		"1842800" => t("Koesan"),
		"1845604" => t("Cheongju"),
		"1846095" => t("Chinch'on"),
	);
}


function location_cities_list_kr_47 () {
	return array (
		"1832015" => t("Heung-hai"),
		"1832215" => t("Enjitsu"),
		"1832384" => t("Eisen"),
		"1832617" => t("Eisen"),
		"1833514" => t("Waegwan"),
		"1835967" => t("Jenzan"),
		"1837706" => t("Sangju"),
		"1839071" => t("Pohang"),
		"1840886" => t("Mungyeong"),
		"1841598" => t("Keizan"),
		"1841603" => t("Kyonju"),
		"1842016" => t("Kunwi"),
		"1842225" => t("Gumi"),
		"1842944" => t("Gimcheon"),
		"1844308" => t("Hayang"),
		"1845519" => t("Cheongsong gun"),
		"1846986" => t("Andong"),
	);
}


function location_cities_list_kr_45 () {
	return array (
		"1833466" => t("Wanju"),
		"1838722" => t("Puan"),
		"1840379" => t("Nangen"),
		"1842025" => t("Kunsan"),
		"1842859" => t("Koch'ang"),
		"1842939" => t("Kimje"),
		"1843491" => t("Iksan"),
		"1843585" => t("Imsil"),
		"1845457" => t("Jeonju"),
		"1846114" => t("jin-angun"),
		"1846355" => t("Changsu"),
	);
}


function location_cities_list_kr_22 () {
	return array (
	);
}


function location_cities_list_kr_11 () {
	return array (
		"1835848" => t("Seoul"),
	);
}


function location_cities_list_kr_44 () {
	return array (
		"1832771" => t("Yesan"),
		"1834885" => t("Tangjin"),
		"1835096" => t("Taesal-li"),
		"1835447" => t("Taisen-ri"),
		"1835895" => t("Suisan"),
		"1836208" => t("Songwon"),
		"1838508" => t("Fuyo"),
		"1839726" => t("Asan"),
		"1840211" => t("Nonsan"),
		"1842153" => t("Kinzan"),
		"1842616" => t("Kongju"),
		"1844174" => t("Hongsung"),
		"1845759" => t("Tenan"),
		"1886598" => t("Yonmu"),
	);
}


function location_cities_list_kr_48 () {
	return array (
		"1832828" => t("Yangsan"),
		"1841149" => t("Miryang"),
		"1841245" => t("Masan"),
		"1842518" => t("Goseong"),
		"1842754" => t("Kyosai"),
		"1842943" => t("Kimhae"),
		"1846052" => t("Chinju"),
		"1846069" => t("Chinhae"),
		"1846326" => t("Changwon"),
		"1882056" => t("Sinhyeon"),
		"1912205" => t("Ungsang"),
		"1925936" => t("Naeso"),
		"6903078" => t("Changnyeong"),
	);
}


function location_cities_list_kr_46 () {
	return array (
		"1832501" => t("Reiko"),
		"1835648" => t("Suncheon"),
		"1839011" => t("Beolgyo"),
		"1840536" => t("Naju"),
		"1840982" => t("Muan"),
		"1841066" => t("Moppo"),
		"1841775" => t("Kwangyang"),
		"1841976" => t("Kurye"),
		"1843841" => t("Hwasun"),
		"1844751" => t("Haenam"),
		"1884138" => t("Yeosu"),
		"6395804" => t("Sinan"),
	);
}


function location_cities_list_kr_31 () {
	return array (
		"1833747" => t("Ulsan"),
	);
}
