<?php


function location_cities_list_gr_i() {
  return array(
    "251780"  => "Voula",
    "251948"  => "Vyronas",
    "254144"  => "Salamis",
    "255274"  => "Piraeus",
    "255377"  => "Petroupolis",
    "255524"  => "Peristeri",
    "255588"  => "Perama",
    "256075"  => "Palaio Faliro",
    "256429"  => "Nikaia",
    "256575"  => "Nea Smyrni",
    "256601"  => "Ilion",
    "256614"  => "Nea Ionia",
    "256621"  => "Nea Filadelfeia",
    "256622"  => "Nea Erythraia",
    "256750"  => "Moskhaton",
    "257302"  => "Melissia",
    "257365"  => "Megara",
    "259251"  => "Koropi",
    "259824"  => "Kifisia",
    "259949"  => "Cholargos",
    "260172"  => "Khalandrion",
    "260204"  => "Keratsini",
    "261414"  => "Kallithea",
    "261614"  => "Alimos",
    "261678"  => "Kaisariani",
    "261743"  => "Irakleio",
    "262135"  => "Galatsi",
    "262719"  => "Elliniko",
    "262752"  => "Elefsina",
    "264111"  => "Agia Varvara",
    "264194"  => "Agia Paraskevi",
    "264371"  => "Athens",
    "264445"  => "Aspropyrgos",
    "264888"  => "Ano Liosia",
    "265243"  => "Marousi",
    "265488"  => "Acharnes",
    "265533"  => "Aigaleo",
    "6324534" => "Vrilissia",
    "7522530" => "Marousi",
  );
}


function location_cities_list_gr_h() {
  return array(
    "252910" => "Thivai",
    "258463" => "Livadeia",
    "258620" => "Lamia",
    "260133" => "Chalkida",
  );
}


function location_cities_list_gr_b() {
  return array(
    "733776" => "Giannitsa",
    "733905" => "Veroia",
    "734077" => "Thessaloniki",
    "734301" => "Sykies",
    "734330" => "Serres",
    "734538" => "Polichni",
    "734643" => "Pylaia",
    "734712" => "Peraia",
    "734771" => "Panorama",
    "734883" => "Oraiokastro",
    "735030" => "Naousa",
    "735215" => "Menemeni",
    "735736" => "Kilkis",
    "735914" => "Katerini",
    "736083" => "Kalamaria",
    "736357" => "Edessa",
  );
}


function location_cities_list_gr_m() {
  return array(
    "254352" => "Rethymno",
    "260114" => "Chania",
    "261745" => "Irakleion",
  );
}


function location_cities_list_gr_a() {
  return array(
    "733840" => "Xanthi",
    "734880" => "Orestiada",
    "735640" => "Komotini",
    "735861" => "Kavala",
    "736364" => "Drama",
    "736928" => "Alexandroupoli",
  );
}


function location_cities_list_gr_d() {
  return array(
    "254698" => "Preveza",
    "261779" => "Ioannina",
    "264559" => "Arta",
  );
}


function location_cities_list_gr_f() {
  return array(
    "2463679" => "Kerkyra",
  );
}


function location_cities_list_gr_69() {
  return array();
}


function location_cities_list_gr_k() {
  return array(
    "256866" => "Mytilini",
    "259973" => "Chios",
  );
}


function location_cities_list_gr_j() {
  return array(
    "252601" => "Tripoli",
    "253394" => "Sparti",
    "259289" => "Korinthos",
    "261604" => "Kalamata",
    "264670" => "Argos",
  );
}


function location_cities_list_gr_l() {
  return array(
    "259245" => "Kos",
    "400666" => "Rodos",
  );
}


function location_cities_list_gr_e() {
  return array(
    "251833" => "Volos",
    "252664" => "Trikala",
    "258576" => "Larisa",
    "260989" => "Karditsa",
  );
}


function location_cities_list_gr_g() {
  return array(
    "255229" => "Pyrgos",
    "255683" => "Patra",
    "256639" => "Nafpaktos",
    "265252" => "Amaliada",
    "265500" => "Aigio",
    "265560" => "Agrinio",
  );
}


function location_cities_list_gr_c() {
  return array(
    "734426" => "Ptolemaida",
    "735563" => "Kozani",
    "736229" => "Florina",
  );
}
