<?php


function location_cities_list_ro_ar() {
  return array(
    "686254" => "Arad",
  );
}


function location_cities_list_ro_bh() {
  return array(
    "668129" => "Salonta",
    "671768" => "Oradea",
  );
}


function location_cities_list_ro_b() {
  return array(
    "683506" => "Bucharest",
  );
}


function location_cities_list_ro_cv() {
  return array(
    "665000" => "Targu Secuiesc",
    "667303" => "Sfantu-Gheorghe",
  );
}


function location_cities_list_ro_dj() {
  return array(
    "678261" => "Filiasi",
    "680332" => "Craiova",
    "683034" => "Calafat",
    "685785" => "Bailesti",
  );
}


function location_cities_list_ro_gr() {
  return array(
    "677106" => "Giurgiu",
  );
}


function location_cities_list_ro_gj() {
  return array(
    "665010" => "Targu Jiu",
    "672757" => "Motru",
  );
}


function location_cities_list_ro_hr() {
  return array(
    "671964" => "Odorheiu Secuiesc",
    "673441" => "Miercurea-Ciuc",
    "677458" => "Gheorgheni",
  );
}


function location_cities_list_ro_hd() {
  return array(
    "670938" => "Petrosani",
    "670969" => "Petrila",
    "671757" => "Orastie",
    "675918" => "Hunedoara",
    "679452" => "Deva",
    "683974" => "Brad",
  );
}


function location_cities_list_ro_if() {
  return array(
    "662476" => "Voluntari",
    "669870" => "Popesti-Leordeni",
    "671382" => "Pantelimon",
    "683394" => "Buftea",
  );
}


function location_cities_list_ro_ab() {
  return array(
    "667526" => "Sebes",
    "672024" => "Ocna Mures",
    "679995" => "Cugir",
    "684612" => "Blaj",
    "686578" => "Alba Iulia",
    "686590" => "Aiud",
  );
}


function location_cities_list_ro_ag() {
  return array(
    "670609"  => "Pitesti",
    "679907"  => "Curtea de Arges",
    "7733099" => "Mioveni",
  );
}


function location_cities_list_ro_bc() {
  return array(
    "672926" => "Moinesti",
    "681017" => "Comanesti",
    "683365" => "Buhusi",
    "685948" => "Bacau",
  );
}


function location_cities_list_ro_bn() {
  return array(
    "684657" => "Bistrita",
  );
}


function location_cities_list_ro_bt() {
  return array(
    "679065" => "Dorohoi",
    "684039" => "Botosani",
  );
}


function location_cities_list_ro_bv() {
  return array(
    "662284" => "Zarnesti",
    "668314" => "Sacele",
    "668828" => "Rasnov",
    "683844" => "Brasov",
  );
}


function location_cities_list_ro_br() {
  return array(
    "683902" => "Braila",
  );
}


function location_cities_list_ro_bz() {
  return array(
    "668873" => "Ramnicu Sarat",
    "683123" => "Buzau",
  );
}


function location_cities_list_ro_cs() {
  return array(
    "668954" => "Resita",
    "682729" => "Caransebes",
    "684490" => "Bocsa",
  );
}


function location_cities_list_ro_cj() {
  return array(
    "664460" => "Turda",
    "677429" => "Gherla",
    "679550" => "Dej",
    "681290" => "Cluj-Napoca",
    "681865" => "Campia Turzii",
  );
}


function location_cities_list_ro_ct() {
  return array(
    "672486" => "Navodari",
    "673636" => "Medgidia",
    "673921" => "Mangalia",
    "680963" => "Constanta",
    "682321" => "Cernavoda",
  );
}


function location_cities_list_ro_cl() {
  return array(
    "671832" => "Oltenita",
  );
}


function location_cities_list_ro_db() {
  return array(
    "665024" => "Targoviste",
    "672862" => "Moreni",
    "677742" => "Gaesti",
  );
}


function location_cities_list_ro_gl() {
  return array(
    "665355" => "Tecuci",
    "677697" => "Galati",
  );
}


function location_cities_list_ro_il() {
  return array(
    "664074"  => "Urziceni",
    "678301"  => "Fetesti-Gara",
    "678306"  => "Fetesti",
    "8581467" => "Slobozia",
  );
}


function location_cities_list_ro_is() {
  return array(
    "675810"  => "Iasi",
    "6945426" => "Pascani",
  );
}


function location_cities_list_ro_mh() {
  return array(
    "678817" => "Drobeta-Turnu Severin",
  );
}


function location_cities_list_ro_ms() {
  return array(
    "664963"  => "Tarnaveni",
    "665004"  => "Targu-Mures",
    "674541"  => "Ludus",
    "8436351" => "Sighisoara",
  );
}


function location_cities_list_ro_nt() {
  return array(
    "665003" => "Targu Neamt",
    "668732" => "Roman",
    "670889" => "Piatra Neamt",
  );
}


function location_cities_list_ro_sb() {
  return array(
    "667268" => "Sibiu",
    "673634" => "Medias",
    "681502" => "Cisnadie",
  );
}


function location_cities_list_ro_sj() {
  return array(
    "662334" => "Zalau",
    "667101" => "Simleu Silvaniei",
  );
}


function location_cities_list_ro_tm() {
  return array(
    "665087" => "Timisoara",
    "674531" => "Lugoj",
  );
}


function location_cities_list_ro_vl() {
  return array(
    "668872" => "Ramnicu Valcea",
    "678978" => "Dragasani",
  );
}


function location_cities_list_ro_mm() {
  return array(
    "667227" => "Sighetu Marmatiei",
    "684156" => "Borsa",
    "685823" => "Baia Sprie",
    "685826" => "Baia Mare",
  );
}


function location_cities_list_ro_ot() {
  return array(
    "666767" => "Slatina",
    "680897" => "Corabia",
    "682747" => "Caracal",
    "685586" => "Bals",
  );
}


function location_cities_list_ro_ph() {
  return array(
    "670474" => "Ploiesti",
    "673033" => "Mizil",
    "681862" => "Campina",
    "683760" => "Breaza",
    "685811" => "Baicoi",
  );
}


function location_cities_list_ro_sm() {
  return array(
    "667873"  => "Satu Mare",
    "682685"  => "Carei",
    "6697993" => "Baia Mare",
  );
}


function location_cities_list_ro_sv() {
  return array(
    "663100" => "Vatra Dornei",
    "665850" => "Suceava",
    "669289" => "Radauti",
    "676527" => "Gura Humorului",
    "678459" => "Falticeni",
    "681845" => "Campulung Moldovenesc",
  );
}


function location_cities_list_ro_tr() {
  return array(
    "662187" => "Zimnicea",
    "664437" => "Turnu Magurele",
    "686502" => "Alexandria",
  );
}


function location_cities_list_ro_tl() {
  return array(
    "664518" => "Tulcea",
  );
}


function location_cities_list_ro_vs() {
  return array(
    "663118" => "Vaslui",
    "675892" => "Husi",
    "684802" => "Barlad",
  );
}


function location_cities_list_ro_vn() {
  return array(
    "678015" => "Focsani",
  );
}
