<?php


function location_cities_list_md_ca() {
  return array(
    "618456" => "Cahul",
  );
}


function location_cities_list_md_dr() {
  return array(
    "618370" => "Drochia",
  );
}


function location_cities_list_md_ga() {
  return array(
    "618405" => "Comrat",
    "618450" => "Ceadir-Lunga",
  );
}


function location_cities_list_md_bd() {
  return array(
    "618577" => "Bender",
  );
}


function location_cities_list_md_ba() {
  return array(
    "618605" => "Balti",
  );
}


function location_cities_list_md_cu() {
  return array(
    "618426" => "Chisinau",
  );
}


function location_cities_list_md_an() {
  return array();
}


function location_cities_list_md_bs() {
  return array();
}


function location_cities_list_md_br() {
  return array();
}


function location_cities_list_md_ct() {
  return array();
}


function location_cities_list_md_cm() {
  return array();
}


function location_cities_list_md_cr() {
  return array();
}


function location_cities_list_md_cl() {
  return array();
}


function location_cities_list_md_cs() {
  return array(
    "618120" => "Causeni",
  );
}


function location_cities_list_md_do() {
  return array();
}


function location_cities_list_md_du() {
  return array();
}


function location_cities_list_md_ed() {
  return array(
    "617076" => "Edinet",
  );
}


function location_cities_list_md_fl() {
  return array(
    "618329" => "Floresti",
  );
}


function location_cities_list_md_fa() {
  return array();
}


function location_cities_list_md_gl() {
  return array();
}


function location_cities_list_md_hi() {
  return array(
    "617993" => "Hincesti",
  );
}


function location_cities_list_md_ia() {
  return array();
}


function location_cities_list_md_le() {
  return array();
}


function location_cities_list_md_ni() {
  return array();
}


function location_cities_list_md_oc() {
  return array();
}


function location_cities_list_md_or() {
  return array(
    "617638" => "Orhei",
  );
}


function location_cities_list_md_re() {
  return array();
}


function location_cities_list_md_ri() {
  return array();
}


function location_cities_list_md_so() {
  return array(
    "617367" => "Soroca",
  );
}


function location_cities_list_md_si() {
  return array(
    "617345" => "Bilicenii Vechi",
  );
}


function location_cities_list_md_ta() {
  return array();
}


function location_cities_list_md_te() {
  return array();
}


function location_cities_list_md_sd() {
  return array();
}


function location_cities_list_md_sv() {
  return array();
}


function location_cities_list_md_st() {
  return array(
    "617302" => "Straseni",
  );
}


function location_cities_list_md_un() {
  return array(
    "617180" => "Ungheni",
  );
}


function location_cities_list_md_sn() {
  return array(
    "617239" => "Tiraspol",
    "617381" => "Slobozia",
    "617486" => "Ribnita",
    "618365" => "Dubasari",
  );
}
