<?php


function location_cities_list_fi_035() {
  return array();
}


function location_cities_list_fi_is() {
  return array(
    "632370" => t("Varkaus"),
    "636947" => t("Siilinjarvi"),
    "637292" => t("Savonlinna"),
    "646005" => t("Mikkeli"),
    "650224" => t("Kuopio"),
    "655808" => t("Joensuu"),
    "656820" => t("Iisalmi"),
  );
}


function location_cities_list_fi_043() {
  return array();
}


function location_cities_list_fi_060() {
  return array();
}


function location_cities_list_fi_062() {
  return array();
}


function location_cities_list_fi_065() {
  return array();
}


function location_cities_list_fi_076() {
  return array();
}


function location_cities_list_fi_170() {
  return array();
}


function location_cities_list_fi_295() {
  return array();
}


function location_cities_list_fi_318() {
  return array();
}


function location_cities_list_fi_ll() {
  return array(
    "634093" => t("Tornio"),
    "638936" => t("Rovaniemi"),
    "653281" => t("Kemi"),
  );
}


function location_cities_list_fi_417() {
  return array();
}


function location_cities_list_fi_438() {
  return array();
}


function location_cities_list_fi_478() {
  return array(
    "3041732" => t("Mariehamn"),
  );
}


function location_cities_list_fi_ol() {
  return array(
    "640276" => t("Raahe"),
    "643492" => t("Oulu"),
    "649924" => t("Kuusamo"),
    "654899" => t("Kajaani"),
    "658629" => t("Haukipudas"),
  );
}


function location_cities_list_fi_12() {
  return array(
    "630752"  => t("Ylojarvi"),
    "632672"  => t("Valkeakoski"),
    "632978"  => t("Vaasa"),
    "633221"  => t("Uusikaupunki"),
    "633679"  => t("Turku"),
    "634963"  => t("Tampere"),
    "637219"  => t("Seinaejoki"),
    "637948"  => t("Salo"),
    "639734"  => t("Rauma"),
    "640124"  => t("Raisio"),
    "640999"  => t("Pori"),
    "641489"  => t("Pirkkala"),
    "644450"  => t("Nokia"),
    "648056"  => t("Lieto"),
    "648366"  => t("Lempaala"),
    "648738"  => t("Laukaa"),
    "651299"  => t("Korsholm"),
    "651943"  => t("Karleby"),
    "654440"  => t("Kangasala"),
    "655130"  => t("Kaarina"),
    "655194"  => t("Jyvaeskylae"),
    "656083"  => t("Jamsa"),
    "656130"  => t("Jakobstad"),
    "7911309" => t("Laensi-Turunmaa"),
  );
}


function location_cities_list_fi_736() {
  return array();
}


function location_cities_list_fi_766() {
  return array();
}


function location_cities_list_fi_es() {
  return array(
    "631707" => t("Vihti"),
    "632453" => t("Vantaa"),
    "633591" => t("Tuusula"),
    "637067" => t("Sibbo"),
    "639406" => t("Riihimaki"),
    "644171" => t("Nurmijarvi"),
    "646723" => t("Mantsala"),
    "647751" => t("Lohja"),
    "648900" => t("Lappeenranta"),
    "649360" => t("Lahti"),
    "649630" => t("Kirkkonummi"),
    "649919" => t("Kuusankoski"),
    "650859" => t("Kouvola"),
    "650946" => t("Kotka"),
    "653185" => t("Kerava"),
    "654137" => t("Karhula"),
    "655958" => t("Jarvenpaa"),
    "656073" => t("Janakkala"),
    "656688" => t("Imatra"),
    "656913" => t("Hyvinkaa"),
    "657530" => t("Hollola"),
    "658225" => t("Helsinki"),
    "658288" => t("Heinola"),
    "659169" => t("Hamina"),
    "659180" => t("Hameenlinna"),
    "659935" => t("Forssa"),
    "660158" => t("Espoo"),
    "660561" => t("Porvoo"),
    "661164" => t("Anjala"),
  );
}


function location_cities_list_fi_771() {
  return array();
}


function location_cities_list_fi_941() {
  return array();
}
