<?php

function location_cities_list_gm_m () {
	return array (
	);
}


function location_cities_list_gm_b () {
	return array (
		"2413876" => t("Banjul"),
		"2413920" => t("Bakau"),
	);
}


function location_cities_list_gm_l () {
	return array (
	);
}


function location_cities_list_gm_n () {
	return array (
		"2412749" => t("Lamin"),
		"2413515" => t("Farafenni"),
	);
}


function location_cities_list_gm_u () {
	return array (
	);
}


function location_cities_list_gm_w () {
	return array (
		"2411880" => t("Sukuta"),
		"2413753" => t("Brikama"),
	);
}
