<?php

function location_cities_list_zm_04 () {
	return array (
		"176555" => t("Kawambwa"),
		"907770" => t("Mansa"),
		"175499" => t("Nchelenge"),
		"899274" => t("Samfya"),
	);
}


function location_cities_list_zm_05 () {
	return array (
		"912764" => t("Kasama"),
		"176146" => t("Mbala"),
		"905846" => t("Mpika"),
	);
}


function location_cities_list_zm_07 () {
	return array (
		"917748" => t("Choma"),
		"910111" => t("Livingstone"),
		"907111" => t("Mazabuka"),
		"906044" => t("Monze"),
		"898188" => t("Siavonga"),
	);
}


function location_cities_list_zm_01 () {
	return array (
		"906054" => t("Mongu"),
		"898905" => t("Sesheke"),
	);
}


function location_cities_list_zm_03 () {
	return array (
		"918702" => t("Chipata"),
		"899825" => t("Petauke"),
	);
}


function location_cities_list_zm_08 () {
	return array (
		"919544" => t("Chililabombwe"),
		"919009" => t("Chingola"),
		"914959" => t("Kalulushi"),
		"911148" => t("Kitwe"),
		"909863" => t("Luanshya"),
		"905395" => t("Mufulira"),
		"901344" => t("Ndola"),
	);
}


function location_cities_list_zm_02 () {
	return array (
		"916095" => t("Kabwe"),
		"913029" => t("Kapiri Mposhi"),
		"904422" => t("Mumbwa"),
	);
}


function location_cities_list_zm_09 () {
	return array (
		"915883" => t("Kafue"),
		"909137" => t("Lusaka"),
	);
}


function location_cities_list_zm_06 () {
	return array (
		"913613" => t("Kansanshi"),
	);
}


