<?php


function location_cities_list_np_1() {
  return array(
    "1282931" => "Patan",
    "1282950" => "Panaoti",
    "1283082" => "Malangwa",
    "1283190" => "Kirtipur",
    "1283240" => "Kathmandu",
    "1283318" => "Janakpur",
    "1283323" => "Jaleswar",
    "1283339" => "Hitura",
    "1283401" => "Gaur",
    "1283581" => "Birganj",
    "1283613" => "Bharatpur",
    "1283679" => "Banepa",
  );
}


function location_cities_list_np_4() {
  return array(
    "1282770" => "Siraha",
    "1282884" => "Rajbiraj",
    "1283161" => "Lahan",
    "1283217" => "Khandbari",
    "1283329" => "Ithari",
    "1283333" => "Ilam",
    "1283460" => "Dharan Bazar",
    "1283465" => "Dhankuta",
    "1283582" => "Biratnagar",
    "1283628" => "Bhadrapur",
  );
}


function location_cities_list_np_5() {
  return array(
    "1282666" => "Tikapur",
    "1283095" => "Mahendranagar",
    "1283467" => "Dhangarhi",
    "1283499" => "Dadeldhura",
    "6254845" => "Dipayal",
  );
}


function location_cities_list_np_2() {
  return array(
    "1282635" => "Tulsipur",
    "1283368" => "Gulariya",
    "1283496" => "Dailekh",
    "6254843" => "Birendranagar",
    "6941099" => "Nepalgunj",
  );
}


function location_cities_list_np_3() {
  return array(
    "1282616" => "Waling",
    "1282714" => "Tansen",
    "1282898" => "Pokhara",
    "1283562" => "Butwal",
    "1283621" => "Bhairahawa",
    "1283711" => "Baglung",
  );
}
