<?php


function location_cities_list_ao_bgo() {
  return array(
    "2242001" => "Caxito",
  );
}


function location_cities_list_ao_bgu() {
  return array(
    "3347939" => "Lobito",
    "3350246" => "Catumbela",
    "3351663" => "Benguela",
  );
}


function location_cities_list_ao_cab() {
  return array(
    "2243271" => "Cabinda",
  );
}


function location_cities_list_ao_cno() {
  return array(
    "2239076" => "N'dalatando",
  );
}


function location_cities_list_ao_cnn() {
  return array();
}


function location_cities_list_ao_hua() {
  return array(
    "3347853" => "Longonjo",
    "3348313" => "Huambo",
    "3351500" => "Caala",
  );
}


function location_cities_list_ao_hui() {
  return array(
    "3347762" => "Lubango",
    "3351024" => "Caluquembe",
  );
}


function location_cities_list_ao_ccu() {
  return array(
    "3347353" => "Menongue",
  );
}


function location_cities_list_ao_cus() {
  return array(
    "3346015" => "Sumbe",
  );
}


function location_cities_list_ao_lua() {
  return array(
    "2240449" => "Luanda",
  );
}


function location_cities_list_ao_lno() {
  return array(
    "145724" => "Lucapa",
  );
}


function location_cities_list_ao_lsu() {
  return array(
    "145531" => "Saurimo",
  );
}


function location_cities_list_ao_mal() {
  return array(
    "2239862" => "Malanje",
  );
}


function location_cities_list_ao_mox() {
  return array(
    "876177"  => "Luau",
    "3347719" => "Luena",
  );
}


function location_cities_list_ao_nam() {
  return array(
    "3347019" => "Mocamedes",
  );
}


function location_cities_list_ao_bie() {
  return array(
    "3348078" => "Cuito",
    "3350372" => "Catabola",
    "3351014" => "Camacupa",
  );
}


function location_cities_list_ao_uig() {
  return array(
    "2236568" => "Uige",
  );
}


function location_cities_list_ao_zai() {
  return array(
    "2236967" => "Soio",
    "2239001" => "Nzeto",
    "2239520" => "Mbanza Congo",
  );
}
