<?php

function location_cities_list_bz_bz () {
	return array (
		"3582677" => t("Belize City"),
	);
}


function location_cities_list_bz_cy () {
	return array (
		"3581194" => t("San Ignacio"),
		"3582672" => t("Belmopan"),
	);
}


function location_cities_list_bz_czl () {
	return array (
	);
}


function location_cities_list_bz_ow () {
	return array (
		"3581514" => t("Orange Walk"),
	);
}


function location_cities_list_bz_sc () {
	return array (
	);
}


function location_cities_list_bz_tol () {
	return array (
	);
}
