<?php


function location_cities_list_ly_ju () {
	return array (
		"2209055" => t("Waddan"),
		"2216645" => t("Hun"),
	);
}


function location_cities_list_ly_kf () {
	return array (
		"88562" => t("At Taj"),
		"88930" => t("Al Kufrah"),
		"88962" => t("Al Jawf"),
	);
}


function location_cities_list_ly_mj () {
	return array (
		"88834" => t("Tukrah"),
		"88903" => t("Al Marj"),
	);
}


function location_cities_list_ly_mb () {
	return array (
		"2210221" => t("Tarhuna"),
		"2219905" => t("Al Khums"),
	);
}


function location_cities_list_ly_dr () {
	return array (
		"87205" => t("Darnah"),
	);
}


function location_cities_list_ly_mq () {
	return array (
		"2214603" => t("Murzuq"),
	);
}


function location_cities_list_ly_ba () {
	return array (
		"81604" => t("Suluq"),
		"88319" => t("Benghazi"),
	);
}


function location_cities_list_ly_gt () {
	return array (
		"2217351" => t("Ghat"),
	);
}


function location_cities_list_ly_mi () {
	return array (
		"2208485" => t("Zliten"),
		"2214846" => t("Misratah"),
	);
}


function location_cities_list_ly_nl () {
	return array (
		"2214433" => t("Nalut"),
	);
}


function location_cities_list_ly_sb () {
	return array (
		"2212775" => t("Sabha"),
		"2219960" => t("Al Jadid"),
	);
}


function location_cities_list_ly_wd () {
	return array (
		"2219235" => t("Awbari"),
	);
}


function location_cities_list_ly_ws () {
	return array (
		"2218478" => t("Birak"),
	);
}


function location_cities_list_ly_bu () {
	return array (
		"81302" => t("Tobruk"),
	);
}


function location_cities_list_ly_ja () {
	return array (
		"89055" => t("Al Bayda'"),
	);
}


function location_cities_list_ly_jg () {
	return array (
		"2208791" => t("Yafran"),
		"2217362" => t("Gharyan"),
		"2218963" => t("Az Zintan"),
	);
}


function location_cities_list_ly_ji () {
	return array (
	);
}


function location_cities_list_ly_wa () {
	return array (
		"88380" => t("Az Zuwaytinah"),
		"89113" => t("Ajdabiya"),
	);
}


function location_cities_list_ly_nq () {
	return array (
		"2208425" => t("Zuwarah"),
	);
}


function location_cities_list_ly_za () {
	return array (
		"2210560" => t("Surman"),
		"2212771" => t("Sabratah"),
		"2216885" => t("Zawiya"),
		"2218970" => t("Az Zawiyah"),
	);
}


function location_cities_list_ly_tb () {
	return array (
		"2210247" => t("Tripoli"),
		"2210394" => t("Tagiura"),
	);
}


function location_cities_list_ly_sr () {
	return array (
		"2210554" => t("Sirte"),
	);
}
