<?php

function location_cities_list_sl_w () {
	return array (
		"2409306" => t("Freetown"),
		"2403094" => t("Waterloo"),
	);
}


function location_cities_list_sl_e () {
	return array (
		"2407790" => t("Kenema"),
		"2407656" => t("Koidu"),
		"2404041" => t("Segbwema"),
	);
}


function location_cities_list_sl_n () {
	return array (
		"2408329" => t("Kabala"),
		"2406916" => t("Lunsar"),
		"2406407" => t("Makeni"),
		"2404433" => t("Port Loko"),
	);
}


function location_cities_list_sl_s () {
	return array (
		"2410048" => t("Bo"),
	);
}


