<?php


function location_cities_list_bg_01() {
  return array(
    "727447" => "Sandanski",
    "728288" => "Petrich",
    "731108" => "Gotse Delchev",
    "733191" => "Blagoevgrad",
  );
}


function location_cities_list_bg_02() {
  return array(
    "730559" => "Karnobat",
    "732770" => "Burgas",
    "733579" => "Aytos",
  );
}


function location_cities_list_bg_07() {
  return array(
    "727337" => "Sevlievo",
    "731549" => "Gabrovo",
  );
}


function location_cities_list_bg_11() {
  return array(
    "726320" => "Troyan",
    "729559" => "Lovech",
  );
}


function location_cities_list_bg_08() {
  return array(
    "726418" => "Dobrich",
  );
}


function location_cities_list_bg_26() {
  return array(
    "726546" => "Svilengrad",
    "730435" => "Haskovo",
    "730442" => "Kharmanli",
    "732263" => "Dimitrovgrad",
  );
}


function location_cities_list_bg_10() {
  return array(
    "726872" => "Dupnitsa",
    "729730" => "Kyustendil",
  );
}


function location_cities_list_bg_09() {
  return array(
    "729794" => "Kurdzhali",
  );
}


function location_cities_list_bg_12() {
  return array(
    "729114" => "Montana",
    "729581" => "Lom",
    "733264" => "Berkovitsa",
  );
}


function location_cities_list_bg_15() {
  return array(
    "728203" => "Pleven",
    "732491" => "Cherven Bryag",
  );
}


function location_cities_list_bg_17() {
  return array(
    "727696" => "Razgrad",
  );
}


function location_cities_list_bg_18() {
  return array(
    "727523" => "Ruse",
  );
}


function location_cities_list_bg_27() {
  return array(
    "727233" => "Shumen",
  );
}


function location_cities_list_bg_19() {
  return array(
    "727221" => "Silistra",
  );
}


function location_cities_list_bg_20() {
  return array(
    "727079" => "Sliven",
    "728742" => "Nova Zagora",
  );
}


function location_cities_list_bg_21() {
  return array(
    "727030" => "Smolyan",
  );
}


function location_cities_list_bg_24() {
  return array(
    "726848" => "Stara Zagora",
    "730496" => "Kazanluk",
    "732452" => "Chirpan",
  );
}


function location_cities_list_bg_25() {
  return array(
    "726174" => "Targovishte",
    "728075" => "Popovo",
  );
}


function location_cities_list_bg_04() {
  return array(
    "725993" => "Veliko Turnovo",
    "726534" => "Svishtov",
    "731233" => "Gorna Oryakhovitsa",
  );
}


function location_cities_list_bg_05() {
  return array(
    "725905" => "Vidin",
  );
}


function location_cities_list_bg_06() {
  return array(
    "725712" => "Vratsa",
  );
}


function location_cities_list_bg_28() {
  return array(
    "725578" => "Yambol",
  );
}


function location_cities_list_bg_13() {
  return array(
    "725988" => "Velingrad",
    "728317" => "Peshtera",
    "728378" => "Pazardzhik",
    "728448" => "Panagyurishte",
  );
}


function location_cities_list_bg_14() {
  return array(
    "728330" => "Pernik",
  );
}


function location_cities_list_bg_16() {
  return array(
    "727791" => "Rakovski",
    "728193" => "Plovdiv",
    "730565" => "Karlovo",
    "733618" => "Asenovgrad",
  );
}


function location_cities_list_bg_22() {
  return array(
    "727011" => "Sofia",
  );
}


function location_cities_list_bg_23() {
  return array(
    "727462" => "Samokov",
    "733014" => "Botevgrad",
  );
}


function location_cities_list_bg_03() {
  return array(
    "726050" => "Varna",
  );
}
