<?php

function location_cities_list_tj_7280679 () {
	return array (
		"1221874" => t("Dushanbe"),
	);
}


function location_cities_list_tj_gb () {
	return array (
		"1221328" => t("Khorugh"),
		"1221614" => t("Ishqoshim"),
	);
}


function location_cities_list_tj_rr () {
	return array (
		"1220855" => t("Vahdat"),
	);
}


function location_cities_list_tj_kt () {
	return array (
		"1220112" => t("Yovon"),
		"1220163" => t("Vose'"),
		"1220219" => t("Vakhsh"),
		"1220747" => t("Qurghonteppa"),
		"1220826" => t("Farkhor"),
		"1220905" => t("Norak"),
		"1221194" => t("Kulob"),
		"1221259" => t("Kolkhozobod"),
		"1221965" => t("Danghara"),
		"1221997" => t("Chubek"),
	);
}


function location_cities_list_tj_su () {
	return array (
		"1220253" => t("Istaravshan"),
		"1220798" => t("Panjakent"),
		"1514839" => t("Proletar"),
		"1514879" => t("Khujand"),
		"1514891" => t("Konibodom"),
		"1514896" => t("Isfara"),
		"1538311" => t("Chkalov"),
	);
}
