<?php


function location_cities_list_bm_ds() {
  return array();
}


function location_cities_list_bm_ha() {
  return array();
}


function location_cities_list_bm_hc() {
  return array(
    "3573197" => "Hamilton",
  );
}


function location_cities_list_bm_pg() {
  return array();
}


function location_cities_list_bm_pb() {
  return array();
}


function location_cities_list_bm_gc() {
  return array();
}


function location_cities_list_bm_sg() {
  return array();
}


function location_cities_list_bm_sa() {
  return array();
}


function location_cities_list_bm_sm() {
  return array();
}


function location_cities_list_bm_sh() {
  return array();
}


function location_cities_list_bm_wa() {
  return array();
}
