<?php

function location_cities_list_de_bb()
{
	return array(
		'2945354' => t('Kreisfreie Stadt Brandenburg an der Havel'),
		'2939810' => t('Kreisfreie Stadt Cottbus'),
		'2925534' => t('Kreisfreie Stadt Frankfurt'),
		'2852455' => t('Kreisfreie Stadt Potsdam'),
		'3249079' => t('Landkreis Barnim'),
		'3249080' => t('Landkreis Dahme-Spreewald'),
		'3249081' => t('Landkreis Elbe-Elster'),
		'3249082' => t('Landkreis Havelland'),
		'3249083' => t('Landkreis Märkisch-Oderland'),
		'3249084' => t('Landkreis Oberhavel'),
		'3249085' => t('Landkreis Oberspreewald-Lausitz'),
		'3249086' => t('Landkreis Oder-Spree'),
		'3249087' => t('Landkreis Ostprignitz-Ruppin'),
		'2852456' => t('Landkreis Potsdam-Mittelmark'),
		'3249088' => t('Landkreis Prignitz'),
		'3249089' => t('Landkreis Spree-Neiße'),
		'3249090' => t('Landkreis Teltow-Fläming'),
		'3249091' => t('Landkreis Uckermark'),
	);
}
function location_cities_list_de_bw()
{
	return array(
		'2925180' => t('Regierungsbezirk Freiburg'),
		'3214104' => t('Regierungsbezirk Karlsruhe'),
		'3214105' => t('Regierungsbezirk Stuttgart'),
		'3214106' => t('Regierungsbezirk Tübingen'),
	);
}
function location_cities_list_de_hb()
{
	return array(
		'3220905' => t('Kreisfreie Stadt Bremen'),
		'3220906' => t('Kreisfreie Stadt Bremerhaven'),
	);
}
function location_cities_list_de_hh()
{
	return array(
		'6547395' => t('Hamburg, Freie und Hansestadt'),
	);
}
function location_cities_list_de_mv()
{
	return array(
		'2917786' => t('Kreisfreie Stadt Greifswald'),
		'2866134' => t('Kreisfreie Stadt Neubrandenburg'),
		'2844587' => t('Kreisfreie Stadt Rostock'),
		'2834281' => t('Kreisfreie Stadt Schwerin'),
		'2826286' => t('Kreisfreie Stadt Stralsund'),
		'2807463' => t('Kreisfreie Stadt Wismar'),
		'2953526' => t('Landkreis Bad Doberan'),
		'2938283' => t('Landkreis Demmin'),
		'2913431' => t('Landkreis Güstrow'),
		'2875341' => t('Landkreis Ludwigslust'),
		'3302144' => t('Landkreis Mecklenburg-Strelitz'),
		'3302148' => t('Landkreis Müritz'),
		'3302145' => t('Landkreis Nordvorpommern'),
		'3302143' => t('Landkreis Nordwestmecklenburg'),
		'3302146' => t('Landkreis Ostvorpommern'),
		'2855440' => t('Landkreis Parchim'),
		'2843324' => t('Landkreis Rügen'),
		'3302147' => t('Landkreis Uecker-Randow'),
	);
}
function location_cities_list_de_rp()
{
	return array(
		'2936213' => t('Donnersbergkreis'),
		'2925546' => t('Kreisfreie Stadt Frankenthal'),
		'3247900' => t('Kreisfreie Stadt Kaiserslautern'),
		'3247459' => t('Kreisfreie Stadt Koblenz'),
		'3247905' => t('Kreisfreie Stadt Landau in der Pfalz'),
		'3247910' => t('Kreisfreie Stadt Ludwigshafen am Rhein'),
		'3247465' => t('Kreisfreie Stadt Mainz'),
		'3247906' => t('Kreisfreie Stadt Neustadt an der Weinstraße'),
		'3247903' => t('Kreisfreie Stadt Pirmasens'),
		'3247908' => t('Kreisfreie Stadt Speyer'),
		'3247911' => t('Kreisfreie Stadt Trier'),
		'3247467' => t('Kreisfreie Stadt Worms'),
		'3247902' => t('Kreisfreie Stadt Zweibrücken'),
		'3247460' => t('Landkreis Ahrweiler'),
		'3247456' => t('Landkreis Altenkirchen'),
		'2956708' => t('Landkreis Alzey-Worms'),
		'2953523' => t('Landkreis Bad Dürkheim'),
		'2953415' => t('Landkreis Bad Kreuznach'),
		'3247912' => t('Landkreis Bernkastel-Wittlich'),
		'2948589' => t('Landkreis Birkenfeld'),
		'3247913' => t('Landkreis Bitburg-Prüm'),
		'3247464' => t('Landkreis Cochem-Zell'),
		'3247914' => t('Landkreis Daun'),
		'3247907' => t('Landkreis Germersheim'),
		'2894002' => t('Landkreis Kaiserslautern'),
		'3247901' => t('Landkreis Kusel'),
		'3247466' => t('Landkreis Mainz-Bingen'),
		'3247461' => t('Landkreis Mayen-Koblenz'),
		'3247458' => t('Landkreis Neuwied'),
		'3247904' => t('Landkreis Pirmasens'),
		'2825001' => t('Landkreis Südliche Weinstraße'),
		'2821160' => t('Landkreis Trier-Saarburg'),
		'3247463' => t('Rhein-Hunsrück-Kreis'),
		'3247462' => t('Rhein-Lahn-Kreis'),
		'3247909' => t('Rhein-Pfalz-Kreis'),
		'3247457' => t('Westerwaldkreis'),
	);
}
function location_cities_list_de_sh()
{
	return array(
		'3249069' => t('Kreis Dithmarschen'),
		'2905434' => t('Kreis Herzogtum Lauenburg'),
		'3249073' => t('Kreis Nordfriesland'),
		'2853657' => t('Kreis Pinneberg'),
		'2853161' => t('Kreis Plön'),
		'3249075' => t('Kreis Rendsburg-Eckernförde'),
		'2838633' => t('Kreis Schleswig-Flensburg'),
		'3249076' => t('Kreis Segeberg'),
		'3249077' => t('Kreis Steinburg'),
		'3249078' => t('Kreis Stormarn'),
		'2926272' => t('Kreisfreie Stadt Flensburg'),
		'3249070' => t('Kreisfreie Stadt Kiel'),
		'3249071' => t('Kreisfreie Stadt Lübeck'),
		'3249072' => t('Kreisfreie Stadt Neumünster'),
		'3249074' => t('Landkreis Ostholstein'),
	);
}
function location_cities_list_de_sl()
{
	return array(
		'2871673' => t('Landkreis Merzig-Wadern'),
		'3249066' => t('Landkreis Neunkirchen'),
		'3249065' => t('Landkreis Saarlouis'),
		'2841464' => t('Landkreis Sankt Wendel'),
		'3249067' => t('Saar-Pfalz-Kreis'),
		'3249068' => t('Stadtverband Saarbrücken'),
	);
}
function location_cities_list_de_be()
{
	return array(
		'6547383' => t('Berlin, Stadt'),
	);
}
function location_cities_list_de_by()
{
	return array(
		'2863622' => t('Lower Bavaria'),
		'2819564' => t('Lower Franconia'),
		'2870736' => t('Middle Franconia'),
		'2835521' => t('Swabia'),
		'2861322' => t('Upper Bavaria'),
		'2860681' => t('Upper Franconia'),
		'2859444' => t('Upper Palatinate'),
	);
}
function location_cities_list_de_he()
{
	return array(
		'2938912' => t('Regierungsbezirk Darmstadt'),
		'3220941' => t('Regierungsbezirk Gießen'),
		'2892513' => t('Regierungsbezirk Kassel'),
	);
}
function location_cities_list_de_ni()
{
	return array(
		'3221014' => t('Helmstedt (district)'),
		'3221011' => t('Kreisfreie Stadt Braunschweig'),
		'3221066' => t('Kreisfreie Stadt Delmenhorst'),
		'3221070' => t('Kreisfreie Stadt Emden'),
		'3221095' => t('Kreisfreie Stadt Oldenburg'),
		'3221096' => t('Kreisfreie Stadt Osnabrück'),
		'3221018' => t('Kreisfreie Stadt Salzgitter'),
		'3221100' => t('Kreisfreie Stadt Wilhelmshaven'),
		'3221023' => t('Kreisfreie Stadt Wolfsburg'),
		'3221058' => t('Landkreis Ammerland'),
		'3221059' => t('Landkreis Aurich'),
		'2940212' => t('Landkreis Celle'),
		'3221064' => t('Landkreis Cloppenburg'),
		'2939657' => t('Landkreis Cuxhaven'),
		'3221024' => t('Landkreis Diepholz'),
		'3221073' => t('Landkreis Emsland'),
		'2924362' => t('Landkreis Friesland'),
		'2920479' => t('Landkreis Gifhorn'),
		'3221012' => t('Landkreis Goslar'),
		'3221075' => t('Landkreis Grafschaft Bentheim'),
		'3221013' => t('Landkreis Göttingen'),
		'3221027' => t('Landkreis Hameln-Pyrmont'),
		'3221033' => t('Landkreis Hannover'),
		'2910684' => t('Landkreis Harburg'),
		'2831482' => t('Landkreis Heidekreis'),
		'2803461' => t('Landkreis Hildesheim'),
		'3221036' => t('Landkreis Holzminden'),
		'3221094' => t('Landkreis Leer'),
		'3221038' => t('Landkreis Lüchow-Dannenberg'),
		'3221040' => t('Landkreis Lüneburg'),
		'2862622' => t('Landkreis Nienburg'),
		'3221015' => t('Landkreis Northeim'),
		'2857455' => t('Landkreis Oldenburg'),
		'3221098' => t('Landkreis Osnabrück'),
		'3221042' => t('Landkreis Osterholz'),
		'3221016' => t('Landkreis Osterode am Harz'),
		'3221017' => t('Landkreis Peine'),
		'3221044' => t('Landkreis Rotenburg'),
		'2840133' => t('Landkreis Schaumburg'),
		'3221046' => t('Landkreis Stade'),
		'3221049' => t('Landkreis Uelzen'),
		'3221097' => t('Landkreis Vechta'),
		'2817598' => t('Landkreis Verden'),
		'3221099' => t('Landkreis Wesermarsch'),
		'3221101' => t('Landkreis Wittmund'),
		'3221020' => t('Landkreis Wolfenbüttel'),
	);
}
function location_cities_list_de_nw()
{
	return array(
		'2955470' => t('Regierungsbezirk Arnsberg'),
		'2937935' => t('Regierungsbezirk Detmold'),
		'2934245' => t('Regierungsbezirk Düsseldorf'),
		'2886241' => t('Regierungsbezirk Köln'),
		'2867539' => t('Regierungsbezirk Münster'),
	);
}
function location_cities_list_de_sn()
{
	return array(
		'3305801' => t('Direktionsbezirk Chemnitz'),
		'3305800' => t('Direktionsbezirk Leipzig'),
		'3305799' => t('Dresden'),
	);
}
function location_cities_list_de_st()
{
	return array(
		'2842111' => t('Altmarkkreis Salzwedel'),
		'2948163' => t('Anhalt-Bitterfeld'),
		'3302156' => t('Burgenlandkreis'),
		'3302159' => t('Börde Rural District'),
		'2937956' => t('Dessau-Roßlau'),
		'3302158' => t('Jerichower Land'),
		'2911516' => t('Kreisfreie Stadt Halle'),
		'2874544' => t('Landeshauptstadt Magdeburg'),
		'2911664' => t('Landkreis Harz'),
		'2827478' => t('Landkreis Stendal'),
		'2807345' => t('Landkreis Wittenberg'),
		'3302155' => t('Mansfeld-Südharz'),
		'2842671' => t('Saalekreis'),
		'2950072' => t('Salzlandkreis'),
	);
}
function location_cities_list_de_th()
{
	return array(
		'6547387' => t('Eichsfeld'),
		'6547386' => t('Eisenach, Stadt'),
		'6547391' => t('Ilm-Kreis'),
		'2929668' => t('Kreisfreie Stadt Erfurt'),
		'2921230' => t('Kreisfreie Stadt Gera'),
		'2895042' => t('Kreisfreie Stadt Jena'),
		'2824945' => t('Kreisfreie Stadt Suhl'),
		'2812479' => t('Kreisfreie Stadt Weimar'),
		'6547390' => t('Kyffhäuserkreis'),
		'2957763' => t('Landkreis Altenburg'),
		'2918750' => t('Landkreis Gotha'),
		'2917735' => t('Landkreis Greiz'),
		'2904803' => t('Landkreis Hildburghausen'),
		'2861979' => t('Landkreis Nordhausen'),
		'3302169' => t('Landkreis Schmalkalden-Meiningen'),
		'2831245' => t('Landkreis Sonneberg'),
		'2831402' => t('Landkreis Sömmerda'),
		'6547393' => t('Saale-Holzland-Kreis'),
		'6547394' => t('Saale-Orla-Kreis'),
		'6547392' => t('Saalfeld-Rudolstadt'),
		'6547389' => t('Unstrut-Hainich-Kreis'),
		'6547388' => t('Wartburgkreis'),
		'2812480' => t('Weimar-Land'),
	);
}
