<?php

function location_cities_list_iq_na () {
	return array (
		"98860" => t("An Najaf al Ashraf"),
		"99060" => t("Al Mishkhab"),
	);
}


function location_cities_list_iq_an () {
	return array (
		"92004" => t("Rawah"),
		"95788" => t("Hit"),
		"96309" => t("Hadithah"),
		"98677" => t("Ar Rutbah"),
		"98717" => t("Ar Ramadi"),
		"98885" => t("`Anat al Qadimah"),
		"99454" => t("Al Fallujah"),
	);
}


function location_cities_list_iq_dq () {
	return array (
		"98622" => t("Ash Shatrah"),
		"98854" => t("An Nasiriyah"),
		"99439" => t("Nahiyat al Fuhud"),
	);
}


function location_cities_list_iq_da () {
	return array (
		"89570" => t("Zakhu"),
		"90708" => t("Sinah"),
		"96994" => t("Dihok"),
	);
}


function location_cities_list_iq_di () {
	return array (
		"93709" => t("Mandali"),
		"94298" => t("Kifri"),
		"97990" => t("Ba`qubah"),
		"99062" => t("Al Miqdadiyah"),
		"99169" => t("Khalis"),
	);
}


function location_cities_list_iq_bg () {
	return array (
		"98182" => t("Baghdad"),
		"100077" => t("Abu Ghurayb"),
	);
}


function location_cities_list_iq_ma () {
	return array (
		"99097" => t("Al Majar al Kabir"),
		"99306" => t("`Ali al Gharbi"),
		"99608" => t("Al `Amarah"),
	);
}


function location_cities_list_iq_sd () {
	return array (
		"90026" => t("Tozkhurmato"),
		"90150" => t("Tikrit"),
		"91597" => t("Samarra'"),
		"97783" => t("Bayji"),
		"98112" => t("Balad"),
		"99759" => t("Ad Dujayl"),
	);
}


function location_cities_list_iq_wa () {
	return array (
		"98459" => t("As Suwayrah"),
		"99131" => t("Al Kut"),
		"99350" => t("Al Hayy"),
		"99548" => t("Al `Aziziyah"),
	);
}


function location_cities_list_iq_ar () {
	return array (
		"92002" => t("Rawanduz"),
		"94220" => t("Koysinceq"),
		"95446" => t("Erbil"),
	);
}


function location_cities_list_iq_bb () {
	return array (
		"91812" => t("Nahiyat Saddat al Hindiyah"),
		"99010" => t("Imam Qasim"),
		"99039" => t("Al Musayyib"),
		"99347" => t("Al Hillah"),
	);
}


function location_cities_list_iq_ka () {
	return array (
		"94824" => t("Karbala"),
		"99344" => t("Al Hindiyah"),
	);
}


function location_cities_list_iq_ts () {
	return array (
		"94787" => t("Kirkuk"),
	);
}


function location_cities_list_iq_ni () {
	return array (
		"90353" => t("Qada' Talkif"),
		"92430" => t("Qada' al Hamdaniyah"),
		"99071" => t("Al Mawsil al Jadidah"),
		"99072" => t("Mosul"),
		"448149" => t("Sinjar"),
	);
}


function location_cities_list_iq_ba () {
	return array (
		"89824" => t("Umm Qasr"),
		"98245" => t("Az Zubayr"),
		"99369" => t("Al Harithah"),
		"99446" => t("Al Faw"),
		"99532" => t("Al Basrah"),
		"388349" => t("Al Basrat al Qadimah"),
	);
}


function location_cities_list_iq_mu () {
	return array (
		"98530" => t("As Samawah"),
		"98685" => t("Ar Rumaythah"),
	);
}


function location_cities_list_iq_qa () {
	return array (
		"98589" => t("Nahiyat ash Shinafiyah"),
		"98629" => t("Ash Shamiyah"),
		"99434" => t("Nahiyat Ghammas"),
		"99738" => t("`Afak"),
		"99762" => t("Ad Diwaniyah"),
	);
}


function location_cities_list_iq_su () {
	return array (
		"96205" => t("Halabjah"),
		"97417" => t("Chamchamal"),
		"98012" => t("Paynjuwayn"),
		"98463" => t("As Sulaymaniyah"),
	);
}
