<?php

function location_cities_list_pa_em () {
	return array (
	);
}


function location_cities_list_pa_ky () {
	return array (
	);
}


function location_cities_list_pa_nb () {
	return array (
	);
}


function location_cities_list_pa_1 () {
	return array (
		"3712560" => t("Changuinola"),
	);
}


function location_cities_list_pa_4 () {
	return array (
		"3702431" => t("Puerto Armuelles"),
		"3703229" => t("Pedregal"),
		"3707899" => t("La Concepcion"),
		"3711668" => t("David"),
	);
}


function location_cities_list_pa_2 () {
	return array (
		"3715042" => t("Aguadulce"),
	);
}


function location_cities_list_pa_3 () {
	return array (
		"3712076" => t("Colon"),
		"3712884" => t("Cativa"),
	);
}


function location_cities_list_pa_6 () {
	return array (
		"3712384" => t("Chitre"),
	);
}


function location_cities_list_pa_7 () {
	return array (
	);
}


function location_cities_list_pa_8 () {
	return array (
		"3700038" => t("Vista Alegre"),
		"3700164" => t("Veracruz"),
		"3700563" => t("Tocumen"),
		"3701329" => t("San Miguelito"),
		"3703443" => t("Panama"),
		"3703647" => t("Pacora"),
		"3703833" => t("Nuevo Arraijan"),
		"3706567" => t("Las Cumbres"),
		"3707961" => t("La Chorrera"),
		"3708066" => t("La Cabima"),
		"3712455" => t("Chilibre"),
		"3712505" => t("Chepo"),
		"3714637" => t("Arraijan"),
		"3714932" => t("Alcaldediaz"),
	);
}


function location_cities_list_pa_9 () {
	return array (
		"3701117" => t("Santiago de Veraguas"),
	);
}


function location_cities_list_pa_5 () {
	return array (
	);
}
