<?php

function location_cities_list_mg_7670851 () {
	return array (
		"1058532" => t("Moramanga"),
		"1076194" => t("Andilamena"),
		"1078446" => t("Amparafaravola"),
		"1082639" => t("Ambatondrazaka"),
	);
}


function location_cities_list_mg_7670904 () {
	return array (
		"1065222" => t("Fandriana"),
		"1079088" => t("Ambositra"),
		"1083239" => t("Ambatofinandrahana"),
	);
}


function location_cities_list_mg_7670856 () {
	return array (
		"1057688" => t("Sadabe"),
		"1060673" => t("Manjakandriana"),
		"1070940" => t("Antananarivo"),
		"1072711" => t("Ankazondandy"),
		"1072849" => t("Ankazobe"),
		"1073482" => t("Anjozorobe"),
		"1079777" => t("Ambohitrolomahitsy"),
		"1084740" => t("Alarobia"),
	);
}


function location_cities_list_mg_7670848 () {
	return array (
		"1054192" => t("Vavatenina"),
		"1056386" => t("Soanierana Ivongo"),
		"1060283" => t("Maroantsetra"),
		"1061412" => t("Mananara"),
		"1064980" => t("Fenoarivo Atsinanana"),
	);
}


function location_cities_list_mg_7670911 () {
	return array (
		"1054500" => t("Tsiombe"),
		"1067565" => t("Beloha"),
		"1079048" => t("Ambovombe"),
	);
}


function location_cities_list_mg_7670910 () {
	return array (
		"1055433" => t("Fort Dauphin"),
		"1081790" => t("Amboasary"),
	);
}


function location_cities_list_mg_7670913 () {
	return array (
		"1055429" => t("Toliara"),
		"1057095" => t("Sakaraha"),
		"1066310" => t("Betioky"),
		"1066831" => t("Beroroha"),
		"1072879" => t("Ankazoabo"),
		"1078553" => t("Ampanihy"),
	);
}


function location_cities_list_mg_7670908 () {
	return array (
		"1053507" => t("Vondrozo"),
		"1053778" => t("Vohipaho"),
		"1054329" => t("Vangaindrano"),
		"1065158" => t("Farafangana"),
	);
}


function location_cities_list_mg_7670857 () {
	return array (
		"1053384" => t("Toamasina"),
		"1054035" => t("Vohibinany"),
		"1060007" => t("Marolambo"),
		"1062553" => t("Mahanoro"),
	);
}


function location_cities_list_mg_7670850 () {
	return array (
		"1055059" => t("Tsaratanana"),
		"1062842" => t("Maevatanana"),
	);
}


function location_cities_list_mg_7670849 () {
	return array (
		"1056531" => t("Sitampiky"),
		"1059507" => t("Marovoay"),
		"1062663" => t("Mahajanga"),
		"1083257" => t("Ambato Boeny"),
	);
}


function location_cities_list_mg_7670853 () {
	return array (
		"1054463" => t("Tsiroanomandidy"),
		"1064978" => t("Fenoarivo Be"),
	);
}


function location_cities_list_mg_7670842 () {
	return array (
		"1068955" => t("Antsohimbondrona"),
		"1069129" => t("Antsiranana"),
		"1076105" => t("Andoany"),
		"1082243" => t("Ambilobe"),
		"1083676" => t("Ambarakaraka"),
		"1083724" => t("Ambanja"),
	);
}


function location_cities_list_mg_7670907 () {
	return array (
		"1064275" => t("Ihosy"),
	);
}


function location_cities_list_mg_7670855 () {
	return array (
		"1056151" => t("Soavinandriana"),
		"1068865" => t("Arivonimamo"),
	);
}


function location_cities_list_mg_7670852 () {
	return array (
		"1061912" => t("Maintirano"),
	);
}


function location_cities_list_mg_7670902 () {
	return array (
		"1058381" => t("Morondava"),
		"1059051" => t("Miandrivazo"),
		"1067531" => t("Belo sur Tsiribihina"),
	);
}


function location_cities_list_mg_7670846 () {
	return array (
		"1056899" => t("Sambava"),
		"1071296" => t("Antalaha"),
		"1076454" => t("Andapa"),
		"1078966" => t("Ampahana"),
	);
}


function location_cities_list_mg_7670847 () {
	return array (
		"1068670" => t("Bealanana"),
		"1068971" => t("Antsohihy"),
	);
}


function location_cities_list_mg_7670905 () {
	return array (
		"1064258" => t("Ikalamavony"),
		"1064890" => t("Fianarantsoa"),
		"1083968" => t("Ambalavao"),
	);
}


function location_cities_list_mg_7670854 () {
	return array (
		"1056381" => t("Soanindrariny"),
		"1059059" => t("Miandrarivo"),
		"1065140" => t("Faratsiho"),
		"1066514" => t("Betafo"),
		"1069166" => t("Antsirabe"),
		"1070661" => t("Antanifotsy"),
		"1082992" => t("Ambatolampy"),
	);
}


function location_cities_list_mg_7670906 () {
	return array (
		"1057277" => t("Sahavato"),
		"1058080" => t("Nosy Varika"),
		"1061335" => t("Mananjary"),
		"1061605" => t("Manakara"),
		"1064234" => t("Ikongo"),
		"1064366" => t("Ifanadiana"),
		"1081863" => t("Amboanjo"),
	);
}
