<?php

function location_cities_list_nr_ao()
{
  return array(
    '7626485' => t('Arijejen'),
    '2110419' => t('Yangor'),
  );
}

function location_cities_list_nr_aa()
{
  return array(
    '2110450' => t('Anabar'),
  );
}

function location_cities_list_nr_at()
{
  return array(
    '2110422' => t('Ronave'),
  );
}

function location_cities_list_nr_ai()
{
  return array(
    '2110447' => t('Anibare'),
  );
}

function location_cities_list_nr_ba()
{
  return array(
    '2110427' => t('Baiti'),
  );
}

function location_cities_list_nr_bu()
{
  return array(
    '7626489' => t('Arenibek'),
  );
}

function location_cities_list_nr_ew()
{
  return array(
    '2110444' => t('Arubo'),
  );
}

function location_cities_list_nr_ij()
{
  return array(
    '2110433' => t('Ijuw'),
  );
}

function location_cities_list_nr_ua()
{
  return array(
    '2110421' => t('Uaboe'),
  );
}

function location_cities_list_nr_ya()
{
  return array(
    '7626461' => t('Yaren'),
  );
}
