<?php


function location_cities_list_ax_035() {
  return array();
}


function location_cities_list_ax_043() {
  return array();
}


function location_cities_list_ax_060() {
  return array();
}


function location_cities_list_ax_062() {
  return array();
}


function location_cities_list_ax_065() {
  return array();
}


function location_cities_list_ax_076() {
  return array();
}


function location_cities_list_ax_170() {
  return array();
}


function location_cities_list_ax_295() {
  return array();
}


function location_cities_list_ax_318() {
  return array();
}


function location_cities_list_ax_417() {
  return array();
}


function location_cities_list_ax_438() {
  return array();
}


function location_cities_list_ax_478() {
  return array(
    "3041732" => t("Mariehamn"),
  );
}


function location_cities_list_ax_736() {
  return array();
}


function location_cities_list_ax_766() {
  return array();
}


function location_cities_list_ax_771() {
  return array();
}


function location_cities_list_ax_941() {
  return array();
}
