<?php


function location_cities_list_pa_em() {
  return array();
}


function location_cities_list_pa_ky() {
  return array();
}


function location_cities_list_pa_nb() {
  return array();
}


function location_cities_list_pa_1() {
  return array(
    "3712560" => "Changuinola",
  );
}


function location_cities_list_pa_4() {
  return array(
    "3702431" => "Puerto Armuelles",
    "3703229" => "Pedregal",
    "3707899" => "La Concepcion",
    "3711668" => "David",
  );
}


function location_cities_list_pa_2() {
  return array(
    "3715042" => "Aguadulce",
  );
}


function location_cities_list_pa_3() {
  return array(
    "3712076" => "Colon",
    "3712884" => "Cativa",
  );
}


function location_cities_list_pa_6() {
  return array(
    "3712384" => "Chitre",
  );
}


function location_cities_list_pa_7() {
  return array();
}


function location_cities_list_pa_8() {
  return array(
    "3700038" => "Vista Alegre",
    "3700164" => "Veracruz",
    "3700563" => "Tocumen",
    "3701329" => "San Miguelito",
    "3703443" => "Panama",
    "3703647" => "Pacora",
    "3703833" => "Nuevo Arraijan",
    "3706567" => "Las Cumbres",
    "3707961" => "La Chorrera",
    "3708066" => "La Cabima",
    "3712455" => "Chilibre",
    "3712505" => "Chepo",
    "3714637" => "Arraijan",
    "3714932" => "Alcaldediaz",
  );
}


function location_cities_list_pa_9() {
  return array(
    "3701117" => "Santiago de Veraguas",
  );
}


function location_cities_list_pa_5() {
  return array();
}
