<?php

function location_cities_list_md_ed () {
	return array (
		"617076" => t("Edinet"),
	);
}


function location_cities_list_md_un () {
	return array (
		"617180" => t("Ungheni"),
	);
}


function location_cities_list_md_sn () {
	return array (
		"618365" => t("Dubasari"),
		"617486" => t("Ribnita"),
		"617381" => t("Slobozia"),
		"617239" => t("Tiraspol"),
	);
}


function location_cities_list_md_st () {
	return array (
		"617302" => t("Straseni"),
	);
}


function location_cities_list_md_si () {
	return array (
		"617345" => t("Bilicenii Vechi"),
	);
}


function location_cities_list_md_so () {
	return array (
		"617367" => t("Soroca"),
	);
}


function location_cities_list_md_or () {
	return array (
		"617638" => t("Orhei"),
	);
}


function location_cities_list_md_hi () {
	return array (
		"617993" => t("Hincesti"),
	);
}


function location_cities_list_md_cs () {
	return array (
		"618120" => t("Causeni"),
	);
}


function location_cities_list_md_fl () {
	return array (
		"618329" => t("Floresti"),
	);
}


function location_cities_list_md_dr () {
	return array (
		"618370" => t("Drochia"),
	);
}


function location_cities_list_md_ga () {
	return array (
		"618450" => t("Ceadir-Lunga"),
		"618405" => t("Comrat"),
	);
}


function location_cities_list_md_cu () {
	return array (
		"618426" => t("Chisinau"),
	);
}


function location_cities_list_md_ca () {
	return array (
		"618456" => t("Cahul"),
	);
}


function location_cities_list_md_bd () {
	return array (
		"618577" => t("Bender"),
	);
}


function location_cities_list_md_ba () {
	return array (
		"618605" => t("Balti"),
	);
}


