<?php

function location_cities_list_np_1 () {
	return array (
		"1282931" => t("Patan"),
		"1282950" => t("Panaoti"),
		"1283082" => t("Malangwa"),
		"1283190" => t("Kirtipur"),
		"1283240" => t("Kathmandu"),
		"1283318" => t("Janakpur"),
		"1283323" => t("Jaleswar"),
		"1283339" => t("Hitura"),
		"1283401" => t("Gaur"),
		"1283581" => t("Birganj"),
		"1283613" => t("Bharatpur"),
		"1283679" => t("Banepa"),
	);
}


function location_cities_list_np_4 () {
	return array (
		"1282770" => t("Siraha"),
		"1282884" => t("Rajbiraj"),
		"1283161" => t("Lahan"),
		"1283217" => t("Khandbari"),
		"1283329" => t("Ithari"),
		"1283333" => t("Ilam"),
		"1283460" => t("Dharan Bazar"),
		"1283465" => t("Dhankuta"),
		"1283582" => t("Biratnagar"),
		"1283628" => t("Bhadrapur"),
	);
}


function location_cities_list_np_5 () {
	return array (
		"1282666" => t("Tikapur"),
		"1283095" => t("Mahendranagar"),
		"1283467" => t("Dhangarhi"),
		"1283499" => t("Dadeldhura"),
		"6254845" => t("Dipayal"),
	);
}


function location_cities_list_np_2 () {
	return array (
		"1282635" => t("Tulsipur"),
		"1283368" => t("Gulariya"),
		"1283496" => t("Dailekh"),
		"6254843" => t("Birendranagar"),
		"6941099" => t("Nepalgunj"),
	);
}


function location_cities_list_np_3 () {
	return array (
		"1282616" => t("Waling"),
		"1282714" => t("Tansen"),
		"1282898" => t("Pokhara"),
		"1283562" => t("Butwal"),
		"1283621" => t("Bhairahawa"),
		"1283711" => t("Baglung"),
	);
}
