<?php


function location_cities_list_bi_bb() {
  return array();
}


function location_cities_list_bi_bm() {
  return array(
    "425378" => "Bujumbura",
  );
}


function location_cities_list_bi_bl() {
  return array();
}


function location_cities_list_bi_br() {
  return array(
    "423328" => "Bururi",
  );
}


function location_cities_list_bi_ca() {
  return array();
}


function location_cities_list_bi_ci() {
  return array();
}


function location_cities_list_bi_gi() {
  return array(
    "426272" => "Gitega",
  );
}


function location_cities_list_bi_kr() {
  return array();
}


function location_cities_list_bi_ky() {
  return array(
    "430952" => "Kayanza",
  );
}


function location_cities_list_bi_ki() {
  return array();
}


function location_cities_list_bi_ma() {
  return array(
    "422232" => "Makamba",
  );
}


function location_cities_list_bi_mu() {
  return array(
    "425551" => "Muramvya",
  );
}


function location_cities_list_bi_my() {
  return array(
    "431748" => "Muyinga",
  );
}


function location_cities_list_bi_ng() {
  return array(
    "430569" => "Ngozi",
  );
}


function location_cities_list_bi_mw() {
  return array();
}


function location_cities_list_bi_rt() {
  return array(
    "433635" => "Rutana",
  );
}


function location_cities_list_bi_ry() {
  return array(
    "426700" => "Ruyigi",
  );
}
