<?php


function location_cities_list_ad_02() {
  return array();
}


function location_cities_list_ad_07() {
  return array(
    "3041563" => "Andorra la Vella",
  );
}


function location_cities_list_ad_03() {
  return array();
}


function location_cities_list_ad_08() {
  return array(
    "3040051" => "les Escaldes",
  );
}


function location_cities_list_ad_05() {
  return array();
}


function location_cities_list_ad_06() {
  return array();
}


function location_cities_list_ad_04() {
  return array();
}
