<?php


function location_cities_list_uz_an() {
  return array(
    "1513271" => "Asaka",
    "1513364" => "Qurghontepa",
    "1513600" => "Khujaobod",
    "1514588" => "Andijon",
  );
}


function location_cities_list_uz_bu() {
  return array(
    "1217084" => "Karakul'",
    "1217180" => "Kogon",
    "1217340" => "Galaosiyo",
    "1217662" => "Bukhara",
    "1512423" => "Wobkent",
    "1512838" => "Shofirkon",
    "1513983" => "Ghijduwon",
  );
}


function location_cities_list_uz_fa() {
  return array(
    "1512320" => "Yaypan",
    "1512568" => "Toshloq",
    "1512979" => "Qo`qon",
    "1513243" => "Marg`ilon",
    "1513331" => "Quvasoy",
    "1513555" => "Kirgili",
    "1514019" => "Fergana",
    "1514382" => "Beshariq",
    "1514615" => "Oltiariq",
    "1526979" => "Quva",
  );
}


function location_cities_list_uz_ji() {
  return array(
    "1215694" => "Zomin",
    "1512480" => "Dashtobod",
    "1513038" => "Paxtakor",
    "1513886" => "Jizzax",
    "1514011" => "Gagarin",
    "1514125" => "Dustlik",
  );
}


function location_cities_list_uz_qr() {
  return array(
    "601294"  => "Nukus",
    "601339"  => "Khujayli",
    "601417"  => "Oltinko'l",
    "1513092" => "Novyy Turtkul'",
    "1513245" => "Manghit",
    "1514387" => "Beruniy",
  );
}


function location_cities_list_uz_qa() {
  return array(
    "1216187" => "Shahrisabz",
    "1216311" => "Qarshi",
    "1216475" => "Muborak",
    "1216787" => "Kitob",
    "1217007" => "Koson",
    "1217262" => "G'uzor",
    "1217540" => "Chiroqchi",
    "1217703" => "Beshkent",
  );
}


function location_cities_list_uz_ng() {
  return array(
    "1512350" => "Yangiqo`rg`on",
    "1512449" => "Uychi",
    "1512501" => "Uchqurghon Shahri",
    "1512549" => "Turagurghon",
    "1512658" => "Toshbuloq",
    "1513023" => "Pop",
    "1513157" => "Namangan",
    "1513655" => "Haqqulobod",
    "1513714" => "Kosonsoy",
    "1514192" => "Chust Shahri",
    "1514258" => "Chortoq",
  );
}


function location_cities_list_uz_nw() {
  return array(
    "1512348" => "Yangirabot",
    "1513087" => "Nurota",
    "1513131" => "Navoiy",
    "1538229" => "Navoiy Shahri",
  );
}


function location_cities_list_uz_sa() {
  return array(
    "1215839" => "Urgut",
    "1216265" => "Samarqand",
    "1216982" => "Kattaqo'rg'on",
    "1217362" => "Juma",
    "1217569" => "Chelak",
    "1217658" => "Bulung'ur",
    "1217926" => "Oqtosh",
    "1513011" => "Payshanba",
  );
}


function location_cities_list_uz_si() {
  return array(
    "1512342" => "Yangiyer",
    "1512770" => "Sirdaryo",
    "1513966" => "Guliston",
  );
}


function location_cities_list_uz_su() {
  return array(
    "1215957" => "Tirmiz",
    "1216115" => "Sho'rchi",
    "1217474" => "Denov",
    "1217734" => "Boysun",
  );
}


function location_cities_list_uz_tk() {
  return array(
    "1512569" => "Tashkent",
    "1514396" => "Bektemir",
  );
}


function location_cities_list_uz_to() {
  return array(
    "1512339" => "Yangiyul",
    "1512372" => "Yangiobod",
    "1512524" => "Tuytepa",
    "1512934" => "Salor",
    "1512986" => "Piskent",
    "1513017" => "Parkent",
    "1513064" => "Olmaliq",
    "1513072" => "Ohangaron",
    "1513567" => "Qibray",
    "1513900" => "Iskandar",
    "1513996" => "G'azalkent",
    "1514210" => "Chirchiq",
    "1514215" => "Chinoz",
    "1514330" => "Buka",
    "1514402" => "Bekobod",
    "1514581" => "Angren",
  );
}


function location_cities_list_uz_xo() {
  return array(
    "1512473" => "Urganch",
    "1512790" => "Showot",
    "1512978" => "Qushkupir",
    "1513604" => "Khiwa",
    "1513957" => "Hazorasp",
    "1513962" => "Gurlan",
  );
}
