<?php


function location_cities_list_my_01() {
  return array(
    "1732687" => t("Batu Pahat"),
    "1732698" => t("Parit Raja"),
    "1732706" => t("Pekan Nenas"),
    "1732711" => t("Pontian Kechil"),
    "1732721" => t("Kampung Pasir Gudang Baru"),
    "1732738" => t("Kota Tinggi"),
    "1732741" => t("Taman Senai"),
    "1732742" => t("Kulai"),
    "1732745" => t("Sekudai"),
    "1732752" => t("Johor Bahru"),
    "1732811" => t("Kluang"),
    "1732814" => t("Yong Peng"),
    "1732826" => t("Mersing"),
    "1732846" => t("Segamat"),
    "1732857" => t("Tangkak"),
    "1732869" => t("Muar"),
    "1732871" => t("Bakeri"),
    "1732877" => t("Labis"),
    "1738294" => t("Ulu Tiram"),
    "1764318" => t("Kampung Simpang Renggam"),
  );
}


function location_cities_list_my_02() {
  return array(
    "1222396" => t("Kuah"),
    "1734393" => t("Kulim"),
    "1734439" => t("Bedong"),
    "1735485" => t("Gurun"),
    "1735498" => t("Sungai Petani"),
    "1736302" => t("Jitra"),
    "1736305" => t("Kuala Kedah"),
    "1736309" => t("Alor Setar"),
  );
}


function location_cities_list_my_03() {
  return array(
    "1734651" => t("Gua Musang"),
    "1735553" => t("Tanah Merah"),
    "1736372" => t("Pasir Mas"),
    "1736376" => t("Kota Bharu"),
    "1750582" => t("Peringat"),
    "1766249" => t("Kampong Pangkal Kalong"),
    "1768664" => t("Kampong Kadok"),
  );
}


function location_cities_list_my_14() {
  return array(
    "1735161" => t("Kuala Lumpur"),
  );
}


function location_cities_list_my_15() {
  return array(
    "1733782" => t("Victoria"),
  );
}


function location_cities_list_my_04() {
  return array(
    "1734745" => t("Alor Gajah"),
    "1734753" => t("Kampung Ayer Keroh"),
    "1734757" => t("Sungai Udang"),
    "1734759" => t("Melaka"),
    "1761242" => t("Klebang Besar"),
    "1767021" => t("Kampong Masjid Tanah"),
    "1770351" => t("Kampung Bukit Baharu"),
    "1771485" => t("Kampung Ayer Molek"),
    "1778290" => t("Bukit Rambai"),
    "1780890" => t("Berendam"),
  );
}


function location_cities_list_my_05() {
  return array(
    "1734738" => t("Tampin"),
    "1734810" => t("Seremban"),
    "1734815" => t("Port Dickson"),
    "1734839" => t("Bahau"),
    "1734841" => t("Kuala Pilah"),
    "1771287" => t("Kampung Baharu Nilai"),
  );
}


function location_cities_list_my_06() {
  return array(
    "1732602" => t("Jerantut"),
    "1732663" => t("Raub"),
    "1733023" => t("Kuala Lipis"),
    "1734971" => t("Pekan"),
    "1735018" => t("Mentekab"),
    "1735022" => t("Temerluh"),
    "1735227" => t("Kuantan"),
    "1779790" => t("Bentong Town"),
  );
}


function location_cities_list_my_08() {
  return array(
    "1734409" => t("Bagan Serai"),
    "1734576" => t("Simpang Empat"),
    "1734586" => t("Taiping"),
    "1734599" => t("Kuala Kangsar"),
    "1734634" => t("Ipoh"),
    "1735089" => t("Parit Buntar"),
    "1735268" => t("Batu Gajah"),
    "1735274" => t("Kampar"),
    "1735282" => t("Tapah Road"),
    "1735287" => t("Bidur"),
    "1735450" => t("Lumut"),
    "1735459" => t("Teluk Intan"),
    "1752256" => t("Pantai Remis"),
  );
}


function location_cities_list_my_09() {
  return array(
    "1736278" => t("Kangar"),
  );
}


function location_cities_list_my_07() {
  return array(
    "1735076" => t("Butterworth"),
    "1735077" => t("Perai"),
    "1735079" => t("Bukit Mertajam"),
    "1735086" => t("Nibong Tebal"),
    "1735093" => t("Tasek Glugor"),
    "1735106" => t("George Town"),
    "1735506" => t("Kepala Batas"),
    "1741550" => t("Tanjung Tokong"),
    "1750500" => t("Permatang Kuching"),
    "1764160" => t("Kampung Sungai Ara"),
  );
}


function location_cities_list_my_16() {
  return array(
    "6697380" => t("Putrajaya"),
  );
}


function location_cities_list_my_12() {
  return array(
    "1733353" => t("Papar"),
    "1733432" => t("Kota Kinabalu"),
    "1733438" => t("Donggongon"),
    "1733440" => t("Putatan"),
    "1733449" => t("Kinarut"),
    "1733502" => t("Ranau"),
    "1733697" => t("Semporna"),
    "1733874" => t("Beaufort"),
    "1733953" => t("Lahad Datu"),
    "1734052" => t("Sandakan"),
    "1734098" => t("Keningau"),
    "1734199" => t("Tawau"),
    "1736458" => t("Kudat"),
    "7302815" => t("Bandar Labuan"),
  );
}


function location_cities_list_my_13() {
  return array(
    "1735634" => t("Kuching"),
    "1735799" => t("Simanggang"),
    "1735837" => t("Sarikei"),
    "1735902" => t("Sibu"),
    "1737185" => t("Kapit"),
    "1737486" => t("Bintulu"),
    "1737714" => t("Limbang"),
    "1738050" => t("Miri"),
  );
}


function location_cities_list_my_10() {
  return array(
    "1732891" => t("Kuala Selangor"),
    "1732903" => t("Shah Alam"),
    "1732905" => t("Klang"),
    "1734793" => t("Jenjarum"),
    "1734798" => t("Semenyih"),
    "1735148" => t("Serendah"),
    "1735150" => t("Rawang"),
    "1735158" => t("Petaling Jaya"),
    "1735195" => t("Sabak Bernam"),
    "1735199" => t("Sungai Besar"),
    "1741562" => t("Tanjung Sepat"),
    "1750974" => t("Ladang Seri Kundang"),
    "1759486" => t("Kuang"),
    "1763412" => t("Kampung Tanjung Karang"),
    "1771023" => t("Kampung Baru Subang"),
    "1771304" => t("Kampong Baharu Balakong"),
    "8504423" => t("Subang Jaya"),
  );
}


function location_cities_list_my_11() {
  return array(
    "1732945" => t("Cukai"),
    "1734313" => t("Paka"),
    "1734316" => t("Kertih"),
    "1734705" => t("Kuala Terengganu"),
    "1734715" => t("Marang"),
  );
}
