<?php


function location_cities_list_dj_as() {
  return array(
    "224152" => "Danan",
    "225284" => "'Ali Sabieh",
  );
}


function location_cities_list_dj_ar() {
  return array();
}


function location_cities_list_dj_di() {
  return array();
}


function location_cities_list_dj_dj() {
  return array(
    "223817" => "Djibouti",
  );
}


function location_cities_list_dj_ob() {
  return array(
    "221527" => "Obock",
  );
}


function location_cities_list_dj_ta() {
  return array(
    "220782" => "Tadjoura",
  );
}
