<?php


function location_cities_list_bs_ak() {
  return array();
}


function location_cities_list_bs_eg() {
  return array();
}


function location_cities_list_bs_bi() {
  return array();
}


function location_cities_list_bs_bp() {
  return array();
}


function location_cities_list_bs_ci() {
  return array();
}


function location_cities_list_bs_co() {
  return array();
}


function location_cities_list_bs_cs() {
  return array();
}


function location_cities_list_bs_ce() {
  return array();
}


function location_cities_list_bs_fp() {
  return array(
    "3571971" => "Lucaya",
    "3572375" => "Freeport",
  );
}


function location_cities_list_bs_ck() {
  return array();
}


function location_cities_list_bs_ex() {
  return array();
}


function location_cities_list_bs_gc() {
  return array();
}


function location_cities_list_bs_gt() {
  return array();
}


function location_cities_list_bs_hi() {
  return array();
}


function location_cities_list_bs_ht() {
  return array(
    "3571824" => "Nassau",
  );
}


function location_cities_list_bs_in() {
  return array();
}


function location_cities_list_bs_li() {
  return array();
}


function location_cities_list_bs_mc() {
  return array();
}


function location_cities_list_bs_mg() {
  return array();
}


function location_cities_list_bs_mi() {
  return array();
}


function location_cities_list_bs_no() {
  return array();
}


function location_cities_list_bs_ns() {
  return array();
}


function location_cities_list_bs_ne() {
  return array();
}


function location_cities_list_bs_ri() {
  return array();
}


function location_cities_list_bs_rc() {
  return array();
}


function location_cities_list_bs_ss() {
  return array();
}


function location_cities_list_bs_so() {
  return array();
}


function location_cities_list_bs_sa() {
  return array();
}


function location_cities_list_bs_se() {
  return array();
}


function location_cities_list_bs_sw() {
  return array();
}


function location_cities_list_bs_wg() {
  return array();
}
