<?php


function location_cities_list_mk_01() {
  return array();
}


function location_cities_list_mk_03() {
  return array();
}


function location_cities_list_mk_04() {
  return array(
    "792578" => "Bitola",
  );
}


function location_cities_list_mk_05() {
  return array();
}


function location_cities_list_mk_06() {
  return array(
    "789611" => "Kamenjane",
    "792501" => "Bogovinje",
  );
}


function location_cities_list_mk_07() {
  return array();
}


function location_cities_list_mk_08() {
  return array(
    "792227" => "Brvenica",
  );
}


function location_cities_list_mk_09() {
  return array(
    "833260" => "Butel",
  );
}


function location_cities_list_mk_21() {
  return array(
    "791606" => "Debar",
  );
}


function location_cities_list_mk_22() {
  return array();
}


function location_cities_list_mk_25() {
  return array();
}


function location_cities_list_mk_24() {
  return array();
}


function location_cities_list_mk_27() {
  return array();
}


function location_cities_list_mk_28() {
  return array();
}


function location_cities_list_mk_17() {
  return array();
}


function location_cities_list_mk_18() {
  return array(
    "790744" => "Gevgelija",
  );
}


function location_cities_list_mk_19() {
  return array(
    "790295" => "Gostivar",
  );
}


function location_cities_list_mk_20() {
  return array();
}


function location_cities_list_mk_34() {
  return array(
    "833357" => "Ilinden",
  );
}


function location_cities_list_mk_35() {
  return array();
}


function location_cities_list_mk_37() {
  return array();
}


function location_cities_list_mk_36() {
  return array(
    "789541" => "Kavadarci",
  );
}


function location_cities_list_mk_39() {
  return array(
    "863675" => "Kisela Voda",
  );
}


function location_cities_list_mk_43() {
  return array();
}


function location_cities_list_mk_44() {
  return array(
    "789045" => "Kriva Palanka",
  );
}


function location_cities_list_mk_47() {
  return array(
    "788886" => "Kumanovo",
  );
}


function location_cities_list_mk_49() {
  return array();
}


function location_cities_list_mk_51() {
  return array();
}


function location_cities_list_mk_52() {
  return array();
}


function location_cities_list_mk_53() {
  return array();
}


function location_cities_list_mk_54() {
  return array(
    "787716" => "Negotino",
  );
}


function location_cities_list_mk_55() {
  return array();
}


function location_cities_list_mk_56() {
  return array();
}


function location_cities_list_mk_58() {
  return array(
    "787487" => "Ohrid",
  );
}


function location_cities_list_mk_29() {
  return array();
}


function location_cities_list_mk_48() {
  return array(
    "788654" => "Lipkovo",
  );
}


function location_cities_list_mk_65() {
  return array();
}


function location_cities_list_mk_02() {
  return array();
}


function location_cities_list_mk_077() {
  return array();
}


function location_cities_list_mk_78() {
  return array(
    "7886881" => "Centar Zupa",
  );
}


function location_cities_list_mk_23() {
  return array(
    "791559" => "Delchevo",
  );
}


function location_cities_list_mk_26() {
  return array();
}


function location_cities_list_mk_38() {
  return array(
    "785842" => "Skopje",
  );
}


function location_cities_list_mk_40() {
  return array(
    "789527" => "Kicevo",
  );
}


function location_cities_list_mk_41() {
  return array();
}


function location_cities_list_mk_42() {
  return array(
    "789403" => "Kochani",
  );
}


function location_cities_list_mk_45() {
  return array();
}


function location_cities_list_mk_46() {
  return array();
}


function location_cities_list_mk_50() {
  return array();
}


function location_cities_list_mk_60() {
  return array();
}


function location_cities_list_mk_63() {
  return array();
}


function location_cities_list_mk_64() {
  return array(
    "786565" => "Radovish",
  );
}


function location_cities_list_mk_83() {
  return array();
}


function location_cities_list_mk_84() {
  return array();
}


function location_cities_list_mk_73() {
  return array(
    "785345" => "Studenichani",
  );
}


function location_cities_list_mk_12() {
  return array();
}


function location_cities_list_mk_15() {
  return array();
}


function location_cities_list_mk_16() {
  return array(
    "787715" => "Negotino",
  );
}


function location_cities_list_mk_79() {
  return array(
    "833262" => "Cair",
  );
}


function location_cities_list_mk_80() {
  return array();
}


function location_cities_list_mk_81() {
  return array();
}


function location_cities_list_mk_82() {
  return array();
}


function location_cities_list_mk_70() {
  return array(
    "785482" => "Shtip",
  );
}


function location_cities_list_mk_74() {
  return array(
    "833258" => "Suto Orizare",
  );
}


function location_cities_list_mk_30() {
  return array(
    "783926" => "Zhelino",
  );
}


function location_cities_list_mk_57() {
  return array();
}


function location_cities_list_mk_59() {
  return array();
}


function location_cities_list_mk_61() {
  return array();
}


function location_cities_list_mk_62() {
  return array(
    "786735" => "Prilep",
  );
}


function location_cities_list_mk_66() {
  return array(
    "786341" => "Resen",
  );
}


function location_cities_list_mk_67() {
  return array();
}


function location_cities_list_mk_68() {
  return array(
    "786093" => "Saraj",
  );
}


function location_cities_list_mk_71() {
  return array(
    "785387" => "Struga",
  );
}


function location_cities_list_mk_72() {
  return array(
    "785380" => "Strumica",
  );
}


function location_cities_list_mk_69() {
  return array();
}


function location_cities_list_mk_75() {
  return array(
    "785113" => "Tearce",
  );
}


function location_cities_list_mk_76() {
  return array(
    "785082" => "Tetovo",
  );
}


function location_cities_list_mk_10() {
  return array();
}


function location_cities_list_mk_11() {
  return array();
}


function location_cities_list_mk_13() {
  return array(
    "785058" => "Veles",
  );
}


function location_cities_list_mk_14() {
  return array(
    "784424" => "Vinica",
  );
}


function location_cities_list_mk_31() {
  return array();
}


function location_cities_list_mk_32() {
  return array();
}


function location_cities_list_mk_33() {
  return array();
}
