<?php


function location_cities_list_mu_ag() {
  return array();
}


function location_cities_list_mu_bl() {
  return array();
}


function location_cities_list_mu_cc() {
  return array();
}


function location_cities_list_mu_fl() {
  return array(
    "934631" => "Centre de Flacq",
    "934750" => "Bel Air",
  );
}


function location_cities_list_mu_gp() {
  return array(
    "934322" => "Mahebourg",
  );
}


function location_cities_list_mu_mo() {
  return array(
    "934032" => "Saint Pierre",
  );
}


function location_cities_list_mu_pa() {
  return array(
    "933959"  => "Triolet",
    "1106809" => "Le Hochet",
  );
}


function location_cities_list_mu_pw() {
  return array(
    "933945" => "Vacoas",
    "934131" => "Quatre Bornes",
    "934570" => "Curepipe",
  );
}


function location_cities_list_mu_pl() {
  return array(
    "934154" => "Port Louis",
  );
}


function location_cities_list_mu_rr() {
  return array(
    "934488" => "Goodlands",
  );
}


function location_cities_list_mu_ro() {
  return array();
}


function location_cities_list_mu_sa() {
  return array();
}
