<?php

function location_cities_list_lb_bi () {
	return array (
		"266045" => t("Zahle"),
	);
}


function location_cities_list_lb_as () {
	return array (
		"276359" => t("Bcharre"),
		"266826" => t("Tripoli"),
	);
}


function location_cities_list_lb_ja () {
	return array (
		"268064" => t("Sidon"),
		"267008" => t("Tyre"),
	);
}


function location_cities_list_lb_ba () {
	return array (
		"276781" => t("Beirut"),
		"268743" => t("Ra's Bayrut"),
	);
}


function location_cities_list_lb_jl () {
	return array (
		"273140" => t("Djounie"),
		"273203" => t("Jbail"),
	);
}


function location_cities_list_lb_na () {
	return array (
		"274874" => t("Habbouch"),
		"278913" => t("Nabatiye et Tahta"),
	);
}


function location_cities_list_lb_bh () {
	return array (
		"277130" => t("Baalbek"),
	);
}


