<?php

function location_cities_list_sh_a()
{
	return array(
		'2411397' => t('Georgetown'),
		'2411327' => t('Thornton'),
		'2572137' => t('Two Boats Village'),
	);
}
function location_cities_list_sh_s()
{
	return array(
		'7730332' => t('Barren Ground'),
		'3371004' => t('Deadwood'),
		'3370936' => t('Half Tree Hollow'),
		'3370907' => t('Hutts Gate'),
		'3370903' => t('Jamestown'),
		'3370880' => t('Levelwood'),
		'3370867' => t('Longwood'),
		'3370831' => t('New Ground'),
		'3370695' => t('Taglate'),
	);
}
function location_cities_list_sh_t()
{
	return array(
		'3370726' => t('Edinburgh of the Seven Seas'),
	);
}
