<?php


function location_cities_list_bg_01() {
  return array(
    "727447" => t("Sandanski"),
    "728288" => t("Petrich"),
    "731108" => t("Gotse Delchev"),
    "733191" => t("Blagoevgrad"),
  );
}


function location_cities_list_bg_02() {
  return array(
    "730559" => t("Karnobat"),
    "732770" => t("Burgas"),
    "733579" => t("Aytos"),
  );
}


function location_cities_list_bg_07() {
  return array(
    "727337" => t("Sevlievo"),
    "731549" => t("Gabrovo"),
  );
}


function location_cities_list_bg_11() {
  return array(
    "726320" => t("Troyan"),
    "729559" => t("Lovech"),
  );
}


function location_cities_list_bg_08() {
  return array(
    "726418" => t("Dobrich"),
  );
}


function location_cities_list_bg_26() {
  return array(
    "726546" => t("Svilengrad"),
    "730435" => t("Haskovo"),
    "730442" => t("Kharmanli"),
    "732263" => t("Dimitrovgrad"),
  );
}


function location_cities_list_bg_10() {
  return array(
    "726872" => t("Dupnitsa"),
    "729730" => t("Kyustendil"),
  );
}


function location_cities_list_bg_09() {
  return array(
    "729794" => t("Kurdzhali"),
  );
}


function location_cities_list_bg_12() {
  return array(
    "729114" => t("Montana"),
    "729581" => t("Lom"),
    "733264" => t("Berkovitsa"),
  );
}


function location_cities_list_bg_15() {
  return array(
    "728203" => t("Pleven"),
    "732491" => t("Cherven Bryag"),
  );
}


function location_cities_list_bg_17() {
  return array(
    "727696" => t("Razgrad"),
  );
}


function location_cities_list_bg_18() {
  return array(
    "727523" => t("Ruse"),
  );
}


function location_cities_list_bg_27() {
  return array(
    "727233" => t("Shumen"),
  );
}


function location_cities_list_bg_19() {
  return array(
    "727221" => t("Silistra"),
  );
}


function location_cities_list_bg_20() {
  return array(
    "727079" => t("Sliven"),
    "728742" => t("Nova Zagora"),
  );
}


function location_cities_list_bg_21() {
  return array(
    "727030" => t("Smolyan"),
  );
}


function location_cities_list_bg_24() {
  return array(
    "726848" => t("Stara Zagora"),
    "730496" => t("Kazanluk"),
    "732452" => t("Chirpan"),
  );
}


function location_cities_list_bg_25() {
  return array(
    "726174" => t("Targovishte"),
    "728075" => t("Popovo"),
  );
}


function location_cities_list_bg_04() {
  return array(
    "725993" => t("Veliko Turnovo"),
    "726534" => t("Svishtov"),
    "731233" => t("Gorna Oryakhovitsa"),
  );
}


function location_cities_list_bg_05() {
  return array(
    "725905" => t("Vidin"),
  );
}


function location_cities_list_bg_06() {
  return array(
    "725712" => t("Vratsa"),
  );
}


function location_cities_list_bg_28() {
  return array(
    "725578" => t("Yambol"),
  );
}


function location_cities_list_bg_13() {
  return array(
    "725988" => t("Velingrad"),
    "728317" => t("Peshtera"),
    "728378" => t("Pazardzhik"),
    "728448" => t("Panagyurishte"),
  );
}


function location_cities_list_bg_14() {
  return array(
    "728330" => t("Pernik"),
  );
}


function location_cities_list_bg_16() {
  return array(
    "727791" => t("Rakovski"),
    "728193" => t("Plovdiv"),
    "730565" => t("Karlovo"),
    "733618" => t("Asenovgrad"),
  );
}


function location_cities_list_bg_22() {
  return array(
    "727011" => t("Sofia"),
  );
}


function location_cities_list_bg_23() {
  return array(
    "727462" => t("Samokov"),
    "733014" => t("Botevgrad"),
  );
}


function location_cities_list_bg_03() {
  return array(
    "726050" => t("Varna"),
  );
}
