<?php

function location_cities_list_si_129 () {
	return array (
		"3188915" => t("Trbovlje"),
	);
}


function location_cities_list_si_133 () {
	return array (
		"3189075" => t("Velenje"),
	);
}


function location_cities_list_si_194 () {
	return array (
		"3190495" => t("Smartno pri Litiji"),
	);
}


function location_cities_list_si_096 () {
	return array (
		"3192241" => t("Ptuj"),
	);
}


function location_cities_list_si_085 () {
	return array (
		"3194351" => t("Novo Mesto"),
	);
}


function location_cities_list_si_070 () {
	return array (
		"3195506" => t("Maribor"),
	);
}


function location_cities_list_si_061 () {
	return array (
		"3196359" => t("Ljubljana"),
	);
}


function location_cities_list_si_052 () {
	return array (
		"3197378" => t("Kranj"),
	);
}


function location_cities_list_si_050 () {
	return array (
		"3197753" => t("Koper"),
	);
}


function location_cities_list_si_011 () {
	return array (
		"3202781" => t("Celje"),
	);
}


