<?php


function location_cities_list_lb_ba() {
  return array(
    "268743" => "Ra's Bayrut",
    "276781" => "Beirut",
  );
}


function location_cities_list_lb_ak() {
  return array();
}


function location_cities_list_lb_bh() {
  return array(
    "277130" => "Baalbek",
  );
}


function location_cities_list_lb_bi() {
  return array(
    "266045" => "Zahle",
  );
}


function location_cities_list_lb_as() {
  return array(
    "266826" => "Tripoli",
    "276359" => "Bcharre",
  );
}


function location_cities_list_lb_ja() {
  return array(
    "267008" => "Tyre",
    "268064" => "Sidon",
  );
}


function location_cities_list_lb_jl() {
  return array(
    "273140" => "Djounie",
    "273203" => "Jbail",
  );
}


function location_cities_list_lb_na() {
  return array(
    "274874" => "Habbouch",
    "278913" => "Nabatiye et Tahta",
  );
}
