<?php


function location_cities_list_uy_ar() {
  return array(
    "3443758" => "Artigas",
  );
}


function location_cities_list_uy_ca() {
  return array(
    "3440571" => "Santa Lucia",
    "3440963" => "Progreso",
    "3441292" => "Paso de Carrasco",
    "3441354" => "Pando",
    "3442057" => "Las Piedras",
    "3442098" => "La Paz",
    "3443413" => "Canelones",
  );
}


function location_cities_list_uy_cl() {
  return array(
    "3441702" => "Melo",
  );
}


function location_cities_list_uy_co() {
  return array(
    "3443013" => "Colonia del Sacramento",
    "3443341" => "Carmelo",
  );
}


function location_cities_list_uy_du() {
  return array(
    "3442727" => "Durazno",
  );
}


function location_cities_list_uy_fs() {
  return array(
    "3439748" => "Trinidad",
    "3439749" => "Trinidad",
  );
}


function location_cities_list_uy_mo() {
  return array(
    "3441575" => "Montevideo",
  );
}


function location_cities_list_uy_pa() {
  return array(
    "3441243" => "Paysandu",
  );
}


function location_cities_list_uy_rv() {
  return array(
    "3440781" => "Rivera",
  );
}


function location_cities_list_uy_ro() {
  return array(
    "3440777" => "Rocha",
  );
}


function location_cities_list_uy_rn() {
  return array(
    "3439525" => "Young",
    "3442568" => "Fray Bentos",
  );
}


function location_cities_list_uy_sa() {
  return array(
    "3440714" => "Salto",
  );
}


function location_cities_list_uy_sj() {
  return array(
    "3440639" => "San Jose de Mayo",
    "3442778" => "Delta del Tigre",
  );
}


function location_cities_list_uy_ta() {
  return array(
    "3440034" => "Tacuarembo",
  );
}


function location_cities_list_uy_tt() {
  return array(
    "3439781" => "Treinta y Tres",
  );
}


function location_cities_list_uy_fd() {
  return array(
    "3442585" => "Florida",
  );
}


function location_cities_list_uy_la() {
  return array(
    "3441665" => "Minas",
  );
}


function location_cities_list_uy_ma() {
  return array(
    "3440696" => "San Carlos",
    "3441894" => "Maldonado",
  );
}


function location_cities_list_uy_so() {
  return array(
    "3441684" => "Mercedes",
    "3442750" => "Dolores",
  );
}
