<?php


function location_cities_list_ru_alt() {
  return array(
    "1485439" => "Zarinsk",
    "1485627" => "Yuzhnyy",
    "1486340" => "Yarovoye",
    "1490266" => "Tal'menka",
    "1491706" => "Slavgorod",
    "1493467" => "Rubtsovsk",
    "1496739" => "Novosilikatnyy",
    "1497173" => "Novoaltaysk",
    "1501460" => "Kulunda",
    "1504871" => "Kamen'-na-Obi",
    "1506260" => "Gornyak",
    "1510018" => "Biysk",
    "1510853" => "Barnaul",
    "1511783" => "Aleysk",
  );
}


function location_cities_list_ru_amu() {
  return array(
    "2012593" => "Zeya",
    "2014718" => "Tynda",
    "2015833" => "Svobodnyy",
    "2016701" => "Shimanovsk",
    "2017487" => "Raychikhinsk",
    "2026609" => "Blagoveshchensk",
    "2026895" => "Belogorsk",
  );
}


function location_cities_list_ru_ark() {
  return array(
    "475938" => "Vel'sk",
    "496285" => "Severodvinsk",
    "515246" => "Onega",
    "516647" => "Nyandoma",
    "518909" => "Novodvinsk",
    "526346" => "Mirnyy",
    "543704" => "Kotlas",
    "544370" => "Koryazhma",
    "581049" => "Arkhangel'sk",
    "831129" => "Mirnyy",
  );
}


function location_cities_list_ru_ast() {
  return array(
    "550671" => "Kharabali",
    "553248" => "Kamyzyak",
    "580497" => "Astrakhan'",
    "583798" => "Akhtubinsk",
    "831130" => "Znamensk",
  );
}


function location_cities_list_ru_ba() {
  return array(
    "469178" => "Yanaul",
    "479561" => "Ufa",
    "479703" => "Uchaly",
    "479704" => "Uchaly",
    "480089" => "Tuymazy",
    "484856" => "Agidel'",
    "487495" => "Sterlitamak",
    "493160" => "Sibay",
    "499292" => "Salavat",
    "502540" => "Rayevskiy",
    "505014" => "Priyutovo",
    "515879" => "Oktyabr'skiy",
    "522942" => "Neftekamsk",
    "527717" => "Meleuz",
    "539283" => "Kumertau",
    "555980" => "Ishimbay",
    "563719" => "Dyurtyuli",
    "567006" => "Davlekanovo",
    "568012" => "Chishmy",
    "576116" => "Blagoveshchensk",
    "576317" => "Birsk",
    "577881" => "Beloretsk",
    "578120" => "Belebey",
    "578534" => "Baymak",
  );
}


function location_cities_list_ru_bel() {
  return array(
    "477192" => "Valuyki",
    "487147" => "Stroitel'",
    "487928" => "Staryy Oskol",
    "495112" => "Shebekino",
    "502400" => "Razumnoye",
    "516931" => "Novyy Oskol",
    "558146" => "Gubkin",
    "568587" => "Chernyanka",
    "578072" => "Belgorod",
    "582956" => "Alekseyevka",
  );
}


function location_cities_list_ru_bry() {
  return array(
    "462822" => "Zhukovka",
    "479028" => "Unecha",
    "481350" => "Trubchevsk",
    "488852" => "Starodub",
    "497610" => "Sel'tso",
    "508656" => "Pochep",
    "517269" => "Novozybkov",
    "547475" => "Klintsy",
    "552920" => "Karachev",
    "563822" => "Dyat'kovo",
    "571476" => "Bryansk",
  );
}


function location_cities_list_ru_ce() {
  return array(
    "478581" => "Urus-Martan",
    "515804" => "Tsotsin-Yurt",
    "538913" => "Kurchaloy",
    "558118" => "Gudermes",
    "558418" => "Groznyy",
    "580218" => "Avtury",
    "581126" => "Argun",
    "584298" => "Achkhoy-Martan",
  );
}


function location_cities_list_ru_che() {
  return array(
    "462444"  => "Zlatoust",
    "478071"  => "Ust'-Katav",
    "492944"  => "Sim",
    "498418"  => "Satka",
    "532288"  => "Magnitogorsk",
    "538442"  => "Kusa",
    "551794"  => "Katav-Ivanovsk",
    "579738"  => "Bakal",
    "580660"  => "Asha",
    "830844"  => "Trekhgornyy",
    "1485634" => "Yuzhnoural'sk",
    "1486039" => "Yemanzhelinsk",
    "1487394" => "Verkhniy Ufaley",
    "1489246" => "Troitsk",
    "1494907" => "Plast",
    "1498894" => "Miass",
    "1500997" => "Kyshtym",
    "1502536" => "Korkino",
    "1502603" => "Kopeysk",
    "1504251" => "Kasli",
    "1504317" => "Kartaly",
    "1504636" => "Karabash",
    "1508291" => "Chelyabinsk",
    "1508350" => "Chebarkul'",
    "1536289" => "Snezhinsk",
    "1538634" => "Ozersk",
  );
}


function location_cities_list_ru_chu() {
  return array();
}


function location_cities_list_ru_cu() {
  return array(
    "493463" => "Shumerlya",
    "518976" => "Novocheboksarsk",
    "553216" => "Kanash",
    "569696" => "Cheboksary",
    "583437" => "Alatyr'",
  );
}


function location_cities_list_ru_da() {
  return array(
    "532096" => "Makhachkala",
    "547840" => "Kizlyar",
    "547849" => "Kizilyurt",
    "550478" => "Khasavyurt",
    "551847" => "Kaspiysk",
    "554894" => "Izberbash",
    "566532" => "Derbent",
    "567290" => "Dagestanskiye Ogni",
    "570479" => "Buynaksk",
    "828055" => "Belidzhi",
  );
}


function location_cities_list_ru_irk() {
  return array(
    "1489870" => "Tayshet",
    "1497549" => "Nizhneudinsk",
    "1507636" => "Chunskiy",
    "2012484" => "Zima",
    "2012557" => "Zheleznogorsk-Ilimskiy",
    "2013399" => "Vikhorevka",
    "2013923" => "Ust'-Kut",
    "2013952" => "Ust'-Ilimsk",
    "2014022" => "Usol'ye-Sibirskoye",
    "2014927" => "Tulun",
    "2016422" => "Slyudyanka",
    "2016764" => "Shelekhov",
    "2023469" => "Irkutsk",
    "2025527" => "Cheremkhovo",
    "2026583" => "Bodaybo",
    "2026979" => "Baykal'sk",
    "2027667" => "Angarsk",
    "2051523" => "Bratsk",
    "2055166" => "Sayansk",
  );
}


function location_cities_list_ru_iva() {
  return array(
    "473788" => "Vichuga",
    "483137" => "Teykovo",
    "493231" => "Shuya",
    "501730" => "Rodniki",
    "505060" => "Privolzhsk",
    "546672" => "Kokhma",
    "548605" => "Kineshma",
    "555312" => "Ivanovo",
    "562309" => "Furmanov",
  );
}


function location_cities_list_ru_yev() {
  return array(
    "2026643" => "Birobidzhan",
  );
}


function location_cities_list_ru_kb() {
  return array(
    "479933" => "Tyrnyauz",
    "483495" => "Terek",
    "504935" => "Prokhladnyy",
    "523405" => "Nartkala",
    "523523" => "Nal'chik",
    "537345" => "Dugulubgey",
    "569639" => "Chegem",
    "579574" => "Baksan",
  );
}


function location_cities_list_ru_kgd() {
  return array(
    "485660"  => "Svetlyy",
    "490068"  => "Sovetsk",
    "554234"  => "Kaliningrad",
    "557882"  => "Gusev",
    "568595"  => "Chernyakhovsk",
    "2609906" => "Baltiysk",
  );
}


function location_cities_list_ru_kl() {
  return array(
    "563514" => "Elista",
  );
}


function location_cities_list_ru_klu() {
  return array(
    "486665" => "Sukhinichi",
    "516436" => "Obninsk",
    "530849" => "Maloyaroslavets",
    "532459" => "Lyudinovo",
    "543348" => "Kozel'sk",
    "545575" => "Kondrovo",
    "548410" => "Kirov",
    "553915" => "Kaluga",
    "579529" => "Balabanovo",
  );
}


function location_cities_list_ru_kam() {
  return array(
    "2118647" => "Vilyuchinsk",
    "2119538" => "Yelizovo",
    "2122104" => "Petropavlovsk-Kamchatskiy",
  );
}


function location_cities_list_ru_kc() {
  return array(
    "463885" => "Zelenchukskaya",
    "478130" => "Ust'-Dzheguta",
    "479687" => "Uchkeken",
    "552924" => "Karachayevsk",
    "569154" => "Cherkessk",
  );
}


function location_cities_list_ru_kem() {
  return array(
    "1485724" => "Yurga",
    "1486298" => "Yashkino",
    "1489394" => "Topki",
    "1489907" => "Tayga",
    "1490042" => "Tashtagol",
    "1494091" => "Promyshlennaya",
    "1494114" => "Prokop'yevsk",
    "1494456" => "Polysayevo",
    "1495974" => "Osinniki",
    "1496990" => "Novokuznetsk",
    "1498129" => "Myski",
    "1498920" => "Mezhdurechensk",
    "1499350" => "Mariinsk",
    "1500665" => "Leninsk-Kuznetskiy",
    "1503277" => "Kiselevsk",
    "1503901" => "Kemerovo",
    "1503940" => "Kedrovka",
    "1504972" => "Kaltan",
    "1506073" => "Gur'yevsk",
    "1510205" => "Berezovskiy",
    "1510469" => "Belovo",
    "1511494" => "Anzhero-Sudzhensk",
  );
}


function location_cities_list_ru_kha() {
  return array(
    "1499163" => "Mayma",
    "2013229" => "Vyazemskiy",
    "2021851" => "Komsomol'sk-na-Amure",
    "2022890" => "Khabarovsk",
    "2026696" => "Bikin",
    "2027749" => "Amursk",
    "2056752" => "Khabarovsk Vtoroy",
    "2119932" => "Vanino",
    "2121052" => "Sovetskaya Gavan'",
    "2122850" => "Nikolayevsk-na-Amure",
  );
}


function location_cities_list_ru_khm() {
  return array(
    "1488429" => "Uray",
    "1490624" => "Surgut",
    "1491230" => "Sovetskiy",
    "1494276" => "Poykovskiy",
    "1496476" => "Nyagan",
    "1497543" => "Nizhnevartovsk",
    "1497917" => "Nefteyugansk",
    "1499053" => "Megion",
    "1502725" => "Yugorsk",
    "1503772" => "Khanty-Mansiysk",
    "1510450" => "Beloyarskiy",
    "1540356" => "Raduzhnyy",
    "1541359" => "Lyantor",
    "6695754" => "Kogalym",
    "6696686" => "Pyt-Yakh",
    "6696767" => "Langepas",
    "7287775" => "Nizhnesortymskiy",
    "7289676" => "Pokachi",
    "7290697" => "Izluchinsk",
  );
}


function location_cities_list_ru_kir() {
  return array(
    "469005" => "Yaransk",
    "470734" => "Vyatskiye Polyany",
    "490067" => "Sovetsk",
    "491882" => "Slobodskoy",
    "515267" => "Omutninsk",
    "543737" => "Kotel'nich",
    "548395" => "Kirovo-Chepetsk",
    "548408" => "Kirov",
  );
}


function location_cities_list_ru_ko() {
  return array(
    "467525"  => "Yemva",
    "479411"  => "Ukhta",
    "485239"  => "Syktyvkar",
    "490391"  => "Sosnogorsk",
    "511794"  => "Pechora",
    "563379"  => "Ezhva",
    "863061"  => "Usinsk",
    "1486910" => "Vorkuta",
    "1486913" => "Vorgashor",
  );
}


function location_cities_list_ru_kos() {
  return array(
    "472750" => "Volgorechensk",
    "495619" => "Shar'ya",
    "522594" => "Nerekhta",
    "529505" => "Manturovo",
    "543878" => "Kostroma",
    "562161" => "Galich",
    "570508" => "Buy",
  );
}


function location_cities_list_ru_kda() {
  return array(
    "466885" => "Yeysk",
    "467854" => "Yelizavetinskaya",
    "470338" => "Vyselki",
    "478044" => "Ust'-Labinsk",
    "480716" => "Tuapse",
    "482965" => "Timashevsk",
    "483029" => "Tikhoretsk",
    "483661" => "Temryuk",
    "483883" => "Tbilisskaya",
    "488635" => "Staroshcherbinovskaya",
    "488742" => "Starominskaya",
    "491422" => "Sochi",
    "492094" => "Slavyansk-na-Kubani",
    "496267" => "Severskaya",
    "505259" => "Primorsko-Akhtarsk",
    "512051" => "Pavlovskaya",
    "512382" => "Pashkovskiy",
    "513911" => "Otradnaya",
    "517842" => "Novotitarovskaya",
    "518255" => "Novorossiysk",
    "518325" => "Novopokrovskaya",
    "518682" => "Novokubansk",
    "524809" => "Mostovskoy",
    "527968" => "Medvedovskaya",
    "536200" => "Leningradskaya",
    "536625" => "Lazarevskoye",
    "537281" => "Labinsk",
    "538416" => "Kushchevskaya",
    "538836" => "Kurganinsk",
    "539907" => "Kudepsta",
    "540251" => "Krymsk",
    "540761" => "Kropotkin",
    "542420" => "Krasnodar",
    "542461" => "Krasnoarmeyskaya",
    "544896" => "Korenovsk",
    "549424" => "Khosta",
    "549741" => "Kholmskiy",
    "550846" => "Khadyzhensk",
    "553152" => "Kanevskaya",
    "556951" => "Il'skiy",
    "558066" => "Gul'kevichi",
    "559317" => "Goryachiy Klyuch",
    "561667" => "Gelendzhik",
    "566181" => "Dinskaya",
    "571420" => "Bryukhovetskaya",
    "577893" => "Belorechensk",
    "578169" => "Belaya Glina",
    "580922" => "Armavir",
    "581313" => "Apsheronsk",
    "582182" => "Anapa",
    "583785" => "Akhtyrskiy",
    "584126" => "Afipskiy",
    "584243" => "Adler",
    "584441" => "Abinsk",
    "823674" => "Dagomys",
  );
}


function location_cities_list_ru_kya() {
  return array(
    "1485997" => "Yeniseysk",
    "1487882" => "Uzhur",
    "1488253" => "Zelenogorsk",
    "1490256" => "Talnakh",
    "1491291" => "Sosnovoborsk",
    "1491953" => "Shushenskoye",
    "1492401" => "Sharypovo",
    "1497337" => "Noril'sk",
    "1497951" => "Nazarovo",
    "1498693" => "Minusinsk",
    "1500607" => "Lesosibirsk",
    "1502026" => "Krasnoyarsk",
    "1503037" => "Kodinsk",
    "1504139" => "Kayyerkan",
    "1504682" => "Kansk",
    "1505933" => "Ilanskiy",
    "1507116" => "Dudinka",
    "1507379" => "Divnogorsk",
    "1508943" => "Borodino",
    "1509852" => "Bogotol",
    "1510255" => "Berezovka",
    "1512165" => "Achinsk",
    "1538635" => "Zheleznogorsk",
  );
}


function location_cities_list_ru_kgn() {
  return array(
    "1491999" => "Shumikha",
    "1492517" => "Shadrinsk",
    "1501255" => "Kurtamysh",
    "1501321" => "Kurgan",
    "1504212" => "Kataysk",
  );
}


function location_cities_list_ru_krs() {
  return array(
    "463343" => "Zheleznogorsk",
    "495206" => "Shchigry",
    "535334" => "L'govskiy",
    "538560" => "Kursk",
    "538908" => "Kurchatov",
    "695019" => "Ryl'sk",
  );
}


function location_cities_list_ru_len() {
  return array(
    "470546"  => "Vyborg",
    "471101"  => "Vsevolozhsk",
    "472722"  => "Volkhov",
    "481964"  => "Tosno",
    "483019"  => "Tikhvin",
    "485639"  => "Svetogorsk",
    "490172"  => "Sosnovyy Bor",
    "492162"  => "Slantsy",
    "496519"  => "Sertolovo",
    "500019"  => "Rybatskoye",
    "505230"  => "Priozersk",
    "508034"  => "Podporozh'ye",
    "509598"  => "Pikalevo",
    "513898"  => "Otradnoye",
    "521509"  => "Nikol'skoye",
    "533690"  => "Luga",
    "534560"  => "Lodeynoye Pole",
    "545788"  => "Kommunar",
    "548392"  => "Kirovsk",
    "548442"  => "Kirishi",
    "548602"  => "Kingisepp",
    "561887"  => "Gatchina",
    "575410"  => "Boksitogorsk",
    "8436165" => "Kurortnyy",
    "8504946" => "Chernaya Rechka",
    "8504947" => "Untolovo",
    "8504950" => "Parnas",
    "8504951" => "Kalininskiy",
    "8504955" => "Krestovskiy ostrov",
    "8504958" => "Akademicheskoe",
    "8504959" => "Finlyandskiy",
    "8504964" => "Svetlanovskiy",
    "8504965" => "Sampsonievskiy",
  );
}


function location_cities_list_ru_lip() {
  return array(
    "467978" => "Yelets",
    "478317" => "Usman'",
    "535121" => "Lipetsk",
    "536518" => "Lebedyan'",
    "558312" => "Gryazi",
    "567109" => "Dankov",
  );
}


function location_cities_list_ru_mag() {
  return array(
    "2123628" => "Magadan",
  );
}


function location_cities_list_ru_mow() {
  return array(
    "461740"  => "Zyuzino",
    "461835"  => "Zyablikovo",
    "462745"  => "Zhulebino",
    "463829"  => "Zelenograd",
    "465057"  => "Zamoskvorech'ye",
    "468809"  => "Yasenevo",
    "470451"  => "Vykhino-Zhulebino",
    "472072"  => "Altuf'yevskiy",
    "472079"  => "Vorob'yevo",
    "472732"  => "Nagornyy",
    "473021"  => "Vnukovo",
    "473127"  => "Novovladykino",
    "473972"  => "Veshnyaki",
    "476368"  => "Vatutino",
    "477377"  => "Vagonoremont",
    "481453"  => "Troparevo",
    "483551"  => "Teplyy Stan",
    "483826"  => "Tekstil'shchiki",
    "484912"  => "Taganskiy",
    "485630"  => "Sviblovo",
    "487150"  => "Strogino",
    "490971"  => "Solntsevo",
    "491250"  => "Sokol'niki",
    "491280"  => "Sokol",
    "491895"  => "Slobodka",
    "495136"  => "Shchukino",
    "496348"  => "Severnyy",
    "496456"  => "Setun'",
    "500843"  => "Rublevo",
    "501187"  => "Rostokino",
    "502971"  => "Ramenki",
    "506043"  => "Kotlovka",
    "506117"  => "Annino",
    "507338"  => "Pokrovskoye-Streshnevo",
    "508751"  => "Ryazanskiy",
    "511153"  => "Perovo",
    "511510"  => "Novo-Peredelkino",
    "513896"  => "Otradnoye",
    "514284"  => "Ostankinskiy",
    "515027"  => "Orekhovo-Borisovo Severnoye",
    "516264"  => "Ochakovo-Matveyevskoye",
    "517121"  => "Novyye Kuz'minki",
    "517161"  => "Novyye Cheremushki",
    "518657"  => "Novokuz'minki",
    "518740"  => "Novokhovrino",
    "521416"  => "Nikulino",
    "521500"  => "Nikol'skoye",
    "524901"  => "Moscow",
    "527057"  => "Mikhalkovo",
    "528454"  => "Matveyevskoye",
    "529237"  => "Mar'ino",
    "529334"  => "Mar'ina Roshcha",
    "530088"  => "Yaroslavskiy",
    "532535"  => "Lyublino",
    "533067"  => "Luzhniki",
    "535270"  => "Likhobory",
    "535330"  => "Lianozovo",
    "535966"  => "Leonovo",
    "536164"  => "Tsaritsyno",
    "536398"  => "Lefortovo",
    "537832"  => "Kuz'minki",
    "543344"  => "Kozeyevo",
    "546244"  => "Kolomenskoye",
    "550280"  => "Khimki",
    "553034"  => "Kapotnya",
    "555129"  => "Ivanovskoye",
    "560465"  => "Gol'yanovo",
    "566809"  => "Zapadnoye Degunino",
    "566976"  => "Davydkovo",
    "570636"  => "Businovo",
    "571741"  => "Brateyevo",
    "576279"  => "Biryulevo",
    "576432"  => "Bibirevo",
    "579870"  => "Babushkin",
    "582266"  => "Amin'yevo",
    "6418146" => "Chertanovo Yuzhnoye",
    "6418201" => "Zagor'ye",
    "6418220" => "Orekhovo-Borisovo",
    "6418787" => "Metrogorodok",
  );
}


function location_cities_list_ru_mos() {
  return array(
    "461920"  => "Zvenigorod",
    "462755"  => "Zhukovskiy",
    "463355"  => "Zheleznodorozhnyy",
    "464687"  => "Zaraysk",
    "468250"  => "Yegor'yevsk",
    "471456"  => "Vostryakovo",
    "471457"  => "Vostryakovo",
    "471656"  => "Voskresensk",
    "472433"  => "Volokolamsk",
    "473778"  => "Vidnoye",
    "480685"  => "Tuchkovo",
    "481608"  => "Troitsk",
    "482260"  => "Tomilino",
    "486968"  => "Stupino",
    "489162"  => "Staraya Kupavna",
    "490996"  => "Solnechnogorsk",
    "491351"  => "Sofrino",
    "492448"  => "Skhodnya",
    "495260"  => "Shcherbinka",
    "495344"  => "Shchelkovo",
    "495518"  => "Shatura",
    "496527"  => "Serpukhov",
    "496638"  => "Sergiyev Posad",
    "497271"  => "Semenovskoye",
    "501320"  => "Roshal'",
    "502018"  => "Reutov",
    "503977"  => "Pushkino",
    "504042"  => "Pushchino",
    "504576"  => "Protvino",
    "508101"  => "Podol'sk",
    "509981"  => "Petrovskaya",
    "512023"  => "Pavlovskiy Posad",
    "513378"  => "Ozery",
    "515024"  => "Orekhovo-Zuyevo",
    "516215"  => "Odintsovo",
    "518879"  => "Novogireyevo",
    "520068"  => "Noginsk",
    "523426"  => "Naro-Fominsk",
    "523553"  => "Nakhabino",
    "523812"  => "Mytishchi",
    "524712"  => "Mozhaysk",
    "525396"  => "Monino",
    "531820"  => "Malakhovka",
    "532615"  => "Lyubertsy",
    "532657"  => "Lytkarino",
    "533543"  => "Lukhovitsy",
    "534015"  => "Losino-Petrovskiy",
    "534595"  => "Lobnya",
    "535243"  => "Likino-Dulevo",
    "535451"  => "Levoberezhnaya",
    "536098"  => "Leninskiye Gory",
    "536206"  => "Yubileyny",
    "538321"  => "Kuskovo",
    "538472"  => "Kur'yanovo",
    "538601"  => "Kurovskoye",
    "540030"  => "Kubinka",
    "541406"  => "Biryulevo Zapadnoye",
    "542374"  => "Krasnogorsk",
    "542463"  => "Krasnoarmeysk",
    "542634"  => "Presnenskiy",
    "543254"  => "Kozhukhovo",
    "543731"  => "Kotel'niki",
    "546230"  => "Kolomna",
    "547523"  => "Klin",
    "547560"  => "Klimovsk",
    "549373"  => "Khot'kovo",
    "549479"  => "Khoroshevo-Mnevniki",
    "551835"  => "Kastanayevo",
    "551964"  => "Kashira",
    "554233"  => "Korolev",
    "554787"  => "Izmaylovo",
    "555111"  => "Ivanteyevka",
    "555746"  => "Istra",
    "560756"  => "Golitsyno",
    "562319"  => "Fryazino",
    "562321"  => "Fryazevo",
    "562820"  => "Fili",
    "563522"  => "Elektrougli",
    "563523"  => "Elektrostal'",
    "563524"  => "Elektrogorsk",
    "563705"  => "Dzerzhinskiy",
    "564719"  => "Dubna",
    "565197"  => "Dorogomilovo",
    "565381"  => "Domodedovo",
    "565614"  => "Dolgoprudnyy",
    "565955"  => "Dmitrov",
    "566854"  => "Dedovsk",
    "568808"  => "Chernogolovka",
    "569273"  => "Cheremushki",
    "569591"  => "Chekhov",
    "571557"  => "Bronnitsy",
    "574675"  => "Bol'shaya Setun'",
    "575505"  => "Bogorodskoye",
    "577901"  => "Beloozerskiy",
    "579464"  => "Balashikha",
    "581321"  => "Aprelevka",
    "581928"  => "Andreyevskoye",
    "582846"  => "Alekseyevka",
    "583589"  => "Levoberezhnyy",
    "819552"  => "Annino",
    "857689"  => "Vnukovo",
    "857690"  => "Moskovskiy",
    "6417459" => "Krasnoznamensk",
    "7117880" => "Zarya",
    "8505053" => "Vostochnoe Degunino",
  );
}


function location_cities_list_ru_mur() {
  return array(
    "464790" => "Zapolyarnyy",
    "496278" => "Severomorsk",
    "506762" => "Polyarnyye Zori",
    "506763" => "Polyarnyy",
    "515698" => "Olenegorsk",
    "522260" => "Nikel'",
    "524305" => "Murmansk",
    "525404" => "Monchegorsk",
    "543508" => "Kovdor",
    "548391" => "Kirovsk",
    "553190" => "Kandalaksha",
    "581357" => "Apatity",
  );
}


function location_cities_list_ru_nen() {
  return array(
    "523392" => "Nar'yan-Mar",
  );
}


function location_cities_list_ru_niz() {
  return array(
    "464101" => "Zavolzh'ye",
    "470444" => "Vyksa",
    "496012" => "Shakhun'ya",
    "496802" => "Sergach",
    "497450" => "Semenov",
    "498525" => "Sarov",
    "520555" => "Nizhniy Novgorod",
    "523198" => "Navashino",
    "532715" => "Lyskovo",
    "539555" => "Kulebaki",
    "540103" => "Kstovo",
    "559678" => "Gorodets",
    "563708" => "Dzerzhinsk",
    "572665" => "Bor",
    "575560" => "Bogorodsk",
    "579514" => "Novaya Balakhna",
    "580724" => "Arzamas",
    "827329" => "Pavlovo",
  );
}


function location_cities_list_ru_se() {
  return array(
    "473249" => "Vladikavkaz",
    "524736" => "Mozdok",
    "576697" => "Beslan",
    "581179" => "Ardon",
    "802078" => "Alagir",
  );
}


function location_cities_list_ru_ngr() {
  return array(
    "477301" => "Valday",
    "489088" => "Staraya Russa",
    "510364" => "Pestovo",
    "519336" => "Velikiy Novgorod",
    "567774" => "Chudovo",
    "572154" => "Borovichi",
  );
}


function location_cities_list_ru_nvs() {
  return array(
    "1489508" => "Toguchin",
    "1490003" => "Tatarsk",
    "1490551" => "Suzun",
    "1496421" => "Ob'",
    "1496747" => "Novosibirsk",
    "1500532" => "Linevo",
    "1501141" => "Kuybyshev",
    "1501365" => "Kupino",
    "1502091" => "Krasnoobsk",
    "1503082" => "Kochenevo",
    "1504489" => "Karasuk",
    "1505429" => "Iskitim",
    "1508161" => "Cherepanovo",
    "1509819" => "Bolotnoye",
    "1510350" => "Berdsk",
    "1510916" => "Barabinsk",
    "1512086" => "Akademgorodok",
  );
}


function location_cities_list_ru_oms() {
  return array(
    "1490140" => "Tara",
    "1496153" => "Omsk",
    "1505074" => "Kalachinsk",
  );
}


function location_cities_list_ru_ore() {
  return array(
    "468657" => "Yasnyy",
    "490554" => "Sorochinsk",
    "491019" => "Sol'-Iletsk",
    "498708" => "Saraktash",
    "514734" => "Orsk",
    "515003" => "Orenburg",
    "517836" => "Novotroitsk",
    "528109" => "Mednogorsk",
    "538138" => "Kuvandyk",
    "561731" => "Gay",
    "570427" => "Buzuluk",
    "571159" => "Buguruslan",
    "584471" => "Abdulino",
  );
}


function location_cities_list_ru_orl() {
  return array(
    "515012" => "Orel",
    "524640" => "Mtsensk",
    "534701" => "Livny",
  );
}


function location_cities_list_ru_pnz() {
  return array(
    "464625" => "Zarechnyy",
    "496934" => "Serdobsk",
    "511565" => "Penza",
    "520574" => "Nizhniy Lomov",
    "521776" => "Nikol'sk",
    "537737" => "Kuznetsk",
    "831165" => "Zarechnyy",
  );
}


function location_cities_list_ru_per() {
  return array(
    "475777" => "Vereshchagino",
    "491023" => "Solikamsk",
    "511196" => "Perm'",
    "514706" => "Osa",
    "516256" => "Ocher",
    "516576" => "Nytva",
    "532675" => "Lys'va",
    "539147" => "Kungur",
    "539817" => "Kudymkar",
    "542184" => "Krasnovishersk",
    "542327" => "Krasnokamsk",
    "547875" => "Kizel",
    "558209" => "Gubakha",
    "565778" => "Dobryanka",
    "567434" => "Chusovoy",
    "568608" => "Chernushka",
    "569742" => "Chaykovskiy",
    "577206" => "Berezniki",
    "583041" => "Aleksandrovsk",
  );
}


function location_cities_list_ru_pri() {
  return array(
    "2013258" => "Vrangel'",
    "2013348" => "Vladivostok",
    "2014006" => "Ussuriysk",
    "2015051" => "Trudovoye",
    "2015310" => "Fokino",
    "2016187" => "Spassk-Dal'niy",
    "2018116" => "Partizansk",
    "2019528" => "Nakhodka",
    "2020689" => "Luchegorsk",
    "2020812" => "Lesozavodsk",
    "2023058" => "Kavalerovo",
    "2025159" => "Dal'nerechensk",
    "2026303" => "Bol'shoy Kamen'",
    "2027456" => "Artem",
    "2027468" => "Arsen'yev",
    "2051471" => "Dal'negorsk",
  );
}


function location_cities_list_ru_psk() {
  return array(
    "476077" => "Velikiye Luki",
    "504341" => "Pskov",
    "514171" => "Ostrov",
    "522410" => "Nevel'",
  );
}


function location_cities_list_ru_ad() {
  return array(
    "469844" => "Yablonovskiy",
    "528293" => "Maykop",
    "561515" => "Giaginskaya",
    "563472" => "Enem",
  );
}


function location_cities_list_ru_al() {
  return array(
    "1506271" => "Gorno-Altaysk",
  );
}


function location_cities_list_ru_bu() {
  return array(
    "2014407" => "Ulan-Ude",
    "2016910" => "Severobaykal'sk",
    "2021066" => "Kyakhta",
    "2023782" => "Gusinoozersk",
  );
}


function location_cities_list_ru_in() {
  return array(
    "481605" => "Troitskaya",
    "486110" => "Surkhakhi",
    "515083" => "Ordzhonikidzevskaya",
    "522470" => "Nesterovskaya",
    "523064" => "Nazran'",
    "531129" => "Malgobek",
    "552951" => "Karabulak",
    "553092" => "Kantyshevo",
    "563551" => "Ekazhevo",
    "874045" => "Staryy Malgobek",
  );
}


function location_cities_list_ru_kr() {
  return array(
    "490466" => "Sortavala",
    "497927" => "Segezha",
    "509820" => "Petrozavodsk",
    "527888" => "Medvezh'yegorsk",
    "543899" => "Kostomuksha",
    "545626" => "Kondopoga",
  );
}


function location_cities_list_ru_kk() {
  return array(
    "1492893" => "Sayanogorsk",
    "1508054" => "Chernogorsk",
    "1512205" => "Abaza",
    "1512236" => "Abakan",
  );
}


function location_cities_list_ru_me() {
  return array(
    "466806" => "Yoshkar-Ola",
    "472234" => "Volzhsk",
    "528056" => "Medvedevo",
    "543018" => "Koz'modem'yansk",
  );
}


function location_cities_list_ru_mo() {
  return array(
    "498698" => "Saransk",
    "500299" => "Ruzayevka",
    "543436" => "Kovylkino",
  );
}


function location_cities_list_ru_sa() {
  return array(
    "2013159" => "Yakutsk",
    "2014624" => "Udachny",
    "2019309" => "Neryungri",
    "2019951" => "Mirny",
    "2020838" => "Lensk",
    "2027296" => "Aykhal",
    "2027968" => "Aldan",
  );
}


function location_cities_list_ru_ty() {
  return array(
    "1500973" => "Kyzyl",
  );
}


function location_cities_list_ru_ros() {
  return array(
    "461910" => "Zverevo",
    "462522" => "Zimovniki",
    "463637" => "Zernograd",
    "468307" => "Yegorlykskaya",
    "472761" => "Volgodonsk",
    "480876" => "Tsimlyansk",
    "484907" => "Taganrog",
    "496015" => "Shakhty",
    "497218" => "Semikarakorsk",
    "499161" => "Sal'sk",
    "501175" => "Rostov-na-Donu",
    "504831" => "Proletarsk",
    "514796" => "Orlovskiy",
    "517963" => "Novoshakhtinsk",
    "518970" => "Novocherkassk",
    "525162" => "Morozovsk",
    "526558" => "Millerovo",
    "541404" => "Krasnyy Sulin",
    "545277" => "Konstantinovsk",
    "553399" => "Kamensk-Shakhtinskiy",
    "558082" => "Gukovo",
    "565348" => "Donetsk",
    "578155" => "Belaya Kalitva",
    "578740" => "Bataysk",
    "579771" => "Bagayevskaya",
    "580054" => "Azov",
    "583673" => "Aksay",
    "802714" => "Persianovka",
  );
}


function location_cities_list_ru_rya() {
  return array(
    "461699" => "Sasovo",
    "492376" => "Skopin",
    "494427" => "Shilovo",
    "499975" => "Rybnoye",
    "500047" => "Ryazhsk",
    "500096" => "Ryazan'",
    "518602" => "Novomichurinsk",
    "551891" => "Kasimov",
  );
}


function location_cities_list_ru_sak() {
  return array(
    "2119441" => "Yuzhno-Sakhalinsk",
    "2121909" => "Poronaysk",
    "2122614" => "Okha",
    "2122894" => "Nevel'sk",
    "2124286" => "Korsakov",
    "2124615" => "Kholmsk",
  );
}


function location_cities_list_ru_sam() {
  return array(
    "463082" => "Zhigulevsk",
    "482283" => "Tol'yatti",
    "484972" => "Syzran'",
    "499099" => "Samara",
    "507624" => "Pokhvistnevo",
    "513883" => "Otradnyy",
    "518659" => "Novokuybyshevsk",
    "522945" => "Neftegorsk",
    "548622" => "Kinel'-Cherkassy",
    "548625" => "Kinel'",
    "569955" => "Chapayevsk",
    "576590" => "Bezenchuk",
  );
}


function location_cities_list_ru_sar() {
  return array(
    "467120" => "Yershov",
    "472278" => "Vol'sk",
    "498677" => "Saratov",
    "500886" => "Rtishchevo",
    "505057" => "Privolzhskiy",
    "509987" => "Petrovsk",
    "517739" => "Novouzensk",
    "529073" => "Marks",
    "542464" => "Krasnoarmeysk",
    "554199" => "Kalininsk",
    "563464" => "Engel's",
    "579460" => "Balashov",
    "579492" => "Balakovo",
    "580420" => "Atkarsk",
  );
}


function location_cities_list_ru_smo() {
  return array(
    "468866" => "Yartsevo",
    "470676" => "Vyaz'ma",
    "491687" => "Smolensk",
    "499452" => "Safonovo",
    "501283" => "Roslavl'",
    "562237" => "Gagarin",
    "566384" => "Desnogorsk",
  );
}


function location_cities_list_ru_spe() {
  return array(
    "461698"  => "Sosnovka",
    "478724"  => "Uritsk",
    "489226"  => "Staraya Derevnya",
    "490377"  => "Sosnovaya Polyana",
    "493316"  => "Shushary",
    "496478"  => "Sestroretsk",
    "498817"  => "Saint Petersburg",
    "504003"  => "Pushkin",
    "510225"  => "Petrodvorets",
    "510291"  => "Peterhof",
    "512052"  => "Pavlovsk",
    "513471"  => "Ozerki",
    "519711"  => "Novaya Derevnya",
    "527361"  => "Metallostroy",
    "534341"  => "Lomonosov",
    "535729"  => "Komendantsky aerodrom",
    "539061"  => "Kupchino",
    "540771"  => "Kronshtadt",
    "542000"  => "Krasnoye Selo",
    "546105"  => "Kolpino",
    "546225"  => "Kolomyagi",
    "559029"  => "Grazhdanka",
    "560142"  => "Gorelovo",
    "567311"  => "Dachnoye",
    "580222"  => "Avtovo",
    "873901"  => "Obukhovo",
    "8504948" => "Petrogradka",
    "8504949" => "Vasyl'evsky Ostrov",
    "8504952" => "Krasnogvargeisky",
    "8504953" => "Admiralteisky",
    "8504960" => "Centralniy",
  );
}


function location_cities_list_ru_sta() {
  return array(
    "463340" => "Zheleznovodsk",
    "463824" => "Zelenokumsk",
    "466989" => "Yessentukskaya",
    "466990" => "Yessentuki",
    "485432" => "Svobody",
    "485698" => "Svetlograd",
    "485871" => "Suvorovskaya",
    "487846" => "Stavropol'",
    "493702" => "Mikhaylovsk",
    "503550" => "Pyatigorsk",
    "518383" => "Novopavlovsk",
    "519106" => "Novoaleksandrovsk",
    "522301" => "Nezlobnaya",
    "522377" => "Nevinnomyssk",
    "526480" => "Mineral'nyye Vody",
    "535886" => "Lermontov",
    "542334" => "Krasnogvardeyskoye",
    "548114" => "Kislovodsk",
    "556230" => "Ipatovo",
    "556320" => "Inozemtsevo",
    "559320" => "Goryachevodskiy",
    "561627" => "Georgiyevsk",
    "565289" => "Donskoye",
    "566155" => "Divnoye",
    "571306" => "Budennovsk",
    "576172" => "Blagodarnyy",
    "580716" => "Arzgir",
    "582993" => "Aleksandrovskoye",
    "797781" => "Neftekumsk",
    "841006" => "Kochubeyevskoye",
  );
}


function location_cities_list_ru_sve() {
  return array(
    "496275"  => "Severoural'sk",
    "502011"  => "Revda",
    "510808"  => "Pervoural'sk",
    "520204"  => "Nizhnyaya Tura",
    "520494"  => "Nizhniy Tagil",
    "538340"  => "Kushva",
    "542199"  => "Krasnoufimsk",
    "554599"  => "Kachkanar",
    "829005"  => "Lesnoy",
    "1485445" => "Zarechnyy",
    "1486209" => "Yekaterinburg",
    "1487277" => "Verkhnyaya Salda",
    "1487281" => "Verkhnyaya Pyshma",
    "1488933" => "Turinsk",
    "1489962" => "Tavda",
    "1490277" => "Talitsa",
    "1490281" => "Talitsa",
    "1490402" => "Sysert'",
    "1490686" => "Sukhoy Log",
    "1491159" => "Sredneural'sk",
    "1492663" => "Serov",
    "1493648" => "Rezh",
    "1493687" => "Reftinskiy",
    "1494573" => "Polevskoy",
    "1497393" => "Nizhnyaya Salda",
    "1497795" => "Nev'yansk",
    "1502060" => "Krasnoural'sk",
    "1502061" => "Krasnotur'insk",
    "1503335" => "Kirovgrad",
    "1504343" => "Karpinsk",
    "1504769" => "Kamyshlov",
    "1504826" => "Kamensk-Ural'skiy",
    "1505260" => "Ivdel'",
    "1505526" => "Irbit",
    "1507488" => "Degtyarsk",
    "1509888" => "Bogdanovich",
    "1510203" => "Berezovskiy",
    "1511330" => "Asbest",
    "1511368" => "Artemovskiy",
    "1511466" => "Aramil'",
    "1511954" => "Alapayevsk",
    "1538636" => "Novoural'sk",
    "6853140" => "Lesnoy",
  );
}


function location_cities_list_ru_tam() {
  return array(
    "463217" => "Zherdevka",
    "477626" => "Uvarovo",
    "484646" => "Tambov",
    "502793" => "Rasskazovo",
    "525138" => "Morshansk",
    "527191" => "Michurinsk",
    "543605" => "Kotovsk",
    "548330" => "Kirsanov",
  );
}


function location_cities_list_ru_ta() {
  return array(
    "463835" => "Zelenodol'sk",
    "465543" => "Zainsk",
    "468082" => "Yelabuga",
    "516716" => "Nurlat",
    "521118" => "Nizhnekamsk",
    "523750" => "Naberezhnyye Chelny",
    "527529" => "Menzelinsk",
    "527579" => "Mendeleyevsk",
    "536162" => "Leninogorsk",
    "539689" => "Kukmor",
    "551487" => "Kazan",
    "567990" => "Chistopol'",
    "571155" => "Buinsk",
    "571170" => "Bugul'ma",
    "578638" => "Bavly",
    "580850" => "Arsk",
    "582432" => "Al'met'yevsk",
    "583983" => "Agryz",
    "611182" => "Vasil'yevo",
  );
}


function location_cities_list_ru_tom() {
  return array(
    "1489425" => "Tomsk",
    "1490796" => "Strezhevoy",
    "1502862" => "Kolpashevo",
    "1511309" => "Asino",
    "1538637" => "Seversk",
  );
}


function location_cities_list_ru_tul() {
  return array(
    "468390" => "Yefremov",
    "468671" => "Yasnogorsk",
    "475881" => "Venev",
    "477494" => "Uzlovaya",
    "480562" => "Tula",
    "485888" => "Suvorov",
    "495394" => "Shchekino",
    "496269" => "Severo-Zadonsk",
    "509052" => "Plavsk",
    "518557" => "Novomoskovsk",
    "544293" => "Kosaya Gora",
    "548506" => "Kireyevsk",
    "548658" => "Kimovsk",
    "565290" => "Donskoy",
    "575591" => "Bogoroditsk",
    "578091" => "Belev",
    "582750" => "Aleksin",
  );
}


function location_cities_list_ru_tve() {
  return array(
    "452949" => "Udomlya",
    "470252" => "Vyshniy Volochek",
    "480060" => "Tver",
    "481985" => "Torzhok",
    "499717" => "Rzhev",
    "514259" => "Ostashkov",
    "522775" => "Nelidovo",
    "545673" => "Konakovo",
    "548652" => "Kimry",
    "551986" => "Kashin",
    "575349" => "Bologoye",
    "576566" => "Bezhetsk",
  );
}


function location_cities_list_ru_tyu() {
  return array(
    "1485357" => "Zavodoukovsk",
    "1486468" => "Yalutorovsk",
    "1488754" => "Tyumen",
    "1489530" => "Tobol'sk",
    "1505453" => "Ishim",
    "1508879" => "Borovskiy",
  );
}


function location_cities_list_ru_ud() {
  return array(
    "471430" => "Votkinsk",
    "477656" => "Uva",
    "498687" => "Sarapul",
    "524699" => "Mozhga",
    "554840" => "Izhevsk",
    "557469" => "Igra",
    "561347" => "Glazov",
    "579432" => "Balezino",
  );
}


function location_cities_list_ru_uly() {
  return array(
    "479123" => "Ulyanovsk",
    "517766" => "Novoul'yanovsk",
    "556283" => "Inza",
    "566199" => "Dimitrovgrad",
    "578931" => "Barysh",
  );
}


function location_cities_list_ru_vla() {
  return array(
    "466215"  => "Yur'yev-Pol'skiy",
    "470666"  => "Vyazniki",
    "473247"  => "Vladimir",
    "487095"  => "Strunino",
    "491480"  => "Sobinka",
    "507599"  => "Pokrov",
    "509697"  => "Petushki",
    "524294"  => "Murom",
    "527740"  => "Melenki",
    "537107"  => "Lakinsk",
    "543460"  => "Kovrov",
    "546521"  => "Kol'chugino",
    "548278"  => "Kirzhach",
    "552977"  => "Karabanovo",
    "557775"  => "Gus'-Khrustal'nyy",
    "582978"  => "Aleksandrow",
    "583350"  => "Aleksandrov",
    "7117885" => "Raduzhnyy",
  );
}


function location_cities_list_ru_vgg() {
  return array(
    "462984" => "Zhirnovsk",
    "468063" => "Yelan'",
    "472231" => "Volzhskiy",
    "472757" => "Volgograd",
    "478544" => "Uryupinsk",
    "486071" => "Surovikino",
    "513042" => "Pallasovka",
    "519062" => "Novoanninskiy",
    "521874" => "Nikolayevsk",
    "527012" => "Mikhaylovka",
    "536156" => "Leninsk",
    "543633" => "Kotovo",
    "543728" => "Kotel'nikovo",
    "553287" => "Kamyshin",
    "554397" => "Kalach-na-Donu",
    "559654" => "Gorodishche",
    "562389" => "Frolovo",
    "564654" => "Dubovka",
  );
}


function location_cities_list_ru_vlg() {
  return array(
    "472459" => "Vologda",
    "476062" => "Velikiy Ustyug",
    "491281" => "Sokol",
    "495062" => "Sheksna",
    "558236" => "Gryazovets",
    "569223" => "Cherepovets",
  );
}


function location_cities_list_ru_vor() {
  return array(
    "472045" => "Voronezh",
    "497206" => "Semiluki",
    "501215" => "Rossosh'",
    "501231" => "Rossosh'",
    "505421" => "Pridonskoy",
    "505806" => "Povorino",
    "512053" => "Pavlovsk",
    "514198" => "Ostrogozhsk",
    "517716" => "Novovoronezh",
    "519447" => "Novaya Usman'",
    "534838" => "Liski",
    "554410" => "Kalach",
    "558799" => "Gribanovskiy",
    "570563" => "Buturlinovka",
    "572525" => "Borisoglebsk",
    "575457" => "Boguchar",
    "575948" => "Bobrov",
    "581671" => "Anna",
  );
}


function location_cities_list_ru_yan() {
  return array(
    "1490085" => "Tarko-Sale",
    "1493197" => "Salekhard",
    "1496503" => "Noyabr'sk",
    "1496511" => "Novyy Urengoy",
    "1498087" => "Nadym",
    "1500933" => "Labytnangi",
    "1539209" => "Gubkinskiy",
    "1540711" => "Muravlenko",
  );
}


function location_cities_list_ru_yar() {
  return array(
    "468902" => "Yaroslavl",
    "479532" => "Uglich",
    "480122" => "Tutayev",
    "500004" => "Rybinsk",
    "501183" => "Rostov",
    "511359" => "Pereslavl'-Zalesskiy",
    "561762" => "Gavrilov-Yam",
    "567183" => "Danilov",
  );
}


function location_cities_list_ru_zab() {
  return array(
    "2017945" => "Petrovsk-Zabaykal'skiy",
    "2019326" => "Nerchinsk",
    "2021618" => "Krasnokamensk",
    "2025339" => "Chita",
    "2026126" => "Borzya",
  );
}
