<?php


function location_cities_list_bn_be() {
  return array(
    "1820187" => t("Seria"),
    "1820491" => t("Kuala Belait"),
  );
}


function location_cities_list_bn_bm() {
  return array(
    "1820906" => t("Bandar Seri Begawan"),
  );
}


function location_cities_list_bn_te() {
  return array();
}


function location_cities_list_bn_tu() {
  return array(
    "1820071" => t("Tutong"),
  );
}
