<?php


function location_cities_list_bo_h () {
	return array (
		"3903987" => t("Sucre"),
	);
}


function location_cities_list_bo_c () {
	return array (
		"3907080" => t("Punata"),
		"3910291" => t("Mizque"),
		"3919968" => t("Cochabamba"),
	);
}


function location_cities_list_bo_l () {
	return array (
		"3911925" => t("La Paz"),
	);
}


function location_cities_list_bo_n () {
	return array (
		"3919998" => t("Cobija"),
	);
}


function location_cities_list_bo_p () {
	return array (
		"3901501" => t("Villazon"),
		"3902202" => t("Tupiza"),
		"3907584" => t("Potosi"),
		"3911409" => t("Llallagua"),
	);
}


function location_cities_list_bo_s () {
	return array (
		"3901301" => t("Warnes"),
		"3901504" => t("Villa Yapacani"),
		"3904666" => t("Santiago del Torno"),
		"3904906" => t("Santa Cruz de la Sierra"),
		"3905658" => t("San Ignacio de Velasco"),
		"3910027" => t("Montero"),
		"3918937" => t("Cotoca"),
		"3922414" => t("Camiri"),
	);
}


function location_cities_list_bo_t () {
	return array (
		"3901178" => t("Yacuiba"),
		"3901547" => t("Villamontes"),
		"3903320" => t("Tarija"),
	);
}


function location_cities_list_bo_b () {
	return array (
		"3902377" => t("La Santisima Trinidad"),
		"3905792" => t("San Borja"),
		"3906466" => t("Riberalta"),
		"3915350" => t("Guayaramerin"),
	);
}


function location_cities_list_bo_o () {
	return array (
		"3909234" => t("Oruro"),
		"3914839" => t("Huanuni"),
	);
}
