<?php

function location_cities_list_gh_ah () {
	return array (
		"2294938" => t("Tafo"),
		"2296606" => t("Obuasi"),
		"2298890" => t("Kumasi"),
	);
}


function location_cities_list_gh_ba () {
	return array (
		"2294086" => t("Wenchi"),
		"2294727" => t("Techiman"),
		"2295021" => t("Sunyani"),
	);
}


function location_cities_list_gh_cp () {
	return array (
		"2294034" => t("Winneba"),
		"2294962" => t("Swedru"),
		"2301190" => t("Elmina"),
		"2302357" => t("Cape Coast"),
	);
}


function location_cities_list_gh_ep () {
	return array (
		"2299522" => t("Koforidua"),
		"2306119" => t("Aburi"),
	);
}


function location_cities_list_gh_aa () {
	return array (
		"2294665" => t("Teshi Old Town"),
		"2294700" => t("Tema"),
		"2296969" => t("Nungua"),
		"2298330" => t("Medina Estates"),
		"2300721" => t("Gbawe"),
		"2301639" => t("Dome"),
		"2306079" => t("Achiaman"),
		"2306104" => t("Accra"),
	);
}


function location_cities_list_gh_np () {
	return array (
		"2293801" => t("Yendi"),
		"2294877" => t("Tamale"),
		"2295517" => t("Savelugu"),
	);
}


function location_cities_list_gh_ue () {
	return array (
		"2297505" => t("Navrongo"),
		"2302821" => t("Bolgatanga"),
		"2303287" => t("Bawku"),
	);
}


function location_cities_list_gh_uw () {
	return array (
		"2294206" => t("Wa"),
	);
}


function location_cities_list_gh_tv () {
	return array (
		"2299645" => t("Keta"),
		"2300379" => t("Ho"),
		"2304548" => t("Anloga"),
	);
}


function location_cities_list_gh_wp () {
	return array (
		"2294915" => t("Takoradi"),
		"2295458" => t("Sekondi-Takoradi"),
		"2303611" => t("Axim"),
	);
}
