<?php

function location_cities_list_hn_ib () {
	return array (
	);
}


function location_cities_list_hn_at () {
	return array (
		"3600931" => t("Tela"),
		"3608248" => t("La Ceiba"),
	);
}


function location_cities_list_hn_ch () {
	return array (
		"3613528" => t("Ciudad Choluteca"),
	);
}


function location_cities_list_hn_cl () {
	return array (
		"3600704" => t("Tocoa"),
	);
}


function location_cities_list_hn_cm () {
	return array (
		"3601311" => t("Siguatepeque"),
		"3613321" => t("Comayagua"),
	);
}


function location_cities_list_hn_cp () {
	return array (
		"3601494" => t("Santa Rosa de Copan"),
	);
}


function location_cities_list_hn_cr () {
	return array (
		"3600026" => t("Puerto Cortez"),
		"3600327" => t("Villanueva"),
		"3601782" => t("San Pedro Sula"),
		"3603330" => t("Potrerillos"),
		"3607511" => t("La Lima"),
		"3613394" => t("Cofradia"),
		"3613533" => t("Choloma"),
	);
}


function location_cities_list_hn_ep () {
	return array (
		"3610965" => t("El Paraiso"),
		"3612907" => t("Danli"),
	);
}


function location_cities_list_hn_fm () {
	return array (
		"3600949" => t("Tegucigalpa"),
	);
}


function location_cities_list_hn_gd () {
	return array (
	);
}


function location_cities_list_hn_in () {
	return array (
	);
}


function location_cities_list_hn_lp () {
	return array (
		"3607254" => t("La Paz"),
	);
}


function location_cities_list_hn_le () {
	return array (
	);
}


function location_cities_list_hn_oc () {
	return array (
	);
}


function location_cities_list_hn_ol () {
	return array (
		"3608503" => t("Juticalpa"),
	);
}


function location_cities_list_hn_sb () {
	return array (
		"3601691" => t("Santa Barbara"),
	);
}


function location_cities_list_hn_va () {
	return array (
		"3601977" => t("San Lorenzo"),
	);
}


function location_cities_list_hn_yo () {
	return array (
		"3600195" => t("Yoro"),
		"3604251" => t("Olanchito"),
		"3610613" => t("El Progreso"),
	);
}
