<?php

function location_cities_list_tr_01 () {
	return array (
		"306112" => t("Kozan"),
		"310892" => t("Kadirli"),
		"311453" => t("Imamoglu"),
		"318675" => t("Ceyhan"),
		"322391" => t("Bahce"),
		"325363" => t("Adana"),
	);
}


function location_cities_list_tr_02 () {
	return array (
		"310855" => t("Kahta"),
		"314136" => t("Golbasi"),
		"321337" => t("Besni"),
		"325330" => t("Adiyaman"),
	);
}


function location_cities_list_tr_03 () {
	return array (
		"301911" => t("Sandikli"),
		"315621" => t("Emirdag"),
		"316634" => t("Dinar"),
		"319104" => t("Cay"),
		"320879" => t("Bolvadin"),
		"325303" => t("Afyonkarahisar"),
	);
}


function location_cities_list_tr_68 () {
	return array (
		"303290" => t("Ortakoy"),
		"324496" => t("Aksaray"),
	);
}


function location_cities_list_tr_05 () {
	return array (
		"739015" => t("Tasova"),
		"739251" => t("Suluova"),
		"741609" => t("Merzifon"),
		"752015" => t("Amasya"),
	);
}


function location_cities_list_tr_06 () {
	return array (
		"301116" => t("Sereflikochisar"),
		"302525" => t("Polatli"),
		"315720" => t("Elmadag"),
		"323786" => t("Ankara"),
		"442301" => t("Batikent"),
		"741347" => t("Nallihan"),
		"743051" => t("Kizilcahamam"),
		"743615" => t("Kazan"),
		"748870" => t("Cubuk"),
		"750637" => t("Beypazari"),
		"6955677" => t("Cankaya"),
	);
}


function location_cities_list_tr_07 () {
	return array (
		"299445" => t("Tekirova"),
		"301101" => t("Serik"),
		"304854" => t("Manavgat"),
		"305680" => t("Beykonak"),
		"306474" => t("Korkuteli"),
		"308220" => t("Kemer"),
		"314812" => t("Gazipasa"),
		"315697" => t("Elmali"),
		"321580" => t("Belek"),
		"323777" => t("Antalya"),
		"324190" => t("Alanya"),
	);
}


function location_cities_list_tr_75 () {
	return array (
		"751952" => t("Ardahan"),
	);
}


function location_cities_list_tr_08 () {
	return array (
		"745530" => t("Hopa"),
		"751817" => t("Artvin"),
		"751931" => t("Arhavi"),
	);
}


function location_cities_list_tr_09 () {
	return array (
		"297090" => t("Didim"),
		"300399" => t("Soeke"),
		"303873" => t("Nazilli"),
		"305359" => t("Kusadasi"),
		"311314" => t("Incirliova"),
		"318372" => t("Cine"),
		"322830" => t("Aydin"),
	);
}


function location_cities_list_tr_04 () {
	return array (
		"302819" => t("Patnos"),
		"309647" => t("Agri"),
		"315758" => t("Eleskirt"),
		"316411" => t("Dogubayazit"),
		"316542" => t("Diyadin"),
	);
}


function location_cities_list_tr_10 () {
	return array (
		"300058" => t("Susurluk"),
		"315985" => t("Edremit"),
		"316102" => t("Dursunbey"),
		"320369" => t("Burhaniye"),
		"321136" => t("Bigadic"),
		"322165" => t("Balikesir"),
		"322673" => t("Ayvalik"),
		"746574" => t("Gonen"),
		"747482" => t("Erdek"),
		"751077" => t("Bandirma"),
	);
}


function location_cities_list_tr_74 () {
	return array (
		"751057" => t("Bartin"),
	);
}


function location_cities_list_tr_72 () {
	return array (
		"306041" => t("Kozluk"),
		"321836" => t("Batman"),
	);
}


function location_cities_list_tr_69 () {
	return array (
		"750938" => t("Bayburt"),
	);
}


function location_cities_list_tr_11 () {
	return array (
		"320557" => t("Bozuyuk"),
		"740881" => t("Osmaneli"),
		"750598" => t("Bilecik"),
	);
}


function location_cities_list_tr_12 () {
	return array (
		"300377" => t("Solhan"),
		"314648" => t("Genc"),
		"321082" => t("Bingol"),
	);
}


function location_cities_list_tr_13 () {
	return array (
		"299582" => t("Tatvan"),
		"312024" => t("Hizan"),
		"313331" => t("Guroymak"),
		"321025" => t("Bitlis"),
		"325103" => t("Ahlat"),
		"325336" => t("Adilcevaz"),
	);
}


function location_cities_list_tr_14 () {
	return array (
		"746940" => t("Gerede"),
		"750516" => t("Bolu"),
	);
}


function location_cities_list_tr_15 () {
	return array (
		"320392" => t("Burdur"),
		"320533" => t("Bucak"),
	);
}


function location_cities_list_tr_16 () {
	return array (
		"737611" => t("Yenisehir"),
		"741045" => t("Orhangazi"),
		"741487" => t("Mudanya"),
		"743404" => t("Kestel"),
		"744537" => t("Karacabey"),
		"745026" => t("Iznik"),
		"745169" => t("Inegeul"),
		"746232" => t("Gursu"),
		"746958" => t("Gemlik"),
		"750269" => t("Bursa"),
	);
}


function location_cities_list_tr_20 () {
	return array (
		"301827" => t("Saraykoy"),
		"307211" => t("Serinhisar"),
		"317109" => t("Denizli"),
	);
}


function location_cities_list_tr_21 () {
	return array (
		"300796" => t("Silvan"),
		"305089" => t("Lice"),
		"305750" => t("Kulp"),
		"315468" => t("Ergani"),
		"316541" => t("Diyarbakir"),
		"318766" => t("Cermik"),
		"321031" => t("Bismil"),
	);
}


function location_cities_list_tr_81 () {
	return array (
		"747764" => t("Duzce"),
		"752584" => t("Akcakoca"),
	);
}


function location_cities_list_tr_22 () {
	return array (
		"738251" => t("Uzun Keupru"),
		"743439" => t("Kesan"),
		"747712" => t("Edirne"),
	);
}


function location_cities_list_tr_23 () {
	return array (
		"306207" => t("Kovancilar"),
		"309663" => t("Karakocan"),
		"315808" => t("Elazig"),
		"321929" => t("Baskil"),
	);
}


function location_cities_list_tr_24 () {
	return array (
		"298230" => t("Cimin"),
		"315373" => t("Erzincan"),
	);
}


function location_cities_list_tr_25 () {
	return array (
		"302824" => t("Pasinler"),
		"310004" => t("Karacoban"),
		"312114" => t("Hinis"),
		"315368" => t("Erzurum"),
		"323094" => t("Askale"),
		"741160" => t("Oltu"),
		"745527" => t("Horasan"),
	);
}


function location_cities_list_tr_26 () {
	return array (
		"315202" => t("Eskisehir"),
	);
}


function location_cities_list_tr_27 () {
	return array (
		"303798" => t("Nizip"),
		"314830" => t("Gaziantep"),
	);
}


function location_cities_list_tr_28 () {
	return array (
		"738753" => t("Tirebolu"),
		"739914" => t("Sebinkarahisar"),
		"746565" => t("Gorele"),
		"746881" => t("Giresun"),
		"750317" => t("Bulancak"),
		"831432" => t("Espiye"),
	);
}


function location_cities_list_tr_29 () {
	return array (
		"743537" => t("Kelkit"),
		"746425" => t("Gumushkhane"),
	);
}


function location_cities_list_tr_30 () {
	return array (
		"296173" => t("Yuksekova"),
		"301209" => t("Semdinli"),
		"318137" => t("Hakkari"),
	);
}


function location_cities_list_tr_31 () {
	return array (
		"296852" => t("Erzin"),
		"301089" => t("Serinyol"),
		"302355" => t("Reyhanli"),
		"307657" => t("Kirikhan"),
		"311111" => t("Iskenderun"),
		"316284" => t("Dortyol"),
		"321572" => t("Belen"),
		"323779" => t("Antioch"),
		"438400" => t("Denizciler"),
	);
}


function location_cities_list_tr_32 () {
	return array (
		"297789" => t("Yalvac"),
		"301172" => t("Senirkent"),
		"301539" => t("Sarkikaraagac"),
		"311073" => t("Isparta"),
		"315905" => t("Egirdir"),
	);
}


function location_cities_list_tr_34 () {
	return array (
		"737071" => t("Zeytinburnu"),
		"738064" => t("Yakuplu"),
		"738329" => t("UEskuedar"),
		"738377" => t("Umraniye"),
		"738858" => t("Tepecik"),
		"739549" => t("Sisli"),
		"739634" => t("Silivri"),
		"741529" => t("Mimarsinan"),
		"741763" => t("Maltepe"),
		"743818" => t("Kavakli"),
		"745044" => t("Istanbul"),
		"746234" => t("Gurpinar"),
		"747323" => t("Esenyurt"),
		"747340" => t("Esenler"),
		"747538" => t("Eminoenue"),
		"749644" => t("Catalca"),
		"751324" => t("Bagcilar"),
		"6354984" => t("merter keresteciler"),
		"6354985" => t("guengoeren merter"),
		"6947637" => t("Atasehir"),
		"6947639" => t("Basaksehir"),
		"6947640" => t("Beylikduezue"),
		"6947641" => t("Bueyuekcekmece"),
		"7627067" => t("Bahcelievler"),
		"7628416" => t("Sultangazi"),
		"7628419" => t("Sultanbeyli"),
		"7628420" => t("Sancaktepe"),
	);
}


function location_cities_list_tr_76 () {
	return array (
		"311665" => t("Igdir"),
	);
}


function location_cities_list_tr_46 () {
	return array (
		"302800" => t("Pazarcik"),
		"310859" => t("Kahramanmaras"),
		"314188" => t("Goksun"),
		"315795" => t("Elbistan"),
		"320004" => t("Caglayancerit"),
		"325304" => t("Afsin"),
	);
}


function location_cities_list_tr_78 () {
	return array (
		"740430" => t("Safranbolu"),
		"744562" => t("Karabuk"),
	);
}


function location_cities_list_tr_70 () {
	return array (
		"309527" => t("Karaman"),
		"315401" => t("Ermenek"),
	);
}


function location_cities_list_tr_36 () {
	return array (
		"740088" => t("Sarikamis"),
		"743952" => t("Kars"),
		"744873" => t("Kagizman"),
	);
}


function location_cities_list_tr_37 () {
	return array (
		"738662" => t("Tosya"),
		"739061" => t("Taskopru"),
		"743882" => t("Kastamonu"),
	);
}


function location_cities_list_tr_38 () {
	return array (
		"297917" => t("Yahyali"),
		"299900" => t("Talas"),
		"308464" => t("Kayseri"),
		"313013" => t("Hacilar"),
		"316795" => t("Develi"),
	);
}


function location_cities_list_tr_79 () {
	return array (
		"307864" => t("Kilis"),
	);
}


function location_cities_list_tr_41 () {
	return array (
		"737961" => t("Korfez"),
		"744168" => t("Karamursel"),
		"745028" => t("Izmit"),
		"746666" => t("Geulzuk"),
		"747014" => t("Gebze"),
	);
}


function location_cities_list_tr_42 () {
	return array (
		"301010" => t("Seydisehir"),
		"305742" => t("Kulu"),
		"306571" => t("Konya"),
		"309415" => t("Karapinar"),
		"310907" => t("Kadinhani"),
		"311553" => t("Ilgin"),
		"312899" => t("Hadim"),
		"315498" => t("Eregli"),
		"317844" => t("Cumra"),
		"321191" => t("Beysehir"),
		"324490" => t("Aksehir"),
	);
}


function location_cities_list_tr_43 () {
	return array (
		"299545" => t("Tavsanli"),
		"300791" => t("Simav"),
		"305268" => t("Kutahya"),
		"314716" => t("Gediz"),
		"315639" => t("Emet"),
	);
}


function location_cities_list_tr_39 () {
	return array (
		"741855" => t("Luleburgaz"),
		"743166" => t("Kirklareli"),
		"751371" => t("Babaeski"),
	);
}


function location_cities_list_tr_71 () {
	return array (
		"307654" => t("Kirikkale"),
		"308024" => t("Keskin"),
	);
}


function location_cities_list_tr_40 () {
	return array (
		"304196" => t("Mucur"),
		"307515" => t("Kirsehir"),
		"310641" => t("Kaman"),
	);
}


function location_cities_list_tr_44 () {
	return array (
		"304922" => t("Malatya"),
		"317588" => t("Darende"),
	);
}


function location_cities_list_tr_45 () {
	return array (
		"298806" => t("Turgutlu"),
		"300371" => t("Soma"),
		"302043" => t("Salihli"),
		"304827" => t("Manisa"),
		"305810" => t("Kula"),
		"307623" => t("Kirkagac"),
		"317241" => t("Demirci"),
		"324172" => t("Alasehir"),
		"324698" => t("Akhisar"),
	);
}


function location_cities_list_tr_47 () {
	return array (
		"296832" => t("Yesilli"),
		"303750" => t("Nusaybin"),
		"304382" => t("Midyat"),
		"304797" => t("Mardin"),
		"307084" => t("Kiziltepe"),
		"317587" => t("Dargecit"),
	);
}


function location_cities_list_tr_33 () {
	return array (
		"299817" => t("Tarsus"),
		"300808" => t("Silifke"),
		"304013" => t("Mut"),
		"304531" => t("Mercin"),
		"315515" => t("Erdemli"),
		"320552" => t("Bozyazi"),
		"323828" => t("Anamur"),
	);
}


function location_cities_list_tr_48 () {
	return array (
		"297564" => t("Yatagan"),
		"303354" => t("Ortaca"),
		"304184" => t("Mugla"),
		"304355" => t("Milas"),
		"304782" => t("Marmaris"),
		"314967" => t("Fethiye"),
		"320995" => t("Bodrum"),
		"447273" => t("Dalaman"),
		"6692524" => t("Sarigerme"),
	);
}


function location_cities_list_tr_49 () {
	return array (
		"298088" => t("Varto"),
		"304081" => t("Mus"),
		"304916" => t("Malazgirt"),
		"320448" => t("Bulanik"),
	);
}


function location_cities_list_tr_50 () {
	return array (
		"298326" => t("Urgub"),
		"303831" => t("Nevsehir"),
	);
}


function location_cities_list_tr_51 () {
	return array (
		"303827" => t("Nigde"),
		"320871" => t("Bor"),
	);
}


function location_cities_list_tr_52 () {
	return array (
		"738349" => t("Unieh"),
		"741100" => t("Ordu"),
		"742238" => t("Kumru"),
		"742658" => t("Korgan"),
		"746252" => t("Gurgentepe"),
		"747155" => t("Fatsa"),
	);
}


function location_cities_list_tr_80 () {
	return array (
		"303195" => t("Osmaniye"),
	);
}


function location_cities_list_tr_53 () {
	return array (
		"740483" => t("Rize"),
		"749502" => t("Cayeli"),
		"751949" => t("Ardesen"),
	);
}


function location_cities_list_tr_54 () {
	return array (
		"740230" => t("Sapanca"),
		"742902" => t("Kocaali"),
		"744093" => t("Karasu"),
		"745664" => t("Hendek"),
		"746898" => t("Geyve"),
		"747135" => t("Ferizli"),
		"752288" => t("Akyazi"),
		"752850" => t("Adapazari"),
	);
}


function location_cities_list_tr_55 () {
	return array (
		"738167" => t("Vezirkopru"),
		"738803" => t("Terme"),
		"738907" => t("Tekkekoy"),
		"740264" => t("Samsun"),
		"745714" => t("Havza"),
		"749704" => t("Carsamba"),
		"751335" => t("Bafra"),
	);
}


function location_cities_list_tr_56 () {
	return array (
		"300822" => t("Siirt"),
		"305532" => t("Kurtalan"),
	);
}


function location_cities_list_tr_57 () {
	return array (
		"739600" => t("Sinop"),
		"750468" => t("Boyabat"),
	);
}


function location_cities_list_tr_58 () {
	return array (
		"300619" => t("Sivas"),
		"301537" => t("Sarkisla"),
		"314665" => t("Gemerek"),
		"739209" => t("Susehri"),
	);
}


function location_cities_list_tr_59 () {
	return array (
		"738927" => t("Tekirdag"),
		"741771" => t("Malkara"),
		"745697" => t("Hayrabolu"),
		"748893" => t("Corlu"),
		"749274" => t("Cerkezkoey"),
	);
}


function location_cities_list_tr_60 () {
	return array (
		"737054" => t("Zile"),
		"738618" => t("Turhal"),
		"738743" => t("Tokat"),
		"741304" => t("Niksar"),
		"747489" => t("Erbaa"),
	);
}


function location_cities_list_tr_61 () {
	return array (
		"737421" => t("Yomra"),
		"738228" => t("Vakfikebir"),
		"738648" => t("Trabzon"),
		"739215" => t("Surmene"),
		"741240" => t("Of"),
		"750735" => t("Besikduzu"),
		"751838" => t("Arsin"),
		"751971" => t("Arakli"),
		"752627" => t("Akcaabat"),
	);
}


function location_cities_list_tr_62 () {
	return array (
		"298846" => t("Tunceli"),
	);
}


function location_cities_list_tr_64 () {
	return array (
		"298299" => t("Usak"),
		"322051" => t("Banaz"),
	);
}


function location_cities_list_tr_65 () {
	return array (
		"298117" => t("Van"),
		"315530" => t("Ercis"),
	);
}


function location_cities_list_tr_77 () {
	return array (
		"738025" => t("Yalova"),
	);
}


function location_cities_list_tr_66 () {
	return array (
		"296562" => t("Yozgat"),
		"296895" => t("Yerkoy"),
		"300352" => t("Sorgun"),
		"324768" => t("Akdagmadeni"),
	);
}


function location_cities_list_tr_67 () {
	return array (
		"737022" => t("Zonguldak"),
		"747471" => t("Eregli"),
		"748167" => t("Devrek"),
		"749508" => t("Caycuma"),
		"752184" => t("Alapli"),
	);
}


function location_cities_list_tr_17 () {
	return array (
		"315061" => t("Ezine"),
		"746983" => t("Gelibolu"),
		"749780" => t("Canakkale"),
		"749795" => t("Can"),
		"750605" => t("Biga"),
	);
}


function location_cities_list_tr_18 () {
	return array (
		"749279" => t("Cerkes"),
		"749748" => t("Khanjarah"),
	);
}


function location_cities_list_tr_19 () {
	return array (
		"739236" => t("Sungurlu"),
		"740883" => t("Osmancik"),
		"745076" => t("Iskilip"),
		"748879" => t("Corum"),
		"752278" => t("Alaca"),
	);
}


function location_cities_list_tr_35 () {
	return array (
		"298316" => t("Urla"),
		"298935" => t("Torbali"),
		"299137" => t("Tire"),
		"301256" => t("Selcuk"),
		"301350" => t("Seferihisar"),
		"303700" => t("Hypaepa"),
		"304612" => t("Menemen"),
		"308224" => t("Kemalpasa"),
		"311046" => t("Izmir"),
		"314903" => t("Foca"),
		"317851" => t("Menderes"),
		"318755" => t("Cesme"),
		"321426" => t("Bergama"),
		"321786" => t("Bayindir"),
		"324106" => t("Aliaga"),
		"7701384" => t("Karabaglar"),
	);
}


function location_cities_list_tr_63 () {
	return array (
		"298033" => t("Viransehir"),
		"298333" => t("Sanliurfa"),
		"300075" => t("Suruc"),
		"300614" => t("Siverek"),
		"312134" => t("Hilvan"),
		"318668" => t("Ceylanpinar"),
		"320581" => t("Bozova"),
		"321062" => t("Birecik"),
		"324944" => t("Akcakale"),
	);
}


function location_cities_list_tr_73 () {
	return array (
		"300640" => t("Sirnak"),
		"300797" => t("Silopi"),
		"311704" => t("Idil"),
		"318253" => t("Cizre"),
	);
}
