<?php


function location_cities_list_by_br() {
  return array(
    "622997" => "Pruzhany",
    "623549" => "Pinsk",
    "625818" => "Luninyets",
    "627145" => "Kobryn",
    "627800" => "Ivatsevichy",
    "629454" => "Byaroza",
    "629634" => "Brest",
    "630429" => "Baranavichy",
  );
}


function location_cities_list_by_ho() {
  return array(
    "618806" => "Zhlobin",
    "621074" => "Svyetlahorsk",
    "622739" => "Rahachow",
    "622794" => "Rechytsa",
    "625324" => "Mazyr",
    "627751" => "Kalinkavichy",
    "627907" => "Homyel'",
    "629018" => "Dobrush",
  );
}


function location_cities_list_by_hr() {
  return array(
    "620391" => "Vawkavysk",
    "621713" => "Smarhon'",
    "621754" => "Slonim",
    "622113" => "Shchuchin",
    "624785" => "Navahrudak",
    "625367" => "Masty",
    "626081" => "Lida",
    "627904" => "Hrodna",
  );
}


function location_cities_list_by_ma() {
  return array(
    "624034" => "Asipovichy",
    "625665" => "Mahilyow",
    "626450" => "Krychaw",
    "627905" => "Horki",
    "629447" => "Bykhaw",
    "630468" => "Babruysk",
  );
}


function location_cities_list_by_hm() {
  return array(
    "8020218" => "Malinovka",
  );
}


function location_cities_list_by_mi() {
  return array(
    "618800" => "Horad Zhodzina",
    "620181" => "Vilyeyka",
    "621266" => "Stowbtsy",
    "621741" => "Slutsk",
    "622428" => "Salihorsk",
    "625144" => "Minsk",
    "625409" => "Mar''ina Horka",
    "625625" => "Maladzyechna",
    "627083" => "Kalodzishchy",
    "628634" => "Dzyarzhynsk",
    "630376" => "Horad Barysaw",
  );
}


function location_cities_list_by_vi() {
  return array(
    "620127" => "Vitebsk",
    "623317" => "Polatsk",
    "623760" => "Pastavy",
    "624079" => "Orsha",
    "624784" => "Navapolatsk",
    "625743" => "Lyepyel'",
    "627908" => "Hlybokaye",
  );
}
