<?php


function location_cities_list_re_re() {
  return array(
    "935214" => "Saint-Pierre",
    "935221" => "Saint-Paul",
    "935223" => "Saint-Louis",
    "935225" => "Saint-Leu",
    "935227" => "Saint-Joseph",
    "935248" => "Sainte-Suzanne",
    "935255" => "Sainte-Marie",
    "935264" => "Saint-Denis",
    "935267" => "Saint-Benoit",
    "935268" => "Saint-Andre",
    "935582" => "Le Tampon",
    "935616" => "Le Port",
    "935691" => "La Possession",
  );
}
