<?php

function location_cities_list_bh_17 () {
	return array (
		"385038" => t("Ar Rifa'"),
		"290187" => t("Madinat `Isa"),
		"290104" => t("Sitrah"),
	);
}


function location_cities_list_bh_13 () {
	return array (
		"290215" => t("Jidd Hafs"),
		"290340" => t("Manama"),
	);
}


function location_cities_list_bh_16 () {
	return array (
		"290269" => t("Dar Kulayb"),
		"290247" => t("Madinat Hamad"),
	);
}


function location_cities_list_bh_15 () {
	return array (
		"290332" => t("Al Muharraq"),
	);
}


