<?php


function location_cities_list_pe_ama() {
  return array(
    "3695675" => "La Peca",
    "3698540" => "Chachapoyas",
    "3699484" => "Bagua Grande",
  );
}


function location_cities_list_pe_anc() {
  return array(
    "3696378" => "Huaraz",
    "3697990" => "Coishco",
    "3698304" => "Chimbote",
    "3939168" => "Huarmey",
  );
}


function location_cities_list_pe_apu() {
  return array(
    "3947740" => "Andahuaylas",
    "3948642" => "Abancay",
  );
}


function location_cities_list_pe_are() {
  return array(
    "3934707" => "Mollendo",
    "3945985" => "Camana",
    "3947322" => "Arequipa",
  );
}


function location_cities_list_pe_aya() {
  return array(
    "3939386" => "Huanta",
    "3947019" => "Ayacucho",
  );
}


function location_cities_list_pe_caj() {
  return array(
    "3696150" => "Jaen",
    "3699088" => "Cajamarca",
  );
}


function location_cities_list_pe_cal() {
  return array(
    "3946083" => "Callao",
  );
}


function location_cities_list_pe_cus() {
  return array(
    "3928679" => "Sicuani",
    "3929295" => "Santa Ana",
    "3941584" => "Cusco",
  );
}


function location_cities_list_pe_moq() {
  return array(
    "3934608" => "Moquegua",
    "3938415" => "Ilo",
  );
}


function location_cities_list_pe_huv() {
  return array(
    "3939470" => "Huancavelica",
  );
}


function location_cities_list_pe_ica() {
  return array(
    "3929768" => "San Clemente",
    "3932145" => "Pisco",
    "3934356" => "Nazca",
    "3935288" => "Minas de Marcona",
    "3938527" => "Ica",
    "3943789" => "Chincha Alta",
  );
}


function location_cities_list_pe_jun() {
  return array(
    "3927758" => "Tarma",
    "3928924" => "Satipo",
    "3936952" => "La Oroya",
    "3937486" => "Junin",
    "3937733" => "Jauja",
    "3939459" => "Huancayo",
  );
}


function location_cities_list_pe_lal() {
  return array(
    "3690875" => "Viru",
    "3691175" => "Trujillo",
    "3692073" => "Santiago de Cao",
    "3692310" => "San Pedro de Lloc",
    "3694119" => "Paijan",
    "3694178" => "Pacasmayo",
    "3694725" => "Moche",
    "3695617" => "Laredo",
    "3696509" => "Huamachuco",
    "3696847" => "Guadalupe",
    "3698194" => "Chocope",
    "3698390" => "Chepen",
  );
}


function location_cities_list_pe_lam() {
  return array(
    "3692667" => "Zana",
    "3693584" => "Pimentel",
    "3693645" => "Picsi",
    "3694666" => "Monsefu",
    "3695754" => "Lambayeque",
    "3697033" => "Ferrenafe",
    "3698176" => "Chongoyape",
    "3698350" => "Chiclayo",
  );
}


function location_cities_list_pe_lim() {
  return array(
    "3928245" => "Surco",
    "3928993" => "San Vicente de Canete",
    "3929631" => "San Isidro",
    "3933024" => "Paramonga",
    "3934239" => "Nuevo Imperial",
    "3935572" => "Mala",
    "3938396" => "Imperial",
    "3939023" => "Huaura",
    "3939285" => "Huaral",
    "3939761" => "Hualmay",
    "3940002" => "Huacho",
    "3943423" => "Chosica",
    "3944399" => "Chancay",
    "3946820" => "Barranca",
  );
}


function location_cities_list_pe_lor() {
  return array(
    "3690654" => "Yurimaguas",
    "3696183" => "Iquitos",
  );
}


function location_cities_list_pe_mdd() {
  return array(
    "3927942" => "Tambopata",
    "3931470" => "Puerto Maldonado",
  );
}


function location_cities_list_pe_pas() {
  return array(
    "3944179" => "Chaupimarca",
    "3944797" => "Cerro de Pasco",
  );
}


function location_cities_list_pe_piu() {
  return array(
    "3691530" => "Tambo Grande",
    "3691582" => "Talara",
    "3691674" => "Sullana",
    "3691954" => "Sechura",
    "3693057" => "Querecotillo",
    "3693528" => "Piura",
    "3694112" => "Paita",
    "3694939" => "Marcavelica",
    "3695466" => "La Union",
    "3698105" => "Chulucanas",
    "3698658" => "Catacaos",
    "3814568" => "La Breita",
  );
}


function location_cities_list_pe_lma() {
  return array(
    "3936456" => "Lima",
  );
}


function location_cities_list_pe_pun() {
  return array(
    "3925476" => "Yunguyo",
    "3931276" => "Puno",
    "3937513" => "Juliaca",
    "3938451" => "Ilave",
    "3946985" => "Ayaviri",
    "7626291" => "La Rinconada",
  );
}


function location_cities_list_pe_huc() {
  return array(
    "3691348" => "Tingo Maria",
    "3696417" => "Huanuco",
    "3925863" => "Yanacancha",
  );
}


function location_cities_list_pe_sam() {
  return array(
    "3691094" => "Uchiza",
    "3691324" => "Tocache Nuevo",
    "3692863" => "Rioja",
    "3694564" => "Moyobamba",
    "3696057" => "Juanjui",
    "3699364" => "Bellavista",
  );
}


function location_cities_list_pe_tac() {
  return array(
    "3928128" => "Tacna",
  );
}


function location_cities_list_pe_tum() {
  return array(
    "3691148" => "Tumbes",
    "3818398" => "Zarumilla",
  );
}


function location_cities_list_pe_uca() {
  return array(
    "3693345" => "Pucallpa",
  );
}
