<?php

function location_cities_list_eg_gh () {
	return array (
		"360829" => t("Al Mahallah al Kubra"),
		"358970" => t("Basyun"),
		"354365" => t("Kafr az Zayyat"),
		"350376" => t("Qutur"),
		"349715" => t("Samannud"),
		"347497" => t("Tanda"),
		"346030" => t("Zifta"),
	);
}


function location_cities_list_eg_kb () {
	return array (
		"360928" => t("Al Khankah"),
		"360615" => t("Al Qanatir al Khayriyah"),
		"359280" => t("Banha"),
		"350789" => t("Qalyub"),
		"349156" => t("Shibin al Qanatir"),
		"347236" => t("Toukh"),
	);
}


function location_cities_list_eg_fym () {
	return array (
		"361320" => t("Al Fayyum"),
		"360464" => t("Al Wasitah"),
		"355648" => t("Ibshaway"),
		"355420" => t("Itsa"),
		"347542" => t("Tamiyah"),
	);
}


function location_cities_list_eg_dk () {
	return array (
		"361702" => t("Aja"),
		"361029" => t("Al Jamaliyah"),
		"360761" => t("Al Mansurah"),
		"360754" => t("Al Manzilah"),
		"360716" => t("Al Matariyah"),
		"358821" => t("Bilqas"),
		"358172" => t("Dikirnis"),
		"352344" => t("Minyat an Nasr"),
		"349114" => t("Shirbin"),
		"347591" => t("Talkha"),
		"355392" => t("`Izbat al Burj"),
	);
}


function location_cities_list_eg_mnf () {
	return array (
		"361457" => t("Al Bajur"),
		"359953" => t("Ash Shuhada'"),
		"360048" => t("Ashmun"),
		"352354" => t("Minuf"),
		"350370" => t("Quwaysina"),
		"349158" => t("Shibin al Kawm"),
		"347612" => t("Tala"),
	);
}


function location_cities_list_eg_shg () {
	return array (
		"361661" => t("Akhmim"),
		"361435" => t("Al Balyana"),
		"360773" => t("Al Manshah"),
		"355026" => t("Jirja"),
		"354981" => t("Juhaynah"),
		"347796" => t("Suhaj"),
		"347634" => t("Tahta"),
	);
}


function location_cities_list_eg_bns () {
	return array (
		"361329" => t("Al Fashn"),
		"359173" => t("Bani Suwayf"),
		"358600" => t("Bush"),
		"347749" => t("Sumusta as Sultani"),
	);
}


function location_cities_list_eg_kfs () {
	return array (
		"361213" => t("Al Hamul"),
		"358108" => t("Disuq"),
		"356806" => t("Fuwah"),
		"354502" => t("Kafr ash Shaykh"),
		"348112" => t("Sidi Salim"),
	);
}


function location_cities_list_eg_mn () {
	return array (
		"362277" => t("Abu Qurqas"),
		"360686" => t("Al Minya"),
		"359212" => t("Bani Mazar"),
		"358274" => t("Dayr Mawas"),
		"352951" => t("Mallawi"),
		"352628" => t("Matay"),
		"349717" => t("Samalut"),
	);
}


function location_cities_list_eg_bh () {
	return array (
		"362882" => t("Abu al Matamir"),
		"361827" => t("Ad Dilinjat"),
		"358448" => t("Damanhur"),
		"356000" => t("Hawsh `Isa"),
		"355628" => t("Idku"),
		"354775" => t("Kafr ad Dawwar"),
		"353828" => t("Kawm Hamadah"),
		"350203" => t("Rosetta"),
	);
}


function location_cities_list_eg_kn () {
	return array (
		"358115" => t("Dishna"),
		"356933" => t("Farshut"),
		"355449" => t("Isna"),
		"350422" => t("Kousa"),
		"351434" => t("Naj` Hammadi"),
		"350550" => t("Qina"),
	);
}


function location_cities_list_eg_shr () {
	return array (
		"362485" => t("Abu Kabir"),
		"361103" => t("Al Ibrahimiyah"),
		"360612" => t("Al Qanayat"),
		"360542" => t("Al Qurayn"),
		"358840" => t("Bilbays"),
		"358095" => t("Diyarb Najm"),
		"356989" => t("Faqus"),
		"355939" => t("Hihya"),
		"354105" => t("Kafr Saqr"),
		"352679" => t("Mashtul as Suq"),
		"359493" => t("Zagazig"),
	);
}


function location_cities_list_eg_mt () {
	return array (
		"352733" => t("Marsa Matruh"),
	);
}


function location_cities_list_eg_ast () {
	return array (
		"362973" => t("Abnub"),
		"362004" => t("Abu Tij"),
		"361478" => t("Al Badari"),
		"360526" => t("Al Qusiyah"),
		"359783" => t("Asyut"),
		"358269" => t("Dayrut"),
		"352913" => t("Manfalut"),
	);
}


function location_cities_list_eg_gz () {
	return array (
		"361394" => t("Al Bawiti"),
		"361179" => t("Al Hawamidiyah"),
		"360995" => t("Al Jizah"),
		"361495" => t("Al `Ayyat"),
		"359900" => t("As Saff"),
		"359576" => t("Awsim"),
		"353219" => t("Madinat Sittah Uktubar"),
	);
}


function location_cities_list_eg_asn () {
	return array (
		"359792" => t("Aswan"),
		"411165" => t("Idfu"),
		"353802" => t("Kawm Umbu"),
	);
}


function location_cities_list_eg_c () {
	return array (
		"360630" => t("Cairo"),
		"355795" => t("Halwan"),
	);
}


function location_cities_list_eg_dt () {
	return array (
		"419435" => t("Az Zarqa"),
		"358048" => t("Damietta"),
		"356945" => t("Faraskur"),
	);
}


function location_cities_list_eg_pts () {
	return array (
		"358619" => t("Port Said"),
	);
}


function location_cities_list_eg_ba () {
	return array (
		"361291" => t("Al Ghardaqah"),
		"360531" => t("Al Qusayr"),
		"358620" => t("Bur Safajah"),
	);
}


function location_cities_list_eg_is () {
	return array (
		"359710" => t("At Tall al Kabir"),
		"361055" => t("Ismailia"),
	);
}


function location_cities_list_eg_suz () {
	return array (
		"7521348" => t("Ain Sukhna"),
		"359796" => t("Suez"),
	);
}


function location_cities_list_eg_lx () {
	return array (
		"360502" => t("Luxor"),
	);
}


function location_cities_list_eg_wad () {
	return array (
		"360923" => t("Al Kharijah"),
	);
}


function location_cities_list_eg_alx () {
	return array (
		"361058" => t("Alexandria"),
	);
}


function location_cities_list_eg_sin () {
	return array (
		"361546" => t("Arish"),
	);
}


