<?php

function location_cities_list_ke_10 () {
	return array (
		"195821" => t("Kabarnet"),
	);
}


function location_cities_list_ke_11 () {
	return array (
	);
}


function location_cities_list_ke_12 () {
	return array (
		"200067" => t("Bungoma"),
	);
}


function location_cities_list_ke_13 () {
	return array (
		"199989" => t("Busia"),
	);
}


function location_cities_list_ke_14 () {
	return array (
	);
}


function location_cities_list_ke_15 () {
	return array (
		"198476" => t("Embu"),
	);
}


function location_cities_list_ke_16 () {
	return array (
		"197745" => t("Garissa"),
	);
}


function location_cities_list_ke_17 () {
	return array (
		"196742" => t("Homa Bay"),
	);
}


function location_cities_list_ke_18 () {
	return array (
		"196231" => t("Isiolo"),
	);
}


function location_cities_list_ke_19 () {
	return array (
	);
}


function location_cities_list_ke_20 () {
	return array (
		"195272" => t("Kakamega"),
	);
}


function location_cities_list_ke_21 () {
	return array (
		"192900" => t("Kericho"),
	);
}


function location_cities_list_ke_22 () {
	return array (
		"192710" => t("Kiambu"),
	);
}


function location_cities_list_ke_23 () {
	return array (
		"187968" => t("Malindi"),
		"192067" => t("Kilifi"),
	);
}


function location_cities_list_ke_24 () {
	return array (
		"192859" => t("Keruguya"),
	);
}


function location_cities_list_ke_25 () {
	return array (
		"191299" => t("Kisii"),
	);
}


function location_cities_list_ke_26 () {
	return array (
		"191245" => t("Kisumu"),
	);
}


function location_cities_list_ke_27 () {
	return array (
		"191038" => t("Kitui"),
	);
}


function location_cities_list_ke_28 () {
	return array (
	);
}


function location_cities_list_ke_29 () {
	return array (
		"184433" => t("Nanyuki"),
	);
}


function location_cities_list_ke_30 () {
	return array (
		"189741" => t("Lamu"),
	);
}


function location_cities_list_ke_31 () {
	return array (
		"188492" => t("Machakos"),
	);
}


function location_cities_list_ke_32 () {
	return array (
	);
}


function location_cities_list_ke_33 () {
	return array (
		"187896" => t("Mandera"),
	);
}


function location_cities_list_ke_34 () {
	return array (
		"187585" => t("Marsabit"),
	);
}


function location_cities_list_ke_35 () {
	return array (
		"186827" => t("Meru"),
	);
}


function location_cities_list_ke_36 () {
	return array (
		"186731" => t("Migori"),
	);
}


function location_cities_list_ke_37 () {
	return array (
		"186301" => t("Mombasa"),
	);
}


function location_cities_list_ke_38 () {
	return array (
	);
}


function location_cities_list_ke_110 () {
	return array (
		"179330" => t("Thika"),
		"181501" => t("Pumwani"),
		"184745" => t("Nairobi"),
	);
}


function location_cities_list_ke_39 () {
	return array (
		"184622" => t("Nakuru"),
	);
}


function location_cities_list_ke_40 () {
	return array (
	);
}


function location_cities_list_ke_41 () {
	return array (
		"184379" => t("Narok"),
	);
}


function location_cities_list_ke_42 () {
	return array (
	);
}


function location_cities_list_ke_43 () {
	return array (
		"7931933" => t("Ol Kalou"),
	);
}


function location_cities_list_ke_44 () {
	return array (
		"182701" => t("Nyeri"),
	);
}


function location_cities_list_ke_45 () {
	return array (
		"187725" => t("Maralal"),
	);
}


function location_cities_list_ke_46 () {
	return array (
		"383388" => t("Siaya"),
	);
}


function location_cities_list_ke_47 () {
	return array (
	);
}


function location_cities_list_ke_48 () {
	return array (
	);
}


function location_cities_list_ke_49 () {
	return array (
		"179381" => t("Tharaka"),
	);
}


function location_cities_list_ke_50 () {
	return array (
		"191220" => t("Kitale"),
	);
}


function location_cities_list_ke_51 () {
	return array (
		"189280" => t("Lodwar"),
	);
}


function location_cities_list_ke_52 () {
	return array (
		"198629" => t("Eldoret"),
	);
}


function location_cities_list_ke_53 () {
	return array (
		"187110" => t("Mbale"),
	);
}


function location_cities_list_ke_54 () {
	return array (
		"178443" => t("Wajir"),
	);
}


function location_cities_list_ke_55 () {
	return array (
		"194160" => t("Kapenguria"),
	);
}
