<?php

function location_cities_list_az_abs () {
	return array (
		"585915" => t("Khirdalan"),
	);
}


function location_cities_list_az_agm () {
	return array (
		"148619" => t("Agdam"),
	);
}


function location_cities_list_az_ags () {
	return array (
		"587378" => t("Agdas"),
	);
}


function location_cities_list_az_agc () {
	return array (
		"587384" => t("Agdzhabedy"),
	);
}


function location_cities_list_az_aga () {
	return array (
	);
}


function location_cities_list_az_agu () {
	return array (
		"587361" => t("Aghsu"),
	);
}


function location_cities_list_az_ab () {
	return array (
		"148565" => t("Sirvan"),
	);
}


function location_cities_list_az_ast () {
	return array (
		"148445" => t("Astara"),
	);
}


function location_cities_list_az_ba () {
	return array (
		"584614" => t("Zabrat"),
		"585103" => t("Qaracuxur"),
		"585184" => t("Sabuncu"),
		"585557" => t("Mastaga"),
		"585568" => t("Mardakyany"),
		"585630" => t("Lokbatan"),
		"586340" => t("Yeni Suraxani"),
		"586429" => t("Hovsan"),
		"586925" => t("Buzovna"),
		"586968" => t("Biny Selo"),
		"587078" => t("Bilajari"),
		"587084" => t("Baku"),
		"587261" => t("Amirdzhan"),
		"824003" => t("Bakixanov"),
	);
}


function location_cities_list_az_bal () {
	return array (
	);
}


function location_cities_list_az_bar () {
	return array (
		"587057" => t("Barda"),
	);
}


function location_cities_list_az_bey () {
	return array (
		"148354" => t("Beyləqan"),
	);
}


function location_cities_list_az_bil () {
	return array (
		"148340" => t("Pushkino"),
	);
}


function location_cities_list_az_cab () {
	return array (
	);
}


function location_cities_list_az_das () {
	return array (
	);
}


function location_cities_list_az_dav () {
	return array (
		"586763" => t("Divichibazar"),
	);
}


function location_cities_list_az_fuz () {
	return array (
		"148106" => t("Fizuli"),
	);
}


function location_cities_list_az_gad () {
	return array (
	);
}


function location_cities_list_az_ga () {
	return array (
		"586523" => t("Ganja"),
	);
}


function location_cities_list_az_qob () {
	return array (
	);
}


function location_cities_list_az_gor () {
	return array (
	);
}


function location_cities_list_az_goy () {
	return array (
		"586427" => t("Geoktschai"),
	);
}


function location_cities_list_az_xan () {
	return array (
		"584716" => t("Yelenendorf"),
	);
}


function location_cities_list_az_hac () {
	return array (
		"585225" => t("Haciqabul"),
	);
}


function location_cities_list_az_imi () {
	return array (
		"147982" => t("Imishli"),
	);
}


function location_cities_list_az_ism () {
	return array (
	);
}


function location_cities_list_az_cal () {
	return array (
		"148290" => t("Dzhalilabad"),
	);
}


function location_cities_list_az_xac () {
	return array (
		"584717" => t("Xacmaz"),
	);
}


function location_cities_list_az_xiz () {
	return array (
	);
}


function location_cities_list_az_kur () {
	return array (
		"585763" => t("Kyurdarmir"),
	);
}


function location_cities_list_az_kal () {
	return array (
	);
}


function location_cities_list_az_la () {
	return array (
		"147622" => t("Lǝnkǝran"),
	);
}


function location_cities_list_az_lac () {
	return array (
	);
}


function location_cities_list_az_ler () {
	return array (
	);
}


function location_cities_list_az_lan () {
	return array (
	);
}


function location_cities_list_az_mas () {
	return array (
	);
}


function location_cities_list_az_mi () {
	return array (
		"585514" => t("Mingelchaur"),
	);
}


function location_cities_list_az_na () {
	return array (
	);
}


function location_cities_list_az_nx () {
	return array (
		"147429" => t("Nakhchivan"),
	);
}


function location_cities_list_az_75 () {
	return array (
	);
}


function location_cities_list_az_nef () {
	return array (
		"147425" => t("Neftcala"),
	);
}


function location_cities_list_az_ogu () {
	return array (
	);
}


function location_cities_list_az_qab () {
	return array (
	);
}


function location_cities_list_az_qax () {
	return array (
	);
}


function location_cities_list_az_qaz () {
	return array (
		"585226" => t("Qazax"),
	);
}


function location_cities_list_az_qba () {
	return array (
		"585221" => t("Quba"),
	);
}


function location_cities_list_az_qbi () {
	return array (
	);
}


function location_cities_list_az_qus () {
	return array (
		"585220" => t("Qusar"),
	);
}


function location_cities_list_az_sat () {
	return array (
		"147059" => t("Ahmadbayli"),
		"147288" => t("Saatli"),
	);
}


function location_cities_list_az_sab () {
	return array (
		"585187" => t("Sabirabad"),
	);
}


function location_cities_list_az_sal () {
	return array (
		"147271" => t("Salyan"),
	);
}


function location_cities_list_az_smx () {
	return array (
	);
}


function location_cities_list_az_sak () {
	return array (
	);
}


function location_cities_list_az_sa () {
	return array (
		"585170" => t("Sheki"),
	);
}


function location_cities_list_az_smi () {
	return array (
		"585156" => t("Shamakhi"),
	);
}


function location_cities_list_az_skr () {
	return array (
		"585152" => t("Shamkhor"),
	);
}


function location_cities_list_az_siy () {
	return array (
	);
}


function location_cities_list_az_sm () {
	return array (
		"584923" => t("Sumqayit"),
		"585379" => t("Haci Zeynalabdin"),
	);
}


function location_cities_list_az_tar () {
	return array (
		"584871" => t("Terter"),
	);
}


function location_cities_list_az_tov () {
	return array (
	);
}


function location_cities_list_az_uca () {
	return array (
		"584791" => t("Ujar"),
	);
}


function location_cities_list_az_xa () {
	return array (
		"146970" => t("Xankǝndi"),
	);
}


function location_cities_list_az_xci () {
	return array (
	);
}


function location_cities_list_az_xvd () {
	return array (
	);
}


function location_cities_list_az_yar () {
	return array (
	);
}


function location_cities_list_az_yev () {
	return array (
	);
}


function location_cities_list_az_ye () {
	return array (
		"584649" => t("Yevlakh"),
	);
}


function location_cities_list_az_zan () {
	return array (
	);
}


function location_cities_list_az_zaq () {
	return array (
		"584596" => t("Zaqatala"),
	);
}


function location_cities_list_az_zar () {
	return array (
	);
}


function location_cities_list_az_ss () {
	return array (
		"147105" => t("Shushi"),
	);
}


function location_cities_list_az_sus () {
	return array (
	);
}
