<?php

function location_cities_list_bf_11 () {
	return array (
		"2361845" => t("Bousse"),
		"2353197" => t("Zorgo"),
	);
}


function location_cities_list_bf_10 () {
	return array (
		"2360238" => t("Gourcy"),
		"2357043" => t("Ouahigouya"),
		"2354349" => t("Titao"),
		"2353688" => t("Yako"),
	);
}


function location_cities_list_bf_01 () {
	return array (
		"2361477" => t("Dedougou"),
		"2357163" => t("Nouna"),
		"2354176" => t("Tougan"),
	);
}


function location_cities_list_bf_04 () {
	return array (
		"2360615" => t("Garango"),
		"2358738" => t("Koupela"),
		"2354675" => t("Tenkodogo"),
	);
}


function location_cities_list_bf_06 () {
	return array (
		"2359317" => t("Kokologo"),
		"2358946" => t("Koudougou"),
		"2358382" => t("Leo"),
		"2356228" => t("Reo"),
	);
}


function location_cities_list_bf_07 () {
	return array (
		"2359227" => t("Kombissiri"),
		"2358100" => t("Manga"),
		"2356454" => t("Po"),
	);
}


function location_cities_list_bf_03 () {
	return array (
		"2357048" => t("Ouagadougou"),
	);
}


function location_cities_list_bf_05 () {
	return array (
		"2361946" => t("Boulsa"),
		"2359608" => t("Kaya"),
		"2359142" => t("Kongoussi"),
	);
}


function location_cities_list_bf_09 () {
	return array (
		"2362344" => t("Bobo-Dioulasso"),
		"2360073" => t("Hounde"),
		"2577164" => t("Orodara"),
	);
}


function location_cities_list_bf_08 () {
	return array (
		"2361373" => t("Diapaga"),
		"2360886" => t("Fada N'gourma"),
	);
}


function location_cities_list_bf_12 () {
	return array (
		"2361177" => t("Djibo"),
		"2361082" => t("Dori"),
	);
}


function location_cities_list_bf_02 () {
	return array (
		"2362909" => t("Banfora"),
	);
}


function location_cities_list_bf_13 () {
	return array (
		"2577162" => t("Gaoua"),
	);
}


