<?php


function location_cities_list_lk_2() {
  return array(
    "1232783" => "Nuwara Eliya",
    "1241622" => "Kandy",
    "1244596" => "Hatton",
    "1246000" => "Gampola",
    "1248749" => "Dambulla",
  );
}


function location_cities_list_lk_5() {
  return array(
    "1226260" => "Trincomalee",
    "1242110" => "Kalmunai",
    "1246924" => "Eravur Town",
    "1250161" => "Batticaloa",
    "1251459" => "Ampara",
  );
}


function location_cities_list_lk_7() {
  return array(
    "1251081" => "Anuradhapura",
  );
}


function location_cities_list_lk_6() {
  return array(
    "1229293" => "Puttalam",
    "1237980" => "Kurunegala",
    "1249145" => "Chilaw",
  );
}


function location_cities_list_lk_4() {
  return array(
    "1225018" => "Vavuniya",
    "1225142" => "Valvedditturai",
    "1229989" => "Point Pedro",
    "1242833" => "Jaffna",
  );
}


function location_cities_list_lk_9() {
  return array(
    "1228730" => "Ratnapura",
  );
}


function location_cities_list_lk_8() {
  return array(
    "1250615" => "Badulla",
  );
}


function location_cities_list_lk_3() {
  return array(
    "1223738" => "Weligama",
    "1235846" => "Matara",
    "1246294" => "Galle",
    "1249978" => "Bentota",
    "1251574" => "Ambalangoda",
  );
}


function location_cities_list_lk_1() {
  return array(
    "1223648" => "Welisara",
    "1224085" => "Wattala",
    "1230089" => "Pita Kotte",
    "1230613" => "Peliyagoda",
    "1231410" => "Panadura",
    "1233369" => "Negombo",
    "1234378" => "Mulleriyawa",
    "1234633" => "Moratuwa",
    "1236854" => "Maharagama",
    "1238992" => "Sri Jayewardenepura Kotte",
    "1239047" => "Kotikawatta",
    "1239593" => "Kolonnawa",
    "1240622" => "Kelaniya",
    "1240935" => "Katunayaka North",
    "1241750" => "Kandana",
    "1241964" => "Kalutara",
    "1242835" => "Ja Ela",
    "1243936" => "Homagama",
    "1244397" => "Hendala",
    "1244773" => "Hanwella Ihala",
    "1246321" => "Galkissa",
    "1248991" => "Colombo",
    "1249931" => "Beruwala",
    "1250164" => "Battaramulla South",
  );
}
