<?php

function location_cities_list_th_83 () {
	return array (
		"7091861" => t("Ban Chalong"),
		"7091912" => t("Ban Ratsada"),
		"1117656" => t("Ban Talat Nua"),
		"1117652" => t("Ban Talat Yai"),
		"1153035" => t("Kathu"),
		"1151254" => t("Phuket"),
		"6696291" => t("Wichit"),
	);
}


function location_cities_list_th_77 () {
	return array (
		"1157662" => t("Bang Saphan"),
		"1153269" => t("Hua Hin"),
		"1152562" => t("Kui Buri"),
		"1151074" => t("Prachuap Khiri Khan"),
		"1151063" => t("Pran Buri"),
		"1117823" => t("Sam Roi Yot"),
	);
}


function location_cities_list_th_76 () {
	return array (
		"1153807" => t("Cha-am"),
		"1152919" => t("Khao Yoi"),
		"1149698" => t("Phetchaburi"),
		"1605467" => t("Tha Yang"),
	);
}


function location_cities_list_th_92 () {
	return array (
		"1153241" => t("Huai Yot"),
		"1150007" => t("Trang"),
	);
}


function location_cities_list_th_80 () {
	return array (
		"1151933" => t("Nakhon Si Thammarat"),
		"1608033" => t("Pak Phanang"),
		"1150921" => t("Ron Phibun"),
		"1150085" => t("Thung Song"),
	);
}


function location_cities_list_th_52 () {
	return array (
		"1152473" => t("Lampang"),
		"1150154" => t("Thoen"),
	);
}


function location_cities_list_th_61 () {
	return array (
		"1150210" => t("Thap Than"),
		"1605221" => t("Uthai Thani"),
	);
}


function location_cities_list_th_71 () {
	return array (
		"1153850" => t("Bo Phloi"),
		"1153081" => t("Kanchanaburi"),
		"1150275" => t("Tha Maka"),
		"1150246" => t("Tha Muang"),
	);
}


function location_cities_list_th_63 () {
	return array (
		"1154677" => t("Ban Tak"),
		"1152202" => t("Mae Ramat"),
		"1152188" => t("Mae Sot"),
		"1150490" => t("Tak"),
	);
}


function location_cities_list_th_84 () {
	return array (
		"1156046" => t("Ban Na San"),
		"1154689" => t("Ko Samui"),
		"1151211" => t("Phunphin"),
		"1150515" => t("Surat Thani"),
	);
}


function location_cities_list_th_64 () {
	return array (
		"1156257" => t("Ban Na"),
		"1150681" => t("Sawankhalok"),
		"1150624" => t("Si Satchanalai"),
		"1150533" => t("Sukhothai"),
	);
}


function location_cities_list_th_50 () {
	return array (
		"1153671" => t("Chiang Mai"),
		"1153386" => t("Hang Dong"),
		"1150732" => t("San Kamphaeng"),
		"1150728" => t("San Pa Tong"),
	);
}


function location_cities_list_th_70 () {
	return array (
		"1155139" => t("Ban Pong"),
		"1157683" => t("Bang Phae"),
		"1153646" => t("Chom Bueng"),
		"1153513" => t("Damnoen Saduak"),
		"1151340" => t("Photharam"),
		"1150954" => t("Ratchaburi"),
	);
}


function location_cities_list_th_85 () {
	return array (
		"1150965" => t("Ranong"),
	);
}


function location_cities_list_th_56 () {
	return array (
		"1153464" => t("Dok Kham Tai"),
		"1151426" => t("Phayao"),
	);
}


function location_cities_list_th_51 () {
	return array (
		"1152468" => t("Lamphun"),
		"1151528" => t("Pa Sang"),
	);
}


function location_cities_list_th_57 () {
	return array (
		"1153669" => t("Chiang Rai"),
		"1152227" => t("Mae Chan"),
		"1152194" => t("Mae Sai"),
	);
}


function location_cities_list_th_60 () {
	return array (
		"1152377" => t("Lat Yao"),
		"1608527" => t("Nakhon Sawan"),
	);
}


function location_cities_list_th_86 () {
	return array (
		"1153557" => t("Chumphon"),
		"1152432" => t("Lang Suan"),
	);
}


function location_cities_list_th_81 () {
	return array (
		"1152633" => t("Krabi"),
	);
}


function location_cities_list_th_62 () {
	return array (
		"1153090" => t("Kamphaeng Phet"),
		"1152953" => t("Khanu Woralaksaburi"),
	);
}


function location_cities_list_th_46 () {
	return array (
		"1610469" => t("Kalasin"),
		"1610459" => t("Kamalasai"),
		"1609990" => t("Khao Wong"),
		"1609345" => t("Kuchinarai"),
		"1595679" => t("Nong Kung Si"),
	);
}


function location_cities_list_th_41 () {
	return array (
		"1619650" => t("Ban Dung"),
		"1599640" => t("Ban Nong Wua So"),
		"1614336" => t("Ban Phan Don"),
		"1609324" => t("Kut Chap"),
		"1608462" => t("Nam Som"),
		"1605239" => t("Udon Thani"),
	);
}


function location_cities_list_th_90 () {
	return array (
		"1601579" => t("Ban Mai"),
		"1610780" => t("Hat Yai"),
		"1607068" => t("Ranot"),
		"1606939" => t("Sadao"),
		"1606147" => t("Songkhla"),
	);
}


function location_cities_list_th_30 () {
	return array (
		"1948015" => t("Amphoe Sikhiu"),
		"1603235" => t("Ban Huai Thalaeng"),
		"1611492" => t("Bua Yai"),
		"1611135" => t("Chok Chai"),
		"1610963" => t("Dan Khun Thot"),
		"1609795" => t("Khon Buri"),
		"1608529" => t("Nakhon Ratchasima"),
		"1608136" => t("Non Sung"),
		"1608057" => t("Pak Chong"),
	);
}


function location_cities_list_th_11 () {
	return array (
		"1620919" => t("Ban Bang Bo (1)"),
		"1604452" => t("Ban Khlong Bang Sao Thong"),
		"1607508" => t("Phra Pradaeng"),
		"1606590" => t("Samut Prakan"),
	);
}


function location_cities_list_th_39 () {
	return array (
		"1604654" => t("Na Klang"),
		"1608269" => t("Nong Bua Lamphu"),
	);
}


function location_cities_list_th_35 () {
	return array (
		"1604769" => t("Yasothon"),
	);
}


function location_cities_list_th_94 () {
	return array (
		"1607978" => t("Pattani"),
		"1604771" => t("Yaring"),
	);
}


function location_cities_list_th_95 () {
	return array (
		"1611635" => t("Betong"),
		"1604870" => t("Yala"),
	);
}


function location_cities_list_th_15 () {
	return array (
		"1605018" => t("Wiset Chaichan"),
	);
}


function location_cities_list_th_67 () {
	return array (
		"1611106" => t("Chon Daen"),
		"1609043" => t("Lom Sak"),
		"1608191" => t("Nong Phai"),
		"1607737" => t("Phetchabun"),
		"1605024" => t("Wichian Buri"),
	);
}


function location_cities_list_th_34 () {
	return array (
		"1610940" => t("Det Udom"),
		"1607730" => t("Phibun Mangsahan"),
		"1605245" => t("Ubon Ratchathani"),
		"1605069" => t("Warin Chamrap"),
	);
}


function location_cities_list_th_42 () {
	return array (
		"1609071" => t("Loei"),
		"1607435" => t("Phu Kradueng"),
		"1605102" => t("Wang Saphung"),
	);
}


function location_cities_list_th_14 () {
	return array (
		"1620875" => t("Ban Bang Kadi Pathum Thani"),
		"1619616" => t("Bang Ban"),
		"1619369" => t("Bang Pa-in"),
		"1608541" => t("Nakhon Luang"),
		"1607865" => t("Phak Hai"),
		"1607532" => t("Phra Nakhon Si Ayutthaya"),
		"1605509" => t("Tha Ruea"),
		"1605118" => t("Wang Noi"),
	);
}


function location_cities_list_th_27 () {
	return array (
		"1621020" => t("Aranyaprathet"),
		"1606807" => t("Sa Kaeo"),
		"1605119" => t("Wang Nam Yen"),
	);
}


function location_cities_list_th_53 () {
	return array (
		"1605215" => t("Uttaradit"),
	);
}


function location_cities_list_th_23 () {
	return array (
		"1605279" => t("Trat"),
	);
}


function location_cities_list_th_66 () {
	return array (
		"1619400" => t("Bang Mun Nak"),
		"1607725" => t("Phichit"),
		"1605754" => t("Taphan Hin"),
		"1605538" => t("Thap Khlo"),
	);
}


function location_cities_list_th_22 () {
	return array (
		"1611269" => t("Chanthaburi"),
		"1609278" => t("Laem Sing"),
		"1605601" => t("Tha Mai"),
	);
}


function location_cities_list_th_43 () {
	return array (
		"1608232" => t("Nong Khai"),
		"1607615" => t("Phon Charoen"),
		"1605677" => t("Tha Bo"),
	);
}


function location_cities_list_th_96 () {
	return array (
		"1608409" => t("Narathiwat"),
		"1607083" => t("Ra-ngae"),
		"1606050" => t("Su-ngai Kolok"),
		"1605957" => t("Tak Bai"),
	);
}


function location_cities_list_th_32 () {
	return array (
		"1606030" => t("Surin"),
	);
}


function location_cities_list_th_72 () {
	return array (
		"1606033" => t("Suphan Buri"),
	);
}


function location_cities_list_th_33 () {
	return array (
		"1610227" => t("Kantharalak"),
		"1606239" => t("Si Sa Ket"),
	);
}


function location_cities_list_th_20 () {
	return array (
		"1620442" => t("Ban Talat Bueng"),
		"1619423" => t("Bang Lamung"),
		"1611110" => t("Chon Buri"),
		"1607793" => t("Phan Thong"),
		"1607838" => t("Phanat Nikhom"),
		"1614295" => t("Phatthaya"),
		"1606386" => t("Sattahip"),
		"1606250" => t("Si Racha"),
	);
}


function location_cities_list_th_17 () {
	return array (
		"1619281" => t("Bang Racham"),
		"1606270" => t("Sing Buri"),
	);
}


function location_cities_list_th_47 () {
	return array (
		"1606790" => t("Sakon Nakhon"),
		"1606350" => t("Sawang Daen Din"),
	);
}


function location_cities_list_th_91 () {
	return array (
		"1606376" => t("Satun"),
	);
}


function location_cities_list_th_19 () {
	return array (
		"1616658" => t("Ban Mo"),
		"1610503" => t("Kaeng Khoi"),
		"1608239" => t("Nong Khae"),
		"1607512" => t("Phra Phutthabat"),
		"1606418" => t("Saraburi"),
	);
}


function location_cities_list_th_75 () {
	return array (
		"1606586" => t("Samut Songkhram"),
	);
}


function location_cities_list_th_74 () {
	return array (
		"1614465" => t("Ban Phaeo"),
		"1609395" => t("Krathum Baen"),
		"1606588" => t("Samut Sakhon"),
	);
}


function location_cities_list_th_73 () {
	return array (
		"1619415" => t("Bang Len"),
		"1608534" => t("Nakhon Pathom"),
		"1606638" => t("Sam Phran"),
	);
}


function location_cities_list_th_45 () {
	return array (
		"1613284" => t("Ban Selaphum"),
		"1610185" => t("Kaset Wisai"),
		"1607001" => t("Roi Et"),
	);
}


function location_cities_list_th_21 () {
	return array (
		"1620254" => t("Ban Chang"),
		"1609610" => t("Klaeng"),
		"1607017" => t("Rayong"),
	);
}


function location_cities_list_th_31 () {
	return array (
		"1611453" => t("Buriram"),
		"1608424" => t("Nang Rong"),
		"1607257" => t("Prakhon Chai"),
	);
}


function location_cities_list_th_25 () {
	return array (
		"1610538" => t("Kabin Buri"),
		"1607280" => t("Prachin Buri"),
	);
}


function location_cities_list_th_36 () {
	return array (
		"1611407" => t("Chaiyaphum"),
		"1610505" => t("Kaeng Khro"),
		"1610187" => t("Kaset Sombun"),
		"1607439" => t("Phu Khiao"),
	);
}


function location_cities_list_th_54 () {
	return array (
		"1610943" => t("Den Chai"),
		"1607552" => t("Phrae"),
	);
}


function location_cities_list_th_65 () {
	return array (
		"1619437" => t("Bang Krathum"),
		"1619276" => t("Bang Rakam"),
		"1607708" => t("Phitsanulok"),
	);
}


function location_cities_list_th_93 () {
	return array (
		"1607779" => t("Phatthalung"),
	);
}


function location_cities_list_th_24 () {
	return array (
		"1619363" => t("Bang Pakong"),
		"1611439" => t("Chachoengsao"),
		"1607801" => t("Phanom Sarakham"),
	);
}


function location_cities_list_th_13 () {
	return array (
		"1617111" => t("Ban Lam Luk Ka"),
		"1613769" => t("Ban Rangsit"),
		"1609899" => t("Khlong Luang"),
		"1607983" => t("Pathum Thani"),
	);
}


function location_cities_list_th_12 () {
	return array (
		"1619602" => t("Bang Bua Thong"),
		"1619434" => t("Bang Kruai"),
		"1608133" => t("Mueang Nonthaburi"),
		"1608048" => t("Pak Kret"),
	);
}


function location_cities_list_th_55 () {
	return array (
		"1608452" => t("Nan"),
	);
}


function location_cities_list_th_48 () {
	return array (
		"1608531" => t("Nakhon Phanom"),
	);
}


function location_cities_list_th_26 () {
	return array (
		"1608539" => t("Nakhon Nayok"),
	);
}


function location_cities_list_th_49 () {
	return array (
		"1608597" => t("Mukdahan"),
	);
}


function location_cities_list_th_44 () {
	return array (
		"1608900" => t("Maha Sarakham"),
	);
}


function location_cities_list_th_16 () {
	return array (
		"1611424" => t("Chai Badan"),
		"1609032" => t("Lop Buri"),
	);
}


function location_cities_list_th_10 () {
	return array (
		"1609350" => t("Bangkok"),
	);
}


function location_cities_list_th_40 () {
	return array (
		"1614455" => t("Ban Phai"),
		"1611026" => t("Chum Phae"),
		"1609776" => t("Khon Kaen"),
	);
}


function location_cities_list_th_18 () {
	return array (
		"1611416" => t("Chai Nat"),
	);
}


function location_cities_list_th_37 () {
	return array (
		"1621060" => t("Amnat Charoen"),
	);
}


