<?php

function location_cities_list_pw_002 () {
	return array (
	);
}


function location_cities_list_pw_004 () {
	return array (
	);
}


function location_cities_list_pw_010 () {
	return array (
	);
}


function location_cities_list_pw_050 () {
	return array (
	);
}


function location_cities_list_pw_100 () {
	return array (
	);
}


function location_cities_list_pw_150 () {
	return array (
	);
}


function location_cities_list_pw_212 () {
	return array (
		"7303944" => t("Melekeok"),
	);
}


function location_cities_list_pw_214 () {
	return array (
	);
}


function location_cities_list_pw_218 () {
	return array (
	);
}


function location_cities_list_pw_222 () {
	return array (
	);
}


function location_cities_list_pw_224 () {
	return array (
	);
}


function location_cities_list_pw_226 () {
	return array (
	);
}


function location_cities_list_pw_227 () {
	return array (
	);
}


function location_cities_list_pw_228 () {
	return array (
	);
}


function location_cities_list_pw_350 () {
	return array (
	);
}


function location_cities_list_pw_370 () {
	return array (
	);
}
