<?php

function location_cities_list_re_re () {
	return array (
		"935214" => t("Saint-Pierre"),
		"935221" => t("Saint-Paul"),
		"935223" => t("Saint-Louis"),
		"935225" => t("Saint-Leu"),
		"935227" => t("Saint-Joseph"),
		"935248" => t("Sainte-Suzanne"),
		"935255" => t("Sainte-Marie"),
		"935264" => t("Saint-Denis"),
		"935267" => t("Saint-Benoit"),
		"935268" => t("Saint-Andre"),
		"935582" => t("Le Tampon"),
		"935616" => t("Le Port"),
		"935691" => t("La Possession"),
	);
}
