<?php

function location_cities_list_nl_fr () {
	return array (
		"2744194" => t("Wolvega"),
		"2747063" => t("Sneek"),
		"2751792" => t("Leeuwarden"),
		"2754669" => t("Heerenveen"),
		"2754817" => t("Harlingen"),
		"2756644" => t("Drachten"),
	);
}


function location_cities_list_nl_gr () {
	return array (
		"2744344" => t("Winschoten"),
		"2745461" => t("Vlagtwedde"),
		"2745783" => t("Veendam"),
		"2746860" => t("Stadskanaal"),
		"2751834" => t("Leek"),
		"2752420" => t("Korrewegwijk"),
		"2753706" => t("Hoogezand"),
		"2754841" => t("Haren"),
		"2755251" => t("Groningen"),
		"2757340" => t("Delfzijl"),
	);
}


function location_cities_list_nl_nb () {
	return array (
		"2743619" => t("Zundert"),
		"2744257" => t("Woensdrecht"),
		"2744827" => t("Werkendam"),
		"2745123" => t("Waalwijk"),
		"2745127" => t("Waalre"),
		"2745154" => t("Vught"),
		"2745706" => t("Veldhoven"),
		"2745726" => t("Veghel"),
		"2745860" => t("Valkenswaard"),
		"2746005" => t("Uden"),
		"2746215" => t("Tongelre"),
		"2746301" => t("Tilburg"),
		"2746804" => t("Steenbergen"),
		"2747021" => t("Someren"),
		"2747227" => t("Sint-Oedenrode"),
		"2747351" => t("'s-Hertogenbosch"),
		"2747584" => t("Schijndel"),
		"2747858" => t("Rucphen"),
		"2747930" => t("Roosendaal"),
		"2749234" => t("Oss"),
		"2749450" => t("Oosterhout"),
		"2749680" => t("Oisterwijk"),
		"2749780" => t("Nuenen"),
		"2751456" => t("Loon op Zand"),
		"2754066" => t("Hilvarenbeek"),
		"2754447" => t("Helmond"),
		"2754635" => t("Heesch"),
		"2755464" => t("Goirle"),
		"2755619" => t("Geldrop"),
		"2755669" => t("Geertruidenberg"),
		"2756253" => t("Eindhoven"),
		"2756342" => t("Eersel"),
		"2756569" => t("Drimmelen"),
		"2756723" => t("Dongen"),
		"2757874" => t("Cuijk"),
		"2757890" => t("Cranendonck"),
		"2758401" => t("Breda"),
		"2758460" => t("Boxtel"),
		"2758878" => t("Bladel"),
		"2759040" => t("Best"),
		"2759132" => t("Bergeyk"),
		"2759145" => t("Bergen op Zoom"),
		"2759621" => t("Asten"),
	);
}


function location_cities_list_nl_nh () {
	return array (
		"2744042" => t("Zandvoort"),
		"2744114" => t("Zaanstad"),
		"2744118" => t("Zaandam"),
		"2744904" => t("Weesp"),
		"2745340" => t("Volendam"),
		"2745673" => t("Velsen-Zuid"),
		"2745973" => t("Uithoorn"),
		"2747720" => t("Schagen"),
		"2748413" => t("Purmerend"),
		"2750521" => t("Naarden"),
		"2753468" => t("Huizen"),
		"2753638" => t("Hoorn"),
		"2753801" => t("Hoofddorp"),
		"2754064" => t("Hilversum"),
		"2754516" => t("Heiloo"),
		"2754659" => t("Heerhugowaard"),
		"2754692" => t("Heemstede"),
		"2754697" => t("Heemskerk"),
		"2754837" => t("Harenkarspel"),
		"2755003" => t("Haarlem"),
		"2756077" => t("Enkhuizen"),
		"2756888" => t("Diemen"),
		"2757220" => t("Den Helder"),
		"2757991" => t("Castricum"),
		"2758064" => t("Bussum"),
		"2758245" => t("Broek op Langedijk"),
		"2758258" => t("Broek in Waterland"),
		"2758804" => t("Bloemendaal"),
		"2758998" => t("Beverwijk"),
		"2759794" => t("Amsterdam"),
		"2759798" => t("Amstelveen"),
		"2759899" => t("Alkmaar"),
		"2760134" => t("Aalsmeer"),
		"6544881" => t("Amsterdam-Zuidoost"),
	);
}


function location_cities_list_nl_dr () {
	return array (
		"2750947" => t("Meppel"),
		"2753719" => t("Hoogeveen"),
		"2756136" => t("Emmen"),
		"2758621" => t("Borger"),
		"2759633" => t("Assen"),
		"2759746" => t("Anloo"),
	);
}


function location_cities_list_nl_fl () {
	return array (
		"2743997" => t("Zeewolde"),
		"2745932" => t("Urk"),
		"2751738" => t("Lelystad"),
		"2756139" => t("Emmeloord"),
		"2756559" => t("Dronten"),
		"2759879" => t("Almere Stad"),
	);
}


function location_cities_list_nl_ge () {
	return array (
		"2743608" => t("Zutphen"),
		"2743949" => t("Zevenaar"),
		"2744102" => t("Zaltbommel"),
		"2744324" => t("Wisch"),
		"2744332" => t("Winterswijk"),
		"2744514" => t("Wijchen"),
		"2744675" => t("Westervoort"),
		"2745088" => t("Wageningen"),
		"2745297" => t("Voorst"),
		"2745677" => t("Velp"),
		"2746331" => t("Tiel"),
		"2748392" => t("Putten"),
		"2749668" => t("Oldebroek"),
		"2749756" => t("Nunspeet"),
		"2750053" => t("Nijmegen"),
		"2750065" => t("Nijkerk"),
		"2751582" => t("Lindenholt"),
		"2751651" => t("Lichtenvoorde"),
		"2753587" => t("Horst"),
		"2754681" => t("Heerde"),
		"2754848" => t("Harderwijk"),
		"2755272" => t("Groesbeek"),
		"2755599" => t("Gendringen"),
		"2755633" => t("Geldermalsen"),
		"2756039" => t("Ermelo"),
		"2756059" => t("Epe"),
		"2756161" => t("Elst"),
		"2756232" => t("Elburg"),
		"2756295" => t("Eibergen"),
		"2756429" => t("Ede"),
		"2756507" => t("Duiven"),
		"2756539" => t("Druten"),
		"2756767" => t("Doetinchem"),
		"2757872" => t("Culemborg"),
		"2758177" => t("Brummen"),
		"2759016" => t("Beuningen"),
		"2759407" => t("Barneveld"),
		"2759661" => t("Arnhem"),
		"2759706" => t("Apeldoorn"),
		"2760123" => t("Aalten"),
	);
}


function location_cities_list_nl_li () {
	return array (
		"2744911" => t("Weert"),
		"2745634" => t("Venray"),
		"2745641" => t("Venlo"),
		"2746504" => t("Tegelen"),
		"2747203" => t("Sittard"),
		"2748000" => t("Roermond"),
		"2749753" => t("Nuth"),
		"2750467" => t("Nederweert"),
		"2751037" => t("Meerssen"),
		"2751283" => t("Maastricht"),
		"2752923" => t("Kerkrade"),
		"2753996" => t("Hoensbroek"),
		"2754652" => t("Heerlen"),
		"2755584" => t("Gennep"),
		"2758174" => t("Brunssum"),
		"2758602" => t("Born"),
		"2759350" => t("Beek"),
	);
}


function location_cities_list_nl_ov () {
	return array (
		"2743477" => t("Zwolle"),
		"2744549" => t("Wierden"),
		"2746133" => t("Tubbergen"),
		"2746766" => t("Steenwijk"),
		"2746839" => t("Staphorst"),
		"2748371" => t("Raalte"),
		"2749644" => t("Oldenzaal"),
		"2751424" => t("Losser"),
		"2753106" => t("Kampen"),
		"2754394" => t("Hengelo"),
		"2754861" => t("Hardenberg"),
		"2755030" => t("Haaksbergen"),
		"2756071" => t("Enschede"),
		"2756987" => t("Deventer"),
		"2757850" => t("Dalfsen"),
		"2758598" => t("Borne"),
		"2759887" => t("Almelo"),
	);
}


function location_cities_list_nl_ut () {
	return array (
		"2743977" => t("Zeist"),
		"2744248" => t("Woerden"),
		"2744483" => t("Wijk bij Duurstede"),
		"2745580" => t("Vianen"),
		"2745774" => t("Veenendaal"),
		"2745912" => t("Utrecht"),
		"2747034" => t("Soest"),
		"2748185" => t("Rhenen"),
		"2750325" => t("Nieuwegein"),
		"2750815" => t("Mijdrecht"),
		"2751316" => t("Maarssen"),
		"2751687" => t("Leusden"),
		"2753355" => t("IJsselstein"),
		"2753557" => t("Houten"),
		"2756619" => t("Driebergen-Rijsenburg"),
		"2757783" => t("De Bilt"),
		"2758104" => t("Bunschoten"),
		"2759544" => t("Baarn"),
		"2759821" => t("Amersfoort"),
	);
}


function location_cities_list_nl_ze () {
	return array (
		"2745392" => t("Vlissingen"),
		"2745739" => t("Veere"),
		"2746420" => t("Terneuzen"),
		"2750896" => t("Middelburg"),
		"2755476" => t("Goes"),
		"2758587" => t("Borssele"),
	);
}


function location_cities_list_nl_zh () {
	return array (
		"2743493" => t("Zwijndrecht"),
		"2743856" => t("Zoetermeer"),
		"2744991" => t("Wassenaar"),
		"2745096" => t("Waddinxveen"),
		"2745301" => t("Voorschoten"),
		"2745311" => t("Voorhout"),
		"2745321" => t("Voorburg"),
		"2745467" => t("Vlaardingen"),
		"2746932" => t("Spijkenisse"),
		"2747169" => t("Sliedrecht"),
		"2747364" => t("'s-Gravenzande"),
		"2747373" => t("The Hague"),
		"2747596" => t("Schiedam"),
		"2747599" => t("Scheveningen"),
		"2747891" => t("Rotterdam"),
		"2748076" => t("Rijswijk"),
		"2748172" => t("Ridderkerk"),
		"2748178" => t("Rhoon"),
		"2748591" => t("Pijnacker"),
		"2748729" => t("Papendrecht"),
		"2749182" => t("Oud-Beijerland"),
		"2749723" => t("Oegstgeest"),
		"2749811" => t("Noordwijkerhout"),
		"2749812" => t("Noordwijk-Binnen"),
		"2750523" => t("Naaldwijk"),
		"2750884" => t("Middelharnis"),
		"2751285" => t("Maassluis"),
		"2751547" => t("Lisse"),
		"2751771" => t("Leiderdorp"),
		"2751773" => t("Leiden"),
		"2751808" => t("Leerdam"),
		"2752264" => t("Krimpen aan den IJssel"),
		"2753010" => t("Katwijk aan Zee"),
		"2754073" => t("Hillegom"),
		"2754408" => t("Hendrik-Ido-Ambacht"),
		"2754454" => t("Hellevoetsluis"),
		"2755420" => t("Gouda"),
		"2755434" => t("Gorinchem"),
		"2756669" => t("Dordrecht"),
		"2757345" => t("Delft"),
		"2757347" => t("Delfshaven"),
		"2758012" => t("Capelle aan den IJssel"),
		"2758547" => t("Boskoop"),
		"2758765" => t("Bodegraven"),
		"2759113" => t("Bergschenhoek"),
		"2759178" => t("Benthuizen"),
		"2759426" => t("Barendrecht"),
		"2759875" => t("Alphen aan den Rijn"),
		"2759915" => t("Alblasserdam"),
		"6929992" => t("Berkel en Rodenrijs"),
		"6941548" => t("Ypenburg"),
	);
}
