<?php

function location_cities_list_ru_tve () {
	return array (
		"576566" => t("Bezhetsk"),
		"575349" => t("Bologoye"),
		"551986" => t("Kashin"),
		"548652" => t("Kimry"),
		"545673" => t("Konakovo"),
		"522775" => t("Nelidovo"),
		"514259" => t("Ostashkov"),
		"499717" => t("Rzhev"),
		"481985" => t("Torzhok"),
		"480060" => t("Tver"),
		"452949" => t("Udomlya"),
		"470252" => t("Vyshniy Volochek"),
	);
}


function location_cities_list_ru_spe () {
	return array (
		"8504953" => t("Admiralteisky"),
		"580222" => t("Avtovo"),
		"8504960" => t("Centralniy"),
		"567311" => t("Dachnoye"),
		"560142" => t("Gorelovo"),
		"559029" => t("Grazhdanka"),
		"546225" => t("Kolomyagi"),
		"546105" => t("Kolpino"),
		"535729" => t("Komendantsky aerodrom"),
		"8504952" => t("Krasnogvargeisky"),
		"542000" => t("Krasnoye Selo"),
		"540771" => t("Kronshtadt"),
		"539061" => t("Kupchino"),
		"534341" => t("Lomonosov"),
		"527361" => t("Metallostroy"),
		"519711" => t("Novaya Derevnya"),
		"873901" => t("Obukhovo"),
		"513471" => t("Ozerki"),
		"512052" => t("Pavlovsk"),
		"510291" => t("Peterhof"),
		"510225" => t("Petrodvorets"),
		"8504948" => t("Petrogradka"),
		"504003" => t("Pushkin"),
		"498817" => t("Saint Petersburg"),
		"496478" => t("Sestroretsk"),
		"493316" => t("Shushary"),
		"490377" => t("Sosnovaya Polyana"),
		"461698" => t("Sosnovka"),
		"489226" => t("Staraya Derevnya"),
		"478724" => t("Uritsk"),
		"8504949" => t("Vasyl'evsky Ostrov"),
	);
}


function location_cities_list_ru_rya () {
	return array (
		"551891" => t("Kasimov"),
		"518602" => t("Novomichurinsk"),
		"500096" => t("Ryazan'"),
		"500047" => t("Ryazhsk"),
		"499975" => t("Rybnoye"),
		"461699" => t("Sasovo"),
		"494427" => t("Shilovo"),
		"492376" => t("Skopin"),
	);
}


function location_cities_list_ru_mow () {
	return array (
		"472072" => t("Altuf'yevskiy"),
		"582266" => t("Amin'yevo"),
		"506117" => t("Annino"),
		"579870" => t("Babushkin"),
		"576432" => t("Bibirevo"),
		"576279" => t("Biryulevo"),
		"571741" => t("Brateyevo"),
		"570636" => t("Businovo"),
		"6418146" => t("Chertanovo Yuzhnoye"),
		"566976" => t("Davydkovo"),
		"560465" => t("Gol'yanovo"),
		"555129" => t("Ivanovskoye"),
		"553034" => t("Kapotnya"),
		"550280" => t("Khimki"),
		"546244" => t("Kolomenskoye"),
		"506043" => t("Kotlovka"),
		"543344" => t("Kozeyevo"),
		"537832" => t("Kuz'minki"),
		"536398" => t("Lefortovo"),
		"535966" => t("Leonovo"),
		"535330" => t("Lianozovo"),
		"535270" => t("Likhobory"),
		"533067" => t("Luzhniki"),
		"532535" => t("Lyublino"),
		"529334" => t("Mar'ina Roshcha"),
		"529237" => t("Mar'ino"),
		"528454" => t("Matveyevskoye"),
		"6418787" => t("Metrogorodok"),
		"527057" => t("Mikhalkovo"),
		"524901" => t("Moscow"),
		"472732" => t("Nagornyy"),
		"521500" => t("Nikol'skoye"),
		"521416" => t("Nikulino"),
		"511510" => t("Novo-Peredelkino"),
		"518740" => t("Novokhovrino"),
		"518657" => t("Novokuz'minki"),
		"473127" => t("Novovladykino"),
		"517161" => t("Novyye Cheremushki"),
		"517121" => t("Novyye Kuz'minki"),
		"516264" => t("Ochakovo-Matveyevskoye"),
		"6418220" => t("Orekhovo-Borisovo"),
		"515027" => t("Orekhovo-Borisovo Severnoye"),
		"514284" => t("Ostankinskiy"),
		"513896" => t("Otradnoye"),
		"511153" => t("Perovo"),
		"507338" => t("Pokrovskoye-Streshnevo"),
		"502971" => t("Ramenki"),
		"501187" => t("Rostokino"),
		"500843" => t("Rublevo"),
		"508751" => t("Ryazanskiy"),
		"496456" => t("Setun'"),
		"496348" => t("Severnyy"),
		"495136" => t("Shchukino"),
		"491895" => t("Slobodka"),
		"491280" => t("Sokol"),
		"491250" => t("Sokol'niki"),
		"490971" => t("Solntsevo"),
		"487150" => t("Strogino"),
		"485630" => t("Sviblovo"),
		"484912" => t("Taganskiy"),
		"483826" => t("Tekstil'shchiki"),
		"483551" => t("Teplyy Stan"),
		"481453" => t("Troparevo"),
		"536164" => t("Tsaritsyno"),
		"477377" => t("Vagonoremont"),
		"476368" => t("Vatutino"),
		"473972" => t("Veshnyaki"),
		"473021" => t("Vnukovo"),
		"472079" => t("Vorob'yevo"),
		"470451" => t("Vykhino-Zhulebino"),
		"530088" => t("Yaroslavskiy"),
		"468809" => t("Yasenevo"),
		"6418201" => t("Zagor'ye"),
		"465057" => t("Zamoskvorech'ye"),
		"566809" => t("Zapadnoye Degunino"),
		"463829" => t("Zelenograd"),
		"462745" => t("Zhulebino"),
		"461835" => t("Zyablikovo"),
		"461740" => t("Zyuzino"),
	);
}


function location_cities_list_ru_ros () {
	return array (
		"583673" => t("Aksay"),
		"580054" => t("Azov"),
		"579771" => t("Bagayevskaya"),
		"578740" => t("Bataysk"),
		"578155" => t("Belaya Kalitva"),
		"565348" => t("Donetsk"),
		"558082" => t("Gukovo"),
		"553399" => t("Kamensk-Shakhtinskiy"),
		"545277" => t("Konstantinovsk"),
		"541404" => t("Krasnyy Sulin"),
		"526558" => t("Millerovo"),
		"525162" => t("Morozovsk"),
		"518970" => t("Novocherkassk"),
		"517963" => t("Novoshakhtinsk"),
		"514796" => t("Orlovskiy"),
		"802714" => t("Persianovka"),
		"504831" => t("Proletarsk"),
		"501175" => t("Rostov-na-Donu"),
		"499161" => t("Sal'sk"),
		"497218" => t("Semikarakorsk"),
		"496015" => t("Shakhty"),
		"484907" => t("Taganrog"),
		"480876" => t("Tsimlyansk"),
		"472761" => t("Volgodonsk"),
		"468307" => t("Yegorlykskaya"),
		"463637" => t("Zernograd"),
		"462522" => t("Zimovniki"),
		"461910" => t("Zverevo"),
	);
}


function location_cities_list_ru_mos () {
	return array (
		"582846" => t("Alekseyevka"),
		"581928" => t("Andreyevskoye"),
		"819552" => t("Annino"),
		"581321" => t("Aprelevka"),
		"579464" => t("Balashikha"),
		"577901" => t("Beloozerskiy"),
		"541406" => t("Biryulevo Zapadnoye"),
		"575505" => t("Bogorodskoye"),
		"574675" => t("Bol'shaya Setun'"),
		"571557" => t("Bronnitsy"),
		"569591" => t("Chekhov"),
		"569273" => t("Cheremushki"),
		"568808" => t("Chernogolovka"),
		"566854" => t("Dedovsk"),
		"565955" => t("Dmitrov"),
		"565614" => t("Dolgoprudnyy"),
		"565381" => t("Domodedovo"),
		"565197" => t("Dorogomilovo"),
		"564719" => t("Dubna"),
		"563705" => t("Dzerzhinskiy"),
		"563524" => t("Elektrogorsk"),
		"563523" => t("Elektrostal'"),
		"563522" => t("Elektrougli"),
		"562820" => t("Fili"),
		"562321" => t("Fryazevo"),
		"562319" => t("Fryazino"),
		"560756" => t("Golitsyno"),
		"555746" => t("Istra"),
		"555111" => t("Ivanteyevka"),
		"554787" => t("Izmaylovo"),
		"551964" => t("Kashira"),
		"551835" => t("Kastanayevo"),
		"549479" => t("Khoroshevo-Mnevniki"),
		"549373" => t("Khot'kovo"),
		"547560" => t("Klimovsk"),
		"547523" => t("Klin"),
		"546230" => t("Kolomna"),
		"554233" => t("Korolev"),
		"543731" => t("Kotel'niki"),
		"543254" => t("Kozhukhovo"),
		"542463" => t("Krasnoarmeysk"),
		"542374" => t("Krasnogorsk"),
		"6417459" => t("Krasnoznamensk"),
		"540030" => t("Kubinka"),
		"538472" => t("Kur'yanovo"),
		"538601" => t("Kurovskoye"),
		"538321" => t("Kuskovo"),
		"536098" => t("Leninskiye Gory"),
		"535451" => t("Levoberezhnaya"),
		"583589" => t("Levoberezhnyy"),
		"535243" => t("Likino-Dulevo"),
		"534595" => t("Lobnya"),
		"534015" => t("Losino-Petrovskiy"),
		"533543" => t("Lukhovitsy"),
		"532657" => t("Lytkarino"),
		"532615" => t("Lyubertsy"),
		"531820" => t("Malakhovka"),
		"525396" => t("Monino"),
		"857690" => t("Moskovskiy"),
		"524712" => t("Mozhaysk"),
		"523812" => t("Mytishchi"),
		"523553" => t("Nakhabino"),
		"523426" => t("Naro-Fominsk"),
		"520068" => t("Noginsk"),
		"518879" => t("Novogireyevo"),
		"516215" => t("Odintsovo"),
		"515024" => t("Orekhovo-Zuyevo"),
		"513378" => t("Ozery"),
		"512023" => t("Pavlovskiy Posad"),
		"509981" => t("Petrovskaya"),
		"508101" => t("Podol'sk"),
		"542634" => t("Presnenskiy"),
		"504576" => t("Protvino"),
		"504042" => t("Pushchino"),
		"503977" => t("Pushkino"),
		"502018" => t("Reutov"),
		"501320" => t("Roshal'"),
		"497271" => t("Semenovskoye"),
		"496638" => t("Sergiyev Posad"),
		"496527" => t("Serpukhov"),
		"495518" => t("Shatura"),
		"495344" => t("Shchelkovo"),
		"495260" => t("Shcherbinka"),
		"492448" => t("Skhodnya"),
		"491351" => t("Sofrino"),
		"490996" => t("Solnechnogorsk"),
		"489162" => t("Staraya Kupavna"),
		"486968" => t("Stupino"),
		"482260" => t("Tomilino"),
		"481608" => t("Troitsk"),
		"480685" => t("Tuchkovo"),
		"473778" => t("Vidnoye"),
		"857689" => t("Vnukovo"),
		"472433" => t("Volokolamsk"),
		"471656" => t("Voskresensk"),
		"8505053" => t("Vostochnoe Degunino"),
		"471456" => t("Vostryakovo"),
		"471457" => t("Vostryakovo"),
		"468250" => t("Yegor'yevsk"),
		"536206" => t("Yubileyny"),
		"464687" => t("Zaraysk"),
		"7117880" => t("Zarya"),
		"463355" => t("Zheleznodorozhnyy"),
		"462755" => t("Zhukovskiy"),
		"461920" => t("Zvenigorod"),
	);
}


function location_cities_list_ru_che () {
	return array (
		"580660" => t("Asha"),
		"579738" => t("Bakal"),
		"1508350" => t("Chebarkul'"),
		"1508291" => t("Chelyabinsk"),
		"1504636" => t("Karabash"),
		"1504317" => t("Kartaly"),
		"1504251" => t("Kasli"),
		"551794" => t("Katav-Ivanovsk"),
		"1502603" => t("Kopeysk"),
		"1502536" => t("Korkino"),
		"538442" => t("Kusa"),
		"1500997" => t("Kyshtym"),
		"532288" => t("Magnitogorsk"),
		"1498894" => t("Miass"),
		"1538634" => t("Ozersk"),
		"1494907" => t("Plast"),
		"498418" => t("Satka"),
		"492944" => t("Sim"),
		"1536289" => t("Snezhinsk"),
		"830844" => t("Trekhgornyy"),
		"1489246" => t("Troitsk"),
		"478071" => t("Ust'-Katav"),
		"1487394" => t("Verkhniy Ufaley"),
		"1486039" => t("Yemanzhelinsk"),
		"1485634" => t("Yuzhnoural'sk"),
		"462444" => t("Zlatoust"),
	);
}


function location_cities_list_ru_bry () {
	return array (
		"571476" => t("Bryansk"),
		"563822" => t("Dyat'kovo"),
		"552920" => t("Karachev"),
		"547475" => t("Klintsy"),
		"517269" => t("Novozybkov"),
		"508656" => t("Pochep"),
		"497610" => t("Sel'tso"),
		"488852" => t("Starodub"),
		"481350" => t("Trubchevsk"),
		"479028" => t("Unecha"),
		"462822" => t("Zhukovka"),
	);
}


function location_cities_list_ru_vgg () {
	return array (
		"564654" => t("Dubovka"),
		"562389" => t("Frolovo"),
		"559654" => t("Gorodishche"),
		"554397" => t("Kalach-na-Donu"),
		"553287" => t("Kamyshin"),
		"543728" => t("Kotel'nikovo"),
		"543633" => t("Kotovo"),
		"536156" => t("Leninsk"),
		"527012" => t("Mikhaylovka"),
		"521874" => t("Nikolayevsk"),
		"519062" => t("Novoanninskiy"),
		"513042" => t("Pallasovka"),
		"486071" => t("Surovikino"),
		"478544" => t("Uryupinsk"),
		"472757" => t("Volgograd"),
		"472231" => t("Volzhskiy"),
		"468063" => t("Yelan'"),
		"462984" => t("Zhirnovsk"),
	);
}


function location_cities_list_ru_sam () {
	return array (
		"576590" => t("Bezenchuk"),
		"569955" => t("Chapayevsk"),
		"548625" => t("Kinel'"),
		"548622" => t("Kinel'-Cherkassy"),
		"522945" => t("Neftegorsk"),
		"518659" => t("Novokuybyshevsk"),
		"513883" => t("Otradnyy"),
		"507624" => t("Pokhvistnevo"),
		"499099" => t("Samara"),
		"484972" => t("Syzran'"),
		"482283" => t("Tol'yatti"),
		"463082" => t("Zhigulevsk"),
	);
}


function location_cities_list_ru_tam () {
	return array (
		"548330" => t("Kirsanov"),
		"543605" => t("Kotovsk"),
		"527191" => t("Michurinsk"),
		"525138" => t("Morshansk"),
		"502793" => t("Rasskazovo"),
		"484646" => t("Tambov"),
		"477626" => t("Uvarovo"),
		"463217" => t("Zherdevka"),
	);
}


function location_cities_list_ru_sta () {
	return array (
		"582993" => t("Aleksandrovskoye"),
		"580716" => t("Arzgir"),
		"576172" => t("Blagodarnyy"),
		"571306" => t("Budennovsk"),
		"566155" => t("Divnoye"),
		"565289" => t("Donskoye"),
		"561627" => t("Georgiyevsk"),
		"559320" => t("Goryachevodskiy"),
		"556320" => t("Inozemtsevo"),
		"556230" => t("Ipatovo"),
		"548114" => t("Kislovodsk"),
		"841006" => t("Kochubeyevskoye"),
		"542334" => t("Krasnogvardeyskoye"),
		"535886" => t("Lermontov"),
		"493702" => t("Mikhaylovsk"),
		"526480" => t("Mineral'nyye Vody"),
		"797781" => t("Neftekumsk"),
		"522377" => t("Nevinnomyssk"),
		"522301" => t("Nezlobnaya"),
		"519106" => t("Novoaleksandrovsk"),
		"518383" => t("Novopavlovsk"),
		"503550" => t("Pyatigorsk"),
		"487846" => t("Stavropol'"),
		"485871" => t("Suvorovskaya"),
		"485698" => t("Svetlograd"),
		"485432" => t("Svobody"),
		"466990" => t("Yessentuki"),
		"466989" => t("Yessentukskaya"),
		"463824" => t("Zelenokumsk"),
		"463340" => t("Zheleznovodsk"),
	);
}


function location_cities_list_ru_krs () {
	return array (
		"538908" => t("Kurchatov"),
		"538560" => t("Kursk"),
		"535334" => t("L'govskiy"),
		"695019" => t("Ryl'sk"),
		"495206" => t("Shchigry"),
		"463343" => t("Zheleznogorsk"),
	);
}


function location_cities_list_ru_ta () {
	return array (
		"583983" => t("Agryz"),
		"582432" => t("Al'met'yevsk"),
		"580850" => t("Arsk"),
		"578638" => t("Bavly"),
		"571170" => t("Bugul'ma"),
		"571155" => t("Buinsk"),
		"567990" => t("Chistopol'"),
		"551487" => t("Kazan"),
		"539689" => t("Kukmor"),
		"536162" => t("Leninogorsk"),
		"527579" => t("Mendeleyevsk"),
		"527529" => t("Menzelinsk"),
		"523750" => t("Naberezhnyye Chelny"),
		"521118" => t("Nizhnekamsk"),
		"516716" => t("Nurlat"),
		"611182" => t("Vasil'yevo"),
		"468082" => t("Yelabuga"),
		"465543" => t("Zainsk"),
		"463835" => t("Zelenodol'sk"),
	);
}


function location_cities_list_ru_kc () {
	return array (
		"569154" => t("Cherkessk"),
		"552924" => t("Karachayevsk"),
		"479687" => t("Uchkeken"),
		"478130" => t("Ust'-Dzheguta"),
		"463885" => t("Zelenchukskaya"),
	);
}


function location_cities_list_ru_niz () {
	return array (
		"580724" => t("Arzamas"),
		"575560" => t("Bogorodsk"),
		"572665" => t("Bor"),
		"563708" => t("Dzerzhinsk"),
		"559678" => t("Gorodets"),
		"540103" => t("Kstovo"),
		"539555" => t("Kulebaki"),
		"532715" => t("Lyskovo"),
		"523198" => t("Navashino"),
		"520555" => t("Nizhniy Novgorod"),
		"579514" => t("Novaya Balakhna"),
		"827329" => t("Pavlovo"),
		"498525" => t("Sarov"),
		"497450" => t("Semenov"),
		"496802" => t("Sergach"),
		"496012" => t("Shakhun'ya"),
		"470444" => t("Vyksa"),
		"464101" => t("Zavolzh'ye"),
	);
}


function location_cities_list_ru_pnz () {
	return array (
		"537737" => t("Kuznetsk"),
		"521776" => t("Nikol'sk"),
		"520574" => t("Nizhniy Lomov"),
		"511565" => t("Penza"),
		"496934" => t("Serdobsk"),
		"831165" => t("Zarechnyy"),
		"464625" => t("Zarechnyy"),
	);
}


function location_cities_list_ru_mur () {
	return array (
		"581357" => t("Apatity"),
		"553190" => t("Kandalaksha"),
		"548391" => t("Kirovsk"),
		"543508" => t("Kovdor"),
		"525404" => t("Monchegorsk"),
		"524305" => t("Murmansk"),
		"522260" => t("Nikel'"),
		"515698" => t("Olenegorsk"),
		"506763" => t("Polyarnyy"),
		"506762" => t("Polyarnyye Zori"),
		"496278" => t("Severomorsk"),
		"464790" => t("Zapolyarnyy"),
	);
}


function location_cities_list_ru_vla () {
	return array (
		"583350" => t("Aleksandrov"),
		"582978" => t("Aleksandrow"),
		"557775" => t("Gus'-Khrustal'nyy"),
		"552977" => t("Karabanovo"),
		"548278" => t("Kirzhach"),
		"546521" => t("Kol'chugino"),
		"543460" => t("Kovrov"),
		"537107" => t("Lakinsk"),
		"527740" => t("Melenki"),
		"524294" => t("Murom"),
		"509697" => t("Petushki"),
		"507599" => t("Pokrov"),
		"7117885" => t("Raduzhnyy"),
		"491480" => t("Sobinka"),
		"487095" => t("Strunino"),
		"473247" => t("Vladimir"),
		"470666" => t("Vyazniki"),
		"466215" => t("Yur'yev-Pol'skiy"),
	);
}


function location_cities_list_ru_me () {
	return array (
		"543018" => t("Koz'modem'yansk"),
		"528056" => t("Medvedevo"),
		"472234" => t("Volzhsk"),
		"466806" => t("Yoshkar-Ola"),
	);
}


function location_cities_list_ru_kda () {
	return array (
		"584441" => t("Abinsk"),
		"584243" => t("Adler"),
		"584126" => t("Afipskiy"),
		"583785" => t("Akhtyrskiy"),
		"582182" => t("Anapa"),
		"581313" => t("Apsheronsk"),
		"580922" => t("Armavir"),
		"578169" => t("Belaya Glina"),
		"577893" => t("Belorechensk"),
		"571420" => t("Bryukhovetskaya"),
		"823674" => t("Dagomys"),
		"566181" => t("Dinskaya"),
		"561667" => t("Gelendzhik"),
		"559317" => t("Goryachiy Klyuch"),
		"558066" => t("Gul'kevichi"),
		"556951" => t("Il'skiy"),
		"553152" => t("Kanevskaya"),
		"550846" => t("Khadyzhensk"),
		"549741" => t("Kholmskiy"),
		"549424" => t("Khosta"),
		"544896" => t("Korenovsk"),
		"542461" => t("Krasnoarmeyskaya"),
		"542420" => t("Krasnodar"),
		"540761" => t("Kropotkin"),
		"540251" => t("Krymsk"),
		"539907" => t("Kudepsta"),
		"538836" => t("Kurganinsk"),
		"538416" => t("Kushchevskaya"),
		"537281" => t("Labinsk"),
		"536625" => t("Lazarevskoye"),
		"536200" => t("Leningradskaya"),
		"527968" => t("Medvedovskaya"),
		"524809" => t("Mostovskoy"),
		"518682" => t("Novokubansk"),
		"518325" => t("Novopokrovskaya"),
		"518255" => t("Novorossiysk"),
		"517842" => t("Novotitarovskaya"),
		"513911" => t("Otradnaya"),
		"512382" => t("Pashkovskiy"),
		"512051" => t("Pavlovskaya"),
		"505259" => t("Primorsko-Akhtarsk"),
		"496267" => t("Severskaya"),
		"492094" => t("Slavyansk-na-Kubani"),
		"491422" => t("Sochi"),
		"488742" => t("Starominskaya"),
		"488635" => t("Staroshcherbinovskaya"),
		"483883" => t("Tbilisskaya"),
		"483661" => t("Temryuk"),
		"483029" => t("Tikhoretsk"),
		"482965" => t("Timashevsk"),
		"480716" => t("Tuapse"),
		"478044" => t("Ust'-Labinsk"),
		"470338" => t("Vyselki"),
		"467854" => t("Yelizavetinskaya"),
		"466885" => t("Yeysk"),
	);
}


function location_cities_list_ru_sar () {
	return array (
		"580420" => t("Atkarsk"),
		"579492" => t("Balakovo"),
		"579460" => t("Balashov"),
		"563464" => t("Engel's"),
		"554199" => t("Kalininsk"),
		"542464" => t("Krasnoarmeysk"),
		"529073" => t("Marks"),
		"517739" => t("Novouzensk"),
		"509987" => t("Petrovsk"),
		"505057" => t("Privolzhskiy"),
		"500886" => t("Rtishchevo"),
		"498677" => t("Saratov"),
		"472278" => t("Vol'sk"),
		"467120" => t("Yershov"),
	);
}


function location_cities_list_ru_ko () {
	return array (
		"563379" => t("Ezhva"),
		"511794" => t("Pechora"),
		"490391" => t("Sosnogorsk"),
		"485239" => t("Syktyvkar"),
		"479411" => t("Ukhta"),
		"863061" => t("Usinsk"),
		"1486913" => t("Vorgashor"),
		"1486910" => t("Vorkuta"),
		"467525" => t("Yemva"),
	);
}


function location_cities_list_ru_lip () {
	return array (
		"567109" => t("Dankov"),
		"558312" => t("Gryazi"),
		"536518" => t("Lebedyan'"),
		"535121" => t("Lipetsk"),
		"478317" => t("Usman'"),
		"467978" => t("Yelets"),
	);
}


function location_cities_list_ru_tul () {
	return array (
		"582750" => t("Aleksin"),
		"578091" => t("Belev"),
		"575591" => t("Bogoroditsk"),
		"565290" => t("Donskoy"),
		"548658" => t("Kimovsk"),
		"548506" => t("Kireyevsk"),
		"544293" => t("Kosaya Gora"),
		"518557" => t("Novomoskovsk"),
		"509052" => t("Plavsk"),
		"496269" => t("Severo-Zadonsk"),
		"495394" => t("Shchekino"),
		"485888" => t("Suvorov"),
		"480562" => t("Tula"),
		"477494" => t("Uzlovaya"),
		"475881" => t("Venev"),
		"468671" => t("Yasnogorsk"),
		"468390" => t("Yefremov"),
	);
}


function location_cities_list_ru_ore () {
	return array (
		"584471" => t("Abdulino"),
		"571159" => t("Buguruslan"),
		"570427" => t("Buzuluk"),
		"561731" => t("Gay"),
		"538138" => t("Kuvandyk"),
		"528109" => t("Mednogorsk"),
		"517836" => t("Novotroitsk"),
		"515003" => t("Orenburg"),
		"514734" => t("Orsk"),
		"498708" => t("Saraktash"),
		"491019" => t("Sol'-Iletsk"),
		"490554" => t("Sorochinsk"),
		"468657" => t("Yasnyy"),
	);
}


function location_cities_list_ru_smo () {
	return array (
		"566384" => t("Desnogorsk"),
		"562237" => t("Gagarin"),
		"501283" => t("Roslavl'"),
		"499452" => t("Safonovo"),
		"491687" => t("Smolensk"),
		"470676" => t("Vyaz'ma"),
		"468866" => t("Yartsevo"),
	);
}


function location_cities_list_ru_yar () {
	return array (
		"567183" => t("Danilov"),
		"561762" => t("Gavrilov-Yam"),
		"511359" => t("Pereslavl'-Zalesskiy"),
		"501183" => t("Rostov"),
		"500004" => t("Rybinsk"),
		"480122" => t("Tutayev"),
		"479532" => t("Uglich"),
		"468902" => t("Yaroslavl"),
	);
}


function location_cities_list_ru_kir () {
	return array (
		"548408" => t("Kirov"),
		"548395" => t("Kirovo-Chepetsk"),
		"543737" => t("Kotel'nich"),
		"515267" => t("Omutninsk"),
		"491882" => t("Slobodskoy"),
		"490067" => t("Sovetsk"),
		"470734" => t("Vyatskiye Polyany"),
		"469005" => t("Yaransk"),
	);
}


function location_cities_list_ru_ba () {
	return array (
		"484856" => t("Agidel'"),
		"578534" => t("Baymak"),
		"578120" => t("Belebey"),
		"577881" => t("Beloretsk"),
		"576317" => t("Birsk"),
		"576116" => t("Blagoveshchensk"),
		"568012" => t("Chishmy"),
		"567006" => t("Davlekanovo"),
		"563719" => t("Dyurtyuli"),
		"555980" => t("Ishimbay"),
		"539283" => t("Kumertau"),
		"527717" => t("Meleuz"),
		"522942" => t("Neftekamsk"),
		"515879" => t("Oktyabr'skiy"),
		"505014" => t("Priyutovo"),
		"502540" => t("Rayevskiy"),
		"499292" => t("Salavat"),
		"493160" => t("Sibay"),
		"487495" => t("Sterlitamak"),
		"480089" => t("Tuymazy"),
		"479703" => t("Uchaly"),
		"479704" => t("Uchaly"),
		"479561" => t("Ufa"),
		"469178" => t("Yanaul"),
	);
}


function location_cities_list_ru_ad () {
	return array (
		"563472" => t("Enem"),
		"561515" => t("Giaginskaya"),
		"528293" => t("Maykop"),
		"469844" => t("Yablonovskiy"),
	);
}


function location_cities_list_ru_len () {
	return array (
		"8504958" => t("Akademicheskoe"),
		"575410" => t("Boksitogorsk"),
		"8504946" => t("Chernaya Rechka"),
		"8504959" => t("Finlyandskiy"),
		"561887" => t("Gatchina"),
		"8504951" => t("Kalininskiy"),
		"548602" => t("Kingisepp"),
		"548442" => t("Kirishi"),
		"548392" => t("Kirovsk"),
		"545788" => t("Kommunar"),
		"8504955" => t("Krestovskiy ostrov"),
		"8436165" => t("Kurortnyy"),
		"534560" => t("Lodeynoye Pole"),
		"533690" => t("Luga"),
		"521509" => t("Nikol'skoye"),
		"513898" => t("Otradnoye"),
		"8504950" => t("Parnas"),
		"509598" => t("Pikalevo"),
		"508034" => t("Podporozh'ye"),
		"505230" => t("Priozersk"),
		"500019" => t("Rybatskoye"),
		"8504965" => t("Sampsonievskiy"),
		"496519" => t("Sertolovo"),
		"492162" => t("Slantsy"),
		"490172" => t("Sosnovyy Bor"),
		"8504964" => t("Svetlanovskiy"),
		"485639" => t("Svetogorsk"),
		"483019" => t("Tikhvin"),
		"481964" => t("Tosno"),
		"8504947" => t("Untolovo"),
		"472722" => t("Volkhov"),
		"471101" => t("Vsevolozhsk"),
		"470546" => t("Vyborg"),
	);
}


function location_cities_list_ru_ud () {
	return array (
		"579432" => t("Balezino"),
		"561347" => t("Glazov"),
		"557469" => t("Igra"),
		"554840" => t("Izhevsk"),
		"524699" => t("Mozhga"),
		"498687" => t("Sarapul"),
		"477656" => t("Uva"),
		"471430" => t("Votkinsk"),
	);
}


function location_cities_list_ru_vor () {
	return array (
		"581671" => t("Anna"),
		"575948" => t("Bobrov"),
		"575457" => t("Boguchar"),
		"572525" => t("Borisoglebsk"),
		"570563" => t("Buturlinovka"),
		"558799" => t("Gribanovskiy"),
		"554410" => t("Kalach"),
		"534838" => t("Liski"),
		"519447" => t("Novaya Usman'"),
		"517716" => t("Novovoronezh"),
		"514198" => t("Ostrogozhsk"),
		"512053" => t("Pavlovsk"),
		"505806" => t("Povorino"),
		"505421" => t("Pridonskoy"),
		"501215" => t("Rossosh'"),
		"501231" => t("Rossosh'"),
		"497206" => t("Semiluki"),
		"472045" => t("Voronezh"),
	);
}


function location_cities_list_ru_vlg () {
	return array (
		"569223" => t("Cherepovets"),
		"558236" => t("Gryazovets"),
		"495062" => t("Sheksna"),
		"491281" => t("Sokol"),
		"476062" => t("Velikiy Ustyug"),
		"472459" => t("Vologda"),
	);
}


function location_cities_list_ru_kos () {
	return array (
		"570508" => t("Buy"),
		"562161" => t("Galich"),
		"543878" => t("Kostroma"),
		"529505" => t("Manturovo"),
		"522594" => t("Nerekhta"),
		"495619" => t("Shar'ya"),
		"472750" => t("Volgorechensk"),
	);
}


function location_cities_list_ru_se () {
	return array (
		"802078" => t("Alagir"),
		"581179" => t("Ardon"),
		"576697" => t("Beslan"),
		"524736" => t("Mozdok"),
		"473249" => t("Vladikavkaz"),
	);
}


function location_cities_list_ru_iva () {
	return array (
		"562309" => t("Furmanov"),
		"555312" => t("Ivanovo"),
		"548605" => t("Kineshma"),
		"546672" => t("Kokhma"),
		"505060" => t("Privolzhsk"),
		"501730" => t("Rodniki"),
		"493231" => t("Shuya"),
		"483137" => t("Teykovo"),
		"473788" => t("Vichuga"),
	);
}


function location_cities_list_ru_per () {
	return array (
		"583041" => t("Aleksandrovsk"),
		"577206" => t("Berezniki"),
		"569742" => t("Chaykovskiy"),
		"568608" => t("Chernushka"),
		"567434" => t("Chusovoy"),
		"565778" => t("Dobryanka"),
		"558209" => t("Gubakha"),
		"547875" => t("Kizel"),
		"542327" => t("Krasnokamsk"),
		"542184" => t("Krasnovishersk"),
		"539817" => t("Kudymkar"),
		"539147" => t("Kungur"),
		"532675" => t("Lys'va"),
		"516576" => t("Nytva"),
		"516256" => t("Ocher"),
		"514706" => t("Osa"),
		"511196" => t("Perm'"),
		"491023" => t("Solikamsk"),
		"475777" => t("Vereshchagino"),
	);
}


function location_cities_list_ru_ark () {
	return array (
		"581049" => t("Arkhangel'sk"),
		"544370" => t("Koryazhma"),
		"543704" => t("Kotlas"),
		"526346" => t("Mirnyy"),
		"831129" => t("Mirnyy"),
		"518909" => t("Novodvinsk"),
		"516647" => t("Nyandoma"),
		"515246" => t("Onega"),
		"496285" => t("Severodvinsk"),
		"475938" => t("Vel'sk"),
	);
}


function location_cities_list_ru_psk () {
	return array (
		"522410" => t("Nevel'"),
		"514171" => t("Ostrov"),
		"504341" => t("Pskov"),
		"476077" => t("Velikiye Luki"),
	);
}


function location_cities_list_ru_bel () {
	return array (
		"582956" => t("Alekseyevka"),
		"578072" => t("Belgorod"),
		"568587" => t("Chernyanka"),
		"558146" => t("Gubkin"),
		"516931" => t("Novyy Oskol"),
		"502400" => t("Razumnoye"),
		"495112" => t("Shebekino"),
		"487928" => t("Staryy Oskol"),
		"487147" => t("Stroitel'"),
		"477192" => t("Valuyki"),
	);
}


function location_cities_list_ru_ngr () {
	return array (
		"572154" => t("Borovichi"),
		"567774" => t("Chudovo"),
		"510364" => t("Pestovo"),
		"489088" => t("Staraya Russa"),
		"477301" => t("Valday"),
		"519336" => t("Velikiy Novgorod"),
	);
}


function location_cities_list_ru_ce () {
	return array (
		"584298" => t("Achkhoy-Martan"),
		"581126" => t("Argun"),
		"580218" => t("Avtury"),
		"558418" => t("Groznyy"),
		"558118" => t("Gudermes"),
		"538913" => t("Kurchaloy"),
		"515804" => t("Tsotsin-Yurt"),
		"478581" => t("Urus-Martan"),
	);
}


function location_cities_list_ru_uly () {
	return array (
		"578931" => t("Barysh"),
		"566199" => t("Dimitrovgrad"),
		"556283" => t("Inza"),
		"517766" => t("Novoul'yanovsk"),
		"479123" => t("Ulyanovsk"),
	);
}


function location_cities_list_ru_kb () {
	return array (
		"579574" => t("Baksan"),
		"569639" => t("Chegem"),
		"537345" => t("Dugulubgey"),
		"523523" => t("Nal'chik"),
		"523405" => t("Nartkala"),
		"504935" => t("Prokhladnyy"),
		"483495" => t("Terek"),
		"479933" => t("Tyrnyauz"),
	);
}


function location_cities_list_ru_in () {
	return array (
		"563551" => t("Ekazhevo"),
		"553092" => t("Kantyshevo"),
		"552951" => t("Karabulak"),
		"531129" => t("Malgobek"),
		"523064" => t("Nazran'"),
		"522470" => t("Nesterovskaya"),
		"515083" => t("Ordzhonikidzevskaya"),
		"874045" => t("Staryy Malgobek"),
		"486110" => t("Surkhakhi"),
		"481605" => t("Troitskaya"),
	);
}


function location_cities_list_ru_kgd () {
	return array (
		"2609906" => t("Baltiysk"),
		"568595" => t("Chernyakhovsk"),
		"557882" => t("Gusev"),
		"554234" => t("Kaliningrad"),
		"490068" => t("Sovetsk"),
		"485660" => t("Svetlyy"),
	);
}


function location_cities_list_ru_klu () {
	return array (
		"579529" => t("Balabanovo"),
		"553915" => t("Kaluga"),
		"548410" => t("Kirov"),
		"545575" => t("Kondrovo"),
		"543348" => t("Kozel'sk"),
		"532459" => t("Lyudinovo"),
		"530849" => t("Maloyaroslavets"),
		"516436" => t("Obninsk"),
		"486665" => t("Sukhinichi"),
	);
}


function location_cities_list_ru_kr () {
	return array (
		"545626" => t("Kondopoga"),
		"543899" => t("Kostomuksha"),
		"527888" => t("Medvezh'yegorsk"),
		"509820" => t("Petrozavodsk"),
		"497927" => t("Segezha"),
		"490466" => t("Sortavala"),
	);
}


function location_cities_list_ru_cu () {
	return array (
		"583437" => t("Alatyr'"),
		"569696" => t("Cheboksary"),
		"553216" => t("Kanash"),
		"518976" => t("Novocheboksarsk"),
		"493463" => t("Shumerlya"),
	);
}


function location_cities_list_ru_sve () {
	return array (
		"1511954" => t("Alapayevsk"),
		"1511466" => t("Aramil'"),
		"1511368" => t("Artemovskiy"),
		"1511330" => t("Asbest"),
		"1510203" => t("Berezovskiy"),
		"1509888" => t("Bogdanovich"),
		"1507488" => t("Degtyarsk"),
		"1505526" => t("Irbit"),
		"1505260" => t("Ivdel'"),
		"554599" => t("Kachkanar"),
		"1504826" => t("Kamensk-Ural'skiy"),
		"1504769" => t("Kamyshlov"),
		"1504343" => t("Karpinsk"),
		"1503335" => t("Kirovgrad"),
		"1502061" => t("Krasnotur'insk"),
		"542199" => t("Krasnoufimsk"),
		"1502060" => t("Krasnoural'sk"),
		"538340" => t("Kushva"),
		"6853140" => t("Lesnoy"),
		"829005" => t("Lesnoy"),
		"1497795" => t("Nev'yansk"),
		"520494" => t("Nizhniy Tagil"),
		"1497393" => t("Nizhnyaya Salda"),
		"520204" => t("Nizhnyaya Tura"),
		"1538636" => t("Novoural'sk"),
		"510808" => t("Pervoural'sk"),
		"1494573" => t("Polevskoy"),
		"1493687" => t("Reftinskiy"),
		"502011" => t("Revda"),
		"1493648" => t("Rezh"),
		"1492663" => t("Serov"),
		"496275" => t("Severoural'sk"),
		"1491159" => t("Sredneural'sk"),
		"1490686" => t("Sukhoy Log"),
		"1490402" => t("Sysert'"),
		"1490277" => t("Talitsa"),
		"1490281" => t("Talitsa"),
		"1489962" => t("Tavda"),
		"1488933" => t("Turinsk"),
		"1487281" => t("Verkhnyaya Pyshma"),
		"1487277" => t("Verkhnyaya Salda"),
		"1486209" => t("Yekaterinburg"),
		"1485445" => t("Zarechnyy"),
	);
}


function location_cities_list_ru_mo () {
	return array (
		"543436" => t("Kovylkino"),
		"500299" => t("Ruzayevka"),
		"498698" => t("Saransk"),
	);
}


function location_cities_list_ru_orl () {
	return array (
		"534701" => t("Livny"),
		"524640" => t("Mtsensk"),
		"515012" => t("Orel"),
	);
}


function location_cities_list_ru_nen () {
	return array (
		"523392" => t("Nar'yan-Mar"),
	);
}


function location_cities_list_ru_da () {
	return array (
		"828055" => t("Belidzhi"),
		"570479" => t("Buynaksk"),
		"567290" => t("Dagestanskiye Ogni"),
		"566532" => t("Derbent"),
		"554894" => t("Izberbash"),
		"551847" => t("Kaspiysk"),
		"550478" => t("Khasavyurt"),
		"547849" => t("Kizilyurt"),
		"547840" => t("Kizlyar"),
		"532096" => t("Makhachkala"),
	);
}


function location_cities_list_ru_ast () {
	return array (
		"583798" => t("Akhtubinsk"),
		"580497" => t("Astrakhan'"),
		"553248" => t("Kamyzyak"),
		"550671" => t("Kharabali"),
		"831130" => t("Znamensk"),
	);
}


function location_cities_list_ru_kl () {
	return array (
		"563514" => t("Elista"),
	);
}


function location_cities_list_ru_tyu () {
	return array (
		"1508879" => t("Borovskiy"),
		"1505453" => t("Ishim"),
		"1489530" => t("Tobol'sk"),
		"1488754" => t("Tyumen"),
		"1486468" => t("Yalutorovsk"),
		"1485357" => t("Zavodoukovsk"),
	);
}


function location_cities_list_ru_alt () {
	return array (
		"1511783" => t("Aleysk"),
		"1510853" => t("Barnaul"),
		"1510018" => t("Biysk"),
		"1506260" => t("Gornyak"),
		"1504871" => t("Kamen'-na-Obi"),
		"1501460" => t("Kulunda"),
		"1497173" => t("Novoaltaysk"),
		"1496739" => t("Novosilikatnyy"),
		"1493467" => t("Rubtsovsk"),
		"1491706" => t("Slavgorod"),
		"1490266" => t("Tal'menka"),
		"1486340" => t("Yarovoye"),
		"1485627" => t("Yuzhnyy"),
		"1485439" => t("Zarinsk"),
	);
}


function location_cities_list_ru_kem () {
	return array (
		"1511494" => t("Anzhero-Sudzhensk"),
		"1510469" => t("Belovo"),
		"1510205" => t("Berezovskiy"),
		"1506073" => t("Gur'yevsk"),
		"1504972" => t("Kaltan"),
		"1503940" => t("Kedrovka"),
		"1503901" => t("Kemerovo"),
		"1503277" => t("Kiselevsk"),
		"1500665" => t("Leninsk-Kuznetskiy"),
		"1499350" => t("Mariinsk"),
		"1498920" => t("Mezhdurechensk"),
		"1498129" => t("Myski"),
		"1496990" => t("Novokuznetsk"),
		"1495974" => t("Osinniki"),
		"1494456" => t("Polysayevo"),
		"1494114" => t("Prokop'yevsk"),
		"1494091" => t("Promyshlennaya"),
		"1490042" => t("Tashtagol"),
		"1489907" => t("Tayga"),
		"1489394" => t("Topki"),
		"1486298" => t("Yashkino"),
		"1485724" => t("Yurga"),
	);
}


function location_cities_list_ru_kya () {
	return array (
		"1512165" => t("Achinsk"),
		"1510255" => t("Berezovka"),
		"1509852" => t("Bogotol"),
		"1508943" => t("Borodino"),
		"1507379" => t("Divnogorsk"),
		"1507116" => t("Dudinka"),
		"1505933" => t("Ilanskiy"),
		"1504682" => t("Kansk"),
		"1504139" => t("Kayyerkan"),
		"1503037" => t("Kodinsk"),
		"1502026" => t("Krasnoyarsk"),
		"1500607" => t("Lesosibirsk"),
		"1498693" => t("Minusinsk"),
		"1497951" => t("Nazarovo"),
		"1497337" => t("Noril'sk"),
		"1492401" => t("Sharypovo"),
		"1491953" => t("Shushenskoye"),
		"1491291" => t("Sosnovoborsk"),
		"1490256" => t("Talnakh"),
		"1487882" => t("Uzhur"),
		"1485997" => t("Yeniseysk"),
		"1488253" => t("Zelenogorsk"),
		"1538635" => t("Zheleznogorsk"),
	);
}


function location_cities_list_ru_khm () {
	return array (
		"1510450" => t("Beloyarskiy"),
		"7290697" => t("Izluchinsk"),
		"1503772" => t("Khanty-Mansiysk"),
		"6695754" => t("Kogalym"),
		"6696767" => t("Langepas"),
		"1541359" => t("Lyantor"),
		"1499053" => t("Megion"),
		"1497917" => t("Nefteyugansk"),
		"7287775" => t("Nizhnesortymskiy"),
		"1497543" => t("Nizhnevartovsk"),
		"1496476" => t("Nyagan"),
		"7289676" => t("Pokachi"),
		"1494276" => t("Poykovskiy"),
		"6696686" => t("Pyt-Yakh"),
		"1540356" => t("Raduzhnyy"),
		"1491230" => t("Sovetskiy"),
		"1490624" => t("Surgut"),
		"1488429" => t("Uray"),
		"1502725" => t("Yugorsk"),
	);
}


function location_cities_list_ru_tom () {
	return array (
		"1511309" => t("Asino"),
		"1502862" => t("Kolpashevo"),
		"1538637" => t("Seversk"),
		"1490796" => t("Strezhevoy"),
		"1489425" => t("Tomsk"),
	);
}


function location_cities_list_ru_nvs () {
	return array (
		"1512086" => t("Akademgorodok"),
		"1510916" => t("Barabinsk"),
		"1510350" => t("Berdsk"),
		"1509819" => t("Bolotnoye"),
		"1508161" => t("Cherepanovo"),
		"1505429" => t("Iskitim"),
		"1504489" => t("Karasuk"),
		"1503082" => t("Kochenevo"),
		"1502091" => t("Krasnoobsk"),
		"1501365" => t("Kupino"),
		"1501141" => t("Kuybyshev"),
		"1500532" => t("Linevo"),
		"1496747" => t("Novosibirsk"),
		"1496421" => t("Ob'"),
		"1490551" => t("Suzun"),
		"1490003" => t("Tatarsk"),
		"1489508" => t("Toguchin"),
	);
}


function location_cities_list_ru_irk () {
	return array (
		"2027667" => t("Angarsk"),
		"2026979" => t("Baykal'sk"),
		"2026583" => t("Bodaybo"),
		"2051523" => t("Bratsk"),
		"2025527" => t("Cheremkhovo"),
		"1507636" => t("Chunskiy"),
		"2023469" => t("Irkutsk"),
		"1497549" => t("Nizhneudinsk"),
		"2055166" => t("Sayansk"),
		"2016764" => t("Shelekhov"),
		"2016422" => t("Slyudyanka"),
		"1489870" => t("Tayshet"),
		"2014927" => t("Tulun"),
		"2014022" => t("Usol'ye-Sibirskoye"),
		"2013952" => t("Ust'-Ilimsk"),
		"2013923" => t("Ust'-Kut"),
		"2013399" => t("Vikhorevka"),
		"2012557" => t("Zheleznogorsk-Ilimskiy"),
		"2012484" => t("Zima"),
	);
}


function location_cities_list_ru_yan () {
	return array (
		"1539209" => t("Gubkinskiy"),
		"1500933" => t("Labytnangi"),
		"1540711" => t("Muravlenko"),
		"1498087" => t("Nadym"),
		"1496511" => t("Novyy Urengoy"),
		"1496503" => t("Noyabr'sk"),
		"1493197" => t("Salekhard"),
		"1490085" => t("Tarko-Sale"),
	);
}


function location_cities_list_ru_oms () {
	return array (
		"1505074" => t("Kalachinsk"),
		"1496153" => t("Omsk"),
		"1490140" => t("Tara"),
	);
}


function location_cities_list_ru_kgn () {
	return array (
		"1504212" => t("Kataysk"),
		"1501321" => t("Kurgan"),
		"1501255" => t("Kurtamysh"),
		"1492517" => t("Shadrinsk"),
		"1491999" => t("Shumikha"),
	);
}


function location_cities_list_ru_kk () {
	return array (
		"1512236" => t("Abakan"),
		"1512205" => t("Abaza"),
		"1508054" => t("Chernogorsk"),
		"1492893" => t("Sayanogorsk"),
	);
}


function location_cities_list_ru_kha () {
	return array (
		"2027749" => t("Amursk"),
		"2026696" => t("Bikin"),
		"2022890" => t("Khabarovsk"),
		"2056752" => t("Khabarovsk Vtoroy"),
		"2021851" => t("Komsomol'sk-na-Amure"),
		"1499163" => t("Mayma"),
		"2122850" => t("Nikolayevsk-na-Amure"),
		"2121052" => t("Sovetskaya Gavan'"),
		"2119932" => t("Vanino"),
		"2013229" => t("Vyazemskiy"),
	);
}


function location_cities_list_ru_ty () {
	return array (
		"1500973" => t("Kyzyl"),
	);
}


function location_cities_list_ru_al () {
	return array (
		"1506271" => t("Gorno-Altaysk"),
	);
}


function location_cities_list_ru_amu () {
	return array (
		"2026895" => t("Belogorsk"),
		"2026609" => t("Blagoveshchensk"),
		"2017487" => t("Raychikhinsk"),
		"2016701" => t("Shimanovsk"),
		"2015833" => t("Svobodnyy"),
		"2014718" => t("Tynda"),
		"2012593" => t("Zeya"),
	);
}


function location_cities_list_ru_sa () {
	return array (
		"2027968" => t("Aldan"),
		"2027296" => t("Aykhal"),
		"2020838" => t("Lensk"),
		"2019951" => t("Mirny"),
		"2019309" => t("Neryungri"),
		"2014624" => t("Udachny"),
		"2013159" => t("Yakutsk"),
	);
}


function location_cities_list_ru_pri () {
	return array (
		"2027468" => t("Arsen'yev"),
		"2027456" => t("Artem"),
		"2026303" => t("Bol'shoy Kamen'"),
		"2051471" => t("Dal'negorsk"),
		"2025159" => t("Dal'nerechensk"),
		"2015310" => t("Fokino"),
		"2023058" => t("Kavalerovo"),
		"2020812" => t("Lesozavodsk"),
		"2020689" => t("Luchegorsk"),
		"2019528" => t("Nakhodka"),
		"2018116" => t("Partizansk"),
		"2016187" => t("Spassk-Dal'niy"),
		"2015051" => t("Trudovoye"),
		"2014006" => t("Ussuriysk"),
		"2013348" => t("Vladivostok"),
		"2013258" => t("Vrangel'"),
	);
}


function location_cities_list_ru_bu () {
	return array (
		"2023782" => t("Gusinoozersk"),
		"2021066" => t("Kyakhta"),
		"2016910" => t("Severobaykal'sk"),
		"2014407" => t("Ulan-Ude"),
	);
}


function location_cities_list_ru_zab () {
	return array (
		"2026126" => t("Borzya"),
		"2025339" => t("Chita"),
		"2021618" => t("Krasnokamensk"),
		"2019326" => t("Nerchinsk"),
		"2017945" => t("Petrovsk-Zabaykal'skiy"),
	);
}


function location_cities_list_ru_yev () {
	return array (
		"2026643" => t("Birobidzhan"),
	);
}


function location_cities_list_ru_kam () {
	return array (
		"2122104" => t("Petropavlovsk-Kamchatskiy"),
		"2118647" => t("Vilyuchinsk"),
		"2119538" => t("Yelizovo"),
	);
}


function location_cities_list_ru_sak () {
	return array (
		"2124615" => t("Kholmsk"),
		"2124286" => t("Korsakov"),
		"2122894" => t("Nevel'sk"),
		"2122614" => t("Okha"),
		"2121909" => t("Poronaysk"),
		"2119441" => t("Yuzhno-Sakhalinsk"),
	);
}


function location_cities_list_ru_mag () {
	return array (
		"2123628" => t("Magadan"),
	);
}


