<?php


function location_cities_list_ke_10() {
  return array(
    "195821" => "Kabarnet",
  );
}


function location_cities_list_ke_11() {
  return array();
}


function location_cities_list_ke_12() {
  return array(
    "200067" => "Bungoma",
  );
}


function location_cities_list_ke_13() {
  return array(
    "199989" => "Busia",
  );
}


function location_cities_list_ke_14() {
  return array();
}


function location_cities_list_ke_15() {
  return array(
    "198476" => "Embu",
  );
}


function location_cities_list_ke_16() {
  return array(
    "197745" => "Garissa",
  );
}


function location_cities_list_ke_17() {
  return array(
    "196742" => "Homa Bay",
  );
}


function location_cities_list_ke_18() {
  return array(
    "196231" => "Isiolo",
  );
}


function location_cities_list_ke_19() {
  return array();
}


function location_cities_list_ke_20() {
  return array(
    "195272" => "Kakamega",
  );
}


function location_cities_list_ke_21() {
  return array(
    "192900" => "Kericho",
  );
}


function location_cities_list_ke_22() {
  return array(
    "192710" => "Kiambu",
  );
}


function location_cities_list_ke_23() {
  return array(
    "187968" => "Malindi",
    "192067" => "Kilifi",
  );
}


function location_cities_list_ke_24() {
  return array(
    "192859" => "Keruguya",
  );
}


function location_cities_list_ke_25() {
  return array(
    "191299" => "Kisii",
  );
}


function location_cities_list_ke_26() {
  return array(
    "191245" => "Kisumu",
  );
}


function location_cities_list_ke_27() {
  return array(
    "191038" => "Kitui",
  );
}


function location_cities_list_ke_28() {
  return array();
}


function location_cities_list_ke_29() {
  return array(
    "184433" => "Nanyuki",
  );
}


function location_cities_list_ke_30() {
  return array(
    "189741" => "Lamu",
  );
}


function location_cities_list_ke_31() {
  return array(
    "188492" => "Machakos",
  );
}


function location_cities_list_ke_32() {
  return array();
}


function location_cities_list_ke_33() {
  return array(
    "187896" => "Mandera",
  );
}


function location_cities_list_ke_34() {
  return array(
    "187585" => "Marsabit",
  );
}


function location_cities_list_ke_35() {
  return array(
    "186827" => "Meru",
  );
}


function location_cities_list_ke_36() {
  return array(
    "186731" => "Migori",
  );
}


function location_cities_list_ke_37() {
  return array(
    "186301" => "Mombasa",
  );
}


function location_cities_list_ke_38() {
  return array();
}


function location_cities_list_ke_110() {
  return array(
    "179330" => "Thika",
    "181501" => "Pumwani",
    "184745" => "Nairobi",
  );
}


function location_cities_list_ke_39() {
  return array(
    "184622" => "Nakuru",
  );
}


function location_cities_list_ke_40() {
  return array();
}


function location_cities_list_ke_41() {
  return array(
    "184379" => "Narok",
  );
}


function location_cities_list_ke_42() {
  return array();
}


function location_cities_list_ke_43() {
  return array(
    "7931933" => "Ol Kalou",
  );
}


function location_cities_list_ke_44() {
  return array(
    "182701" => "Nyeri",
  );
}


function location_cities_list_ke_45() {
  return array(
    "187725" => "Maralal",
  );
}


function location_cities_list_ke_46() {
  return array(
    "383388" => "Siaya",
  );
}


function location_cities_list_ke_47() {
  return array();
}


function location_cities_list_ke_48() {
  return array();
}


function location_cities_list_ke_49() {
  return array(
    "179381" => "Tharaka",
  );
}


function location_cities_list_ke_50() {
  return array(
    "191220" => "Kitale",
  );
}


function location_cities_list_ke_51() {
  return array(
    "189280" => "Lodwar",
  );
}


function location_cities_list_ke_52() {
  return array(
    "198629" => "Eldoret",
  );
}


function location_cities_list_ke_53() {
  return array(
    "187110" => "Mbale",
  );
}


function location_cities_list_ke_54() {
  return array(
    "178443" => "Wajir",
  );
}


function location_cities_list_ke_55() {
  return array(
    "194160" => "Kapenguria",
  );
}
