<?php

function location_cities_list_ma_04 () {
	return array (
		"2561124" => t("Ahfir"),
		"2555467" => t("Berkane"),
		"2550806" => t("El Aioun"),
		"2545017" => t("Jerada"),
		"2541479" => t("Nador"),
		"2540483" => t("Oujda"),
		"2530048" => t("Taourirt"),
		"2526435" => t("Zaio"),
	);
}


function location_cities_list_ma_13 () {
	return array (
		"2561668" => t("Agadir"),
		"2540850" => t("Ouarzazat"),
		"2539134" => t("Oulad Teima"),
		"2534515" => t("Sidi Ifni"),
		"2529649" => t("Taroudant"),
		"2527915" => t("Tineghir"),
		"2527089" => t("Tiznit"),
		"2526452" => t("Zagora"),
	);
}


function location_cities_list_ma_10 () {
	return array (
		"2556657" => t("Azemmour"),
		"2550078" => t("El Jadida"),
		"2537881" => t("Safi"),
		"2536074" => t("Sidi Bennour"),
		"2526488" => t("Youssoufia"),
	);
}


function location_cities_list_ma_03 () {
	return array (
		"2558545" => t("Al Hoceima"),
		"2548489" => t("Guercif"),
		"2545985" => t("Imzourene"),
		"2531480" => t("Tahala"),
		"2530155" => t("Taounate"),
		"2529317" => t("Taza"),
		"2527645" => t("Tirhanimine"),
	);
}


function location_cities_list_ma_07 () {
	return array (
		"2558470" => t("Khemisset"),
		"2538475" => t("Rabat"),
		"2537763" => t("Sale"),
		"2562055" => t("Skhirat"),
		"2528659" => t("Tiflet"),
	);
}


function location_cities_list_ma_01 () {
	return array (
		"2557055" => t("Asilah"),
		"2553455" => t("Chefchaouene"),
		"2544001" => t("Ksar el Kebir"),
		"2543549" => t("Larache"),
		"2542987" => t("Martil"),
		"2530335" => t("Tangier"),
		"2528910" => t("Tetouan"),
	);
}


function location_cities_list_ma_14 () {
	return array (
		"2548526" => t("Guelmim"),
		"2530241" => t("Tan-Tan"),
	);
}


function location_cities_list_ma_02 () {
	return array (
		"2544571" => t("Kenitra"),
		"2542866" => t("Mechra Belqsiri"),
		"2540810" => t("Ouazzane"),
		"2533191" => t("Sidi Qacem"),
		"2532945" => t("Sidi Slimane"),
		"2532822" => t("Sidi Yahia el Gharb"),
		"2532394" => t("Souq Larb'a al Gharb"),
	);
}


function location_cities_list_ma_09 () {
	return array (
		"2556272" => t("Berrechid"),
		"6546693" => t("Boujniba"),
		"2553751" => t("Bouznika"),
		"2544248" => t("Khouribga"),
		"2540689" => t("Oued Zem"),
		"2537406" => t("Settat"),
	);
}


function location_cities_list_ma_05 () {
	return array (
		"2548885" => t("Fes"),
		"2537545" => t("Sefrou"),
	);
}


function location_cities_list_ma_08 () {
	return array (
		"2553604" => t("Casablanca"),
		"2542051" => t("Mohammedia"),
	);
}


function location_cities_list_ma_06 () {
	return array (
		"2556464" => t("Azrou"),
		"2550252" => t("El Hajeb"),
		"2544333" => t("Khenifra"),
		"2542715" => t("Meknes"),
		"2542227" => t("Midelt"),
	);
}


function location_cities_list_ma_11 () {
	return array (
		"2549263" => t("Essaouira"),
		"2542997" => t("Marrakesh"),
	);
}


function location_cities_list_ma_12 () {
	return array (
		"2555745" => t("Beni Mellal"),
		"2548830" => t("Fkih Ben Salah"),
		"2544720" => t("Kasba Tadla"),
	);
}


