<?php


function location_cities_list_az_abs() {
  return array(
    "585915" => "Khirdalan",
  );
}


function location_cities_list_az_agm() {
  return array(
    "148619" => "Agdam",
  );
}


function location_cities_list_az_ags() {
  return array(
    "587378" => "Agdas",
  );
}


function location_cities_list_az_agc() {
  return array(
    "587384" => "Agdzhabedy",
  );
}


function location_cities_list_az_aga() {
  return array();
}


function location_cities_list_az_agu() {
  return array(
    "587361" => "Aghsu",
  );
}


function location_cities_list_az_ab() {
  return array(
    "148565" => "Sirvan",
  );
}


function location_cities_list_az_ast() {
  return array(
    "148445" => "Astara",
  );
}


function location_cities_list_az_ba() {
  return array(
    "584614" => "Zabrat",
    "585103" => "Qaracuxur",
    "585184" => "Sabuncu",
    "585557" => "Mastaga",
    "585568" => "Mardakyany",
    "585630" => "Lokbatan",
    "586340" => "Yeni Suraxani",
    "586429" => "Hovsan",
    "586925" => "Buzovna",
    "586968" => "Biny Selo",
    "587078" => "Bilajari",
    "587084" => "Baku",
    "587261" => "Amirdzhan",
    "824003" => "Bakixanov",
  );
}


function location_cities_list_az_bal() {
  return array();
}


function location_cities_list_az_bar() {
  return array(
    "587057" => "Barda",
  );
}


function location_cities_list_az_bey() {
  return array(
    "148354" => "Beyləqan",
  );
}


function location_cities_list_az_bil() {
  return array(
    "148340" => "Pushkino",
  );
}


function location_cities_list_az_cab() {
  return array();
}


function location_cities_list_az_das() {
  return array();
}


function location_cities_list_az_dav() {
  return array(
    "586763" => "Divichibazar",
  );
}


function location_cities_list_az_fuz() {
  return array(
    "148106" => "Fizuli",
  );
}


function location_cities_list_az_gad() {
  return array();
}


function location_cities_list_az_ga() {
  return array(
    "586523" => "Ganja",
  );
}


function location_cities_list_az_qob() {
  return array();
}


function location_cities_list_az_gor() {
  return array();
}


function location_cities_list_az_goy() {
  return array(
    "586427" => "Geoktschai",
  );
}


function location_cities_list_az_xan() {
  return array(
    "584716" => "Yelenendorf",
  );
}


function location_cities_list_az_hac() {
  return array(
    "585225" => "Haciqabul",
  );
}


function location_cities_list_az_imi() {
  return array(
    "147982" => "Imishli",
  );
}


function location_cities_list_az_ism() {
  return array();
}


function location_cities_list_az_cal() {
  return array(
    "148290" => "Dzhalilabad",
  );
}


function location_cities_list_az_xac() {
  return array(
    "584717" => "Xacmaz",
  );
}


function location_cities_list_az_xiz() {
  return array();
}


function location_cities_list_az_kur() {
  return array(
    "585763" => "Kyurdarmir",
  );
}


function location_cities_list_az_kal() {
  return array();
}


function location_cities_list_az_la() {
  return array(
    "147622" => "Lǝnkǝran",
  );
}


function location_cities_list_az_lac() {
  return array();
}


function location_cities_list_az_ler() {
  return array();
}


function location_cities_list_az_lan() {
  return array();
}


function location_cities_list_az_mas() {
  return array();
}


function location_cities_list_az_mi() {
  return array(
    "585514" => "Mingelchaur",
  );
}


function location_cities_list_az_na() {
  return array();
}


function location_cities_list_az_nx() {
  return array(
    "147429" => "Nakhchivan",
  );
}


function location_cities_list_az_75() {
  return array();
}


function location_cities_list_az_nef() {
  return array(
    "147425" => "Neftcala",
  );
}


function location_cities_list_az_ogu() {
  return array();
}


function location_cities_list_az_qab() {
  return array();
}


function location_cities_list_az_qax() {
  return array();
}


function location_cities_list_az_qaz() {
  return array(
    "585226" => "Qazax",
  );
}


function location_cities_list_az_qba() {
  return array(
    "585221" => "Quba",
  );
}


function location_cities_list_az_qbi() {
  return array();
}


function location_cities_list_az_qus() {
  return array(
    "585220" => "Qusar",
  );
}


function location_cities_list_az_sat() {
  return array(
    "147059" => "Ahmadbayli",
    "147288" => "Saatli",
  );
}


function location_cities_list_az_sab() {
  return array(
    "585187" => "Sabirabad",
  );
}


function location_cities_list_az_sal() {
  return array(
    "147271" => "Salyan",
  );
}


function location_cities_list_az_smx() {
  return array();
}


function location_cities_list_az_sak() {
  return array();
}


function location_cities_list_az_sa() {
  return array(
    "585170" => "Sheki",
  );
}


function location_cities_list_az_smi() {
  return array(
    "585156" => "Shamakhi",
  );
}


function location_cities_list_az_skr() {
  return array(
    "585152" => "Shamkhor",
  );
}


function location_cities_list_az_siy() {
  return array();
}


function location_cities_list_az_sm() {
  return array(
    "584923" => "Sumqayit",
    "585379" => "Haci Zeynalabdin",
  );
}


function location_cities_list_az_tar() {
  return array(
    "584871" => "Terter",
  );
}


function location_cities_list_az_tov() {
  return array();
}


function location_cities_list_az_uca() {
  return array(
    "584791" => "Ujar",
  );
}


function location_cities_list_az_xa() {
  return array(
    "146970" => "Xankǝndi",
  );
}


function location_cities_list_az_xci() {
  return array();
}


function location_cities_list_az_xvd() {
  return array();
}


function location_cities_list_az_yar() {
  return array();
}


function location_cities_list_az_yev() {
  return array();
}


function location_cities_list_az_ye() {
  return array(
    "584649" => "Yevlakh",
  );
}


function location_cities_list_az_zan() {
  return array();
}


function location_cities_list_az_zaq() {
  return array(
    "584596" => "Zaqatala",
  );
}


function location_cities_list_az_zar() {
  return array();
}


function location_cities_list_az_ss() {
  return array(
    "147105" => "Shushi",
  );
}


function location_cities_list_az_sus() {
  return array();
}
