<?php


function location_cities_list_kp_04() {
  return array(
    "2043572" => "Kanggye-si",
  );
}


function location_cities_list_kp_07() {
  return array(
    "1866923" => "Wonsan",
    "1867927" => "T'ongch'on-up",
    "1875632" => "Kosan",
    "1877148" => "Hoeyang",
    "1879672" => "Anbyon-up",
  );
}


function location_cities_list_kp_09() {
  return array(
    "2042267" => "Onsong",
    "2042498" => "Nanam",
    "2042503" => "Namyang-dong",
    "2042738" => "Musan-up",
    "2042987" => "Kyongsong",
    "2043484" => "Kilju",
    "2044091" => "Hoeryong",
    "2044757" => "Chongjin",
    "2045311" => "Aoji-ri",
  );
}


function location_cities_list_kp_08() {
  return array(
    "1871484" => "Samho-rodongjagu",
    "1875588" => "Kowon-up",
    "1877030" => "Hungnam",
    "1877449" => "Hamhung",
    "2038854" => "Yuktae-dong",
    "2042249" => "Yonggwang-up",
    "2043677" => "Iwon-up",
    "2044050" => "Hongwon",
  );
}


function location_cities_list_kp_06() {
  return array(
    "1869446" => "Songnim",
    "1870883" => "Sariwon",
    "1876873" => "Hwangju-up",
    "1877046" => "Hukkyo-ri",
    "1879682" => "Anak",
  );
}


function location_cities_list_kp_05() {
  return array(
    "1866569" => "Yonan-up",
    "1873172" => "Ongjin",
    "1876373" => "Kaesong",
    "1877615" => "Haeju",
    "1879029" => "Changyon",
    "1879487" => "Chaeryong-up",
    "1879544" => "Ayang-ni",
  );
}


function location_cities_list_kp_13() {
  return array(
    "2040674" => "Sonbong",
    "2042645" => "Najin",
  );
}


function location_cities_list_kp_03() {
  return array(
    "1875107" => "Kusong",
    "1875506" => "Kujang-up",
    "1878389" => "Chongju",
    "2039623" => "Uiju",
    "2040893" => "Sinuiju",
    "2041533" => "Sakchu-up",
  );
}


function location_cities_list_kp_02() {
  return array(
    "1870413" => "Sil-li",
    "1870742" => "Sinanju",
    "1871871" => "P'yongsong",
    "1873757" => "Namp'o",
    "1879613" => "Anju",
  );
}


function location_cities_list_kp_01() {
  return array(
    "1868998" => "Sungho 1-tong",
    "1869021" => "Sunan",
    "1871859" => "Pyongyang",
    "1876153" => "Kangdong-up",
    "1877872" => "Chunghwa",
  );
}


function location_cities_list_kp_10() {
  return array(
    "2043531" => "Kapsan-up",
    "2043835" => "Hyesan-dong",
    "2043837" => "Hyesan-si",
  );
}
