<?php

function location_cities_list_al_12 () {
	return array (
		"363243" => t("Sarande"),
		"3183719" => t("Vlore"),
	);
}


function location_cities_list_al_07 () {
	return array (
		"782661" => t("Kukes"),
	);
}


function location_cities_list_al_06 () {
	return array (
		"782756" => t("Korce"),
	);
}


function location_cities_list_al_05 () {
	return array (
		"783148" => t("Gjirokaster"),
	);
}


function location_cities_list_al_03 () {
	return array (
		"783263" => t("Elbasan"),
	);
}


function location_cities_list_al_09 () {
	return array (
		"783493" => t("Burrel"),
	);
}


function location_cities_list_al_11 () {
	return array (
		"3185211" => t("Kavaje"),
		"3183875" => t("Tirana"),
	);
}


function location_cities_list_al_10 () {
	return array (
		"3184081" => t("Shkoder"),
	);
}


function location_cities_list_al_04 () {
	return array (
		"3185672" => t("Fier"),
		"3185670" => t("Fier-Cifci"),
		"3184862" => t("Lushnje"),
		"3184517" => t("Patos Fshat"),
	);
}


function location_cities_list_al_08 () {
	return array (
		"3185012" => t("Lac"),
		"3184935" => t("Lezhe"),
	);
}


function location_cities_list_al_01 () {
	return array (
		"3186084" => t("Berat"),
		"3185060" => t("Kucove"),
	);
}


function location_cities_list_al_02 () {
	return array (
		"3185728" => t("Durres"),
		"3185082" => t("Kruje"),
	);
}


