<?php

function location_cities_list_tz_15 () {
	return array (
		"148730" => t("Zanzibar"),
	);
}


function location_cities_list_tz_06 () {
	return array (
		"148842" => t("Wete"),
	);
}


function location_cities_list_tz_14 () {
	return array (
		"160464" => t("Chimala"),
		"159380" => t("Igurusi"),
		"159107" => t("Ipinda"),
		"158151" => t("Katumba"),
		"156627" => t("Kiwira"),
		"156111" => t("Kyela"),
		"154380" => t("Mbeya"),
		"153352" => t("Mlowo"),
		"150453" => t("Rujewa"),
		"149437" => t("Tukuyu"),
		"149402" => t("Tunduma"),
		"148942" => t("Vwawa"),
	);
}


function location_cities_list_tz_19 () {
	return array (
		"161290" => t("Bagamoyo"),
		"160877" => t("Bungu"),
		"160660" => t("Chalinze"),
		"158027" => t("Kibaha"),
		"157977" => t("Kibiti"),
		"155743" => t("Lugoba"),
		"153482" => t("Mkuranga"),
		"153412" => t("Mlandizi"),
		"152403" => t("Mvomero"),
		"148987" => t("Vikindu"),
	);
}


function location_cities_list_tz_08 () {
	return array (
		"158563" => t("Kakonko"),
		"158214" => t("Kasulu"),
		"157960" => t("Kibondo"),
		"157738" => t("Kigoma"),
		"153709" => t("Mwandiga"),
		"151567" => t("Nguruka"),
		"149050" => t("Uvinza"),
	);
}


function location_cities_list_tz_18 () {
	return array (
		"155307" => t("Kihangara"),
		"153759" => t("Misungwi"),
		"152224" => t("Mwanza"),
		"151599" => t("Ngudu"),
		"149151" => t("Usagara"),
	);
}


function location_cities_list_tz_01 () {
	return array (
		"161325" => t("Arusha"),
		"158324" => t("Kiratu"),
		"6640202" => t("Merelani"),
		"152743" => t("Mto wa Mbu"),
		"149155" => t("Usa River"),
	);
}


function location_cities_list_tz_24 () {
	return array (
		"159386" => t("Igunga"),
		"155515" => t("Mabama"),
		"150930" => t("Nzega"),
		"149929" => t("Sikonge"),
		"149658" => t("Tabora"),
		"149418" => t("Tumbi"),
		"149172" => t("Urambo"),
	);
}


function location_cities_list_tz_22 () {
	return array (
		"159045" => t("Isaka"),
		"158597" => t("Kahama"),
		"156963" => t("Kishapu"),
		"154002" => t("Mhango"),
		"152376" => t("Mwadui"),
		"150885" => t("Old Shinyanga"),
		"150006" => t("Shinyanga"),
		"149775" => t("Songwa"),
		"149512" => t("Tinde"),
	);
}


function location_cities_list_tz_13 () {
	return array (
		"160892" => t("Bunda"),
		"160798" => t("Butiama"),
		"158016" => t("Kibara"),
		"152663" => t("Mugumu"),
		"152497" => t("Muriti"),
		"152451" => t("Musoma"),
		"151108" => t("Nyamuswa"),
		"149854" => t("Sirari"),
		"149581" => t("Tarime"),
	);
}


function location_cities_list_tz_25 () {
	return array (
		"160592" => t("Chanika"),
		"155569" => t("Lushoto"),
		"155076" => t("Makuyuni"),
		"154780" => t("Maramba"),
		"154566" => t("Matui"),
		"154470" => t("Mazinde"),
		"153423" => t("Mlalo"),
		"152632" => t("Muheza"),
		"149606" => t("Tanga"),
	);
}


function location_cities_list_tz_20 () {
	return array (
		"160670" => t("Chala"),
		"157107" => t("Kirando"),
		"156098" => t("Laela"),
		"154638" => t("Matai"),
		"151986" => t("Namanyere"),
		"149703" => t("Sumbawanga"),
	);
}


function location_cities_list_tz_11 () {
	return array (
		"149812" => t("Sokoni"),
	);
}


function location_cities_list_tz_23 () {
	return array (
		"159398" => t("Igugunu"),
		"159267" => t("Ikungi"),
		"159186" => t("Ilongero"),
		"158904" => t("Itigi"),
		"157198" => t("Kiomboi"),
		"154097" => t("Mgandu"),
		"152781" => t("Mtinko"),
		"152546" => t("Mungaa"),
		"150634" => t("Puma"),
		"150099" => t("Sepuka"),
		"150037" => t("Shelui"),
		"149879" => t("Singida"),
	);
}


function location_cities_list_tz_09 () {
	return array (
		"159647" => t("Hedaru"),
		"156025" => t("Lembeni"),
		"153209" => t("Moshi"),
		"150276" => t("Same"),
	);
}


function location_cities_list_tz_05 () {
	return array (
		"161154" => t("Biharamulo"),
		"161023" => t("Bugarama"),
		"160961" => t("Bukoba"),
		"158684" => t("Kabanga"),
		"158492" => t("Kamachumu"),
		"158179" => t("Katerero"),
		"151711" => t("Ngara"),
		"151373" => t("Nshamba"),
		"151363" => t("Nsunga"),
		"150436" => t("Rulenge"),
	);
}


function location_cities_list_tz_16 () {
	return array (
		"159909" => t("Geiro"),
		"159492" => t("Ifakara"),
		"157863" => t("Kidatu"),
		"157826" => t("Kidodi"),
		"157403" => t("Kilosa"),
		"155334" => t("Magole"),
		"155016" => t("Malinyi"),
		"153871" => t("Mikumi"),
		"153384" => t("Mlimba"),
		"153220" => t("Morogoro"),
		"152933" => t("Msowero"),
		"151678" => t("Ngerengere"),
	);
}


function location_cities_list_tz_26 () {
	return array (
		"161312" => t("Babati"),
		"161204" => t("Bashanet"),
		"161197" => t("Basotu"),
		"160266" => t("Dareda"),
		"160172" => t("Dongobesh"),
		"159951" => t("Galappo"),
		"155310" => t("Magugu"),
		"151929" => t("Nangwa"),
	);
}


function location_cities_list_tz_03 () {
	return array (
		"160196" => t("Dodoma"),
		"158024" => t("Kibakwe"),
		"156510" => t("Kondoa"),
		"153094" => t("Mpwapwa"),
	);
}


function location_cities_list_tz_21 () {
	return array (
		"878400" => t("Kigonsera"),
		"155285" => t("Mahanje"),
		"878073" => t("Maposeni"),
		"878041" => t("Matiri"),
		"877998" => t("Mbinga"),
		"877401" => t("Songea"),
		"877384" => t("Tingi"),
	);
}


function location_cities_list_tz_02 () {
	return array (
		"160263" => t("Dar es Salaam"),
		"155321" => t("Magomeni"),
	);
}


function location_cities_list_tz_04 () {
	return array (
		"159179" => t("Ilula"),
		"159071" => t("Iringa"),
		"158825" => t("Izazi"),
		"155405" => t("Mafinga"),
	);
}


function location_cities_list_tz_12 () {
	return array (
		"878281" => t("Lindi"),
		"155921" => t("Liwale"),
		"877702" => t("Nachingwea"),
		"877471" => t("Nyangao"),
	);
}


function location_cities_list_tz_10 () {
	return array (
		"160677" => t("Chake Chake"),
	);
}


function location_cities_list_tz_17 () {
	return array (
		"878367" => t("Kitama"),
		"878223" => t("Luchingu"),
		"878195" => t("Lukuledi"),
		"878058" => t("Masasi"),
		"877747" => t("Mtwara"),
		"877605" => t("Nanganga"),
		"877597" => t("Nangomba"),
		"877581" => t("Nanyamba"),
		"877532" => t("Newala Kisimani"),
		"877391" => t("Tandahimba"),
	);
}


