<?php


function location_cities_list_sl_e() {
  return array(
    "2404041" => "Segbwema",
    "2407656" => "Koidu",
    "2407790" => "Kenema",
  );
}


function location_cities_list_sl_n() {
  return array(
    "2404433" => "Port Loko",
    "2406407" => "Makeni",
    "2406916" => "Lunsar",
    "2408329" => "Kabala",
  );
}


function location_cities_list_sl_s() {
  return array(
    "2410048" => "Bo",
  );
}


function location_cities_list_sl_w() {
  return array(
    "2403094" => "Waterloo",
    "2409306" => "Freetown",
  );
}
