<?php


function location_cities_list_cu_10() {
  return array(
    "3543299" => "Puerto Padre",
    "3550598" => "Las Tunas",
    "3556078" => "Jobabo",
    "3556268" => "Jesus Menendez",
    "3563856" => "Colombia",
    "3569024" => "Amancio",
  );
}


function location_cities_list_cu_99() {
  return array(
    "3545867" => "Nueva Gerona",
  );
}


function location_cities_list_cu_ar() {
  return array(
    "3540680" => "San Cristobal",
    "3540885" => "San Antonio de los Banos",
    "3547600" => "Mariel",
    "3557347" => "Guira de Melena",
    "3557801" => "Guanajay",
    "3567612" => "Bauta",
    "3567995" => "Bahia Honda",
    "3568312" => "Artemisa",
    "3569136" => "Alquizar",
  );
}


function location_cities_list_cu_12() {
  return array(
    "3533753" => "Yara",
    "3542167" => "Rio Cauto",
    "3545981" => "Niquero",
    "3547260" => "Media Luna",
    "3547867" => "Manzanillo",
    "3556168" => "Jiguani",
    "3557332" => "Guisa",
    "3564885" => "Cauto Cristo",
    "3565951" => "Campechuela",
    "3567597" => "Bayamo",
    "3567669" => "Bartolome Maso",
  );
}


function location_cities_list_cu_ma() {
  return array(
    "3537845" => "Santa Cruz del Norte",
    "3539560" => "San Jose de las Lajas",
    "3548529" => "Madruga",
    "3551608" => "La Salud",
    "3556351" => "Jaruco",
    "3567546" => "Bejucal",
  );
}


function location_cities_list_cu_09() {
  return array(
    "3534363" => "Vertientes",
    "3536259" => "Sibanicu",
    "3537840" => "Santa Cruz del Sur",
    "3545841" => "Nuevitas",
    "3546894" => "Minas",
    "3557923" => "Guaimaro",
    "3558771" => "Florida",
    "3559318" => "Esmeralda",
    "3566067" => "Camaguey",
    "3754915" => "Jimaguayu",
  );
}


function location_cities_list_cu_08() {
  return array(
    "3534432" => "Venezuela",
    "3543498" => "Primero de Enero",
    "3546434" => "Moron",
    "3558792" => "Florencia",
    "3564084" => "Ciro Redondo",
    "3564178" => "Ciego de Avila",
    "3564394" => "Chambas",
    "3567823" => "Baragua",
  );
}


function location_cities_list_cu_06() {
  return array(
    "3541999" => "Rodas",
    "3545040" => "Palmira",
    "3562827" => "Cumanayagua",
    "3563145" => "Cruces",
    "3564124" => "Cienfuegos",
    "3569546" => "Aguada de Pasajeros",
    "3569741" => "Abreus",
  );
}


function location_cities_list_cu_14() {
  return array(
    "3542137" => "Rio Guayabal de Yateras",
    "3548441" => "Maisi",
    "3557689" => "Guantanamo",
    "3567834" => "Baracoa",
  );
}


function location_cities_list_cu_11() {
  return array(
    "3534749" => "Urbano Noris",
    "3541446" => "Sagua de Tanamo",
    "3546791" => "Moa",
    "3556077" => "Jobabo",
    "3556969" => "Holguin",
    "3558315" => "Gibara",
    "3562895" => "Cueto",
    "3566429" => "Cacocum",
    "3567869" => "Banes",
    "3746938" => "Baguanos",
  );
}


function location_cities_list_cu_03() {
  return array(
    "3536724" => "Santiago de las Vegas",
    "3538803" => "San Miguel del Padron",
    "3542502" => "Regla",
    "3553478" => "Havana",
    "3557846" => "Guanabacoa",
    "3564436" => "Cerro",
    "3568342" => "Arroyo Naranjo",
    "3569370" => "Alamar",
    "3746181" => "Habana del Este",
    "3746183" => "Centro Habana",
    "3746184" => "La Habana Vieja",
    "6956646" => "Arroyo Naranjo",
    "6956647" => "Boyeros",
    "6956648" => "Diez de Octubre",
  );
}


function location_cities_list_cu_04() {
  return array(
    "3534632" => "Varadero",
    "3534761" => "Union de Reyes",
    "3544393" => "Perico",
    "3544607" => "Pedro Betancourt",
    "3547398" => "Matanzas",
    "3555907" => "Jovellanos",
    "3556437" => "Jaguey Grande",
    "3563843" => "Colon",
    "3565432" => "Cardenas",
    "3566134" => "Calimete",
  );
}


function location_cities_list_cu_01() {
  return array(
    "3534094" => "Vinales",
    "3544091" => "Pinar del Rio",
    "3546882" => "Minas de Matahambre",
    "3548993" => "Los Palacios",
    "3557758" => "Guane",
    "3563559" => "Consolacion del Sur",
  );
}


function location_cities_list_cu_07() {
  return array(
    "3533826" => "Yaguajay",
    "3534915" => "Trinidad",
    "3540667" => "Sancti Spiritus",
    "3551184" => "La Sierpe",
    "3556334" => "Jatibonico",
    "3558744" => "Fomento",
    "3563609" => "Condado",
    "3566603" => "Cabaiguan",
  );
}


function location_cities_list_cu_13() {
  return array(
    "3536729" => "Santiago de Cuba",
    "3539093" => "San Luis",
    "3545064" => "Palma Soriano",
    "3563504" => "Contramaestre",
  );
}


function location_cities_list_cu_05() {
  return array(
    "3536640" => "Santo Domingo",
    "3537906" => "Santa Clara",
    "3541440" => "Sagua la Grande",
    "3542455" => "Remedios",
    "3542744" => "Ranchuelo",
    "3543961" => "Placetas",
    "3547976" => "Manicaragua",
    "3559416" => "Encrucijada",
    "3563317" => "Corralillo",
    "3564114" => "Cifuentes",
    "3566054" => "Camajuani",
    "3566356" => "Caibarien",
  );
}
