<?php

function location_cities_list_by_mi () {
	return array (
		"628634" => t("Dzyarzhynsk"),
		"630376" => t("Horad Barysaw"),
		"618800" => t("Horad Zhodzina"),
		"627083" => t("Kalodzishchy"),
		"625625" => t("Maladzyechna"),
		"625409" => t("Mar''ina Horka"),
		"625144" => t("Minsk"),
		"622428" => t("Salihorsk"),
		"621741" => t("Slutsk"),
		"621266" => t("Stowbtsy"),
		"620181" => t("Vilyeyka"),
	);
}


function location_cities_list_by_ho () {
	return array (
		"629018" => t("Dobrush"),
		"627907" => t("Homyel'"),
		"627751" => t("Kalinkavichy"),
		"625324" => t("Mazyr"),
		"622739" => t("Rahachow"),
		"622794" => t("Rechytsa"),
		"621074" => t("Svyetlahorsk"),
		"618806" => t("Zhlobin"),
	);
}


function location_cities_list_by_vi () {
	return array (
		"627908" => t("Hlybokaye"),
		"625743" => t("Lyepyel'"),
		"624784" => t("Navapolatsk"),
		"624079" => t("Orsha"),
		"623760" => t("Pastavy"),
		"623317" => t("Polatsk"),
		"620127" => t("Vitebsk"),
	);
}


function location_cities_list_by_hr () {
	return array (
		"627904" => t("Hrodna"),
		"626081" => t("Lida"),
		"625367" => t("Masty"),
		"624785" => t("Navahrudak"),
		"622113" => t("Shchuchin"),
		"621754" => t("Slonim"),
		"621713" => t("Smarhon'"),
		"620391" => t("Vawkavysk"),
	);
}


function location_cities_list_by_br () {
	return array (
		"630429" => t("Baranavichy"),
		"629634" => t("Brest"),
		"629454" => t("Byaroza"),
		"627800" => t("Ivatsevichy"),
		"627145" => t("Kobryn"),
		"625818" => t("Luninyets"),
		"623549" => t("Pinsk"),
		"622997" => t("Pruzhany"),
	);
}


function location_cities_list_by_ma () {
	return array (
		"624034" => t("Asipovichy"),
		"630468" => t("Babruysk"),
		"629447" => t("Bykhaw"),
		"627905" => t("Horki"),
		"626450" => t("Krychaw"),
		"625665" => t("Mahilyow"),
	);
}


function location_cities_list_by_hm () {
	return array (
		"8020218" => t("Malinovka"),
	);
}


