<?php

function location_cities_list_dk_82 () {
	return array (
		"2624652" => t("Arhus"),
		"2620425" => t("Herning"),
		"2620046" => t("Holstebro"),
		"2619771" => t("Horsens"),
		"2615006" => t("Randers"),
		"2614030" => t("Silkeborg"),
		"2613731" => t("Skive"),
		"2610319" => t("Viborg"),
	);
}


function location_cities_list_dk_83 () {
	return array (
		"2625070" => t("Aabenraa"),
		"2622447" => t("Esbjerg"),
		"2621951" => t("Fredericia"),
		"2620964" => t("Haderslev"),
		"2618528" => t("Kolding"),
		"2616015" => t("Nyborg"),
		"2615876" => t("Odense"),
		"2613102" => t("Sonderborg"),
		"2612045" => t("Svendborg"),
		"2610613" => t("Vejle"),
	);
}


function location_cities_list_dk_84 () {
	return array (
		"2624906" => t("Albertslund"),
		"2624341" => t("Ballerup"),
		"2624112" => t("Birkerod"),
		"2623188" => t("Charlottenlund"),
		"2618425" => t("Copenhagen"),
		"2622306" => t("Farum"),
		"2621942" => t("Frederiksberg"),
		"2621356" => t("Glostrup"),
		"2620473" => t("Helsingor"),
		"2620320" => t("Hillerod"),
		"2619856" => t("Horsholm"),
		"2619528" => t("Hvidovre"),
		"2619377" => t("Ishoj"),
		"2617658" => t("Lillerod"),
		"2614600" => t("Rodovre"),
		"2612629" => t("Stenlose"),
		"2611828" => t("Taastrup"),
	);
}


function location_cities_list_dk_85 () {
	return array (
		"2621215" => t("Greve"),
		"2620147" => t("Holbaek"),
		"2619154" => t("Kalundborg"),
		"2618415" => t("Koge"),
		"2618361" => t("Korsor"),
		"2616038" => t("Naestved"),
		"2615961" => t("Nykobing Falster"),
		"2614764" => t("Ringsted"),
		"2614481" => t("Roskilde"),
		"2613460" => t("Slagelse"),
	);
}


function location_cities_list_dk_81 () {
	return array (
		"2624886" => t("Aalborg"),
		"2621927" => t("Frederikshavn"),
		"2620214" => t("Hjorring"),
	);
}


