<?php


function location_cities_list_py_asu() {
  return array(
    "3439389" => "Asuncion",
  );
}


function location_cities_list_py_11() {
  return array(
    "3436728" => "Villa Elisa",
    "3437056" => "San Lorenzo",
    "3437127" => "San Antonio",
    "3437665" => "Nemby",
    "3437842" => "Limpio",
    "3437863" => "Lambare",
    "3437918" => "Itaugua",
    "3437954" => "Ita",
    "3438115" => "Fernando de la Mora",
    "3438995" => "Colonia Mariano Roque Alonso",
    "3439214" => "Capiata",
  );
}


function location_cities_list_py_16() {
  return array();
}


function location_cities_list_py_19() {
  return array();
}


function location_cities_list_py_5() {
  return array(
    "3438819" => "Coronel Oviedo",
    "3439317" => "Caaguazu",
  );
}


function location_cities_list_py_6() {
  return array(
    "3439297" => "Caazapa",
  );
}


function location_cities_list_py_14() {
  return array();
}


function location_cities_list_py_1() {
  return array(
    "3438834" => "Concepcion",
  );
}


function location_cities_list_py_7() {
  return array(
    "3438735" => "Encarnacion",
  );
}


function location_cities_list_py_8() {
  return array(
    "3437063" => "San Juan Bautista",
  );
}


function location_cities_list_py_9() {
  return array();
}


function location_cities_list_py_15() {
  return array(
    "3436725" => "Villa Hayes",
  );
}


function location_cities_list_py_2() {
  return array();
}


function location_cities_list_py_3() {
  return array(
    "3439320" => "Caacupe",
  );
}


function location_cities_list_py_12() {
  return array(
    "3437526" => "Pilar",
  );
}


function location_cities_list_py_10() {
  return array(
    "3437444" => "Presidente Franco",
    "3439101" => "Ciudad del Este",
  );
}


function location_cities_list_py_13() {
  return array(
    "3437547" => "Pedro Juan Caballero",
  );
}


function location_cities_list_py_4() {
  return array(
    "3436714" => "Villarrica",
  );
}
