<?php

function location_cities_list_il_m () {
	return array (
		"293207" => t("Yehud"),
		"293222" => t("Yavne"),
		"293690" => t("Rosh Ha'Ayin"),
		"293703" => t("Rishon LeZiyyon"),
		"293768" => t("Ramla"),
		"293807" => t("Ra'anana"),
		"293896" => t("Qalansuwa"),
		"294071" => t("Netanya"),
		"294074" => t("Ness Ziona"),
		"294421" => t("Lod"),
		"294514" => t("Kfar Saba"),
		"294604" => t("Kafr Qasim"),
		"294760" => t("Hod HaSharon"),
		"295127" => t("Tirah"),
		"295130" => t("Et Taiyiba"),
		"6693674" => t("Petah Tikva"),
		"6693679" => t("Modiin"),
	);
}


function location_cities_list_il_ha () {
	return array (
		"293286" => t("Umm el Fahm"),
		"293308" => t("Tirat Karmel"),
		"293822" => t("Qiryat Yam"),
		"293831" => t("Qiryat Motzkin"),
		"293844" => t("Qiryat Bialik"),
		"293845" => t("Qiryat Ata"),
		"294078" => t("Nesher"),
		"294801" => t("Haifa"),
		"294946" => t("Hadera"),
		"295365" => t("Daliyat el Karmil"),
	);
}


function location_cities_list_il_jm () {
	return array (
		"281184" => t("Jerusalem"),
		"294244" => t("Mevo Betar"),
		"295432" => t("Bet Shemesh"),
		"6945291" => t("Old City"),
		"7498240" => t("West Jerusalem"),
	);
}


function location_cities_list_il_z () {
	return array (
		"293100" => t("Zefat"),
		"293322" => t("Tiberias"),
		"293420" => t("maalot Tarshiha"),
		"293426" => t("Tamra"),
		"293655" => t("Sakhnin"),
		"293825" => t("Qiryat Shemona"),
		"294098" => t("Nazareth"),
		"294117" => t("Nahariyya"),
		"294210" => t("Migdal Ha`Emeq"),
		"294387" => t("Maghar"),
		"294577" => t("Karmi'el"),
		"294608" => t("Kafr Manda"),
		"294610" => t("Kafr Kanna"),
		"294622" => t("Judieda Makr"),
		"295174" => t("Er Reina"),
		"295435" => t("Bet She'an"),
		"295721" => t("`Akko"),
		"295739" => t("`Afula `Illit"),
	);
}


function location_cities_list_il_d () {
	return array (
		"293619" => t("Sederot"),
		"293842" => t("Qiryat Gat"),
		"293992" => t("Ofaqim"),
		"294068" => t("Netivot"),
		"295277" => t("Eilat"),
		"295328" => t("Dimona"),
		"295530" => t("Beersheba"),
		"295620" => t("Ashqelon"),
		"295629" => t("Ashdod"),
		"295657" => t("'Arad"),
	);
}


function location_cities_list_il_ta () {
	return array (
		"293253" => t("Yafo"),
		"293397" => t("Tel Aviv"),
		"293783" => t("Ramat HaSharon"),
		"293788" => t("Ramat Gan"),
		"293962" => t("Or Yehuda"),
		"294751" => t("Holon"),
		"294778" => t("Herzliyya"),
		"294981" => t("Giv`at Shemu'el"),
		"294999" => t("Giv`atayim"),
		"295514" => t("Bene Beraq"),
		"295548" => t("Bat Yam"),
	);
}
