<?php


function location_cities_list_tl_al() {
  return array(
    "1651816" => "Aileu",
  );
}


function location_cities_list_tl_an() {
  return array();
}


function location_cities_list_tl_ba() {
  return array(
    "1649539" => "Baucau",
    "1943235" => "Venilale",
  );
}


function location_cities_list_tl_bo() {
  return array(
    "1636670" => "Maliana",
  );
}


function location_cities_list_tl_co() {
  return array(
    "1626459" => "Suai",
  );
}


function location_cities_list_tl_oe() {
  return array();
}


function location_cities_list_tl_di() {
  return array(
    "1645457" => "Dili",
  );
}


function location_cities_list_tl_er() {
  return array();
}


function location_cities_list_tl_la() {
  return array(
    "1937274" => "Lospalos",
  );
}


function location_cities_list_tl_li() {
  return array(
    "1635826" => "Maubara",
    "1637730" => "Liquica",
  );
}


function location_cities_list_tl_mt() {
  return array();
}


function location_cities_list_tl_mf() {
  return array(
    "1937031" => "Same",
  );
}


function location_cities_list_tl_vi() {
  return array();
}
