<?php


function location_cities_list_so_aw() {
  return array(
    "8045596" => "Baki",
  );
}


function location_cities_list_so_bk() {
  return array();
}


function location_cities_list_so_bn() {
  return array(
    "53654" => "Mogadishu",
  );
}


function location_cities_list_so_br() {
  return array(
    "53157" => "Qandala",
    "64013" => "Bosaso",
  );
}


function location_cities_list_so_by() {
  return array(
    "63571" => "Buurhakaba",
    "64536" => "Baydhabo",
  );
}


function location_cities_list_so_ga() {
  return array(
    "62788" => "Ceeldheer",
  );
}


function location_cities_list_so_ge() {
  return array(
    "54715" => "Luuq",
    "65170" => "Baardheere",
  );
}


function location_cities_list_so_hi() {
  return array(
    "63689" => "Buulobarde",
    "64460" => "Beledweyne",
  );
}


function location_cities_list_so_jh() {
  return array(
    "55671" => "Kismayo",
    "56399" => "Jamaame",
  );
}


function location_cities_list_so_sh() {
  return array(
    "50672" => "Wanlaweyn",
    "52867" => "Qoryooley",
    "54225" => "Marka",
    "65785" => "Afgooye",
  );
}


function location_cities_list_so_jd() {
  return array(
    "56166" => "Jilib",
  );
}


function location_cities_list_so_mu() {
  return array(
    "59611" => "Gaalkacyo",
  );
}


function location_cities_list_so_nu() {
  return array(
    "58933" => "Garoowe",
    "60019" => "Eyl",
  );
}


function location_cities_list_so_sa() {
  return array(
    "62691" => "Ceerigaabo",
  );
}


function location_cities_list_so_sd() {
  return array(
    "56335" => "Jawhar",
  );
}


function location_cities_list_so_so() {
  return array(
    "400769" => "Laascaanood",
  );
}


function location_cities_list_so_to() {
  return array(
    "63795" => "Burco",
  );
}


function location_cities_list_so_wo() {
  return array(
    "57289" => "Hargeysa",
    "64435" => "Berbera",
  );
}
