<?php


function location_cities_list_ca_ab() {
  return array(
    "5882799" => "Airdrie",
    "5913490" => "Calgary",
    "5914653" => "Camrose",
    "5924618" => "Cochrane",
    "5946768" => "Edmonton",
    "5955895" => "Fort McMurray",
    "5964347" => "Grande Prairie",
    "6051562" => "Leduc",
    "6053154" => "Lethbridge",
    "6071618" => "Medicine Hat",
    "6118158" => "Red Deer",
    "6146279" => "Sherwood Park",
    "6154383" => "Spruce Grove",
    "6155033" => "St. Albert",
  );
}


function location_cities_list_ca_bc() {
  return array(
    "5881791" => "Abbotsford",
    "5911606" => "Burnaby",
    "5914132" => "Campbell River",
    "5921356" => "Chilliwack",
    "5927689" => "Coquitlam",
    "5930890" => "Courtenay",
    "5931800" => "Cranbrook",
    "5937615" => "Delta",
    "5943865" => "Duncan",
    "5955960" => "Fort St. John",
    "5989045" => "Kamloops",
    "5990579" => "Kelowna",
    "6049388" => "Langford",
    "6049429" => "Langley",
    "6049430" => "Langley",
    "6065686" => "Maple Ridge",
    "6075293" => "Mission",
    "6085772" => "Nanaimo",
    "6087844" => "New Westminster",
    "6089661" => "North Cowichan",
    "6090785" => "North Vancouver",
    "6091919" => "Oak Bay",
    "6098642" => "Parksville",
    "6101141" => "Penticton",
    "6105815" => "Pitt Meadows",
    "6111632" => "Port Alberni",
    "6111962" => "Port Moody",
    "6113365" => "Prince George",
    "6122085" => "Richmond",
    "6139416" => "Salmon Arm",
    "6159905" => "Surrey",
    "6162949" => "Terrace",
    "6173331" => "Vancouver",
    "6173864" => "Vernon",
    "6174041" => "Victoria",
    "6180961" => "White Rock",
    "7281931" => "Okanagan",
    "7281936" => "West Kelowna",
    "7602078" => "Ladner",
    "7669012" => "Walnut Grove",
    "8533869" => "West Vancouver",
  );
}


function location_cities_list_ca_mb() {
  return array(
    "5907896" => "Brandon",
    "6183235" => "Winnipeg",
  );
}


function location_cities_list_ca_nb() {
  return array(
    "5939219" => "Dieppe",
    "5957776" => "Fredericton",
    "6075081" => "Miramichi",
    "6076211" => "Moncton",
    "6138517" => "Saint John",
    "6545023" => "Edmundston",
  );
}


function location_cities_list_ca_nl() {
  return array(
    "5926511" => "Conception Bay South",
    "5927969" => "Corner Brook",
    "6082231" => "Mount Pearl",
    "6324733" => "St. John's",
  );
}


function location_cities_list_ca_nt() {
  return array(
    "6185377" => "Yellowknife",
  );
}


function location_cities_list_ca_ns() {
  return array(
    "5935277" => "Dartmouth",
    "5961564" => "Glace Bay",
    "6087579" => "New Glasgow",
    "6169587" => "Truro",
    "6324729" => "Halifax",
    "6354908" => "Sydney",
    "7280414" => "Cole Harbour",
  );
}


function location_cities_list_ca_nu() {
  return array();
}


function location_cities_list_ca_on() {
  return array(
    "5882873" => "Ajax",
    "5894171" => "Barrie",
    "5897884" => "Belleville",
    "5907180" => "Bradford West Gwillimbury",
    "5907364" => "Brampton",
    "5907983" => "Brant",
    "5907990" => "Brantford",
    "5909294" => "Brockville",
    "5911592" => "Burlington",
    "5913695" => "Cambridge",
    "5923101" => "Clarence-Rockland",
    "5924579" => "Cobourg",
    "5925975" => "Collingwood",
    "5928065" => "Cornwall",
    "5950267" => "Etobicoke",
    "5955815" => "Fort Erie",
    "5964700" => "Greater Sudbury",
    "5965812" => "Greater Napanee",
    "5967629" => "Guelph",
    "5969782" => "Hamilton",
    "5978765" => "Huntsville",
    "5991056" => "Kenora",
    "5991370" => "Keswick",
    "5992500" => "Kingston",
    "5992996" => "Kitchener",
    "6051123" => "Leamington",
    "6058560" => "London",
    "6066513" => "Markham",
    "6073363" => "Midland",
    "6074377" => "Milton",
    "6075357" => "Mississauga",
    "6087701" => "Newmarket",
    "6087892" => "Niagara Falls",
    "6089125" => "Norfolk County",
    "6089426" => "North Bay",
    "6091104" => "North York",
    "6092122" => "Oakville",
    "6094201" => "Orangeville",
    "6094325" => "Orillia",
    "6094578" => "Oshawa",
    "6094817" => "Ottawa",
    "6095645" => "Owen Sound",
    "6100832" => "Pembroke",
    "6101645" => "Peterborough",
    "6104111" => "Pickering",
    "6111704" => "Port Colborne",
    "6113355" => "Prince Edward",
    "6115355" => "Quinte West",
    "6117731" => "Rayside-Balfour",
    "6122091" => "Richmond Hill",
    "6141190" => "Sarnia",
    "6141439" => "Sault Ste. Marie",
    "6155721" => "St. Catharines",
    "6157977" => "Stratford",
    "6158357" => "St. Thomas",
    "6165719" => "Thorold",
    "6166142" => "Thunder Bay",
    "6166739" => "Timmins",
    "6167865" => "Toronto",
    "6173577" => "Vaughan",
    "6176823" => "Waterloo",
    "6177869" => "Welland",
    "6182962" => "Windsor",
    "6184365" => "Woodstock",
    "8285452" => "Ancaster",
    "8558534" => "Willowdale",
  );
}


function location_cities_list_ca_pe() {
  return array(
    "5920288" => "Charlottetown",
  );
}


function location_cities_list_ca_qc() {
  return array(
    "5884083" => "Alma",
    "5884588" => "Amos",
    "5889745" => "Baie-Comeau",
    "5895650" => "Beaconsfield",
    "5898138" => "Beloeil",
    "5903510" => "Blainville",
    "5905132" => "Boisbriand",
    "5906267" => "Boucherville",
    "5909629" => "Brossard",
    "5914826" => "Candiac",
    "5919566" => "Chambly",
    "5920433" => "Chateauguay",
    "5928488" => "Cote-Saint-Luc",
    "5938513" => "Deux-Montagnes",
    "5940956" => "Dollard-Des Ormeaux",
    "5941925" => "Dorval",
    "5942845" => "Drummondville",
    "5959974" => "Gatineau",
    "5964215" => "Granby",
    "5987650" => "Joliette",
    "5992830" => "Kirkland",
    "6049863" => "La Prairie",
    "6050263" => "L'Assomption",
    "6050610" => "Laval",
    "6059891" => "Longueuil",
    "6064180" => "Magog",
    "6067494" => "Mascouche",
    "6075061" => "Mirabel",
    "6077243" => "Montreal",
    "6077315" => "Mont-Royal",
    "6077340" => "Mont-Saint-Hilaire",
    "6107325" => "Pointe-Claire",
    "6119518" => "Repentigny",
    "6128577" => "Rouyn-Noranda",
    "6137270" => "Saguenay",
    "6137489" => "Saint-Basile-le-Grand",
    "6137540" => "Saint-Bruno-de-Montarville",
    "6137633" => "Saint-Constant",
    "6137781" => "Sainte-Catherine",
    "6137941" => "Sainte-Julie",
    "6138121" => "Sainte-Therese",
    "6138175" => "Saint-Eustache",
    "6138374" => "Saint-Hyacinthe",
    "6138495" => "Saint-Jean-sur-Richelieu",
    "6138501" => "Saint-Jerome",
    "6138599" => "Saint-Lambert",
    "6138610" => "Saint-Laurent",
    "6138617" => "Saint-Lazare",
    "6138625" => "Saint-Leonard",
    "6139289" => "Salaberry-de-Valleyfield",
    "6144312" => "Sept-Iles",
    "6145489" => "Shawinigan",
    "6146143" => "Sherbrooke",
    "6151352" => "Sorel-Tracy",
    "6163012" => "Terrebonne",
    "6169141" => "Trois-Rivieres",
    "6173017" => "Val-d'Or",
    "6173508" => "Varennes",
    "6173570" => "Vaudreuil-Dorion",
    "6174151" => "Victoriaville",
    "6179226" => "Westmount",
    "6325494" => "Quebec",
    "6325521" => "Levis",
    "6354895" => "Rimouski",
    "6354897" => "Riviere-du-Loup",
    "6534203" => "L'Ancienne-Lorette",
    "6943827" => "Thetford-Mines",
    "7302647" => "Bellechasse Regional County Municipality",
    "7303786" => "Jonquiere",
    "7535681" => "Saint-Augustin-de-Desmaures",
  );
}


function location_cities_list_ca_sk() {
  return array(
    "6058024" => "Lloydminster",
    "6078112" => "Moose Jaw",
    "6089404" => "North Battleford",
    "6113335" => "Prince Albert",
    "6119109" => "Regina",
    "6141256" => "Saskatoon",
    "6185607" => "Yorkton",
  );
}


function location_cities_list_ca_yt() {
  return array(
    "6180550" => "Whitehorse",
  );
}
