<?php


function location_cities_list_mu_ag () {
	return array (
	);
}


function location_cities_list_mu_bl () {
	return array (
	);
}


function location_cities_list_mu_cc () {
	return array (
	);
}


function location_cities_list_mu_fl () {
	return array (
		"934631" => t("Centre de Flacq"),
		"934750" => t("Bel Air"),
	);
}


function location_cities_list_mu_gp () {
	return array (
		"934322" => t("Mahebourg"),
	);
}


function location_cities_list_mu_mo () {
	return array (
		"934032" => t("Saint Pierre"),
	);
}


function location_cities_list_mu_pa () {
	return array (
		"933959" => t("Triolet"),
		"1106809" => t("Le Hochet"),
	);
}


function location_cities_list_mu_pw () {
	return array (
		"933945" => t("Vacoas"),
		"934131" => t("Quatre Bornes"),
		"934570" => t("Curepipe"),
	);
}


function location_cities_list_mu_pl () {
	return array (
		"934154" => t("Port Louis"),
	);
}


function location_cities_list_mu_rr () {
	return array (
		"934488" => t("Goodlands"),
	);
}


function location_cities_list_mu_ro () {
	return array (
	);
}


function location_cities_list_mu_sa () {
	return array (
	);
}
