<?php


function location_cities_list_rs_vo () {
	return array (
		"783814" => t("Zrenjanin"),
		"784136" => t("Vrsac"),
		"785559" => t("Stara Pazova"),
		"785965" => t("Senta"),
		"787237" => t("Pancevo"),
		"789518" => t("Kikinda"),
		"790015" => t("Ingija"),
		"792814" => t("Becej"),
		"3187297" => t("Vrbas"),
		"3189595" => t("Subotica"),
		"3190103" => t("Sremska Mitrovica"),
		"3190342" => t("Sombor"),
		"3191429" => t("Ruma"),
		"3194360" => t("Novi Sad"),
		"3204672" => t("Backa Topola"),
		"3204674" => t("Backa Palanka"),
		"3204793" => t("Apatin"),
	);
}


function location_cities_list_rs_se () {
	return array (
		"783920" => t("Zemun"),
		"784024" => t("Zajecar"),
		"784227" => t("Vranje"),
		"784873" => t("Trstenik"),
		"785753" => t("Smederevska Palanka"),
		"785756" => t("Smederevo"),
		"786690" => t("Prokuplje"),
		"786827" => t("Pozarevac"),
		"787050" => t("Pirot"),
		"787516" => t("Obrenovac"),
		"787595" => t("Novi Pazar"),
		"787657" => t("Nis"),
		"787718" => t("Negotin"),
		"788709" => t("Leskovac"),
		"788771" => t("Lazarevac"),
		"788975" => t("Krusevac"),
		"789107" => t("Kraljevo"),
		"789128" => t("Kragujevac"),
		"789923" => t("Jagodina"),
		"790367" => t("Gornji Milanovac"),
		"791678" => t("Cuprija"),
		"792078" => t("Cacak"),
		"792456" => t("Bor"),
		"792680" => t("Belgrade"),
		"793111" => t("Arangelovac"),
		"3188402" => t("Valjevo"),
		"3188434" => t("Uzice"),
		"3191376" => t("Sabac"),
		"6619277" => t("Knjazevac"),
	);
}
