<?php


function location_cities_list_cu_10 () {
	return array (
		"3543299" => t("Puerto Padre"),
		"3550598" => t("Las Tunas"),
		"3556078" => t("Jobabo"),
		"3556268" => t("Jesus Menendez"),
		"3563856" => t("Colombia"),
		"3569024" => t("Amancio"),
	);
}


function location_cities_list_cu_99 () {
	return array (
		"3545867" => t("Nueva Gerona"),
	);
}


function location_cities_list_cu_ar () {
	return array (
		"3540680" => t("San Cristobal"),
		"3540885" => t("San Antonio de los Banos"),
		"3547600" => t("Mariel"),
		"3557347" => t("Guira de Melena"),
		"3557801" => t("Guanajay"),
		"3567612" => t("Bauta"),
		"3567995" => t("Bahia Honda"),
		"3568312" => t("Artemisa"),
		"3569136" => t("Alquizar"),
	);
}


function location_cities_list_cu_12 () {
	return array (
		"3533753" => t("Yara"),
		"3542167" => t("Rio Cauto"),
		"3545981" => t("Niquero"),
		"3547260" => t("Media Luna"),
		"3547867" => t("Manzanillo"),
		"3556168" => t("Jiguani"),
		"3557332" => t("Guisa"),
		"3564885" => t("Cauto Cristo"),
		"3565951" => t("Campechuela"),
		"3567597" => t("Bayamo"),
		"3567669" => t("Bartolome Maso"),
	);
}


function location_cities_list_cu_ma () {
	return array (
		"3537845" => t("Santa Cruz del Norte"),
		"3539560" => t("San Jose de las Lajas"),
		"3548529" => t("Madruga"),
		"3551608" => t("La Salud"),
		"3556351" => t("Jaruco"),
		"3567546" => t("Bejucal"),
	);
}


function location_cities_list_cu_09 () {
	return array (
		"3534363" => t("Vertientes"),
		"3536259" => t("Sibanicu"),
		"3537840" => t("Santa Cruz del Sur"),
		"3545841" => t("Nuevitas"),
		"3546894" => t("Minas"),
		"3557923" => t("Guaimaro"),
		"3558771" => t("Florida"),
		"3559318" => t("Esmeralda"),
		"3566067" => t("Camaguey"),
		"3754915" => t("Jimaguayu"),
	);
}


function location_cities_list_cu_08 () {
	return array (
		"3534432" => t("Venezuela"),
		"3543498" => t("Primero de Enero"),
		"3546434" => t("Moron"),
		"3558792" => t("Florencia"),
		"3564084" => t("Ciro Redondo"),
		"3564178" => t("Ciego de Avila"),
		"3564394" => t("Chambas"),
		"3567823" => t("Baragua"),
	);
}


function location_cities_list_cu_06 () {
	return array (
		"3541999" => t("Rodas"),
		"3545040" => t("Palmira"),
		"3562827" => t("Cumanayagua"),
		"3563145" => t("Cruces"),
		"3564124" => t("Cienfuegos"),
		"3569546" => t("Aguada de Pasajeros"),
		"3569741" => t("Abreus"),
	);
}


function location_cities_list_cu_14 () {
	return array (
		"3542137" => t("Rio Guayabal de Yateras"),
		"3548441" => t("Maisi"),
		"3557689" => t("Guantanamo"),
		"3567834" => t("Baracoa"),
	);
}


function location_cities_list_cu_11 () {
	return array (
		"3534749" => t("Urbano Noris"),
		"3541446" => t("Sagua de Tanamo"),
		"3546791" => t("Moa"),
		"3556077" => t("Jobabo"),
		"3556969" => t("Holguin"),
		"3558315" => t("Gibara"),
		"3562895" => t("Cueto"),
		"3566429" => t("Cacocum"),
		"3567869" => t("Banes"),
		"3746938" => t("Baguanos"),
	);
}


function location_cities_list_cu_03 () {
	return array (
		"3536724" => t("Santiago de las Vegas"),
		"3538803" => t("San Miguel del Padron"),
		"3542502" => t("Regla"),
		"3553478" => t("Havana"),
		"3557846" => t("Guanabacoa"),
		"3564436" => t("Cerro"),
		"3568342" => t("Arroyo Naranjo"),
		"3569370" => t("Alamar"),
		"3746181" => t("Habana del Este"),
		"3746183" => t("Centro Habana"),
		"3746184" => t("La Habana Vieja"),
		"6956646" => t("Arroyo Naranjo"),
		"6956647" => t("Boyeros"),
		"6956648" => t("Diez de Octubre"),
	);
}


function location_cities_list_cu_04 () {
	return array (
		"3534632" => t("Varadero"),
		"3534761" => t("Union de Reyes"),
		"3544393" => t("Perico"),
		"3544607" => t("Pedro Betancourt"),
		"3547398" => t("Matanzas"),
		"3555907" => t("Jovellanos"),
		"3556437" => t("Jaguey Grande"),
		"3563843" => t("Colon"),
		"3565432" => t("Cardenas"),
		"3566134" => t("Calimete"),
	);
}


function location_cities_list_cu_01 () {
	return array (
		"3534094" => t("Vinales"),
		"3544091" => t("Pinar del Rio"),
		"3546882" => t("Minas de Matahambre"),
		"3548993" => t("Los Palacios"),
		"3557758" => t("Guane"),
		"3563559" => t("Consolacion del Sur"),
	);
}


function location_cities_list_cu_07 () {
	return array (
		"3533826" => t("Yaguajay"),
		"3534915" => t("Trinidad"),
		"3540667" => t("Sancti Spiritus"),
		"3551184" => t("La Sierpe"),
		"3556334" => t("Jatibonico"),
		"3558744" => t("Fomento"),
		"3563609" => t("Condado"),
		"3566603" => t("Cabaiguan"),
	);
}


function location_cities_list_cu_13 () {
	return array (
		"3536729" => t("Santiago de Cuba"),
		"3539093" => t("San Luis"),
		"3545064" => t("Palma Soriano"),
		"3563504" => t("Contramaestre"),
	);
}


function location_cities_list_cu_05 () {
	return array (
		"3536640" => t("Santo Domingo"),
		"3537906" => t("Santa Clara"),
		"3541440" => t("Sagua la Grande"),
		"3542455" => t("Remedios"),
		"3542744" => t("Ranchuelo"),
		"3543961" => t("Placetas"),
		"3547976" => t("Manicaragua"),
		"3559416" => t("Encrucijada"),
		"3563317" => t("Corralillo"),
		"3564114" => t("Cifuentes"),
		"3566054" => t("Camajuani"),
		"3566356" => t("Caibarien"),
	);
}
