<?php


function location_cities_list_sv_ah () {
	return array (
		"3587426" => t("Ahuachapan"),
	);
}


function location_cities_list_sv_ca () {
	return array (
		"3583158" => t("Sensuntepeque"),
	);
}


function location_cities_list_sv_ch () {
	return array (
		"3587091" => t("Chalatenango"),
	);
}


function location_cities_list_sv_cu () {
	return array (
		"3583471" => t("San Martin"),
		"3586977" => t("Cojutepeque"),
	);
}


function location_cities_list_sv_li () {
	return array (
		"3583981" => t("Quezaltepeque"),
		"3584257" => t("Santa Tecla"),
		"3585157" => t("La Libertad"),
		"3587362" => t("Antiguo Cuscatlan"),
	);
}


function location_cities_list_sv_pa () {
	return array (
		"3582805" => t("Zacatecoluca"),
	);
}


function location_cities_list_sv_un () {
	return array (
		"3584772" => t("La Union"),
	);
}


function location_cities_list_sv_mo () {
	return array (
		"3583747" => t("San Francisco"),
	);
}


function location_cities_list_sv_sm () {
	return array (
		"3583379" => t("San Rafael Oriente"),
		"3583446" => t("San Miquel"),
	);
}


function location_cities_list_sv_ss () {
	return array (
		"3583096" => t("Soyapango"),
		"3583361" => t("San Salvador"),
		"3583480" => t("San Marcos"),
		"3584399" => t("Mejicanos"),
		"3585484" => t("Ilopango"),
		"3586814" => t("Delgado"),
		"3586833" => t("Cuscatancingo"),
		"3587308" => t("Ayutuxtepeque"),
		"3587345" => t("Apopa"),
		"3587428" => t("Aguilares"),
	);
}


function location_cities_list_sv_sv () {
	return array (
		"3583178" => t("San Vicente"),
	);
}


function location_cities_list_sv_sa () {
	return array (
		"3583334" => t("Santa Ana"),
		"3584384" => t("Metapan"),
		"3587086" => t("Chalchuapa"),
	);
}


function location_cities_list_sv_so () {
	return array (
		"3583098" => t("Sonzacate"),
		"3583102" => t("Sonsonate"),
		"3585473" => t("Izalco"),
		"3587498" => t("Acajutla"),
	);
}


function location_cities_list_sv_us () {
	return array (
		"3582883" => t("Usulutan"),
		"3583199" => t("Santiago de Maria"),
		"3584003" => t("Puerto El Triunfo"),
	);
}
