<?php

/**
 * Implementation of hook_form_alter()
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function contact_forms_alter_form_alter(&$form, $form_state, $form_id) {

  # for module "contact_forms"
  if ($form_id == 'contact_mail_page' && module_exists('contact_forms')) {
    $form['#prefix'] = "";
    $info = array(
      __('Site Suggestion', array('@code' => 'contact-info-suggestion')),
      __('Site Complaint', array('@code' => 'contact-info-complaint')),
      __('Volunteer', array('@code' => 'contact-info-volunteer')),
      __('General', array('@code' => 'contact-info-general')),
    );
    $form['info'] = array(
      '#type'    => 'select',
      '#options' => array_combine($info, $info),
      '#weight'  => -1,
    );
    $form['contact_information']['#weight'] = -2;
    array_unshift($form['#submit'], 'contact_mail_page_form_submit');

    $form['copy'] = array(
      '#type'  => 'checkbox',
      '#title' => __('Send yourself a copy.', array('@code' => 'contact-copy')),
    );

    drupal_set_subtitle(__('Contact', array('@code' => 'contact-page-title')));
  }
}

/**
 * Submitter for "contact_mail_page" form
 *
 * @param $form
 * @param $form_state
 */
function contact_mail_page_form_submit(&$form, &$form_state) {
  $values = & $form_state['values'];
  $values['subject'] = '[' . $values['info'] . '] ' . $values['subject'];
}
