<?php

/**
 * Implementation of hook_nodeapi()
 *
 * @param $node
 * @param $op
 * @param null $a3
 * @param null $a4
 */
function argument_options_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  if ('argument' == $node->type || 'resource' == $node->type) {
    switch ($op) {
      case 'insert' :
      case 'update' :
        $choices = cpoll_load_choices($node->field_reference[0]['nid']);
        foreach ($choices as $chid => $choice) {
          db_query("
            REPLACE INTO {argument_options}
            SET val = '%d', nid = '%d', chid = '%d', date_added = '%s'",
            $choice['val'], $node->nid, $chid, date('Y-m-d h:i:s')
          );
        }
      break;
      case 'load' :
        if (isset($node->argument_options)) {
          return;
        }
        $node->argument_options = array();
        $result = db_query("
          SELECT cc.*, IFNULL(val, 0) val
          FROM {content_field_reference} cfr
          INNER JOIN {cpoll_choices} cc ON cc.nid = cfr.field_reference_nid
          LEFT JOIN {argument_options} ao ON ao.nid = cfr.nid AND cc.chid = ao.chid
          WHERE cfr.nid = '%d'", $node->nid);
        while ($row = db_fetch_array($result)) {
          $node->argument_options[$row['chid']] = $row;
        }
      break;
      case 'delete' :
        // delete records
        db_query("DELETE FROM {argument_options} WHERE nid = '%d'", $node->nid);
      break;
    }
  }
}

/**
 * @return array
 */
function argument_options_theme()
{
  $theme = array();

  $theme['argument_options'] = array(
    'arguments' => array('options' => array()),
    'template' => 'argument-options',
  );

  return $theme;
}