<?php

/**
 * Define the types of actions
 */
define('ACTIVITY_STREAM_ISSUE_CREATE', 'issue_create');
define('ACTIVITY_STREAM_ISSUE_VOTE', 'vote');
define('ACTIVITY_STREAM_ARGUMENT_CREATE', 'argument_create');
define('ACTIVITY_STREAM_ARGUMENT_REPLY', 'argument_reply');
define('ACTIVITY_STREAM_ARGUMENT_VOTE', 'argument_vote');
define('ACTIVITY_STREAM_ARGUMENT_REPLY_VOTE', 'argument_reply_vote');
define('ACTIVITY_STREAM_PROFILE_UPDATE', 'user_profile_update');
define('ACTIVITY_STREAM_BADGE', 'user_badge');
define('ACTIVITY_STREAM_FOLLOW', 'user_follow');

/**
 * API function
 */
function activity_stream_add_activity($type, $variables, $uid = false) {
  if ($uid === false) {
    global $user;
    $uid = $user->uid;
  }
  db_query("INSERT INTO {activity_stream} SET uid = '%d', type = '%s', variables = '%s', date_added = '%s'", $uid, $type, serialize($variables), date('Y-m-d H:i:s'));
}

/**
 * Implementation of hook_theme
 */
function activity_stream_theme() {
  $theme = array();

  $theme['activity_stream'] = array(
    'arguments' => array(
      'items'     => array(),
    ),
    'template'  => 'activity-stream',
  );

  $theme['activity_stream_item'] = array(
    'arguments' => array(
      'id'        => null,
      'uid'       => null,
      'type'      => null,
      'vars'      => array(),
      'date'      => null,
    ),
    'template'  => 'activity-stream-item',
  );

  return $theme;
}

/**
 * Get latest activities
 */
function _activity_stream_home($count = 100) {
  $items = array();

  $result = db_query("SELECT * FROM {activity_stream} ORDER BY date_added DESC LIMIT %d", $count);
  while ($item = db_fetch_array($result)) {
    $item['variables'] = unserialize($item['variables']);
    $item['date_added'] = ugc_time_interval($item['date_added']);
    $items[] = $item;
  }

  return $items;
}

/**
 * Implementation of hook_block
 */
function activity_stream_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['activity-stream-home'] = array(
        'info' => t('Activity Stream Home'),
      );
      return $blocks;
    case 'view':
      switch ($delta) {
        case 'activity-stream-home' :
          $block['subject'] = t('HAPPENING NOW');
          $block['content'] = theme('activity_stream', _activity_stream_home());
        break;
      }
      return $block;
  }
}