<?php

function contact_forms_extension_form_alter(&$form, $form_state, $form_id)
{
  if ($form_id == "contact_mail_page") {
    $info = array(t('Site Suggestion'), t('Site Complaint'), t('Volunteer'), t('General'));
    $form['info'] = array(
      '#type' => 'select',
      '#options' => array_combine($info, $info),
      '#weight' => -1,
    );
    $form['contact_information']['#weight'] = -2;
    array_unshift($form['#submit'], 'contact_forms_extension_form_submit');
  }
}

function contact_forms_extension_form_submit(&$form, &$form_state)
{
  $values = &$form_state['values'];
  $values['subject'] = '[' . $values['info'] . '] ' . $values['subject'];
}