<?php

/**
 * Implementation of hook_badges()
 *
 * @return array
 */
function badges_flag_badges()
{
  $badges = array();

  $badges['flag_first'] = array(
    'function' => 'badges_flag_check',
    'name' => t('Citizen Patrol'),
    'info' => t('First flagged post'),
  );
  $badges['flag_success'] = array(
    'function' => 'badges_flag_success_check',
    'name' => t('Scrutineer'),
    'info' => t('Flags post, that eventually results in a change or removal'),
  );

  return $badges;

  // Scrutineer
}

/**
 * @param $uid
 * @return bool
 */
function badges_flag_check($uid)
{
  static $cache;

  if (is_null($cache)) {
    $result = db_query("SELECT uid FROM {flag_content} fc GROUP BY content_type, content_id ORDER BY timestamp DESC");
    while ($_ = db_result($result)) {
      $cache[$_] = true;
    }
  }

  return isset($cache[$uid]);
}

/**
 * @param $uid
 * @return bool
 */
function badges_flag_success_check($uid)
{
  static $cache;

  if (is_null($cache)) {
    $result = db_query("
      SELECT fc.uid FROM {flag_content} fc
      INNER JOIN (
        (SELECT 'node' content_type, nid content_id, status FROM {node}) UNION
        (SELECT 'comment' content_type, cid content_id, 1-status FROM {comments})) c
      ON c.content_type = fc.content_type AND c.content_id = fc.content_id WHERE c.status = '%d'", 0);
    while ($_ = db_result($result)) {
      $cache[$_] = true;
    }
  }

  return isset($cache[$uid]);
}