<?php

/**
 * Implementation of hook_perm().
 */
function heard_perm() {
    return array('Heard Content View');
}

/**
 * Implementation of hook_menu().
 */
function heard_menu() {
    $items['heard/%node'] = array(
        'title callback' => 'heard_page_title',
        'title arguments' => array(1),
        'page callback' => 'heard_page_view',
        'page arguments' => array(1),
        'access arguments' => array('Heard Content View'),
        'type' => MENU_CALLBACK);

    return $items;
}

function heard_page_title($node) {
    return $node->title;
    
}

function heard_page_view($node, $cid = NULL) {

    global $gSitePath, $user, $gDocPath, $base_root;
  //drupal_set_title(check_plain($node->title));

    return node_show($node, $cid);
}
