<?php 

$list = array(
    "AD" => array('href' => "/countries/AD/andorra.html", 'name' => "Andorra"),
    "AE" => array('href' => "/countries/AE/united-arab-emirates.html", 'name' => "United Arab Emirates"),
    "AF" => array('href' => "/countries/AF/afghanistan.html", 'name' => "Afghanistan"),
    "AG" => array('href' => "/countries/AG/antigua-and-barbuda.html", 'name' => "Antigua and Barbuda"),
    "AI" => array('href' => "/countries/AI/anguilla.html", 'name' => "Anguilla"),
    "AL" => array('href' => "/countries/AL/albania.html", 'name' => "Albania"),
    "AM" => array('href' => "/countries/AM/armenia.html", 'name' => "Armenia"),
    // "AN" => array('href' => "/countries/AN/.html", 'name' => ""),
    "AO" => array('href' => "/countries/AO/angola.html", 'name' => "Angola"),
    "AQ" => array('href' => "/countries/AQ/antarctica.html", 'name' => "Antarctica"),
    "AR" => array('href' => "/countries/AR/argentina.html", 'name' => "Argentina"),
    "AS" => array('href' => "/countries/AS/american-samoa.html", 'name' => "American Samoa"),
    "AT" => array('href' => "/countries/AT/austria.html", 'name' => "Austria"),
    "AU" => array('href' => "/countries/AU/australia.html", 'name' => "Australia"),
    "AW" => array('href' => "/countries/AW/aruba.html", 'name' => "Aruba"),
    "AX" => array('href' => "/countries/AX/aland.html", 'name' => "Aland"),
    "AZ" => array('href' => "/countries/AZ/azerbaijan.html", 'name' => "Azerbaijan"),
    "BA" => array('href' => "/countries/BA/bosnia-and-herzegovina.html", 'name' => "Bosnia and Herzegovina"),
    "BB" => array('href' => "/countries/BB/barbados.html", 'name' => "Barbados"),
    "BD" => array('href' => "/countries/BD/bangladesh.html", 'name' => "Bangladesh"),
    "BE" => array('href' => "/countries/BE/belgium.html", 'name' => "Belgium"),
    "BF" => array('href' => "/countries/BF/burkina-faso.html", 'name' => "Burkina Faso"),
    "BG" => array('href' => "/countries/BG/bulgaria.html", 'name' => "Bulgaria"),
    "BH" => array('href' => "/countries/BH/bahrain.html", 'name' => "Bahrain"),
    "BI" => array('href' => "/countries/BI/burundi.html", 'name' => "Burundi"),
    "BJ" => array('href' => "/countries/BJ/benin.html", 'name' => "Benin"),
    "BL" => array('href' => "/countries/BL/saint-barthelemy.html", 'name' => "Saint Barthelemy"),
    "BM" => array('href' => "/countries/BM/bermuda.html", 'name' => "Bermuda"),
    "BN" => array('href' => "/countries/BN/brunei.html", 'name' => "Brunei"),
    "BO" => array('href' => "/countries/BO/bolivia.html", 'name' => "Bolivia"),
    "BQ" => array('href' => "/countries/BQ/bonaire.html", 'name' => "Bonaire"),
    "BR" => array('href' => "/countries/BR/brazil.html", 'name' => "Brazil"),
    "BS" => array('href' => "/countries/BS/bahamas.html", 'name' => "Bahamas"),
    "BT" => array('href' => "/countries/BT/bhutan.html", 'name' => "Bhutan"),
    "BV" => array('href' => "/countries/BV/bouvet-island.html", 'name' => "Bouvet Island"),
    "BW" => array('href' => "/countries/BW/botswana.html", 'name' => "Botswana"),
    "BY" => array('href' => "/countries/BY/belarus.html", 'name' => "Belarus"),
    "BZ" => array('href' => "/countries/BZ/belize.html", 'name' => "Belize"),
    "CA" => array('href' => "/countries/CA/canada.html", 'name' => "Canada"),
    "CC" => array('href' => "/countries/CC/cocos-%5Bkeeling%5D-islands.html", 'name' => "Cocos [Keeling] Islands"),
    "CD" => array('href' => "/countries/CD/democratic-republic-of-the-congo.html", 'name' => "Democratic Republic of the Congo"),
    "CF" => array('href' => "/countries/CF/central-african-republic.html", 'name' => "Central African Republic"),
    "CG" => array('href' => "/countries/CG/republic-of-the-congo.html", 'name' => "Republic of the Congo"),
    "CH" => array('href' => "/countries/CH/switzerland.html", 'name' => "Switzerland"),
    "CI" => array('href' => "/countries/CI/ivory-coast.html", 'name' => "Ivory Coast"),
    "CK" => array('href' => "/countries/CK/cook-islands.html", 'name' => "Cook Islands"),
    "CL" => array('href' => "/countries/CL/chile.html", 'name' => "Chile"),
    "CM" => array('href' => "/countries/CM/cameroon.html", 'name' => "Cameroon"),
    "CN" => array('href' => "/countries/CN/china.html", 'name' => "China"),
    "CO" => array('href' => "/countries/CO/colombia.html", 'name' => "Colombia"),
    "CR" => array('href' => "/countries/CR/costa-rica.html", 'name' => "Costa Rica"),
    // "CS" => array('href' => "/countries/CS/.html", 'name' => ""),
    "CU" => array('href' => "/countries/CU/cuba.html", 'name' => "Cuba"),
    "CV" => array('href' => "/countries/CV/cape-verde.html", 'name' => "Cape Verde"),
    "CW" => array('href' => "/countries/CW/curacao.html", 'name' => "Curacao"),
    "CX" => array('href' => "/countries/CX/christmas-island.html", 'name' => "Christmas Island"),
    "CY" => array('href' => "/countries/CY/cyprus.html", 'name' => "Cyprus"),
    "CZ" => array('href' => "/countries/CZ/czechia.html", 'name' => "Czechia"),
    "DE" => array('href' => "/countries/DE/germany.html", 'name' => "Germany"),
    "DJ" => array('href' => "/countries/DJ/djibouti.html", 'name' => "Djibouti"),
    "DK" => array('href' => "/countries/DK/denmark.html", 'name' => "Denmark"),
    "DM" => array('href' => "/countries/DM/dominica.html", 'name' => "Dominica"),
    "DO" => array('href' => "/countries/DO/dominican-republic.html", 'name' => "Dominican Republic"),
    "DZ" => array('href' => "/countries/DZ/algeria.html", 'name' => "Algeria"),
    "EC" => array('href' => "/countries/EC/ecuador.html", 'name' => "Ecuador"),
    "EE" => array('href' => "/countries/EE/estonia.html", 'name' => "Estonia"),
    "EG" => array('href' => "/countries/EG/egypt.html", 'name' => "Egypt"),
    "EH" => array('href' => "/countries/EH/western-sahara.html", 'name' => "Western Sahara"),
    "ER" => array('href' => "/countries/ER/eritrea.html", 'name' => "Eritrea"),
    "ES" => array('href' => "/countries/ES/spain.html", 'name' => "Spain"),
    "ET" => array('href' => "/countries/ET/ethiopia.html", 'name' => "Ethiopia"),
    "FI" => array('href' => "/countries/FI/finland.html", 'name' => "Finland"),
    "FJ" => array('href' => "/countries/FJ/fiji.html", 'name' => "Fiji"),
    "FK" => array('href' => "/countries/FK/falkland-islands.html", 'name' => "Falkland Islands"),
    "FM" => array('href' => "/countries/FM/micronesia.html", 'name' => "Micronesia"),
    "FO" => array('href' => "/countries/FO/faroe-islands.html", 'name' => "Faroe Islands"),
    "FR" => array('href' => "/countries/FR/france.html", 'name' => "France"),
    "GA" => array('href' => "/countries/GA/gabon.html", 'name' => "Gabon"),
    "GB" => array('href' => "/countries/GB/united-kingdom.html", 'name' => "United Kingdom"),
    "GD" => array('href' => "/countries/GD/grenada.html", 'name' => "Grenada"),
    "GE" => array('href' => "/countries/GE/georgia.html", 'name' => "Georgia"),
    "GF" => array('href' => "/countries/GF/french-guiana.html", 'name' => "French Guiana"),
    "GG" => array('href' => "/countries/GG/guernsey.html", 'name' => "Guernsey"),
    "GH" => array('href' => "/countries/GH/ghana.html", 'name' => "Ghana"),
    "GI" => array('href' => "/countries/GI/gibraltar.html", 'name' => "Gibraltar"),
    "GL" => array('href' => "/countries/GL/greenland.html", 'name' => "Greenland"),
    "GM" => array('href' => "/countries/GM/gambia.html", 'name' => "Gambia"),
    "GN" => array('href' => "/countries/GN/guinea.html", 'name' => "Guinea"),
    "GP" => array('href' => "/countries/GP/guadeloupe.html", 'name' => "Guadeloupe"),
    "GQ" => array('href' => "/countries/GQ/equatorial-guinea.html", 'name' => "Equatorial Guinea"),
    "GR" => array('href' => "/countries/GR/greece.html", 'name' => "Greece"),
    "GS" => array('href' => "/countries/GS/south-georgia-and-the-south-sandwich-islands.html", 'name' => "South Georgia and the South Sandwich Islands"),
    "GT" => array('href' => "/countries/GT/guatemala.html", 'name' => "Guatemala"),
    "GU" => array('href' => "/countries/GU/guam.html", 'name' => "Guam"),
    "GW" => array('href' => "/countries/GW/guinea-bissau.html", 'name' => "Guinea-Bissau"),
    "GY" => array('href' => "/countries/GY/guyana.html", 'name' => "Guyana"),
    "HK" => array('href' => "/countries/HK/hong-kong.html", 'name' => "Hong Kong"),
    "HM" => array('href' => "/countries/HM/heard-island-and-mcdonald-islands.html", 'name' => "Heard Island and McDonald Islands"),
    "HN" => array('href' => "/countries/HN/honduras.html", 'name' => "Honduras"),
    "HR" => array('href' => "/countries/HR/croatia.html", 'name' => "Croatia"),
    "HT" => array('href' => "/countries/HT/haiti.html", 'name' => "Haiti"),
    "HU" => array('href' => "/countries/HU/hungary.html", 'name' => "Hungary"),
    "ID" => array('href' => "/countries/ID/indonesia.html", 'name' => "Indonesia"),
    "IE" => array('href' => "/countries/IE/ireland.html", 'name' => "Ireland"),
    "IL" => array('href' => "/countries/IL/israel.html", 'name' => "Israel"),
    "IM" => array('href' => "/countries/IM/isle-of-man.html", 'name' => "Isle of Man"),
    "IN" => array('href' => "/countries/IN/india.html", 'name' => "India"),
    "IO" => array('href' => "/countries/IO/british-indian-ocean-territory.html", 'name' => "British Indian Ocean Territory"),
    "IQ" => array('href' => "/countries/IQ/iraq.html", 'name' => "Iraq"),
    "IR" => array('href' => "/countries/IR/iran.html", 'name' => "Iran"),
    "IS" => array('href' => "/countries/IS/iceland.html", 'name' => "Iceland"),
    "IT" => array('href' => "/countries/IT/italy.html", 'name' => "Italy"),
    "JE" => array('href' => "/countries/JE/jersey.html", 'name' => "Jersey"),
    "JM" => array('href' => "/countries/JM/jamaica.html", 'name' => "Jamaica"),
    "JO" => array('href' => "/countries/JO/jordan.html", 'name' => "Jordan"),
    "JP" => array('href' => "/countries/JP/japan.html", 'name' => "Japan"),
    "KE" => array('href' => "/countries/KE/kenya.html", 'name' => "Kenya"),
    "KG" => array('href' => "/countries/KG/kyrgyzstan.html", 'name' => "Kyrgyzstan"),
    "KH" => array('href' => "/countries/KH/cambodia.html", 'name' => "Cambodia"),
    "KI" => array('href' => "/countries/KI/kiribati.html", 'name' => "Kiribati"),
    "KM" => array('href' => "/countries/KM/comoros.html", 'name' => "Comoros"),
    "KN" => array('href' => "/countries/KN/saint-kitts-and-nevis.html", 'name' => "Saint Kitts and Nevis"),
    "KP" => array('href' => "/countries/KP/north-korea.html", 'name' => "North Korea"),
    "KR" => array('href' => "/countries/KR/south-korea.html", 'name' => "South Korea"),
    "KW" => array('href' => "/countries/KW/kuwait.html", 'name' => "Kuwait"),
    "KY" => array('href' => "/countries/KY/cayman-islands.html", 'name' => "Cayman Islands"),
    "KZ" => array('href' => "/countries/KZ/kazakhstan.html", 'name' => "Kazakhstan"),
    "LA" => array('href' => "/countries/LA/laos.html", 'name' => "Laos"),
    "LB" => array('href' => "/countries/LB/lebanon.html", 'name' => "Lebanon"),
    "LC" => array('href' => "/countries/LC/saint-lucia.html", 'name' => "Saint Lucia"),
    "LI" => array('href' => "/countries/LI/liechtenstein.html", 'name' => "Liechtenstein"),
    "LK" => array('href' => "/countries/LK/sri-lanka.html", 'name' => "Sri Lanka"),
    "LR" => array('href' => "/countries/LR/liberia.html", 'name' => "Liberia"),
    "LS" => array('href' => "/countries/LS/lesotho.html", 'name' => "Lesotho"),
    "LT" => array('href' => "/countries/LT/lithuania.html", 'name' => "Lithuania"),
    "LU" => array('href' => "/countries/LU/luxembourg.html", 'name' => "Luxembourg"),
    "LV" => array('href' => "/countries/LV/latvia.html", 'name' => "Latvia"),
    "LY" => array('href' => "/countries/LY/libya.html", 'name' => "Libya"),
    "MA" => array('href' => "/countries/MA/morocco.html", 'name' => "Morocco"),
    "MC" => array('href' => "/countries/MC/monaco.html", 'name' => "Monaco"),
    "MD" => array('href' => "/countries/MD/moldova.html", 'name' => "Moldova"),
    "ME" => array('href' => "/countries/ME/montenegro.html", 'name' => "Montenegro"),
    "MF" => array('href' => "/countries/MF/saint-martin.html", 'name' => "Saint Martin"),
    "MG" => array('href' => "/countries/MG/madagascar.html", 'name' => "Madagascar"),
    "MH" => array('href' => "/countries/MH/marshall-islands.html", 'name' => "Marshall Islands"),
    "MK" => array('href' => "/countries/MK/macedonia.html", 'name' => "Macedonia"),
    "ML" => array('href' => "/countries/ML/mali.html", 'name' => "Mali"),
    "MM" => array('href' => "/countries/MM/myanmar-%5Bburma%5D.html", 'name' => "Myanmar [Burma]"),
    "MN" => array('href' => "/countries/MN/mongolia.html", 'name' => "Mongolia"),
    "MO" => array('href' => "/countries/MO/macao.html", 'name' => "Macao"),
    "MP" => array('href' => "/countries/MP/northern-mariana-islands.html", 'name' => "Northern Mariana Islands"),
    "MQ" => array('href' => "/countries/MQ/martinique.html", 'name' => "Martinique"),
    "MR" => array('href' => "/countries/MR/mauritania.html", 'name' => "Mauritania"),
    "MS" => array('href' => "/countries/MS/montserrat.html", 'name' => "Montserrat"),
    "MT" => array('href' => "/countries/MT/malta.html", 'name' => "Malta"),
    "MU" => array('href' => "/countries/MU/mauritius.html", 'name' => "Mauritius"),
    "MV" => array('href' => "/countries/MV/maldives.html", 'name' => "Maldives"),
    "MW" => array('href' => "/countries/MW/malawi.html", 'name' => "Malawi"),
    "MX" => array('href' => "/countries/MX/mexico.html", 'name' => "Mexico"),
    "MY" => array('href' => "/countries/MY/malaysia.html", 'name' => "Malaysia"),
    "MZ" => array('href' => "/countries/MZ/mozambique.html", 'name' => "Mozambique"),
    "NA" => array('href' => "/countries/NA/namibia.html", 'name' => "Namibia"),
    "NC" => array('href' => "/countries/NC/new-caledonia.html", 'name' => "New Caledonia"),
    "NE" => array('href' => "/countries/NE/niger.html", 'name' => "Niger"),
    "NF" => array('href' => "/countries/NF/norfolk-island.html", 'name' => "Norfolk Island"),
    "NG" => array('href' => "/countries/NG/nigeria.html", 'name' => "Nigeria"),
    "NI" => array('href' => "/countries/NI/nicaragua.html", 'name' => "Nicaragua"),
    "NL" => array('href' => "/countries/NL/netherlands.html", 'name' => "Netherlands"),
    "NO" => array('href' => "/countries/NO/norway.html", 'name' => "Norway"),
    "NP" => array('href' => "/countries/NP/nepal.html", 'name' => "Nepal"),
    "NR" => array('href' => "/countries/NR/nauru.html", 'name' => "Nauru"),
    "NU" => array('href' => "/countries/NU/niue.html", 'name' => "Niue"),
    "NZ" => array('href' => "/countries/NZ/new-zealand.html", 'name' => "New Zealand"),
    "OM" => array('href' => "/countries/OM/oman.html", 'name' => "Oman"),
    "PA" => array('href' => "/countries/PA/panama.html", 'name' => "Panama"),
    "PE" => array('href' => "/countries/PE/peru.html", 'name' => "Peru"),
    "PF" => array('href' => "/countries/PF/french-polynesia.html", 'name' => "French Polynesia"),
    "PG" => array('href' => "/countries/PG/papua-new-guinea.html", 'name' => "Papua New Guinea"),
    "PH" => array('href' => "/countries/PH/philippines.html", 'name' => "Philippines"),
    "PK" => array('href' => "/countries/PK/pakistan.html", 'name' => "Pakistan"),
    "PL" => array('href' => "/countries/PL/poland.html", 'name' => "Poland"),
    "PM" => array('href' => "/countries/PM/saint-pierre-and-miquelon.html", 'name' => "Saint Pierre and Miquelon"),
    "PN" => array('href' => "/countries/PN/pitcairn-islands.html", 'name' => "Pitcairn Islands"),
    "PR" => array('href' => "/countries/PR/puerto-rico.html", 'name' => "Puerto Rico"),
    "PS" => array('href' => "/countries/PS/palestine.html", 'name' => "Palestine"),
    "PT" => array('href' => "/countries/PT/portugal.html", 'name' => "Portugal"),
    "PW" => array('href' => "/countries/PW/palau.html", 'name' => "Palau"),
    "PY" => array('href' => "/countries/PY/paraguay.html", 'name' => "Paraguay"),
    "QA" => array('href' => "/countries/QA/qatar.html", 'name' => "Qatar"),
    "RE" => array('href' => "/countries/RE/reunion.html", 'name' => "Reunion"),
    "RO" => array('href' => "/countries/RO/romania.html", 'name' => "Romania"),
    "RS" => array('href' => "/countries/RS/serbia.html", 'name' => "Serbia"),
    "RU" => array('href' => "/countries/RU/russia.html", 'name' => "Russia"),
    "RW" => array('href' => "/countries/RW/rwanda.html", 'name' => "Rwanda"),
    "SA" => array('href' => "/countries/SA/saudi-arabia.html", 'name' => "Saudi Arabia"),
    "SB" => array('href' => "/countries/SB/solomon-islands.html", 'name' => "Solomon Islands"),
    "SC" => array('href' => "/countries/SC/seychelles.html", 'name' => "Seychelles"),
    "SD" => array('href' => "/countries/SD/sudan.html", 'name' => "Sudan"),
    "SE" => array('href' => "/countries/SE/sweden.html", 'name' => "Sweden"),
    "SG" => array('href' => "/countries/SG/singapore.html", 'name' => "Singapore"),
    "SH" => array('href' => "/countries/SH/saint-helena.html", 'name' => "Saint Helena"),
    "SI" => array('href' => "/countries/SI/slovenia.html", 'name' => "Slovenia"),
    "SJ" => array('href' => "/countries/SJ/svalbard-and-jan-mayen.html", 'name' => "Svalbard and Jan Mayen"),
    "SK" => array('href' => "/countries/SK/slovakia.html", 'name' => "Slovakia"),
    "SL" => array('href' => "/countries/SL/sierra-leone.html", 'name' => "Sierra Leone"),
    "SM" => array('href' => "/countries/SM/san-marino.html", 'name' => "San Marino"),
    "SN" => array('href' => "/countries/SN/senegal.html", 'name' => "Senegal"),
    "SO" => array('href' => "/countries/SO/somalia.html", 'name' => "Somalia"),
    "SR" => array('href' => "/countries/SR/suriname.html", 'name' => "Suriname"),
    "SS" => array('href' => "/countries/SS/south-sudan.html", 'name' => "South Sudan"),
    "ST" => array('href' => "/countries/ST/sao-tome-and-principe.html", 'name' => "Sao Tome and Principe"),
    "SV" => array('href' => "/countries/SV/el-salvador.html", 'name' => "El Salvador"),
    "SX" => array('href' => "/countries/SX/sint-maarten.html", 'name' => "Sint Maarten"),
    "SY" => array('href' => "/countries/SY/syria.html", 'name' => "Syria"),
    "SZ" => array('href' => "/countries/SZ/swaziland.html", 'name' => "Swaziland"),
    "TC" => array('href' => "/countries/TC/turks-and-caicos-islands.html", 'name' => "Turks and Caicos Islands"),
    "TD" => array('href' => "/countries/TD/chad.html", 'name' => "Chad"),
    "TF" => array('href' => "/countries/TF/french-southern-territories.html", 'name' => "French Southern Territories"),
    "TG" => array('href' => "/countries/TG/togo.html", 'name' => "Togo"),
    "TH" => array('href' => "/countries/TH/thailand.html", 'name' => "Thailand"),
    "TJ" => array('href' => "/countries/TJ/tajikistan.html", 'name' => "Tajikistan"),
    "TK" => array('href' => "/countries/TK/tokelau.html", 'name' => "Tokelau"),
    "TL" => array('href' => "/countries/TL/east-timor.html", 'name' => "East Timor"),
    "TM" => array('href' => "/countries/TM/turkmenistan.html", 'name' => "Turkmenistan"),
    "TN" => array('href' => "/countries/TN/tunisia.html", 'name' => "Tunisia"),
    "TO" => array('href' => "/countries/TO/tonga.html", 'name' => "Tonga"),
    "TR" => array('href' => "/countries/TR/turkey.html", 'name' => "Turkey"),
    "TT" => array('href' => "/countries/TT/trinidad-and-tobago.html", 'name' => "Trinidad and Tobago"),
    "TV" => array('href' => "/countries/TV/tuvalu.html", 'name' => "Tuvalu"),
    "TW" => array('href' => "/countries/TW/taiwan.html", 'name' => "Taiwan"),
    "TZ" => array('href' => "/countries/TZ/tanzania.html", 'name' => "Tanzania"),
    "UA" => array('href' => "/countries/UA/ukraine.html", 'name' => "Ukraine"),
    "UG" => array('href' => "/countries/UG/uganda.html", 'name' => "Uganda"),
    "UM" => array('href' => "/countries/UM/u-s-minor-outlying-islands.html", 'name' => "U.S. Minor Outlying Islands"),
    "US" => array('href' => "/countries/US/united-states.html", 'name' => "United States"),
    "UY" => array('href' => "/countries/UY/uruguay.html", 'name' => "Uruguay"),
    "UZ" => array('href' => "/countries/UZ/uzbekistan.html", 'name' => "Uzbekistan"),
    "VA" => array('href' => "/countries/VA/vatican-city.html", 'name' => "Vatican City"),
    "VC" => array('href' => "/countries/VC/saint-vincent-and-the-grenadines.html", 'name' => "Saint Vincent and the Grenadines"),
    "VE" => array('href' => "/countries/VE/venezuela.html", 'name' => "Venezuela"),
    "VG" => array('href' => "/countries/VG/british-virgin-islands.html", 'name' => "British Virgin Islands"),
    "VI" => array('href' => "/countries/VI/u-s-virgin-islands.html", 'name' => "U.S. Virgin Islands"),
    "VN" => array('href' => "/countries/VN/vietnam.html", 'name' => "Vietnam"),
    "VU" => array('href' => "/countries/VU/vanuatu.html", 'name' => "Vanuatu"),
    "WF" => array('href' => "/countries/WF/wallis-and-futuna.html", 'name' => "Wallis and Futuna"),
    "WS" => array('href' => "/countries/WS/samoa.html", 'name' => "Samoa"),
    "XK" => array('href' => "/countries/XK/kosovo.html", 'name' => "Kosovo"),
    "YE" => array('href' => "/countries/YE/yemen.html", 'name' => "Yemen"),
    "YT" => array('href' => "/countries/YT/mayotte.html", 'name' => "Mayotte"),
    "ZA" => array('href' => "/countries/ZA/south-africa.html", 'name' => "South Africa"),
    "ZM" => array('href' => "/countries/ZM/zambia.html", 'name' => "Zambia"),
    "ZW" => array('href' => "/countries/ZW/zimbabwe.html", 'name' => "Zimbabwe"),
  );