<?php
/**
 * Implementation of hook_perm().
 */
function category_perm() {
  return array('Category list','Category add','Category view','Admin Category');
}


/**
 * Implementation of hook_menu().
 */
 
function category_menu() {	
  $items['category'] = array(
    'title' => ' Sections',
    'page callback' => 'treemenu_list',
    'access arguments' => array('Category list'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'category.pages.inc',
  );
$items['category/add'] = array(
    'title' => ' Add Sections',
    'page callback' => 'treemenu_add',
    'access arguments' => array('Category add'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
$items['category/edit'] = array(
    'title' => ' Edit Sections',
    'page callback' => 'treemenu_edit',
    'access arguments' => array('Category edit'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
$items['category/delete'] = array(
    'title' => 'Delete Sections',
    'page callback' => 'drupal_get_form',
	'page arguments' => array('menu_delete_confirm', 3),
    'access arguments' => array('Category delete'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
$items['category/follow'] = array(
    'title' => 'Follow Sections',
    'page callback' => 'search_follow',
    'access arguments' => array('Category view'),
    'file' => 'category.pages.inc',
  );
$items['category/unfollow'] = array(
    'title' => 'unfollow Sections',
    'page callback' => 'search_unfollow',
    'access arguments' => array('Category view'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );

$items['category/list'] = array(
    'title' => 'List Sections',
    'page callback' => 'category_list',
	'access arguments' => array('Category view'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'category.pages.inc',
  );
$items['admin/category'] = array(
    'title' => 'Admin Sections',
    'page callback' => 'category_admin',
	'access arguments' => array('Admin Category'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'category.pages.inc',
  );
$items['admin/category/add'] = array(
    'title' => ' Add Sections',
    'page callback' => 'treemenu_add',
    'access arguments' => array('Admin Category add'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
$items['admin/category/edit'] = array(
    'title' => ' Edit Sections',
    'page callback' => 'treemenu_edit',
    'access arguments' => array('Admin Category edit'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
$items['admin/category/delete'] = array(
    'title' => 'Delete Sections',
    'page callback' => 'drupal_get_form',
	'page arguments' => array('menu_delete_confirm', 3),
    'access arguments' => array('Admin Category delete'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
  $items['admin/category/add'] = array(
    'title' => ' Admin Add Sections',
    'page callback' => 'treemenu_add',
    'access arguments' => array('Admin Category add'),
    'type' => MENU_CALLBACK,
    'file' => 'category.pages.inc',
  );
  
  
  return $items;
}


function category_cron() {

    global $gSitePath, $user, $gDocPath, $base_root, $base_path;

// section
   // $pundit = "SELECT * FROM {category} where parent_id='0'  ";
     $pundit = "SELECT * FROM {term_hierarchy} where parent='0'  ";

    $cat = ExecuteQuery($pundit, "select");
    db_query("TRUNCATE TABLE {pundit_section} ");
    foreach ($cat as $list) {

//        $query = "SELECT sum(score) as score,p.uid
//FROM {question_cat} AS q
//LEFT
//JOIN {pundit_scores} AS p ON p.qid = q.qid
//WHERE q.cat ='" . $list['cat_id'] . "' group by p.uid";

        $query = "SELECT sum(p.score) as score,p.uid
FROM {term_node} AS tn
LEFT
JOIN {pundit_scores} AS p ON p.qid = tn.nid
WHERE tn.tid ='" . $list['tid'] . "' group by p.uid";

        $pundit_final = ExecuteQuery($query, "select");
    
        foreach($pundit_final as $ins){
      
      if(!empty($ins['uid'])&&!empty($ins['score']))
    db_query("insert into {pundit_section} set cat_id='".$list['tid']."',uid='".$ins['uid']."',score='".$ins['score']."' ");
        
        }

    }

    //for subsection
     //$pundit = "SELECT * FROM {category} where parent_id>0 ";
    $pundit = "SELECT * FROM {term_hierarchy} where parent>0  ";

    $cat = ExecuteQuery($pundit, "select");

    foreach ($cat as $list) {

//    $query = "SELECT sum(score) as score,p.uid
//FROM {question_cat} AS q
//LEFT
//JOIN {pundit_scores} AS p ON p.qid = q.qid
//WHERE q.scat ='" . $list['cat_id'] . "' group by p.uid";

        $query = "SELECT sum(p.score) as score,p.uid
FROM {term_node} AS tn
LEFT
JOIN {pundit_scores} AS p ON p.qid = tn.nid
WHERE tn.tid ='" . $list['tid'] . "' group by p.uid";
        
        $pundit_final = ExecuteQuery($query, "select");

        foreach($pundit_final as $ins){

       if(!empty($ins['uid'])&&!empty($ins['score']))
    db_query("insert into {pundit_section} set cat_id='".$list['tid']."',uid='".$ins['uid']."',score='".$ins['score']."' ");

        }

    }
   
}