<?php

define('MICROSOFT_TRANSLATE_ADMIN', 'administer microsoft translation module');

function microsoft_translate_perm()
{
  return array(MICROSOFT_TRANSLATE_ADMIN);
}

function microsoft_translate_menu()
{
  $menu = array();

  $menu['admin/settings/mtranslate'] = array(
    'title' => t('Microsoft Translate'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('microsoft_translate_form'),
    'access arguments' => array(MICROSOFT_TRANSLATE_ADMIN),
    'type' => MENU_NORMAL_ITEM,
  );

  return $menu;
}

function microsoft_translate_form()
{
  $form = array();

  $form['microsoft_translate_clientid'] = array(
    '#type' => 'textfield',
    '#title' => 'Client ID',
    '#value' => variable_get('microsoft_translate_clientid', ''),
  );
  $form['microsoft_translate_clientsecret'] = array(
    '#type' => 'textfield',
    '#title' => 'Client ID',
    '#value' => variable_get('microsoft_translate_clientsecret', ''),
  );

  return system_settings_form($form);
}