<?php

function profiles_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':

      $blocks[6] = array(
        'info' => t('You are following'),
      );
      $blocks[7] = array(
        'info' => t('Following Counts'),
      );
      $blocks[8] = array(
        'info' => t('Issues Search Count'),
      );
      return $blocks;

    case 'view':
      switch ($delta) {

        case 6:
          $block['subject'] = t("You Are Following");
          $block['content'] = _following_list();
          break;
        case 7:
          $block['subject'] = t("Following Counts");
          $block['content'] = _following_counts();
          break;
        case 8:
          $block['subject'] = t("Issues Search Count");
          $block['content'] = hm_issues_search_count();
          break;
      }
      return $block;
  }
}

function hm_issues_search_count() {

  $count = t("<em>!search-count</em> issues ", array("!search-count" => variable_get("hm_search_results_count", "")));
  $output =
          '<div class="message right-message">
	  <p class="profile-status"><strong></strong></p>   
      <p class="profile-status">' . $count . '</p>   	  
	 </div>';
  return $output;
}




// profiles themes
function profiles_theme() {
  return array(

     'you_are_following' => array(
      'template' => 'you-are-following',
      'arguments' => array('relationships' => NULL, 'requestcount' => NULL),
    ),
    'following_counts' => array(
      'template' => 'following-counts',
      'arguments' => array('followingCount' => NULL, 'followersCount' => NULL),
    ),
  );
}


// user following list
function _following_list($uid = '') {
  //using user relation module api
  global $user;
  $path = '<front>';
  $sitelink = url($path, array('absolute' => TRUE)) . '/';
  $output = '';
  $i = 0;
  $more = '';

  drupal_add_css(drupal_get_path('module', 'user_search') . '/style/style.css');

  $uid = $uid != '' ? $uid : $user->uid;
  $relationships = user_relationships_load($param = array("approved" => 1, "requester_id" => $uid, 'rtid' => 1), $options = array('include_user_info' => 1, 'order' => 1, 'limit' => '10'), $reset = FALSE);
  $requestcount = count($relationships);

  $following = theme('you_are_following', $relationships, $requestcount);
  return $following;
}

// user following counts
function _following_counts() {
  global $user;
  $following = user_relationships_load($param = array("approved" => 1, "requester_id" => $user->uid, 'rtid' => 1), $options = array('include_user_info' => 1, 'order' => 1), $reset = FALSE);
  $followers = user_relationships_load($param = array("approved" => 1, "requestee_id" => $user->uid, 'rtid' => 1), $options = array('include_user_info' => 1, 'order' => 1), $reset = FALSE);
  $followingCount = count($following);
  $followersCount = count($followers);
  return theme('following_counts', $followingCount, $followersCount);
}