<?php
/**
 * Implementation of hook_perm().
 */
function moderator_perm() {
  return array('Moderate User','Moderate Question');
}


/**
 * Implementation of hook_menu().
 */
 
function moderator_menu() {	

$mdtrest['admin/moderateuser'] = array(
    'title' => 'Moderate User',
    'page callback' => 'moderate_user',
    'access arguments' => array('Moderate User'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'moderator.pages.inc',
  );

  $mdtrest['admin/moderatequestion'] = array(
    'title' => 'Moderate Question',
    'page callback' => 'moderate_quest',
    'access arguments' => array('Moderate Question'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'moderator.pages.inc',
  );

  return $mdtrest;
}

