<?php

/**
 * Implementation of hook_perm().
 */
function moderator_perm() {
    return array('Moderate User', 'Moderate Question', 'Edit Question', 'View Question');
}

/**
 * Implementation of hook_menu().
 */
function moderator_menu() {

    $mdtrest['admin/moderateuser'] = array(
        'title' => 'Moderate User',
        'page callback' => 'moderate_user',
        'access arguments' => array('Moderate User'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );

    $mdtrest['admin/moderatequestion'] = array(
        'title' => 'Moderate Question',
        'page callback' => 'moderate_quest',
        'access arguments' => array('Moderate Question'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['admin/notifymail'] = array(
        'title' => 'Moderate Question',
        'page callback' => 'moderate_user_mail',
        'access arguments' => array('Moderate User'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['admin/editquestions'] = array(
        'title' => 'Edit Question',
        'page callback' => 'edit_questions',
        'access arguments' => array('Edit Question'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['admin/viewquestion'] = array(
        'title' => 'View Question',
        'page callback' => 'view_questions',
        'access arguments' => array('View Question'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['moderator/issues'] = array(
        'title' => 'Moderator Issues',
        'page callback' => 'moderator_issues',
        'access arguments' => array('Moderate Question'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['moderator/issues/list/%'] = array(
        'title' => 'Moderator Issues',
        'page callback' => 'moderator_issues_list',
        'access arguments' => array('Moderate Question'),
        'page arguments' => array(3),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['moderator/issues/edit/%'] = array(
        'title' => 'Moderator Issues ',
        'page callback' => 'moderator_edit_issues',
        'access arguments' => array('Moderate Question'),
        'page arguments' => array(3),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    $mdtrest['moderator/ajax/%'] = array(
        'title' => 'Moderator ajax ',
        'page callback' => 'moderator_ajax',
        'access arguments' => array('Moderate Question'),
        'page arguments' => array(2),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'moderator.pages.inc',
    );
    return $mdtrest;
}

function moderator_issues() {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path;

    // drupal_set_html_head('<script src="http://ws.geonames.org/export/geonamesData.js" type="text/javascript"></script>');
    $inline = "      var admin='1';";

    drupal_add_js($inline, $type = 'inline');
    drupal_add_js(drupal_get_path('module', 'moderator') . '/scripts/moderator.js');
    drupal_add_js(drupal_get_path('module', 'question') . '/scripts/question.js');
    drupal_add_js(drupal_get_path('module', 'question') . '/scripts/qadmin.js');
    drupal_add_js(drupal_get_path('module', 'moderator') . '/scripts/jquery.multiSelect.js');
    drupal_add_css(drupal_get_path('module', 'moderator') . '/scripts/jquery.multiSelect.css');
    $output = _moderator_left();
    $output.=' <div class="mod-midside-inner">
            <div class="warning" >No Issue Selected !</div>
          <div class="clr"></div>
        </div>';
    return $output;
}

function _moderator_left() {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path;
    $output = '        <div class="commu">
          <div id="rotate">
            <ul id="maintabs" class="mytabs">
              <li class="current"><a href="' . $gSitePath . 'moderator/issues/list/new" title="Reporting"><span>News (59)</span></a></li>
              <li class="ui-tabs-selected"><a href="' . $gSitePath . 'moderator/issues/list/flag" title="Forum"><span>Flagged (14)</span></a></li>
                     </ul>

            <div id="tabcontent" class="mytabs-container" style="height:auto;" >
             
              <div class="clr"></div>
            </div>

          </div>


          <div class="mod-btn-outer">

          <div><input name="" type="button"  class="mod-btn" value="Ignore"/></div>
          <div><input name="" type="button"  class="mod-btn" value="Reject"/></div>
          <div class="clr"></div>
          </div>


        </div>';

    return $output;
}

function moderator_issues_list($type='') {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path;
    //This is numbers per page
    $num_per_page = 12;

    $output = '';
switch($type){
    case 'new':

            //actual query
    $query = "SELECT * from {question} as q  where new='0' ORDER BY q.qid DESC";
 $count = "SELECT count(*) from {question} as q  where new='0' ";
 $sqlcnt=db_result(db_query($count));
        break;
    case 'flag':
                    //actual query
    $query = "SELECT *,ifnull((select count(*) from {question_flags} where nodeid=q.qid AND type='question' group by nodeid),0) as fcnt  FROM {question_flags} as f  join {question} as q  on f.nodeid=q.qid where f.type='question' ORDER BY f.flag_date DESC";
  $count = "SELECT count(*) from {question_flags} as f  join {question} as q  on f.nodeid=q.qid  where f.type='question'  ";
 $sqlcnt=db_result(db_query($count));
        break;
    default:

    echo '<div class="warning">No Action(s) Found!</div>';exit;
        break;



}

    //pager_query function
    $rs = pager_query($query, $num_per_page);
    $alt = 'm-even';
    $output.= '  <div class="mod-leftside-inner">';
    if($sqlcnt){
    while ($data = db_fetch_object($rs)) {
       
        if($type=='flag')
         $flag= (''.$data->fcnt.'<img src="'.$gSitePath.path_to_theme().'/images/flag.png" align="absmiddle"/>');
         $chk=('<div align="right"><input type="checkbox" class="check-me" name="qids[]" value="' . $data->qid . '" />&nbsp; '.$flag.'</div> ');
        $nd = ('<div class="' . $alt . '" > ');
        $nd .= l($data->question, $gSitePath . 'moderator/issues/edit/' . $data->qid, array('attributes' => array('class' => 'issue-links')));
        $nd.=$chk;
        $nd .= ( '</div>');
        $output .= ( $nd);
        if ($alt == 'm-even')
            $alt = 'm-odd';
        else
            $alt='m-even';
    }
    $output .= theme('pager',array(), $num_per_page,0);
    }else{
       echo '<div class="warning">No Issue(s) Found!</div>';
    }
    $output.='  <div class="clr"></div></div>';
    echo $output;exit;
}

function moderator_edit_issues($qid='') {

    global $gSitePath, $user, $gDocPath, $base_root;

    if (!is_numeric($qid)) {
        return false;
    }



    $left_qry = "SELECT * FROM {question} as q left join {question_cat} as t on q.qid=t.qid where q.qid='" . $qid . "'";
    $result = db_query($left_qry);
    $quest = db_fetch_object($result);
    //country
    $result = db_query("select country from {question_location} where qid='$qid'}");
    $cont_array = array();
    while ($cont = db_fetch_array($result)) {
        array_push($cont_array, $cont['country']);
    }

    $result = geonames_query('countryinfo');
    $optionlist .= '<option value="">Select country</option>';
    foreach ($result->results as $country) {

        $set = '';
        if (in_array($country['countryname'], $cont_array)) {
            $set = 'SELECTED';
        }

        $optionlist .= sprintf('<option value="%s" %s>%s</option>', $country['countryname'], $set, $country['countryname']);
    }
    ///country ends state starts
    $result = db_query("select state from {question_location} where qid='$qid'}");
    $state_array = array();
    while ($cont = db_fetch_array($result)) {
        array_push($state_array, $cont['state']);
    }
    $setstate = implode(',', array_filter($state_array));
    $ret = '<select tabindex="18" multiple="multiple" style="width: 125px;"  onchange="get_city(this.value);" id="q_state" name="q_state[]"> <option value="">--States--</option>';
    $ret .= "</select>";

    /////////////state list end here //////////////////////////////
    /////////// city list start here/////////////////
    $result = db_query("select city from {question_location} where qid='$qid'}");
    $city_array = array();
    while ($cont = db_fetch_array($result)) {
        array_push($city_array, $cont['city']);
    }
    $setcity = implode(',', array_filter($city_array));

    $ret_city = '<select multiple="multiple" tabindex="19"   style="width: 125px;" id="q_city" name="q_city[]"> <option value="">--Cities--</option> ';
    $ret_city .= "<option value='-1'>Others</option>";
    $ret_city .= "</select>";
    //////////// city list end here //////////////
    ///////// Sub category values///////////////////////
   $qry_scat = "SELECT qc.scat from {question_cat} as qc where qc.qid='" . $qid . "' group by qc.scat";
    $result_scat = db_query($qry_scat);
    $scat = array();

    while ($quest_scat = db_fetch_object($result_scat)) {
              array_push($scat, $quest_scat->scat);
    }

  $escat1 = implode(",", array_filter($scat));
     ///////// Sub category values ends///////////////////////
      /////////load sub Sub category values///////////////////////
    $qry_sscat = "SELECT qc.sscat from {question_cat} as qc where qc.qid='" . $qid . "' group by qc.sscat";
    $result_sscat = db_query($qry_sscat);
    $sscat = array();

    while ($quest_sscat = db_fetch_object($result_sscat)) {
          array_push($sscat, $quest_sscat->sscat);
    }
    $esscat1 = implode(",", array_filter($sscat));
     ///////// load sub Sub category values ends///////////////////////

    $output .= '<script type="text/javascript">
                        var spath=\'' . $gSitePath . '\';
                    var setstate=\'' . $setstate . '\';
                        var setcity=\'' . $setcity . '\';
                            var setscat=\'' . $escat1 . '\';
                                var setsscat=\'' . $esscat1 . '\';
                            var admin=\'1\';
		</script>
			';

    $output .= '        
        <div id="err" class="clear"></div>
<div class="mod-t-outer" align="right">
           <b>* Required fields &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>
            <div class="clr"></div>
          </div>
				<form id="mod-question" name="mod-question" action="' . $gSitePath . 'moderator/ajax/saveissue" method="post"    >
                               <input type="hidden" name="qid" value="' . $qid . '"/>
<div class="mod-t-outer">
            <div class="mod-t1">Question<span title="This field is required." class="form-required">*</span></div>
            <div class="mod-t2">
               <input type="text" name="q_quest" class="mod-select" tabindex="1" id="q_quest" value="' . $quest->question . '" />
            </div>
            <div class="clr"></div>
          </div>
          <div class="mod-t-outer">
            <div class="mod-t1">Context</div>
            <div class="mod-t2">
             <textarea   tabindex="2" class="mod-select" name="q_context" id="q_context" >' . $quest->context . '</textarea>
            </div>
            <div class="clr"></div>
          </div>
            <div class="clr"></div>
            <div class="mod-t-outer">
            <div class="mod-t1">&nbsp;</div>
            <div class="mod-t5">
              &nbsp;
            </div>';
    $Spec_query = db_query("SELECT spec_name,spec_min_range,spec_max_range FROM political_spectrum");
    while ($Spec_result = db_fetch_object($Spec_query)) {
        $output .='<div class="mod-t6">' . $Spec_result->spec_name . '  </div>';
    }

    $output.='
            <div class="clr"></div>
          </div>
          <div class="clr"></div>
        <div class="clr"></div>

';


    $query = "SELECT * FROM {possible_answer} where qid='" . $qid . "' ";
    $ans = ExecuteQuery($query, "select");
    $i = 1;
    $tab = 3;
    $answer_count = 1;
    foreach ($ans as $array) {

        $output .= '<div class="mod-t-outer">
            <div class="mod-t1">Answer <b>*</b></div>
            <div class="mod-t5">
                  <input  tabindex="' . $tab++ . '" name="q_ans' . $i . '" type="text" id="q_ans' . $i . '" class="mod-select3" value="' . $array['answer'] . '" />&nbsp;<input type="hidden" name="aid' . $i . '" value="' . $array['paid'] . '">
                </div>
          ';
        $i++;
        /* META TAG OPTION GENERATION */

        $row_count = 1;
        $Spec_query1 = db_query("SELECT political_spec_id,spec_name,spec_min_range,spec_max_range FROM political_spectrum");
        $radio_output = '';
        while ($Spec_result1 = db_fetch_object($Spec_query1)) {
            $answer_id = $array['paid'];
            $option = '';
            $option.='<option  value="0">-</option>';
            for ($spec_count = $Spec_result1->spec_min_range; $spec_count <= $Spec_result1->spec_max_range; $spec_count++) {
                /* PRE SELECT OPTION VALUE */
                $fetch_exist = db_result(db_query("select value from {possible_answer_spectrum} where qid='$qid' and possible_ans_id='$answer_id' and
					political_spec_id='$Spec_result1->political_spec_id'"));
                /* PRE SELECT OPTION VALUE */

                $selected = '';
                if ($fetch_exist == $spec_count)
                    $selected = 'selected="selected"';

                $option.='<option ' . $selected . ' value=' . $spec_count . '>' . $spec_count . '</option>';
            }
            $radio_output .='  <div class="mod-t6"><select style="width:50px" name="sel_' . $answer_id . '_' . $Spec_result1->political_spec_id . '_' . $row_count . '" id="sel_' . $answer_id . '_' . $row_count . '">' . $option . '</select>    </div>';
            $row_count++;
        }
        $output .=$radio_output;
        /* META TAG OPTION GENERATION */
        $output.='            <div class="clr"></div>
          </div>
          <div class="clr"></div>';
    }
    $output.='';
    $output .= '<div class="mod-t-outer" id="add_more"></div><div align="center" id="del_ans" style="display:none;"><small><a href="javascript:void(0);" class="mod-t-outer"  tabindex="88" onclick="del_ans();">[Remove]</a></small><br/></div>
   

            <div class="clr"></div>
          <div class="mod-t-outer">
            <div class="mod-t1">&nbsp;</div>
            <div class="mod-t5">
              &nbsp;
            </div>
            <div class="mod-t5">
             <strong> Categories</strong>
            </div>
            <div class="mod-t5">
             &nbsp;
            </div>
            <div class="mod-t5">
            &nbsp;
            </div>
            <div class="clr"></div>
          </div>
          <div class="clr"></div>
';

    // $output .= $radio_output . '
    //	</table>
    //</td></tr>
    //<!--POSSIBLE META ANSWER-->';
    $output.='   <div class="mod-t-outer">
            <div class="mod-t1">&nbsp;</div>
            <div class="mod-t5">
        <input type="button" name="Add" class="mod-btn" tabindex="13" id="Add" onclick="add_ans();" value="Add Answer" /> <input type="hidden" name="ans_cnt" id="ans_cnt" value="' . count($ans) . '">
            </div>
            <div class="mod-t5">
  <select  tabindex="14" name="q_cat[]" id="q_cat" multiple="multiple"   class="mod-txtarea" onchange="get_subcat(\'q_cat\',\'chg_scat\',1,this.value);" >
        <option value="">Select Category</option>';
    $client_select = db_query("SELECT cat_id,cat_name FROM {category} where parent_id='0'");

    $qry_cat = "SELECT qc.cat from {question_cat} as qc where qc.qid='" . $qid . "' group by qc.cat";
    $result_cat = db_query($qry_cat);
    $cat = array();

    while ($quest_cat = db_fetch_object($result_cat)) {
        $cat[] = $quest_cat->cat;
    }
    $ecat1 = explode(",", $cat);
    while ($list = db_fetch_object($client_select)) {

        if (in_array($list->cat_id, $cat)) {
            $sel = 'SELECTED="SELECTED"';
        } else {
            $sel = '';
        }
        $output .= '<option value="' . $list->cat_id . '" ' . $sel . '>' . stripslashes($list->cat_name) . '</option>';
    }

    $output .= '</select>
         </div>        <input type="hidden" id="cat1" name="cat1" value="' . $ecat1 . '">&nbsp;
            <div class="mod-t5">

        <div id="chg_scat"><select class="mod-txtarea"  tabindex="15" name="q_scat[]" onchange="get_subcat(q_scat,\'chg_sscat\',2);" id="q_scat"   size="5">
        <option value="">Select Sub Category</option>';
    $output .= '</select></div></div>
   <div class="mod-t5"><input type="hidden"  id="cat2" name="cat2" value="' .$escat1. '">
   <div id="chg_sscat"><select class="mod-txtarea"  tabindex="16" name="q_sscat[]" onchange="get_subcat(q_sscat,\'chg_sscat\',3);" id="q_sscat"   size="5">
   <option value="">Select Sub Sub Category</option>';
    $output .= '</select></div> </div><input type="hidden"  id="cat3" name="cat3" value="' .$esscat1. '">
        <div class="clr"></div>
          </div>
               <div class="clr"></div>
          <div class="mod-t-outer">
            <div class="mod-t1">&nbsp;</div>
            <div class="mod-t5">
              &nbsp;
            </div>
            <div class="mod-t5">
             <strong> Location</strong>
            </div>
            <div class="mod-t5">
             &nbsp;
            </div>
            <div class="mod-t5">
            &nbsp;
            </div>
            <div class="clr"></div>
          </div>
                <div class="clr"></div>
	 <div class="mod-t-outer">
           <div class="mod-t1">&nbsp;</div>
            <div class="mod-t5">
    <input type="submit" name="update" class="mod-btn" tabindex="21" id="save" value="Update" />
      </div>
            <div class="mod-t5">
<select name="q_country[]"  style="width: 125px;" multiple="multiple" tabindex="17" onchange="get_state(this.value);" id="q_country">' . $optionlist . '</select>
    </div>
	 <div class="mod-t5"><div id="chg_state">' . $ret . '</div>  </div>
     <div class="mod-t5"><div id="chg_city">' . $ret_city . '</div> </div>
                  <div class="clr"></div>
          </div>
';
    $selmlist = "select * from qtag as a, tagging as b where a.qid='$qid' and a.tag_id=b.tid ";
    $mysqlfet = db_query($selmlist);


    //$output .= '<tr><td colspan="6">'.get_tagging_edit($qid).'</td></tr>';


    $output .= '</form>
          <div class="clr"></div></div>
        <div class="clr"></div>


';
    if (isAjax ())
        echo $output;
    else
        return $output;
}

//Moderator ajax works goes here

function moderator_ajax($action='') {

    global $gSitePath, $user, $gDocPath, $base_root;

    switch ($action) {
        case 'saveissue':

            $content = moderator_save_issue($_REQUEST);
            extract($content);
            break;
        case 'state':
            $explode = explode(',', $_REQUEST['ids']);
            $ret = '<select tabindex="18"  style="width: 125px;" multiple="multiple" id="q_state" name="q_state[]"> <option value="">--States--</option>';
            $results = array();
            if (count($explode) > 0) {
                foreach ($explode as $country) {

                    $geoid = db_result(db_query("SELECT geonameid FROM {geonames_countryinfo} where name LIKE '%" . $country . "%' limit 0,1"));

                    $query = array('geonameid' => $geoid);
                    $results = geonames_query('children', $query);
                    foreach ($results->results as $state) {
                        $set = '';
                        if (strpos(strtolower($setstate), strtolower($state['name']))) {
                            $set = 'SELECTED=SELECTED';
                        }
                        $ret .= sprintf('<option value="%s" %s >%s</option>', $state['geonameid'], $set, $state['name']);
                    }
                }

                $ret .= "</select>";
                $err = false;
                $msg = 'No action found!';
                $output = $ret;
            } else {
                $ret .= "</select>";
                $err = true;
                $msg = 'No State found!';
                $output = $ret;
            }
            break;
        case 'city':
            $explode = explode(',', $_REQUEST['ids']);
            $ret = '<select  tabindex="19"  style="width: 125px;"  id="q_city" name="q_city[]" > <option value="">--Cities--</option> ';
            $results = array();
            if (count($explode) > 0) {
                foreach ($explode as $code) {

                    $query = array('geonameid' => $code);
                    $result = geonames_query('children', $query);
                    foreach ($result->results as $state) {

                        $ret .= sprintf('<option value="%s">%s</option>', $state['geonameid'], $state['name']);
                    }
                }
                $ret .= "<option value='-1'>Others</option>";
                $ret .= "</select>";
                $err = false;
                $msg = 'No action found!';
                $output = $ret;
            } else {
                $ret .= "</select>";
                $err = true;
                $msg = 'No City found!';
                $output = $ret;
            }
            break;
        default:
            $err = true;
            $msg = 'No action found!';
            $output = '';
            break;
    }
    if (isAjax ())
        print json_encode(array('err' => $err, 'msg' => $msg, 'content' => $output));
    else
        return 'No Action Found!';
}

function moderator_save_issue($array) {

    global $gSitePath, $user, $gDocPath, $base_root;
    extract($array);
    $output = '';
    $nid = $qid;
    /* SAVING META INFORMATION */
    $query = "SELECT * FROM {possible_answer} where qid='" . $nid . "' ";
    $ans = ExecuteQuery($query, "select");
    $chk_exsit = db_result(db_query("select count(*) from {possible_answer_spectrum} where qid='$nid'"));
    if ($chk_exsit > 0) {
        $Spec_query2 = db_query("delete * from {possible_answer_spectrum} where qid='$nid'");
    }
    foreach ($ans as $ans_array) {
        $row_count = 1;
        $Spec_query2 = db_query("SELECT political_spec_id FROM {political_spectrum}");
        while ($Spec_result2 = db_fetch_object($Spec_query2)) {
            $radio_output = "sel_" . $ans_array['paid'] . "_" . $Spec_result2->political_spec_id . "_" . $row_count;
            $posted_rating = $array["$radio_output"];
            $ans_id = $ans_array['paid'];
            $political_id = $Spec_result2->political_spec_id;
            /* echo '<pre>';
              echo $posted_rating.'-';
              echo $Spec_result2->political_spec_id.'<br>'; */
            $insert_query = db_query("insert into possible_answer_spectrum set qid= '$nid' , possible_ans_id='$ans_id' , political_spec_id='$political_id',
				value='$posted_rating'");
            $row_count++;
        }
    }
    /* SAVING META INFORMATION */



    if (!empty($q_quest) && !empty($q_ans1) && !empty($q_ans2) && !empty($q_cat)) {


        $del_result = db_query("delete from {question_cat} where qid='" . $nid . "'");

        // add scrutineer badge
        $sql = "SELECT fid FROM {question_flags} WHERE nodeid = '$nid'";
        $flagids = ExecuteQuery($sql, "select");
        foreach ($flagids as $flagid) {
            $fids[] = $flagid['fid'];
        }
        update_flag_badges($fids);
///  category  starts & 1st level
        $fetch = array();
        if (!empty($q_cat)) {
            $cat1 = $q_cat;
            foreach ($cat1 as $ins1) {

                db_query("insert into {question_cat} set qid='$nid',uid='$user->uid',cat='$ins1'");
            }
        }

        /// category 2nd level
        if (!empty($q_scat)) {
            $cat2 = $q_scat;
            foreach ($cat2 as $ins2) {

                $fetch = load_parent_cat($ins2, 2);
                $chk_exsit = db_result(db_query("select count(*) from {question_cat} where qid='$nid' AND cat='" . $fetch[0]['lev1'] . "' AND scat='0' "));
                if ($chk_exsit > 0) {
                    db_query("update {question_cat} set scat='$ins2',uid='$user->uid' where qid='$nid' AND cat='" . $fetch[0]['lev1'] . "'");
                } else {
                    db_query("insert into {question_cat} set qid='$nid',uid='$user->uid',cat='" . $fetch[0]['lev1'] . "',scat='$ins2'");
                }
            }
        }
        ///category 3rd level
        if (!empty($q_sscat)) {
            $cat3 = $q_sscat;
            foreach ($cat3 as $ins3) {
                $fetch = load_parent_cat($ins3, 3);
                $chk_exsit = db_result(db_query("select count(*) from {question_cat} where qid='$nid' AND cat='" . $fetch[0]['lev1'] . "' AND scat='" . $fetch[0]['lev2'] . "' AND sscat='0'"));
                if ($chk_exsit > 0) {
                    db_query("update {question_cat} set sscat='$ins3',uid='$user->uid'  where qid='$nid' AND cat='" . $fetch[0]['lev1'] . "' AND scat='" . $fetch[0]['lev2'] . "'");
                } else {
                    db_query("insert into {question_cat} set qid='$nid',uid='$user->uid',cat='" . $fetch[0]['lev1'] . "',scat='" . $fetch[0]['lev2'] . "',sscat='$ins3'");
                }
            }
        }

        for ($i = 1; $i <= $ans_cnt; $i++) {
            $name = "q_ans" . $i;
            $aid = "aid" . $i;
            if (!empty($$name)) {

                if (!empty($$aid)) {
                    $result = db_query("UPDATE {possible_answer} set answer='%s' where paid='%d' AND qid='%d'", check_plain($$name), $$aid, $nid);
                } else {
                    // echo kkkkkkkkkk;
                    //	echo "INSERT INTO {possible_answer} (qid,answer) VALUES (%d,'%s')", $nid, $$name;
                    $result = db_query("INSERT INTO {possible_answer} (qid,answer) VALUES (%d,'%s')", $nid, check_plain($$name));
                }
            }
        }

        //multi location

        foreach ($q_country as $country) {

            db_query("insert into {question_location} set uid='%d',qid='%d',country='%s'", $user->uid, $qid, $country);
        }
        foreach ($q_state as $state) {

            db_query("insert into {question_location} set uid='%d',qid='%d',state='%s'", $user->uid, $qid, $state);
        }
        foreach ($q_city as $city) {

            db_query("insert into {question_location} set uid='%d',qid='%d',city='%s'", $user->uid, $qid, $city);
        }


        //location

        $output['msg'] = 'Thank you, Question updated successfully!';
        $output['err'] = false;

        //	print_r($result);
         question_edited_mail($nid);
        question_edited_mail_voters($nid);
        question_edited_mail_suggest($nid);
        //  drupal_goto("admin/moderatequestion");
    } else {


        $output['msg'] = 'Sorry, Some of the (*) required fields are Empty!';
        $output['err'] = true;
    }

    return $output;
}

//Badges call back
function update_flag_badges($fids) {
    foreach ($fids as $fid) {
        $sql = "SELECT uid,nodeid FROM (question_flags) WHERE fid = '$fid' AND type = 'question'";
        $users = ExecuteQuery($sql, 'select');

        foreach ($users as $user) {
            $uid = $user['uid'];
            $qid = $user['nodeid'];
            scrutineer($uid, $qid);
        }
    }
}