<?php

/**
 * @param array $codes1
 * @param array $codes2
 * @param array $codes3
 * @return array
 */
function tfl_list($codes1 = array(), $codes2 = array(), $codes3 = array(), $filter = false)
{
  $tfl = array(
    'list' => array(),
    'checked' => array(),
  );

  // countries
  $countries = location_get_iso3166_list();
  $tfl['list'][] = $countries;

  // countries checked
  $checked = array();
  foreach ($countries as $code => $name) {
    if (in_array($code, $codes1)) {
      $checked[] = $code;
    }
  }
  $tfl['checked'][] = $checked;

  // states/provinces
  $provinces = array();
  foreach ($checked as $code) {
    foreach (location_get_provinces($code) as $pcode => $pname) {
      $provinces[$code . '_' . $pcode] = $pname;
    }
  }
  $tfl['list'][] = $provinces;

  // states/provinces checked
  $checked = array();
  foreach ($provinces as $code => $name) {
    if (in_array($code, $codes2)) {
      $checked[] = $code;
    }
  }
  $tfl['checked'][] = $checked;

  // cities
  $cities = array();
  foreach ($checked as $code) {
    list($ccode, $pcode) = explode("_", $code, 2);
    foreach (location_get_cities($ccode, $pcode) as $citycode => $cityname) {
      $cities[$code.'_'.$citycode] = $cityname;
    }
  }
  $tfl['list'][] = $cities;

  // cities checked
  $checked = array();
  foreach ($cities as $code => $name) {
    if (in_array($code, $codes3)) {
      $checked[] = $code;
    }
  }
  $tfl['checked'][] = $checked;

  // setting
  $all = array_keys($countries);
  foreach ($countries as $code => $countryname) {
    foreach (location_get_provinces($code) as $pcode => $pname) {
      $id = $code . '_' . $pcode;
      $all[$code][$id] = array(
        'id' => $id,
        'name' => $pname,
      );
      foreach (location_get_cities($code, $pcode) as $citycode => $cityname) {
        $id = $code . '_' . $pcode . '_' . $citycode;
        $all[$code . '_' . $pcode][$id] = array(
          'id' => $id,
          'name' => $cityname,
        );
      }
    }
  }

  if ($filter) {
    static $codes = array();

    if (empty($codes)) {
      $result = db_query("SELECT DISTINCT(name) code FROM {location}");
      while ($code = db_result($result)) {
        $split = explode("_", $code);
        $tmp = $split[0];
        $codes[0][$tmp] = $tmp;
        for ($i=1;$i<=2;$i++) {
          if (isset($split[$i])) {
            $tmp .= '_'.$split[$i];
            $codes[$i][$tmp] = $tmp;
          }
        }
      }
      for ($i=0;$i<=2;$i++) {
        $codes[$i] = array_unique($codes[$i]);
      }
    }
    foreach ($tfl['list'] as $i => &$list) {
      $list = array_intersect_key($list, $codes[$i]);
    }
    $all = array_intersect_key($all, array_merge($codes[0], $codes[1]));
    for ($i=0; $i<=1; $i++) {
      foreach ($codes[$i] as $code) {
        $all[$code] = isset($all[$code]) ? array_intersect_key($all[$code], $codes[$i+1]) : array();
      }
    }
  }

  drupal_add_js(array('tfl' => $all), 'setting');

  return $tfl;
}