<?php
// $Id: openid_ax.module,v 1.4 2008/06/30 07:48:28 anshuprateek Exp $

/**
 * @file Openid Attribute Exchange implementation for drupal
 */

/**
 * Implementation ofhook_menu()
 */
function openid_ax_menu() {
  $items['openid/ax'] = array(
    'title' => 'Openid Attribute Exchange',
    'page callback' => 'openid_ax_endpoint',
    'type' => MENU_CALLBACK,
    'file' => 'openid_ax.pages.inc',
    'access callback' => TRUE
    );

  $items['openid/ax/continue'] = array(
    'title' => 'OpenID Attribute Exchange',
    'page callback' => 'openid_ax_continue',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'openid_ax.pages.inc'
    );

  $items['openid/ax/send'] = array(
    'title' => 'OpenID Attribute Exchange',
    'page callback' => 'openid_ax_send',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'openid_ax.pages.inc'
    );

  $items['user/%user/persona'] = array(
    'title' => 'OpenID AX Personas',
    'page callback' => 'openid_ax_persona',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'file' => 'openid_ax.pages.inc'
    );

  return $items;
}

/**
 * Implementation of hook_openid()
 */
function openid_ax_openid() {
  $request['openid.ns.ax'] = 'http://openid.net/srv/ax/1.0';
  $request['openid.ax.mode']='fetch_request';
  $request['openid.ax.type.fname'] = 'http://openid.net/schema/namePerson/first';
  $request['openid.ax.type.gender'] = 'http://openid.net/schema/gender';
  $request['openid.ax.required'] = 'fname,gender';
  return $request;

}

?>
