<?php

/**
 * @param $content_type
 * @param $content_id
 * @param $language_to
 */
function content_translate($content_type, $content_id, $language_to)
{
  switch ($content_type) {
    case 'node' :
      module_invoke_all("content_translate_node", node_load($content_id), $language_to);
      break;
    case 'comment' :
      module_invoke_all("content_translate_comment", _comment_load($content_id), $language_to);
      break;
  }
}

/**
 * @param $string
 * @return string
 */
function content_translate_detect_language($string)
{
  // TODO Language detection
  global $user;
  return $user->language;
}


/**
 * Implementation of hook_nodeapi()
 */
function content_translate_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  switch ($op) {
    case 'delete' :
      db_query("DELETE FROM {content_translate} WHERE content_type = '%s' AND content_id = '%d'", 'node', $node->nid);
    break;
  }
}

/**
 * @param $content_type
 * @param $content_id
 * @param $field
 * @param $text
 * @param int $field_order
 */
function content_translate_add($content_type, $content_id, $field, $text, $field_order = 0) {
  db_query("
    REPLACE INTO {content_translate}
    SET
      content_type = '%s',
      content_id = '%d',
      field = '%s',
      field_order = '%d',
      text = '%s',
      date_added = '%s'
      ",
      $content_type, $content_id, $field, $field_order, $text, date('Y-m-d H:i:s')
    );
}