<?php

/**
 * Implementation of hook_nodeapi()
 *
 * Invokes   hook_pollfix($nid, $map)
 * $nid - Poll node id
 * $map - Map of changed poll chorders
 */
function pollfix_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  if ($node->type == 'poll' && $op == 'presave') {
    $map = array();
    $count = (int)db_result(db_query('SELECT COUNT(*) FROM {poll_choices} WHERE nid = %d', $node->nid));
    $count2 = count($node->choice);
    $skip = 0;
    for ($i = 0; $i < $count2; $i++) {
      if (empty($node->choice[$i]['chtext'])) {
        if ($i < $count) {
          $map[$i] = array('status' => 'deleted');
        }
        $skip++;
      } elseif ($skip != 0) {
        if ($i < $count) {
          $map[$i] = array('status' => 'updated', 'index' => $i - $skip);
        } else {
          $map[$i] = array('status' => 'inserted', 'index' => $i - $skip);
        }
      }
    }
//    drupal_set_message(json_encode($map));
    module_invoke_all('pollfix', $node->nid, $map);
  }
}