<?php

/**
 * Implementation of hook_nodeapi()
 *
 * Invokes   hook_pollfix($nid, $map)
 * $nid - Poll node id
 * $map - Map of changed poll chorders
 */
function pollfix_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  if ($node->type == 'poll' && $op == 'presave') {
    $map = array();
    $count = (int)db_result(db_query('SELECT COUNT(*) FROM {poll_choices} WHERE nid = %d', $node->nid));
    $skip = 0;
    for ($i = 0; $i < $count; $i++) {
      if (empty($node->choice[$i]['chtext'])) {
        $skip++;
      } elseif ($skip != 0) {
        $map[$i] = $i - $skip;
      }
    }
    module_invoke_all('pollfix', $node->nid, $map);
  }
}