<?php


function location_cities_list_xk_32 () {
	return array (
	);
}


function location_cities_list_xk_10 () {
	return array (
	);
}


function location_cities_list_xk_01 () {
	return array (
		"791580" => t("Decan"),
	);
}


function location_cities_list_xk_02 () {
	return array (
		"791122" => t("Dragash"),
	);
}


function location_cities_list_xk_07 () {
	return array (
		"790701" => t("Glogovac"),
	);
}


function location_cities_list_xk_03 () {
	return array (
		"784759" => t("Ferizaj"),
	);
}


function location_cities_list_xk_05 () {
	return array (
		"791646" => t("Gjakove"),
	);
}


function location_cities_list_xk_06 () {
	return array (
		"790674" => t("Gjilan"),
	);
}


function location_cities_list_xk_31 () {
	return array (
	);
}


function location_cities_list_xk_08 () {
	return array (
		"789996" => t("Istok"),
	);
}


function location_cities_list_xk_33 () {
	return array (
	);
}


function location_cities_list_xk_09 () {
	return array (
	);
}


function location_cities_list_xk_11 () {
	return array (
	);
}


function location_cities_list_xk_34 () {
	return array (
	);
}


function location_cities_list_xk_12 () {
	return array (
		"788731" => t("Leposaviq"),
	);
}


function location_cities_list_xk_14 () {
	return array (
		"788470" => t("Llazice"),
	);
}


function location_cities_list_xk_35 () {
	return array (
	);
}


function location_cities_list_xk_15 () {
	return array (
		"789225" => t("Mitrovice"),
	);
}


function location_cities_list_xk_17 () {
	return array (
	);
}


function location_cities_list_xk_36 () {
	return array (
	);
}


function location_cities_list_xk_18 () {
	return array (
		"787157" => t("Peje"),
	);
}


function location_cities_list_xk_20 () {
	return array (
		"786714" => t("Pristina"),
	);
}


function location_cities_list_xk_37 () {
	return array (
	);
}


function location_cities_list_xk_24 () {
	return array (
		"785485" => t("Shtime"),
	);
}


function location_cities_list_xk_25 () {
	return array (
	);
}


function location_cities_list_xk_26 () {
	return array (
		"785238" => t("Suva Reka"),
	);
}


function location_cities_list_xk_27 () {
	return array (
		"784372" => t("Vitina"),
	);
}


function location_cities_list_xk_29 () {
	return array (
	);
}


function location_cities_list_xk_04 () {
	return array (
		"789228" => t("Kosovo Polje"),
	);
}


function location_cities_list_xk_13 () {
	return array (
	);
}


function location_cities_list_xk_16 () {
	return array (
	);
}


function location_cities_list_xk_30 () {
	return array (
		"783770" => t("Zvecan"),
	);
}


function location_cities_list_xk_23 () {
	return array (
	);
}


function location_cities_list_xk_22 () {
	return array (
		"787456" => t("Orahovac"),
	);
}


function location_cities_list_xk_19 () {
	return array (
		"786950" => t("Podujeva"),
	);
}


function location_cities_list_xk_21 () {
	return array (
		"786712" => t("Prizren"),
	);
}


function location_cities_list_xk_28 () {
	return array (
		"784097" => t("Vushtrri"),
	);
}
