<?php


function location_cities_list_ws_aa () {
	return array (
	);
}


function location_cities_list_ws_al () {
	return array (
	);
}


function location_cities_list_ws_at () {
	return array (
	);
}


function location_cities_list_ws_fa () {
	return array (
	);
}


function location_cities_list_ws_gi () {
	return array (
	);
}


function location_cities_list_ws_ge () {
	return array (
	);
}


function location_cities_list_ws_pa () {
	return array (
	);
}


function location_cities_list_ws_sa () {
	return array (
	);
}


function location_cities_list_ws_tu () {
	return array (
		"4035413" => t("Apia"),
	);
}


function location_cities_list_ws_vs () {
	return array (
	);
}


function location_cities_list_ws_vf () {
	return array (
	);
}
