<?php


function location_cities_list_ee_37 () {
	return array (
		"588409" => t("Tallinn"),
		"590447" => t("Maardu"),
	);
}


function location_cities_list_ee_39 () {
	return array (
	);
}


function location_cities_list_ee_44 () {
	return array (
		"588686" => t("Sillamae"),
		"590031" => t("Narva"),
		"591260" => t("Kohtla-Jarve"),
	);
}


function location_cities_list_ee_51 () {
	return array (
	);
}


function location_cities_list_ee_49 () {
	return array (
	);
}


function location_cities_list_ee_57 () {
	return array (
	);
}


function location_cities_list_ee_59 () {
	return array (
		"589165" => t("Rakvere"),
	);
}


function location_cities_list_ee_67 () {
	return array (
		"589580" => t("Parnu"),
	);
}


function location_cities_list_ee_65 () {
	return array (
	);
}


function location_cities_list_ee_70 () {
	return array (
	);
}


function location_cities_list_ee_74 () {
	return array (
	);
}


function location_cities_list_ee_78 () {
	return array (
		"588335" => t("Tartu"),
	);
}


function location_cities_list_ee_82 () {
	return array (
	);
}


function location_cities_list_ee_84 () {
	return array (
		"587577" => t("Viljandi"),
	);
}


function location_cities_list_ee_86 () {
	return array (
	);
}
