<?php

/**
 * Implementation of hook_perm().
 */
function debate_perm() {
    return array('Debate List', 'Debate Save', 'Admin Debate', 'Resource Debate');
}

/**
 * Implementation of hook_menu().
 */
function debate_menu() {
    $items['issues/debate/%/%'] = array(
        'title' => ' Debate',
        'page callback' => 'debate_list',
        'access arguments' => array('Debate List'),
        'type' => MENU_SUGGESTED_ITEM,
        'page arguments' => array(2, 3),
        'file' => 'debate.pages.inc',
    );
    $items['debate/resource/new/%'] = array(
        'title' => 'Debate Resources',
        'page callback' => 'add_resources',
        'access arguments' => array('Resource Debate'),
        'page arguments' => array(3),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',);

    $items['resource/debate/%/%'] = array(
        'title' => 'Resource Debate',
        'page callback' => 'resdebate_list',
        'access arguments' => array('Resource Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'page arguments' => array(2, 3),
        'file' => 'debate.pages.inc',
    );
     $items['issues/resource/%/%'] = array(
        'title' => 'Resource Debate List',
        'page callback' => 'resource_list',
        'access arguments' => array('Resource Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'page arguments' => array(2, 3),
        'file' => 'debate.pages.inc',
    );
    $items['issues/debate/save'] = array(
        'title' => 'Debate',
        'page callback' => 'debate_submit',
        'access arguments' => array('Debate Save'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );
    $items['admin/debate'] = array(
        'title' => 'Admin Debate',
        'page callback' => 'admin_debate',
        'access arguments' => array('Admin Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );

    $items['admin/debate/edit'] = array(
        'title' => 'Admin Edit Debate',
        'page callback' => 'admin_debate_edit',
        'access arguments' => array('Admin Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );
    $items['admin/wavelets'] = array(
        'title' => 'Admin Debate Wavelets',
        'page callback' => 'admin_debate_wlets',
        'access arguments' => array('Admin Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );

    $items['admin/wavelets/edit'] = array(
        'title' => 'Admin Forum Wavelets',
        'page callback' => 'admin_wlets_edit',
        'access arguments' => array('Admin Debate'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );
    $items['debate/ajax'] = array(
        'title' => 'Admin Forum Wavelets',
        'page callback' => 'debate_ajax',
        'access arguments' => array('Debate List'),
        'type' => MENU_SUGGESTED_ITEM,
        'file' => 'debate.pages.inc',
    );
    return $items;
}

function debate_init() {
    drupal_add_js(drupal_get_path('module', 'debate') . '/scripts/debate.js');
}

function send_forumnotify($nid='', $qid='') {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path;

    $insert_notify = db_query("insert into notification (uid,follower_action,is_wave,node_id) values('" . $user->uid . "','1','1','" . $nid . "' ) ");

    hm_mails($qid, $nid, 'add_forum');
}

function list_debate($qid='', $type='') {
    global $gSitePath, $user, $gDocPath, $base_root;

    $wave = '';
    $click = '';
    $query = "select f.*,DATE_FORMAT(f.date_added, '%a %M %Y %h:%i %p') as date_added,IFNULL((select DATE_FORMAT(date_added, '%a %M %Y %h:%i %p') from {debate_reply} as wl where wl.did=f.did ORDER BY wl.rid ASC LIMIT 0,1),0) as rdate,IFNULL((select count(*) from {user_likes} as l where l.node_id=f.did AND is_debate='1' AND is_agree='1' group by l.node_id),0) as cntagree,IFNULL((select count(*) from {user_likes} as l where l.node_id=f.did AND is_debate='1' AND is_agree='0' group by l.node_id),0) as cntdisagree from {debate} as f join {user_profile} as u on u.uid=f.uid where f.qid_rid='$qid' AND type='$type' AND status='1' ORDER BY did DESC ";

    $cnt = ExecuteQuery($query, "select");

    $i = 0;
    if (!empty($cnt)) {


        foreach ($cnt as $forum) {
            $bg = $i % 2;
            if ($bg)
                $setbg = 'back-col';
            else
                $setbg='';
            $i++;
            $account = user_load($forum['uid']);

                $query="select * from {debate_options} a,{possible_answer} b where a.paid=b.paid AND a.did='".$forum['did']."'";
                 $strnth = ExecuteQuery($query, "select");
                   $strength='';
                 foreach($strnth as $list){
                     $ans=$list['answer'];
                   
                    switch($list['ans_val']){
                        case 0:
                            $strength.='<div class="bottpart">
                                <div class="green"><em>&nbsp;&nbsp;+</em></div>
                                <div class="green-box">'.$ans.'</div>
                                     <div class="clr"></div>
                                     </div>';
                            break;
                        case 1:
                            $strength.='<div class="bottpart">
                                <div class="green"><em>&nbsp;&nbsp;+</em></div>
                                <div class="green-box">'.$ans.'</div>
                                     <div class="clr"></div>
                                     </div>';
                            break;
                        case 2:
                                $strength.='<div class="bottpart">
                                <div class="pink"><em>&nbsp;&nbsp;-</em></div>
                                <div class="pink-box">'.$ans.'</div>
                                     <div class="clr"></div>
                                     </div>';
                            break;
                    }
                     
                 }

            if ($type == 1) {

                $wave.='         <div class="debate-summary-wrapper" >
                    	<div class="deb-center">
                                  <div class="leftpartside">
                                     <div class="toppart"><p>' . $forum['cntagree'] . '</p>

                                    <p align="center"><img src="' . $gSitePath . drupal_get_path('theme', 'newtheme') . '/images/aggree-hand.jpg" width="18" height="15" alt="Agree" /></p></div>
                                     <div class="toppart2"><p>' . $forum['cntdisagree'] . '</p>
                                      <p align="center"><img src="' . $gSitePath . drupal_get_path('theme', 'newtheme') . '/images/disaggree-hand.jpg" width="18" height="15" alt="Agree" /></p>

                                     </div>

                                  </div>


                                    <div class="centerpartside-out">
                                    	<div class="centerpartside-top">
                                           <div class="centerpartside">
                                           <h4><a class="debate-links" href="' . $gSitePath . 'issues/debate/' . $qid . '/' . $forum['did'] . '" >' . myTruncate($forum['title'], '30', '', '..') . '</a></h4><br>
                                           ' . myTruncate($forum['content'], '25', '', '..') . '
                                               </div>
                                               <div class="rightpartside">
                                            <a  rel=\'' . $bubble . '\' href="' . $gSitePath . 'profile/' . $account->name . '">' . UserPicture_small($account->uid) . '</a></div>

                                        </div>
                                         <div class="clr"></div>

                                        	<div class="centerpartside-bottom">
                                                    ' . $strength . '

                                            	<ul>


                                                	<li>Posted : ' . $forum['date_added'] . ' </li>
                                                    <div class="clr"></div>
                                                    <li>Last Activity: ' . $forum['rdate'] . '</li>


                                                </ul>


                                            </div>


                                    <div class="clr"></div>

                                    </div>

                                </div>
                                	<div class="deb-bott">
                                    </div>
 <div class="clr"></div>

                        </div>

                        <div class="clr"></div>
';
            } else {

                $click = 'rwavelet(' . $qid . ',' . $forum['did'] . ')';


                $wave .= '
	<div class="post-title back-col">
<div class="leftsideimg">' . UserPicture_small($account->uid) . '</div>

<div class="rightside">
<h4><a href="javascript:void(0);" onclick="' . $click . '">' . myTruncate($forum['title'], '30', '', '..') . '</a></h4><br>

<p> ' . myTruncate($forum['content'], '25', '', '..') . '</p><br>

<div class="likelink-outer">
           <div class="likekink">
              <ul>
               <li><a href="#"><b>' . $forum['cntpost'] . ' Comments</b></a></li>
               <li>|</li>
               <li><a href="#">' . $forum['cntlike'] . ' likes</a></li>


               </ul>


           </div>
          <div class="date">' . $forum['date_added'] . '</div>

        <div class="clr"></div>
        </div>


</div>

<div class="clr"></div>
</div>
<div class="bott-bord"></div>	';
            }
        }
    } else {

        $wave .= '
	<div class="post-title">

	<b>No Waves Posted Yet!!</b>
		</div>


	';
    }

    return $wave;
}


function debate_roundup($did=''){
 global $gSitePath, $user, $gDocPath, $base_root;
//main debate
   $query = "SELECT IFNULL((select count(*) from {user_likes} as l where l.node_id=f.did AND is_debate='1' AND is_agree='1' group by l.node_id),0) as cntagree,IFNULL((select count(*) from {user_likes} as l where l.node_id=f.did AND is_debate='1' AND is_agree='0' group by l.node_id),0) as cntdisagree  FROM {debate} as f  join {user_profile} as u on u.uid=f.uid   where f.did='$did'";    $main = ExecuteQuery($query, "select");
//sub debate
$query="SELECT IFNULL( (

SELECT count( * )
FROM {user_likes} AS l
WHERE l.node_id = f.rid
AND is_debate_reply = '1'
AND is_agree = '1'
GROUP BY l.node_id ) , 0
) AS cntagree, IFNULL( (

SELECT count( * )
FROM {user_likes} AS l
WHERE l.node_id = f.rid
AND is_debate_reply = '1'
AND is_agree = '0'
GROUP BY l.node_id ) , 0
) AS cntdisagree,f.str_wk
FROM {debate_reply} AS f
JOIN user_profile AS u ON u.uid = f.uid
WHERE f.did = '$did'";
 $sub = ExecuteQuery($query, "select");

 foreach($sub as $list){
    $list['str_wk'];
    $str_wk=($list['str_wk']==0)?'-1':'1';
     $agree=$agree+$list['cntagree'];
     $dagree=$dagree+$list['cntdisagree'];
     $strength=$list['cntagree']-$list['cntdisagree'];
     $activity=$list['cntagree']+$list['cntdisagree'];

     $rollup=$strength*$str_wk;

     //Activity
     $sum_act=$sum_act+$activity;
     //For Rollup Strenght
    $sum_rollup=$sum_rollup+$rollup;
 }
    $agree=$main['0']['cntagree']+$agree;
    $dagree=$main['0']['cntdisagree']+$dagree;
    $sum_act=$agree+$dagree;
    $sum_rollup=$main['0']['cntagree']+$sum_rollup;
    $query = "update {debate} set agree='$agree',disagree='$dagree',activity='$sum_act',strength='$sum_rollup' where did='$did'";
    $main = ExecuteQuery($query, "select");
 

}


function resource_roundup($rid=''){
 global $gSitePath, $user, $gDocPath, $base_root;
//main debate
   $query = "SELECT IFNULL((select count(*) from {user_likes} as l where l.node_id=f.rid AND is_resource='1' AND is_agree='1' group by l.node_id),0) as cntagree,IFNULL((select count(*) from {user_likes} as l where l.node_id=f.rid AND is_debate='1' AND is_agree='0' group by l.node_id),0) as cntdisagree  FROM {resource} as f  join {user_profile} as u on u.uid=f.uid   where f.rid='$rid'";
   $main = ExecuteQuery($query, "select");
//sub debate
$query="SELECT IFNULL( (

SELECT count( * )
FROM {user_likes} AS l
WHERE l.node_id = f.reid
AND is_resource_reply = '1'
AND is_agree = '1'
GROUP BY l.node_id ) , 0
) AS cntagree, IFNULL( (

SELECT count( * )
FROM {user_likes} AS l
WHERE l.node_id = f.reid
AND is_resource_reply = '1'
AND is_agree = '0'
GROUP BY l.node_id ) , 0
) AS cntdisagree,f.str_wk
FROM {resource_reply} AS f
JOIN user_profile AS u ON u.uid = f.uid
WHERE f.rid = '$rid'";
 $sub = ExecuteQuery($query, "select");

 foreach($sub as $list){
    $list['str_wk'];
    $str_wk=($list['str_wk']==0)?'-1':'1';
     $agree=$agree+$list['cntagree'];
     $dagree=$dagree+$list['cntdisagree'];
     $strength=$list['cntagree']-$list['cntdisagree'];
     $activity=$list['cntagree']+$list['cntdisagree'];

     $rollup=$strength*$str_wk;

     //Activity
     $sum_act=$sum_act+$activity;
     //For Rollup Strenght
    $sum_rollup=$sum_rollup+$rollup;
 }
    $agree=$main['0']['cntagree']+$agree;
    $dagree=$main['0']['cntdisagree']+$dagree;
    $sum_act=$agree+$dagree;
    $sum_rollup=$main['0']['cntagree']+$sum_rollup;
    $query = "update {resource} set agree='$agree',disagree='$dagree',activity='$sum_act',strength='$sum_rollup' where rid='$rid'";
    $main = ExecuteQuery($query, "select");


}
