<?php

/**
 * Implementation of hook_perm().
 */
function invite_perm() {
    return array('Invite Friends', 'Twitter Login');
}

/**
 * Implementation of hook_menu().
 */
function invite_menu() {

    $items['invite/invite_friends'] = array(
        'title' => ' Invite Friends',
        'page callback' => 'invite_friends',
        'access arguments' => array('Invite Friends'),
        'type' => MENU_CALLBACK,
        'file' => 'invite.pages.inc',
    );
    $items['twitter/post'] = array(
        'title' => ' Twitter ',
        'page callback' => 'twitter_login',
        'access arguments' => array('Twitter Login'),
        'type' => MENU_CALLBACK,
        'file' => 'invite.pages.inc',
    );

    $items['twitterpost'] = array(
        'title' => ' Twitter ',
        'page callback' => 'twitterpost_save',
        'access arguments' => array('Twitter Login'),
        'type' => MENU_CALLBACK,
        'file' => 'invite.pages.inc',
    );
    $items['invite/sendmail'] = array(
        'title' => 'sendmail',
        'page callback' => 'invite_cron',
        'access arguments' => array('Twitter Login'),
        'type' => MENU_CALLBACK,
        'file' => 'invite.pages.inc',
    );


    return $items;
}

function htmlmail($to, $subject, $message, $from='', $headers = NULL) {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path;
    $from = variable_get('site_mail');

    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','$to','" . $subject . "','" . $message . "',0,now())";
    db_query($ins_qry);
    return true;
}

function htmlmail_function($to, $subject, $message, $headers = NULL) {
 global $gSitePath, $user, $gDocPath, $base_root, $base_path,$base_url, $theme_path, $theme, $conf;
    
   
    $from = variable_get('site_mail');
// To send HTML mail, the Content-type header must be set
    $path =$base_url.'/'.drupal_get_path('theme', 'newtheme');

    $newmessage = '';

    // To send HTML mail, the Content-type header must be set
    $headers = 'MIME-Version: 1.0' . "\r\n";
    $headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
    $headers .= 'From: ' . $conf['site_name'] . ' <' . $conf['site_mail'] . '>' . "\r\n";

    $newmessage .= '
			   <html>
				<head>
				 <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				 <title>' . $conf['site_name'] . '</title>
				 <style type="text/css">
				  <!--
				   *{ margin:0px; padding:0px;}
					body{ margin:0px; padding:0px;font:normal 12px Arial, Helvetica, sans-serif;}
					img{ border:none; outline:none;}
					a{ color:#000; text-decoration:none;}
					a:hover{ text-decoration:underline;}
					.clr{ clear:both;}

					#email-main{ width:622px; margin:0 auto; min-height:200px; height:auto !important; height:200px; border:2px #8f8c8c solid;}
					#email-main #header{ background:#8f8c8c; padding:7px 0px; padding-left:10px;}
					#email-main #header .email-logo{ background:url('.$path . '/images/email-logo.jpg) no-repeat; width:229px; height:27px;}
					#email-main #content{ margin:0px; padding:10px;}
					#email-main #content h1{ font:normal 22px Arial, Helvetica, sans-serif; color:#000; text-decoration:none;}
					#email-main #content h1 a{ font:normal 22px Arial, Helvetica, sans-serif; color:#000; text-decoration:none;}
					#email-main #content h1 a:hover{ font:normal 22px Arial, Helvetica, sans-serif; color:#000; text-decoration: underline;}
					#email-main #content h3{ font:normal 16px Arial, Helvetica, sans-serif; color:#666; text-decoration: underline;}
					#email-main #content p{ font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;}
					#email-main #content p strong{ font:normal 12px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;}
					#email-main #content h2 { font:bold 13px Arial, Helvetica, sans-serif; color:#000; padding-bottom:10px; text-decoration:none;}
					#email-main #content h2 a{ font:bold 13px Arial, Helvetica, sans-serif; color:#000; padding-bottom:10px; text-decoration:underline;}
					#email-main #content h2 a:hover{ text-decoration:none;}
					a{ color:#000; text-decoration:underline; font:bold 12px Arial, Helvetica, sans-serif; color: #960;}
					a:hover{ text-decoration:none;}
					#email-main #content b{ font:normal 11px Arial, Helvetica, sans-serif; color:#666666;}
					#email-main #content .avatar-intro{ width:290px; min-height:100px; height: auto !important; height:100px; padding:10px; background:#fafafa; border:1px #ccc solid; margin-top:10px; margin-bottom:10px;}
					#email-main #content .avatar-intro ul{ padding:10px;}
					#email-main #content .avatar-intro ul li{ float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000; padding:5px 10px; border-right:1px #ccc solid;}
					#email-main #content .avatar-intro ul .border-none{ border:none;}
					#email-main #content .avatar-intro ul li strong{ont:bold 12px Verdana, Geneva, sans-serif; color:#999;}
					#email-main #content .avatar-intro ul li a{ float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000;}
					#email-main #content .avatar-intro ul li a:hover{ float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000; text-decoration:underline;}
					#email-main #content .avatar-intro-left{ float:left; width:70px;}
					#email-main #content .avatar-intro-right{ float:left; width:200px;}
					#email-main #content .avatar-box{ width:590px; background:#f0f0f0; padding:7px; margin-top:10px; border-bottom:1px #999 dotted; border-top:1px #999 dotted; margin-bottom:5px;}
					#email-main #content .avatar-box .avatar-box-left{ float:left; width:70px;}
					#email-main #content .avatar-box .avatar-box-left img{ border:1px #ccc solid;}
					#email-main #content .avatar-box .avatar-box-right{ float:left; width:478px; padding-left:10px;}
					.email-btn{ background:url(' . $path . '/images/email-btn-bg.jpg) repeat-x; padding:4px 10px; border:none; cursor:pointer; font:normal 17px Arial, Helvetica, sans-serif; color:#fff; text-decoration:none;}
					.email-btn:hover{ background:url(' . $path . '/images/email-btn-bg-h.jpg) repeat-x; padding:4px 10px; border:none; cursor:pointer; font:normal 17px Arial, Helvetica, sans-serif; color:#fff; text-decoration:none;}
				  -->
				 </style>
				</head>
				<body>
				<div id="email-main">
				 <div id="header">
				  <div class="email-logo"></div>
				  <div class="clr"></div>
				 </div>
				<div class="clr"></div>
				<div id="content">';
    $newmessage .= $message;
    $newmessage .='<div class="clr"></div><div align="left">
              Visit our website <a title="Heardmentality.org" href="'.$base_url.'" target="_blank">Heardmentality.com</a> <br />
              <br />Thanks, <br />Heardmentality Team. </div>
							 <div align="center"><a href="' . $base_url . '"><input name="" type="button" value="View All Updates" class="email-btn"/></a></div>
							 <div class="clr"></div>
							 </div>
							</div>
							</body>
						   </html>';
   // echo $newmessage;
   

    return mail($to, $subject, $newmessage, $headers);
}

function hm_mails($qid, $nid, $type) {
    global $gSitePath, $user, $gDocPath, $base_root;

    $qdetails = load_question($qid);
    $mail_row = db_query("select mail from users where uid='" . $user->uid . "'");
    $fet_mail = db_fetch_object($mail_row);

    $sel_follow = "select f.*,u.mail,u.notify_etype,u.name from follower as f join users as u on f.uid=u.uid where f.follower_id='" . $user->uid . "' and follower_id!=0 and cat_id=0 and question_id=0";

    $get_follow = db_query($sel_follow);
    $from = variable_get('site_mail');


    switch ($type) {
        case vote_answer:

            while ($fet_follow = db_fetch_object($get_follow)) {
                if ($fet_follow->notify_etype == 1) {

                    $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='5'";
                    $rs_mgmt = db_query($sel_user_cmt);
                    $list_content = db_fetch_object($rs_mgmt);
                    $subject_proj = $list_content->subject;
                    $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                    $contentm = str_replace("#anothername#", $user->name, $contentm);

                    $contentm = str_replace("#question#", rtrim($qdetails['question'], '?') . '?', $contentm);
                    $contentm = str_replace("#link#", $gSitePath . $qdetails['url'], $contentm);
                    $contentm = str_replace("#content#", 'voted for the below question. Kindly have a review', $contentm);

                    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','" . $fet_follow->mail . "','" . $subject_proj . "','" . $contentm . "',0,now())";
                    db_query($ins_qry);
                }
            }
            break;
        case add_question:

            while ($fet_follow = db_fetch_object($get_follow)) {
                if ($fet_follow->notify_etype == 1) {

                    //id=4 for add question
                    $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='4'";
                    $rs_mgmt = db_query($sel_user_cmt);
                    $list_content = db_fetch_object($rs_mgmt);
                    $subject_proj = $list_content->subject;
                    $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                    $contentm = str_replace("#anothername#", $user->name, $contentm);

                    $contentm = str_replace("#question#", rtrim($qdetails['question'], '?') . '?', $contentm);
                    $contentm = str_replace("#link#", $gSitePath . $qdetails['url'], $contentm);
                    $contentm = str_replace("#content#", 'post a question', $contentm);


                    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','" . $fet_follow->mail . "','" . $subject_proj . "','" . $contentm . "',0,now())";
                    db_query($ins_qry);
                }
            }
            break;
        case add_like:

            $sel_forum = "select * from forum_wavelets where wlid='" . $nid . "'";
            $forum_fet = db_query($sel_forum);
            $forum_row = db_fetch_object($forum_fet);
            $wavelet = $forum_row->wavelet;

            while ($fet_follow = db_fetch_object($get_follow)) {
                if ($fet_follow->notify_etype == 1) {
                    //id=4 for add question
                    $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='5'";
                    $rs_mgmt = db_query($sel_user_cmt);
                    $list_content = db_fetch_object($rs_mgmt);
                    $subject_proj = $list_content->subject;
                    $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                    $contentm = str_replace("#anothername#", $user->name, $contentm);

                    $contentm = str_replace("#question#", $wavelet, $contentm);
                    //$contentm = str_replace("#link#", $wavelet, $contentm);
                    $contentm = str_replace("#content#", 'like new forum', $contentm);


                    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','" . $fet_follow->mail . "','" . $subject_proj . "','" . $contentm . "',0,now())";
                    db_query($ins_qry);
                }
            }
            break;
        case add_forum:

            $sel_wave = db_fetch_object(db_query("select * from {forum_wave} where fid='$nid'"));


            while ($fet_follow = db_fetch_object($get_follow)) {
                if ($fet_follow->notify_etype == 1) {
                    //id=4 for add question
                    $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='5'";
                    $rs_mgmt = db_query($sel_user_cmt);
                    $list_content = db_fetch_object($rs_mgmt);
                    $subject_proj = $list_content->subject;
                    $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                    $contentm = str_replace("#anothername#", $user->name, $contentm);

                    $contentm = str_replace("#question#", $wavelet, $contentm);
                    $contentm = str_replace("#link#", $gSitePath . $qdetails['url'], $contentm);
                    $contentm = str_replace("#content#", "created a Forum Topic [" . $sel_wave->title . "] for the below question. Kindly have a review", $contentm);


                    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','" . $fet_follow->mail . "','" . $subject_proj . "','" . $contentm . "',0,now())";
                    db_query($ins_qry);
                }
            }
            break;
        case reply_forum:

            $sel_wave = db_fetch_object(db_query("select * from {forum_wave} where fid='$nid'"));

            $qdetails = load_question($sel_wave->qid_rid);
            $sel_wavelet = db_fetch_object(db_query("select * from {forum_wavelets} where wlid='$nid' AND uid='$user->uid'"));
            $mail_row = db_query("select mail from users where uid='" . $user->uid . "'");
            $fet_mail = db_fetch_object($mail_row);

            $sel_follow = "select f.*,u.mail,u.notify_etype,u.name from follower as f join users as u on f.uid=u.uid where f.follower_id='" . $user->uid . "' and follower_id!=0 and cat_id=0 and question_id=0";

            $get_follow = db_query($sel_follow);
            while ($fet_follow = db_fetch_object($get_follow)) {
                if ($fet_follow->notify_etype == 1) {
                    //id=4 for add question
                    $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='5'";
                    $rs_mgmt = db_query($sel_user_cmt);
                    $list_content = db_fetch_object($rs_mgmt);
                    $subject_proj = $list_content->subject;
                    $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                    $contentm = str_replace("#anothername#", $user->name, $contentm);

                    $contentm = str_replace("#question#", $wavelet, $contentm);
                    $contentm = str_replace("#link#", $gSitePath . $qdetails['url'], $contentm);
                    $contentm = str_replace("#content#", "posted a reply[" . $sel_wavelet->wavelet . "] under Forum Topic [" . $sel_wave->title . "] for the below question. Kindly have a review", $contentm);


                    $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date)values('$from','$from','" . $fet_follow->mail . "','" . $subject_proj . "','" . $contentm . "',0,now())";
                    db_query($ins_qry);
                }
            }
            break;


        case user_badges:
            $sel_wave = db_fetch_object(db_query("select * from {user_badges} where badge='$nid' AND uid='$user->uid'"));
            //$sel_wavelet = db_fetch_object(db_query("select * from {forum_wavelets} where wlid='$nid' AND uid='$user->uid'"));
            $mail_row = db_query("select mail from users where uid='" . $user->uid . "'");
            $fet_mail = db_fetch_object($mail_row);

            $sel_follow = "select f.*,u.mail,u.notify_etype,u.name from follower as f join users as u on f.uid=u.uid where f.follower_id='" . $user->uid . "' and follower_id!=0 and cat_id=0 and question_id=0";

            $get_follow = db_query($sel_follow);
            while ($fet_follow = db_fetch_object($get_follow)) {

                $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='5'";
                $rs_mgmt = db_query($sel_user_cmt);
                $list_content = db_fetch_object($rs_mgmt);
                $subject_proj = $list_content->subject;
                $contentm = str_replace("#uname#", $fet_follow->name, $list_content->content);
                $contentm = str_replace("#anothername#", $user->name, $contentm);
                $contentm = str_replace("#content#", "earn " . $sel_wave->bid . " badges ", $contentm);
                $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,notify,posted_date)values('$from','$from','" . $user_namelistfs[0]['mail'] . "','" . $subject_proj . "','" . $contentm . "',0,0,now())";

                db_query($ins_qry);
            }
            break;

        case follower:
            $sel_ulists = "SELECT * FROM users LEFT JOIN user_profile ON users.uid=user_profile.uid Where users.uid='" . $nid . "'";

            $user_namelistfs = ExecuteQuery($sel_ulists, "select");
            $sel_user_cmt = "SELECT * FROM notification_mail_format Where id='1'";
            $rs_mgmt = db_query($sel_user_cmt);
            $list_content = db_fetch_object($rs_mgmt);
            $subject_proj = $list_content->subject;
            $contentm = str_replace("#uname#", $user_namelistfs[0]['name'], $list_content->content);
            $contentm = str_replace("#anothername#", $user->name, $contentm);
            //echo $contentm;die;
            $ins_qry = "insert into hm_mails(from_mail_id,user_from_id,user_to_id,subject,content,mail_status,notify,posted_date)values('$from','$from','" . $user_namelistfs[0]['mail'] . "','" . $subject_proj . "','" . $contentm . "',0,0,now())";
            db_query($ins_qry);

            //$mail_success = htmlmail_function($user_namelistfs[0]['mail'], $subject, $contentm, '');
            break;
    }
}

function invite_cron() {
    global $gSitePath, $user, $gDocPath, $base_root;
    $send_qry = "select * from {hm_mails} where mail_status='0'";
    $send_exec = ExecuteQuery($send_qry, "select");

    foreach ($send_exec as $sendeach) {

        $mail_success = htmlmail_function($sendeach['user_to_id'], $sendeach['subject'], $sendeach['content'], '');
        if ($mail_success) {
            db_query("update hm_mails set mail_status=1 where mail_id='" . $sendeach['mail_id'] . "'");
        }
    }
}

