<?php

/**
 * Implementation of hook_nodeapi()
 */
function poll_ext_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  if ($node->type == 'poll') {
    switch ($op) {
      case 'delete' :
        db_query("DELETE FROM {poll_votes_history} WHERE nid = '%d'", $node->nid);
        db_query("DELETE FROM {poll_choices_short} WHERE nid = '%d'", $node->nid);
        break;
      case 'load' :
        poll_ext_chtext_short($node);
        break;
    }
  }
}

/**
 * Implementation of hook_user()
 */
function poll_ext_user($op, &$edit, &$account, $category = NULL)
{
  if ($op == 'delete') {
    db_query("DELETE FROM {poll_votes_history} WHERE uid = '%d'", $account->uid);
  }
}

/**
 * Load the short chtext
 *
 * @param $poll Node object of type 'poll'
 */
function poll_ext_chtext_short(&$poll)
{
  $result = db_query("SELECT pc.chorder, IFNULL(pch.chtext, pc.chtext) AS chtext_short FROM {poll_choices} pc LEFT JOIN {poll_choices_short} pch ON pc.nid = pch.nid AND pc.chorder = pch.chorder WHERE pc.nid = '%d'", $poll->nid);
  while ($choice = db_fetch_array($result)) {
    $poll->choice[$choice['chorder']]['chtext_short'] = $choice['chtext_short'];
  }
}

/**
 * Set the short chtext
 *
 * @param $nid
 * @param $chorder
 * @param $chtext_short
 */
function poll_ext_chtext_short_set($nid, $chorder, $chtext_short)
{
  db_query("INSERT INTO {poll_choices_short} (nid, chorder, chtext) VALUES ('%d', '%d', '%s') ON DUPLICATE KEY UPDATE chtext = '%s'", $nid, $chorder, $chtext_short, $chtext_short);
}

/**
 * Implementation of hook_pollfix()
 *
 * @param $nid
 * @param $map
 */
function poll_ext_pollfix($nid, $map)
{
  foreach ($map as $key => $data) {
    switch ($data['status']) {
      case 'deleted' :
        db_query("DELETE FROM {poll_choices_short} WHERE nid = '%d' AND chorder = '%d'", $nid, $key);
      break;
      case 'updated' :
        db_query("UPDATE {poll_choices_short} SET chorder = '%d' WHERE nid = '%d' AND chorder = '%d'", $map['index'], $nid, $key);
      break;
    }
  }
}