<?php

/**
 * This function is a wrapper for the t-function
 *
 * @param        $code
 * @param        $string
 * @param array  $args
 * @param null   $langcode
 * @param string $textgroup
 *
 * @see t()
 * @see format_plural()
 *
 */
function __($code, $string, $args = array(), $langcode = NULL, $textgroup = 'default') {
  // detect language
  if (is_null($langcode)) {
    global $language;
    $langcode = $language->language;
  }

  // check if this text allows plurality (has @count arg)
  if (isset($args['@count'])) {
    $count = $args['@count'];
    unset($args['@count']);
    $index = (function_exists('locale_get_plural')) ? locale_get_plural($count, $langcode) : -1;
    $args['@count[' . $index . ']'] = $count;
    return __($code, strtr($string, array('@count' => '@count[' . $index . ']')), $args, $langcode, $textgroup);
  }

  // location
  $location = '';

  // check if there is a special function that handles translation
//  $function = '__t_' . $textgroup;
//  if (function_exists($function)) {
//    return $function($code, $string, $location);
//  }


  // create record in the database if not exists
  tt_src_set($code, $string, $textgroup, $location);

  //
  return __t($code, $string, $args, $langcode);
}




define('TT_SRC_LID', 'tt_src_lid');

/**
 * @param bool   $code
 * @param string $string
 * @param bool   $reset
 *
 * @return int
 */
function tt_src_lid($code = FALSE, $string = '', $reset = FALSE) {
  static $lids = NULL;

  if (is_null($lids) || $reset) {
    if ($reset) {
      $lids_tmp = array();

      $results = db_query("SELECT lid, source, code FROM {locales_source} WHERE code <> ''");
      while ($row = db_fetch_object($results)) {
        $lids_tmp[$row->code][md5($row->source)] = $row->lid;
      }

      variable_set(TT_SRC_LID, $lids_tmp);
    }

    $lids = variable_get(TT_SRC_LID, array());
  }

  if (FALSE === $code) {
    return $lids;
  }

  return isset($lids[$code][md5($string)]) ? $lids[$code][md5($string)] : 0;
}

/**
 * @param        $code
 * @param        $string
 * @param string $textgroup
 * @param string $location
 */
function tt_src_set($code, $string, $textgroup = 'default', $location = '') {
  static $i, $mtime = NULL;
  if (is_null($mtime)) $mtime = microtime(true);
  if ($i++ > 1000) {
    Kint::trace();
    dd(round($mtime - microtime(true), 4));
  }
  else {
    echo $i  . ' - ' . $string . ' - ' . round(microtime(true) - $mtime, 4), "<br>";
  }

  // check if exists in cache
  if ($lid = tt_src_lid($code, $string)) {
    return $lid;
  }

  // check if exists in db
  if ($lid = db_result(db_query("SELECT lid FROM {locales_source} WHERE source = '%s' AND code = '%s'", $string, $code))) {
    // __locale(NULL, NULL, NULL, TRUE);
  }
  else {
    // create
    $object = array(
      'code'      => $code,
      'source'    => $string,
      'textgroup' => $textgroup,
      'location'  => $location,
      'version'   => VERSION,
    );
    drupal_write_record('locales_source', $object);

    // rebuild cache
    // tt_src_lid(FALSE, '', TRUE);
  }
}

/**
 *
 */
define('TT_PREFIX', 'tt');

/**
 * Analogue of t-function that can translate textgroup != 'default'
 *
 * @param       $code
 * @param       $string
 * @param array $args
 * @param null  $langcode
 *
 * @return null|string
 */
function __t($code, $string, $args = array(), $langcode = NULL) {
  // detect language
  if (is_null($langcode)) {
    global $language;
    $langcode = $language->language;
  }

  //
  if ($langcode != 'en') {
    $string = __locale($code, $string, $langcode, FALSE);
  }

  //
  if (empty($args)) {
    return $string;
  }
  else {
    // Transform arguments before inserting them.
    foreach ($args as $key => $value) {
      switch ($key[0]) {
        case '@':
          // Escaped only.
          $args[$key] = check_plain($value);
          break;

        case '%':
        default:
          // Escaped and placeholder.
          $args[$key] = theme('placeholder', $value);
          break;

        case '!':
          // Pass-through.
      }
    }
    return strtr($string, $args);
  }
}

/**
 * Analogue of locale-function that can translate textgroup != 'default'
 *
 * @param      $code
 * @param null $string
 * @param null $langcode
 * @param bool $reset
 *
 * @return null
 */
function __locale($code, $string = NULL, $langcode = NULL, $reset = FALSE) {
  // detect language
  if (is_null($langcode)) {
    global $language;
    $langcode = $language->language;
  }

  //
  $cache_id = TT_PREFIX . '_locale:' . $langcode;
  $semaphore_id = TT_PREFIX . '_locale_' . $langcode;

  //
  static $locale_t;

  // Reset in-memory cache.
  if ($reset) {
    $locale_t = NULL;
    cache_clear_all(TT_PREFIX . '_locale:*', 'cache', TRUE);
  }

  // Return all cached strings if no string was specified
  if (!isset($string)) {
    return $locale_t;
  }

  //
  if (!isset($locale_t[$langcode])) {
    $locale_t[$langcode] = array();

    //
    if ($cache = cache_get($cache_id, 'cache')) {
      $locale_t[$langcode] = $cache->data;
    }

    //
    elseif (lock_acquire($semaphore_id)) {
      $result = db_query("
        SELECT s.source, t.translation, t.language, s.code
        FROM {locales_source} s
        LEFT JOIN {locales_target} t ON s.lid = t.lid AND t.language = '%s'
        WHERE s.version = '%s' AND s.code <> ''", $langcode, VERSION);
      while ($data = db_fetch_object($result)) {
        $locale_t[$langcode][$data->code][md5($data->source)] = (empty($data->translation) ? TRUE : $data->translation);
      }
      cache_set($cache_id, $locale_t[$langcode]);
      lock_release($semaphore_id);
    }
  }

  return ($locale_t[$langcode][$code][md5($string)] === TRUE ? $string : $locale_t[$langcode][$code][md5($string)]);
}

/**
 *
 */
function tt_enable () {
  // terms
  db_query("DELETE FROM {locales_source} WHERE textgroup = '%s'", 'term');
  db_query("
    INSERT INTO {locales_source}
    SELECT NULL, '', 'term', name, '%s', CONCAT('term-', tid)
    FROM {term_data}", VERSION);

  // locations
  db_query("DELETE FROM {locales_source} WHERE textgroup = '%s'", 'location');
  if (module_exists('extract')) {
    extract_cache_location();
    db_query("
      INSERT INTO {locales_source}
      SELECT
        NULL,
        '',
        'location',
        (CASE
          WHEN location3_name <> '' THEN location3_name
          WHEN location2_name <> '' THEN location2_name
          ELSE location1_name
          END),
        '%s',
        CONCAT('location-', location_id)
      FROM {extract_cache_location}", VERSION);
  }
}

/**
 *
 */
function tt_flush_caches () {
  __locale(NULL, NULL, NULL, TRUE);
  return array();
}

/**
 *
 */
function tt_init() {
  // if (isset($_REQUEST['translate'])) tt_enable();
//  if () {
//
//  }

}
