<?php

/**
 * Implementation of hook_perm().
 * @return array
 */
function hmnewsletter_perm() {
    return array('Send Newsletters');
}

/**
 * Implementation of hook_menu().
 */
function hmnewsletter_menu() {
    $items['hmnewsletter'] = array(
        'title' => 'HMNewsLetter',
        'page callback' => 'send_newsletter',
        'access arguments' => array('Send Newsletters'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
 * To get the follower and followers.
 */
function getFollowers($follwerQ='', $subject='') {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;

    $path = drupal_get_path('theme', $theme);

//    if (findtask() <= 3) {
//        $follwerQ = db_query("
//								SELECT f.`uid`, f.`follower_id` FROM {follower} AS f
//								INNER JOIN {users} AS u ON u.uid = f.uid
//								WHERE u.`notify_etype` = 2
//								ORDER BY f.`uid`
//						");
//    } else {
//        $follwerQ = db_query("
//								SELECT f.`uid`, f.`follower_id` FROM {follower} AS f
//								INNER JOIN {users} AS u ON u.uid = f.uid
//								WHERE u.`notify_etype` = 1
//								ORDER BY f.`uid`
//						");
//    }

    $follwers = array();
    $allfollwers = array();
    while ($follwer = db_fetch_array($follwerQ)) {
        if (!in_array($follwer['uid'], $follwers[$follwer['follower_id']]) && $follwer['uid'] != $follwer['follower_id']) {
            $follwers[$follwer['uid']][] = $follwer['follower_id'];
        }

        if (!in_array($follwer['uid'], $allfollwers)) {
            $allfollwers[] = $follwer['follower_id'];
        }
    }


//      echo '<pre>';
//       print_r($follwerQ);
//      print_r($follwers);
//      print_r($allfollwers);
//      print_r($allfollwers);
//      print_r($follower_activites);	exit;
//
//    if (findtask() <= 3) {
//        $subject = $conf['site_name'] . ': Monthly update';
//    } else {
//        $subject = $conf['site_name'] . ': Weekly update';
//    }

    $follower_activites = getfolloweractivites(array_filter(array_unique($allfollwers)));

    foreach ($follwers as $key => $value) {
        $receiver_id = '';
        $mailcontent = '';
        foreach ($value as $val) {
            $follower_details = load_user($val);
            if (!empty($follower_details)) {
                $receiver_id = $key;
                $mailcontent .= '
									<div class="avatar-box" style="width:590px; background:#f0f0f0; padding:7px; margin-top:10px; border-bottom:1px #999 dotted; border-top:1px #999 dotted; margin-bottom:5px;">
										<div class="avatar-box-left" style="float:left; width:70px;"><a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '/profile/' . $follower_details->name . '">';
                $mailcontent .= UserPicture($follower_details->uid);

                $mailcontent .= '
											</a><p align="center" style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">' . $follower_details->real_name . '</p>
										</div>                    
										<div class="avatar-box-right" style="float:left; width:478px; padding-left:10px;">';
                if (!empty($follower_activites[$val])) {
                    $mailcontent .= preparemailcontent($follower_activites[$val], $receiver_id);
                } else {
                    $mailcontent .= '<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">No activities are found!!</p>';
                }
                $mailcontent .= '
										</div> 
										<div class="clr" style="clear:both;"></div>
									</div>
								';
            }
        }

        //Save mails
        if ($receiver_id != '') {
            $receiver = load_user($receiver_id);
            echo $mail = preparemail($mailcontent, $receiver);
//			echo "
//					INSERT INTO {hm_mails}
//					(`from_mail_id`, `user_from_id`, `user_to_id`, `subject`, `content`, `posted_date`, `mail_type`)
//						VALUES('".$conf['site_mail']."', '".$conf['site_mail']."', '$receiver->mail', '$subject', '$mail', now(), 'html')
//					";

            if (!empty($receiver->mail)) {
                db_query("INSERT INTO {hm_mails} (`from_mail_id`, `user_from_id`, `user_to_id`, `subject`, `content`, `posted_date`, `mail_type`) VALUES('%s', '%s', '%s', '%s', '%s', now(), '%s')", $conf['site_mail'], $conf['site_mail'], $receiver->mail, $subject, $mail, '2');
            }
        }
    }exit;
    return '';
}

function getfollowers_weekly() {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;
//generate the user which are subscribed weekly 
//   $query = db_query("
//								SELECT f.`uid`, f.`follower_id` FROM {follower} AS f
//								INNER JOIN {users} AS u ON u.uid = f.uid
//								WHERE u.`notify_etype` = 1
//								ORDER BY f.`uid`
//						");
    // If the current user is fan, following, ..., has a one way relation
    // to the other user, or if he has a two way relation to the user ...
    // fetch them
    $query = db_query("SELECT DISTINCT u.uid,ur.requestee_id as follower_id FROM {user_relationships} ur INNER JOIN {users} AS u ON u.uid = ur.requester_id
    WHERE u.`notify_etype` = 1");

    $subject = $conf['site_name'] . ': Weekly update';
    return getFollowers($query, $subject);
}

function getfollowers_monthly() {

    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;
    if (findtask() <= 3) {
//        $query = db_query("
//								SELECT f.`uid`, f.`follower_id` FROM {follower} AS f
//								INNER JOIN {users} AS u ON u.uid = f.uid
//								WHERE u.`notify_etype` = 2
//								ORDER BY f.`uid`
//						");
        $query = db_query("SELECT DISTINCT u.uid,ur.requestee_id as follower_id FROM {user_relationships} ur INNER JOIN {users} AS u ON u.uid = ur.requester_id
    WHERE u.`notify_etype` = 2");
        $subject = $conf['site_name'] . ': Monthly update';
        return getFollowers($query, $subject);
    }
}

/*
  To get users who followa none and send the questions
 */

function getnonfollowers() {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $theme_path, $theme, $conf;

    $path = drupal_get_path('theme', $theme);
    if (findtask() <= 3) {
        $nonfollwerQ = db_query("
								SELECT DISTINCT u.`uid` FROM {users} AS u
								LEFT JOIN {follower} AS f ON u.uid = f.uid
								WHERE f.uid IS NULL AND u.notify_etype = 2
						");
    } else {
        $nonfollwerQ = db_query("
								SELECT DISTINCT u.`uid` FROM {users} AS u
								LEFT JOIN {follower} AS f ON u.uid = f.uid
								WHERE f.uid IS NULL AND u.notify_etype = 1
						");
    }

    $nonfollwers = array();
    while ($nonfollwer = db_fetch_array($nonfollwerQ)) {
        $nonfollwers[] = $nonfollwer['uid'];
    }

    if (findtask() <= 3) {
        $subject = $conf['site_name'] . ': Monthly update';
    } else {
        $subject = $conf['site_name'] . ': Weekly update';
    }

    $nonfollower_question = getnonfollowerquestion();

    foreach ($nonfollwers as $key => $value) {
        $receiver_id = $value;
        $mailcontent = '';
        $nonfollower_details = load_user($value);
        $mailcontent .= '
							<div class="avatar-box">
								<div class="avatar-box-left"><a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"     href="' . $base_url . '/profile/' . $nonfollower_details->name . '">';
        $mailcontent .= UserPicture($nonfollower_details->uid);

        $mailcontent .= '
									</a><p align="center">' . $nonfollower_details->real_name . '</p>
								</div>                    
								<div class="avatar-box-right">';
        $mailcontent .= $nonfollower_question;
        $mailcontent .= '
								</div> 
								<div class="clr" style="clear:both;"></div>
							</div>
						';

        //Save mails
        if ($receiver_id != '') {
            $receiver = load_user($receiver_id);
             $mail = preparemail($mailcontent, $receiver, 'nonfollower');
            if (!empty($receiver->mail)) {
//                echo "
//					INSERT INTO {hm_mails}
//					(`from_mail_id`, `user_from_id`, `user_to_id`, `subject`, `content`, `posted_date`, `mail_type`)
//						VALUES('".$conf['site_mail']."', '".$conf['site_mail']."', '$receiver->mail', '$subject', '$mail', now(), 'html')
//					";
               db_query("INSERT INTO {hm_mails} (`from_mail_id`, `user_from_id`, `user_to_id`, `subject`, `content`, `posted_date`, `mail_type`) VALUES('%s', '%s', '%s', '%s', '%s', now(), '%s')", $conf['site_mail'], $conf['site_mail'], $receiver->mail, $subject, $mail, '2');
            }
        }
    }
    return '';
}

/*
  Question content for non followers
 */

function getnonfollowerquestion() {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;
    $mailcontent = '';
    $questionsQ = db_query("
							SELECT `question`, `url` FROM {question} 
							WHERE `status` = '1'
							ORDER BY active_rate LIMIT 0, 5
						");
    while ($question = db_fetch_array($questionsQ)) {
        $mailcontent .= '<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;"><a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '/' . $question['url'] . '">' . $question['question'] . '</a></p>';
    }
    return $mailcontent;
}

/*
  Prepare mail
 */

function preparemail($mailcontent, $receiver, $task = 'follower') {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;

    $path = drupal_get_path('theme', $theme);

    $mail = '';


    $mail .= ' <p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">Hi ' . $receiver->real_name . '!</p>';

    $mess = '';
    if (findtask() <= 3) {
        $month_dates = week_date_month(strtotime(date('d-m-Y')));
        $start_date = strtotime($month_dates[0]);
        if ($task == 'nonfollower') {
            $mess = 'Here is your montly summary of recent quiestions from <a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '">' . $conf['site_name'] . '</a>';
        } else {
            $mess = 'Here is your montly summary of Followers activity from <a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '">' . $conf['site_name'] . '</a>';
        }
    } else {
        $month_dates = week_date(strtotime(date('d-m-Y')));
        $start_date = strtotime($month_dates[0]);
        if ($task == 'nonfollower') {
            $mess = 'Here is your weekly summary of recent quiestions from <a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '">' . $conf['site_name'] . '</a>';
        } else {
            $mess = 'Here is your weekly summary of Followers activity from <a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '">' . $conf['site_name'] . '</a>';
        }
    }

    $mail .= '<h1 style="font:normal 22px Arial, Helvetica, sans-serif; color:#000; text-decoration:none;">Network Updates, ' . date('M d', $start_date) . ' - ' . date('M d') . '</h1> <br /><div class="clr" style="clear:both;"></div><h3 style="font:normal 16px Arial, Helvetica, sans-serif; color:#666; text-decoration: underline;">' . $mess . '</h3>';

    $tweets = db_result(db_query("SELECT count(distinct `nid`) AS 'tweets' FROM node WHERE `uid` = $receiver->uid AND type='poll'"));

    //$following = db_result(db_query("SELECT count(distinct `uid`) AS 'following' FROM follower WHERE `follower_id` = $receiver->uid"));
    $following = count(_activity_heartbeat_related_uid_info($receiver->uid));
    //$followers = db_result(db_query("SELECT count(distinct `follower_id`) AS 'followers' FROM follower WHERE `uid` = $receiver->uid"));
    $followers = db_result(db_query("SELECT COUNT(*)  from user_relationships  where requestee_id='" . $receiver->uid . "' AND requester_id>0  "));

    $mail .= '
								<div class="avatar-intro" style="width:290px; min-height:100px; height: auto !important; height:100px; padding:10px; background:#fafafa; border:1px #ccc solid; margin-top:10px; margin-bottom:10px;">
								 <div class="avatar-intro-left" style="float:left; width:70px;">';
    $mail .= UserPicture($receiver->uid);
    $mail .= '
								</div>
								 <div class="avatar-intro-right" style="float:left; width:200px;">
								  <h2>' . $receiver->real_name . '</h2>
								  <p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;"><a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '/profile/' . $receiver->name . '">Profile</a></p>
								  <b style="font:normal 11px Arial, Helvetica, sans-serif; color:#666666;">' . $receiver->bio . '</b>
								 </div>
								 <div class="clr" style="clear:both;"></div>
								 <div>
								  <ul style="padding:10px;">
								   <li style="float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000; padding:5px 10px; border-right:1px #ccc solid;">' . number_format($tweets) . '<br /><strong style="font:bold 12px Verdana, Geneva, sans-serif; color:#999;">Post</strong></li>
								   <li style="float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000; padding:5px 10px; border-right:1px #ccc solid;">' . number_format($following) . '<br /><strong style="font:bold 12px Verdana, Geneva, sans-serif; color:#999;">Following</strong></li>
								   <li style="float:left; list-style:none; font:bold 12px Verdana, Geneva, sans-serif; color:#000; padding:5px 10px;">' . number_format($followers) . '<br /><strong style="font:bold 12px Verdana, Geneva, sans-serif; color:#999;">Followers</strong></li>
								  </ul>
								 </div>
								 <div class="clr" style="clear:both;"></div>
								</div>
				';
    $mail .= $mailcontent;

    return $mail;
}

/*
  Prepare mail content
 */

function preparemailcontent($follower_activites, $receiver_id) {
    global $gSitePath, $user, $gDocPath, $base_root, $base_path, $base_url, $theme_path, $theme, $conf;

    $path = drupal_get_path('theme', $theme);
//print_r($follower_activites);
    $uid_details = load_user($follower_activites[0]['uid']);


    $mail.=t('<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;"><a href="' . $base_path . 'profile/' . $uid_details->name . '" title="' . $uid_details->name . '">' . $uid_details->name . '</a></p>');
    foreach ($follower_activites as $activites) {
        $data = unserialize($activites['variables']);
        switch ($activites['message_id']) {
            CASE 'user_follow':
                $uid_target_details = load_user($data['target_id']);
                $mail .= '
					<h2 style="font:bold 13px Arial, Helvetica, sans-serif; color:#000; padding-bottom:10px; text-decoration:none;"><a style="{color:#000; text-decoration:none;}:hover{text-decoration:underline}"    href="' . $base_url . '/profile/' . $uid_details->name . '">' . $uid_details->real_name . '</a> is following
						<a style="{ font:bold 13px Arial, Helvetica, sans-serif; color:#000; padding-bottom:10px; text-decoration:underline;}:hover{text-decoration:none}"    href="' . $base_url . '/profile/' . $uid_target_details->name . '">';
                $mail .= UserPicture_small($data['target_id']);
                $mail .= '	</a>
					</h2>
					<b style="font:normal 11px Arial, Helvetica, sans-serif; color:#666666;">' . hmnews_ago($activites['timestamp']) . '.</b>
				';
                break;

            CASE 'add_question':

            CASE 'add_vote':
                $mail .= '<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">' . t($activites['message']) . '&nbsp;' . l($data['q_title'], drupal_get_path_alias('node/' . $data['qid'])) . '</p><b>' . hmnews_ago($activites['timestamp']) . '.</b>';
                break;
                        CASE 'debate_reply':
            CASE 'add_debate':
            CASE 'deb_agree':
            CASE 'deb_disagree':
                $mail .= '<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">' . $activites['message'] . '&nbsp;' . $data['d_title'] . 'for the issue <br/>' . l($data['q_title'], drupal_get_path_alias('node/' . $data['qid'])) . '</p><b>' . hmnews_ago($activites['timestamp']) . '.</b>';
                break;
            default:
                $mail .= '<p style="font:bold 13px Arial, Helvetica, sans-serif; color:#666666; padding:5px 0px;">' . $activites['message'] . '</p><b>' . hmnews_ago($activites['timestamp']) . '.</b>';
                break;
        }
    }
    return $mail;
}

/*
  Get Followers activites
 */

function getfolloweractivites($allfollwers) {
    $follower_activites = array();
    foreach ($allfollwers as $key => $value) {
        $follower_activites[$value] = array();
        //Recent 5 activites
        if (findtask() <= 3) {
            $month_dates = week_date_month(strtotime(date('d-m-Y')));
            $start_date = $month_dates[0];

//            $recent_activitiesQ = db_query("
//											SELECT `uid`, `message_id`, `message`, `uid_target`, `timestamp`
//											FROM {heartbeat_activity}
//											WHERE `uid` = $value
//											AND DATE(FROM_UNIXTIME(`timestamp`)) >= '$start_date'
//											AND DATE(FROM_UNIXTIME(`timestamp`)) <= CURDATE()
//											ORDER BY `timestamp` DESC LIMIT 10
//										");
            $recent_activitiesQ = db_query("SELECT distinct b.*,a.message
      FROM `notify_activity` b
INNER JOIN `notify_messages` a
        ON `b`.`message_id` = `a`.`message_id`
     WHERE b.`uid` = $value AND a.status = 1 AND DATE(FROM_UNIXTIME(b.`timestamp`)) >= '$start_date'
	AND DATE(FROM_UNIXTIME(b.`timestamp`)) <= CURDATE() ORDER BY b.`timestamp` DESC LIMIT 10");
        } else {
            $month_dates = week_date(strtotime(date('d-m-Y')));
            $start_date = $month_dates[0];

//            $recent_activitiesQ = db_query("
//											SELECT `uid`, `message_id`, `message`, `uid_target`, `timestamp` FROM
//											{heartbeat_activity}
//											WHERE `uid` = $value
//											AND DATE(FROM_UNIXTIME(`timestamp`)) >= '$start_date'
//											AND DATE(FROM_UNIXTIME(`timestamp`)) <= CURDATE()
//											ORDER BY `timestamp` DESC LIMIT 5
//										");
            $recent_activitiesQ = db_query("SELECT distinct b.*,a.message
      FROM `notify_activity` b
INNER JOIN `notify_messages` a
        ON `b`.`message_id` = `a`.`message_id`
     WHERE b.`uid` = $value AND a.status = 1 AND DATE(FROM_UNIXTIME(b.`timestamp`)) >= '$start_date'
	AND DATE(FROM_UNIXTIME(b.`timestamp`)) <= CURDATE() ORDER BY b.`timestamp` DESC LIMIT 10");
        }
        //create mail templates for each users
        while ($recent_activities = db_fetch_array($recent_activitiesQ)) {
            $follower_activites[$value][] = $recent_activities;
        }
    }
    return $follower_activites;
}

/*
  Getgate and find week end or month end
 */

function findtask() {
    $mdates = week_date_month(strtotime(date('d-m-Y')));
    $dayno = array_keys($mdates, date('Y-m-d'));
    return $remaining_days = count($mdates) - $dayno[0];
}

function week_date($current_date) {
    $ts = $current_date;
    $year = date('Y', $ts);
    $week = date('W', $ts);

    for ($i = 1; $i <= 7; $i++) {
        $ts = strtotime($year . 'W' . $week . $i);
        $week_date_array[] = date("Y-m-d", $ts);
    }
    return $week_date_array;
}

function week_date_month($current_date) {
    $ts = $current_date;
    $year = date('Y', $ts);
    $week = date('W', $ts);
    $month = date('m', $ts);

    $number_of_days = cal_days_in_month(CAL_GREGORIAN, $month, $year);

    for ($i = 1; $i <= $number_of_days; $i++) {
        if ($i < 10) {
            $i = "0" . $i;
        }
        $ts = strtotime($year . $month . $i);
        $week_date_array[] = date("Y-m-d", $ts);
    }
    return $week_date_array;
}

/*
  Implement hook_cron()
 */

//function hmnewsletter_cron() {
//   getFollowers();
//   getnonfollowers();
//}

function send_newsletter() {
    // send for users having followers
    getfollowers_weekly();
    getfollowers_monthly();
    //getFollowers();
    //send mail for users having no followers
    getnonfollowers();

    return true;
}

/*
  Get date time
 */

function hmnews_ago($timestamp) {
    $difference = time() - $timestamp;
    $periods = array("second", "minute", "hour", "day", "week", "month", "years", "decade");
    $lengths = array("60", "60", "24", "7", "4.35", "12", "10");
    for ($j = 0; $difference >= $lengths[$j]; $j++)
        $difference /= $lengths[$j];
    $difference = round($difference);
    if ($difference != 1)
        $periods[$j].= "s";
    $text = "$difference $periods[$j] ago";
    return $text;
}

?>