<?php

/**
 * Implementation of hook_preprocess_page()
 *
 * @param $vars
 */
function user_login_modal_preprocess_page(&$vars)
{
  if (!user_is_logged_in()) {
    $vars['user_popups'] = theme('user_login_modal_popup');
  }
  drupal_add_js('misc/ahah.js');
  drupal_add_js(drupal_get_path('module', 'user_login_modal') . '/user_login_modal.js');
  drupal_add_css(drupal_get_path('module', 'user_login_modal') . '/user_login_modal.css');
  $vars['user_login_modal'] = theme('user_login_modal');

  if (!user_is_logged_in()) {
    $vars['login_block'] = drupal_get_form('user_login');
    $vars['login_register'] = drupal_get_form('user_register');
  }
}

/**
 * Implementation of hook_theme()
 *
 * @return array
 */
function user_login_modal_theme()
{
  $theme = array();

  $theme['user_login_modal'] = array(
    'arguments' => array(),
  );
  $theme['user_login_modal_popup'] = array(
    'arguments' => array(),
  );
  $theme['user_login_modal_class'] = array(
    'arguments' => array('force' => false),
  );

  return $theme;
}

/**
 * Theme "user_login_modal"
 *
 * @return string
 */
function theme_user_login_modal()
{
  global $user;
  return '<p><a id="dialog_link" class="ui-state-default ui-corner-all login ' . theme('user_login_modal_class') . '" href="#"><i class="icon-user"></i><span>' .
    (user_is_logged_in() ? $user->name : t('Login')) .
    '</span></a></p>';
}

/**
 * Theme "user_login_modal_popup"
 *
 * @return string
 */
function theme_user_login_modal_popup()
{
  return '
  <div style="display:none">

    <a href="#popup-login" class="inline-dialog"></a>

    <div id="popup-login">

      <div id="tabs-1" class="popup-tab">
        <div id="user-login">
          <h2>'.t('Login').'</h2>
          ' . drupal_get_form('user_login') . '
        </div>
      </div>

      <div id="tabs-2" class="popup-tab">
        <div id="user-register">
          <h2>'.t('Register').'</h2>
          ' . drupal_get_form('user_register') . '
        </div>
      </div>

    </div>
  </div>';
}

/**
 * @param bool $force
 * @return string
 */
function user_login_modal_class($force = false)
{
  return !$force && user_is_logged_in() ? '' : 'openlogin_box';
}

/**
 * @param bool $force
 * @return string
 */
function theme_user_login_modal_class($force = false)
{
  return user_login_modal_class($force);
}