<?php
/**
 * Implementation of hook_perm().
 */
function invite_perm() {
  return array('Invite Friends','Twitter Login');
}
/**
 * Implementation of hook_menu().
 */
 
function invite_menu() {	

$items['invite/invite_friends'] = array(
    'title' => ' Invite Friends',
    'page callback' => 'invite_friends',
    'access arguments' => array('Invite Friends'),
    'type' => MENU_CALLBACK,
    'file' => 'invite.pages.inc',
  );
  $items['twitter/post'] = array(
    'title' => ' Twitter ',
    'page callback' => 'twitter_login',
    'access arguments' => array('Twitter Login'),
    'type' => MENU_CALLBACK,
    'file' => 'invite.pages.inc',
  );
  
    $items['twitterpost'] = array(
    'title' => ' Twitter ',
    'page callback' => 'twitterpost_save',
    'access arguments' => array('Twitter Login'),
    'type' => MENU_CALLBACK,
    'file' => 'invite.pages.inc',
  );
  
  
  return $items;
}

function htmlmail($to, $subject, $message, $headers = NULL)
{
	 global $gSitePath,$user,$gDocPath,$base_root,$base_path;

$imgw=$gSitePath."/sites/all/modules/heardmentality/images/logo_mail.gif";
	$imag=$config['file_path'].$img;
// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";





$headers .= 'From: HeardMentality <support@heardmenatlity.com>' . "\r\n";


	$newmessage .='<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Heard Mentality</title>
<style type="text/css">
<!--
body,td,th {
	font-family: Arial, Helvetica, sans-serif; font-size:14px; line-height:25px;
}
.y18{font-family: Arial, Helvetica, sans-serif; font-size:18px; color:#cc9900; text-decoration:none;}
-->
</style></head>

<body>
<table width="831px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="591" valign="top" background="'.$gSitePath.$path.'/images/email.jpg" style="background-repeat:no-repeat"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="187">&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td width="36%">&nbsp;</td>
        <td width="64%"><table style="border:1px solid #cc9900" width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="left" bgcolor="#FFFFFF" style="padding:5px;">';
        $newmessage .= $message;
	 $newmessage .='</td>
          </tr>
          <tr>
            <td align="left" bgcolor="#FFFFFF" style="padding:5px;"><br />
              Visit our website <a title="Heardmentality.com" href="'.$gSitePath.'" target="_blank" class="y18">Heardmentality.com</a> <br />
              <br />
Thanks, <br />
Heardmentality Team. </td>
          </tr>
        </table></td>
      </tr>

      <tr>
        <td>&nbsp;</td>
        <td align="right"><img src="'.$gSitePath.$path.'/images/email-bot.jpg" alt="img" width="152" height="47" /></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>';

return mail($to, $subject, $newmessage, $headers);
}






function htmlmail_function($to, $subject, $message, $headers = NULL)
{

 
	 global $gSitePath,$user,$gDocPath,$base_root,$base_path,$theme_path,$theme;
$path = drupal_get_path('theme', 'newtheme');

$newmessage = '';
$imgw=$gSitePath.$path."/images/logo_mail.gif";
	$imag=$config['file_path'].$img;
// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";

$headers .= 'From: HeardMentality <support@heardmenatlity.com>' . "\r\n";

 $newmessage .='<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Heard Mentality</title>
<style type="text/css">
<!--
body,td,th {
	font-family: Arial, Helvetica, sans-serif; font-size:14px; line-height:25px;
}
.y18{font-family: Arial, Helvetica, sans-serif; font-size:18px; color:#cc9900; text-decoration:none;}
-->
</style></head>

<body>
<table width="831px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="591" valign="top" background="'.$gSitePath.$path.'/images/email.jpg" style="background-repeat:no-repeat"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="187">&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td width="36%">&nbsp;</td>
        <td width="64%"><table style="border:1px solid #cc9900" width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="left" bgcolor="#FFFFFF" style="padding:5px;">';
 $newmessage .= $message;
	 $newmessage .='</td>
          </tr>
          <tr>
            <td align="left" bgcolor="#FFFFFF" style="padding:5px;"><br />
              Visit our website <a title="Heardmentality.com" href="'.$gSitePath.'" target="_blank" class="y18">Heardmentality.com</a> <br />
              <br />
Thanks, <br />
Heardmentality Team. </td>
          </tr>
        </table></td>
      </tr>

      <tr>
        <td>&nbsp;</td>
        <td align="right"><img src="'.$gSitePath.$path.'/images/email-bot.jpg" alt="img" width="152" height="47" /></td>
      </tr>
    </table></td>
  </tr>
</table>
</body>
</html>';
  
  

	return mail($to, $subject, $newmessage, $headers);
}



function hm_mails($subject,$content)
{
    global $gSitePath, $user, $gDocPath, $base_root;
    $sel_follow="select f.*,u.mail from follower as f join users as u on f.uid=u.uid where f.follower_id='".$user->uid."' and follower_id!=0 and cat_id=0 and question_id=0";
    $get_follow = db_query($sel_follow);


    
    $mail_row = db_query("select mail from users where uid='".$user->uid."'");
    $fet_mail = db_fetch_object($mail_row);

    
     while($fet_follow = db_fetch_object($get_follow))
    {
         if($fet_follow->notify_etype==1)
         {
       echo $ins_qry = "insert into hm_mails(mail_id,from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date,mail_type)values('".$fet_follow->uid."','mgopi.php@gmail.com','".$fet_mail->mail."','".$fet_follow->mail."','".$subject."','".$content."',0,now())";
       exit;
       db_query($ins_qry);
         }
    }
    
}






     /*$sel_follow="select * from follower where uid='".$user->uid."' and follower_id!=0 and cat_id=0";
     $get_follow = db_query($sel_follow);

     while($fet_follow = db_fetch_object($get_follow))
    {

     $wer_qry = "select * from follower where uid='".$fet_follow->follower_id."' and follower_id=0 and cat_id!=0";

        $db_res = db_query($wer_qry);
         while($db_rows = db_fetch_object($db_res))
        {

$insert_notify = db_query("insert into hm_mails (mail_id,from_mail_id,user_from_id,user_to_id,subject,content,mail_status,posted_date,mail_type)values('".$user->uid."','admin@gmail.com','".$user->uid."');
        }
    }*/

            
           










