<?php
/**
 * Implementation of hook_perm().
 */
function invite_perm() {
  return array('Invite Friends');
}


/**
 * Implementation of hook_menu().
 */
 
function invite_menu() {	

$items['invite/invite_friends'] = array(
    'title' => ' Invite Friends',
    'page callback' => 'invite_friends',
    'access arguments' => array('Invite Friends'),
    'type' => MENU_CALLBACK,
    'file' => 'invite.pages.inc',
  );
  return $items;
}


function htmlmail($to, $subject, $message, $headers = NULL)
{
	

// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";





$headers .= 'From: HeardMentality <support@heardmenatlity.com>' . "\r\n";



	$newmessage .= '<body link="#990000" vlink="#990000" alink="#990000" leftmargin="5" topmargin="5" marginwidth="0" marginheight="0">
		<table width="465" height="332" border="0" cellpadding="8" cellspacing="2" bgcolor="#C20C3D">
		<tr> 
		<td width="439" bgcolor="#FFFFFF"><img src="'.$gSitePath.'sites/all/themes/heardmentality/images/logo.gif" height="75" width="150"></td>
		</tr>
		<tr> 
		<td bgcolor="#FFFFFF" class="text">';

	
	$newmessage .= $message;

	
	$newmessage .= '</td></tr></table></td></tr></table></body>
</html>
';

	return mail($to, $subject, $newmessage, $headers);
}