<?php
/**
 * Implementation of hook_perm().
 */
function invite_perm() {
  return array('Invite Friends');
}


/**
 * Implementation of hook_menu().
 */
 
function invite_menu() {	

$items['invite/invite_friends'] = array(
    'title' => ' Invite Friends',
    'page callback' => 'invite_friends',
    'access arguments' => array('Invite Friends'),
    'type' => MENU_CALLBACK,
    'file' => 'invite.pages.inc',
  );
  return $items;
}


function htmlmail($to, $subject, $message, $headers = NULL)
{
	 global $gSitePath,$user,$gDocPath,$base_root,$base_path;

$imgw=$gSitePath."/sites/all/modules/heardmentality/images/logo_mail.gif";
	$imag=$config['file_path'].$img;
// To send HTML mail, the Content-type header must be set
$headers  = 'MIME-Version: 1.0' . "\r\n";
$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";





$headers .= 'From: HeardMentality <support@heardmenatlity.com>' . "\r\n";



	$newmessage .= '<html>
<head>
<title>welcome</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</head>
<body bgcolor="#FFFFFF" text="#000000" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table cellspacing=0 cellpadding=0 width=600 align=center bgcolor=#ffffff 
      border=0>
  <tbody> 
  <tr>  
    <td background="'.$gSitePath.'/sites/all/themes/heardmentality/images/header_bg.gif"><img src="'.$gSitePath.'/sites/all/themes/heardmentality/images/logo_mail.jpg" width="100" height="140" ></td>
 
  </tr>
  <tr> 
    <td> 
      <table width="100%" border="0" cellspacing="1" cellpadding="0" bgcolor="#494DCD">
        <tr> 
          <td> 
            <table cellspacing=1 cellpadding=25 width=600 
            align=center border=0 class="text_black" bgcolor="#F2F2EC">
              <tbody> 
              <tr> 
                <td valign=top align=middle class="text_black">';

	
	$newmessage .= $message;

	
	$newmessage .= ' </td>
  </tr>
  
  </tbody> 
</table>
</body>
</html>
';

	return mail($to, $subject, $newmessage, $headers);
}