<?php
function qlite_perm() {
    
    return array('QLite', 'Report', 'Report Content', 'Ajax Content');

} // function newmodule_perm
function qlite_menu() {
    
    $item['qmini'] = array('title'=>'Question Lite', 'page callback'=>'qlitemini', 'access arguments'=>array('QLite'), 'type'=>MENU_CALLBACK, 'file'=>'qlite.pages.inc', );
    
    $item['qmini/report'] = array('title'=>'Question Lite', 'page callback'=>'qlite_report', 'type'=>MENU_CALLBACK, 'access arguments'=>array('Report'), 'file'=>'qlite.pages.inc', );
    $item['qmini/repcontent'] = array('title'=>'Question Lite', 'page callback'=>'report_content', 'type'=>MENU_CALLBACK, 'access arguments'=>array('Report Content'), 'file'=>'qlite.pages.inc', );
    $item['qmini/ajax'] = array('title'=>'Question Lite', 'page callback'=>'load_ajax', 'type'=>MENU_CALLBACK, 'access arguments'=>array('Ajax Content'), 'file'=>'qlite.pages.inc', );
    
    return $item;


}

function top_list() {
    drupal_add_js(drupal_get_path('module', 'qlite').'/scripts/qmini.js');
    $output = '';
    
    $query = "SELECT * from {category} where parent_id='0' ORDER BY cat_name ASC";
    $list = ExecuteQuery($query, "select");
    $output .= '<select id="tcat" onchange="get_toplist(this.value,1)"><option value="" >Select</option>';
    foreach ($list as $cat) {
        
        $output .= '<option value='.$cat['cat_id'].' > '.$cat['cat_name'].' </option>';
    }
    
    $output .= '</select><br/>	<div id="res_scat"> </div><br/><div id="res_top">';
    
    $output .= get_top_list();
    
    $output .= get_hot_list();
    
    $output .= get_local_list();
    
    echo "</div>";

    
    return $output;


}

function get_top_list() {
    
    global $gSitePath,$user,$gDocPath,$base_root;
    $output = '';
    $cond = '';

    
    $cond = load_condition();

    
    $query = "SELECT * from {question} as q join {user_profile} as u on u.uid=q.uid  where q.status='1' $cond order by q.active_rate  DESC LIMIT 0,10";
    $list = ExecuteQuery($query, "select");
    $output .= '<div id="pageWrapper" >';
    if (! empty($list)) {
        foreach ($list as $quest) {
            
            $output .= '<li><a href="'.$quest['url'].'">'.myTruncate($quest['question'], '40', '', '..').'</a></li>';

        
        }
    } else {
        
        $output .= '<div><b>No Top List Found</b></div>';
    
    }
    $output .= '</div>';
    return $output;
}

function get_hot_list() {
    
    global $gSitePath,$user,$gDocPath,$base_root;
    $output = '';
    $cond = '';

    
    $cond = load_condition();
    
    $m = date("m");
    $de = date("d");
    $y = date("Y");
    $date = date('Y-m-d', mktime(0, 0, 0, $m, ($de - 7), $y));

    
    $query = "SELECT * from {question} as q join {user_profile} as u on u.uid=q.uid  where q.status='1' AND date(q.date_added) >= '$date' $cond order by q.active_rate  DESC LIMIT 0,10 ";
    $list = ExecuteQuery($query, "select");
    $output .= '<div id="pageWrapper" >';
    if (! empty($list)) {
        foreach ($list as $quest) {
            
            $output .= '<li><a href="'.$quest['url'].'">'.myTruncate($quest['question'], '40', '', '..').'</a></li>';

        
        }
    } else {
        
        $output .= '<div><b>No Hot List Found</b></div>';
    
    }
    $output .= '</div>';
    return $output;


}

function get_local_list() {
    global $gSitePath,$user,$gDocPath,$base_root;
    $output = '';
    $cond = '';

    
    $cond = load_condition();
    
    $homepage = file_get_contents('http://api.hostip.info/country.php');

    
    $query = "SELECT * from {question} as q join {user_profile} as u on u.uid=q.uid  where q.status='1' AND q.country='".trim($homepage)."' $cond order by q.active_rate  DESC LIMIT 0,10 ";
    $list = ExecuteQuery($query, "select");
    $output .= '<div id="pageWrapper" >';
    
    if (! empty($list)) {
        foreach ($list as $quest) {
            
            $output .= '<li><a href="'.$quest['url'].'">'.myTruncate($quest['question'], '40', '', '..').'</a></li>';
        
        }
    } else {
        
        $output .= '<div><b>No Local List Found</b></div>';
    
    }
    return $output;


}

function cal_active_rate() {

    
    global $gSitePath,$user,$gDocPath,$base_root;
    $j = 5;
    $k = 5;
    $l = 5;
    $fcnt = array();
    $gvote = array();
    $query = "SELECT * from {question}";
    $list = ExecuteQuery($query, "select");
    
    foreach ($list as $quest) {

        
        $query1 = "select IFNULL((select count(*) from {possible_answer_vote} as pa where q.qid=pa.qid group by pa.qid ),0) as pvote,(select count(*) from {suggest_answer_vote} as sa where q.qid=sa.qid group by sa.qid ) as svote from {question} as q where q.qid='".$quest['qid']."'";
        $gvote = ExecuteQuery($query1, "select");
        $m1 = $gvote[0]['pvote'];
        $m2 = $gvote[0]['svote'];
        
        $tvote = $m1 + $m2;
        
        $query2 = "select IFNULL((select count(*) from {forum_wavelets} as w where w.wid=f.fid group by w.wid),0) as wcnt,IFNULL((select count(*) from {resource} where qid='".$quest['qid']."' group by qid),0) as rcnt from {forum_wave} as f where f.qid_rid='".$quest['qid']."' ";
        $fcnt = db_fetch_object(db_query($query2));
        
        //The value “active” will be calculated as follows (j,k,l are constant values that will be hard-coded):
        //Active =  (j * #_of_votes_for_question) + (k * #_of_forum_posts) + (l * #_of_posted_resources)
        if (! empty($fcnt)) {
            $cntr = $fcnt->wcnt;
            $wcnt = $fcnt->rcnt;
            $active = (($j * $tvote) + ($k * $cntr) + ($l * $wcnt));
            db_query("update {question} set active_rate='".$active."' where qid='".$quest['qid']."'");
        }

    
    }

}
function load_condition() {
    $cond = '';
    //print_r($_REQUEST);
    if (isset($_REQUEST['cid']) && isset($_REQUEST['action'])) {
        extract($_REQUEST);
        if (! empty($cid)) {
            
            $cond .= " AND q.cid='$cid'";
        }
        
        if (! empty($scid)) {
            
            $cond .= " AND q.scid='$scid'";
        }
    
    }
    
    return $cond;

}