<?php
/**
 * Implementation of hook_perm().
 */
function gurupoints_perm() {
  return array('Add Points','list Points');
}


/**
 * Implementation of hook_menu().
 */
 
function gurupoints_menu() {	

$search_result['admin/addpoints'] = array(
    'title' => ' Add Points',
    'page callback' => 'add_points',
    'access arguments' => array('Add Points'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'gurupoints.pages.inc',
  );

$search_result['admin/point/save'] = array(
    'title' => ' Add Points',
    'page callback' => 'save_points',
    'access arguments' => array('Add Points'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'gurupoints.pages.inc',
  );
  
  $search_result['admin/userpoints'] = array(
    'title' => 'User Points',
    'page callback' => 'user_points',
    'access arguments' => array('list Points'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'gurupoints.pages.inc',
  );
  return $search_result;
}

function increasepoints($ptype,$qid,$idm)
{
 global $gSitePath,$user,$gDocPath,$base_root,$base_path;
	
	
	$queryuser= "SELECT * FROM user_profile where uid=$user->uid "; 
	$query_result=db_query($queryuser);
	$userresult=db_fetch_object($query_result);
	
	if($idm=='0')
	{
	$numpt= db_result(db_query("SELECT COUNT(*) from {tbl_user_points} where point_id='$ptype' and qid='$qid' and uid='$user->uid'"));
	  $query_pt= "SELECT * FROM tbl_points where id='$ptype' "; 
	$query_ptinfo=db_query($query_pt);
	$fetuserpts=db_fetch_object($query_ptinfo);
	
	if($numpt==0)
	{
	  $insert_pts="insert into tbl_user_points (uid,qid,point_id,points,vote_point_id) values($user->uid,$qid,$ptype,$fetuserpts->points,$idm)";
	$qus=db_query($insert_pts);
	$totpts=$userresult->points+$fetuserpts->points;
	$uppts="update user_profile set points=$totpts where uid=$user->uid";
	$quspts=db_query($uppts);
	}
	}
	else
	{
	//echo $idm;
	
	
	$cntr= db_result(db_query("SELECT COUNT(*) from {tbl_user_points} where vote_point_id='$idm' and qid='$qid' and uid='$user->uid'"));
	
	 $query_ptm ="select * from tbl_vote_gurupoints where id='".$idm."'"; 
	$query_ptinfo=db_query($query_ptm);
	$fetuserpts=db_fetch_object($query_ptinfo);
	
	
	
	if($cntr==0)
	{
	 $insert_pts="insert into tbl_user_points (uid,qid,point_id,points,vote_point_id) values($user->uid,$qid,$ptype,$fetuserpts->points,$idm)";
	$qus=db_query($insert_pts);
	$totpts=$userresult->points+$fetuserpts->points;
	$uppts="update user_profile set points=$totpts where uid=$user->uid";
	$quspts=db_query($uppts);
	}
	
	
	
	
	
	
	}
	

}


function insertpoints($action='',$nodeid='')
{
 global $gSitePath,$user,$gDocPath,$base_root,$base_path;
	
	if(!empty($nodeid)&&!empty($action)){
		$set=$action."='1'";
		//points 
			 $query_pt= "SELECT * FROM tbl_points where id='3' "; 
	$query_ptinfo=db_query($query_pt);
	$fetuserpts=db_fetch_object($query_ptinfo);
		$queryuser= "SELECT count(*) FROM {tbl_user_points}  where uid='$user->uid' AND $set AND nodeid='$nodeid' "; 
	$rcnt=db_result(db_query($queryuser));
	
	if($rcnt==0){
		
	db_query("insert into {tbl_user_points} set point_id='$fetuserpts->id',points='$fetuserpts->points',uid='$user->uid',$set,nodeid='$nodeid'");	
		
	}
	
		
	}
	
	

}


function guru_points(){
	
	
	
		$user_pt = "SELECT a.uid, a.name, a.mail, SUM(b.points) AS point FROM users as a LEFT OUTER JOIN tbl_user_points as b ON a.uid = b.uid GROUP BY uid  "; 

	 $point_list = ExecuteQuery($user_pt, "select");
   
   $outputppt='<table width="60%" border="0" cellspacing="0" cellpadding="0">
   
   
  <tr>
    <td><h2>User</h2></td>
   <td><h2>Total Points</h2></td>
  </tr>';
  for($p=0;$p<count($point_list);$p++)
	{
	
	$puid=$point_list[$p]['uid'];
	
	   $qptstd="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='1' group by uid";
	  // $qrylist = ExecuteQuery($qptstd, "select");
	 $voteqrylist = db_query($qptstd);
    $fetqrylist = db_fetch_array($voteqrylist);
	
	
	     $qptstd2="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='2' group by uid";
	  // $qrylist2 = ExecuteQuery($qptstd2, "select");
	  $voteqrylist2 = db_query($qptstd2);
    $fetqrylist2 = db_fetch_array($voteqrylist2);
	$pt1=$fetqrylist2['qpt'];
	
	 $qptstd3="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='3' group by uid";
	  // $qrylist3 = ExecuteQuery($qptstd3, "select");
	   
	    $voteqrylist3 = db_query($qptstd3);
    $fetqrylist3 = db_fetch_array($voteqrylist3);
	$pt2=$fetqrylist3['qpt'];
	  
	   
	   $qptstd4="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='4' group by uid";
	  // $qrylist4 = ExecuteQuery($qptstd4, "select");
	  //$pt3=$qrylist4[0]['qpt'];
	    $voteqrylist4 = db_query($qptstd4);
    $fetqrylist4 = db_fetch_array($voteqrylist4);
	$pt3=$fetqrylist4['qpt'];
	  
	$qptstd5="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='5' group by uid";
	   //$qrylist5 = ExecuteQuery($qptstd5, "select");
	   //$pt4=$qrylist5[0]['qpt'];
	    $voteqrylist5 = db_query($qptstd5);
    $fetqrylist5 = db_fetch_array($voteqrylist5);
	$pt4=$fetqrylist5['qpt'];
	   
	   $qptstd6="select SUM(points) AS qpt   FROM tbl_user_points where  uid=".$puid." and point_id='6' group by uid";
	  // $qrylist6 = ExecuteQuery($qptstd6, "select");
	   // $pt5=$qrylist6[0]['qpt'];
		
		$voteqrylist6 = db_query($qptstd6);
		$fetqrylist6 = db_fetch_array($voteqrylist6);
		$pt5=$fetqrylist6['qpt'];
	   if($point_list[$p]['point']=='')
	$pt='0';
	else
	$pt=$point_list[$p]['point'];
	$spt=$fetqrylist['qpt'];
	   $vtpt=$pt-($spt+$pt1+$pt2+$pt3+$pt4+$pt5);
	
  $outputppt.=' <tr>
	<td height="40">'.$point_list[$p]['name'].'</td>
	<td>'.$pt.'</td>
  </tr>';
  
  }
$outputppt.='</table>';
   
   return $outputppt;
	
	
}


