<?php

/*
 * Implementation of hook_init()
 */
function ugc_init() {
  global $base_url;
  drupal_add_js(array('base_url' => $base_url), 'setting');
}

/*
 * Custom filter
 *
 * @see array_filter
 */
function word_array_filter($word = '') {
  return !empty($word) && (strlen($word)>=3);
}


/*
 * Get input language
 */
function get_input_language($title = '') {
  module_load_include('inc', 'issue_translator', 'gtranslate-api-php/googletranslate.class');
  $gt = new GoogleTranslateWrapper();
  $input = $gt->detectLanguage($title);
  $language = $input['language'];
  $language = $language != '' ? $language : 'en';
  return $language;
}

/*
 * TODO - remove
 */
function drupal_link_color($uid, $nid) {
  return false != db_result(db_query("SELECT COUNT(*) AS count FROM {poll_votes} WHERE nid='%d' AND uid='%d'", $uid, $nid)) ? 'font-weight:bold' : '';
}