<?php

function location_province_list_yt () {
	return array (
		"97601" => t("Acoua"),
		"97602" => t("Bandraboua"),
		"97603" => t("Bandrele"),
		"97604" => t("Bouéni"),
		"97605" => t("Chiconi"),
		"97606" => t("Chirongui"),
		"97607" => t("Dembeni"),
		"97608" => t("Dzaoudzi"),
		"97609" => t("Kani-Kéli"),
		"97610" => t("Koungou"),
		"97613" => t("M'Tsangamouji"),
		"97611" => t("Mamoudzou"),
		"97612" => t("Mtsamboro"),
		"97614" => t("Ouangani"),
		"97615" => t("Pamandzi"),
		"97616" => t("Sada"),
		"97617" => t("Tsingoni"),
	);
}
