<?php

function location_province_list_ec () {
	return array (
		"B" => t("Provincia de Bolívar"),
		"X" => t("Provincia de Cotopaxi"),
		"O" => t("Provincia de El Oro"),
		"E" => t("Provincia de Esmeraldas"),
		"D" => t("Provincia de Francisco de Orellana"),
		"W" => t("Provincia de Galápagos"),
		"I" => t("Provincia de Imbabura"),
		"L" => t("Provincia de Loja"),
		"R" => t("Provincia de Los Ríos"),
		"M" => t("Provincia de Manabí"),
		"S" => t("Provincia de Morona Santiago"),
		"N" => t("Provincia de Napo"),
		"P" => t("Provincia de Pichincha"),
		"SE" => t("Provincia de Santa Elena"),
		"SD" => t("Provincia de Santo Domingo de los Tsáchilas"),
		"U" => t("Provincia de Sucumbíos"),
		"Z" => t("Provincia de Zamora Chinchipe"),
		"A" => t("Provincia del Azuay"),
		"C" => t("Provincia del Carchi"),
		"F" => t("Provincia del Cañar"),
		"H" => t("Provincia del Chimborazo"),
		"G" => t("Provincia del Guayas"),
		"Y" => t("Provincia del Pastaza"),
		"T" => t("Provincia del Tungurahua"),
	);
}
