<?php
/**
 * Implementation of hook_perm().
 */
function political_perm() {
  return array('Category list','Category add','Category view','Admin Category');
}


/**
 * Implementation of hook_menu().
 */
 
function political_menu() {	
  $items['politicalapi'] = array(
    'title' => 'Political',
    'page callback' => 'political_api',
    'access arguments' => array('Category list'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'political.pages.inc',
  );

  return $items;
}


