<?php

function location_province_list_ve() {
  return array(
    "Y" => t("Delta Amacuro"),
    "W" => t("Dependencias Federales"),
    "A" => t("Distrito Federal"),
    "Z" => t("Estado Amazonas"),
    "B" => t("Estado Anzoátegui"),
    "C" => t("Estado Apure"),
    "D" => t("Estado Aragua"),
    "E" => t("Estado Barinas"),
    "F" => t("Estado Bolívar"),
    "G" => t("Estado Carabobo"),
    "H" => t("Estado Cojedes"),
    "I" => t("Estado Falcón"),
    "J" => t("Estado Guárico"),
    "K" => t("Estado Lara"),
    "M" => t("Estado Miranda"),
    "N" => t("Estado Monagas"),
    "L" => t("Estado Mérida"),
    "O" => t("Estado Nueva Esparta"),
    "P" => t("Estado Portuguesa"),
    "S" => t("Estado Táchira"),
    "U" => t("Estado Yaracuy"),
    "V" => t("Estado Zulia"),
    "R" => t("Sucre"),
    "T" => t("Trujillo"),
    "X" => t("Vargas"),
  );
}
