<?php

function location_province_list_gh() {
  return array(
    "AH" => t("Ashanti Region"),
    "BA" => t("Brong-Ahafo"),
    "CP" => t("Central Region"),
    "EP" => t("Eastern Region"),
    "AA" => t("Greater Accra Region"),
    "NP" => t("Northern Region"),
    "UE" => t("Upper East Region"),
    "UW" => t("Upper West Region"),
    "TV" => t("Volta Region"),
    "WP" => t("Western Region"),
  );
}
