<?php

function location_province_list_no() {
  return array(
    "02" => t("Akershus county"),
    "09" => t("Aust-Agder county"),
    "06" => t("Buskerud county"),
    "20" => t("Finnmark Fylke"),
    "04" => t("Hedmark county"),
    "12" => t("Hordaland Fylke"),
    "15" => t("Møre og Romsdal fylke"),
    "17" => t("Nord-Trøndelag Fylke"),
    "18" => t("Nordland Fylke"),
    "05" => t("Oppland county"),
    "03" => t("Oslo County"),
    "11" => t("Rogaland Fylke"),
    "14" => t("Sogn og Fjordane Fylke"),
    "16" => t("Sør-Trøndelag Fylke"),
    "08" => t("Telemark county"),
    "19" => t("Troms Fylke"),
    "10" => t("Vest-Agder Fylke"),
    "07" => t("Vestfold county"),
    "01" => t("Østfold"),
  );
}
