<?php

function location_province_list_am() {
  return array(
    "AG" => t("Aragatsotni Marz"),
    "AR" => t("Ararati Marz"),
    "AV" => t("Armaviri Marz"),
    "GR" => t("Geghark’unik’i Marz"),
    "KT" => t("Kotayk’i Marz"),
    "LO" => t("Lorru Marz"),
    "SH" => t("Shiraki Marz"),
    "SU" => t("Syunik’i Marz"),
    "TV" => t("Tavushi Marz"),
    "VD" => t("Vayots’ Dzori Marz"),
    "ER" => t("Yerevan"),
  );
}
