<?php

function location_province_list_sd() {
  return array(
    "GZ" => t("Al Jazirah State"),
    "GD" => t("Al Qadarif State"),
    "NB" => t("Blue Nile State"),
    "DC" => t("Central Darfur State"),
    "DE" => t("Eastern Darfur"),
    "KA" => t("Kassala"),
    "KH" => t("Khartoum State"),
    "NO" => t("Northern"),
    "DN" => t("Northern Darfur State"),
    "KN" => t("Northern Kordofan State"),
    "RS" => t("Red Sea"),
    "NR" => t("River Nile State"),
    "SI" => t("Sinnar"),
    "DS" => t("Southern Darfur State"),
    "KS" => t("Southern Kordofan State"),
    "DW" => t("Western Darfur State"),
    "NW" => t("White Nile State"),
  );
}
