<?php

function location_province_list_sr() {
  return array(
    "BR" => t("Distrikt Brokopondo"),
    "CM" => t("Distrikt Commewijne"),
    "CR" => t("Distrikt Coronie"),
    "MA" => t("Distrikt Marowijne"),
    "NI" => t("Distrikt Nickerie"),
    "PR" => t("Distrikt Para"),
    "PM" => t("Distrikt Paramaribo"),
    "SA" => t("Distrikt Saramacca"),
    "SI" => t("Distrikt Sipaliwini"),
    "WA" => t("Distrikt Wanica"),
  );
}
