<?php

function location_province_list_tn() {
  return array(
    "13" => t("Gouvernorat de Ben Arous"),
    "23" => t("Gouvernorat de Bizerte"),
    "31" => t("Gouvernorat de Béja"),
    "81" => t("Gouvernorat de Gabès"),
    "71" => t("Gouvernorat de Gafsa"),
    "32" => t("Gouvernorat de Jendouba"),
    "41" => t("Gouvernorat de Kairouan"),
    "42" => t("Gouvernorat de Kasserine"),
    "33" => t("Gouvernorat de Kef"),
    "73" => t("Gouvernorat de Kébili"),
    "53" => t("Gouvernorat de Mahdia"),
    "52" => t("Gouvernorat de Monastir"),
    "82" => t("Gouvernorat de Médenine"),
    "21" => t("Gouvernorat de Nabeul"),
    "61" => t("Gouvernorat de Sfax"),
    "43" => t("Gouvernorat de Sidi Bouzid"),
    "34" => t("Gouvernorat de Siliana"),
    "51" => t("Gouvernorat de Sousse"),
    "72" => t("Gouvernorat de Tozeur"),
    "11" => t("Gouvernorat de Tunis"),
    "22" => t("Gouvernorat de Zaghouan"),
    "12" => t("Gouvernorat de l’ Ariana"),
    "14" => t("Manouba"),
    "83" => t("Tataouine"),
  );
}
