<?php

function location_province_list_mg() {
  return array(
    "7670851" => t("Alaotra Mangoro Region"),
    "7670904" => t("Amoron'i Mania Region"),
    "7670856" => t("Analamanga Region"),
    "7670848" => t("Analanjirofo Region"),
    "7670911" => t("Androy Region"),
    "7670910" => t("Anosy Region"),
    "7670913" => t("Atsimo-Andrefana Region"),
    "7670908" => t("Atsimo-Atsinanana Region"),
    "7670857" => t("Atsinanana Region"),
    "7670850" => t("Betsiboka Region"),
    "7670849" => t("Boeny Region"),
    "7670853" => t("Bongolava Region"),
    "7670842" => t("Diana Region"),
    "7670907" => t("Ihorombe Region"),
    "7670855" => t("Itasy Region"),
    "7670852" => t("Melaky Region"),
    "7670902" => t("Menabe Region"),
    "7670846" => t("Sava Region"),
    "7670847" => t("Sofia Region"),
    "7670905" => t("Upper Matsiatra"),
    "7670854" => t("Vakinankaratra Region"),
    "7670906" => t("Vatovavy Fitovinany Region"),
  );
}
