<?php

function location_province_list_sv() {
  return array(
    "AH" => t("Departamento de Ahuachapán"),
    "CA" => t("Departamento de Cabañas"),
    "CH" => t("Departamento de Chalatenango"),
    "CU" => t("Departamento de Cuscatlán"),
    "LI" => t("Departamento de La Libertad"),
    "PA" => t("Departamento de La Paz"),
    "UN" => t("Departamento de La Unión"),
    "MO" => t("Departamento de Morazán"),
    "SM" => t("Departamento de San Miguel"),
    "SS" => t("Departamento de San Salvador"),
    "SV" => t("Departamento de San Vicente"),
    "SA" => t("Departamento de Santa Ana"),
    "SO" => t("Departamento de Sonsonate"),
    "US" => t("Departamento de Usulután"),
  );
}
