<?php

function location_province_list_ma() {
  return array(
    "09" => t("Chaouia-Ouardigha"),
    "10" => t("Doukkala-Abda"),
    "02" => t("Gharb-Chrarda-Beni Hssen"),
    "14" => t("Guelmim-Es Semara"),
    "15" => t("Laâyoune-Boujdour-Sakia El Hamra"),
    "11" => t("Marrakech-Tensift-Al Haouz"),
    "04" => t("Oriental Region"),
    "EH" => t("Oued ed Dahab-Lagouira"),
    "05" => t("Région de Fès-Boulemane"),
    "06" => t("Région de Meknès-Tafilalet"),
    "07" => t("Région de Rabat-Salé-Zemmour-Zaër"),
    "13" => t("Région de Souss-Massa-Drâa"),
    "01" => t("Région de Tanger-Tétouan"),
    "08" => t("Région du Grand Casablanca"),
    "12" => t("Tadla-Azilal"),
    "03" => t("Taza-Al Hoceima-Taounate"),
  );
}
