<?php

function location_province_list_et() {
  return array(
    "AF" => t("Afar Region"),
    "AM" => t("Amhara Region"),
    "BE" => t("Benishangul-Gumuz Region"),
    "DD" => t("Dire Dawa Region"),
    "GA" => t("Gambela"),
    "HA" => t("Harari Region"),
    "OR" => t("Oromiya Region"),
    "SO" => t("Somali Region"),
    "SN" => t("Southern Nations, Nationalities, and People's Region"),
    "TI" => t("Tigray Region"),
    "AA" => t("Ādīs Ābeba Āstedader"),
  );
}
