<?php

function location_province_list_bo() {
  return array(
    "H" => t("Departamento de Chuquisaca"),
    "C" => t("Departamento de Cochabamba"),
    "L" => t("Departamento de La Paz"),
    "N" => t("Departamento de Pando"),
    "P" => t("Departamento de Potosí"),
    "S" => t("Departamento de Santa Cruz"),
    "T" => t("Departamento de Tarija"),
    "B" => t("Departamento del Beni"),
    "O" => t("Oruro"),
  );
}
