<?php

function location_province_list_bt() {
  return array(
    "33" => t("Bumthang Dzongkhag"),
    "12" => t("Chhukha Dzongkhag"),
    "22" => t("Dagana Dzongkhag"),
    "GA" => t("Gasa"),
    "13" => t("Haa Dzongkhag"),
    "44" => t("Lhuentse Dzongkhag"),
    "42" => t("Mongar Dzongkhag"),
    "11" => t("Paro"),
    "43" => t("Pemagatshel Dzongkhag"),
    "23" => t("Punakha Dzongkhag"),
    "45" => t("Samdrup Jongkhar"),
    "14" => t("Samtse Dzongkhag"),
    "31" => t("Sarpang Dzongkhag"),
    "15" => t("Thimphu Dzongkhag"),
    "TY" => t("Trashi Yangste"),
    "41" => t("Trashigang Dzongkhag"),
    "32" => t("Trongsa Dzongkhag"),
    "21" => t("Tsirang Dzongkhag"),
    "24" => t("Wangdue Phodrang Dzongkhag"),
    "34" => t("Zhemgang Dzongkhag"),
  );
}
