<?php

function location_province_list_bj() {
  return array(
    "AL" => t("Alibori"),
    "AK" => t("Atakora Department"),
    "AQ" => t("Atlantique Department"),
    "BO" => t("Borgou Department"),
    "CO" => t("Collines Department"),
    "DO" => t("Donga"),
    "OU" => t("Département de l’ Ouémé"),
    "KO" => t("Kouffo Department"),
    "LI" => t("Littoral"),
    "MO" => t("Mono"),
    "PL" => t("Plateau Department"),
    "ZO" => t("Zou Department"),
  );
}
