<?php

function location_province_list_so() {
  return array(
    "AW" => t("Awadal Region"),
    "BK" => t("Bakool Region"),
    "BN" => t("Banadir Region"),
    "BR" => t("Bari Region"),
    "BY" => t("Bay Region"),
    "GA" => t("Galgadud Region"),
    "GE" => t("Gedo Region"),
    "HI" => t("Hiiran Region"),
    "JH" => t("Jubbada Hoose Region"),
    "SH" => t("Lower Shabeelle"),
    "JD" => t("Middle Jubba"),
    "MU" => t("Mudug Region"),
    "NU" => t("Nugaal Region"),
    "SA" => t("Sanaag Region"),
    "SD" => t("Shabeele Dhexe Region"),
    "SO" => t("Sool Region"),
    "TO" => t("Togdheer Region"),
    "WO" => t("Waqooyi Galbeed Region"),
  );
}
