<?php

function location_province_list_ye() {
  return array(
    "AD" => t("Aden"),
    "MR" => t("Al Mahrah"),
    "MW" => t("Al Maḩwīt"),
    "SA" => t("Amanat Al Asimah"),
    "IB" => t("Ibb"),
    "AB" => t("Muḩāfaz̧at Abyan"),
    "DH" => t("Muḩāfaz̧at Dhamār"),
    "LA" => t("Muḩāfaz̧at Laḩij"),
    "MA" => t("Muḩāfaz̧at Ma’rib"),
    "RA" => t("Muḩāfaz̧at Raymah"),
    "TA" => t("Muḩāfaz̧at Ta‘izz"),
    "BA" => t("Muḩāfaz̧at al Bayḑā’"),
    "JA" => t("Muḩāfaz̧at al Jawf"),
    "HU" => t("Muḩāfaz̧at al Ḩudaydah"),
    "DA" => t("Muḩāfaz̧at aḑ Ḑāli‘"),
    "SD" => t("Muḩāfaz̧at Şa‘dah"),
    "HJ" => t("Muḩāfaz̧at Ḩajjah"),
    "HD" => t("Muḩāfaz̧at Ḩaḑramawt"),
    "AM" => t("Omran"),
    "SN" => t("Sanaa"),
    "SH" => t("Shabwah"),
  );
}
