<?php

function location_province_list_ly() {
  return array(
    "JU" => t("Al Jufrah"),
    "KF" => t("Al Kufrah"),
    "MJ" => t("Al Marj"),
    "MB" => t("Al Marqab"),
    "DR" => t("Darnah"),
    "MQ" => t("Murzuq"),
    "BA" => t("Sha‘bīyat Banghāzī"),
    "GT" => t("Sha‘bīyat Ghāt"),
    "MI" => t("Sha‘bīyat Mişrātah"),
    "NL" => t("Sha‘bīyat Nālūt"),
    "SB" => t("Sha‘bīyat Sabhā"),
    "WD" => t("Sha‘bīyat Wādī al Ḩayāt"),
    "WS" => t("Sha‘bīyat Wādī ash Shāţi’"),
    "BU" => t("Sha‘bīyat al Buţnān"),
    "JA" => t("Sha‘bīyat al Jabal al Akhḑar"),
    "JG" => t("Sha‘bīyat al Jabal al Gharbī"),
    "JI" => t("Sha‘bīyat al Jafārah"),
    "WA" => t("Sha‘bīyat al Wāḩāt"),
    "NQ" => t("Sha‘bīyat an Nuqāţ al Khams"),
    "ZA" => t("Sha‘bīyat az Zāwiyah"),
    "TB" => t("Sha‘bīyat Ţarābulus"),
    "SR" => t("Surt"),
  );
}
