<?php

function location_province_list_gt() {
  return array(
    "AV" => t("Departamento de Alta Verapaz"),
    "BV" => t("Departamento de Baja Verapaz"),
    "CM" => t("Departamento de Chimaltenango"),
    "CQ" => t("Departamento de Chiquimula"),
    "PR" => t("Departamento de El Progreso"),
    "ES" => t("Departamento de Escuintla"),
    "GU" => t("Departamento de Guatemala"),
    "HU" => t("Departamento de Huehuetenango"),
    "IZ" => t("Departamento de Izabal"),
    "JA" => t("Departamento de Jalapa"),
    "JU" => t("Departamento de Jutiapa"),
    "QZ" => t("Departamento de Quetzaltenango"),
    "RE" => t("Departamento de Retalhuleu"),
    "SA" => t("Departamento de Sacatepéquez"),
    "SM" => t("Departamento de San Marcos"),
    "SR" => t("Departamento de Santa Rosa"),
    "SO" => t("Departamento de Sololá"),
    "SU" => t("Departamento de Suchitepéquez"),
    "TO" => t("Departamento de Totonicapán"),
    "ZA" => t("Departamento de Zacapa"),
    "PE" => t("Departamento del Petén"),
    "QC" => t("Departamento del Quiché"),
  );
}
