<?php

/**
 * Implementation of hook_user()
 *
 * @param      $op
 * @param      $edit
 * @param      $account
 * @param null $category
 */
function user_ext_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'insert' :
      db_query("UPDATE {users} SET source_ip = '%s', source_page = '%s' WHERE uid = '%s'", $_SERVER['REMOTE_ADDR'], request_uri(), $account->uid);
      break;
  }
}