<?php

/**
 * Implementation of hook_enable()
 */
function poll_translate_enable()
{
  db_query("UPDATE {system} SET weight = '%d' WHERE name = 'poll_translate'", 100);
}

/**
 * @return array
 */
function poll_translate_menu() {
  $menu = array();

  $menu['content_translate/poll'] = array(
    'page callback'     => 'poll_translate_translate',
    'access arguments'  => array(CONTENT_TRANSLATE),
    'type'              => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * @param $nid
 */
function poll_translate_translate() {
  if ($language_to = arg(3)) {
    $languages = array($language_to);
  } else {
    $langs = language_list('enabled');
    foreach ($langs[0] as $code => $lang) {
      $languages[] = $code;
    }
  }
  foreach ($languages as $langcode) {
    content_translate('node', intval(arg(2)), $langcode);
  }
  exit('x--x');
}

/**
 * Implementation of hook_nodeapi()
 *
 * There we replace some data in SIDE poll with CORE one
 *
 * @param $node
 * @param $op
 * @param null $a3
 * @param null $a4
 */
function poll_translate_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  if ($node->type == 'poll') {
    switch ($op) {
      case 'presave' :
        if ($node->t) {
          foreach ($node->t as $language => $data) {
            content_translate_del(array(
              'content_type' => 'node',
              'content_id' => $node->nid,
              'language' => $language,
            ));
            foreach ($data as $field => $list) {
              if (is_array($list)) {
                foreach ($list as $field_order => $text) {
                  content_translate_add('node', $node->nid, $language, $field, $text, $field_order);
                }
              } else {
                content_translate_add('node', $node->nid, $language, $field, $list);
              }
            }
          }
          unset($node->t);
        }
      break;
      case 'load' :
        $node->t = content_translate_get('node', $node->nid);
      break;
    }
  }
}

/**
 * Implementation of hook_content_translate_node()
 *
 * @param $node
 * @param $language_to
 */
function poll_translate_content_translate_node($node, $language_to)
{
  if (!$node) {
    return;
  }

  # translation array
  if (!isset($node->t)) {
    $node->t = array();
  }


  # check if the node was translated to that language
  if (isset($node->t[$language_to])) {
    return;
  } else {
    $node->t[$language_to] = array();
  }

  # pointer
  $t = &$node->t[$language_to];

  # language to translate from
  $language_from = $node->language;

  if ($language_from == $language_to) {
    return;
  }

  # Collect data to translate
  $list = array();
  if ($title = strip_tags($node->title)) {
    $list[] = $title;
  }
  if ($body = strip_tags($node->field_description[0]['value'])) {
    $list[] = $body;
  }
  foreach ($node->choice as $choice) {
    if (!empty($choice['chtext'])) {
      $list[] = $choice['chtext'];
    }
    if (!empty($choice['chtext_short'])) {
      $list[] = $choice['chtext_short'];
    }
  }
  if (module_exists('poll_suggest')) {
    foreach ($node->choice_suggest as $choice) {
      if (!empty($choice['chtext'])) {
        $list[] = $choice['chtext'];
      }
    }
  }

  # Translate
  $translations = mstapi_exec($language_from, $language_to, $list);

  # put the translations to node
  $t['title'] = $translations[strip_tags($node->title)];
  $t['body'] = $translations[strip_tags($node->field_description[0]['value'])];
  foreach ($node->choice as $choice) {
    $t['choice'][$choice['chorder']] = $translations[$choice['chtext']];
    $t['choice_short'][$choice['chorder']] = $translations[$choice['chtext_short']];
  }
  if (module_exists('poll_suggest')) {
    foreach ($node->choice_suggest as $choice) {
      $t['choice_suggest'][$choice['chid']] = $translations[$choice['chtext']];
    }
  }

  node_save($node);
}

/**
 * @param $nid
 * @param $map
 */
function poll_translate_pollfix($nid, $map) {
  foreach ($map as $chorder => $data) {
    switch ($data['status']) {
      case 'deleted' :
        content_translate_del(array(
          'content_type' => 'node',
          'content_id' => $nid,
          'field' => 'choice',
          'field_order' => $chorder,
        ));
        content_translate_del(array(
          'content_type' => 'node',
          'content_id' => $nid,
          'field' => 'choice_short',
          'field_order' => $chorder,
        ));
      break;
      case 'updated' :
        $query = "
          UPDATE {content_translate}
          SET field_order = '%d'
          WHERE content_type = '%s' AND content_id = '%d' AND field = '%s' AND field_order = '%d'
        ";
        db_query($query, $data['index'], 'node', $nid, 'choice', $chorder);
        db_query($query, $data['index'], 'node', $nid, 'choice_short', $chorder);
      break;
    }
  }
}

/**
 * @param $node
 * @return array
 */
function poll_translate_translation($node) {
  # display language & translation
  global $language;
  return !empty($node->t[$language->language]) ? $node->t[$language->language] : array();
}

/**
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function poll_translate_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'poll_node_form') {
    global $language;
    $node = $form['#node'];

    if ($node->language != $language->language) {
      // choices count
      if (isset($form_state['choice_count'])) {
        $choice_count = $form_state['choice_count'];
      } else {
        $choice_count = max(2, empty($node->choice) ? 2 : count($node->choice));
      }
      // translations
      $translation = module_exists('poll_translate') ? poll_translate_translation($node) : array();
      //
      if (!empty($translation['title'][0])) {
//        $form['title']['#value_original'] = $form['title']['#value'];
        $form['title']['#value'] = check_plain($translation['title'][0]);
      }
      if (!empty($translation['body'][0])) {
//        $form['field_description'][0]['#default_value']['value_original'] = $form['field_description'][0]['#default_value']['value'];
        $form['field_description'][0]['#default_value']['value'] = check_plain($translation['body'][0]);
      }
      // Add the current choices to the form.
      for ($delta = 0; $delta < $choice_count; $delta++) {
        if (!empty($translation['choice'][$delta])) {
//          $form['choice_wrapper']['choice'][$delta]['chtext']['#value_original'] = $form['choice_wrapper']['choice'][$delta]['chtext']['#value'];
          $form['choice_wrapper']['choice'][$delta]['chtext']['#value'] = check_plain($translation['choice'][$delta]);
        }
      }
      // additional submit handler
      array_unshift($form['#submit'], 'poll_translate_node_form_submit');
      // TODO -- poll add more not working
      unset($form['choice_wrapper']['poll_more']);
    }
  }
}

/**
 * @param $form
 * @param $form_state
 */
function poll_translate_node_form_submit(&$form, &$form_state) {
  global $language;
  $node = $form['#node'];
  $values =  &$form_state['values'];
  // title
  content_translate_add('node', $node->nid, $language->language, 'title', $form['#post']['title']);
  $values['title'] = $node->title;
  // body
  content_translate_add('node', $node->nid, $language->language, 'body', $values['field_description'][0]['value']);
  $values['field_description'][0]['value'] = $node->field_description[0]['value'];
  // save translated values
  foreach ($form['choice_wrapper']['choice'] as $chorder => &$element) {
    if (!is_numeric($chorder)) continue;
    content_translate_add('node', $node->nid, $language->language, 'choice', $form['#post']['choice'][(int)$chorder]['chtext'], (int)$chorder);
  }
  // restore the default non-translated values
  if ($node->choice) {
    foreach ($node->choice as $chorder => $choice) {
      $values['choice'][$chorder]['chtext'] = $choice['chtext'];
    }
  }
}