<?php

/**
 * No form here. Just come along.
 *
 * @return array
 */
function user_login_modal_form() {
  $form = array();

  $form['#suffix'] = theme('user_login_modal_form_content');

  return $form;
}

/**
 * Implementation of hook_theme()
 *
 * @return array
 */
function user_login_modal_theme()
{
  $theme = array();

  $theme['user_login_modal_form_content'] = array(
    'arguments' => array(),
    'template' => 'user_login_modal',
  );

  $theme['user_login_modal'] = array(
    'arguments' => array(),
  );

  $theme['user_login_modal_class'] = array(
    'arguments' => array('force' => false),
  );

  return $theme;
}

/**
 * Access to the custom forms from colorbox/form path
 *
 * @param $form_id
 *
 * @return bool
 */
function user_login_modal_colorbox_form_access ($form_id) {
  return user_is_anonymous() && ('user_login_modal_form' == $form_id);
}

/**
 * Theme "user_login_modal"
 *
 * @return string
 */
function theme_user_login_modal()
{
  global $user;
  return '<p>
    <a id="dialog_link"
        class="ui-state-default ui-corner-all login ' . theme('user_login_modal_class') . '"
        href="'.(user_is_logged_in() ? '#' : url('user/login')).'"><i class="icon-user"></i><span>' .
    (user_is_logged_in() ? $user->name : t('Login')) .
    '</span></a></p>';
}

/**
 * @param bool $force
 * @return string
 */
function user_login_modal_class($force = false)
{
  return !$force && user_is_logged_in() ? '' : 'openlogin_box';
}

/**
 * @param bool $force
 * @return string
 */
function theme_user_login_modal_class($force = false)
{
  return user_login_modal_class($force);
}

/**
 * Implementation of hook_preprocess_page()
 *
 * @param $vars
 */
function user_login_modal_preprocess_page(&$vars)
{
  $vars['user_login_modal'] = theme('user_login_modal');

  // drupal_add_js('misc/ahah.js');
  drupal_add_js(drupal_get_path('module', 'user_login_modal') . '/user_login_modal.js');
  drupal_add_css(drupal_get_path('module', 'user_login_modal') . '/user_login_modal.css');

  $vars['styles'] = drupal_get_css();
  $vars['script'] = drupal_get_js();
}

/**
 * @param $vars
 */
function user_login_modal_form_alter(&$form, $form_state, $form_id)
{
  if ('colorbox' == arg(0) && 'form' == arg(1)) {
    if ('user_login' == $form_id || 'user_register' == $form_id) {
      $destination = isset($_GET["destination"]) ? $_GET["destination"] : $_SERVER["HTTP_REFERER"];
      $form['#action'] = $destination;
    }
  }
}
