<?php

/*
 * Implementation of hook_perm()
 */
function ranks_perm() {
  return array('Administer Ranks');
}

/*
 * Implementation of hook_menu()
 */
function ranks_menu() {
  $menu = array();

  # ranks menu edit
  $menu['admin/ranks'] = array(
    'title' => t('Ranks'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ranks_form'),
    'access arguments' => array('Administer Ranks'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'ranks.admin.inc',
  );

  return $menu;
}

/*
 * Get the list of ranks
 */
function ranks_get() {
  $ranks = array();
  $result = db_query('SELECT * FROM {module_ranks} ORDER BY points ASC');
  while( $rank = db_fetch_array($result) ) {
    $ranks[] = $rank;
  }
  if( empty($ranks) ) {
    $ranks[] = array('id' => 0, 'name' => 'Citizen', 'points' => 0);
  }
  return $ranks;
}

/*
 * Add the rank
 */
function rank_add($name, $points) {
  db_query("INSERT INTO {module_ranks} SET name = '%s', points = '%d'", $name, $points);
}

/*
 * Delete the rank
 */
function rank_delele($id) {
  db_query("DELETE FROM {module_ranks} WHERE id = '%d'", $id);
}

/*
 * Update the rank
 */
function rank_update($id, $name, $points) {
  db_query("UPDATE {module_ranks} SET name = '%s', points = '%d' WHERE id = '%d'", $name, $points, $id);
}

/*
 * Update users' ranks
 *
 * TODO -- move from user points to some nice place
 */
function users_ranks_update() {
  $ranks = ranks_get();
  for( $i = 0; $i < count($ranks); $i++ ) {
    if( $i == 0 ) {
      db_query("
        UPDATE {users} AS u
        SET u.id = '%d'
        WHERE (
          SELECT SUM(points)
          FROM {tbl_user_points} AS p
          WHERE p.uid = u.uid
        ) <= %d",
        $ranks[$i]['id'], $ranks[$i]['points']
      );
    } elseif( $i == count($ranks)-1 ) {
      db_query("
        UPDATE {users} AS u
        SET u.id = '%d'
        WHERE (
          SELECT SUM(points)
          FROM {tbl_user_points} AS p
          WHERE p.uid = u.uid
        ) >= %d",
        $ranks[$i]['id'], $ranks[$i]['points']
      );
    } else {
      db_query("
        UPDATE {users} AS u
        SET u.id = '%d'
        WHERE ( SELECT SUM(points) FROM {tbl_user_points} AS p WHERE p.uid = u.uid ) >".($i==1?'':'=')." %d AND
        WHERE ( SELECT SUM(points) FROM {tbl_user_points} AS p WHERE p.uid = u.uid ) < %d
      ", $ranks[$i]['id'], $ranks[$i-1]['points'], $ranks[$i]['points']
      );
    }
  }
}

/*
 * Update user's rank
 *
 * TODO
 */
function user_ranks_update($uid) {
  $user = user_load(array('uid' => $uid));
  $ranks = ranks_get();
  $user->id = $ranks[count($ranks)-1]['id'];
  $points = db_result(db_query("SELECT SUM(points) FROM {tbl_user_points} AS p WHERE p.uid = %d", $uid));
  for( $i = 0; $i < count($ranks); $i++ ) {
    if( $ranks[$i]['points'] > $points ) {
      $user->id = $ranks[$i == 0 ? 0 : $i-1 ]['id'];
      break;
    }
  }
  user_save($user);
}