<?php
/**
 * Implementation of hook_perm().
 */
function user_search_perm() {
  return array('Search User','Following','Follower','Suggested Users');
}


/**
 * Implementation of hook_menu().
 */
 
function user_search_menu() {	

$search_result['search'] = array(
    'title' => ' USER SEARCH RESULTS',
    'page callback' => 'search_results',
    'access arguments' => array('Search User'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );

$search_result['follower'] = array(
    'title' => 'Follower',
    'page callback' => 'user_follower',
    'access arguments' => array('Follower'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );

$search_result['following'] = array(
    'title' => ' Following',
    'page callback' => 'user_following',
    'access arguments' => array('Following'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );
  
  $search_result['suggest/follow'] = array(
    'title' => ' Suggested Users',
    'page callback' => 'suggest_follow',
    'access arguments' => array('Suggested Users'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );
  
  
  $search_result['savefollowing'] = array(
    'title' => ' Following',
    'page callback' => 'save_follow',
    'access arguments' => array('Following'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );
  
  
   $search_result['savefollower'] = array(
    'title' => ' Following',
    'page callback' => 'save_follower',
    'access arguments' => array('Following'),
    'type' => MENU_SUGGESTED_ITEM,
    'file' => 'user_search.pages.inc',
  );
  
  return $search_result;
}

