<?php

/**
 * Implementation of hook_badges()
 *
 * @return array
 */
function badges_poll_suggest_badges() {
  $badges = array();

  $badges['poll_suggest_bronze'] = array(
    'function' => 'badges_poll_suggest_check',
    'name'     => t('Suggest Answer'),
    'info'     => t('Suggesting answers to the questions'),
    'type'     => 'bronze',
  );

  return $badges;
}

/**
 * @param $uid
 *
 * @return bool
 */
function badges_poll_suggest_check($uid, $arguments = array()) {
  static $cache;

  if (is_null($cache)) {
    $cache = array();

    $result = db_query("SELECT uid, COUNT(*) count FROM {poll_suggest} GROUP BY uid");
    while ($row = db_fetch_array($result)) {
      $cache[$row['uid']] = $row['count'];
    }
  }

  return isset($cache[$uid]) ? $cache[$uid] > 0 : FALSE;
}
