<?php

function tester_boot() {
	
}

function tester_init() {
	
	
}  


function tester_menu() {
  return array(
    'tester' => array(
      'page callback' => 'tester',
      'type' => MENU_CALLBACK,
      'access callback' => true,
    ),
  );
}

function tester() {

  global $user;

//  $result = _profile_get_fields('hidden');
  $user = drupal_anonymous_user();
  $f = avatar_selection_get_random_image($user);
  var_dump($f);
//  rules_invoke_event('user_update', $user);

  exit;
}