<?php

function tester_boot() {
	
}

function tester_init() {
	
	
}  


function tester_menu() {
  return array(
    'tester' => array(
      'page callback' => 'tester',
      'type' => MENU_CALLBACK,
      'access callback' => true,
    ),
  );
}

function tester() {

  global $user;

//  $result = _profile_get_fields('hidden');
  $fields = variable_get(PROFILE_FIELDMAP, array());;
  var_dump($fields);
//  rules_invoke_event('user_update', $user);

  exit;
}