<?php

/**
 *
 */
define('BILL_FEEDS_PARAM', 'bill_feeds_url');
define('BILL_FEEDS_URL', variable_get(BILL_FEEDS_PARAM, 'http://www.govtrack.us/data/us/112/bills'));

/**
 * Implementation of hook_menu()
 *
 * @return array
 */
function bf_menu() {
  $menu = array();

  $menu['admin/settings/bill-feeds'] = array(
    'title' => t('Bill Feeds'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bf_admin_form'),
    'access arguments' => array('administer content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $menu;
}

/**
 * @return mixed
 */
function bf_admin_form() {
  $form = array();

  $form[BILL_FEEDS_PARAM] = array(
    '#type' => 'textfield',
    '#title' => t('Data Source URL'),
    '#default_value' => BILL_FEEDS_URL,
  );

  return system_settings_form($form);
}

/**
 * @return bool
 */
function bf_get_list() {
  set_time_limit(0);
  # make the request
  $result = drupal_http_request(BILL_FEEDS_URL);
  # error
  if (!$result->data) {
    return FALSE;
  }
  # data
  $data = $result->data;
  # fetch
  if (preg_match_all('/<a\s+href="([^\"]+.xml)"/', $data, $m)) {
    foreach ($m[0] as $i => $full) {
      bf_issue(BILL_FEEDS_URL.'/'.$m[1][$i]);
      break;
    }
  }
}

/**
 * @param $url
 */
function bf_issue($url) {
  $account = user_load(1);

  # get data
  if (false !== ($data = bf_get_feed($url))) {
    $doc = new DOMDocument();
    $doc->loadXML($data);

    // generic info
    $node = new stdClass();
    $node->type = 'poll';
    $node->language = 'en';
    $node->uid = $account->uid;
    $node->status = 1;
    $node->created = time();
    $node->changed = time();
    $node->comment = 0;
    $node->promote = 0;
    $node->moderate = 0;
    $node->sticky = 0;
    $node->tnid = 0;
    $node->translate = 0;
    $node->format = 0;
    $node->name = $account->name;
    $node->picture = $account->picture;
    $node->body = '';
    $node->choice = array();
    $node->field_arguments = array();
    $node->allowsuggestions = false;
    $node->taxonomy = array();

    // fetched info

    # title
    $title = $doc->getElementsByTagName('title');
    $titles = array();
    foreach ($title as $value) {
      $titles[$value->getAttribute('type')][] = $value->nodeValue;
    }
    $title = '';
    if (isset($titles['popular'])) {
      $title = $titles['popular'][0];
    } elseif (isset($titles['short'])) {
      $title = $titles['short'][0];
    } else {
      foreach ($titles as $type => $list) {
        foreach ($list as $item) {
          $title = $item;
          break 2;
        }
      }
    }
    if (!$title) {
      $title = $url;
    }
    $node->title = $title;

    # summary
    $summary = $doc->getElementsByTagName('summary');
    foreach ($summary as $value) {
      $summary = $value->nodeValue;
    }
    $node->field_description[0]['value'] = $summary;

    # terms
    foreach ($doc->getElementsByTagName('term') as $value) {
      $term = bf_term_by_name($value->getAttribute('name'));
      $node->taxonomy[ $term->tid ] = $term;
    }

    # choices
    $node->choice[] = array(
      'chtext' => 'Yay',
      'chvotes' => 0,
      'chorder' => 0,
    );
    $node->choice[] = array(
      'chtext' => 'Nay',
      'chvotes' => 0,
      'chorder' => 0,
    );

    # arguments
//    $node->field_arguments[] = array(
//      'nid' => '',
//    );

    // node_save($node);
    unset($node);

  }
}

/**
 * @param $url
 * @return bool
 */
function bf_get_feed($url) {
  # cache?
  if ($data = db_fetch_object(db_query("SELECT * FROM {bill_feeds} WHERE url = '%s'", $url))) {
    if ($data->nid) {
      return false;
    }
    $data = $data->content;
  }
  # request
  else {
    # make the request
    $result = drupal_http_request($url);
    # error
    if (!$result->data) {
      return FALSE;
    }
    # data
    $data = $result->data;
    # cache!
    db_query("REPLACE INTO {bill_feeds} SET url = '%s', content = '%s', date_added = '%s'",
      $url, $data, date("y-m-d H:i:s")
    );
  }

  return $data;
}

/**
 * @return bool
 */
function bf_term() {
  $terms = taxonomy_get_term_by_name('Bill Feeds');
  return $terms ? $terms[0] : false;
}

/**
 * @param $name
 * @return array
 */
function bf_term_by_name($name) {
  static $root_term, $root_term_children;

  if (is_null($root_term)) {
    $root_term = bf_term();
  }

  if (is_null($root_term_children)) {
    $root_term_children = taxonomy_get_children($root_term->tid, 0, 'name');
  }

  # get the term
  if (isset($root_term_children[$name])) {
    return $root_term_children[$name];
  } else {
    $term = array(
      'name' => $name,
      'vid' => $root_term->vid,
      'parent' => $root_term->tid,
    );
    taxonomy_save_term($term);
    return taxonomy_get_term($term['tid']);
  }
}