<?php

/**
 * Implementation of hook_badges()
 *
 * @return array
 */
function badges_argument_badges()
{
  $badges = array();

  $badges['argument_bronze'] = array(
    'function' => 'badges_argument_check',
    'name' => t('Conversation Piece'),
    'info' => t('Created a question that resulted in 20 debate posts or resource posts (including replies)'),
    'type' => 'bronze',
    'arguments' => array('count' => 20),
  );
  $badges['argument_silver'] = array(
    'function' => 'badges_argument_check',
    'name' => t('Cocktail Party'),
    'info' => t('Created a question that resulted in 50 debate posts or resource posts (including replies)'),
    'type' => 'silver',
    'arguments' => array('count' => 50),
  );
  $badges['argument_gold'] = array(
    'function' => 'badges_argument_check',
    'name' => t('Healthy Debate'),
    'info' => t('Created a question that resulted in 100 debate posts or resource posts (including replies)'),
    'type' => 'gold',
    'arguments' => array('count' => 100),
  );

  return $badges;
}

/**
 * @param $uid
 * @return bool
 */
function badges_argument_check($uid, $arguments = array())
{
  static $cache;

  if (is_null($cache)) {
    $cache = array();

    $result = db_query("
      SELECT n.uid, COUNT(DISTINCT(cfr.nid)) + COUNT(DISTINCT(c.cid)) count
      FROM {node} n
      INNER JOIN {content_field_reference} cfr ON cfr.field_reference_nid = n.nid
      LEFT JOIN {comments} c ON c.nid = cfr.nid
      GROUP BY n.nid");
    while ($row = db_fetch_array($result)) {
      if (!isset($cache[$row['uid']]) || ($cache[$row['uid']] < $row['count'])) {
        $cache[$row['uid']] = $row['count'];
      }
    }
  }

  return isset($cache[$uid]) ? $cache[$uid] >= $arguments['count'] : false;
}