<?php

function location_province_list_ee () {
	return array (
		"37" => t("Harju County"),
		"39" => t("Hiiu County"),
		"44" => t("Ida-Viru County"),
		"49" => t("Jogeva County"),
		"51" => t("Jarva County"),
		"57" => t("Laane County"),
		"59" => t("Laane-Viru County"),
		"65" => t("Polva County"),
		"67" => t("Parnu County"),
		"70" => t("Rapla County"),
		"74" => t("Saare County"),
		"78" => t("Tartu County"),
		"82" => t("Valga County"),
		"84" => t("Viljandi County"),
		"86" => t("Voru County"),
	);
}
