<?php

function location_province_list_mc () {
	return array (
		"CL" => t("La Colle"),
		"CO" => t("La Condamine"),
		"FO" => t("Fontvieille"),
		"GA" => t("La Gare"),
		"JE" => t("Jardin Exotique"),
		"LA" => t("Larvotto"),
		"MA" => t("Malbousquet"),
		"MC" => t("Monte-Carlo"),
		"MG" => t("Moneghetti"),
		"MO" => t("Monaco-Ville"),
		"MU" => t("Moulins"),
		"PH" => t("Port-Hercule"),
		"SD" => t("Sainte-Devote"),
		"SO" => t("La Source"),
		"SP" => t("Spelugues"),
		"SR" => t("Saint-Roman"),
		"VR" => t("Vallon de la Rousse"),
	);
}
