<?php

function location_province_list_it () {
	return array (
		"21" => t("Piedmont"),
		"23" => t("Regione Autonoma Valle d'Aosta"),
		"25" => t("Lombardy"),
		"32" => t("Regione Autonoma Trentino-Alto Adige"),
		"34" => t("Regione del Veneto"),
		"36" => t("Regione Autonoma Friuli-Venezia Giulia"),
		"42" => t("Regione Liguria"),
		"45" => t("Regione Emilia-Romagna"),
		"52" => t("Tuscany"),
		"55" => t("Regione Umbria"),
		"57" => t("Regione Marche"),
		"62" => t("Regione Lazio"),
		"65" => t("Regione Abruzzo"),
		"67" => t("Regione Molise"),
		"72" => t("Regione Campania"),
		"75" => t("Regione Puglia"),
		"77" => t("Regione Basilicata"),
		"78" => t("Regione Calabria"),
		"82" => t("Regione Autonoma Siciliana"),
		"88" => t("Regione Autonoma della Sardegna"),
	);
}
