<?php

function location_province_list_pl () {
	return array (
		"DS" => t("Dolnoslaskie"),
		"KP" => t("Kujawsko-Pomorskie"),
		"LB" => t("Lubuskie"),
		"LD" => t("Lodzkie"),
		"LU" => t("Lubelskie"),
		"MA" => t("Malopolskie"),
		"MZ" => t("Mazowieckie"),
		"OP" => t("Opolskie"),
		"PD" => t("Podlaskie"),
		"PK" => t("Podkarpackie"),
		"PM" => t("Pomorskie"),
		"SK" => t("Swietokrzyskie"),
		"SL" => t("Slaskie"),
		"WN" => t("Warminsko-Mazurskie"),
		"WP" => t("Wielkopolskie"),
		"ZP" => t("Zachodniopomorskie"),
	);
}
