<?php

function location_province_list_pt () {
	return array (
		"01" => t("Aveiro"),
		"02" => t("Beja"),
		"03" => t("Braga"),
		"04" => t("Braganca"),
		"05" => t("Castelo Branco"),
		"06" => t("Coimbra"),
		"07" => t("Evora"),
		"08" => t("Faro"),
		"09" => t("Guarda"),
		"10" => t("Leiria"),
		"11" => t("Lisboa"),
		"12" => t("Portalegre"),
		"13" => t("Porto"),
		"14" => t("Santarem"),
		"15" => t("Setubal"),
		"16" => t("Viana do Castelo"),
		"17" => t("Vila Real"),
		"18" => t("Viseu"),
		"20" => t("Acores (Azores)"),
		"30" => t("Madeira"),
	);
}
