<?php

function location_province_list_tn () {
	return array (
		"11" => t("Tunis"),
		"12" => t("L'Ariana"),
		"13" => t("Ben Arous"),
		"14" => t("La Manouba"),
		"21" => t("Nabeul"),
		"22" => t("Zaghouan"),
		"23" => t("Bizerte"),
		"31" => t("Beja"),
		"32" => t("Jendouba"),
		"33" => t("Le Kef"),
		"34" => t("Siliana"),
		"41" => t("Kairouan"),
		"42" => t("Kasserine"),
		"43" => t("Sidi Bouzid"),
		"51" => t("Sousse"),
		"52" => t("Monastir"),
		"53" => t("Mahdia"),
		"61" => t("Sfax"),
		"71" => t("Gafsa"),
		"72" => t("Tozeur"),
		"73" => t("Kebili"),
		"81" => t("Gabes"),
		"82" => t("Medenine"),
		"83" => t("Tataouine"),
	);
}
