<?php

function location_province_list_kp () {
	return array (
		"01" => t("P'yongyang Special City"),
		"02" => t("P'yongan-namdo"),
		"03" => t("P'yongan-bukto"),
		"04" => t("Chagang-do"),
		"05" => t("Hwanghae-namdo"),
		"06" => t("Hwanghae-bukto"),
		"07" => t("Kangwon-do"),
		"08" => t("Hamgyong-namdo"),
		"09" => t("Hamgyong-bukto"),
		"10" => t("Ryanggang-do (Yanggang-do)"),
		"13" => t("Nason (Najin-Sonbong)"),
	);
}
