<?php

function location_province_list_ua () {
	return array (
		"05" => t("Vinnytsya"),
		"07" => t("Volyn'"),
		"09" => t("Luhans'k"),
		"12" => t("Dnipropetrovs'k"),
		"14" => t("Donets'k"),
		"18" => t("Zhytomyr"),
		"21" => t("Zakarpattya"),
		"23" => t("Zaporizhzhya"),
		"26" => t("Ivano-Frankivs'k"),
		"30" => t("Kyyiv"),
		"32" => t("Kiev"),
		"35" => t("Kirovohrad"),
		"40" => t("Sevastopol"),
		"43" => t("Crimea"),
		"46" => t("L'viv"),
		"48" => t("Mykolayiv"),
		"51" => t("Odesa"),
		"53" => t("Poltava"),
		"56" => t("Rivne"),
		"59" => t("Sumy"),
		"61" => t("Ternopil'"),
		"63" => t("Kharkiv"),
		"65" => t("Kherson"),
		"68" => t("Khmel'nyts'kyy"),
		"71" => t("Cherkasy"),
		"74" => t("Chernihiv"),
		"77" => t("Chernivtsi"),
	);
}
