<?php

function location_province_list_my () {
	return array (
		"01" => t("Johor"),
		"02" => t("Kedah"),
		"03" => t("Kelantan"),
		"04" => t("Melaka"),
		"05" => t("Negeri Sembilan"),
		"06" => t("Pahang"),
		"07" => t("Pinang"),
		"08" => t("Perak"),
		"09" => t("Perlis"),
		"10" => t("Selangor"),
		"11" => t("Terengganu"),
		"12" => t("Sabah"),
		"13" => t("Sarawak"),
		"14" => t("Kuala Lumpur"),
		"15" => t("Labuan"),
		"16" => t("Putrajaya"),
	);
}
