<?php

function location_province_list_qa () {
	return array (
		"WA" => t("Al Wakrah"),
		"11" => t("Baladīyat Jarayān al Bāţinah"),
		"12" => t("Baladīyat Umm Sa‘īd"),
		"US" => t("Baladīyat Umm Şalāl"),
		"DA" => t("Baladīyat ad Dawḩah"),
		"02" => t("Baladīyat al Ghuwayrīyah"),
		"03" => t("Baladīyat al Jumaylīyah"),
		"KH" => t("Baladīyat al Khawr wa adh Dhakhīrah"),
		"RA" => t("Baladīyat ar Rayyān"),
		"MS" => t("Baladīyat ash Shamāl"),
		"13" => t("Baladīyat az̧ Z̧a‘āyin"),
	);
}
