<?php

function location_province_list_cz () {
	return array (
		"ST" => t("Central Bohemian Region"),
		"PR" => t("Hlavní město Praha"),
		"JC" => t("Jihočeský kraj"),
		"KA" => t("Karlovarský kraj"),
		"VY" => t("Kraj Vysočina"),
		"KR" => t("Královéhradecký kraj"),
		"LI" => t("Liberecký kraj"),
		"MO" => t("Moravskoslezský kraj"),
		"OL" => t("Olomoucký kraj"),
		"PA" => t("Pardubický kraj"),
		"PL" => t("Plzeňský kraj"),
		"JM" => t("South Moravian Region"),
		"ZL" => t("Zlínský kraj"),
		"US" => t("Ústecký kraj"),
	);
}
