<?php

function location_province_list_ca () {
	return array (
		"AB" => t("Alberta"),
		"BC" => t("British Columbia "),
		"MB" => t("Manitoba"),
		"NB" => t("New Brunswick"),
		"NL" => t("Newfoundland and Labrador"),
		"NS" => t("Nova Scotia"),
		"NT" => t("Northwest Territories"),
		"NU" => t("Nunavut"),
		"ON" => t("Ontario"),
		"PE" => t("Prince Edward Island"),
		"QC" => t("Quebec"),
		"SK" => t("Saskatchewan"),
		"YT" => t("Yukon Territory"),
	);
}
