<?php

function location_province_list_cf () {
	return array (
		"AC" => t("Ouham"),
		"BB" => t("Bamingui-Bangoran"),
		"BGF" => t("Bangui"),
		"BK" => t("Basse-Kotto"),
		"HK" => t("Haute-Kotto"),
		"HM" => t("Haut-Mbomou"),
		"HS" => t("Mambere-Kadei"),
		"KB" => t("Nana-Grebizi"),
		"KG" => t("Kemo"),
		"LB" => t("Lobaye"),
		"MB" => t("Mbomou"),
		"MP" => t("Ombella-M'Poko"),
		"NM" => t("Nana-Mambere"),
		"OP" => t("Ouham-Pende"),
		"SE" => t("Sangha-Mbaere"),
		"UK" => t("Ouaka"),
		"VK" => t("Vakaga"),
	);
}
