<?php

function location_province_list_me () {
	return array (
		"01" => t("Opstina Andrijevica"),
		"02" => t("Opstina Bar"),
		"03" => t("Opstina Berane"),
		"04" => t("Opstina Bijelo Polje"),
		"05" => t("Opstina Budva"),
		"06" => t("Opstina Cetinje"),
		"07" => t("Opstina Danilovgrad"),
		"08" => t("Opstina Herceg-Novi"),
		"09" => t("Opstina Kolasin"),
		"10" => t("Opstina Kotor"),
		"11" => t("Opstina Mojkovac"),
		"12" => t("Opstina Niksic"),
		"13" => t("Opstina Plav"),
		"14" => t("Opstina Pljevlja"),
		"15" => t("Opstina Pluzine"),
		"16" => t("Opstina Podgorica"),
		"17" => t("Opstina Rozaje"),
		"18" => t("Opstina Savnik"),
		"19" => t("Opstina Tivat"),
		"20" => t("Opstina Ulcinj"),
		"21" => t("Opstina Zabljak"),
	);
}
