<?php

function location_province_list_ly () {
	return array (
		"BA" => t("Banghazi"),
		"BU" => t("Al Butnan"),
		"DR" => t("Darnah"),
		"GT" => t("Ghat"),
		"JA" => t("Al Jabal al Akhdar"),
		"JG" => t("Al Jabal al Gharbi"),
		"JI" => t("Al Jifarah"),
		"JU" => t("Al Jufrah"),
		"KF" => t("Al Kufrah"),
		"MB" => t("Al Marqab"),
		"MI" => t("Misratah"),
		"MJ" => t("Al Maraj"),
		"MQ" => t("Murzuq"),
		"NL" => t("Nalut"),
		"NQ" => t("An Nuqat al Khams"),
		"SB" => t("Sabha"),
		"SR" => t("Surt"),
		"TB" => t("Tarabulus"),
		"WA" => t("Al Wah,at"),
		"WD" => t("Wadi al Hayat"),
		"WS" => t("Wadi ash Shati´"),
		"ZA" => t("Az Zawiyah"),
	);
}
