<?php

function location_province_list_es () {
	return array (
		"AN" => t("Comunidad Autonoma de Andalucia"),
		"AR" => t("Comunidad Autonoma de Aragon"),
		"AS" => t("Comunidad Autonoma del Principado de Asturias"),
		"CB" => t("Comunidad Autonoma de Cantabria"),
		"CE" => t("Ceuta"),
		"CL" => t("Comunidad Autonoma de Castilla y Leon"),
		"CM" => t("Comunidad Autonoma de Castilla-La Mancha"),
		"CN" => t("Comunidad Autonoma de Canarias"),
		"CT" => t("Catalunya"),
		"EX" => t("Comunidad Autonoma de Extremadura"),
		"GA" => t("Comunidad Autonoma de Galicia"),
		"IB" => t("Comunidad Autonoma de las Islas Baleares"),
		"MC" => t("Comunidad Autonoma de la Region de Murcia"),
		"MD" => t("Comunidad de Madrid"),
		"ML" => t("Melilla"),
		"NC" => t("Comunidad Foral de Navarra"),
		"PV" => t("Euskal Autonomia Erkidegoa"),
		"RI" => t("Comunidad Autonoma de La Rioja"),
		"VC" => t("Comunidad Valenciana"),
	);
}
