<?php

function location_province_list_om () {
	return array (
		"SH" => t("Ash Sharqiyah South"),
		"ZA" => t("Az̧ Z̧āhirah"),
		"MU" => t("Musandam"),
		"BA" => t("Muḩāfaz̧at Janūb al Bāţinah"),
		"MA" => t("Muḩāfaz̧at Masqaţ"),
		"11" => t("Muḩāfaz̧at Shamāl al Bāţinah"),
		"12" => t("Muḩāfaz̧at Shamāl ash Sharqīyah"),
		"ZU" => t("Muḩāfaz̧at Z̧ufār"),
		"DA" => t("Muḩāfaz̧at ad Dākhilīyah"),
		"BU" => t("Muḩāfaz̧at al Buraymī"),
		"WU" => t("Muḩāfaz̧at al Wusţá"),
	);
}
