<?php

function location_province_list_kh () {
	return array (
		"1" => t("Banteay Mean Choay"),
		"10" => t("Kratie"),
		"11" => t("Mondul Kiri"),
		"12" => t("Phnom Penh"),
		"13" => t("Preah Vihear"),
		"14" => t("Prey Veng"),
		"15" => t("Pursat"),
		"16" => t("Rotanokiri"),
		"17" => t("Siemreap"),
		"18" => t("Preah Seihanu (Kompong Som or Sihanoukville)"),
		"19" => t("Stung Treng"),
		"2" => t("Battambang"),
		"20" => t("Svay Rieng"),
		"21" => t("Takeo"),
		"22" => t("Otdar Mean Choay"),
		"23" => t("Keb"),
		"24" => t("Pailin"),
		"3" => t("Kampong Cham"),
		"4" => t("Kampong Chhnang"),
		"5" => t("Kampong Speu"),
		"6" => t("Kampong Thom"),
		"7" => t("Kampot"),
		"8" => t("Kandal"),
		"9" => t("Kaoh Kong"),
	);
}
