<?php

function location_province_list_ma () {
	return array (
		"01" => t("Tanger-Tetouan"),
		"02" => t("Gharb-Chrarda-Beni Hssen"),
		"03" => t("Taza-Al Hoceima-Taounate"),
		"04" => t("Oriental"),
		"05" => t("Fes-Boulemane"),
		"06" => t("Meknes-Tafilalet"),
		"07" => t("Rabat-Sale-Zemmour-Zaer"),
		"08" => t("Grand Casablanca"),
		"09" => t("Chaouia-Ouardigha"),
		"10" => t("Doukkala-Abda"),
		"11" => t("Marrakech-Tensift-Al Haouz"),
		"12" => t("Tadla-Azilal"),
		"13" => t("Souss-Massa-Draa"),
		"14" => t("Guelmim-Es Smara"),
		"15" => t("Laayoune-Boujdour-Sakia El Hamra"),
		"16" => t("Oued ed Dahab-Lagouira"),
	);
}
