<?php

function location_province_list_se () {
	return array (
		"AB" => t("Stockholms"),
		"AC" => t("Vasterbottens"),
		"BD" => t("Norrbottens"),
		"C" => t("Uppsala"),
		"D" => t("Sodermanlands"),
		"E" => t("Ostergotlands"),
		"F" => t("Jonkopings"),
		"G" => t("Kronobergs"),
		"H" => t("Kalmar"),
		"I" => t("Gotlands"),
		"K" => t("Blekinge"),
		"M" => t("Skane"),
		"N" => t("Hallands"),
		"O" => t("Vastra Gotaland"),
		"S" => t("Varmlands"),
		"T" => t("Orebro"),
		"U" => t("Vastmanlands"),
		"W" => t("Dalarna"),
		"X" => t("Gavleborgs"),
		"Y" => t("Vasternorrlands"),
		"Z" => t("Jamtlands"),
	);
}
