<?php

function location_province_list_pw () {
	return array (
		"002" => t("Aimeliik"),
		"004" => t("Airai"),
		"010" => t("Angaur"),
		"050" => t("Hatohobei"),
		"100" => t("Kayangel"),
		"150" => t("Koror"),
		"212" => t("Melekeok"),
		"214" => t("Ngaraard"),
		"218" => t("Ngarchelong"),
		"222" => t("Ngardmau"),
		"224" => t("Ngatpang"),
		"226" => t("Ngchesar"),
		"227" => t("Ngeremlengui"),
		"228" => t("Ngiwal"),
		"350" => t("Peleliu"),
		"370" => t("Sonsorol"),
	);
}
