<?php

function location_province_list_so () {
	return array (
		"AW" => t("Awdal"),
		"BK" => t("Bakool"),
		"BN" => t("Banaadir"),
		"BR" => t("Bari"),
		"BY" => t("Bay"),
		"GA" => t("Galguduud"),
		"GE" => t("Gedo"),
		"HI" => t("Hiiraan"),
		"JD" => t("Jubbada Dhexe"),
		"JH" => t("Jubbada Hoose"),
		"MU" => t("Mudug"),
		"NU" => t("Nugaal"),
		"SA" => t("Sanaag"),
		"SD" => t("Shabeellaha Dhexe"),
		"SH" => t("Shabeellaha Hoose"),
		"SO" => t("Sool"),
		"TO" => t("Togdheer"),
		"WO" => t("Woqooyi Galbeed"),
	);
}
