<?php

function location_province_list_ci () {
	return array (
		"01" => t("Lagunes (Region des)"),
		"02" => t("Haut-Sassandra (Region du)"),
		"03" => t("Savanes (Region des)"),
		"04" => t("Vallee du Bandama (Region de la)"),
		"05" => t("Moyen-Comoe (Region du)"),
		"06" => t("18 Montagnes (Region des)"),
		"07" => t("Lacs (Region des)"),
		"08" => t("Zanzan (Region du)"),
		"09" => t("Bas-Sassandra (Region du)"),
		"10" => t("Denguele (Region du)"),
		"11" => t("Nzi-Comoe (Region)"),
		"12" => t("Marahoue (Region de la)"),
		"13" => t("Sud-Comoe (Region du)"),
		"14" => t("Worodougou (Region du)"),
		"15" => t("Sud-Bandama (Region du)"),
		"16" => t("Agnebi (Region de l')"),
		"17" => t("Bafing (Region du)"),
		"18" => t("Fromager (Region du)"),
		"19" => t("Moyen-Cavally (Region du)"),
	);
}
