<?php

function location_province_list_kz () {
	return array (
		"AKT" => t("Aktyubinskaya Oblast’"),
		"ALM" => t("Almaty Oblysy"),
		"ALA" => t("Almaty Qalasy"),
		"AKM" => t("Aqmola Oblysy"),
		"AST" => t("Astana Qalasy"),
		"ATY" => t("Atyraū Oblysy"),
		"ZAP" => t("Batys Qazaqstan Oblysy"),
		"BAY" => t("Bayqongyr Qalasy"),
		"VOS" => t("East Kazakhstan"),
		"MAN" => t("Mangistauskaya Oblast’"),
		"PAV" => t("Pavlodar Oblysy"),
		"KAR" => t("Qaraghandy Oblysy"),
		"KUS" => t("Qostanay Oblysy"),
		"KZY" => t("Qyzylorda Oblysy"),
		"SEV" => t("Severo-Kazakhstanskaya Oblast’"),
		"YUZ" => t("Yuzhno-Kazakhstanskaya Oblast’"),
		"ZHA" => t("Zhambyl Oblysy"),
	);
}
