<?php

function location_province_list_sc () {
	return array (
		"02" => t("Anse Boileau"),
		"03" => t("Anse Etoile"),
		"05" => t("Anse Royale"),
		"01" => t("Anse aux Pins"),
		"04" => t("Au Cap"),
		"06" => t("Baie Lazare"),
		"07" => t("Baie Sainte Anne"),
		"08" => t("Beau Vallon"),
		"09" => t("Bel Air"),
		"10" => t("Bel Ombre"),
		"11" => t("Cascade"),
		"16" => t("English River"),
		"12" => t("Glacis"),
		"13" => t("Grand Anse Mahe"),
		"14" => t("Grand Anse Praslin"),
		"15" => t("Inner Islands"),
		"24" => t("Les Mamelles"),
		"17" => t("Mont Buxton"),
		"18" => t("Mont Fleuri"),
		"19" => t("Plaisance"),
		"20" => t("Pointe Larue"),
		"21" => t("Port Glaud"),
		"25" => t("Roche Caiman"),
		"22" => t("Saint Louis"),
		"23" => t("Takamaka"),
	);
}
