<?php

function location_province_list_dm () {
	return array (
		"02" => t("Saint Andrew Parish"),
		"03" => t("Saint David Parish"),
		"04" => t("Saint George Parish"),
		"05" => t("Saint John Parish"),
		"06" => t("Saint Joseph Parish"),
		"07" => t("Saint Luke Parish"),
		"08" => t("Saint Mark Parish"),
		"09" => t("Saint Patrick Parish"),
		"10" => t("Saint Paul Parish"),
		"11" => t("Saint Peter Parish"),
	);
}
