<?php

function location_province_list_ga () {
	return array (
		"1" => t("Estuaire"),
		"4" => t("Province de la Ngounié"),
		"5" => t("Province de la Nyanga"),
		"6" => t("Province de l’ Ogooué-Ivindo"),
		"7" => t("Province de l’ Ogooué-Lolo"),
		"8" => t("Province de l’ Ogooué-Maritime"),
		"2" => t("Province du Haut-Ogooué"),
		"3" => t("Province du Moyen-Ogooué"),
		"9" => t("Province du Woleu-Ntem"),
	);
}
