<?php

function location_province_list_bf () {
	return array (
		"01" => t("Boucle du Mouhoun"),
		"02" => t("Cascades"),
		"03" => t("Centre"),
		"04" => t("Centre-Est"),
		"05" => t("Centre-Nord"),
		"06" => t("Centre-Ouest"),
		"07" => t("Centre-Sud"),
		"08" => t("Est"),
		"09" => t("Hauts-Bassins"),
		"10" => t("Nord"),
		"11" => t("Plateau-Central"),
		"12" => t("Sahel"),
		"13" => t("Sud-Ouest"),
	);
}
