<?php

function location_province_list_tt () {
	return array (
		"ARI" => t("Arima"),
		"CHA" => t("Chaguanas"),
		"CTT" => t("Couva/Tabaquite/Talparo"),
		"DMN" => t("Diego Martin"),
		"ETO" => t("Eastern Tobago"),
		"PED" => t("Penal/Debe"),
		"POS" => t("Port of Spain"),
		"PRT" => t("Princes Town"),
		"PTF" => t("Point Fortin"),
		"RCM" => t("Mayaro/Rio Claro"),
		"SFO" => t("San Fernando"),
		"SGE" => t("Sangre Grande"),
		"SIP" => t("Siparia"),
		"SJL" => t("San Juan/Laventille"),
		"TUP" => t("Tunapuna/Piarco"),
		"WTO" => t("Tobago"),
	);
}
