<?php

function location_province_list_pg () {
	return array (
		"CPK" => t("Chimbu"),
		"CPM" => t("Central"),
		"EBR" => t("East New Britain"),
		"EHG" => t("Eastern Highlands"),
		"EPW" => t("Enga"),
		"ESW" => t("East Sepik"),
		"GPK" => t("Gulf"),
		"MBA" => t("Milne Bay"),
		"MPL" => t("Morobe"),
		"MPM" => t("Madang"),
		"MRL" => t("Manus"),
		"NCD" => t("National Capital"),
		"NIK" => t("New Ireland"),
		"NPP" => t("Northern"),
		"NSA" => t("Bougainville"),
		"SAN" => t("Sandaun"),
		"SHM" => t("Southern Highlands"),
		"WBK" => t("West New Britain"),
		"WHM" => t("Western Highlands"),
		"WPD" => t("Western"),
	);
}
