<?php

function location_province_list_kz () {
	return array (
		"AKM" => t("Aqmola"),
		"AKT" => t("Aqtobe"),
		"ALA" => t("Almaty"),
		"ALM" => t("Almaty"),
		"AST" => t("Astana"),
		"ATY" => t("Atyrau"),
		"BAY" => t("Baykonyr"),
		"KAR" => t("Qaraghandy"),
		"KUS" => t("Qustanay"),
		"KZY" => t("Qyzylorda"),
		"MAN" => t("Mangghystau"),
		"PAV" => t("Paylodar"),
		"SEV" => t("Soltustik Qazaqstan "),
		"VOS" => t("Shyghys Qazaqstan "),
		"YUZ" => t("Ongtustik Qazaqstan"),
		"ZAP" => t("Baty Qazaqstan"),
		"ZHA" => t("Zhambyl"),
	);
}
