<?php

function location_province_list_fi () {
	return array (
		"01" => t("Ahvenanmaa [Finnish] / Aland [Swedish]"),
		"02" => t("Etela-Karjala [Finnish] / Sodra Karelen [Swedish]"),
		"03" => t("Etela-Pohjanmaa [Finnish] / Sodra Osterbotten [Swedish]"),
		"04" => t("Etela-Savo [Finnish] / Sodra Savolax [Swedish]"),
		"05" => t("Kainuu [Finnish] / Kajanaland [Swedish]"),
		"06" => t("Kanta-Hame [Finnish] / Egentliga Tavastland [Swedish]"),
		"07" => t("Keski-Pohjanmaa [Finnish] / Mellersta Osterbotten [Swedish]"),
		"08" => t("Keski-Suomi [Finnish] / Mellersta Finland [Swedish]"),
		"09" => t("Kymenlaakso [Finnish] / Kymmenedalen [Swedish]"),
		"10" => t("Lappi [Finnish] / Lappland [Swedish]"),
		"11" => t("Pirkanmaa [Finnish] / Birkaland [Swedish]"),
		"12" => t("Pohjanmaa [Finnish] / Osterbotten [Swedish]"),
		"13" => t("Pohjois-Karjala [Finnish] / Norra Karelen [Swedish]"),
		"14" => t("Pohjois-Pohjanmaa [Finnish] / Norra Osterbotten [Swedish]"),
		"15" => t("Pohjois-Savo [Finnish] / Norra Savolax [Swedish]"),
		"16" => t("Paijat-Hame [Finnish] / Paijanne-Tavastland [Swedish]"),
		"17" => t("Satakunta [Finnish and Swedish]"),
		"18" => t("Uusimaa [Finnish] / Nyland [Swedish]"),
		"19" => t("Varsinais-Suomi [Finnish] / Egentliga Finland [Swedish]"),
		"AL" => t("Ahvenanmaan laani"),
		"ES" => t("Etela-Suomen laani"),
		"IS" => t("Ita-Suomen laani"),
		"LL" => t("Lapin laani"),
		"LS" => t("Lansi-Suomen laani"),
		"OL" => t("Oulun laani"),
	);
}
