<?php

function location_province_list_mm () {
	return array (
		"01" => t("Sagaing"),
		"02" => t("Bago"),
		"03" => t("Magway"),
		"04" => t("Mandalay"),
		"05" => t("Tanintharyi"),
		"06" => t("Yangon"),
		"07" => t("Ayeyarwady"),
		"11" => t("Kachin State"),
		"12" => t("Kayah State"),
		"13" => t("Kayin State"),
		"14" => t("Chin State"),
		"15" => t("Mon State"),
		"16" => t("Rakhine State"),
		"17" => t("Shan State"),
	);
}
