<?php

function location_province_list_gt () {
	return array (
		"AV" => t("Alta Verapaz"),
		"BV" => t("Baja Verapaz"),
		"CM" => t("Chimaltenango"),
		"CQ" => t("Chiquimula"),
		"ES" => t("Escuintla"),
		"GU" => t("Guatemala"),
		"HU" => t("Huehuetenango"),
		"IZ" => t("Izabal"),
		"JA" => t("Jalapa"),
		"JU" => t("Jutiapa"),
		"PE" => t("El Peten"),
		"PR" => t("El Progreso"),
		"QC" => t("El Quiche"),
		"QZ" => t("Quetzaltenango"),
		"RE" => t("Retalhuleu"),
		"SA" => t("Sacatepequez"),
		"SM" => t("San Marcos"),
		"SO" => t("Solola"),
		"SR" => t("Santa Rosa"),
		"SU" => t("Suchitepequez"),
		"TO" => t("Totonicapan"),
		"ZA" => t("Zacapa"),
	);
}
