<?php

function location_province_list_sa () {
	return array (
		"01" => t("Ar Riyad"),
		"02" => t("Makkah"),
		"03" => t("Al Madinah"),
		"04" => t("Ash Sharqiyah (Eastern Province)"),
		"05" => t("Al Qasim"),
		"06" => t("Ha'il"),
		"07" => t("Tabuk"),
		"08" => t("Al Hudud ash Shamaliyah"),
		"09" => t("Jizan"),
		"10" => t("Najran"),
		"11" => t("Al Bahah"),
		"12" => t("Al Jawf"),
		"14" => t("'Asir"),
	);
}
