<?php

function location_province_list_gy () {
	return array (
		"BA" => t("Barima-Waini"),
		"CU" => t("Cuyuni-Mazaruni"),
		"DE" => t("Demerara-Mahaica"),
		"EB" => t("East Berbice-Corentyne"),
		"ES" => t("Essequibo Islands-West Demerara"),
		"MA" => t("Mahaica-Berbice"),
		"PM" => t("Pomeroon-Supenaam"),
		"PT" => t("Potaro-Siparuni"),
		"UD" => t("Upper Demerara-Berbice"),
		"UT" => t("Upper Takutu-Upper Essequibo"),
	);
}
