<?php

function location_province_list_bt () {
	return array (
		"11" => t("Paro"),
		"12" => t("Chukha"),
		"13" => t("Haa"),
		"14" => t("Samtse"),
		"15" => t("Thimphu"),
		"21" => t("Tsirang"),
		"22" => t("Dagana"),
		"23" => t("Punakha"),
		"24" => t("Wangdue Phodrang"),
		"31" => t("Sarpang"),
		"32" => t("Trongsa"),
		"33" => t("Bumthang"),
		"34" => t("Zhemgang"),
		"41" => t("Trashigang"),
		"42" => t("Mongar"),
		"43" => t("Pemagatshel"),
		"44" => t("Lhuntse"),
		"45" => t("Samdrup Jongkhar"),
		"GA" => t("Gasa"),
		"TY" => t("Trashi Yangste"),
	);
}
