<?php

function location_province_list_hn () {
	return array (
		"AT" => t("Atlantida"),
		"CH" => t("Choluteca"),
		"CL" => t("Colon"),
		"CM" => t("Comayagua"),
		"CP" => t("Copan"),
		"CR" => t("Cortes"),
		"EP" => t("El Paraiso"),
		"FM" => t("Francisco Morazan"),
		"GD" => t("Gracias a Dios"),
		"IB" => t("Islas de la Bahia (Bay Islands)"),
		"IN" => t("Intibuca"),
		"LE" => t("Lempira"),
		"LP" => t("La Paz"),
		"OC" => t("Ocotepeque"),
		"OL" => t("Olancho"),
		"SB" => t("Santa Barbara"),
		"VA" => t("Valle"),
		"YO" => t("Yoro"),
	);
}
