<?php

function location_province_list_bi () {
	return array (
		"BB" => t("Bubanza"),
		"BL" => t("Bujumbura Rural"),
		"BM" => t("Bujumbura Mairie"),
		"BR" => t("Bururi"),
		"CA" => t("Cankuzo"),
		"CI" => t("Cibitoke"),
		"GI" => t("Gitega"),
		"KI" => t("Kirundo"),
		"KR" => t("Karuzi"),
		"KY" => t("Kayanza"),
		"MA" => t("Makamba"),
		"MU" => t("Muramvya"),
		"MW" => t("Mwaro"),
		"MY" => t("Muyinga"),
		"NG" => t("Ngozi"),
		"RT" => t("Rutana"),
		"RY" => t("Ruyigi"),
	);
}
