<?php

function location_province_list_sd () {
	return array (
		"DC" => t("Wasat Darfur"),
		"DE" => t("Sharq Darfur"),
		"DN" => t("Shamal Darfur"),
		"DS" => t("Janub Darfur"),
		"DW" => t("Gharb Darfur"),
		"GD" => t("Al Qadarif"),
		"GZ" => t("Al Jazirah"),
		"KA" => t("Kassala"),
		"KH" => t("Al Khartum"),
		"KN" => t("Shamal Kurdufan"),
		"KS" => t("Janub Kurdufan"),
		"NB" => t("An Nil al Azraq"),
		"NO" => t("Ash Shamaliyah"),
		"NR" => t("An Nil"),
		"NW" => t("An Nil al Abyad"),
		"RS" => t("Al Bahr al Ahmar"),
		"SI" => t("Sinnar"),
	);
}
