<?php

function location_province_list_tz () {
	return array (
		"01" => t("Arusha"),
		"02" => t("Dar es Salaam"),
		"03" => t("Dodoma"),
		"04" => t("Iringa"),
		"05" => t("Kagera"),
		"06" => t("Pemba North"),
		"07" => t("Zanzibar North"),
		"08" => t("Kigoma"),
		"09" => t("Kilimanjaro"),
		"10" => t("Pemba South"),
		"11" => t("Zanzibar Central/South"),
		"12" => t("Lindi"),
		"13" => t("Mara"),
		"14" => t("Mbeya"),
		"15" => t("Zanzibar Urban/West"),
		"16" => t("Morogoro"),
		"17" => t("Mtwara"),
		"18" => t("Mwanza"),
		"19" => t("Pwani"),
		"20" => t("Rukwa"),
		"21" => t("Ruvuma"),
		"22" => t("Shinyanga"),
		"23" => t("Singida"),
		"24" => t("Tabora"),
		"25" => t("Tanga"),
		"26" => t("Manyara"),
	);
}
