<?php

function location_province_list_hr () {
	return array (
		"07" => t("Bjelovarsko-Bilogorska Županija"),
		"12" => t("Brodsko-Posavska Županija"),
		"19" => t("Dubrovačko-Neretvanska Županija"),
		"21" => t("Grad Zagreb"),
		"18" => t("Istarska Županija"),
		"04" => t("Karlovačka Županija"),
		"06" => t("Koprivničko-Križevačka Županija"),
		"02" => t("Krapinsko-Zagorska Županija"),
		"09" => t("Ličko-Senjska Županija"),
		"20" => t("Međimurska Županija"),
		"14" => t("Osječko-Baranjska Županija"),
		"11" => t("Požeško-Slavonska Županija"),
		"08" => t("Primorsko-Goranska Županija"),
		"03" => t("Sisačko-Moslavačka Županija"),
		"17" => t("Splitsko-Dalmatinska Županija"),
		"05" => t("Varaždinska Županija"),
		"10" => t("Virovitičko-Podravska Županija"),
		"16" => t("Vukovarsko-Srijemska Županija"),
		"13" => t("Zadarska Županija"),
		"01" => t("Zagreb County"),
		"15" => t("Šibensko-Kninska Županija"),
	);
}
