<?php

function location_province_list_ch () {
	return array (
		"AG" => t("Aargau"),
		"AR" => t("Appenzell Ausserrhoden"),
		"BS" => t("Basel-City"),
		"BL" => t("Basel-Landschaft"),
		"BE" => t("Bern"),
		"FR" => t("Fribourg"),
		"GE" => t("Geneva"),
		"GL" => t("Glarus"),
		"GR" => t("Grisons"),
		"JU" => t("Jura"),
		"AI" => t("Kanton Appenzell Innerrhoden"),
		"LU" => t("Lucerne"),
		"NE" => t("Neuchâtel"),
		"NW" => t("Nidwalden"),
		"OW" => t("Obwalden"),
		"SG" => t("Saint Gallen"),
		"SH" => t("Schaffhausen"),
		"SZ" => t("Schwyz"),
		"SO" => t("Solothurn"),
		"TG" => t("Thurgau"),
		"TI" => t("Ticino"),
		"UR" => t("Uri"),
		"VS" => t("Valais"),
		"VD" => t("Vaud"),
		"ZG" => t("Zug"),
		"ZH" => t("Zurich"),
	);
}
