<?php

function location_province_list_uy () {
	return array (
		"AR" => t("Artigas"),
		"CA" => t("Canelones"),
		"CL" => t("Cerro Largo"),
		"CO" => t("Colonia"),
		"DU" => t("Durazno"),
		"FD" => t("Florida"),
		"FS" => t("Flores"),
		"LA" => t("Lavalleja"),
		"MA" => t("Maldonado"),
		"MO" => t("Montevideo"),
		"PA" => t("Paysandu"),
		"RN" => t("Rio Negro"),
		"RO" => t("Rocha"),
		"RV" => t("Rivera"),
		"SA" => t("Salto"),
		"SJ" => t("San Jose"),
		"SO" => t("Soriano"),
		"TA" => t("Tacuarembo"),
		"TT" => t("Treinta y Tres"),
	);
}
