<?php

function location_province_list_cu () {
	return array (
		"01" => t("Pinar del Rio"),
		"03" => t("La Habana"),
		"04" => t("Matanzas"),
		"05" => t("Villa Clara"),
		"06" => t("Cienfuegos"),
		"07" => t("Sancti Spiritus"),
		"08" => t("Ciego de Avila"),
		"09" => t("Camaguey"),
		"10" => t("Las Tunas"),
		"11" => t("Holguin"),
		"12" => t("Granma"),
		"13" => t("Santiago de Cuba"),
		"14" => t("Guantanamo"),
		"99" => t("Isla de la Juventud"),
		"02" => t("La Habana"),
	);
}
