<?php

function location_province_list_ao () {
	return array (
		"BGO" => t("Bengo"),
		"BGU" => t("Benguela province"),
		"BIE" => t("Bie"),
		"CAB" => t("Cabinda"),
		"CCU" => t("Cuando-Cubango"),
		"CNN" => t("Cunene"),
		"CNO" => t("Cuanza Norte"),
		"CUS" => t("Cuanza Sul"),
		"HUA" => t("Huambo province"),
		"HUI" => t("Huila province"),
		"LNO" => t("Lunda Norte"),
		"LSU" => t("Lunda Sul"),
		"LUA" => t("Luanda"),
		"MAL" => t("Malange"),
		"MOX" => t("Moxico"),
		"NAM" => t("Namibe"),
		"UIG" => t("Uige"),
		"ZAI" => t("Zaire"),
	);
}
