<?php

function location_province_list_sn () {
	return array (
		"DB" => t("Diourbel"),
		"DK" => t("Dakar"),
		"FK" => t("Fatick"),
		"KA" => t("Kaffrine"),
		"KD" => t("Kolda"),
		"KE" => t("Kedougou"),
		"KL" => t("Kaolack"),
		"LG" => t("Louga"),
		"MT" => t("Matam"),
		"SE" => t("Sedhiou"),
		"SL" => t("Saint-Louis"),
		"TC" => t("Tambacounda"),
		"TH" => t("Thies "),
		"ZG" => t("Ziguinchor"),
	);
}
