<?php

function location_province_list_de () {
	return array (
		"BB" => t("Brandenburg"),
		"BE" => t("Berlin"),
		"BW" => t("Baden-Wurttemberg"),
		"BY" => t("Bayern"),
		"HB" => t("Bremen"),
		"HE" => t("Hessen"),
		"HH" => t("Hamburg"),
		"MV" => t("Mecklenburg-Vorpommern"),
		"NI" => t("Niedersachsen"),
		"NW" => t("Nordrhein-Westfalen"),
		"RP" => t("Rheinland-Pfalz"),
		"SH" => t("Schleswig-Holstein"),
		"SL" => t("Saarland"),
		"SN" => t("Sachsen"),
		"ST" => t("Sachsen-Anhalt"),
		"TH" => t("Thuringen"),
	);
}
