<?php

function location_province_list_mu () {
	return array (
		"AG" => t("Agalega Islands"),
		"BL" => t("Black River"),
		"BR" => t("Beau Bassin-Rose Hill"),
		"CC" => t("Cargados Carajos Shoals (Saint Brandon Islands)"),
		"CU" => t("Curepipe"),
		"FL" => t("Flacq"),
		"GP" => t("Grand Port"),
		"MO" => t("Moka"),
		"PA" => t("Pamplemousses"),
		"PL" => t("Port Louis"),
		"PU" => t("Port Louis"),
		"PW" => t("Plaines Wilhems"),
		"QB" => t("Quatre Bornes"),
		"RO" => t("Rodrigues"),
		"RR" => t("Riviere du Rempart"),
		"SA" => t("Savanne"),
		"VP" => t("Vacoas-Phoenix"),
	);
}
