<?php

function location_province_list_ni () {
	return array (
		"AN" => t("Region Autonoma del Atlantico Norte"),
		"AS" => t("Region Autonoma del Atlantico Sur"),
		"BO" => t("Boaco"),
		"CA" => t("Carazo"),
		"CI" => t("Chinandega"),
		"CO" => t("Chontales"),
		"ES" => t("Esteli"),
		"GR" => t("Granada"),
		"JI" => t("Jinotega"),
		"LE" => t("Leon"),
		"MD" => t("Madriz"),
		"MN" => t("Managua"),
		"MS" => t("Masaya"),
		"MT" => t("Matagalpa"),
		"NS" => t("Nueva Segovia"),
		"RI" => t("Rivas"),
		"SJ" => t("Rio San Juan"),
	);
}
