<?php

function location_province_list_uy () {
	return array (
		"AR" => t("Artigas"),
		"CA" => t("Canelones"),
		"CL" => t("Cerro Largo"),
		"CO" => t("Colonia"),
		"DU" => t("Departamento de Durazno"),
		"FS" => t("Departamento de Flores"),
		"MO" => t("Departamento de Montevideo"),
		"PA" => t("Departamento de Paysandú"),
		"RV" => t("Departamento de Rivera"),
		"RO" => t("Departamento de Rocha"),
		"RN" => t("Departamento de Río Negro"),
		"SA" => t("Departamento de Salto"),
		"SJ" => t("Departamento de San José"),
		"TA" => t("Departamento de Tacuarembó"),
		"TT" => t("Departamento de Treinta y Tres"),
		"FD" => t("Florida"),
		"LA" => t("Lavalleja"),
		"MA" => t("Maldonado"),
		"SO" => t("Soriano"),
	);
}
