<?php
function openids_perm() {

  return array('Login','Facebook Friends');

} // function newmodule_perm
function openids_menu() {	
 
  $log['member/login'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
 
 
$log['member/index'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login2',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  $log['openids/save'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login_save',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  
  
   $log['openids/new'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login3',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  $log['facebook/answers'] = array(
    'title' => 'Facebook Friends Answered question',
    'page callback' => 'friends_answers',
    'access arguments' => array('Facebook Friends'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
   $log['edit'] = array(
    'title' => 'User',
    'page callback' => 'welcome_page',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  return $log;
  
}

function add_visit_points($uid = ''){
    $pexist = db_result(db_query("SELECT COUNT(pid) FROM {tbl_user_points} WHERE uid = '".$uid."' AND point_id = '8' AND DATE(date_added) = CURDATE()"));
    if($pexist == 0){
        // get_points() placed in quest_lite.module
        $points = get_points(9);
        db_query("INSERT INTO {tbl_user_points} SET uid = '%d', point_id = '%d', points = '%d'", $uid, 8, $points);
    }
}

