<?php
function openids_perm() {

  return array('Login','Facebook Friends');

} // function newmodule_perm
function openids_menu() {	
 
  $log['member/login'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
 
 
$log['member/index'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login2',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  $log['openids/save'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login_save',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  
  
   $log['openids/new'] = array(
    'title' => 'Login',
    'page callback' => 'openid_login3',
    'access arguments' => array('Login'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  $log['facebook/answers'] = array(
    'title' => 'Facebook Friends Answered question',
    'page callback' => 'friends_answers',
    'access arguments' => array('Facebook Friends'),
	   'type' => MENU_SUGGESTED_ITEM,
    'file' => 'openids.pages.inc',
  );
  
  
  
  return $log;
  
}


	