<?php
/*
function ExecuteQuery($Query, $Qrytype) {
  if (!empty($Query) && !empty($Qrytype)) {
    switch (strtolower($Qrytype)) {
      case "select":
        $Result = db_query($Query);
        if ($Result) {
          $ResultSet = array();
          while ($ResultSet1 = mysql_fetch_array($Result))
            $ResultSet[] = $ResultSet1;
          return $ResultSet;
        }
        else
          return false;
        break;
      case "update":
        $Result = db_query($Query);
        if ($Result) {
          $AffectedNums = mysql_affected_rows();
          return $AffectedNums;
        }
        else
          return false;
        break;
      case "norows":
        $Result = db_query($Query);
        if ($Result) {
          $Totalrows = mysql_num_rows($Result);
          return $Totalrows;
        }
        else
          return false;
        break;

      case "insert":
        $Result = db_query($Query);
        if ($Result) {
          $LastInsertedRow = mysql_insert_id();
          return $LastInsertedRow;
        }
        else
          return false;
        break;
      case "delete":
        $Result = db_query($Query);
        if ($Result)
          return true;
        else
          return false;
    }
  }
}*/