<?php

function location_province_list_iq () {
	return array (
		"NA" => t("An Najaf"),
		"AN" => t("Anbar"),
		"DQ" => t("Dhi Qar"),
		"DA" => t("Dihok"),
		"DI" => t("Diyala Province"),
		"BG" => t("Mayorality of Baghdad"),
		"MA" => t("Maysan"),
		"SD" => t("Muhafazat Salah ad Din"),
		"WA" => t("Muhafazat Wasit"),
		"AR" => t("Muḩāfaz̧at Arbīl"),
		"BB" => t("Muḩāfaz̧at Bābil"),
		"KA" => t("Muḩāfaz̧at Karbalā’"),
		"TS" => t("Muḩāfaz̧at Kirkūk"),
		"NI" => t("Muḩāfaz̧at Nīnawá"),
		"BA" => t("Muḩāfaz̧at al Başrah"),
		"MU" => t("Muḩāfaz̧at al Muthanná"),
		"QA" => t("Muḩāfaz̧at al Qādisīyah"),
		"SU" => t("Muḩāfaz̧at as Sulaymānīyah"),
	);
}
