<?php

# api functions
require_once "events.api.php";

/**
 * Implementation of hook_nodeapi()
 *
 * @param $node
 * @param $op
 * @param null $a3
 * @param null $a4
 */
function events_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
  switch ($op) {
    case 'delete' :
      events_del(array(
        'content_id' => $node->nid,
        'content_type' => 'node',
      ));
      // comments
      $result = db_query("
        (SELECT cid FROM comments WHERE nid = '%d') UNION
        (SELECT content_id FROM events WHERE
          content_type = 'comment' AND content_id NOT IN (SELECT cid FROM comments))", $node->nid);
      while ($cid = db_result($result)) {
        events_del(array(
          'content_id' => $cid,
          'content_type' => 'comment',
        ));
      }
      break;
  }
}

/**
 * Implementation of hook_user()
 *
 * @param $op
 * @param $edit
 * @param $account
 * @param null $category
 */
function events_user($op, &$edit, &$account, $category = NULL)
{
  switch ($op) {
    case 'delete' :
      events_del(array(
        'content_id' => $account->uid,
        'content_type' => 'user',
      ));
      events_del(array(
        'uid' => $account->uid,
      ));
      break;
  }
}

/**
 * @return array
 */
function events_menu() {
  $menu = array();

  $menu['events/event/%'] = array(
    'page callback' => 'events_preprocess_event',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // todo check below

  $menu['events/latest/%'] = array(
    'page callback' => 'events_get_latest',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * @param $type
 */
function events_preprocess_event($type) {
  $mtime = microtime(true);

  $vars = $_POST;
  unset($vars['q']);

  global $user;
  $uid = $user->uid;

  $messages = module_invoke_all('process_event', $type, $vars, $uid);

  $mtime = round(microtime(true) - $mtime, 4);

  exit(json_encode(array(
    'time' => $mtime,
    'messages' => $messages,
  )));
}

/**
 * @param $type
 */
function events_process_event($type, $vars, $uid) {
  if ('_' == $type[0]) {
    $p = array(
      'uid' => $uid,
      'type' => substr($type, 1),
    ) + $vars;
    events_del($p);
  } else {
    events_add($type, $vars, $uid);
  }
}










/**
 * Implementation of hook_comment()
 *
 * @param $a1
 * @param $op
 */
//function events_comment(&$a1, $op)
//{
//  switch ($op) {
//    case 'delete' :
//      events_del(array(
//        'content_id' => $a1->cid,
//        'content_type' => 'comment',
//      ));
//      break;
//  }
//}



/**
 * Implementation of hook_theme()
 *
 * @return array
 */
function events_theme()
{
  $theme = array();

  $theme['events'] = array(
    'arguments' => array(
      'items' => array(),
      'settings' => '',
    ),
    'preprocess functions' => array('events_stream_theme_preprocess'),
    'template' => 'events',
  );
  $theme['events_item'] = array(
    'arguments' => array(
      'item' => array(),
    ),
  );

  return $theme + events_theme_items();
}

/**
 * Preprocess for theme "events"
 *
 * @param $vars
 */
function events_stream_theme_preprocess(&$vars)
{
  drupal_add_js(drupal_get_path('module', 'events') . '/events.translate.js');
  if (isset($vars['settings']['update'])) {
    drupal_add_js(drupal_get_path('module', 'events') . '/events.js');
  }
  drupal_add_js(array('time' => array(
    'second' => t('second'),
    'seconds' => t('seconds'),
    'minute' => t('minute'),
    'minutes' => t('minutes'),
    'hour' => t('hour'),
    'hours' => t('hours'),
    'day' => t('day'),
    'days' => t('days'),
    'week' => t('week'),
    'weeks' => t('weeks'),
    'month' => t('month'),
    'months' => t('months'),
    'year' => t('year'),
    'years' => t('years'),
    'ago' => t('ago'),
    'just now' => t('just now'),
  )), 'setting');
}

/**
 * Implementation of hook_preprocess_page()
 *
 * @param $vars
 */
function events_preprocess_page(&$vars)
{
  drupal_add_js(drupal_get_path('module', 'events') . '/events.ajax.js');
}

/**
 * Implementation of hook_block
 *
 * @param string $op
 * @param int $delta
 * @param array $edit
 * @return mixed
 */
function events_block($op = 'list', $delta = 0, $edit = array())
{
  switch ($op) {
    case 'list':
      $blocks['events-front'] = array(
        'info' => t('Front Events'),
      );
      return $blocks;
    case 'view':
      switch ($delta) {
        case 'events-front' :
          $block['subject'] = t('HAPPENING NOW');
          $block['content'] = theme('events', events_get(array(
            'q' => array(
              events_build_query(array('exclude' => array('type' => array('user_profile', 'taxonomy'),))),
            )
          )), array('update' => TRUE));
          break;
      }
      return $block;
  }
}


/**
 * @param $item
 * @return mixed|string
 */
function theme_events_item($item)
{
  static $themes = NULL;

  if (is_null($themes)) {
    $themes = module_invoke_all('events_info');
  }

  $classes = array();
  $classes[] = 'activity-stream';
  $classes[] = 'msg';
  $classes[] = 'msg-' . $item['type'];
  $classes[] = 'uid-' . $item['uid'];
  $classes[] = 'content_id-' . $item['content_id'];
  $classes[] = 'content_type-' . $item['content_type'];

  return isset($themes[$item['type']]) ?
    '<div name="'.$item['id'].'" id="msg-' . $item['id'] . '" class="' . implode(' ', $classes) . '">' .
      theme($themes[$item['type']], $item) .
      '</div>'
    : '';
}

/**
 * Function to add the custom themes for item types
 *
 * TODO
 *
 * @return array
 */
function events_theme_items()
{
  $theme = array();

  $items = module_invoke_all('events_info');

  foreach ($items as $event => $themename) {
    $theme[$themename] = array(
      'arguments' => array(
        'item' => array(),
      ),
      'preprocess functions' => array('event_item_theme_preprocess', $themename.'_theme_preprocess'),
      'file' => 'events.theme.inc',
      'template' => 'templates/event-' . $event,
    );
  }

  return $theme;
}

/**
 * @return array
 */
function events_events_info()
{
  return array(
    'poll_create' => 'event_poll_create',
    'poll_vote' => 'event_poll_vote',
    'forum_create' => 'event_forum_create',
    'forum_comment' => 'event_forum_comment',
    'forum_vote' => 'event_forum_vote',
    'forum_comment_vote' => 'event_forum_comment_vote',
    'user_profile' => 'event_user_profile',
    'user_badge' => 'event_user_badge',
    'user_follow' => 'event_user_follow',
    'taxonomy' => 'event_taxonomy',
  );
}


/**
 * API function : get events
 *
 * @param int $count
 * @param array $p
 * @return array
 */
function events_get_latest($id)
{
  $items = array();

  print json_encode(
    events_get(array(
      'q' => array(
        events_build_query(array('exclude' => array('type' => array('user_profile', 'taxonomy'),))),
      ),
      'update' => $id,
    ))
  );

  # fetch results
//  static $users = array();
//  $result = db_query("SELECT * FROM {events} WHERE id > '%d' ORDER BY date_added ASC", $id);
//  while ($item = db_fetch_array($result)) {
//    $item['vars'] = unserialize($item['vars']);
//    if (!$users[$item['uid']]) {
//      $users[$item['uid']] = user_load($item['uid']);
//    }
//    $item['account'] = $users[$item['uid']];
//    $item['timestamp'] = strtotime($item['date_added']);
//    if (function_exists('time_interval')) {
//      $item['date_added'] = time_interval($item['date_added']);
//    }
//    $items[$item['id']] = theme('events_item', $item);
//  }
//
//  print json_encode($items);
  exit;
}

/**
 * @param $date
 * @return string
 */
function time_interval($date) {
  # dates/interval
  $date_now = new DateTime("now");
  $date = new DateTime($date);
  $interval = $date->diff($date_now);
  # convert to string
  if ($interval->y != 0) {
    return $interval->y . ' year' . ($interval->y > 1 ? 's' : '') . ' ago';
  }
  if ($interval->m != 0) {
    return $interval->m . ' month' . ($interval->m > 1 ? 's' : '') . ' ago';
  }
  if ($interval->d != 0) {
    return $interval->d . ' day' . ($interval->d > 1 ? 's' : '') . ' ago';
  }
  if ($interval->h != 0) {
    return $interval->h . ' hour' . ($interval->h > 1 ? 's' : '') . ' ago';
  }
  if ($interval->i != 0) {
    return $interval->i . ' minute' . ($interval->i > 1 ? 's' : '') . ' ago';
  }
  return 'just now';
}