<?php

/**
 * include admin file
 */
include_once "bitcoin_api.admin.inc";

/**
 * include required class
 */
require_once "lib/Coinbase.php";

/**
 * @return array
 */
function bitcoin_api_donations() {
  return array('bitcoin_api' => t('Bitcoin'));
}

/**
 * Implementation of hook_donation_make()
 *
 * @param $op_id
 */
function bitcoin_api_donation_make($op_id) {
  if ($record = donations_record($op_id)) {
    $apikey = variable_get('bitcoin_api_apikey', '');
    $coinbase = new Coinbase($apikey);
    $response = $coinbase->createButton(t('Donation to ') . variable_get('site_name', 'Heard Mentality'), $record->amount, $record->currency, $record->id, array(
        'description'  => t('Donation to ') . variable_get('site_name', 'Heard Mentality'),
        'choose_price' => TRUE,
      ));
    db_query("UPDATE {donations} SET token = '%s' WHERE id = '%d'", $response->button->code, $record->id);
    drupal_goto("https://coinbase.com/checkouts/" . $response->button->code);
  }
}

/**
 *
 */
function bitcoin_api_donations_cancel() {
  if ($data = bitcoin_api_json_decode()) {
    $op_id = $data['order']['custom'];
    if ($record = donations_record($op_id)) {
      return $record;
    }
  }
  return FALSE;
}

/**
 *
 */
function bitcoin_api_donations_success() {
  if ($data = bitcoin_api_json_decode()) {
    $op_id = $data['order']['custom'];
    if ($record = donations_record($op_id)) {
      db_query("UPDATE {donations} SET transaction_id = '%d' WHERE id = '%d'", $data['order']['transaction']['hash'], $record->id);
      drupal_set_message(t('Thank you for the donation!'));
      return $record;
    }
  }
  return FALSE;
}

/**
 * @return mixed
 */
function bitcoin_api_json_decode() {
  $content = file_get_contents('php://input');

  //  $content = '{
  //    "order": {
  //        "id": "5RTQNACF",
  //        "created_at": "2012-12-09T21:23:41-08:00",
  //        "status": "completed",
  //        "total_btc": {
  //            "cents": 100000000,
  //            "currency_iso": "BTC"
  //        },
  //        "total_native": {
  //            "cents": 1253,
  //            "currency_iso": "USD"
  //        },
  //        "custom": "5",
  //        "button": {
  //            "type": "buy_now",
  //            "name": "Alpaca Socks",
  //            "description": "The ultimate in lightweight footwear",
  //            "id": "5d37a3b61914d6d0ad15b5135d80c19f"
  //        },
  //        "transaction": {
  //            "id": "514f18b7a5ea3d630a00000f",
  //            "hash": "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
  //            "confirmations": 0
  //        }
  //    }
  //  }';

  return json_decode($content, TRUE);
}
