<?php


function location_cities_list_kh_1() {
  return array(
    "1822207" => t("Sisophon"),
    "1830194" => t("Paoy Pet"),
  );
}


function location_cities_list_kh_2() {
  return array(
    "1831797" => t("Battambang"),
  );
}


function location_cities_list_kh_3() {
  return array(
    "1831173" => t("Kampong Cham"),
  );
}


function location_cities_list_kh_4() {
  return array(
    "1831167" => t("Kampong Chhnang"),
  );
}


function location_cities_list_kh_5() {
  return array(
    "1831133" => t("Kampong Speu"),
  );
}


function location_cities_list_kh_6() {
  return array(
    "1831125" => t("Kampong Thom"),
  );
}


function location_cities_list_kh_7() {
  return array(
    "1831112" => t("Kampot"),
  );
}


function location_cities_list_kh_8() {
  return array(
    "1821935" => t("Ta Khmau"),
  );
}


function location_cities_list_kh_23() {
  return array();
}


function location_cities_list_kh_9() {
  return array(
    "1830468" => t("Koh Kong"),
  );
}


function location_cities_list_kh_10() {
  return array(
    "1830564" => t("Kratie"),
  );
}


function location_cities_list_kh_11() {
  return array();
}


function location_cities_list_kh_24() {
  return array(
    "1830205" => t("Pailin"),
  );
}


function location_cities_list_kh_12() {
  return array(
    "1821306" => t("Phnom Penh"),
  );
}


function location_cities_list_kh_18() {
  return array(
    "1831142" => t("Sihanoukville"),
  );
}


function location_cities_list_kh_13() {
  return array(
    "1830098" => t("Tbeng Meanchey"),
  );
}


function location_cities_list_kh_14() {
  return array(
    "1822610" => t("Prey Veng"),
  );
}


function location_cities_list_kh_15() {
  return array(
    "1822768" => t("Pursat"),
  );
}


function location_cities_list_kh_16() {
  return array(
    "1830377" => t("Lumphat"),
    "1831732" => t("Ban Lung"),
  );
}


function location_cities_list_kh_17() {
  return array(
    "1822214" => t("Siem Reap"),
  );
}


function location_cities_list_kh_19() {
  return array(
    "1822029" => t("Stung Treng"),
  );
}


function location_cities_list_kh_20() {
  return array(
    "1821993" => t("Svay Rieng"),
  );
}


function location_cities_list_kh_21() {
  return array(
    "1821940" => t("Takeo"),
    "1822906" => t("Phumi Veal Sre"),
  );
}


function location_cities_list_kh_22() {
  return array(
    "1825093" => t("Samraong"),
  );
}
