<?php


function location_cities_list_no_02() {
  return array();
}


function location_cities_list_no_09() {
  return array(
    "3162955" => t("Arendal"),
  );
}


function location_cities_list_no_06() {
  return array(
    "3149563" => t("Kongsberg"),
    "3159016" => t("Drammen"),
  );
}


function location_cities_list_no_20() {
  return array();
}


function location_cities_list_no_04() {
  return array(
    "3154084" => t("Hamar"),
  );
}


function location_cities_list_no_12() {
  return array(
    "3161732" => t("Bergen"),
    "3336587" => t("Askoy"),
    "6697344" => t("Ytrebygda"),
  );
}


function location_cities_list_no_15() {
  return array(
    "3145580" => t("Molde"),
    "3149312" => t("Kristiansund"),
    "3163392" => t("Alesund"),
  );
}


function location_cities_list_no_17() {
  return array(
    "3136947" => t("Steinkjer"),
  );
}


function location_cities_list_no_18() {
  return array(
    "3145614" => t("Mo i Rana"),
    "3160881" => t("Bodo"),
  );
}


function location_cities_list_no_05() {
  return array(
    "3147474" => t("Lillehammer"),
    "3155573" => t("Gjovik"),
  );
}


function location_cities_list_no_03() {
  return array(
    "3143244" => t("Oslo"),
  );
}


function location_cities_list_no_11() {
  return array(
    "3137115" => t("Stavanger"),
    "3140321" => t("Sandnes"),
    "3153623" => t("Haugesund"),
  );
}


function location_cities_list_no_14() {
  return array();
}


function location_cities_list_no_16() {
  return array(
    "3133880" => t("Trondheim"),
  );
}


function location_cities_list_no_08() {
  return array(
    "3139075" => t("Skien"),
    "3142657" => t("Porsgrunn"),
  );
}


function location_cities_list_no_19() {
  return array(
    "3133895" => t("Tromso"),
    "3153823" => t("Harstad"),
  );
}


function location_cities_list_no_10() {
  return array(
    "3149318" => t("Kristiansand"),
  );
}


function location_cities_list_no_07() {
  return array(
    "3134331" => t("Tonsberg"),
    "3140390" => t("Sandefjord"),
    "3148129" => t("Larvik"),
    "3151770" => t("Horten"),
  );
}


function location_cities_list_no_01() {
  return array(
    "3140084" => t("Sarpsborg"),
    "3145375" => t("Moss"),
    "3154209" => t("Halden"),
    "3156529" => t("Fredrikstad"),
  );
}
