<?php


function location_cities_list_ge_ab() {
  return array(
    "611847" => t("Sokhumi"),
  );
}


function location_cities_list_ge_aj() {
  return array(
    "613762" => t("Kobuleti"),
    "615532" => t("Batumi"),
  );
}


function location_cities_list_ge_gu() {
  return array(
    "612536" => t("Ozurget'i"),
  );
}


function location_cities_list_ge_im() {
  return array(
    "610864" => t("Zestap'oni"),
    "613607" => t("K'ut'aisi"),
    "824288" => t("Tsqaltubo"),
  );
}


function location_cities_list_ge_tb() {
  return array(
    "611717" => t("Tbilisi"),
  );
}


function location_cities_list_ge_ka() {
  return array(
    "611694" => t("T'elavi"),
  );
}


function location_cities_list_ge_kk() {
  return array(
    "612287" => t("Rust'avi"),
    "613074" => t("Marneuli"),
  );
}


function location_cities_list_ge_mm() {
  return array();
}


function location_cities_list_ge_rl() {
  return array();
}


function location_cities_list_ge_sz() {
  return array(
    "610824" => t("Zugdidi"),
    "612053" => t("Senaki"),
    "612366" => t("P'ot'i"),
  );
}


function location_cities_list_ge_sj() {
  return array(
    "615860" => t("Akhalts'ikhe"),
  );
}


function location_cities_list_ge_sk() {
  return array(
    "613988" => t("Khashuri"),
    "614455" => t("Gori"),
  );
}
