<?php


function location_cities_list_kp_04() {
  return array(
    "2043572" => t("Kanggye-si"),
  );
}


function location_cities_list_kp_07() {
  return array(
    "1866923" => t("Wonsan"),
    "1867927" => t("T'ongch'on-up"),
    "1875632" => t("Kosan"),
    "1877148" => t("Hoeyang"),
    "1879672" => t("Anbyon-up"),
  );
}


function location_cities_list_kp_09() {
  return array(
    "2042267" => t("Onsong"),
    "2042498" => t("Nanam"),
    "2042503" => t("Namyang-dong"),
    "2042738" => t("Musan-up"),
    "2042987" => t("Kyongsong"),
    "2043484" => t("Kilju"),
    "2044091" => t("Hoeryong"),
    "2044757" => t("Chongjin"),
    "2045311" => t("Aoji-ri"),
  );
}


function location_cities_list_kp_08() {
  return array(
    "1871484" => t("Samho-rodongjagu"),
    "1875588" => t("Kowon-up"),
    "1877030" => t("Hungnam"),
    "1877449" => t("Hamhung"),
    "2038854" => t("Yuktae-dong"),
    "2042249" => t("Yonggwang-up"),
    "2043677" => t("Iwon-up"),
    "2044050" => t("Hongwon"),
  );
}


function location_cities_list_kp_06() {
  return array(
    "1869446" => t("Songnim"),
    "1870883" => t("Sariwon"),
    "1876873" => t("Hwangju-up"),
    "1877046" => t("Hukkyo-ri"),
    "1879682" => t("Anak"),
  );
}


function location_cities_list_kp_05() {
  return array(
    "1866569" => t("Yonan-up"),
    "1873172" => t("Ongjin"),
    "1876373" => t("Kaesong"),
    "1877615" => t("Haeju"),
    "1879029" => t("Changyon"),
    "1879487" => t("Chaeryong-up"),
    "1879544" => t("Ayang-ni"),
  );
}


function location_cities_list_kp_13() {
  return array(
    "2040674" => t("Sonbong"),
    "2042645" => t("Najin"),
  );
}


function location_cities_list_kp_03() {
  return array(
    "1875107" => t("Kusong"),
    "1875506" => t("Kujang-up"),
    "1878389" => t("Chongju"),
    "2039623" => t("Uiju"),
    "2040893" => t("Sinuiju"),
    "2041533" => t("Sakchu-up"),
  );
}


function location_cities_list_kp_02() {
  return array(
    "1870413" => t("Sil-li"),
    "1870742" => t("Sinanju"),
    "1871871" => t("P'yongsong"),
    "1873757" => t("Namp'o"),
    "1879613" => t("Anju"),
  );
}


function location_cities_list_kp_01() {
  return array(
    "1868998" => t("Sungho 1-tong"),
    "1869021" => t("Sunan"),
    "1871859" => t("Pyongyang"),
    "1876153" => t("Kangdong-up"),
    "1877872" => t("Chunghwa"),
  );
}


function location_cities_list_kp_10() {
  return array(
    "2043531" => t("Kapsan-up"),
    "2043835" => t("Hyesan-dong"),
    "2043837" => t("Hyesan-si"),
  );
}
