<?php


function location_cities_list_bb_01() {
  return array();
}


function location_cities_list_bb_02() {
  return array();
}


function location_cities_list_bb_03() {
  return array();
}


function location_cities_list_bb_04() {
  return array();
}


function location_cities_list_bb_05() {
  return array();
}


function location_cities_list_bb_06() {
  return array();
}


function location_cities_list_bb_07() {
  return array();
}


function location_cities_list_bb_08() {
  return array(
    "3374036" => t("Bridgetown"),
  );
}


function location_cities_list_bb_09() {
  return array();
}


function location_cities_list_bb_10() {
  return array();
}


function location_cities_list_bb_11() {
  return array();
}
