<?php


function location_cities_list_ci_16() {
  return array(
    "2288118" => t("Affery"),
    "2293107" => t("Akoupe"),
    "2293268" => t("Agboville"),
    "2293342" => t("Adzope"),
  );
}


function location_cities_list_ci_17() {
  return array(
    "2280376" => t("Touba"),
  );
}


function location_cities_list_ci_09() {
  return array(
    "2281120" => t("Tabou"),
    "2281951" => t("Sassandra"),
    "2282006" => t("San-Pedro"),
    "2598243" => t("Soubre"),
  );
}


function location_cities_list_ci_10() {
  return array(
    "2283016" => t("Odienne"),
  );
}


function location_cities_list_ci_06() {
  return array(
    "2284647" => t("Man"),
    "2290462" => t("Danane"),
    "2291666" => t("Biankouma"),
    "2292179" => t("Bangolo"),
  );
}


function location_cities_list_ci_18() {
  return array(
    "2282827" => t("Oume"),
    "2288829" => t("Gagnoa"),
  );
}


function location_cities_list_ci_02() {
  return array(
    "2280045" => t("Vavoua"),
    "2287790" => t("Issia"),
    "2290486" => t("Daloa"),
  );
}


function location_cities_list_ci_07() {
  return array(
    "2279755" => t("Yamoussoukro"),
    "2280316" => t("Toumodi"),
  );
}


function location_cities_list_ci_01() {
  return array(
    "2280761" => t("Tiassale"),
    "2290582" => t("Dabou"),
    "2291580" => t("Bingerville"),
    "2292852" => t("Anyama"),
    "2293521" => t("Abobo"),
    "2293538" => t("Abidjan"),
  );
}


function location_cities_list_ci_12() {
  return array(
    "2279172" => t("Zuenoula"),
    "2290964" => t("Bouafle"),
  );
}


function location_cities_list_ci_19() {
  return array(
    "2287958" => t("Guiglo"),
    "2289549" => t("Duekoue"),
  );
}


function location_cities_list_ci_05() {
  return array(
    "2293260" => t("Agnibilekrou"),
    "2293549" => t("Abengourou"),
  );
}


function location_cities_list_ci_11() {
  return array(
    "2289983" => t("Dimbokro"),
    "2290412" => t("Daoukro"),
    "2291113" => t("Bongouanou"),
    "2292755" => t("Arrah"),
  );
}


function location_cities_list_ci_13() {
  return array(
    "2288115" => t("Grand-Bassam"),
    "2291087" => t("Bonoua"),
    "2293428" => t("Adiake"),
    "2293507" => t("Aboisso"),
  );
}


function location_cities_list_ci_03() {
  return array(
    "2280589" => t("Tengrela"),
    "2286304" => t("Korhogo"),
    "2289049" => t("Ferkessedougou"),
    "2290836" => t("Boundiali"),
  );
}


function location_cities_list_ci_15() {
  return array(
    "2285449" => t("Lakota"),
    "2289887" => t("Divo"),
  );
}


function location_cities_list_ci_04() {
  return array(
    "2282178" => t("Sakassou"),
    "2287298" => t("Katiola"),
    "2290956" => t("Bouake"),
    "2291779" => t("Beoumi"),
  );
}


function location_cities_list_ci_14() {
  return array(
    "2284589" => t("Mankono"),
    "2596934" => t("Seguela"),
  );
}


function location_cities_list_ci_08() {
  return array(
    "2280995" => t("Tanda"),
    "2281606" => t("Sinfra"),
    "2290849" => t("Bouna"),
    "2291136" => t("Bondoukou"),
  );
}
