<?php


function location_cities_list_sl_e() {
  return array(
    "2404041" => t("Segbwema"),
    "2407656" => t("Koidu"),
    "2407790" => t("Kenema"),
  );
}


function location_cities_list_sl_n() {
  return array(
    "2404433" => t("Port Loko"),
    "2406407" => t("Makeni"),
    "2406916" => t("Lunsar"),
    "2408329" => t("Kabala"),
  );
}


function location_cities_list_sl_s() {
  return array(
    "2410048" => t("Bo"),
  );
}


function location_cities_list_sl_w() {
  return array(
    "2403094" => t("Waterloo"),
    "2409306" => t("Freetown"),
  );
}
