<?php


function location_cities_list_gt_av() {
  return array(
    "3590316" => t("San Cristobal Verapaz"),
    "3591676" => t("Panzos"),
    "3598119" => t("Coban"),
    "3598415" => t("Chisec"),
  );
}


function location_cities_list_gt_bv() {
  return array(
    "3590616" => t("Salama"),
  );
}


function location_cities_list_gt_cm() {
  return array(
    "3588476" => t("Tecpan Guatemala"),
    "3590529" => t("San Andres Itzapa"),
    "3591512" => t("Patzun"),
    "3591523" => t("Patzicia"),
    "3596041" => t("El Tejar"),
    "3598034" => t("Comalapa"),
    "3598572" => t("Chimaltenango"),
  );
}


function location_cities_list_gt_cq() {
  return array(
    "3595783" => t("Esquipulas"),
    "3598465" => t("Chiquimula"),
  );
}


function location_cities_list_gt_pr() {
  return array(
    "3590406" => t("Sanarate"),
  );
}


function location_cities_list_gt_es() {
  return array(
    "3589289" => t("Santa Lucia Cotzumalguapa"),
    "3591060" => t("Puerto San Jose"),
    "3591093" => t("Pueblo Nuevo Tiquisate"),
    "3591833" => t("Palin"),
    "3594575" => t("La Gomera"),
    "3595803" => t("Escuintla"),
  );
}


function location_cities_list_gt_gu() {
  return array(
    "3587902" => t("Villa Nueva"),
    "3587923" => t("Villa Canales"),
    "3589452" => t("Santa Catarina Pinula"),
    "3589646" => t("San Pedro Ayampuc"),
    "3589885" => t("San Juan Sacatepequez"),
    "3589977" => t("San Jose Pinula"),
    "3591415" => t("Petapa"),
    "3591851" => t("Palencia"),
    "3592519" => t("Mixco"),
    "3595714" => t("Fraijanes"),
    "3598132" => t("Guatemala City"),
    "3598529" => t("Chinautla"),
    "3599735" => t("Amatitlan"),
  );
}


function location_cities_list_gt_hu() {
  return array(
    "3595248" => t("Jacaltenango"),
    "3595416" => t("Huehuetenango"),
  );
}


function location_cities_list_gt_iz() {
  return array(
    "3591062" => t("Puerto Barrios"),
    "3592362" => t("Morales"),
    "3597078" => t("El Estor"),
  );
}


function location_cities_list_gt_ja() {
  return array(
    "3595237" => t("Jalapa"),
  );
}


function location_cities_list_gt_ju() {
  return array(
    "3595069" => t("Jutiapa"),
    "3599639" => t("Asuncion Mita"),
  );
}


function location_cities_list_gt_qz() {
  return array(
    "3590979" => t("Quetzaltenango"),
    "3591997" => t("Ostuncalco"),
    "3594703" => t("La Esperanza"),
    "3596644" => t("El Palmar"),
    "3598073" => t("Colomba"),
    "3598122" => t("Coatepeque"),
    "3599069" => t("Cantel"),
  );
}


function location_cities_list_gt_re() {
  return array(
    "3590858" => t("Retalhuleu"),
    "3592105" => t("Nuevo San Carlos"),
  );
}


function location_cities_list_gt_sa() {
  return array(
    "3588653" => t("Sumpango"),
    "3589101" => t("Santiago Sacatepequez"),
    "3589253" => t("Santa Maria de Jesus"),
    "3589852" => t("San Lucas Sacatepequez"),
    "3595171" => t("Jocotenango"),
    "3598128" => t("Ciudad Vieja"),
    "3599699" => t("Antigua Guatemala"),
    "3599788" => t("Alotenango"),
  );
}


function location_cities_list_gt_sm() {
  return array(
    "3589626" => t("San Pedro Sacatepequez"),
    "3589805" => t("San Marcos"),
    "3598025" => t("Comitancillo"),
  );
}


function location_cities_list_gt_sr() {
  return array(
    "3597804" => t("Cuilapa"),
    "3599582" => t("Barberena"),
  );
}


function location_cities_list_gt_so() {
  return array(
    "3588698" => t("Solola"),
    "3589105" => t("Santiago Atitlan"),
    "3592286" => t("Nahuala"),
  );
}


function location_cities_list_gt_su() {
  return array(
    "3589671" => t("San Pablo Jocopilas"),
    "3592609" => t("Mazatenango"),
    "3598678" => t("Chicacao"),
  );
}


function location_cities_list_gt_to() {
  return array(
    "3588258" => t("Totonicapan"),
    "3590219" => t("San Francisco El Alto"),
    "3592483" => t("Momostenango"),
  );
}


function location_cities_list_gt_za() {
  return array(
    "3587587" => t("Zacapa"),
    "3595560" => t("Gualan"),
  );
}


function location_cities_list_gt_pe() {
  return array(
    "3590389" => t("San Benito"),
    "3591181" => t("Poptun"),
    "3595725" => t("Flores"),
  );
}


function location_cities_list_gt_qc() {
  return array(
    "3589404" => t("Santa Cruz del Quiche"),
    "3592237" => t("Nebaj"),
    "3598655" => t("Chichicastenango"),
  );
}
