<?php


function location_cities_list_td_bg() {
  return array(
    "2427336" => t("Moussoro"),
  );
}


function location_cities_list_td_ba() {
  return array(
    "2426370" => t("Oum Hadjer"),
    "2436400" => t("Ati"),
  );
}


function location_cities_list_td_bo() {
  return array();
}


function location_cities_list_td_cb() {
  return array(
    "2427123" => t("N'Djamena"),
    "2433055" => t("Dourbali"),
  );
}


function location_cities_list_td_en() {
  return array(
    "244128" => t("Fada"),
  );
}


function location_cities_list_td_gr() {
  return array(
    "2427637" => t("Mongo"),
    "2435124" => t("Bitkine"),
  );
}


function location_cities_list_td_hl() {
  return array(
    "2428228" => t("Massakory"),
    "2428231" => t("Massaguet"),
  );
}


function location_cities_list_td_ka() {
  return array(
    "2428394" => t("Mao"),
  );
}


function location_cities_list_td_lc() {
  return array();
}


function location_cities_list_td_lo() {
  return array(
    "2427455" => t("Moundou"),
    "2435508" => t("Benoy"),
  );
}


function location_cities_list_td_lr() {
  return array(
    "2433437" => t("Doba"),
  );
}


function location_cities_list_td_ma() {
  return array(
    "2429605" => t("Koumra"),
  );
}


function location_cities_list_td_me() {
  return array(
    "2434910" => t("Bongor"),
  );
}


function location_cities_list_td_mo() {
  return array(
    "2426240" => t("Pala"),
    "2428042" => t("Mboursou Lere"),
  );
}


function location_cities_list_td_mc() {
  return array(
    "2425791" => t("Sagh"),
    "2429344" => t("Kyabe"),
  );
}


function location_cities_list_td_od() {
  return array(
    "245785" => t("Abeche"),
  );
}


function location_cities_list_td_sa() {
  return array(
    "245338" => t("Am Timan"),
  );
}


function location_cities_list_td_si() {
  return array();
}


function location_cities_list_td_ta() {
  return array(
    "2429296" => t("Lai"),
    "2430506" => t("Kelo"),
  );
}


function location_cities_list_td_ti() {
  return array();
}


function location_cities_list_td_nd() {
  return array();
}


function location_cities_list_td_wf() {
  return array();
}
